test/e2e/helm/kuma_helm_upgrade_multizone.go, test/e2e/helm/kuma_helm_upgrade_standalone.go, test/e2e_env/universal/compatibility/dp_compatibility.go, test/e2e_env/universal/universal_suite_test.go, test/framework/config.go, test/framework/universal_app.go, test/framework/versions/suite_test.go, test/framework/versions/versions.go, test/framework/versions/versions_test.go
Partial backport of https://github.com/kumahq/kuma/pull/8410
=> test(e2e): fix previous version installs

pkg/plugins/runtime/k8s/controllers/meshservice_controller.go, pkg/plugins/runtime/k8s/controllers/meshservice_controller_test.go, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/01.meshservice.yaml, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/02.meshservice.yaml, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/headless.meshservice.yaml, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/headless.resources.yaml, pkg/plugins/runtime/k8s/metadata/annotations.go
=> feat(MeshService): tag with headlessness, add pod-name/pod-index labels

pkg/plugins/policies/meshpassthrough/api/v1alpha1/testdata/full-invalid.output.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/testdata/valid.input.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/validator.go, test/e2e_env/kubernetes/meshpassthrough/meshpassthrough.go
=> feat(meshpassthrough): allow only proxyType sidecar

pkg/core/resources/apis/hostnamegenerator/hostname/generator.go, pkg/core/resources/apis/meshexternalservice/hostname/generator.go, pkg/core/resources/apis/meshservice/hostname/generator.go
Not sure what it was copy paste.
Added `.Namespace` and `.Zone` resolution.
xref https://github.com/kumahq/kuma/pull/10476
https://github.com/kumahq/kuma/pull/10478/files#r1642600471 
=> feat(hostnamegenerator): add zone and namespace variables

.github/dependabot.yml
=> chore(dependabot): set dependabot to run on monday

test/e2e_env/kubernetes/kubernetes_suite_test.go, test/e2e_env/universal/universal_suite_test.go
=> ci(meshexternalservice): skip ipv6 on meshexternalservice

mk/build.mk
=> fix(build): set envoy version conditionally

pkg/plugins/runtime/k8s/webhooks/validation.go
I.e. we're getting `spec.spec...` on Kubernetes
=> fix(validation): don't prefix validation errors with `spec.` for core plugin resources

UPGRADE.md, pkg/core/validators/common_validators.go, pkg/core/validators/common_validators_test.go, pkg/plugins/policies/meshfaultinjection/api/v1alpha1/validator_test.go, test/e2e_env/kubernetes/meshfaultinjection/api.go
=> fix(kuma-cp): validate the bandwidth strictly

test/e2e_env/kubernetes/kubernetes_suite_test.go, test/e2e_env/multizone/meshservice/status.go, test/e2e_env/multizone/multizone_suite_test.go, test/e2e_env/universal/universal_suite_test.go, test/framework/config.go, test/framework/envs/multizone/env.go, test/framework/k8s_cluster.go, test/framework/universal_cluster.go
IPV6 works by setting CIDR for our VIPs to IPV6. It turned out to be just a matter of test configuration. I deleted CIDR in E2E config, because it sounds like an overkill.
Fix #10471
=> test(e2e): ipv6 for mesh service and mesh external service

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshservices.yaml, docs/generated/openapi.yaml, docs/generated/raw/crds/kuma.io_meshservices.yaml, pkg/api-server/testdata/resources/crud/list_meshservices.golden.json, pkg/api-server/testdata/resources/crud/list_meshservices.input.yaml, pkg/api-server/testdata/resources/crud/put_meshservice_01.golden.json, pkg/core/resources/apis/meshservice/api/v1alpha1/meshservice.go, pkg/core/resources/apis/meshservice/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshservice/k8s/crd/kuma.io_meshservices.yaml, pkg/plugins/policies/core/xds/meshroute/listeners.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/runtime/k8s/controllers/meshservice_controller.go, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/01.meshservice.yaml, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/02.meshservice.yaml, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/headless.meshservice.yaml, pkg/test/resources/builders/meshservice_builder.go, pkg/test/store/store_test_template.go, pkg/xds/topology/outbound_test.go, test/e2e_env/multizone/meshservice/status.go, test/e2e_env/universal/meshservice/meshservice.go
Rename protocol to appprotocol. We decided on appprotocol in this madr https://github.com/kumahq/kuma/blob/master/docs/madr/decisions/039-meshservice-api.md
but we didn't get to rename it. 
=> feat(meshservice): rename protocol to appprotocol

test/e2e_env/multizone/sync/sync.go
Only part of this test was adjusted in #10426
=> test(e2e): fix race in sync + available services test

pkg/kds/v2/store/sync.go
Previously:
```
│ 2024-06-19T11:55:46.828Z    INFO    kds-delta-zone    deleting a resource since it's no longer available in the upstream    {"type": "MeshRetry", "name": "mesh-retry-all-default-4266fddczv5d2fvv.kuma-system", "mesh": "default"}                                                                                                                                                                                                                                                        │
│ 2024-06-19T11:55:46.853Z    INFO    kds-delta-zone    creating a new resource from upstream    {"type": "MeshRetry", "name": "mesh-retry-all-default-d4zvfwwxf4x44z76.kuma-system", "mesh": "default"}    
```
When we change how resource name hash is computed, we will need to recreate resources in other …
=> feat(kds): create first, then remove synced resources

pkg/core/xds/types.go, pkg/plugins/policies/core/xds/meshroute/clusters.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshexternalservice.clusters.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls-and-custom-settings.clusters.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls-and-skipall.clusters.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls.clusters.golden.yaml, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/default-meshexternalservice.clusters.golden.yaml, pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go, pkg/xds/context/mesh_context_builder.go, pkg/xds/envoy/clusters/v3/client_side_tls_configurer.go, pkg/xds/generator/egress/external_services_generator.go, pkg/xds/generator/egress/generator_test.go, pkg/xds/generator/egress/testdata/01.externalservice-only.golden.yaml, pkg/xds/generator/egress/testdata/input/01.externalservice-only.yaml, test/e2e_env/kubernetes/meshexternalservice/meshexternalservice.go
* fix setting tls context for MeshExternalService
* take the correct protocol for MeshExternalService
* do not set tls context when tls disabled
* use correct way of checking protocol for egress
=> fix(meshexternalservice): correctly set tls context and protocol

test/e2e_env/multizone/meshservice/connectivity.go, test/e2e_env/multizone/meshservice/sync.go, test/e2e_env/multizone/multizone_suite_test.go
E2E tests improvements for MeshService.
I extracted connectivity part from the sync part.
The connectivity part now checks not only uni -> kube, uni -> uni, but all combinations. It's a "mirror" of `e2e/connectivity/connectivity`
=> test(e2e): mesh service connectivity

test/framework/versions/versions.go, test/framework/versions/versions_test.go
=> test(upgrades): skip versions if does not have release date

pkg/plugins/runtime/k8s/util/util.go, pkg/plugins/runtime/k8s/util/util_test.go
`kuma.io/mesh` annotation was deprecated. It is but not for namespace for some reason. It should be consistent for all objects.
=> fix(k8s): take mesh from label of the namespace

pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/name-too-long.input.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/name-too-long.output.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator_test.go, pkg/core/resources/apis/meshservice/api/v1alpha1/suite_test.go, pkg/core/resources/apis/meshservice/api/v1alpha1/validator.go, pkg/core/resources/apis/meshservice/api/v1alpha1/validator_test.go, pkg/core/resources/model/rest/unmarshaller.go, pkg/core/validators/common_validators.go, pkg/plugins/runtime/k8s/controllers/meshservice_controller.go, pkg/test/resources/validators/validation.go, pkg/util/k8s/name_converter.go
=> feat(Mesh*Service): validate name length

pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/validate.go, pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/validate_test.go
I don't think there is a valid case for an empty template.
=> feat(hostnamegenerator): prevent template being empty

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml, deployments/charts/kuma/templates/_helpers.tpl
`KUMA_RUNTIME_KUBERNETES_SERVICE_ACCOUNT_NAME` was deprecated here
https://github.com/kumahq/kuma/pull/6505
but it was not changed in the default helm installation therefore we print a warning on a default installation.
=> chore(k8s): use allowed users instead of deprecated env

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshexternalservices.yaml, deployments/charts/kuma/crds/kuma.io_meshservices.yaml, docs/generated/openapi.yaml, docs/generated/raw/crds/kuma.io_meshexternalservices.yaml, docs/generated/raw/crds/kuma.io_meshservices.yaml, pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/hostnamegenerator.go, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshexternalservice/k8s/crd/kuma.io_meshexternalservices.yaml, pkg/core/resources/apis/meshservice/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshservice/k8s/crd/kuma.io_meshservices.yaml
In the future if we want to introduce smarter refs involving `name`/`namespace` we can.
=> fix(Mesh*Service): rename HostnameGenerator ref `name` to `coreName`

pkg/core/resources/apis/mesh/dataplane_validator.go, pkg/core/resources/apis/mesh/dataplane_validator_test.go
relax validation of port on universal for mesh external service
=> feat(meshexternalservice): relax validation of port on universal

pkg/xds/context/aggregate_mesh_context.go, pkg/xds/context/aggregate_mesh_context_test.go
Fixes
```
2024-06-20T21:03:00.1496054Z   2024-06-20T21:02:53.798Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"","Name":"ingress"}, "error": "there should be a corresponding mesh context for every mesh in mesh contexts", "errorVerbose": "there should be a corresponding mesh context for every mesh in mesh contexts\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick.func1\n\tgithub.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:64\nruntime.gopanic\n\truntime/panic.go:914\ngithub.com/kumahq/kuma/pkg/xds/context.AggregatedMeshContexts.MustGetMeshContext\n\tgithub.com/kumahq/kuma/pkg/xds/context/context.go:155\ngithub.com/kumahq/kuma/pkg/xds/sync.(*IngressProxyBuilder).buildZoneIngressProxy\n\tgithub.com/kumahq/kuma/pkg/xds/sync/ingress_proxy_ …
```
=> fix(kuma-cp): panic on mesh delete

test/e2e_env/multizone/multizone_suite_test.go
https://github.com/kumahq/kuma/issues/10605
=> test(e2e): temporarily skip available services test

pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/basic.listener.golden.yaml, pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/simple.listener.golden.yaml, pkg/plugins/policies/meshpassthrough/plugin/xds/configurer.go, pkg/plugins/policies/meshpassthrough/plugin/xds/listeners_filter_chain.go, pkg/xds/envoy/virtualhosts/configurer.go, pkg/xds/envoy/virtualhosts/route_configurer.go, test/e2e_env/kubernetes/meshpassthrough/meshpassthrough.go
When MeshPassthrough doesn't expose traffic, but the traffic is HTTP and there is other HTTP traffic exposed, we used to return a 404 error indicating that there is no route. I have changed this to return a 503 error when there is no route because the traffic is forbidden.
> Changelog: feat(meshpassthrough): implement new policy
=> fix(meshpassthrough): return 503 when no route found

pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/http_filter_mod.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/network_filter_mod.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/virtual_host_mod.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/virtual_host_test.go
=> perf(MeshProxyPatch): remove filters without allocation

test/e2e_env/multizone/connectivity/available_services.go, test/e2e_env/multizone/multizone_suite_test.go
I saw a failure on the dataplane list being empty. I think the app deletion should happen first here, otherwise there's a race with it recreating the Dataplane on reconnection. Also reenable to keep testing it on master.
=> test(e2e): tweak and reenable available services test

pkg/zone/available_services.go, pkg/zone/available_services_test.go, pkg/zone/components.go
Fix #10611
Disable available services when service tag vips are disabled.
I put the existing test into `Context("Enabled Available Services` and switched to using a zone ingress builder. 
It's intentional to put it to master. I don't want to add this to release branch last minute
=> feat(meshservice): disable available services on disabled vips

test/e2e/helm/e2e_suite_test.go
2.6.8 and 2.7.4 was released with a fix so we should enable it and observe if kds is stable
=> test(e2e): enable skipped e2e test after KDS changes

test/e2e/virtualoutbound/virtualoutbound_k8s.go, test/e2e_env/kubernetes/gateway/delegated.go, test/e2e_env/kubernetes/gateway/gateway.go, test/e2e_env/kubernetes/virtualoutbound/virtualoutbound.go, test/e2e_env/multizone/virtualoutbound/virtualoutbound.go, test/framework/deployments/testserver/deployment.go, test/framework/deployments/testserver/kubernetes.go
=> test(e2e): add HeadlessService option to test-server deployment

test/e2e_env/multizone/meshservice/connectivity.go
This works now because we create the MeshService manually.
=> test(e2e): use MeshService managed-by label, same as when autogenerated

pkg/plugins/runtime/k8s/controllers/inbound_converter.go, test/e2e_env/multizone/meshservice/connectivity.go
Named ports from autogenerated MeshServices weren't working
=> fix(MeshService): add port name when converting from Service

test/framework/deployments/testserver/kubernetes.go
This way it works with MeshService
=> test(e2e): add kuma.io/mesh label to test-server Service

test/e2e_env/kubernetes/kubernetes_suite_test.go, test/e2e_env/multizone/multizone_suite_test.go, test/e2e_env/universal/universal_suite_test.go, test/framework/envs/kubernetes/env.go, test/framework/envs/multizone/env.go, test/framework/envs/universal/env.go, test/framework/utils/utils.go
so we know earlier about: https://github.com/kumahq/kuma/actions/runs/9603592697/job/26488848273#step:13:25165 
=> test(e2e): add assertions to not panic in e2e tests

test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_gateway.go, test/framework/gateway.go
We can sometimes observe inconsistencies in the number of requests reaching a specific server. Since each Envoy worker might take and serve a request, the distribution might not closely adhere to the assigned weights. By specifying the concurrency level as 1, the behavior might become more predictable.
=> test(e2e): set concurrency level for gateway

pkg/core/resources/apis/meshservice/match.go, pkg/core/resources/apis/meshservice/match_benchmark_test.go, pkg/core/resources/apis/meshservice/match_test.go, pkg/core/resources/apis/meshservice/status/updater.go, pkg/core/resources/apis/meshservice/suite_test.go, pkg/test/resources/builders/meshservice_builder.go, pkg/xds/topology/outbound.go
Fix #10477
This PR optimizes MeshService to Dataplane matching.
Instead of naive `O(n_mehservices * n_datpalanes)` we now do `O(n_mehservices * n_shortest_list_of_matched_tag_dpps + n_datpalanes)`, so in practice, it's almost a linear complexity.
The idea is to index all the DPPs by tag pairs, for each MeshService select the shortest list of DPPs of all tag pairs and then only iterate over this shortest list. In practice this is usually `app: xyz` or `kuma.io/service: xyz` so all of them will match.
I also did benchmarks. On small data (10 namespaces, 5 services per namespace, 1 dpp per service) naive version takes 50% more time. On large data (200 namespaces , 20 services per namespace, 5 dpps per service) it takes 230x more time. …
=> perf(kuma-cp): faster service to dpp matching

tools/releases/version.sh
https://github.com/envoyproxy/envoy/releases/tag/v1.29.6
=> chore(deps): upgrade envoy version to 1.29.6

.github/workflows/_e2e.yaml, .github/workflows/build-test-distribute.yaml
Please merge this PR only after you see the self hosted runners shared by the org level on this page:
https://github.com/kumahq/kuma/settings/actions/runners
- fixes https://github.com/kumahq/kuma/issues/10583
- Should not impact
- No
- No
=> ci(gha): enable self hosted runners for arm64 e2e tasks

pkg/core/resources/apis/meshservice/status/updater.go, pkg/core/resources/apis/meshservice/status/updater_test.go, pkg/insights/components.go, pkg/test/resources/builders/meshservice_builder.go
I noticed that MeshService status E2E test is flaky while working on other PR.
It turned out that we wipe out `spec.identities` from synced MeshServices, which also breaks multicluster communication.
We should only compute `spec.identities` for local MeshServices.
How did it pass through all the testing and how did multizone traffic work?
We always tested it with a local service and remote service with same selectors.
If you have local and sycned MeshService that selects `app: xyz` and you have local DPPs that have `app: xyz` tag then we would correctly compute identities to synced MeshService.
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue- …
=> fix(meshservice): do not wipe out identities of synced service

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, deployments/charts/kuma/templates/_helpers.tpl, test/e2e/cni/taint_controller_race.go, test/framework/interface.go, test/framework/k8s_cluster.go
The controller did not get the system namespace set so it was always checking for CNI pods in the default `kube-system` namespace. 
xrel: https://github.com/kumahq/kuma/pull/6721/files
=> fix(cni): set proper namespace for the taint controller

tools/releases/dockerfiles/envoy.Dockerfile, tools/releases/dockerfiles/kuma-dp.Dockerfile
Just noticed warnings from docker like:
```
1 warning found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
```
=> chore(dockerfiles): fix keyword casing

pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go
=> fix(MeshService): don't skip endpoints for headless

pkg/plugins/runtime/k8s/controllers/meshservice_controller.go
=> fix(MeshService): don't duplicate headless service VIPs

tools/releases/version.sh
=> chore(deps): upgrade envoy to 1.27.7

tools/releases/version.sh
=> chore(deps): upgrade envoy to 1.28.5

tools/releases/version.sh
=> chore(deps): upgrade envoy to 1.29.7

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
This fixes problems with using kubernetes rollout restart
Fixes: https://github.com/kumahq/kuma/issues/9476
=> fix(meshgateway): do not override annotations from deployment

test/e2e/helm/e2e_suite_test.go
We have released patch releases with a fix (2.6.8, 2.7.4), so we should enable it again.
=> test(e2e): enable upgrade test

pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go
=> refactor(injector): remove old transparent proxy v1 annotation

test/framework/config_transparentproxy.go, test/transparentproxy/transparentproxy_suite_test.go
TProxyConfig is used only in tproxy tests, and when it was initialized in `init()` function, it was run even for e2e tests, which in case of legacy e2e tests was failing because of missing kumactl binary.
- It won't
=> test(framework): init TProxyConfig only in tproxy tests

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/envVarsDownwardApi.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/envVarsDownwardApi.values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cp-deployment.yaml, deployments/charts/kuma/values.yaml, docs/generated/raw/helm-values.yaml
At the moment, we don't have possibility to configure env vars that will use Kuberenetes downward API in Kuma control plane via helm. This can be used to properly configure otel tracing in datadog: https://docs.datadoghq.com/opentelemetry/interoperability/otlp_ingest_in_the_agent/?tab=kubernetes#sending-opentelemetry-traces-metrics-and-logs-to-datadog-agent
=> feat(helm): add possibility to configure env vars with value form referenced field

pkg/xds/ingress/outbound.go, pkg/xds/ingress/outbound_test.go
Headless MeshService didn't work cross-zone.
See #10684
=> fix(MeshService): don't skip endpoints for headless with ZoneIngress

pkg/core/resources/apis/meshservice/api/v1alpha1/meshservice.go, pkg/core/resources/apis/meshservice/api/v1alpha1/validator.go, test/e2e_env/multizone/meshservice/sync.go
The name was being validated to have the given length leading to errors with syncing and the `name.namespace` format on Kubernetes. We actually only need to limit the display name.
See https://github.com/kumahq/kuma/issues/10474
=> fix(MeshService): limit display name to 63 characters

pkg/plugins/bootstrap/k8s/plugin.go
Closes #8160 
This was enabled in some form in https://github.com/kumahq/kuma/pull/1113 and then in its current form in https://github.com/kumahq/kuma/pull/6809
This is of course more correct but the performance implications are not 100% clear.
=> fix(k8s): reenable deep copies

.github/dependabot.yml
These are quite often dependent of each other, let's just update them at once.
=> ci(dependabot): include all k8s updates in one group

.golangci.yml
```
WARN [config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`.
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`.
WARN [config_reader] The configuration option `run.skip-dirs-use-default` is deprecated, please use `issues.exclude-dirs-use-default`.
```
=> ci(golangci-lint): update deprecated config fields

pkg/plugins/policies/meshpassthrough/api/v1alpha1/testdata/full-invalid.output.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/testdata/valid.input.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/validator.go, pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/basic.clusters.golden.yaml, pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/basic.listener.golden.yaml, pkg/plugins/policies/meshpassthrough/plugin/xds/listeners_filter_chain.go, test/e2e_env/kubernetes/gateway/delegated.go, test/e2e_env/kubernetes/gateway/delegated/common.go, test/e2e_env/kubernetes/gateway/delegated/meshpassthrough.go, test/framework/k8s.go
* Added support for MeshGateway in a delegated mode
* Added E2E test for delegated gateway
* Added appending domains with a port and adding them to the domains. Based on the [RFC](https://www.rfc-editor.org/rfc/rfc9110.html#section-7.2) host header might have a port at the end if it's not 80/443. 
=> feat(meshpassthrough): add support for delegated gateway

.github/workflows/_test.yaml
Multiple flakiness occured after self host runners were enabled yesterday, so disable them temporarily and wait for a stabled workflow setup.
Examples:
https://github.com/kumahq/kuma/actions/runs/9784245075/job/27020613836#step:13:995
https://github.com/kumahq/kuma/actions/runs/9784245075/job/27020615529#step:13:11837
https://github.com/kumahq/kuma/actions/runs/9784245075/job/27020613465#step:13:2380
Added
- No
- No
=> ci(.github): disable self host runners for AMD64 tasks temporarily because of flakiness

pkg/transparentproxy/iptables/builder/builder_restore.go, pkg/transparentproxy/iptables/consts/consts.go
This change fixes installing transparent proxy on environments, which doesn't come with iptables executables with mode suffixes (iptables-nft or iptables-legacy) and come with just iptables. Such environment is RHEL 8.
- It won't
=> fix(transparent-proxy): allow iptables executable without mode

test/framework/envs/multizone/env.go
For more complete testing of MeshService and testing of a potential migration path where existing `kuma.io/service` destinations are not ignored.
=> test(e2e): enable GENERATE_MESH_SERVICES in first multizone k8s cluster

pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/transparentproxy/config/config.go, pkg/transparentproxy/iptables/consts/consts.go
Instead of relying on `config.DefaultConfig()` in k8s injector, we are now importing only consts package, which makes it possible, to build `kuma-cp` on non-unix-based systems.
- It won't
=> refactor(transparent-proxy): put default ports in consts package

pkg/transparentproxy/config/config.go, pkg/transparentproxy/iptables/builder/builder_table_nat.go, pkg/transparentproxy/iptables/builder/builder_table_raw.go, pkg/transparentproxy/iptables/parameters/protocol.go
When the `--redirect-dns` flag is present during the execution of `kumactl install transparent-proxy`, the `/etc/resolv.conf` file is parsed to obtain DNS servers. However, when the transparent proxy is configured to include IPv6 and no valid IPv6 servers are found, incorrect iptables rules were generated.
This commit fixes this when in such situation logs warning and skip IPv6 DNS traffic redirection.
Generated earlier IPv6 rules:
```sh
* raw
-A OUTPUT -p udp --dport 53 -m owner --uid-owner 5678 -j CT --zone 1
-A OUTPUT -p udp --sport 15053 -m owner --uid-owner 5678 -j CT --zone 2
COMMIT
* nat
-N KUMA_MESH_INBOUND
-N KUMA_MESH_OUTBOUND
-N KUMA_MESH_INBOUND_REDIRECT
-N KUMA_MESH_OUTBOUND_REDIRECT
-A PREROUTING -p tcp -j KUMA_MESH_INBOUND
-I OUTPUT 1 -p udp --dport 53 -m owner --uid-owner …
```
=> fix(transparent-proxy): fix IPv6 iptables rules when no IPv6 DNS servers

test/e2e_env/kubernetes/kubernetes_suite_test.go, test/e2e_env/multizone/multizone_suite_test.go, test/e2e_env/universal/universal_suite_test.go, test/framework/debug.go, test/framework/envs/kubernetes/env.go, test/framework/envs/multizone/env.go, test/framework/envs/universal/env.go
Check that universal CP did not crash.
Additionally, I extracted all responsibilities to one common `*AfterSuite` in each env, so whenever we add a new responsibility here, it also goes automatically to all projects that are based on Kuma (ex. Kong Mesh).
=> test(e2e): check that universal CP did not crash

pkg/transparentproxy/iptables/builder/builder.go, pkg/transparentproxy/iptables/builder/builder_table_nat_test.go, pkg/transparentproxy/iptables/chains/chains.go, pkg/transparentproxy/iptables/rules/rules.go, pkg/transparentproxy/iptables/tables/tables.go
In the PR introducing comments in iptables rules, I neglected to verify the availability of the comment iptables extension/module. This change addresses that oversight.
I acknowledge that passing the ipv6 value everywhere is cumbersome. I plan to refactor the builders to handle IP types in a more agnostic manner. This improvement will be addressed in subsequent PRs, as it requires a more complex update.
- https://github.com/kumahq/kuma/pull/10809
- https://github.com/kumahq/kuma/issues/8411
- It won't
=> fix(transparent-proxy): don't add comments if no comment iptables module

pkg/plugins/runtime/k8s/controllers/pod_controller.go, test/e2e_env/gatewayapi/conformance_test.go
`apiVersion` isn't set by k8s for `Pods` for some reason.
Closes https://github.com/kumahq/kuma/issues/10768
=> fix(GatewayAPI): check manual endpoints ref properly

test/framework/utils/utils.go, test/transparentproxy/config.go, test/transparentproxy/install/install.go
This update allows specifying a map where keys are prefixes used for generating golden file names, and values are lists of arguments for the `kumactl install transparent-proxy` command.
You can specify this using an env var, e.g.:
```sh
ADDITIONAL_FLAGS_TO_TEST='{"foo":["--verbose","--iptables-logs"]}'
```
It improves situation when you want to test multiple flags in one test case. In such situation golden files would include all flags in the name before. Now the name would contain a key from the map.
- It won't
=> test(transparent-proxy): refactor InstallFlagsToTest to use a map

.github/workflows/transparentproxy-tests.yaml
- Increased transparent proxy tests timeout in CI to 40 minutes as 20 minutes was not enough
- Removed unnecessary empty line
- Renamed job to `test` as it's obvious what test it applies to
- Renamed the name of workflow to one which suits it better
- It won't
- It does
=> chore(transparent-proxy): increase tproxy tests timeout in CI

test/e2e_env/gatewayapi/conformance_test.go
=> test(e2e): enable additional GAMMA Gateway API test

docs/madr/decisions/046-meshservice-policy-matching.md
While trying to support Inspect API I realised it might be not possible to resolve targetRef with `name/namespace` in case it's referring to already synced resource (with hash suffix).
=> docs(MADR): update referencing synced resources by `name/namespace`

test/e2e_env/kubernetes/gateway/delegated.go, test/e2e_env/kubernetes/gateway/delegated/meshpassthrough.go
MeshPassthrough test is using the same resource name and it might cause an overriding. Renaming to avoid this situation and flakes
=> test(e2e): rename resource for delegated to avoid conflicts

api/mesh/v1alpha1/dataplane_helpers.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment_test.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, test/e2e_env/gatewayapi/conformance_test.go
=> feat(GatewayAPI): support port in parentRef

test/e2e_env/universal/matching/matching.go
Fix #4864
There is another `fi1` in another test.
=> test(e2e): fix test flakiness

pkg/transparentproxy/config/config.go, pkg/transparentproxy/config/config_executables_functionality.go, pkg/transparentproxy/config/config_suite_test.go, pkg/transparentproxy/config/config_test.go, pkg/transparentproxy/iptables/builder/builder_table_mangle.go, pkg/transparentproxy/iptables/builder/builder_table_nat.go, pkg/transparentproxy/iptables/builder/builder_table_raw.go, pkg/transparentproxy/iptables/chains/chains.go, pkg/transparentproxy/iptables/consts/consts.go, pkg/transparentproxy/iptables/parameters/protocol.go, pkg/transparentproxy/iptables/parameters/source.go, pkg/transparentproxy/iptables/rules/rules.go
> [!TIP]
> I recommend reviewing each commit individually, as I've organized the work into self-contained, descriptive commits for easier understanding.
This PR introduces several key improvements and refactorings to enhance the maintainability, flexibility, and clarity of the iptables rule generation process in the transparent proxy.
- **Add Multiport module validation to `Functionality` struct**
This commit enhances the `Functionality` struct by incorporating validation for the Multiport module. This update allows the system to determine whether the Multiport module is supported, enabling more efficient handling of port exclusions.
- **Add `NewValueOrRangeList` function**
This commit introduces the `NewValueOrRangeList` function, which provides a flexible and type-safe way to create a …
=> refactor(transparent-proxy): improvements in table builders

pkg/plugins/policies/core/xds/meshroute/gateway.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go, pkg/plugins/runtime/gateway/filter_chain_generator.go, pkg/plugins/runtime/gateway/generator.go, pkg/plugins/runtime/gateway/route_table_generator.go, test/e2e_env/gatewayapi/conformance_test.go
And now it passes the isolation conformance tests
=> fix(MeshGateway): prevent duplicate virtual hosts

.circleci/config.yml, go.mod
This is a manual PR to the release branch to upgrade a patch version of go for the CircleCI configuration.
=> ci(circleci): upgrade go version on CircleCI config to 1.21.12

pkg/plugins/runtime/k8s/webhooks/injector/injector.go
Allow setting `kuma.io/transparent-proxying-ip-family-mode` annotation on a per-pod basis.
Log warnings when `kuma.io/transparent-proxying`,
`kuma.io/transparent-proxying-inbound-port`, or
`kuma.io/transparent-proxying-outbound-port` are specified on a per-pod basis, as these values are ignored.
Closes https://github.com/kumahq/kuma/issues/10903
- https://github.com/kumahq/kuma/issues/10903
- It won't
- Tested on local k3d cluster:
- with init containers
- with init containers and ` --set controlPlane.envVars.KUMA_RUNTIME_KUBERNETES_INJECTOR_SIDECAR_CONTAINER_IP_FAMILY_MODE=ipv4`
- with CNI
- with CNI and ` --set controlPlane.envVars.KUMA_RUNTIME_KUBERNETES_INJECTOR_SIDECAR_CONTAINER_IP_FAMILY_MODE=ipv4`
- There …
=> fix(transparent-proxy): enable `kuma.io/transparent-proxying-ip-family-mode` annotation per pod

pkg/core/rest/errors/error_handler.go, pkg/intercp/envoyadmin/forwarding_kds_client.go, pkg/intercp/envoyadmin/forwarding_kds_client_test.go
When the user enters GUI and his zone is offline, it is still possible to execute an admin operation. We don't check if zone is online. This PR introduces a check to validate if zone is online before going forward. Also, added a mapping to 400 status code.
=> fix(kuma-cp): check if zone is online before forwarding request

api/common/v1alpha1/ref.go, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/helpers.go, pkg/core/resources/apis/meshservice/api/v1alpha1/helpers.go, pkg/plugins/policies/core/xds/meshroute/clusters.go, pkg/plugins/policies/core/xds/meshroute/listeners.go, pkg/test/resources/builders/meshmultizoneservice_builder.go, pkg/test/resources/samples/meshservice_samples.go, pkg/xds/context/context.go, pkg/xds/context/mesh_context_builder.go, pkg/xds/context/resources.go, pkg/xds/envoy/tls/sni.go, pkg/xds/envoy/tls/sni_test.go, pkg/xds/envoy/types.go, pkg/xds/generator/egress/external_services_generator.go, pkg/xds/generator/egress/internal_services_generator.go, pkg/xds/generator/ingress_generator.go, pkg/xds/generator/zoneproxy/destinations.go, pkg/xds/generator/zoneproxy/generator.go, pkg/xds/server/components.go, pkg/xds/sync/dataplane_proxy_builder.go, pkg/xds/topology/dns.go, pkg/xds/topology/ingress_outbound_test.go, pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go, test/e2e_env/multizone/meshmultizoneservice/connectivity.go, test/e2e_env/multizone/multizone_suite_test.go, test/framework/k8s.go
Part of https://github.com/kumahq/kuma/issues/10507
* Generate clusters of `<name>_mzsvc_<port>`.
* To generate endpoints for those clusters, leverage existing endpoints
* It prefers local endpoints but fallbacks to other zone.
* Right now we don't exclude the zone with 0 endpoints of MeshService. See E2E test. Out of scope of this PR
* Building SNI is annoying. It most likely will go on the resource itself. Out of scope of this PR.
=> feat(meshmultizoneservice): generate xds

docs/madr/decisions/058-meshservice-permissive-tls.md
xref https://github.com/kumahq/kuma/issues/10896
=> docs(MADR): permissive mtls and mesh service

pkg/core/resources/manager/manager.go, pkg/core/resources/manager/meta.go
At the moment the [MeshService validator](https://github.com/kumahq/kuma/blob/master/pkg/core/resources/apis/meshservice/api/v1alpha1/validator.go) fails when Create is called because the meta is `nil` and the future name of the resource is missing.
needed to get rid of [this commit in #10917](https://github.com/michaelbeaumont/kuma/commit/7bcee67d58d0deb7e2db192d2a3c3133a5aacbc4)
=> fix(kuma-cp): pass future meta to Validate when creating a resource

tools/releases/version.sh
=> chore(deps): upgrade envoy with DNS fix

test/e2e/federation/federation_suite_test.go
Temporarily skipping due to https://github.com/kumahq/kuma/pull/10914
=> test(e2e): skip federation tests

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshpassthroughs.yaml, docs/generated/openapi.yaml, docs/generated/raw/crds/kuma.io_meshpassthroughs.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/meshpassthrough.go, pkg/plugins/policies/meshpassthrough/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshpassthrough/k8s/crd/kuma.io_meshpassthroughs.yaml
We had a pointer to int for a `port` but it requires `omitempty` to make it nor required.
=> fix(meshpassthrough): do not require port

pkg/core/resources/apis/meshservice/status/updater.go, pkg/core/resources/apis/meshservice/status/updater_test.go, pkg/core/resources/model/resource.go, pkg/plugins/policies/core/xds/meshroute/clusters.go, pkg/test/resources/builders/dataplane_insight_builder.go, pkg/test/resources/builders/meshservice_builder.go, pkg/test/resources/samples/dataplane_insight_samples.go, test/e2e_env/universal/meshservice/meshservice.go
Implementation of https://github.com/kumahq/kuma/pull/10924
=> feat(meshservice): permissive mtls

docs/madr/decisions/056-meshservice-proxies-stats.md
=> docs(MADR): proxies stats of MeshService

app/kumactl/cmd/apply/testdata/apply-multiple-resource-different-type.yaml, pkg/util/yaml/split.go, test/e2e/federation/federation_suite_test.go
When a document had just 1 comment this would cause problems when doing `kumactl apply -f`.
We now strip comments before doing anything which would ignore this doc
=> fix(kumactl): in apply support empty docs

pkg/core/bootstrap/bootstrap.go, pkg/plugins/secrets/k8s/plugin.go
We were wrapping a store that already had a pagination store with another pagination store.
This led to inconsistent results like:
```
% kumactl get secrets --mesh nonprod --size 1000 | grep -v MESH | wc -l
450
% kumactl get secrets --mesh nonprod --offset 100 | grep -v MESH | wc -l
0
```
Only k8s stores needs to be wrapped with a pagination store, the default store for universal is already paginated:
https://github.com/kumahq/kuma/blob/7075f0e17466c73ec82aa95649124edad6cafe8d/pkg/core/bootstrap/bootstrap.go#L295-L301
https://github.com/kumahq/kuma/blob/7075f0e17466c73ec82aa95649124edad6cafe8d/pkg/plugins/secrets/universal/plugin.go#L17
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-a …
=> fix(kuma-cp): paginate Secrets correctly in universal

pkg/xds/bootstrap/handler.go, pkg/xds/context/context.go, pkg/xds/context/mesh_context_builder.go, pkg/xds/envoy/clusters/v3/health_check_configurer.go, pkg/xds/generator/egress/generator.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/prometheus_endpoint_generator.go, pkg/xds/generator/secrets/generator.go, pkg/xds/server/callbacks/dataplane_sync_tracker.go, pkg/xds/server/v3/components.go, pkg/xds/server/v3/context.go, pkg/xds/server/v3/reconcile.go, pkg/xds/sync/components.go, pkg/xds/sync/dataplane_watchdog.go, pkg/xds/template/proxy_template_resolver.go, pkg/xds/topology/outbound.go
=> feat(kuma-cp): make loggers naming from xds package consistent

UPGRADE.md, app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/prometheus/server.yaml
Service can be used by a lot of things and cause label collision kuma_service is a better alternative.
Dashboards currently don't use this label so the change is transparent for demos
part of kong/kong-mesh#4576
=> fix(kumactl): remove service in prometheus config

.github/workflows/build-test-distribute.yaml
We were hitting [issues](
https://github.com/kumahq/kuma/actions/runs/9946537064/job/27482182852#step:6:100) with gh rate limiting us.
We instead use pip directly which will not have this issue: https://github.com/cloudsmith-io/action/blob/master/action.yml#L118-L139
=> ci(github): use cloudsmith cli from pulp not gh releases

pkg/core/tokens/default_signing_key.go, pkg/defaults/components.go, pkg/defaults/components_test.go, pkg/defaults/envoy_admin_ca.go, pkg/defaults/envoy_admin_ca_test.go, pkg/defaults/mesh.go, pkg/defaults/zone.go, pkg/plugins/authn/api-server/tokens/plugin.go
Refactor Ensuring default resources.
I wanted to add a new default HostnameGenerators. However, I noticed that there is a lot of code duplication and inflexibility here.
1) Every ensuring default was a component, which adds a lot of code
2) The default Mesh component was weird (it had wait groups but only had one operation only?)
3) Adding a new default requires Kong's team to modify the code of Kong Mesh to execute the code to create a new resource when creating a new tenant in Konnect.
The refactor streamlines this code so that
1) You write `EnsureXResource` function that matches `EnsureDefaultFunc` signature
2) You add this to the `EnsureDefaultFuncs` list.
This way we don't duplicate the code of the component. In Kong Mesh, we can just iterate over list when we create a new tenant.
I …
=> chore(refactor): ensuring default resources

pkg/core/resources/model/resource.go, pkg/kds/context/context.go, pkg/kds/v2/store/sync.go, pkg/plugins/resources/k8s/store.go, pkg/plugins/runtime/k8s/webhooks/defaulter_test.go
This reverts commit 51a5b55153f2a8729f6a7c5f710812c7676b5025.
=> Revert "fix(kuma-cp): don't add namespace labels when resource was synced from universal zone (#10913)"

pkg/core/resources/manager/manager.go
=> fix(kuma-cp): don't override owner and creation time Create opts

pkg/core/resources/apis/hostnamegenerator/hostname/generator.go, pkg/core/resources/apis/meshservice/hostname/generator_test.go, pkg/test/resources/builders/meshservice_builder.go
- https://github.com/kumahq/kuma/pull/11009
We weren't sorting the resources before running the HostnameGenerators
=> fix(HostnameGenerator): consistently order resources

docs/generated/raw/kuma-cp.yaml, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/core/resources/apis/meshservice/generate/component.go, pkg/core/resources/apis/meshservice/generate/generator.go, pkg/core/resources/apis/meshservice/generate/generator_test.go
=> feat(MeshService): add grace period before deleting generated MeshServices on universal

pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
Kubebuilder generates OpenAPI spec with defaults; once we don't set it, it is set to the default from the spec. Unfortunately, it doesn't work on Universal, and the value might not be set correctly. Because of this once dereferencing weight, we hit the nil pointer. https://github.com/kumahq/kuma/issues/6070
Logs 
```
OnTick() failed	{"dataplaneKey": {"Mesh":"default","Name":"gateway-instance-1"}, "error": "runtime error: invalid memory address or nil pointer dereference", "errorVerbose": "runtime error: invalid memory address or nil pointer dereference\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick.func1\n\tgithub.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:62\nruntime.gopanic\n\truntime/panic.go:770\nruntime.panicmem\n\truntime/panic.go:261\nruntime.sigpanic\n\trunti …
```
=> fix(meshhttproute): deref pointer to weight or use default 1

pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
Just noticed this improvement randomly, we don't need the whole route
=> refactor(kuma-cp): simplify function signature for Gateway API conversion

app/cni/pkg/cni/injector_linux.go, pkg/transparentproxy/config/config.go, pkg/transparentproxy/config/config_executables.go, pkg/transparentproxy/config/config_executables_linux.go, pkg/transparentproxy/config/config_executables_unspecified.go, pkg/transparentproxy/iptables/consts/consts.go
A bug resulting in pod start being delayed by 30-60s occurs in the following situation:
- Kuma CNI plugin is used
- GKE is new enough to have a recent GKE Metadata Server, which is more restrictive
- OS Login is enabled in GCE
The issue arises due to a circular dependency during the pod initialization process. When a pod starts, `kuma-cni` gets invoked. At this moment, the pod exists, but its containers are not yet running. `kuma-cni` essentially runs a command similar to `nsenter <POD> -- iptables-restore`. This command uses the `xt_owner` module with the `-m owner` flag, which makes a call to `getpwnam` (reference here: https://git.netfilter.org/iptables/tree/extensions/libxt_owner.c#n150). This call triggers the PAM authentication process.
In environments where OS Login is enabled on a …
=> fix(transparent-proxy): fix pod delay when CNI on GKE with OS Login

api/mesh/v1alpha1/dataplane_helpers.go, pkg/core/resources/apis/meshservice/generate/generator.go, pkg/kds/context/context.go, pkg/kds/util/meta.go
=> fix(MeshService): don't sync deletion grace period label

pkg/api-server/resource_endpoints.go
Now looks like:
```
{
"type": "/std-errors",
"status": 405,
"title": "Method not allowed",
"detail": "On global control plane you can not modify dataplane resources with 'kumactl apply' or via the HTTP API. You can still use 'kumactl' or the HTTP API to modify them on the zone control plane.\n",
"details": "On global control plane you can not modify dataplane resources with 'kumactl apply' or via the HTTP API. You can still use 'kumactl' or the HTTP API to modify them on the zone control plane.\n"
}
```
`HandleError` is kind of strange, a lot of the cases don't even use the `title` parameter, which is more like `details` in a lot of cases.
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-t …
=> fix(api-server): method not allowed error

test/framework/universal_cluster.go
there are some tests that are failing in the parent project without any trace in the logs, maybe there is something on stderr?
=> test(debug): add more logs

pkg/util/watchdog/watchdog.go, pkg/util/watchdog/watchdog_test.go
This delays xds config generation unnecessarily.
=> fix(kuma-cp): don't wait before ticking the first time in watchdog

app/kuma-dp/cmd/run.go, app/kuma-dp/pkg/dataplane/envoy/compatibility.go, app/kuma-dp/pkg/dataplane/envoy/compatibility_test.go
In compatibility checks we checked that the version matched our version constraints.
We used to panic if the build envoy version isn't a valid semver. We now allow this and an error log will show up
Also if the version isn't semver we check lexicographic equality.
fix #11086
=> fix(kuma-dp): don't fail if internal version is not semver

app/kuma-cp/cmd/run.go, pkg/plugins/bootstrap/k8s/plugin.go
So we can distinguish this from an error case. The `Pod` has `restartPolicy: Always` as default
=> feat(kuma-cp): exit with 0 when kubernetes leader election is lost

app/kuma-dp/pkg/dataplane/probes/component.go, app/kuma-dp/pkg/dataplane/probes/probe_dialer_others.go, app/kuma-dp/pkg/dataplane/probes/probe_dialer_windows.go
- Fix failed CI on child repos.
- Confirmed
- Added
- No
- No
=> fix(kuma-dp): fix build failures on Windows because of TCP socket options on SO_LINGER

app/kuma-dp/pkg/dataplane/probes/probe_suite_test.go, app/kuma-dp/pkg/dataplane/probes/probes_test.go
In previous version of unit tests, probe actions can be performed before the mock app is actually ready. Now it makes sure the mock app is ready before any test action is performed.
- fix CI flakiness https://github.com/kumahq/kuma/actions/runs/10447433680/job/28926560710
- Confirmed
- Added
- No
- No
=> fix(kuma-dp): fix flaky tests on application probe proxy due to readiness of mock apps

test/e2e_env/kubernetes/gateway/delegated/meshaccesslog.go, test/e2e_env/kubernetes/gateway/delegated/meshhealthcheck.go, test/e2e_env/kubernetes/gateway/delegated/meshhttproute.go, test/e2e_env/kubernetes/gateway/delegated/meshtcproute.go
Some of the delegated tests might have a conflict in resource names with other tests. To avoid this situation, I added a suffix to the resource names.
=> test(e2e): added resource name suffix to avoid conflicts

pkg/plugins/resources/k8s/native/api/v1alpha1/mesh_gateway_instance.go
While debugging https://github.com/kumahq/kuma/pull/11137, I discovered that after upgrading the Kubernetes libraries, the gateway tests were failing. The issue was due to the `kuma.io/service` label being required, even though it's autogenerated and we don't allow it to be set manually since 2.9.x(https://github.com/kumahq/kuma/pull/10968). To resolve this, I changed the label's status from required to optional.
=> fix(meshgatewayinstance): remove required since we generate serviceName

api/common/v1alpha1/ref.go, pkg/plugins/policies/core/rules/rules.go
`BuildToRules` calls two methods: `BuildRules` and `BuildResourceRules`. `BuildRules` maps kinds to tags, but for `MeshExternalService`, it cannot be mapped to a specific tag because it's a different type. Previously, we were returning an error and didn't attempt to run `BuildResourceRules`, which caused the policy to not match the dataplane (DP).
Note: I will add a test once MeshExternalService is supported by one of the policies, as it currently does not pass the validator.
=> fix(policy): don't fail once cannot map MES to tags rules

test/e2e_env/kubernetes/gateway/delegated/meshhttproute.go
We were using the some name of the ES resource in 2 places in `e2e_env/kubernetes`
=> test(e2e): rename ES resource name

pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator.go, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator_test.go
Part of https://github.com/kumahq/kuma/issues/10935
=> feat(MeshLoadBalancingStrategy): only allow localZone for real MeshService

pkg/transparentproxy/config/config_executables.go, pkg/transparentproxy/config/config_executables_functionality.go
In cases where both iptables-legacy and iptables-nft are available, this PR improves the selection process by checking which executable contains existing rules or custom chains and prioritizing that one for use.
- It won't
- Existing transparent-proxy tests are passing
> Changelog: feat(transparent-proxy): check for existing rules or custom chains when picking iptables executables
=> feat(transparent-proxy): check for existing iptables rules when picking executables

pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator.go, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator_test.go
Forgot to add the test condition in https://github.com/kumahq/kuma/pull/11173
=> fix(MeshLoadBalancingStrategy): validation for real MeshService

test/e2e_env/universal/meshhealthcheck/policy.go
We were sharing a mesh between tests, I've changed it to create a new one for MeshService test.
=> test(e2e): use separate mesh

tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
Fixes our update vulnerable dependencies CI action, which was not updating dependencies with erros:
```sh
Scanning dir 
Unable to parse git ignores: stat : no such file or directory
Failed to walk : lstat : no such file or directory
lstat : no such file or directory
```
- it won't
- manually tested
=> ci(deps): fix update-vulnerable-dependencies.sh additional opts passing

tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
Earlier try didn't fix the issue when provided `OSV_SCANNER_ADDITIONAL_OPTS` env var war empty (as it's in the case of our CI). Now we are handling explicitly parsing of this env var, which should fix `update-vulnerable-dependencies.sh` script.
- https://github.com/kumahq/kuma/pull/11181
- It won't
=> ci(deps): improve handling OSV_SCANNER_ADDITIONAL_OPTS env var

pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/basic.listener.golden.yaml, pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/simple.listener.golden.yaml, pkg/xds/envoy/virtualhosts/route_configurer.go
The basic route configurer is only used by MeshPassthrough
=> fix(MeshPassthrough): don't only route /

docs/madr/decisions/061-meshtls.md
https://docs.google.com/document/d/1zA1q1hD3PN7c1EsnxkwggtBR08-8i5voZG3yNJyjQfI/edit#heading=h.n6cmlf1eel2z
=> docs(meshtls): design of MeshTLS

pkg/core/resources/apis/meshservice/generate/generator.go, pkg/core/resources/apis/meshservice/generate/generator_test.go, pkg/plugins/runtime/k8s/controllers/meshservice_controller.go, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/02.meshservice.yaml, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/headless.meshservice.yaml, pkg/test/resources/builders/dataplane_builder.go
=> feat(MeshService): automatically add port name when generating

pkg/plugins/policies/meshtimeout/api/v1alpha1/validator.go, test/e2e_env/multizone/meshtimeout/meshtimeout.go
Needs https://github.com/kumahq/kuma/pull/11205
=> feat(MeshTimeout): support MeshMultiZoneService

pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshexternalservice/01.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-k8s-2-zone-k8s.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-k8s-2-zone-uni.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-k8s.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-uni-2-zone-k8s.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-uni-2-zone-uni.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-uni.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s-2-global-k8s.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s-2-global-uni.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s-2-zone-k8s.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s-2-zone-uni.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni-2-global-k8s.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni-2-global-uni.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni-2-zone-k8s.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni-2-zone-uni.golden.yaml, pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni.golden.yaml
After a merge files needs to be regenerated.
=> test(unit): regenerate golden files after merge

pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.34.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.34.golden.yaml
Since kuma CNI is designed to allow the pods to run with less privileges, and the pod already doesn't run as root, also set `allowPrivilegeEscalation: false` to better lock down the validator container.
Closes https://github.com/kumahq/kuma/issues/11176
=> fix(injector): set allowPrivilegeEscalation: false on `kuma-validation` container

test/framework/debug.go, test/framework/universal_cluster.go
We currently can see a lot of flakes in universal e2e tests, and we don't have enough data to debug it, especially that we cannot reproduce it locally. This commit adds results of `kumactl inspect dataplane ...` when any of these tests will fail.
- There is no relevant issues
- It won't
- Locally tested on few e2e tests
- Only to release-2.8
=> test(e2e/debug): add kumactl inspect result when universal e2e test fail

pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/basic_outbound.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/basic_outbound_real_meshservice.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/inbound_route.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_file_backend_default_format.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_file_backend_json_format.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_file_backend_plain_format.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_otel_backend_plain_format.cluster.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_otel_backend_plain_format.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_otel_backend_plain_format_1.cluster.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_otel_backend_plain_format_1.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_otel_backend_plain_format_2.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_route_without_match.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_tcp_backend_default_format.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_tcp_backend_json_format.listener.golden.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/outbound_tcp_backend_plain_format.listener.golden.yaml, pkg/plugins/runtime/k8s/webhooks/validation.go, test/e2e_env/universal/meshaccesslog/meshaccesslog.go
=> feat(policy): add possibility to target real MeshService in MeshAccessLog policy

test/framework/debug.go
So far we didn't have access to logs of workloads in docker containers when e2e universal test fails. This commit copies files with logs to appropriate debug directory, which then is uploaded as an artifact via our CI.
- It won't
- Locally tested
- Only to 2.8
=> test(e2e/universal): copy container logs during e2e universal debug

pkg/plugins/policies/meshtrafficpermission/graph/reachable_services_graph_test.go, pkg/plugins/policies/meshtrafficpermission/graph/services/reachable_services_graph.go
We do not recommend using MeshService anymore in top level target ref, but autoreachable services do not work with kuma.io/service in MeshSubset. This PR adds kuma.io/service to supported list of tags for MeshSubset
=> feat(autoreachableservices): support kuma.io/service in mesh subset

test/e2e_env/universal/meshexternalservice/meshexternalservice.go
I have noticed that one test flaked because of the same name.
=> test(e2e): use different name to avoid conflict

pkg/xds/topology/ingress_outbound_test.go, pkg/xds/topology/outbound_test.go
These tests are changing in a later PR but I think they don't quite make sense as is when it comes to the ports.
=> test(topology): make test resource ports consistent with each other

pkg/core/resources/apis/meshservice/api/v1alpha1/helpers.go, pkg/plugins/policies/core/xds/meshroute/listeners.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice.clusters.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice.endpoints.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice.listeners.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.clusters.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.endpoints.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.listeners.golden.yaml, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/basic-real-meshservice.clusters.golden.yaml, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/basic-real-meshservice.endpoints.golden.yaml, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/basic-real-meshservice.listeners.golden.yaml, pkg/xds/generator/testdata/ingress/mesh-service.envoy.golden.yaml, pkg/xds/topology/ingress_outbound_test.go, pkg/xds/topology/outbound_test.go, test/e2e_env/universal/meshservice/meshservice.go
=> feat(MeshService): create different clusters for real MeshServices

test/e2e/reachableservices/auto_reachable_mesh_services_k8s.go
=> test(e2e): adjust MeshService cluster name based expectations

pkg/plugins/policies/meshtrafficpermission/graph/reachable_graph.go
Fixes e2e failure https://github.com/kumahq/kuma/actions/runs/10661894136/job/29548513074#step:12:3062
Map in reachable_graph.go contains MeshServices without port. That's why we have to remove ports before the lookup.
=> fix(kuma-cp): handle cases when requested BackendRefIdentifier contains ports

test/e2e_env/kubernetes/gateway/mtls.go, test/framework/deployments/testserver/deployment.go, test/framework/deployments/testserver/kubernetes.go
Improving existing testserver deployment DSL to allow allow customizing args and adding more Kubernetes probes
- A dependency of https://github.com/kumahq/kuma/issues/11122
- Confirmed
- N/A
- No
- No
=> refactor(test-framework): allow customizing args and probes to testserver deployments on Kubernetes

pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go, test/e2e_env/multizone/localityawarelb/meshmultizoneservice.go, test/e2e_env/multizone/multizone_suite_test.go
Mesh lbstrategy with MeshMultiZoneService
Fix #10935
=> feat(meshloadbalancingstrategy): support for multizoneservice

test/e2e_env/multizone/localityawarelb/meshmultizoneservice.go
=> test(e2e): enable MeshServices in MeshMultiZoneService/MeshLoadBalancingStrategy

pkg/xds/sync/dataplane_proxy_builder.go, test/e2e_env/multizone/multizone_suite_test.go, test/e2e_env/multizone/reachablebackends/reachablebackends.go, test/e2e_env/multizone/reachablebackends/reachablebackends_meshservices.go
This also adds e2e tests for `meshServices.enabled: ReachableBackendRefs`.
=> fix(MeshService): don't exclude kuma.io/service if using reachableBackends

pkg/plugins/policies/meshaccesslog/api/v1alpha1/validator.go, pkg/plugins/policies/meshaccesslog/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshretry/api/v1alpha1/validator.go, pkg/plugins/policies/meshretry/api/v1alpha1/validator_test.go
=> feat(MeshMultiZoneService): add support to MeshCircuitBreaker, MeshAccessLog, MeshHealthCheck, MeshRetry

UPGRADE.md
Fixing incorrect configuration keys in original version of upgrade notes on application probe proxy. Improved wording of related statements.
- N/A
- Confirmed
- N/A
- Added
- Yes, I did.
- No
=> docs(upgrade.md): minor enhancement on upgrade notes of app probe proxy

test/e2e_env/kubernetes/appprobeproxy/probe_proxy.go, test/e2e_env/kubernetes/kubernetes_suite_test.go, test/framework/deployments/testserver/deployment.go, test/framework/deployments/testserver/kubernetes.go
- closes https://github.com/kumahq/kuma/issues/11122
- Confirmed
- No
- No
=> test(kuma-dp): add E2E for application probe proxy

pkg/core/resources/apis/hostnamegenerator/hostname/generator.go, pkg/core/resources/apis/meshexternalservice/hostname/generator.go, pkg/core/resources/apis/meshexternalservice/hostname/generator_test.go, pkg/core/resources/apis/meshmultizoneservice/hostname/generator.go, pkg/core/resources/apis/meshmultizoneservice/hostname/generator_test.go, pkg/core/resources/apis/meshservice/generate/generator.go, pkg/core/resources/apis/meshservice/hostname/generator.go, pkg/core/resources/apis/meshservice/hostname/generator_test.go, pkg/dns/hostname_generator.go, test/e2e_env/multizone/meshservice/connectivity.go
See https://github.com/kumahq/kuma/pull/11037 and then https://github.com/kumahq/kuma/pull/11104.
ComputeLabels isn't called in this case.
Also moved MeshService e2e tests to use the generated MeshServices.
=> fix(MeshService): add mesh label to generated universal, use local zone in HostnameGenerator if zone label missing

test/framework/debug.go
There are situations where we are calling `Debug*` helper e2e framework functions multiple times. So far if one of them would fail, it stops other from execution. This commit changes this behavior to just log warning in such situations.
- It won't
=> ci(e2e/framework): don't fail when some debug commands will fail

UPGRADE.md, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshexternalservices.yaml, docs/generated/openapi.yaml, docs/generated/raw/crds/kuma.io_meshexternalservices.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/meshexternalservice.go, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.input.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.output.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-without-extension-valid.input.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go, pkg/core/resources/apis/meshexternalservice/k8s/crd/kuma.io_meshexternalservices.yaml, pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go
closes https://github.com/kumahq/kuma/issues/11132
It's in experimental until 2.9 so we're ok to remove it.
=> feat(meshexternalservice): remove unix support

test/framework/debug.go
As Kuma now uses go1.23.1, we are able to get rid of functions related to copy directories in e2e framework debug functions. This commit also includes small changes around log messages.
- it won't
- tested on local machine
=> ci(e2e/framework): refactor debug functions

pkg/core/resources/apis/meshservice/generate/generator.go, test/e2e_env/multizone/meshmultizoneservice/connectivity.go
These aren't added otherwise. `ComputeLabels` isn't called when using the store directly.
=> fix(MeshService): add kuma.io/display-name label to generated MeshService on universal

pkg/plugins/policies/core/xds/meshroute/listeners.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
We don't need the entire legacybackend here.
=> refactor(xds): reduce size of meshroute.DestinationService type

pkg/plugins/runtime/gateway/cluster_generator.go
=> fix(MeshGateway): correct system namespace with real backendref clusters

pkg/core/resources/apis/meshexternalservice/api/v1alpha1/meshexternalservice.go, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go, pkg/plugins/policies/core/xds/meshroute/listeners.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go, pkg/test/resources/builders/meshexternalservice_builder.go, pkg/xds/topology/outbound_test.go, test/e2e_env/universal/meshexternalservice/meshexternalservice.go
needed for or related to https://github.com/kumahq/kuma/pull/11361
=> feat(meshexternalservice): use common protocol field

pkg/plugins/policies/core/matchers/egress.go, pkg/plugins/policies/core/matchers/egress_test.go, pkg/plugins/policies/core/matchers/testdata/egressmatchedpolicies/meshexternalservice/fromtorules/mes-with-mcb-policy-on-egress.golden.yaml, pkg/plugins/policies/core/matchers/testdata/egressmatchedpolicies/meshexternalservice/fromtorules/mes-with-mcb-policy-on-egress.input.yaml
We were not mapping correctly from/to policy to resource rule for egress
=> fix(meshexternalservice): map from/to policy to resource rule for Egress

.github/workflows/_e2e.yaml, test/e2e_env/gatewayapi/conformance_test.go, test/e2e_env/kubernetes/appprobeproxy/probe_proxy.go, test/framework/config.go, test/framework/debug.go, test/framework/k8s.go
* Introduce a `debug` switch on E2E config
* Print pod details for un-available deployments in `DebugKube`
* Add DebugKube for GatewayAPI specs
* Add context info for "App Probe Proxy" specs
- N/A
- Confirmed
- No
- No
=> test(framework): introduce `debug` switch and collect more deploy details on gateway API failures

UPGRADE.md, pkg/plugins/runtime/k8s/webhooks/injector/precheck.go, pkg/plugins/runtime/k8s/webhooks/injector/precheck_test.go
- fixes https://github.com/kumahq/kuma/issues/11108
- Confirmed
- Tested
- Yes, I did.
=> feat(injector): mark yes/no as deprecated for annotation values

.github/workflows/_e2e.yaml
Improve e2e debug artifacts name to avoid conflicts
Solves
- It won't
=> ci(actions): add more segments to artifacts name to avoid conflicts

mk/k3d.mk
=> chore(dev): set all image tags if run on clean branch in k3d/deploy targets

test/e2e/reachableservices/auto_reachable_mesh_services_k8s.go
=> test(e2e): rename colliding 'mesh' and 'ns'

app/kumactl/cmd/install/install_transparent_proxy_validator.go, pkg/transparentproxy/config/config.go, pkg/transparentproxy/config/utils.go, pkg/transparentproxy/transparentproxy.go, pkg/transparentproxy/validate/validator.go, pkg/transparentproxy/validate/validator_test.go
IPv6 validation never worked and this PR prepares validation code to be reused after installation of tproxy
- it won't
- locally tested
=> fix(tproxy/validator): refactor and make validation to work on IPv6

.github/workflows/_e2e.yaml
Some jobs uses the same parameters and differs with only `matrix.parallelRunnerId` so I'm adding it to make sure there won't be conflicts
- it won't
- it doesn't
=> ci(gh/actions): add parallelRunnerId to e2e debug artifact name

pkg/config/loader.go
These logs were unnecessary and could potentially cause deadlocks around initializing kubernetes loggers:
```sh
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
>  goroutine 1 [running]:
>  runtime/debug.Stack()
>      runtime/debug/stack.go:26 +0x64
>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
>      sigs.k8s.io/controller-runtime@v0.19.0/pkg/log/log.go:60 +0xf4
>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName (0x4000215ec0, {0x2b84407, 0x6})
>      sigs.k8s.io/controller-runtime@v0.19.0/pkg/log/deleg.go:147 +0x34
>  github.com/go-logr/logr.Logger.WithName(...)
>      github.com/go-logr/logr@v1.4.2/logr.go:345
>  github.com/kumahq/kuma/pkg/config.NewLoader({0x41988a8, 0x400094e308})
> …
```
=> chore(config/loader): remove logs when loading configs

app/kumactl/cmd/install/install_transparent_proxy.go, app/kumactl/cmd/install/install_transparent_proxy_test.go
If both values `redirect.dns.enabled` and `redirect.dns.captureAll` would be provided in the config yaml via `--config` or `--config-file`, so far we would fail, but it's a correct scenario. We should check if `--redirect-dns` and `--redirect-all-dns-traffic` are not provided together, so we should do it before we'll load config from file.
- it won't
- tested locally
=> fix(transparent-proxy): check DNS related CLI flags earlier

pkg/config/dp-server/config.go, pkg/xds/bootstrap/components.go
=> fix(k8s): always authenticate with latest service account token

test/e2e_env/multizone/meshservice/connectivity.go
=> test(e2e): add cross-zone MeshGateway + MeshService labels test

pkg/plugins/policies/core/jsonpatch/validators/validator.go, pkg/plugins/policies/meshaccesslog/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshfaultinjection/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshmetric/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshproxypatch/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshratelimit/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshretry/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshtcproute/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshtimeout/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshtrace/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/deprecated.go, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mtp.global.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mtp.non-federated.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_zone-mtp.federated.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_zone-mtp.global.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_zone-mtp.non-federated.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mtp.federated.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mtp.global.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mtp.non-federated.golden.yaml
=> chore(kuma-cp): deprecate top-level targetRef kind 'MeshService'

app/cni/pkg/cni/annotations_linux.go, app/cni/pkg/cni/injector_linux.go, app/cni/pkg/cni/main_linux.go, app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/_helpers.tpl, deployments/charts/kuma/templates/cp-configmap.yaml, deployments/charts/kuma/templates/cp-rbac.yaml, deployments/charts/kuma/values.yaml, docs/generated/raw/helm-values.yaml, pkg/config/loader_test.go, pkg/config/plugins/runtime/k8s/config.go, pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml, pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/probes/pod_probe_overrider.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/transparentproxy/config/config.go, pkg/transparentproxy/config/config_executables.go, pkg/transparentproxy/consts/consts.go, pkg/transparentproxy/kubernetes/kubernetes.go, pkg/transparentproxy/kubernetes/kubernetes_config.go, pkg/transparentproxy/kubernetes/kubernetes_test.go
This update enables Kubernetes deployments to use the transparent proxy feature, allowing the configuration to be provided via the `--config` or `--config-file` CLI flags. When `--set transparentProxy.configMap.enabled=true` is set, the configuration will be stored in a ConfigMap. Additionally, you can use the `traffic.kuma.io/transparent-proxy-configmap-name` annotation to specify a different ConfigMap for specific workloads.
Closes: https://github.com/kumahq/kuma/issues/8324
- https://github.com/kumahq/kuma/issues/8324
- it won't
- necessary unit tests updated
- tested locally on k3d cluster with CNI and init containers
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/link …
=> feat(transparent-proxy): allow to use tproxy config from configmap in kubernetes

api/common/v1alpha1/ref.go, pkg/api-server/resource_endpoints.go, pkg/plugins/policies/core/rules/resourcerules.go, pkg/plugins/policies/core/rules/rules.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/compare.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/meshhttproute.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/merge_test.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhttproute/xds/builder.go, pkg/plugins/policies/meshhttproute/xds/configurer.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
Just an improvement I noticed, helpful for understanding semantics of the values passed around.
=> refactor(xds): use type for matches hash more

pkg/plugins/policies/core/xds/meshroute/gateway/gateway.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go, pkg/plugins/runtime/gateway/cluster_generator.go, pkg/xds/envoy/tags/match.go, pkg/xds/generator/zoneproxy/destinations.go, test/e2e_env/kubernetes/gateway/gateway.go, test/e2e_env/multizone/meshmultizoneservice/connectivity.go
By _not_ requiring the call to `FromTargetRef`, this enables `MeshMultiZoneService`.
=> refactor(MeshGateway): don't call unused FromTargetRef

pkg/api-server/resource_endpoints.go, pkg/api-server/testdata/resources/inspect/dataplanes/_rules/meshgateway.golden.json, pkg/api-server/testdata/resources/inspect/dataplanes/_rules/overriding_meshtimeout.golden.json, pkg/api-server/testdata/resources/inspect/dataplanes/_rules/resource_rule_meshtimeout.golden.json, pkg/api-server/testdata/resources/inspect/dataplanes/_rules/resource_rule_meshtimeout_index.golden.json, pkg/api-server/testdata/resources/inspect/dataplanes/_rules/resource_rule_meshtimeout_section.golden.json, pkg/api-server/testdata/resources/inspect/meshgateways/_rules/meshgateway.golden.json, pkg/api-server/testdata/resources/inspect/meshgateways/_rules/meshgateway2.golden.json, pkg/api-server/testdata/resources/inspect/meshgateways/_rules/meshhttproute.golden.json
Should be the resource type of the policy, no the type of targetRef. See changes in golden files for better understanding.
=> fix(inspect-api): `toResourceRules[].origin` contains wrong resource type

pkg/api-server/testdata/resources/crud/put_circuitbreaker_01.golden.json, pkg/api-server/testdata/resources/crud/put_faultinjection_01.golden.json, pkg/api-server/testdata/resources/crud/put_globalsecret_01.golden.json, pkg/api-server/testdata/resources/crud/put_healthcheck_01.golden.json, pkg/api-server/testdata/resources/crud/put_secret_01.golden.json, pkg/api-server/testdata/resources/crud/put_trafficroute_01.golden.json, pkg/api-server/testdata/resources/crud/put_traffictrace_01.golden.json, pkg/core/resources/model/resource.go, pkg/core/resources/model/resource_test.go, pkg/test/resources/builders/meshtimeout_builder.go
Changes:
* stop adding `kuma.io/zone`, `kuma.io/origin` and `kuma.io/env` label to resources that can't be originated on zone (like Mesh and old source/destination policies)
=> fix(kuma-cp): couldn't use `to[].targetRef: Mesh` on non-federated zones

pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshtls/plugin/v1alpha1/testdata/gateway-tls-version-and-cipher.clusters.golden.yaml, pkg/plugins/policies/meshtls/plugin/v1alpha1/testdata/gateway-tls-version-and-cipher.listeners.golden.yaml, pkg/plugins/policies/meshtls/plugin/v1alpha1/testdata/gateway-tls-version-and-cipher.policy.yaml, pkg/plugins/policies/meshtls/plugin/v1alpha1/testdata/gateway-tls-version-and-cipher.routes.golden.yaml, test/e2e_env/kubernetes/gateway/gateway.go
While testing, I noticed that the built-in gateway isn't supported. This PR adds support for configuring Gateway clusters with TLS versions and ciphers.
d8b489d4e304bfcc4e9dac9bb3ccadbc02dc41f0 implementation 
fdc419a824a97961dfbb6843fbc1ceea600f2a2b unit test + golden files 
4b2c978538d052c1b62f3a3da59868bbe9e30123 e2e test
=> feat(meshtls): added builtin gateway implementation

pkg/test/resources/builders/mesh_builder.go, test/e2e_env/kubernetes/gateway/delegated.go, test/e2e_env/kubernetes/meshexternalservice/meshexternalservice.go
Added option to map resource into kube yaml and changed 2 tests to show it.
=> test(e2e): add function mapping Mesh resource to KubeYaml

pkg/api-server/resource_endpoints.go, pkg/api-server/server.go, pkg/core/bootstrap/bootstrap.go, pkg/core/managers/apis/dataplane/dataplane_manager.go, pkg/core/managers/apis/dataplane/dataplane_manager_test.go, pkg/core/resources/model/resource.go, pkg/core/resources/model/resource_test.go, pkg/plugins/runtime/k8s/webhooks/defaulter.go
While investigating the failure of the universal test (https://github.com/kumahq/kuma/pull/11425), I discovered that labels were not being set for dataplanes on the universal environment. In the universal setup, users can send the Dataplane object in the metadata, which is later processed by the control plane. On Kubernetes, we call ComputeLabels in the defaulter, which sets the labels, but this was not happening for the universal environment. In the universal setup, tags were only being set on the inbounds and not on the entire dataplane object. I've added a flow to apply tags to the whole dataplane.
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an …
=> fix(kuma-cp): add labels to dataplane object on universal

pkg/xds/context/mesh_context_builder.go
We should only use labels to index services. Right now we use labels as well as tags from selectors.
=> fix(meshservices): use only labels to index services

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml, app/kumactl/data/install/k8s/metrics/prometheus/server.yaml
Prometheus is broken by default with Exclusive MeshService.
It's because we install prometheus and grafana in the mesh by default.
The `mesh-observability` namespace has disabled sidecar injection. We enable this for a couple of services. In this case, we had to annotate those services with `kuma.io/mesh` for CP to know that it should convert those for MeshSerivce
=> feat(observability): default installation with exclusive mesh services

api/common/v1alpha1/ref.go, pkg/kds/context/context.go, pkg/kds/context/context_test.go, pkg/kds/features.go, pkg/kds/v2/client/stream.go, pkg/plugins/policies/donothingpolicy/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshaccesslog/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshfaultinjection/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshmetric/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshpassthrough/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshproxypatch/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshratelimit/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshretry/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshtcproute/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshtimeout/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshtls/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshtrace/api/v1alpha1/zz_generated.helpers.go, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/zz_generated.helpers.go, tools/policy-gen/generator/cmd/helpers.go
Fixes: #11426
Since `Policy` interface exposes only function `GetTargetRef` which returns default targetRef, we don't have an easy way of checking if policy had targetRef set. To deal with this, we can introduce `UsesSyntacticSugar` to make sure we are not syncing policies not supported by older version. This can be easily removed in two versions
=> fix(kuma-cp): do not sync policies with empty topLevel targetRef to zones that does not support it

pkg/plugins/runtime/gateway/cluster_generator.go
=> chore(MeshGateway): fix output in log message

test/e2e_env/multizone/meshmultizoneservice/connectivity.go, test/e2e_env/multizone/meshservice/connectivity.go, test/e2e_env/universal/meshaccesslog/meshaccesslog.go, test/e2e_env/universal/meshhealthcheck/policy.go, test/e2e_env/universal/meshretry/http.go
It appears that we have two `MeshGateway` resources with the name `edge-gateway`. Each one can override the other's selector, potentially causing other tests to fail. Since `MeshGateway` is not [namespace-scoped](https://github.com/kumahq/kuma/blob/master/docs/generated/raw/crds/kuma.io_meshgateways.yaml#L17), I have renamed the resources to avoid conflicts. I also changed the route name to avoid conflicts. 
On Universal, I renamed the resources because there were already resources with the same name.
=> test(e2e): use different name for gateway resource

pkg/api-server/testdata/resources/inspect/policies/_resources/dataplanes/meshtimeout_consumer_dataplanes.golden.json, pkg/plugins/policies/core/matchers/dataplane.go
[This PR](https://github.com/kumahq/kuma/pull/11425) introduced an error that caused ExternalServices to not be properly matched. Autoreachable services build a graph of relationships based on a fake Dataplane, which lacks labels, leading to a nil pointer issue. Additionally, the zone tag is not supported for autoreachable services, making its introduction unnecessary. Finally, since ExternalService is a global resource, the origin label will not be added.
=> fix(policy): verify zone if dpp origin is zone and metadata exists

pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go, pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin_test.go, test/e2e_env/multizone/meshservice/connectivity.go
=> fix(MeshGateway): handle unresolved real backendRefs

.github/workflows/build-test-distribute.yaml, app/kumactl/cmd/install/render_helm_files.go, test/e2e_env/kubernetes/appprobeproxy/probe_proxy.go
These were flagged by CodeQL so getting them fixed
=> chore(codeql): fix minor lint issues

pkg/plugins/policies/meshtls/api/v1alpha1/testdata/full-valid-no-top-target.input.yaml, pkg/plugins/policies/meshtls/api/v1alpha1/validator.go, pkg/plugins/policies/meshtls/api/v1alpha1/validator_test.go
We had no default to Mesh top level target ref.
=> fix(meshtls): do not panic when no topLevel targetRef

test/e2e_env/kubernetes/gateway/delegated/meshhttproute.go
I noticed that the test failed once. I'm increasing the number of requests to make the results more consistent.
=> test(e2e): increase number of requests to make it more stable

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshtlses.yaml, docs/generated/openapi.yaml, docs/generated/raw/crds/kuma.io_meshtlses.yaml, pkg/plugins/policies/meshtls/api/v1alpha1/meshtls.go, pkg/plugins/policies/meshtls/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtls/k8s/crd/kuma.io_meshtlses.yaml, pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtls/plugin/v1alpha1/testdata/permissive-no-mtls.listeners.golden.yaml, pkg/plugins/policies/meshtls/plugin/v1alpha1/testdata/strict-no-mtls.listeners.golden.yaml
We were incorrectly configuring tls inbound even when mtls was enabled. Added a check and used default mesh mode in the next steps.
=> fix(meshtls): don't configure listener when mesh mtls disabled

pkg/core/resources/apis/mesh/validators.go, pkg/core/resources/apis/mesh/validators_test.go
We are not always configuring policies in a system namespace when MES is created. We want users to be able to select MES in policies on their namespaces, but in order to do it they need to be able to specify namespace in `to.targetRef` section
=> fix(kuma-cp): allow specifying namespace when targeting MeshExternalService in policies

pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/meshmultizoneservice.go, pkg/core/resources/apis/meshmultizoneservice/status_updater.go, pkg/core/resources/apis/meshmultizoneservice/status_updater_test.go
Fix #11470
It was right when we added it, because it was just name which was a hashed name. It was then modified to also add namespace, zone and mesh here, so just sorting by name is not enough
=> fix(meshmultizoneservice): order of matched mesh services

pkg/core/validators/common_validators.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/validation.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/validation_test.go, pkg/plugins/policies/meshtcproute/api/v1alpha1/validator.go, pkg/plugins/policies/meshtcproute/api/v1alpha1/validator_test.go
=> feat(Mesh*Route): require port with MeshMultiZoneService backends

test/e2e_env/universal/gateway/gateway.go, test/e2e_env/universal/gateway/utils.go, test/e2e_env/universal/meshaccesslog/meshaccesslog.go, test/e2e_env/universal/observability/meshtrace.go
For gateway utils it was using a helper which didn't include good offsets
This resulted in hard to comprehend test failure.
Improved this and rewrote gateway test with externalService to try to fix flakiness
=> test(e2e): improve gateway matchers

pkg/plugins/policies/core/matchers/egress_test.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go, test/e2e_env/universal/meshexternalservice/meshexternalservice.go
xref https://github.com/kumahq/kuma/issues/11472
xrel https://github.com/kumahq/kuma/issues/8417
xrel https://github.com/kumahq/kuma/issues/11078
=> chore(meshexternalservice): prevent targeting mesh circuit breaker by validation

pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator.go, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go, pkg/test/resources/validators/validation.go, test/e2e_env/universal/meshexternalservice/meshexternalservice.go
xref https://github.com/kumahq/kuma/issues/11472
xrel https://github.com/kumahq/kuma/issues/8417
xrel https://github.com/kumahq/kuma/issues/11078
=> chore(meshloadbalancingstrategy): prevent targeting meshexternalservice by validation

pkg/plugins/policies/core/matchers/egress_test.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go, test/e2e_env/universal/meshexternalservice/meshexternalservice.go
xref https://github.com/kumahq/kuma/issues/11472
xrel https://github.com/kumahq/kuma/issues/8417
xrel https://github.com/kumahq/kuma/issues/11078
=> chore(meshhealthcheck): prevent targeting meshexternalservice by validation

pkg/core/resources/apis/donothingresource/api/v1alpha1/zz_generated.resource.go, pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/zz_generated.resource.go, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/meshexternalservice.go, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/zz_generated.resource.go, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/meshmultizoneservice.go, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/zz_generated.resource.go, pkg/core/resources/apis/meshservice/api/v1alpha1/meshservice.go, pkg/core/resources/apis/meshservice/api/v1alpha1/zz_generated.resource.go, pkg/core/resources/model/resource.go, pkg/plugins/policies/donothingpolicy/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshaccesslog/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshfaultinjection/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshmetric/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshpassthrough/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshproxypatch/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshratelimit/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshretry/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshtcproute/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshtimeout/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshtls/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshtrace/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/zz_generated.resource.go, pkg/xds/context/mesh_context_builder.go, tools/policy-gen/generator/cmd/core_resource.go, tools/policy-gen/generator/pkg/parse/policyconfig.go
* add Descriptor field to identify resources that can be referenced in 'to'
=> fix(inspect-api): add missing resources to BaseMeshContext

test/e2e/federation/federation_suite_test.go, test/e2e_env/universal/universal_suite_test.go
=> chore(e2e): supplement FlakeAttempts for flaky tests

tools/releases/version.sh
https://github.com/envoyproxy/envoy/releases/tag/v1.28.7
=> chore(deps): upgrade envoy to 1.28.7

test/framework/debug.go, test/framework/envs/universal/env.go, test/framework/universal_app.go, test/framework/universal_cluster.go
Similar to the kube debuggability PR: https://github.com/kumahq/kuma/pull/11466 , This PR tries to enable `debug` log level on both CP and DP when `Config.Debug` switch is enabled.
To export CP logs, the PR also copies all logs generated in the E2E running instead of just generated from `Describe`. 
- N/A
- Confirmed
- No
- No
=> test(framework): enable debug log for both CP and DP on universal

test/e2e/federation/federation_kubernetes.go
This isn't going to fix the flakes but it's incorrect as is
=> test(e2e): use proper skip default mesh setting in Kubernetes federation tests

pkg/core/resources/apis/mesh/validators.go, pkg/plugins/policies/meshtimeout/api/v1alpha1/validator_test.go
fix: https://github.com/kumahq/kuma/issues/11499
=> fix(meshexternalservice): allow defining only name or labels

app/kumactl/cmd/export/export.go, app/kumactl/cmd/export/testdata/export-no-dp.golden.yaml, app/kumactl/cmd/export/testdata/export.golden.yaml
This way users have the opportunity to manage all policies themselves at the global level.
> Changelog: fix(federation): set skipCreatingInitialPolicies on exported Meshes
> This way users have the opportunity to manage all policies themselves at the global level.
=> fix(federation): set skipCreatingInitialPolicies on exported Meshes

test/framework/k8s_cluster.go
This is probably the expected behavior.
=> test(e2e): also apply Kuma deploy envs with Helm

test/framework/envs/universal/env.go
When the debug level logs are enbled,too many log entries make the GitHub log view truncate.
We now export the CP logs into artifacts, so don't need to print to stdout any more.
- N/A
- No
- No
=> test(framework): dont print CP logs to stdout on Universal as they can be too long

app/kumactl/cmd/export/export.go, app/kumactl/cmd/export/testdata/export-kube.golden.yaml, app/kumactl/cmd/export/testdata/export-no-dp.golden.yaml, app/kumactl/cmd/export/testdata/export.golden.yaml
This fixes changes introduced by #11497. Universal checks whether a mesh exists before allowing a secret to be created.
=> fix(kumactl): declare meshes before secrets when exporting

api/openapi/specs/common/resource.yaml, api/openapi/types/common/zz_generated.resource.go, docs/generated/openapi.yaml
This PR alters instances of `type: object` (with no additional information) to use:
1.  `additionalProperties: true` in the case where we are saying an arbitrary object/`interface {}` (i.e. TS `Record<string, unknown>`)
2. `additionalProperties.type: string` where we are saying a `map[string]string` (i.e. TS `Record<string, string>`)
Generated files generated using `make generate/oas`.
Previous to this PR these properties were using `never` in the produced frontend TS which was causing issues.
---
**Please note:** I will probably add more amends to this PR once I've had an initial review, so initially I'm looking for comment so I know I'm doing things correctly so I can go ahead and do more before getting a final review ~(see inline question)~
---
- Don't forget `ci/` labels to run …
=> fix(inspect-api): amend openapi types for arbitrary objects

test/e2e_env/gatewayapi/conformance_test.go, test/framework/envs/multizone/env.go, test/framework/universal_cluster.go
Solving two issues:
1. When `ENABLE_E2E_DEBUG_GLOBALLY` is turned on, there is too much logs flooding the GHA output view and it's truncated (fixing again, a further step following [a previous PR](https://github.com/kumahq/kuma/pull/11506))
2. We can't collect logs from pods from GatewayAPI conformance for the moment as they are cleaned up after running. So turn off cleaning up when debug is enabled.
- A helper effort when fixing flakiness: https://github.com/kumahq/kuma/actions/runs/10986369217/job/30500941118
- Confirmed
- Tested
- No need
- No
=> test(framework): smarter logs on universal, multizone and gatewayapi

test/e2e_env/gatewayapi/conformance_test.go
Trying to fix a timeout introduced by a previous PR.
The gatewayapi E2E case does not complete, so reverting that part for the moment to unblock the work.
 ### Checklist prior to review
- https://github.com/kumahq/kuma/actions/runs/11005458911/job/30559825392#step:12:46812
- No
- No
=> test(gatewayapi): cleanup resources to unblock the gatewayapi job

.github/workflows/_build_publish.yaml
It seems that 15mins is not enough for Kong Mesh. Maybe it's because of custom runners, but it takes more time to execute setup go (up to 3mins) as well as building images
=> ci(gha): bump timeout for image build

pkg/plugins/policies/core/xds/meshroute/gateway/gateway.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/real-mesh-service-meshhttproute.gateway_cluster.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go
=> fix(MeshGateway): apply policies to clusters from real backendRefs

api/openapi/specs/common/resource.yaml, api/openapi/types/common/zz_generated.resource.go, docs/generated/openapi.yaml, mk/generate.mk
1. Amends `toResourceRules[].conf` to be an array of structs rather than a struct
2. Adds a makefile target for easier full generation of all OpenAPI related code (i.e. _both_ the golang and the `docs` YAMLs which typescript uses)
=> fix(inspect-api): `conf` should be an array of unknown structs

test/e2e_env/kubernetes/externalservices/externalservices.go, test/e2e_env/kubernetes/meshtcproute/test.go
* rework MeshTCPRoute to check if there are responses from 4 instances
* change resource name
=> test(e2e): avoid name conflict and simplfy logic

app/kumactl/cmd/export/export.go, app/kumactl/cmd/export/testdata/export-kube.golden.yaml
Instead only export the "empty" Mesh first on Universal.
=> fix(kumactl): don't export full Mesh before secrets on Kubernetes

.github/workflows/_build_publish.yaml
We hit rate limiting a lot in Kong Mesh.
Temporarily skip docker scan until sec team figure out trivy image cache / registry
=> ci(workflow): skip cis docker scan

pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/only-ipv4-rules.clusters.golden.yaml, pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/only-ipv4-rules.listener.golden.yaml, pkg/plugins/policies/meshpassthrough/plugin/xds/configurer.go
While debugging the tests, I noticed a log entry:
```yaml
error adding listener 'outbound:passthrough:ipv6': no filter chains specified
```
This leads to the case where the MeshPassthrough policy might consist of only IPv4 or IPv6-specific entries. In such cases, the current logic removes all filter chains and initializes a new, empty filter chain. If there’s no match for the specific IP protocol, the list could end up empty, which may cause Envoy to reject the configuration. I've added a change to check if there are rules for a specific IP protocol, and only trigger the logic if rules exist.
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-us …
=> fix(meshpassthrough): don't remove all filters chains

pkg/core/xds/resource.go, pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/01.golden.yaml, pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/02.golden.yaml, pkg/plugins/policies/core/rules/rules.go, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin_test.go, pkg/plugins/runtime/gateway/cluster_generator.go
Follow up PRs will introduce support for individual policies
Almost all the changes are because of reformatting in tests and golden files, go commit by commit
See final 3 commits of https://github.com/kumahq/kuma/pull/11541 for how it will look in policies
=> refactor(MeshGateway): add ResourceRules to GatewayRules, ResourceOrigin and Protocol to clusters

test/e2e_env/universal/universal_suite_test.go
xref https://github.com/kumahq/kuma/issues/11546
Default traffic route seems to fix the fact that we were missing clusters. However, we see conntrack issue as I mentioned in my PR https://github.com/kumahq/kuma/pull/11523
=> test(e2e): cover conntrack issue

test/e2e/helm/kuma_helm_upgrade_multizone.go
=> fix(e2e): don't reuse namespace for helm upgrade test

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshtraces.yaml, docs/generated/openapi.yaml, docs/generated/raw/crds/kuma.io_meshtraces.yaml, pkg/plugins/policies/meshtrace/api/v1alpha1/meshtrace.go, pkg/plugins/policies/meshtrace/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtrace/k8s/crd/kuma.io_meshtraces.yaml
=> fix(MeshTrace): invalid sampling default values

test/framework/deployments/observability/kubernetes.go
We don't need to wait for observability namespace termination, it can be best effort, and even if we fail it will be removed alongside with cluster at the end of tests
=> fix(e2e): dont wait for observability namespace termination

pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/real-mesh-service-target-real-mesh-service-meshhttproute.gateway_cluster.golden.yaml
Needs https://github.com/kumahq/kuma/pull/11541
=> fix(MeshHealthCheck): apply to real resource targeted policies with MeshGateway

pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/testdata/real-MeshService-targeted-to-real-MeshService.gateway_cluster.golden.yaml
=> fix(MeshCircuitBreaker): apply to real resource targeted policies with MeshGateway

test/e2e_env/gatewayapi/conformance_test.go
GatewayAPI resoruces are cleaned up even when test fails. This prevents us from collecting debug info from the cluster.
When simply set `CleanupBaseResources` to `false`, it will hang because that the next statement `g.Expect(cluster.DeleteKuma()).To(Succeed())` tries to remove the `gatewayclass/kuma` when it's still being referenced in some namespace that is not cleaned up.
This resolves the issues introduced by [the PR of trying to diable cleanup](https://github.com/kumahq/kuma/pull/11510) and replaces the temporary solution in the [previous PR](https://github.com/kumahq/kuma/pull/11527).
- N/A
- Confirmed
- No
- No
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pu …
=> test(gatewayapi): cleanup resources manually after dumping debug info

pkg/plugins/policies/core/xds/meshroute/clusters.go, pkg/xds/context/mesh_context_builder.go, pkg/xds/context/resources.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/secrets/generator.go, pkg/xds/generator/secrets/generator_test.go, pkg/xds/sync/dataplane_proxy_builder.go, test/e2e_env/kubernetes/meshtimeout/meshtimeout.go, test/framework/setup.go
=> fix(resourcerules): add own mesh to the MeshContext, so it could be successfully resolved

go.mod
so that we won't get surprised by a dependabot update and someone merging it by mistake https://github.com/kumahq/kuma/pull/11521#pullrequestreview-2330229564
=> chore(deps): replace all go control plane versions

test/framework/universal_app.go
this is a bit hacky but works:
```
docker logs kuma-3_test-server_WP7yST | head -n 30
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Accepted none for root from 172.18.0.1 port 55380 ssh2
syslogin_perform_logout: logout() returned an error
Received disconnect from 172.18.0.1 port 55380:11: disconnected by user
Disconnected from user root 172.18.0.1 port 55380
Accepted none for root from 172.18.0.1 port 55384 ssh2
syslogin_perform_logout: logout() returned an error
Received disconnect from 172.18.0.1 port 55384:11: disconnected by user
Disconnected from user root 172.18.0.1 port 55384
Accepted none for root from 172.18.0.1 port 55386 ssh2
syslogin_perform_logout: logout() returned an error
Received disconnect from 172.18.0.1 port 55386:11: disconnected by user …
```
=> chore(debug): get envoy logs in docker logs on universal tests

mk/build.mk
=> chore(deps): bump coredns from v1.11.1 to v1.11.3

UPGRADE.md, pkg/plugins/policies/meshaccesslog/api/v1alpha1/validator.go, pkg/plugins/policies/meshaccesslog/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshaccesslog/plugin/xds/clusters.go
This is a breaking change. The access logging is configured at the gateway listener level, which makes it impossible to configure depending on the traffic destination.
=> fix(MeshAccessLog): strengthen validation for MeshAccessLog and MeshGateway

.github/workflows/_test.yaml, test/e2e/zoneegress/externalservices/e2e_suite_test.go
We have a lot of arm runners and starve amd runners. We have very high trust in our arm support so comparing amd and arm on the same test suite is a little wasteful.
We therefore only run e2e tests on old versions of k8s on arm64 this removes a few entries in the matrix and improve utilization of arm runners
Also move large e2e tests to arm64
Fix https://github.com/kumahq/kuma/issues/11562
=> ci(e2e): run `K8S_MIN_VERSION` tests on arm64

test/framework/docker.go
While running universal tests on macOS, you might notice that tests randomly fail with the following error message
```
<*net.AddrError | 0x14000d97280>:
missing port in address
{
Err: "missing port in address",
Addr: "",
```
During debugging, I discovered that sometimes the port is not available immediately, but no error is thrown. To handle this, I introduced a method that retries the call up to 5 times to check if the port becomes available.
=> test(e2e): retry when there is no port

pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/real-MeshService-targeted-to-real-MeshService.gateway.clusters.golden.yaml, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/real-MeshService-targeted-to-real-MeshService.gateway.endpoints.golden.yaml, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/real-MeshService-targeted-to-real-MeshService.gateway.listeners.golden.yaml, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/real-MeshService-targeted-to-real-MeshService.gateway.routes.golden.yaml
=> fix(MeshLoadBalancingStrategy): apply to real resource targeted policies with MeshGateway

test/framework/k8s_cluster.go
It's working
```
[2024-09-27 09:29:28.174][34][debug][connection] [source/common/network/connection_impl_base.cc:53] [Tags: "ConnectionId":"20"] setting delayed close timer with timeout 1000 ms
```
=> chore(debug): set k8s cluster default egress log level to debug

pkg/test/resources/builders/mesh_builder.go, test/e2e_env/kubernetes/meshtimeout/meshtimeout.go
Improve general tests by removing repetition and systematically delete all policies at the start.
Run some tests that work only on Exclusive and not with other modes
=> test(e2e): improve meshtimeout kubernetes tests

.github/workflows/_e2e.yaml
prolong debug artifacts retention so they do not disappear over the weekend
=> ci(debug): prolong debug artifacts retention

pkg/core/resources/apis/meshservice/generate/generator_test.go
Fixes flaky test at:
https://github.com/kumahq/kuma/actions/runs/10946133312/job/30392313021#step:6:183
The original asserion can overflow the grace period on resouces, now we strictly read the start time from the resource label to prevent the overflow.
- N/A
- Confirmed
- No
- No
=> test(meshservice): fix flaky tests on resource grace period

test/framework/k8s_cluster.go
We met the `Namespace` deletion timeout but got no obvious messages, let's output the `Namespace.Status.Condition` to see the usefull messages.
Here's a error that we hit in one CI, we spent 360s to delete that namespace and hit the timeout
```text
Zone and Global with Helm chart should deploy Zone and Global on 2 clusters 2024-09-27T14:16:22Z retry.go:91: Wait for kuma-test Namespace to terminate.
Zone and Global with Helm chart should deploy Zone and Global on 2 clusters 2024-09-27T14:16:22Z client.go:45: Configuring Kubernetes client using config file /home/ubuntu/.kube/kind-kuma-2-config with context 
Zone and Global with Helm chart should deploy Zone and Global on 2 clusters 2024-09-27T14:16:22Z retry.go:103: Wait for kuma-test Namespace to terminate. returned an error: Namespace …
```
=> test(e2e): output namespace last condition once met deletion timeout

pkg/core/resources/apis/mesh/dataplane_helpers.go
When `ResolveBackendRef` returns nil we don't want to add outbound at all instead of adding outbound with `Resource: nil`.
=> fix(kuma-cp): panic when DPP uses outbounds with 'backendRef.Labels' and no meshservices were matched

pkg/core/xds/inspect/rules.go
Since '/rules' is an old endpoint, this PR doesn't try to compute RuleAttachment for new outbounds with backendRef. It skips such outbounds to avoid panic. 
=> fix(inspect-api): don't panic when outbound doesn't have 'kuma.io/service' tag

test/e2e/helm/kuma_helm_upgrade_multizone.go, test/framework/k8s_cluster.go
We've tested this mechanism in `TriggerDeleteNamespace` so it can be safely used in sync version of this method
=> test(e2e): speed up namespace termination

api/openapi/specs/common/resource.yaml, api/openapi/types/common/zz_generated.resource.go, docs/generated/openapi.yaml, pkg/api-server/resource_endpoints.go, pkg/api-server/testdata/resources/inspect/dataplanes/_rules/resource_rule_meshtimeout_exclusive.golden.json, pkg/api-server/testdata/resources/inspect/dataplanes/_rules/resource_rule_meshtimeout_exclusive.input.yaml
=> fix(inspect-api): don't set 'toRules' when `meshServices.mode: Exclusive`

go.mod
Proper fix for https://github.com/kumahq/kuma/pull/11412 / https://github.com/golang/go/issues/69110
https://github.com/golang/go/issues?q=milestone%3AGo1.23.2+label%3ACherryPickApproved
=> chore(deps): manually bump go to 1.23.2

go.mod
=> chore(deps): bump golang from 1.22.7 to 1.22.8

test/e2e/federation/federation_suite_test.go
This should be fixed now
Fix #11420
=> test(e2e): remove flake attempts on federation tests

test/e2e/externalservices/externalservices_kubernetes_without_egress.go, test/framework/k8s_cluster.go
Gather more data about namespace termination
=> test(e2e): print debug info on namespace delete

.github/workflows/ci-stability.yaml
Introduce GHA action to check CI stability.
It's this https://github.com/kumahq/kuma/pull/11589 but without me leaving the laptop running the script.
The action runs every 2h outside of working hours during weekdays (feel free to suggest better hours) and every 2h on the weekends. It adds a commit to PRs with `ci/verify-stability` label. Additionally, if there is `ci/verify-stability-merge-master` we merge master.
The use case is that we can have a "long-running" PR with both labels so it checks the stability of the current master branch.
You can also do the same but on a PR. Let's say we introduce a risky change. We can remove a label on our long-running PR and instead put `ci/verify-stability` on the PR with a risky change.
Potential improvements:
* Instead of every 2h, we could track …
=> ci(gha): verify CI stability action

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/check.yaml
This is so that we can use the PR description as a commit message. Also the checklist should be checked by the reviewer.
xrel https://github.com/Kong/team-mesh/issues/302
=> ci(github): move checklist to a PR

mk/k3d.mk
Metrics server was enabled in this PR https://github.com/kumahq/kuma/pull/9892/files#diff-6a9a6d7b0c33e516a1579d4ea2ccdfdbec5bd689d4f15bcab302e2a80b0d7ee4L45 but it's not clear why.
Every now and then we have a flake in e2e tests where we cannot terminate namespace. The reason is
```
NamespaceCondition{Type:NamespaceDeletionDiscoveryFailure,Status:True,LastTransitionTime:2024-10-03 18:48:53 +0000 UTC,Reason:DiscoveryFailed,Message:Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request,}
```
An example of such run https://github.com/kumahq/kuma/actions/runs/11167497534/job/31044250187
According to the Internet, communication to the metrics server is broken (the metrics …
=> test(e2e): disable metrics server in k3d

.github/workflows/check.yaml, test/framework/k8s_cluster.go
Very rarely we see a flake on the CI that looks like this
```
2024-10-03T13:54:30.911Z	ERROR	kuma-cp.run	problem running Control Plane	{"error": "error running Kubernetes Manager: no matches for kind \"MeshCircuitBreaker\" in version \"kuma.io/v1alpha1\"", "errorVerbose": "no matches for kind \"MeshCircuitBreaker\" in version \"kuma.io/v1alpha1\"\nerror running Kubernetes Manager\ngithub.com/kumahq/kuma/pkg/plugins/bootstrap/k8s.(*kubeComponentManager).Start\n\tgithub.com/kumahq/kuma/pkg/plugins/bootstrap/k8s/plugin.go:208\ngithub.com/kumahq/kuma/app/kuma-cp/cmd.newRunCmdWithOpts.func1\n\tgithub.com/kumahq/kuma/app/kuma-cp/cmd/run.go:170\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13 …
```
=> test(e2e): wait for CRDs

.github/workflows/_test.yaml
We are not utilizing arm runners enough. Right now we have 33 arm runners idle and a big queue.
Isolated/old e2e is half of runs of our e2e tests
Let's move them to arm
No issue. CI queues.
=> test(e2e): move isolated e2e to arm

.github/workflows/build-test-distribute.yaml
We're sometimes seeing long queue times and that can be partially due to people pushing to PRs often.
I'm adding a concurrency group to cancel jobs in progress on PRs only.
xrel https://github.com/kumahq/kuma/pull/10146/files
=> chore(gha): cancel in progress on prs to not clog up CI

.github/workflows/ci-stability.yaml
CI stability action was broken. It worked when I tested it on my separate repo, because my PR description did not contain `'` character. Once you have `'` then `echo '${{ steps.get_prs.outputs.data }}'` is broken. We cannot change it to `echo "${{ steps.get_prs.outputs.data }}"`, because then we cannot have `"` in the output (it's json!).
The solution is to use `gh` cli, and use only relevant data in the file.
No issue, broken GHA.
=> ci(gha): fix retriving PR data for ci stability

.github/workflows/_test.yaml
We scaled down number of arm runners on our big ARM host for self-hosted runners. It's not 14/14, so we should also rebalance the test so it's equal
=> test(e2e): rebalance arm and amd runners

pkg/intercp/catalog/heartbeat_component.go
We were logging a bool instead of the address.
Found during a heartbeat problem - xrel https://github.com/kumahq/kuma/issues/11718
Change the bool to the address.
Nothing really.
=> chore(heartbeat): properly log new leader address

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshexternalservices.yaml, deployments/charts/kuma/crds/kuma.io_meshmultizoneservices.yaml, deployments/charts/kuma/crds/kuma.io_meshservices.yaml, docs/generated/raw/crds/kuma.io_meshexternalservices.yaml, docs/generated/raw/crds/kuma.io_meshmultizoneservices.yaml, docs/generated/raw/crds/kuma.io_meshservices.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/meshexternalservice.go, pkg/core/resources/apis/meshexternalservice/k8s/crd/kuma.io_meshexternalservices.yaml, pkg/core/resources/apis/meshexternalservice/k8s/v1alpha1/zz_generated.types.go, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/meshmultizoneservice.go, pkg/core/resources/apis/meshmultizoneservice/k8s/crd/kuma.io_meshmultizoneservices.yaml, pkg/core/resources/apis/meshmultizoneservice/k8s/v1alpha1/zz_generated.types.go, pkg/core/resources/apis/meshservice/api/v1alpha1/meshservice.go, pkg/core/resources/apis/meshservice/k8s/crd/kuma.io_meshservices.yaml, pkg/core/resources/apis/meshservice/k8s/v1alpha1/zz_generated.types.go, tools/policy-gen/generator/cmd/k8s_resource.go, tools/policy-gen/generator/pkg/parse/policyconfig.go
Always nice to not have to go to the YAML
```
❯ kubectl get meshservice -A
NAMESPACE     NAME                        HOSTNAME
kuma-demo     demo-app
kuma-demo     redis
kuma-demo     redis-v1
kuma-demo     redis-v2
kuma-system   demo-app-dxxvv72fvx2wcx9d   demo-app.kuma-demo.svc.east.mesh.local
kuma-system   redis-x5874724v674bxb2      redis.kuma-demo.svc.east.mesh.local
```
=> feat(Mesh*Service): add first hostname as kubectl column

test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_egress.go, test/e2e_env/universal/trafficroute/traffic_route.go
Envoy is not stable enough with the LB weights, we need to loosen up our assertions: https://github.com/kumahq/kuma/actions/runs/11248559631/job/31274149810#step:12:8505
Change 10 error bars to 25.
=> test(lb): loosen up assertion lb weights

.github/workflows/_test.yaml
Reverts kumahq/kuma#11689 because CI is really unstable on arm
=> Revert "test(e2e): move isolated e2e to arm"

pkg/plugins/runtime/k8s/plugin.go
This reconciler shouldn't run on global.
I'm at least seeing errors:
```
2024-10-09T09:22:39.277Z	ERROR	kube-manager	Reconciler error	{"controller": "kuma-mesh-service-controller", "controllerGroup": "", "controllerKind": "Service", "Service": {"name":"kube-dns","namespace":"kube-system"}, "namespace": "kube-system", "name": "kube-dns", "reconcileID": "101c399a-4733-4afe-b4f5-f7a3ae25b7eb", "error": "could not delete MeshService: meshservices.kuma.io \"kube-dns\" is forbidden: User \"system:serviceaccount:kuma-system:kuma-control-plane\" cannot delete resource \"meshservices\" in API group \"kuma.io\" in the namespace \"kube-system\": 
```
=> fix(kuma-cp): don't run MeshService reconciler on global

.github/workflows/ci-stability.yaml
We need to pass PAT to trigger a CI on commits we push
tested from a branch here https://github.com/kumahq/kuma/pull/11672
Noticed CI not being triggered
=> test(e2e): ci stability app token

pkg/core/resources/apis/mesh/dataplane_validator.go, pkg/core/resources/apis/mesh/dataplane_validator_test.go, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/helpers.go, pkg/core/resources/apis/meshservice/api/v1alpha1/helpers.go, pkg/xds/context/context.go, test/e2e_env/multizone/reachablebackends/reachablebackends_meshservices.go
While testing reachable backends, I noticed that when a port is specified but the port name is not a string (i.e., it's not the actual port name), I got 0 clusters.
Once we retrieve a ResourceIdentifier and the port is provided, we look up the MeshService or MeshMultiZoneService from the map of resources and attempt to find a matching port name, if one exists. If no port name is found, we treat the port as a string.
Noticed once testing
=> fix(kuma-cp): map port to section name for reachable backends

test/framework/k8s_controlplane.go
From time to time we were experiencing issues in upgrade test because we were starting port forward to wrong pod of kuma-cp, pod that was already terminating. This fix should mitigate this issue
port forward to service instead of pod
=> fix(e2e): port forward to service instead of pod of kuma-cp to improve test stability

pkg/plugins/policies/meshtrafficpermission/graph/reachable_graph.go
When auto reachable services are enabled, we had no MeshMultiZoneServices.
Support for MeshMultiZoneService for auto reachable services is not there and we shouldn't filter out MeshMultiZoneService.
Auto reachable services therefore works this way:
- For MeshService it works
- For MeshExternalService and MeshMultiZoneService are just ignored and therefore always present regardless of MTP
Reported during tests
Proper fix to support auto reachable services tracked in:
- https://github.com/kumahq/kuma/issues/11748
- https://github.com/kumahq/kuma/issues/11077
=> fix(autoreachableservices): do not filter out MeshMultiZoneService

.github/workflows/merge-release-to-master.yaml
As is the job fails because it's taking `release-2.8`, we should just not try to do the merge if we're not merging the right branch.
Don't try to merge, the rest of the job should just proceed as if there's no merge necessary.
=> ci(.github): don't fail merge release to master if versions.yml isn't updated

pkg/plugins/runtime/k8s/controllers/pod_controller_test.go, pkg/plugins/runtime/k8s/controllers/pod_converter.go, pkg/plugins/runtime/k8s/plugin.go
When upgrading from 2.8.4 to 2.9, I noticed that Dataplane labels were not propagated, and the Dataplane object wasn't reconciled.
We introduced a performance optimization that compares an object before adding it to the database on Kubernetes: https://github.com/kumahq/kuma/pull/11327. Unfortunately, this check only covers the Spec and Mesh. In the 2.9 release, we added functionality to set common labels on the Dataplane object: https://github.com/kumahq/kuma/blob/master/pkg/core/managers/apis/dataplane/dataplane_manager.go#L59. The issue is that this is called much later. At the controller level, we had no information about label changes. To fix this, I added a change in the controller that generates labels, and if the existing labels differ from those returned by `ComputeLabels`, we …
=> fix(k8s): check if labels has changed when reconciling

test/e2e_env/universal/trafficroute/traffic_route.go
We have seen flake on master recently:
I think we could loosen up the assertions to make it more stable
=> fix(e2e): loosen up assertion on traffic route test

.github/workflows/_build_publish.yaml
We hit the cross compiling error once building the `kuma-init` ARM64 image on github CI runner (X86 platform) with the `ubuntu-latest` runner.
Here's the context
```text
#5 31.28 dpkg: error processing package libc-bin (--configure):
#5 31.28  installed libc-bin package post-installation script subprocess returned error exit status 139
#5 31.29 Errors were encountered while processing:
#5 31.29  libc-bin
#5 31.36 E: Sub-process /usr/bin/dpkg returned an error code (1)
#5 ERROR: process "/bin/sh -c apt-get update &&     apt-get install --no-install-recommends -y iptables=1.8.7-1ubuntu5.2 iproute2=5.15.0-1ubuntu2 &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
> [2/6] RUN apt-get update &&     apt-get install --no-install-recommends -y …
```
=> ci(github): downgrade github action runner from ubuntu-latest to ubuntu-22.04 for images building

pkg/plugins/policies/core/matchers/dataplane.go
Affected Dataplanes list was incorrect for policies targeting builtin gateways.
The call of `filterGatewaysByZone` was missing in `PolicyMatches` method.
No issue
=> fix(kuma-cp): Global Inspect API returns incorrect list of affected gateways dataplanes

.github/workflows/_e2e.yaml, mk/test.mk
Those kind of reports
```
❯❯❯ python3 script.py
Test: [It] > MeshRetry > should retry on GRPC connection failure, Duration: 158.285 seconds
Test: [It] > Retry > should retry on HTTP connection failure, Duration: 154.582 seconds
Test: [SynchronizedAfterSuite] > , Duration: 125.061 seconds
Test: [It] > External Services through Zone Egress > should not access external service when zone egress is down, Duration: 54.543 seconds
Test: [It] > Resilience > should mark data plane proxy as offline after it is killed forcefully when control-plane is down, Duration: 41.954 seconds
Test: [It] > Gateway - Cross-mesh > when mTLS is enabled > should proxy HTTP requests from a different mesh, Duration: 38.306 seconds
Test: [It] > Compatibility > connection between old and new DPP > from version: 2.8.4, …
```
=> test(e2e): upload e2e reports

test/framework/envs/kubernetes/env.go, test/framework/envs/multizone/env.go
Every now and then we hit a problem when CP on Kube drops a leader, then the test fails because we have an assertion that CP did not restart. Additionally, I'm testing speeding up tests here https://github.com/kumahq/kuma/pull/11791 which puts more pressure on CP and increases the chances of it happening.
Just increase lease and renew duration. It makes sense to have those higher in case of local kube cluster. Why we won't change defaults? Because on real kube clusters with multiple nodes and multiple instances of Kuma CP, the chance of switching a leader because of random event in the cluster is much much higher.
We do exact same thing in mesh-perf scenario when we stress CP out.
may solve xref https://github.com/kumahq/kuma/issues/11090 but not in 100% of cases.
=> test(e2e): increase leader election lease and renew duration

pkg/kds/context/context.go, pkg/kds/util/meta.go
In 2.7.x method `GetMeta().GetLabels()` on Kubernetes returned a label map with `k8s.kuma.io/namespace` added dynamically. This behaviour was changed in 2.9.x by https://github.com/kumahq/kuma/pull/11020, the namespace label is now supposed to be set in ComputeLabels function. But this functions is called only on Create/Update of the resources. This means policies that were created on 2.7.x won't have `k8s.kuma.io/namespace` label when synced to Global. Even though the lack of namespace labels affects only how resource looks in GUI on Global it's still worth setting it.
Set `k8s.kuma.io/namespace` label if not exist to the resources before syncing them to Global.
Fix #XX
=> fix(kuma-cp): resources that were created on 2.7.x are missing namespace labels when synced on global

.github/workflows/_e2e.yaml
The uploaded names should contain all the params.
Technically we were fine in Kuma without sidecar containers param, because we run
* sidecars containers: true, k8s version: max, cni: empty
* sidecars containers: false, k8s version: max, cni: flannel
so CNI was different.
However, in KM we also add another target
* sidecars containers: false, k8s version: max, cni: empty, other param: true
and we hit the conflict.
Ideally we should also add this other param to file name in KM, but adding this in Kuma is correct and is a good start.
No issue. KM CI broken.
=> test(e2e): add sidecar containers param to uploaded file names

pkg/plugins/runtime/k8s/plugin.go, pkg/plugins/runtime/k8s/plugin_gateway.go
These aren't needed on global.
=> fix(k8s): only run necessary controllers on global

test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_gateway.go
The test seems to be a bit flaky, but not frequently. The difference in test values was small.
I have increased the traffic split values slightly.
Fix #XX
=> test(e2e): loosen up assertions on traffic split

.github/workflows/_build_publish.yaml
Restore the changes we'd done to work around these issues:
* https://github.com/kumahq/kuma/issues/11804
* https://github.com/kumahq/kuma/issues/11809
Use `ubuntu-latest` runner images.
I'm creating the PR from the same repo to maintain parity between runs here and those of master branches.
Fix #XX
=> ci(.github): use latest version of ubuntu runner image to build kuma-init image

pkg/core/rest/errors/error_handler.go
A client requesting a resource from the service might close the connection, canceling the context. In this case, the API throws a 5xx server error, but this is more of a client-side issue.
I used status code 499 as the response code for this situation, which is commonly used in NGINX to indicate that the client closed the connection before the server could send a response.
https://github.com/pocketbase/pocketbase/discussions/834
Fix https://github.com/Kong/kong-mesh/issues/6468
=> fix(api): return 499 when client cancel context

pkg/kds/context/context.go
We shouldn't log an error when a user disconnects and we observe `context canceled`.
Added a condition to check if an error is `context canceled` and if is to don't login an error.
Fix: https://github.com/Kong/kong-mesh/issues/6467
=> fix(kds): do not log error when context canceled

pkg/plugins/runtime/k8s/controllers/meshservice_controller.go, pkg/plugins/runtime/k8s/controllers/meshservice_controller_test.go, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/ignore.meshservice.yaml, pkg/plugins/runtime/k8s/controllers/testdata/meshservice/ignore.resources.yaml
We need to have a way to opt out one service
Support existing kuma.io/ignore annotation.
Fix https://github.com/kumahq/kuma/issues/11784
=> feat(meshservices): opt-in ignore converting

test/e2e_env/universal/meshhealthcheck/policy.go
I've noticed a flake of the test
I switched to using MeshService mode instead of manually creating a MeshService. I'm not sure if MeshService might be removed since the Mesh has `meshServices.mode` disabled. Additionally, I changed the hostname to use generated one.
Fix #XX
=> test(e2e): use MeshService mode and generated hostname

.github/workflows/_e2e.yaml
Every now and then we see this
https://github.com/Kong/kong-mesh/actions/runs/11439316275/job/31823270265
```
envoy.Dockerfile:1
--------------------
1 | >>> FROM debian:12.7@sha256:27586f4609433f2f49a9157405b473c62c3cb28a581c413393975b4e8496d0ab AS envoy
2 |     ARG ARCH
3 |     
--------------------
ERROR: failed to solve: debian:12.7@sha256:27586f4609433f2f49a9157405b473c62c3cb28a581c413393975b4e8496d0ab: failed to resolve source metadata for docker.io/library/debian:12.7@sha256:27586f4609433f2f49a9157405b473c62c3cb28a581c413393975b4e8496d0ab: failed to authorize: failed to fetch oauth token: unexpected status from POST request to https://auth.docker.io/token: 502 Bad Gateway
```
Auth server of docker has problems. I found a solution to just not use auth, but then we get rate limited …
=> test(e2e): retry build images

docs/generated/raw/kuma-cp.yaml, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/config/multizone/kds.go, pkg/config/multizone/multicluster.go, pkg/config/multizone/tracing.go, pkg/kds/mux/server.go
These traces are potentially not useful and too long-lived.
Added option to leave the status quo or completely disable KDS traces. Note that Envoy admin operations should not be affected.
=> feat(kuma-cp): add option to disable KDS traces

.github/workflows/build-test-distribute.yaml
IPV6 tests seems to be broken with our self-hosted runners.
It's not clear what's the problem, it can take some time to resolve it.
We'd rather have a slower CI with queues than CI which is broken. We can still keep arm64 tests on self-hosted runners because those do not run IPV6.
Broken CI
=> test(e2e): disable amd64 self-hosted runners

pkg/dp-server/server/server.go
Expose GrpcKeepAlive so that we can use it in KM on the client side of OPA Discovery Service instead of repeating.
Fix #XX
=> chore(kuma-cp): expose keep alive const

test/e2e_env/kubernetes/gateway/delegated/meshhttproute.go
This test flaked over the weekend
```
2024-10-26T19:13:28.3720416Z   [38;5;9m[FAILED] Timed out after 30.326s.
2024-10-26T19:13:28.3722049Z   The function passed to Eventually failed at github.com/kumahq/kuma/test/e2e_env/kubernetes/gateway/delegated/meshhttproute.go:203 with:
2024-10-26T19:13:28.3723375Z   Expected
2024-10-26T19:13:28.3723895Z       <map[string]int | len:4>: {
2024-10-26T19:13:28.3724696Z           "test-server-2": 12,
2024-10-26T19:13:28.3725408Z           "test-server-1": 11,
2024-10-26T19:13:28.3726273Z           "external-service-6dc7fff645-l9g9g": 66,
2024-10-26T19:13:28.3727140Z           "test-server-0": 11,
2024-10-26T19:13:28.3727711Z       }
2024-10-26T19:13:28.3728168Z   to have {key: value} matching
2024-10-26T19:13:28.3728921Z       <map[interface …
```
=> test(e2e): drop assertion on weight

test/e2e_env/universal/reachableservices/reachableservices.go
CI flaked with
```
2024-10-27T05:07:14.6972309Z   [38;5;9m[FAILED] Failed after 20.468s.
2024-10-27T05:07:14.6973849Z   The function passed to Consistently failed at github.com/kumahq/kuma/test/e2e_env/universal/reachableservices/reachableservices.go:53 with:
2024-10-27T05:07:14.6975235Z   Expected
2024-10-27T05:07:14.6975644Z       <int>: 28
2024-10-27T05:07:14.6976051Z   to equal
2024-10-27T05:07:14.6976544Z       <int>: 6[0m
```
I checked the debug data from the dump, we don't have `second-test-server.mesh` in the config dump. In logs we see
```
[2024-10-27 05:07:10.969][166][debug][filter] [source/extensions/filters/udp/dns_filter/dns_parser.cc:238] Ignoring additional RRs in a query because Envoy does not support. This could be an EDNS query.
[2024-10-27 …
```
=> test(e2e): improve assertion on reachable services

pkg/api-server/inspect_mesh_service.go, pkg/api-server/resource_endpoints.go, pkg/api-server/server.go, pkg/api-server/testdata/resources/inspect/policies/_resources/dataplanes/meshservice.golden.json, pkg/api-server/testdata/resources/inspect/policies/_resources/dataplanes/meshservice.input.yaml, pkg/core/resources/apis/meshservice/match.go
We want to list matching DPPs in the UI
We already had a code for it for policies. In the case of MeshServices, the matching is different.
I extracted "boilerplate" of parsing, marshaling request and validating the access to "generic function", so won't duplicate the logic and whether we have a change it matches both.
When it comes to OAPI, we already have a definition for it
https://github.com/kumahq/kuma/blob/2adb7f53026f3ab38f5967b21f507e6674ce893d/api/openapi/specs/api.yaml#L122
not sure we can do anything more here
Fix #10244
=> feat(meshservices): api for listing matching DPPs

pkg/api-server/service_insight_endpoints.go, pkg/api-server/testdata/service-insights/get.input.yaml, pkg/api-server/testdata/service-insights/list-simple.input.yaml, pkg/api-server/testdata/service-insights/pagination.input.yaml
This API would list the SeviceInsight resources with k8s mode, in which the common method [GetLabels](https://github.com/kumahq/kuma/blob/e21c751d782bc06eb7e8c779dacf71097bfe5732/pkg/plugins/resources/k8s/store.go#L299) would be called and supplement the `display-name` for the `Meta`.
So, let's just add a mapper function to remove that label in the API-Server component.
=> fix(api-server): skip display-name label for service insight

.github/workflows/build-test-distribute.yaml
It's about 12min in KM, because of slower machines and extra checks. We hit a limit once or twice already.
Let's increase it to 20. The alternative would be to replace it with yq.
No issue. Failed CI.
=> ci(gha): adjust timeout for check

.github/workflows/_build_publish.yaml, .github/workflows/_e2e.yaml, .github/workflows/helm-release.yaml
Retention days in KM is set to 10 days max, because of that there are a lot of warning noise in KM jobs.
We could do some yq magic to replace it, but maybe we don't need 30 here as well?
Fix #XX
=> ci(gha): adjust retention days

test/e2e_env/kubernetes/reachableservices/reachableservices.go
We suspect DNS lookups themselves are timing out and [causing flakes](https://github.com/kumahq/kuma/actions/runs/11514774996/job/32152139325). This may be related to https://github.com/kumahq/kuma/pull/11862
Similar to https://github.com/kumahq/kuma/pull/11874
=> test(e2e): improve reachable services expectation to allow DNS timeouts

app/kumactl/cmd/completion/testdata/bash.golden, app/kumactl/cmd/generate/generate_dataplane_token.go, app/kumactl/cmd/generate/generate_dataplane_token_test.go, app/kumactl/cmd/generate/generate_user_token.go, pkg/xds/envoy/names/resource_names.go
fixes https://github.com/kumahq/kuma/issues/11848
Mark the option as required.
Includes a small fixes  that resolves https://github.com/kumahq/kuma/pull/11107#discussion_r1751419328
fixes https://github.com/kumahq/kuma/issues/11848
=> fix(kumactl): mark valid-for as required for command kumactl generate dataplane-token

app/kumactl/cmd/get/table_printer.go, app/kumactl/cmd/get/testdata/get/get-mesh.golden.txt, app/kumactl/cmd/get/testdata/list/get-meshes.golden.txt, app/kumactl/cmd/get/testdata/list/get-meshes.pagination.golden.txt
These columns no longer make sense with new policies that configure these aspects of the data plane.
Closes https://github.com/kumahq/kuma/issues/10973
=> fix(kumactl): remove metrics, logging, tracing columns in `get meshes`

go.mod, test/e2e/reachableservices/auto_reachable_mesh_services_k8s.go, test/e2e/reachableservices/auto_reachable_services_k8s.go, test/e2e/reachableservices/cluster.go, test/e2e/reachableservices/e2e_suite_test.go, test/framework/setup.go
Let's try to speed up some non-shared e2e tests.
They take as much resources as all e2e_env combined.
Before
```
❯❯❯ python test-time.py
Test: [It] > Auto Reachable Services on Kubernetes > should not connect to non auto reachable service, Duration: 74.248 seconds
Test: [It] > Auto Reachable Mesh Services on Kubernetes > should not connect to non auto reachable service, Duration: 61.293 seconds
Test: [It] > Auto Reachable Services on Kubernetes > should connect to ExternalService when MeshTrafficPermission defined, Duration: 60.537 seconds
```
196s
```
Test: [It] > Auto Reachable Mesh Services on Kubernetes > should not connect to non auto reachable service, Duration: 24.698 seconds
Test: [It] > Auto Reachable Services on Kubernetes > should connect to ExternalService when …
```
=> test(e2e): speed up reachable services

pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/injector_test.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.41.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.41.input.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.41.golden.yaml, test/framework/envs/multizone/env.go
I wanted to run Zone 2 in e2e tests in CNI mode and I encountered a problem with injection.
We were injecting such init container
```
initContainers:
- name: ""
resources: {}
```
I fixed it and switched one zone to CNI to avoid this in the future.
Inject container only if it's created
Placing run-full-matrix, because I need to see if all variants are ok. I checked locally and e2e is fine with CNI.
=> fix(cni): delegated gateway was not correctly injected

.github/workflows/_test.yaml
I don't see good reason to run old e2e tests with min version of kube or ipv6.
We test 90% in the shared `e2e_env`, but old tests spawns 12 VMs (as much as all variants of new tests) and runs longer than them.
I see minimal risk of not running those tests with IPV6 and old kube and huge win for CI time.
=> test(e2e): only run kube max version on old e2e tests

pkg/api-server/resource_endpoints.go, pkg/api-server/resource_endpoints_test.go, pkg/api-server/testdata/resources/crud/put_update_dataplanes_01.golden.json, pkg/core/resources/apis/meshservice/generate/component.go, pkg/core/resources/apis/meshservice/generate/generator.go, pkg/core/resources/apis/meshservice/generate/generator_test.go
While writing a POC for `MeshExternalService` through a specific zone, I noticed that the resource I used did not have a zone label. During debugging, I found that the resource was initially created correctly in one test, and in a subsequent test, we updated it without actually modifying any fields. However, after this second call, the updated resource was missing labels, while the original resource retained them. After fixing one thing I've noticed that MeshService is missing `kuma.io/zone` label and that caused that policy wasn't matched and had to add it.
Create
Update
I added a ComputeLabels call during the update, as previously we were simply overriding all labels with those from the resource, without recalculating them. I added a `kuma.io/zone` label on MeshService generated on …
=> fix(api): compute labels on resource update

.github/workflows/_e2e.yaml, .github/workflows/build-test-distribute.yaml
Renable self-hosted runners that were disabled here
https://github.com/kumahq/kuma/pull/11862
Docker changes were tested here https://github.com/kumahq/kuma/pull/11872
=> test(e2e): reenable amd64 self-hosted runners

tools/releases/version.sh
Envoy 1.28 is out of life, we should upgrade to 1.29
Fix #XX
=> chore(deps): upgrade envoy version from 1.28.7 to 1.29.10

test/e2e_env/multizone/localityawarelb/meshmultizoneservice.go
This is left over from when they weren't autogenerated on universal.
=> test(e2e): in MLBS + MZMS test, don't manually create MeshService

pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go, test/e2e_env/multizone/localityawarelb/meshmultizoneservice.go
We already set `priority: 1` for remote zones in `fillRemoteMeshServices` so we need to explicitly set `priority: 0` if we _don't_ want locality awareness.
Also fix an insufficient condition in an existing case, where we weren't verifying that requests really go to all zones, only that it's OK if they do.
Fixes https://github.com/kumahq/kuma/issues/11968
=> fix(MeshLoadBalancingStrategy): set all priorities equal if localityAware is disabled

test/e2e/helm/kuma_helm_deploy_global_zone.go
This test was flaking, so it's disabled for the investigation, which I'm currently conducting
=> test(e2e): disable helm deploy / admin ops test while investigating flake

test/e2e_env/multizone/localityawarelb/meshmultizoneservice.go
The uni MeshService is autogenerated, without the namespace tag, since #11978 and the first condition in "should fallback only to first zone" was fixed in #11980. This caused the test to start failing on master.
=> test(e2e): fix MMZS + MLBS test after merge

.github/workflows/update-insecure-dependencies.yaml, tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
[Fails atm](https://github.com/kumahq/kuma/actions/runs/11696575060/job/32573910890#step:7:10):
```
Scanned /home/runner/work/kuma/kuma/go.mod file and found 222 packages
panic: Cannot range over: func(yield func(K, V) bool)
goroutine 40815 [running]:
golang.org/x/tools/go/ssa.(*builder).rangeStmt(0xc0053d0770, 0xc0ea4c1520, 0xc006c5cd20, 0x0)
/home/runner/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2279 +0x805
golang.org/x/tools/go/ssa.(*builder).stmt(0xc0053d0770, 0xc0ea4c1520, {0x1911160?, 0xc006c5cd20?})
/home/runner/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2503 +0x205
golang.org/x/tools/go/ssa.(*builder).stmtList(...)
/home/runner/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:909
golang.org/x/tools/go/ssa.(*builder).stmt(0xc0053d0770, …
```
=> ci(update-insecure-dependencies): fix osv-scanner failure

deployments/charts/kuma/templates/_helpers.tpl, deployments/charts/kuma/templates/cp-configmap.yaml, pkg/plugins/runtime/k8s/webhooks/injector/injector.go
Until now you couldn't delete the default transparent proxy configuration ConfigMap when `transparentProxy.configMap.enabled` was set. You also couldn't have `transparentProxy.configMap.config` empty during installation as it would automatically disable this feature.
This commit changes this behavior and allows empty ConfigMaps or deletions of them, so if you want to enable this feature, but don't want to initially have anything specified in the configuration now you can.
=> feat(kuma-cp): allow missing transparent proxy ConfigMap or empty in k8s

.github/workflows/release.yaml
This fixes: https://github.com/kumahq/kuma-website/pull/2073 which is needed as we moved to the latest site-generator with: https://github.com/kumahq/kuma-website/pull/1623.
=> ci(github): fix release.yaml to use label:dev in version.yaml

docs/generated/openapi.yaml, pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshservice/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshfaultinjection/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshhttproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshmetric/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshproxypatch/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshratelimit/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshretry/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtcproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtimeout/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtls/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtrace/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/schema.yaml, tools/policy-gen/templates/schema.yaml
In order to further complete the openAPI specs, we need to add `creationTime` and `modificationTime`. These properties are already part of the response payload (see context below). Since the GUI project started to generate the TypeScript types from the specs, there is a high demand in having complete specs to avoid manual backfilling.
Added `modificationTime` and `creationTime` to `tools/policy-gen/templates/schema.yaml`. Afterwards ran `make check`.
<details>
<summary>Example Payloads</summary>
```json
{
"type": "MeshMetric",
"mesh": "default",
"name": "otel-metrics.kuma-system",
"creationTime": "2024-11-05T13:50:03Z",
"modificationTime": "2024-11-05T13:50:03Z",
"labels": {
"k8s.kuma.io/namespace": "kuma-system",
"kuma.io/display-name": "otel-metrics",
"kuma.io/mesh": "default", …
```
=> feat(tools/policy-gen/templates/schema): add creationTime and modificationTime to policy specs

pkg/kds/util/meta.go, pkg/kds/util/resource.go, pkg/plugins/resources/memory/store.go, pkg/plugins/resources/remote/store.go, pkg/plugins/secrets/k8s/store.go
There were some places where labels on meta weren't not cloned when duplicating the meta.
Walked the code for odd usages of `GetLabels()`.
xref https://github.com/kumahq/kuma/issues/11886
=> fix(kuma-cp): avoid concurrent access on resource meta

pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-dp/testdata/default-config.golden.yaml
fixes https://github.com/kumahq/kuma/issues/11854
`kuma-dp` decides whether to start the application probe proxy according to port settings on `applicationProbeProxyServer.port`, when it's configured to `0`, the server won't start. 
It was set to `9001` by default. So now change this default value to "not set", which will be actually `0`.  
On Kubernetes, we have another injector configuration item which still defaults to `9901`, it will eventually be applied to the `kuma-dp` process in the pod. Users can use environment variable and data plane pod annotation to configure this port. So the functionality of the feature is not impacted at all.
https://kuma.io/docs/2.9.x/policies/service-health-probes/#application-probe-proxy
=> feat(kuma-dp): disable application probe proxy by default on Universal

pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_cluster.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_listener.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
We noticed that when a user upgrades to version 2.9.x without a default MeshTimeout/Timeout policy, default timeouts are applied on inbound clusters and listeners. This could disrupt the existing behavior of the environment.
When no policy is present, we simply skip configuration and do not set up the timeouts for inbound cluster or listener.
Fix https://github.com/kumahq/kuma/issues/12033
=> fix(meshtimeout): don't set default timeouts on inbound cluster and listener

.github/workflows/release.yaml, .github/workflows/update-docs.yaml, .github/workflows/update-insecure-dependencies.yaml
upgrade the github-action peter-evans/create-pull-request from v0.5.2 to v0.5.3 manually
Fix https://github.com/Kong/kong-mesh/pull/6963
=> ci(github): bump github action create-pull-request from v0.5.2 to v0.5.3

.github/workflows/ci-stability.yaml
After adding a label to the second PR, I noticed that the job failed. This was caused by the value being split across multiple lines. Additionally, the subsequent loop didn't recognize it as an array but instead treated it as an array of individual characters.
```
PRs with 'ci/verify-stability' label: 11672
11296
PRs with 'ci/verify-stability-merge-master' label: 1[16](https://github.com/kumahq/kuma/actions/runs/12000059034/job/33448712899#step:5:17)72
Error: Unable to process file command 'output' successfully.
Error: Invalid format '11296'
```
* Changed new line to whitespace
* Change the string into an array and iterate over it
https://github.com/kumahq/kuma/actions/runs/12000059034/job/33448712899
Fix #XX
=> chore(gha): replace new line with whitespace and change to array

test/e2e_env/universal/meshretry/http.go
I noticed a failed test and during investigation found out that we hit an issue https://github.com/kumahq/kuma/issues/12098
Since the initial_fetch_timeout is 15 seconds, everything should return to normal after this period. For now, I've increased the timeout from 10 seconds to 30 seconds.
Fix #XX
=> test(e2e): increase eventually time

test/e2e_env/kubernetes/gateway/delegated.go, test/e2e_env/kubernetes/gateway/delegated/meshtls.go
I noticed a flake and began investigating. I discovered the TLS version and cipher are not configured for the delegated gateway. Since the `MeshTLS` policy is a `from` policy and the delegated gateway has no inbound listener, the policy cannot be matched to any listener. The test passed because the request was sent before the configuration was fully delivered.
Excluded the test and added `MustPassRepeatedly(5)` to ensure better validation once the issue is resolved.
xref: https://github.com/kumahq/kuma/issues/12107
=> test(e2e): disable meshmtls test with delegated gateway

test/e2e/reachableservices/auto_reachable_services_k8s.go
I've noticed a flake in a specific test. We are using `Consistently`, which expects that error code `52` will always be returned. This is a correct assumption, unless something happens on the network and we receive a different error code.
```
[FAILED] Failed after 0.250s.
The function passed to Consistently failed at github.com/kumahq/kuma/test/e2e/reachableservices/auto_reachable_services_k8s.go:100 with:
Expected
<int>: 56
to equal
<int>: 52
Error: It 11/22/24 10:02:24.833
```
To avoid this flake, I changed `Consistently` to `Eventually` and added `MustPassRepeatedly`. We cannot guarantee that the network is 100% reliable, so we have two options:
* Add another error code to check, or
* If it fails, wait for 5 consecutive successes. …
=> test(e2e): change consitently to eventually

.github/workflows/build-test-distribute.yaml
The `kuma-init` image fails to build on Ubuntu versions newer than 22. To avoid this issue, we plan to use an older runner image. This problem does not occur on the `master` branch because we use a different base image for `kuma-init`. Additionally, on `release-2.9`, we are already using Ubuntu 22.04.
Use ubuntu 22
https://github.com/actions/runner-images/issues/10636#issuecomment-2397720931
https://github.com/kumahq/kuma/pull/5945
https://github.com/kumahq/kuma/pull/11826
=> chore(images): pin ubuntu version

pkg/config/loader_test.go, pkg/config/multizone/kds.go, pkg/config/multizone/sync.go, pkg/kds/context/context.go, pkg/kds/util/meta.go, test/e2e_env/multizone/sync/sync.go, test/framework/envs/multizone/env.go
Users might not want certain labels to be propagated between control planes.
Two config values, one for zone and one for global.
Closes https://github.com/kumahq/kuma/issues/11416
=> feat(kuma-cp): allow skipping certain label propagation on multizone

.github/workflows/release.yaml
We're cleaning up some old docs. This will stop generating versions before 2.2.x in the `versions.yaml` which will remove them from the docs website.
Once this is done and pushed to the docs website we'll be able to cleanup stuff.
Part of https://github.com/kumahq/kuma-website/issues/2072
=> ci(docs): remove version before 2.2.x from automation of versions.yaml

UPGRADE.md
These were not super useful and are for very old version. Should be fine removing them.
Part of https://github.com/kumahq/kuma-website/issues/2072
=> docs(UPGRADE.md): remove links to docs that are not longer published

OWNERS.md
Add Icarus Wu as Kuma maintainer.
Icarus Wu
Email: icarus.wu@konghq.com
Github: Icarus9913
I wish to become a Kuma project maintainer to better engage in the discussions, contributions, code reviews for substantial time.
Here are my significant contribution PRs and Issues for this project:
- [feat(kds): remove kds v1](https://github.com/kumahq/kuma/pull/10946)
- [fix(ZoneIngress): fix no pointer panic for advertised address resolving](https://github.com/kumahq/kuma/pull/10475)
- [fix(xds): accelerate universal dp XDS generation](https://github.com/kumahq/kuma/pull/11180)
- [Kuma control plane pod crashed](https://github.com/kumahq/kuma/issues/10072)
- [MeshGatewayInstance Validating Webhook not works](https://github.com/kumahq/kuma/issues/10329)
=> docs(maintainer): maintainer nomination

test/e2e_env/multizone/trafficroute/trafficroute.go
Flaking test
xref: https://github.com/kumahq/kuma/issues/12142
=> chore(e2e): disable flaking TrafficRoute multizone e2e_env test

.github/workflows/ci-stability.yaml
When processing a workflow file through the `yq`, the format is destroyed because of whitespace at the end
Removed a whitespace
Fix #XX
=> chore(gha): remove whitespace

UPGRADE.md, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshloadbalancingstrategies.yaml, docs/generated/openapi.yaml, docs/generated/raw/crds/kuma.io_meshloadbalancingstrategies.yaml, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/meshloadbalancingstrategy.go, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator.go, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshloadbalancingstrategy/k8s/crd/kuma.io_meshloadbalancingstrategies.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mtlbs.federated.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mtlbs.global.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mtlbs.input.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mtlbs.non-federated.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mlbs.federated.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mlbs.global.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mlbs.input.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mlbs.non-federated.golden.yaml
While investigating [kuma#12110](https://github.com/kumahq/kuma/issues/12110), we noticed that the following policy is rejected:
```yaml
kind: MeshLoadBalancingStrategy
apiVersion: kuma.io/v1alpha1
metadata:
name: ring-hash
namespace: kuma-system
labels:
kuma.io/mesh: default
spec:
targetRef:
kind: MeshSubset
tags: 
kuma.io/service: demo-app_kuma-demo_svc_5000
to:
- targetRef:
kind: MeshService
name: redis_kuma-demo_svc_6379
default:
loadBalancer:
type: RingHash
ringHash:
hashPolicies:
- type: Connection
connection:
sourceIP: true
```
However, a policy with `type: SourceIP` passes validation, which seems incorrect based on the [documentation](https://kuma.io/docs/2.9.x/policies/meshloadbalancingstrategy/#ringhash). Upon checking the code, I found that the kubebuilder validation uses the …
=> fix(meshloadbalancingstrategy): deprecate SourceIP and use Connection

pkg/plugins/policies/meshtrafficpermission/graph/backends/reachable_backend_refs_graph.go, pkg/plugins/policies/meshtrafficpermission/graph/reachable_backend_refs_graph_test.go, pkg/plugins/policies/meshtrafficpermission/graph/reachable_services_graph_test.go, pkg/plugins/policies/meshtrafficpermission/graph/services/reachable_services_graph.go
Since 2.9 we don't require top-level target ref. If it's empty we assume it's a `kind: Mesh`. We can observe nil pointer once the user provides a policy without top-level target ref.
Added check for nil top target ref and test
Fix #XX
=> fix(meshtrafficpermission): nil pointer for autoreachableservice when no top targetRef

.github/workflows/build-test-distribute.yaml
We don’t know how stable our CI is on release branches because we don’t make changes to them often. This means we don’t get enough feedback about their status.
This is a first PR to run CI on release branches on schedule described in: https://github.com/kumahq/kuma/pull/12164
=> ci(gh): allow to run `build-test-distribute` on `workflow_dispatch`

docs/madr/decisions/068-improve-the-state-of-the-ci-on-release-branches-periodic-ci-runs.md
We don’t know how stable our CI is on release branches because we don’t make changes to them often. This means we don’t get enough feedback about their status.
[MADR-068 Improve the state of the CI on release branches - Periodic CI Runs](https://docs.google.com/document/d/1-t8aa3uxdFEaZOpAAN7ojRVn4AnjVUqdd4HXlSN7U9I)
Part of: https://github.com/kumahq/kuma/issues/12163
=> docs(MADR): improve state of the ci on release branches - periodic runs

test/framework/k8s.go
GatewayApi tests are failing after upgrade of k8s lib
Upgrade CRDs version in tests
We should document it somewhere
xref: https://github.com/kumahq/kuma/commit/f01183becd9c4398fd1a17071070f88ecdd4d01f
=> ci(gatewayapi): update crd version

.github/workflows/check.yaml
There was a typo in the footnote link.
Part of https://github.com/Kong/team-mesh/issues/302
=> ci(github): fix footnote link

go.mod
This comment had no point in still existing as we'll always have a fork
=> chore(deps): remove comment that was misleading

.github/workflows/build-test-distribute.yaml
We don’t know how stable our CI is on release branches because we don’t make changes to them often. This means we don’t get enough feedback about their status.
This is a part of the effort to run tests on CI for release branches on schedule. As GitHub doesn't allow to run workflows on schedule from branches other than default (master in our case), the best solution I could find is to allow to run `build-test-distribute` workflow on `workflow_dispatch` event and then in master on schedule send a REST call to manually trigger these workflows on wanted release branches.
Part of:
- https://github.com/kumahq/kuma/pull/12164
- https://github.com/kumahq/kuma/issues/12163
=> ci(gh): allow to run build-test-distribute on workflow_dispatch

.github/workflows/build-test-distribute.yaml
Increase timeout to 25 minutes to fix issues with other projects timing out
Fix #XX
=> ci(gh): increate timeout for `check` job in `built-test-distribute`

app/kuma-dp/pkg/dataplane/metrics/profiles.go, app/kuma-dp/pkg/dataplane/metrics/testdata/profiles/basic_and_none.golden, app/kuma-dp/pkg/dataplane/metrics/testdata/profiles/basic_and_none.in
DNS statistics seem important and should be included in the default profile.
Added a filter which matches 2 sections
```
envoy_dns_care
```
Which provides a lot of interesting data about DNS queries 
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/dns_resolution
Name | Type | Description
-- | -- | --
resolve_total | Count | Number of DNS queries
pending_resolutions | Gauge | Number of pending DNS queries
not_found | Counter | Number of DNS queries that returned NXDOMAIN or NODATA response
timeout | Counter | Number of DNS queries that resulted in timeout
get_addr_failure | Counter | Number of general failures during DNS quries
and `envoy_dns_filter` which has more detailed metrics. I would consider maybe reducing them but I would like to get your opinion:
``` …
```
=> feat(meshmetrics): add dns metrics to basic profile

pkg/kds/v2/server/tenant_callback.go
The application's memory usage was slowly increasing but did not correlate with the number of active connections. I decided to investigate the memory usage and noticed some context entries. While reviewing the code, I discovered that we are not cleaning up the map of streams and contexts. I'm not certain if this is the primary issue, but it could be a contributing factor.
Implemented the `OnDeltaStreamClosed` method to remove entries from the map when a stream is closed.
xref: https://github.com/Kong/kong-mesh/issues/6616
=> fix(kds): remove context from map on stream close

.github/workflows/check.yaml
Prevent shell script injection via PR titles, which could allow running malicious shell code in actions. This made it easy to leak secrets and posed a broader security risk.
=> ci(github): sanitize title input in pr-check action

.github/workflows/_e2e.yaml
GitHub Actions provides the `ACTIONS_RUNNER_DEBUG` environment variable to enable debugging. We should leverage it.
Instead of using `ENABLE_E2E_DEBUG_GLOBALLY` we can rely on `ACTIONS_RUNNER_DEBUG` env.
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging
=> chore(e2e): remove ENABLE_E2E_DEBUG_GLOBALLY env and rely on github

app/kuma-cp/cmd/run.go, app/kuma-dp/cmd/run.go, pkg/api-server/config_ws.go, pkg/config/display.go, pkg/kds/envoyadmin/kds_client_test.go, pkg/kds/zone/components.go
In a customer investigation it took a while to figure what the version of the dp was.
Also the logs between the CP and DP were quite different.
- Log version and config as early as possible on startup of cp and dp
- Use similar log messages for cp and dp to develop muscle memory
- Simplify api to get json safe to print
=> chore(app): add common logging of version, config on startup

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/dnsConfigOption.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/envVarsDownwardApi.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml, deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
Removed unused ValidatingWebhookConfiguration for GatewayClass from Helm templates. This webhook was used in the past but is no longer needed, as referenced [here](https://github.com/kumahq/kuma/pull/9732/files#diff-c52d66882aa05dbce22b5860ae537e41820b2a6b1940acb6a5524cee9e039b84L312).
=> chore(k8s): remove unused GatewayClass validating webhook

pkg/kds/v2/server/tenant_callback.go
Backport https://github.com/kumahq/kuma/pull/12243
I had to do a manual backport because GitHub changed my merge method to merge commit and this one cannot be backported.
Fix #XX
=> fix(kds): remove context from map on stream close (backport of #12243)

.github/workflows/build-test-distribute.yaml, .github/workflows/ci-stability-release-branches.yaml
We are reusing this workflow in other project, which has different name for the file containing build-test-distribute workflow so I added option to configure it.
At resulting in summary table, we don't need to information with amount of steps, so I'm getting rid of it as well.
=> ci(github): make workflow id to trigger for ci-stability-release-branches workflow configurable

.github/workflows/build-test-distribute.yaml, .github/workflows/ci-stability-release-branches.yaml
Correct ID for the workflow to trigger in ci-stability-release-branches is the name of the workflow file.
=> ci(github): set the correct id of workflow to trigger for CI stability

mk/k3d.mk
To fix k3d start errors when using calica CNI
It's reported in CI run of the latest commit on `release-2.8` and older release versions:
https://github.com/kumahq/kuma/actions/runs/12357114240/job/34492385775
During backport `\` was forgotten which caused that calico step wasn't a prerequisite for running k3d.
Code on master: https://github.com/kumahq/kuma/pull/12277/files#diff-6a9a6d7b0c33e516a1579d4ea2ccdfdbec5bd689d4f15bcab302e2a80b0d7ee4R109
=> chore(mk): fix k3d start errors when using calico CNI

.github/workflows/ci-stability-release-branches.yaml
We don't have javascript workflows so this change makes it consistent with every other workflow where jobs are written as bash scripts
**Example run**: https://github.com/kumahq/kuma/actions/runs/12373850049
=> ci(github): rewrite ci-stability-release-branches workflow to bash

.github/workflows/ci-stability-release-branches.yaml
This trailing space caused that the whole workflow file was not properly synced
=> ci(github): remove trailing space from ci-stability-release-branches

api/mesh/v1alpha1/mesh/schema.yaml, docs/generated/openapi.yaml, mk/generate.mk, tools/resource-gen/main.go
The build was failing in parent repo because of:
https://github.com/kumahq/kuma/blob/39a5f176c7bd1f608fdc0a6e834d33289256d108/docs/generated/openapi.yaml#L11498
Also the paths in the parent repo were not properly set
We're ignoring the `structpb.Struct` so that it is effectively any JSON map.
Fixes this error:
```
error loading swagger spec in api/openapi/specs/global_insight.yaml
: failed to load OpenAPI specification: error resolving reference "../kuma/openapi.yaml#/components/schemas/GlobalInsight": failed to unmarshal data: json error: invalid character 'o' looking for beginning of value, yaml error: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal bool into field Schema.properties of type openapi3.Schema
make: *** [kuma/mk/generate.mk:108: generate/oas] Error 1 …
```
=> feat(oapi): properly marshal proto struct and set paths

mk/generate.mk
Because otherwise this is not built and fails https://github.com/Kong/kong-mesh/actions/runs/12408432049/job/34640101247?pr=7179#step:13:69
Add dependency in makefile
Fix https://github.com/Kong/kong-mesh/actions/runs/12408432049/job/34640101247?pr=7179#step:13:69
> Changelog: feat(oapi): add mesh and meshgateway to oapi spec
=> feat(oapi): fix missing dependency

tools/resource-gen/main.go
still failing https://github.com/Kong/kong-mesh/actions/runs/12410164787/job/34645214875?pr=7179#step:13:74 probably had the wrong path, not sure why it worked locally
Fix https://github.com/Kong/kong-mesh/actions/runs/12410164787/job/34645214875?pr=7179#step:13:74
> Changelog: feat(oapi): add mesh and meshgateway to oapi spec
=> feat(oapi): fix out dir

.github/workflows/build-test-distribute.yaml
`DOCKERHUB_PULL_CREDENTIAL` wasn't propagated
I suspect it's because of missing secret inherit
Fix #XX
=> chore(gha): inherit secrets

pkg/kds/mux/client.go
We're seeing errors like this https://github.com/kumahq/kuma/issues/12183.
According to the docs https://github.com/grpc/grpc-go/blob/master/Documentation/compression.md#compression if turned on on the client side it will automatically make server also respond with compressed responses.
Fix https://github.com/kumahq/kuma/issues/12183
=> feat(kds): use compressor to make requests and responses smaller

.github/workflows/pr-modification.yaml
Instead of using a potentially dangerous pull_request_target We use a cron that looks at recently updated PRs
=> ci(github): add PR checklist comment as a cron

.github/workflows/pr-merged.yaml
Cherry-picking commit 5067a4e3192f44baa22f9afa652a1f1ac85b59b5 to release-2.7 branch
=> ci(github): use on.push to notify about updates (backport of #12424)

.github/workflows/pr-modification.yaml
The job wasn't implemented correctly
We now retrieve all recently updated PR and add the checklist as a stick comment.
This is completely safe as it only executes on master and runs trusted code
=> ci(github): fix PR comment action

api/openapi/specs/api.yaml, api/openapi/types/zz_generated.api.go, docs/generated/openapi.yaml
So it's properly merged in parent object. Otherwise we end up with both `properties` and `allOf` on the same level which doesn't play nicely with parent project validator.
Move to separate object.
xrel https://github.com/kumahq/ci-tools/issues/59
=> chore(oapi): move global inisight schema to separate object

api/openapi/specs/api.yaml, docs/generated/openapi.yaml
There is no such a things as "resources" this was probably a typo because a field nearby is "_resources".
Rename "resources" to the correct "responses".
xrel https://github.com/Kong/kong-mesh/issues/7202
=> chore(oapi): rename resources to responses

api/openapi/specs/api.yaml, api/openapi/types/zz_generated.api.go, docs/generated/openapi.yaml
Rename InternalServerError to Internal so it gets correctly deduplicated in parent project
Rename the field.
xrel https://github.com/Kong/kong-mesh/issues/7202
=> chore(oapi): rename InternalServerError to Internal

.github/workflows/_build_publish.yaml, .github/workflows/_provenance.yaml, .github/workflows/build-test-distribute.yaml, .github/workflows/ci-stability.yaml
This change reduces GitHub Actions workflow permissions to follow the principle of least privilege, addressing security alerts from Scorecard and improving overall workflow security.
- `_build_publish.yaml`:
- Moved `id-token: write` to `build-images` job
- Removed global `id-token: write` permission
- `_provenance.yaml`:
- Added `permissions: {}` globally
- Set specific permissions (`contents`, `actions`, `id-token`, `packages`) per job
- `build-test-distribute.yaml`:
- Removed global permissions
- Added job-specific permissions for `checks`, `contents`, `id-token`, and `packages`
- `ci-stability.yaml`:
- Added explicit `permissions: {}` globally
=> ci(gha): reduce permissions in workflows based on scorecard alerts

.github/workflows/build-test-distribute.yaml
When job has any permission provided any other, non specified ones are treated like they would have permission `none` and global permissions block is not merged with them, so we have to add back `contents: read` permission to `check` job.
=> ci(gha): add back contents: read permission to check job

mk/check.mk
I noticed that we renamed the dockerfiles but we did not change the hadolint target. Notice the `*` is not at the beginning.
Add a check to see if the find command found any files or not and modify the glob.
Not reported anywhere.
=> ci(hadolint): make hadolint fail if there aren't any dockerfiles found

.github/workflows/_build_publish.yaml, .github/workflows/_e2e.yaml, .github/workflows/_test.yaml, .github/workflows/build-test-distribute.yaml, .github/workflows/helm-release.yaml, .github/workflows/pr-comments.yaml, .github/workflows/transparentproxy-tests.yaml
We can observe warnings in jobs because of old cache action
Upgrade to the same as master branch
=> chore(deps): upgrade actions/cache from v4.1.0 to v4.2.0

pkg/plugins/leader/postgres/leader_elector.go
We saw this error without any information: 
I've added proper error logging in postgres leader elector to see more details, and to skip the context cancelled error
=> fix(postgres-leader): add proper error logging in postgres leader elector

mk/check.mk
CI on dependent project is broken
- Changed `*Dockerfile` to `*Dockerfile*` as in dependent project the name format is different
- Improved a little bit find command to not unnecessarily pipe results
=> ci(check): fix hadolint make target

test/framework/deployments/postgres/kubernetes.go
Issues with adding the Bitnami repository caused by Cloudflare instability made our CI very unstable ([example CI run](https://github.com/kumahq/kuma/actions/runs/12669382227/job/35307422204))
```
"Error: looks like \"[https://charts.bitnami.com/bitnami\](https://charts.bitnami.com/bitnami/)" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR; received from peer",
```
Switched from the Bitnami Helm chart to the OCI-based chart, resolving issues with adding the Bitnami repository caused by Cloudflare instability. This change allows the complete removal of the Bitnami repository.
- https://github.com/bitnami/charts/issues/31257
- https://blog.bitnami.com/2024/10/bitnami-helm-charts-moving-to-oci.html
<details>
<summary>CloudFlare Status</summary> …
=> test(framework): replace bitnami helm chart with oci one

api/common/v1alpha1/ref.go, pkg/core/resources/apis/mesh/validators.go, pkg/core/resources/apis/mesh/validators_test.go
As discussed in Inbound policies madr we need a new kind Dataplane, this pr introduces API for this kind
Fix #12358
=> feat(kuma-cp): add new targetRef kind Dataplane

test/framework/deployments/postgres/kubernetes.go
Issues with adding the Bitnami repository caused by Cloudflare instability made our CI very unstable ([example CI run](https://github.com/kumahq/kuma/actions/runs/12669382227/job/35307422204))
```
"Error: looks like \"[https://charts.bitnami.com/bitnami\](https://charts.bitnami.com/bitnami/)" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR; received from peer",
```
Switched from the Bitnami Helm chart to the OCI-based chart, resolving issues with adding the Bitnami repository caused by Cloudflare instability. This change allows the complete removal of the Bitnami repository.
- bitnami/charts issue 31257
- https://blog.bitnami.com/2024/10/bitnami-helm-charts-moving-to-oci.html
=> test(framework): replace bitnami helm chart with oci one (backport #12489)

.github/workflows/_build_publish.yaml
=> ci(github): add read content permissions to build-images

pkg/core/xds/inspect/rules.go, pkg/plugins/policies/core/rules/rules.go, pkg/plugins/policies/core/rules/rules_test.go, pkg/plugins/policies/core/rules/testdata/rules/from/06.golden.yaml, pkg/plugins/policies/core/rules/testdata/rules/from/06.input.yaml, pkg/plugins/policies/core/rules/testdata/rules/from/07.golden.yaml, pkg/plugins/policies/core/rules/testdata/rules/from/07.input.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshratelimit/plugin/xds/configurer.go, pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshretry/plugin/xds/configurer.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go, pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtrafficpermission/graph/reachable_graph.go
1. When I went through the policy matching subset `Intersect` method, I found the behavior is incorrect with one case
2. Rewrite the rule's `Compute` method to use the new `ContainsElement` method instead of using the old `IsSubset` method
Introduce one new type `type Element map[string]string` for differentiation by `IsSubset`.
cherry-picked commit 3a00363b331f92278c57caa3b47e6113e83e7525
=> fix(policy): use new compute for rules and fix rules intersect (backport of  #12340)

pkg/core/xds/inspect/rules.go, pkg/plugins/policies/core/rules/rules.go, pkg/plugins/policies/core/rules/rules_test.go, pkg/plugins/policies/core/rules/testdata/rules/from/06.golden.yaml, pkg/plugins/policies/core/rules/testdata/rules/from/06.input.yaml, pkg/plugins/policies/core/rules/testdata/rules/from/07.golden.yaml, pkg/plugins/policies/core/rules/testdata/rules/from/07.input.yaml, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshratelimit/plugin/xds/configurer.go, pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshretry/plugin/xds/configurer.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go, pkg/plugins/policies/meshtrafficpermission/graph/reachable_services_graph.go
1. When I went through the policy matching subset `Intersect` method, I found the behavior is incorrect with one case
2. Rewrite the rule's `Compute` method to use the new `ContainsElement` method instead of using the old `IsSubset` method
Introduce one new type `type Element map[string]string` for differentiation by `IsSubset`.
cherry-picked commit 3a00363b331f92278c57caa3b47e6113e83e7525
=> fix(policy): use new compute for rules and fix rules intersect (backport of #12340)

.github/workflows/check.yaml
After removing checklist comment job this workflow doesn't need any permissions including `contents: read`.
=> ci(gha): remove unnecessary  permissions from check.yaml workflow

.github/workflows/_build_publish.yaml
Sometimes we can observe sign image errors related to token validation. This version has a fix which should solve the problem
```
Retrieving signed certificate...
Non-interactive mode detected, using device flow.
Enter the verification code DZXT-XKLG in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=DZXT-XKLG
Code will be valid for 300 seconds
Error: signing [docker.io/kumahq/kuma-cp@sha256:f1798ae5df07acf3968a23f44fd73e1d47ba998ad1ec2612efb92ba752ead4ec]: getting signer: getting key from Fulcio: retrieving cert: error obtaining token: expired_token
main.go:74: error during command execution: signing [docker.io/kumahq/kuma-cp@sha256:f1798ae5df07acf3968a23f44fd73e1d47ba998ad1ec2612efb92ba752ead4ec]: getting signer: getting key from Fulcio: retrieving cert: error …
```
=> chore(deps): upgrade security-actions/sign-docker-image to v4.0.1

renovate.json
We want to move from dependabot to renovate
This file is not final, but it should be a good base. I can't find any builtin way to dynamically provide `baseBranches` or read them from `active-branches.json` file, so our release scripts should be updated to update them on the same tame as `active-branches.json`.
Part of https://github.com/kumahq/kuma/issues/12529
=> ci(renovate): add initial renovate.json configuration file

renovate.json
Currently some PRs have prefix `fix(deps)` when it should be `chore(deps)`
Part of https://github.com/kumahq/kuma/issues/12529
=> ci(renovatae): set PR title semmantic type to be always "chore"

pkg/kds/service/server.go
We have seen `conn closed` errors on live environment when trying to save connection info: 
```
failed to execute query UPDATE resources SET spec=$1, version=$2, modification_time=$3, labels=$4, status=$5 WHERE name=$6 AND mesh=$7 AND type=$8 AND version=$9;: conn closed
```
When we look into logs, the stream is closed just before we see this error: 
I think that we just need better handling of cancelled streams.
=> fix(kuma-cp): handle conn closed issue when creating saving stream connection

mk/distribution.mk
In https://github.com/kumahq/kuma/pull/5945/files#diff-1fb040b6f3b38a29c5de5a15f9633430c8e613a076e0de67c6e0902a4130062a I added `group` and `passwd` to docker images because distroless doesn't have `useradd` binary. I did not know that packaged binaries are copied from dockerfile and this is how these files got in.
I added `--exclude` for both of these files.
Output of `make build/distributions`:
```
a kuma-0.0.0-preview.vlocal-build
a kuma-0.0.0-preview.vlocal-build/LICENSE
a kuma-0.0.0-preview.vlocal-build/bin
a kuma-0.0.0-preview.vlocal-build/README
a kuma-0.0.0-preview.vlocal-build/NOTICE
a kuma-0.0.0-preview.vlocal-build/conf
a kuma-0.0.0-preview.vlocal-build/conf/kuma-cp.defaults.yaml
a kuma-0.0.0-preview.vlocal-build/bin/kuma-cp
a kuma-0.0.0-preview.vlocal-build/bin/kumactl
a …
```
=> fix(distributions): exclude group and passwd from packaged binaries

.github/workflows/lifecycle.yml, renovate.json5
Renovate couldn't update `Kong/public-shared-actions/*`
- Fixed `customManagers` configuration to correctly update `Kong/public-shared-actions` GitHub Actions versions using `github-tags` datasource
- Pinned `kumahq/.github/.github/workflows/wfc_lifecycle.yml` to a specific commit which will be updated by renovate
- Removed unused `customDatasources` for public-shared-actions
- Adjusted `packageRules` to disable default GitHub Actions manager for `Kong/public-shared-actions`
- Cleaned up comments and aligned settings for clarity
Related: https://github.com/kumahq/kuma/issues/12529
=> ci(renovate): fix config to properly update Kong/public-shared-actions versions

renovate.json5
Missing `ci/skip-test` label when updating `Kong/public-shared-actions/*` github actions
This commit fixes an issue where updates to `Kong/public-shared-actions/*` were not getting the `ci/skip-test` label. Since these updates are managed by a custom manager instead of the default `github-actions`, the rule was updated to match by `depType: action`.
Related: https://github.com/kumahq/kuma/issues/12529
=> ci(renovate): match by depType to skip tests for GitHub Actions updates

renovate.json5
Renovate couldn't update `Kong/public-shared-actions/*` which were not pinned by digest
This change updates the `renovate.json5` configuration to handle cases where `Kong/public-shared-actions` dependencies are specified using only the version (e.g., `Kong/public-shared-actions/security-actions/sca@v2.8.0`) instead of including a digest (e.g.,
`Kong/public-shared-actions/security-actions/sca@0ccacffed804d85da3f938a1b78c12831935f992 # v2.8.0`). The `matchStrings` pattern was adjusted to account for version strings without a digest, and the `autoReplaceStringTemplate` was updated to support optional digests, ensuring Renovate correctly processes and updates these dependencies.
Related to: https://github.com/kumahq/kuma/issues/12529
=> ci(renovate): support updates for public-shared-actions without digests

docs/generated/openapi.yaml, mk/docs.mk
Because there was a bug in previous one that polluted the top level of the doc.
All in https://github.com/kumahq/ci-tools/pull/60
Just version bump
=> chore(oapi): update oapi tool

go.mod
bump golang from 1.22.10 to 1.22.11
Go 1.22.11 milestone: https://github.com/golang/go/issues?q=milestone%3AGo1.22.11+label%3ACherryPickApproved
Fix #XX
=> chore(deps): bump golang from 1.22.10 to 1.22.11

go.mod
bump golang from 1.23.4 to 1.23.5
Go 1.23.5 milestone: https://github.com/golang/go/issues?q=milestone%3AGo1.23.5+label%3ACherryPickApproved
Fix #XX
=> chore(deps): bump golang from 1.23.4 to 1.23.5

pkg/config/dp-server/config.go, pkg/xds/bootstrap/components.go
Backport of https://github.com/kumahq/kuma/pull/11399
=> fix(k8s): always authenticate with latest service account token (backport #11399)

pkg/plugins/runtime/k8s/controllers/pod_controller_test.go, pkg/plugins/runtime/k8s/controllers/pod_converter.go, pkg/plugins/runtime/k8s/controllers/pod_converter_test.go, pkg/plugins/runtime/k8s/controllers/testdata/egress/01.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/egress/02.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/egress/03.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/egress/04.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/egress/05.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/egress/egress-exists-labels.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/egress/egress-exists-labels.existing-dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/egress/egress-exists-labels.node.yaml, pkg/plugins/runtime/k8s/controllers/testdata/egress/egress-exists-labels.pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/egress/egress-exists-labels.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/01.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/02.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/03.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/04.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/05.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/06.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists-labels.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists-labels.existing-dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists-labels.pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists-labels.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/update-dataplane.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/update-dataplane.existing-dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/update-dataplane.other-services.yaml, pkg/plugins/runtime/k8s/controllers/testdata/update-dataplane.pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/update-dataplane.services-for-pod.yaml, test/e2e/federation/federation_suite_test.go
Fixes: #12142
We should not override already present dataplane labels with pod labels
=> fix(kuma-cp): fix issue with pod labels overriding existing dataplane labels

app/cni/pkg/install/installer_config.go, app/cni/pkg/install/main.go
this should solve https://github.com/kumahq/kuma/issues/12567 as a simplified implementation.
Bart will come up with a more complete version based on his upcoming refatoring.
Setup a ticker and sync service account token into kubeconfig file periodically
the official client-go SDK re-reads the token once a minute:
https://github.com/kubernetes/client-go/issues/1255
> that method initiates a background process that rereads the token file once a minute.
=> fix(cni): support bound service account token by reloading periodically

.github/workflows/pr-modification.yaml
Reviewers checklist comment was unnecessarily being added to dependabot PRs
Fixed `pr-modifications.yaml` where `-author:dependabot` was not working. Updated it to skip PRs from `app/dependabot` and `app/renovate`. Made minor improvements to the workflow script
=> ci(gha): fix pr-modifications workflow to skip dependabot and renovate PRs

renovate.json
Configure Renovate so it can fully replace Dependabot
Added `dockerfile` manager to the Renovate configuration to automate updates for Dockerfiles
Set `ignorePaths` to an empty array in Renovate config to stop ignoring the `test` directory. By default, `Kong/public-shared-renovate:backend` extends settings that ignore `test`, which we use for e2e framework code and Dockerfiles. Other default ignored paths are not relevant to our project.
Related to: https://github.com/kumahq/kuma/issues/12529
=> ci(renovate): enable dockerfile manager and clear ignorePaths

app/cni/pkg/install/installer_config.go, app/cni/pkg/install/main.go
Manual backport of https://github.com/kumahq/kuma/pull/12592 to `release-2.7`
Fix #XX
=> fix(cni): support bound service account token by reloading periodically (backport of #12592)

.github/workflows/pr-modification.yaml
Removed the reference link from the reviewers checklist comment in `pr-modification.yaml`. The empty line before the link caused issues in automation that processes this workflow, breaking the comment format in the parent project.
=> ci(gha): remove reference link from reviewers checklist comment

test/e2e_env/kubernetes/gateway/gateway.go
Trying to fix the flaky test here: https://github.com/kumahq/kuma/actions/runs/12880363478/job/35911983525#step:12:11928
Wait for readiness of the `test-server-mlbs` app before using it.
Fix #XX
=> test(e2e): fix the flaky test in the gateway scenario

.github/workflows/pr-modification.yaml
PRs like [this one](https://github.com/kumahq/kuma/pull/12635) unnecessarily include the ["Reviewer Checklist" comment](https://github.com/kumahq/kuma/pull/12635#issuecomment-2604301610)
=> ci(gha): exclude kumahq bot PRs from adding reviewer checklist comment

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml
I know we plan to remove `kumactl install observability` eventually, but I think we should update its components for now, especially if it’s easy to do. Once the versions are more current, Renovate can take care of updates going forward.
Upgraded `grafana/grafana` from 8.5.2 to 11.4.0 in the Kubernetes manifest used by `kumactl install observability`. [Checked all intermediate versions](https://grafana.com/docs/grafana/latest/upgrade-guide/), and no configuration changes were needed. Tested locally to make sure it works.
Related to: https://github.com/kumahq/kuma/issues/11693
=> chore(kumactl): upgrade grafana/grafana to 11.4.0 in observability manifests

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/logging/loki/loki.yaml, app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml
I know we plan to remove `kumactl install observability` eventually, but I think we should update its components for now, especially if it’s easy to do. Once the versions are more current, Renovate can take care of updates going forward.
Upgraded `grafana/promtail` from 2.4.1 to 3.3.2 in the Kubernetes manifest used by `kumactl install observability`. No configuration changes were needed, but removed `readOnly: true` from the `/var/lib/grafana/plugins` volume mount to allow Grafana to install the `grafana-lokiexplore-app` plugin. Tested locally to ensure everything works.
Related to: https://github.com/kumahq/kuma/issues/11693
=> chore(kumactl): upgrade grafana/promtail to 3.3.2 in observability manifests

api/mesh/v1alpha1/mesh/schema.yaml, docs/generated/openapi.yaml, tools/resource-gen/main.go
The default mapper configuration wraps these values in `{ value: 100 }` and that results in the following errors in TF:
```
│ Error: failure to invoke API
│
│ error unmarshalling json response body: json: cannot unmarshal bool into Go struct field Outbound.networking.outbound.passthrough of type shared.Passthrough
╵
```
Use a mapper to map these types properly.
xrel https://github.com/Kong/kong-mesh/issues/7201
=> feat(oapi): properly map proto types likes DoubleValue

pkg/kds/service/server.go
Sometimes we see
```
Resource not found: type="Zone" name="zone-01" mesh=""
```
It can happen when we disconnect and remove zone immediately, but HC handler will be executed after that. There is no point in logging it. We already ignore context cancelled.
Alternatively, we could log this on debug level, but I don't think it's worth it.
=> chore(kds): ignore error log on zone not found

pkg/util/watchdog/watchdog.go, pkg/util/watchdog/watchdog_test.go
We are producing logs that we should ignore
I made a change to ignore OnError callback in case of ctx is cancelled.
Other option would be to change log level from ERROR to INFO dynamically in OnError callback implementation, but we would need to repeat this across all watchdog implems. I'm not sure we care about this error. The intention of already existing `!errors.Is(err, context.Canceled)` seems to be to ignore such errors.
While this is fix, I don't think it's worth to backport it. It's not a stability issue, it's just a slight noise in logs.
Fix #12663
=> fix(xds): ignore watchdog error on context cancelled

pkg/plugins/policies/core/jsonpatch/validators/validator.go, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mt-origin-global-mesh-subset.federated.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mt-origin-global-mesh-subset.global.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mt-origin-global-mesh-subset.input.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cli-user_create_mt-origin-global-mesh-subset.non-federated.golden.yaml
Fix: #12362
Since we've introduced new Dataplane kind we can deprecate usage of MeshSubset for selecting proxies. Dataplane is more powerful and better matches our approach for selecting real resources.
=> feat(kuma-cp): deprecate MeshSubset kind in top level targetRef

test/e2e_env/universal/envoyconfig/envoyconfig.go, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/no-policies.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/no-policies.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/outbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/outbound.test-server.golden.json
* The order of operations in `response.diff` depends on the listeners' and clusters' names that contain IP addresses. If we want this order to be stable, we have to sort it once again after redacting the IPs.
* compile regex once globally
=> test(meshtimeout): stable sort the `.diff` list after redacting IPs

mk/kind.mk
We observed that during multizone tests, while all tests succeeded, the job occasionally failed with the following error:
```
failed to update kubeconfig: failed to lock config file: open /home/ubuntu/.kube/config.lock: file exists
```
After investigating the issue and reviewing similar cases, I came across a suggestion to provide a kubeconfig file. Reusing a specific kubeconfig file could help prevent this issue from occurring.
Provide kubeconfig file location on removal
xref: https://github.com/kubernetes-sigs/kind/issues/2008
=> test(e2e): provide kubeconfig on kind cluster removal

test/e2e/externalservices/externalservices_kubernetes_without_egress.go, test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/universal_cluster.go
- Namespace deletion now forcefully removes services, not just pods. This speeds up deletion significantly in perf-tests, where leaving services behind caused long delays due to Kubernetes events issues.
- Added support for custom delete namespace hooks, allowing extra cleanup steps to be run after a namespace deletion is triggered.
- Refactored `DeleteNamespace` to use a default hook that force deletes services and pods while allowing additional hooks.
=> chore(e2e/framework): improve namespace deletion and add custom hooks

test/e2e_env/kubernetes/meshtimeout/meshtimeout.go
=> fix(e2e): add flake attempt on new meshtimeout test as we do on older tests

test/e2e_env/universal/envoyconfig/envoyconfig.go, test/e2e_env/universal/envoyconfig/testdata/meshratelimit/inbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshratelimit/inbound.input.yaml, test/e2e_env/universal/envoyconfig/testdata/meshratelimit/inbound.test-server.golden.json
We need more tests before we add rules api for MeshRateLimit
=> chore(e2e): add envoy config e2e tests for MeshRateLimit

test/e2e_env/universal/envoyconfig/envoyconfig.go, test/e2e_env/universal/envoyconfig/testdata/meshfaultinjection/inbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshfaultinjection/inbound.input.yaml, test/e2e_env/universal/envoyconfig/testdata/meshfaultinjection/inbound.test-server.golden.json
We need to add more e2e tests before we implement rules api for MeshFaultIjection
=> chore(MeshFaultInjection): add envoy config e2e test

pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go, tools/policy-gen/bootstrap/root.go
We were not passing options for MeshTLS policy matching, because of this shadow effect didn't work for it. I've also updated policy-gen tool to prevent this from happening in the future.
=> fix(MeshTLS): fix shadow policy effect for MeshTLS

test/e2e_env/universal/envoyconfig/envoyconfig.go, test/e2e_env/universal/envoyconfig/testdata/meshaccesslog/inbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshaccesslog/inbound.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshaccesslog/outbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshaccesslog/outbound.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshfaultinjection/inbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshfaultinjection/inbound.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshratelimit/inbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshratelimit/inbound.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound-rules-dpp.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound-rules-dpp.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound-rules.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound-rules.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/no-policies.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/no-policies.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/outbound.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/meshtimeout/outbound.test-server.golden.json
We will need this to test MeshTLS policy
=> chore(e2e): enable mTLS in envoy config tests

pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin.go
GRPC is an HTTP2 protocol and the difference in configuration is only additional grpc stats. We can enable it for GRPC.
Configure MeshFaultInjection for GRPC protocol
=> feat(meshfaultinjection): support GRPC protocol

test/e2e_env/kubernetes/gateway/cross-mesh.go, test/e2e_env/kubernetes/gateway/delegated/meshpassthrough.go, test/e2e_env/kubernetes/gateway/gateway.go, test/e2e_env/kubernetes/meshmetric/meshmetric.go
We want to speed up tests execution
* added parallel for MeshMetrics setup to speedup setting up a cluster
* Added `MustPassRepeatedly` for Consistently to avoid waiting for a minute
time reduced from 20-22min -> 18-20min
=> test(e2e): change some assertions to reduce time

docs/generated/openapi.yaml, pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/schema.yaml, pkg/core/resources/apis/meshservice/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshfaultinjection/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshhttproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshmetric/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshproxypatch/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshratelimit/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshretry/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtcproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtimeout/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtls/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtrace/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/schema.yaml, tools/openapi/templates/schema.yaml, tools/policy-gen/generator/cmd/openapi.go
Described in https://github.com/kumahq/kuma/issues/12734. This is only part of the work, the part needed for the TF provider. We should have validation not only there but on the API as well.
Add "readOnly" parameter to generated OAPI schema. For modification / creation time do it always. For `status` do it only when it's present in the schema.
xrel https://github.com/kumahq/kuma/issues/12734
=> fix(api): mark read-only fields as readOnly

pkg/core/resources/apis/core/interfaces.go, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/helpers.go, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/meshmultizoneservice.go, pkg/core/resources/apis/meshservice/api/v1alpha1/helpers.go, pkg/plugins/policies/core/rules/common/resolvetargetref.go, pkg/plugins/policies/core/rules/common/resolvetargetref_test.go, pkg/plugins/policies/core/rules/common/suite_test.go, pkg/plugins/policies/core/rules/outbound/resourcerules.go, pkg/test/resources/builders/meshmultizoneservice_builder.go, pkg/test/resources/builders/meshservice_builder.go
It's a minor bug, I noticed it while covering `ResolveTargetRef` function with unit tests. It resulted in creating extra entities in `ResourceRules` map, i.e if policy has:
```yaml
to:
- targetRef:
kind: MeshService
name: backend
namespace: kuma-demo
sectionName: non-existent-section-name
default: $conf1
```
we're going to produce entry
```json
{
"..."
"meshservice:mesh/mesh-1:namespace/kuma-demo:name/backend:section/non-existent-section-name": $conf1,
"..."
}
```
but it won't be used by the actual policy plugins because `MeshService` doesn't have `non-existent-section-name`.
* properly handle section names in `ResolveTargetRef` function
* add unit tests
* common interface for ports to avoid depending on specific types like MeshService or MeshMutliZoneService
=> fix(rules): a bug in ResolveTargetRef that caused creating excessive entries in ResourceRules

docs/generated/openapi.yaml, pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshfaultinjection/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshhttproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshmetric/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshproxypatch/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshratelimit/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshretry/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtcproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtimeout/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtls/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtrace/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/schema.yaml, tools/policy-gen/generator/cmd/openapi.go
In https://github.com/kumahq/kuma/pull/12735 I mistakenly added `status.readonly: true` to properties that did not have `status` in the first place.
Use `select` to filter this out
> Changelog: fix(api): mark read-only fields as readOnly
=> fix(api): only mark readonly when status exists

api/mesh/v1alpha1/mesh/rest.yaml, api/mesh/v1alpha1/meshgateway/rest.yaml, docs/generated/openapi.yaml, pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml, pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml, tools/openapi/templates/endpoints.yaml
Because they are readOnly, you shouldn't update "warnings" yourself. Pretty much the same as https://github.com/kumahq/kuma/pull/12742.
Add "readOnly" in template.
xrel https://github.com/kumahq/kuma/issues/12734
=> fix(api): mark warnings as read-only

pkg/api-server/resource_endpoints.go
In the logs I noticed an error
```
http: superfluous response.WriteHeader call from github.com/emicklei/go-restful/v3.(*Response).WriteHeader (response.go:224)
```
After checking the code, I noticed that we don't return on error, which causes execution to continue to the next step, `WriteHeaderAndJson`. Since we call it a second time and it internally calls `WriteHeader`, we encounter the following error.
Changed the logic to return earlier
=> fix(api-server): return when there is error on delete

pkg/util/watchdog/watchdog.go, pkg/util/watchdog/watchdog_test.go
Issue: https://github.com/kumahq/kuma/issues/12657
Changed to wait for the `HasTicked` to be called before first Ticker event, since there was a race and sometimes on ticked happened before the assertion 
fix: https://github.com/kumahq/kuma/issues/12657
=> fix(watchdog): wait for the first tick

pkg/plugins/policies/core/xds/meshroute/clusters.go, pkg/plugins/policies/core/xds/meshroute/listeners.go, test/e2e_env/kubernetes/gateway/gateway.go, test/e2e_env/multizone/meshservice/policies.go, test/e2e_env/multizone/meshtimeout/meshtimeout.go
We were using an incorrect way to retrieve protocol for a MeshService, and that caused the configuration to not be applied
Instead of using GetServiceProtocol, I changed the implementation to retrieve the port protocol directly from MeshService and use it. Additionally, I added an end-to-end (E2E) test to verify that `idleTimeout` is correctly set. The test ensures the connection is closed after 2 seconds, given that the default timeout is 1 hour.
Fix https://github.com/kumahq/kuma/issues/12702
=> fix(meshservice): use Protocol from the MeshService

pkg/plugins/runtime/k8s/controllers/inbound_converter.go, pkg/plugins/runtime/k8s/controllers/pod_controller_test.go, pkg/plugins/runtime/k8s/controllers/testdata/01.dataplane.yaml, pkg/plugins/runtime/k8s/util/util.go, pkg/plugins/runtime/k8s/util/util_test.go
At this moment we are taking inbound name from service port name. In order to get rid of kuma.io/service we need to take name from pod port name. Since we are not using name at the moment, it is safe to switch this.
=> feat(kuma-cp): inbound name should be taken from pod instead of service

pkg/xds/auth/callbacks.go, pkg/xds/auth/k8s/authenticator.go, test/e2e_env/universal/auth/dp_auth.go
Right now, we are authenticating the DP on every `OnStreamRequest` event in `auth.Callback`, and [the authenticator has a cache](https://github.com/kumahq/kuma/blob/5359d941bf6a7fab22cb177cd94de1112b9b4ad7/pkg/xds/auth/k8s/authenticator.go#L48-L64) which caches the successful verification results. The Kubernetes API Server is only called when it is not hitting the cache, and the cache can last long: when the cache expires, the token is already expired from Kube's point of view.
In a cluster with bound service account token enabled and "extend-token-expiration" disabled, service account tokens expire once an hour by default.
* Only auth once per gRPC stream.
* Remove auth cache as it's not required when it's only auth once during a gRPC stream/connection.
fixes …
=> fix(xds): only auth once per xds gRPC stream in kuma-cp

test/e2e_env/universal/gateway/cross-mesh.go, test/e2e_env/universal/gateway/gateway.go, test/e2e_env/universal/gateway/utils.go, test/e2e_env/universal/observability/meshtrace.go
MeshGatewayRoute is deprecated in favor of MeshHTTPRoute.
Fix: https://github.com/kumahq/kuma/issues/12763
=> test(e2e): changed MeshGatewayRoute to MeshHTTPRoute

test/e2e_env/universal/envoyconfig/builtingateway.go, test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshaccesslog/mal-with-from.gateway-proxy.golden.json, test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshaccesslog/mal-with-from.input.yaml, test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshaccesslog/mt-with-to.gateway-proxy.golden.json, test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshaccesslog/mt-with-to.input.yaml
We need more tests before we add rules api to MeshAccessLog selecting gateway
=> chore(MeshAccessLog): add envoyconfig e2e tests for MeshAccessLog selecting gateway

test/e2e_env/universal/envoyconfig/builtingateway.go, test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshtls/inbound-permissive.gateway-proxy.golden.json, test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshtls/inbound-permissive.input.yaml, test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshtls/inbound.gateway-proxy.golden.json, test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshtls/inbound.input.yaml
We need more tests to implement rules api for selecing gateway in MeshTLS
=> chore(e2e): add envoy config test for MeshTLS selecting gateway

test/e2e_env/universal/envoyconfig/builtingateway.go, test/e2e_env/universal/envoyconfig/sidecars.go
This should fix flaky test where endpoints are missing in xds config
=> fix(e2e): use eventually on envoy config comparison as some resources may not be present on first check

pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin_test.go
We need to properly configure gateway when MeshTLS with new rules api is used
Fix #12819
=> feat(MeshTLS): meshTLS should configure gateway when rules api is used

pkg/plugins/policies/meshaccesslog/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshratelimit/api/v1alpha1/deprecated.go, pkg/plugins/policies/meshtls/api/v1alpha1/deprecated.go
We have added new `rules` api to inbound policies. We can now safely deprecate `from` section in these policies
=> feat(kuma-cp): deprecate from section in policies with rules api implemented

pkg/core/resources/model/resource.go, pkg/kds/v2/client/kds_client.go, pkg/kds/v2/client/stream.go, pkg/kds/v2/store/sync.go, pkg/kds/v2/store/sync_test.go, pkg/util/xds/logging_callbacks.go
While working on
[kumahq/kuma#12719](https://github.com/kumahq/kuma/issues/12719), I noticed some strange behavior. If there are X resources and one is invalid, none of the valid resources are added. Once the invalid resource is fixed, the previously valid resources are still not added.
We send a NACK for the invalid resource type, but there's no way to reject only a single resource of that type—[we have to NACK the entire resource type](https://github.com/envoyproxy/envoy/issues/5739). Additionally, since the hash in the cache remains unchanged for valid resources, they are not resent (this is how Delta xDS works), and only the last changed resource is sent again.
* Changed the logic to mark IsInitialRequest when there is a NACK, since Delta XDS, on the second request, sends only the …
=> fix(kds): add all valid resources and skip only not valid (backport #12776)

test/framework/deployments/kic/kubernetes.go
Noticed a flake https://github.com/kumahq/kuma/actions/runs/13278477384/job/37072625102
While investigating a debug package, I noticed the following error:
```
2025-02-12T05:36:51Z	error	controllers.Gateway	Reconciler error	{"reconcileID": "0c64b565-7733-4f48-b2ca-976f28c2cbad", "error": "publish service reference \"kic/kic-gateway-proxy\" from Gateway's annotations did not match configured controller manager's publish services (\"delegated-gateway-ms/delegated-gateway-ms-gateway-proxy\")"}
```
This indicated that changes from another test case were affecting the results of a different test. Upon investigation, I found that we had not configured the `watchNamespaces` parameter, causing KIC to react to changes from all namespaces. I added a configuration to restrict it to the ingress …
=> test(e2e): configure kic to watch specific namespace

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/logging/loki/loki.yaml, app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml, app/kumactl/data/install/k8s/metrics/prometheus/server.yaml
I know we plan to remove `kumactl install observability` eventually, but I think we should update its components for now, especially if it’s easy to do. Once the versions are more current, Renovate can take care of updates going forward.
- Updated Prometheus server image to the latest available and reordered arguments for better grouping.
- Added missing resources to kube-state-metrics roles to prevent RBAC errors.
- Improved Loki configuration:
- Added startupProbe and adjusted other probes for faster startup.
- Reconfigured volumes to align with Grafana documentation.
- Provided Loki config secret as stringData instead of data to avoid manual base64 encoding.
- Applied minor configuration improvements.
Related to: https://github.com/kumahq/kuma/issues/11693
=> feat(kumactl): update install observability components

api/openapi/specs/api.yaml, api/openapi/types/zz_generated.api.go, docs/generated/openapi.yaml, pkg/api-server/resource_endpoints.go, test/e2e_env/universal/envoyconfig/utils.go
The docs were not very clear and the entities were using the already overloaded "inspect" word.
=> chore(api-server): improve types and docs for /dataplanes/_config

.github/workflows/ci-stability-master.yaml, .github/workflows/ci-stability.yaml
We should trigger `build-test-distribute.yaml` manually instead of pushing a commit directly into the PR. This approach increases the visibility of the state of CI in our tools.
Added a new workflow that triggers build-test-distribute.yaml and then checks if it runs successfully. If it starts, the job completes. I kept the ci-stability job so we can use it to check PR change stability.
Fix https://github.com/kumahq/kuma/issues/11624
=> chore(gha): added a workflow to trigger build on master branch

pkg/plugins/runtime/k8s/controllers/meshservice_controller.go
Fixes an issue in `MeshService` controller where `GetNamespace()` was used on a Namespace object, causing it to list all services in the cluster. Replaced with `GetName()` to correctly scope label changes. This significantly improves performance in large deployments.
=> fix(meshservice): prevent reconciling all namespaces on label change

pkg/core/resources/model/resource.go
I was investigating a test fail https://github.com/kumahq/kuma/actions/runs/13448107702/job/37578543976 and noticed there was a panic
```
fatal error: concurrent map read and map write
goroutine 5374 [running]:
github.com/kumahq/kuma/pkg/plugins/policies/core/matchers.dppSelectedByZone({0x40d65f0, 0xc00275c120}, 0xc002aca5e8, 0x0)
github.com/kumahq/kuma/pkg/plugins/policies/core/matchers/dataplane.go:299 +0xb1
```
I reviewed another goroutine and noticed that we perform an update. I suspect this happens because we didn't clone the labels in ComputeLabels.
```
github.com/kumahq/kuma/pkg/hds/tracker.(*tracker).updateDataplane(0xc00048e700, 0x20, 0xc0018317a0, 0x1)
github.com/kumahq/kuma/pkg/hds/tracker/callbacks.go:228 +0x7c4
```
=> fix(kuma-cp): clone labels

pkg/api-server/resource_endpoints.go, pkg/api-server/testdata/resources/inspect/dataplanes/_rules/dataplane_kind_meshtimeout_section_name.golden.json
Fixing flake when inbounds were reordered in inspectapi
=> fix(inspectapi): inspect api flake because of inbound ordering

mk/check.mk
Otherwise it fails in parent project.
Add CI_TOOLS to the invocation.
=> chore(lint): fix api lint path

app/kumactl/cmd/export/export.go, pkg/core/managers/apis/mesh/mesh_manager_test.go, pkg/core/resources/apis/system/constants.go, pkg/defaults/components.go, pkg/defaults/envoy_admin_ca_test.go, pkg/defaults/mesh/mesh.go, pkg/defaults/mesh/mesh_test.go, pkg/defaults/mesh/signing_key.go, pkg/envoy/admin/tls/pki.go, pkg/intercp/tls/pki.go, pkg/kds/context/context.go, pkg/kds/context/context_test.go, pkg/kds/v2/store/sync.go, pkg/plugins/authn/api-server/tokens/admin_token_bootstrap.go, pkg/plugins/authn/api-server/tokens/admin_token_bootstrap_test.go, pkg/plugins/authn/api-server/tokens/issuer/token.go, pkg/plugins/authn/api-server/tokens/plugin.go, pkg/plugins/authn/api-server/tokens/ws/ws_test.go, pkg/test/resources/samples/global_secret_samples.go, pkg/test/resources/samples/secret_samples.go, pkg/tokens/builtin/components.go, pkg/tokens/builtin/issuer/token.go, pkg/tokens/builtin/zone/token.go, pkg/xds/auth/universal/auth_test.go
They are used all over the place and make more sense in this more generic package
=> refactor(tokens): move token constants to core/resources/apis/system

api/mesh/v1alpha1/mesh/rest.yaml, api/mesh/v1alpha1/meshgateway/rest.yaml, docs/generated/openapi.yaml, pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml, pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml, tools/openapi/templates/endpoints.yaml
It's just wrong and causes failures upstream.
Put it in the right place - https://swagger.io/docs/specification/v3_0/describing-parameters/#default-parameter-values
xrel: https://github.com/kumahq/kuma/issues/12935
=> fix(oapi): fix default in size query parameter

pkg/xds/server/callbacks/dataplane_callbacks.go, pkg/xds/server/callbacks/dataplane_callbacks_test.go, pkg/xds/server/callbacks/dataplane_lifecycle.go, pkg/xds/server/callbacks/dataplane_metadata_tracker.go, pkg/xds/server/callbacks/dataplane_sync_tracker.go, pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
Manual cherry-pick of #12886 to branch `release-2.9`
cherry-picked commit f6f58cf76539055f7d0f5c14b1135bd3680419c9
=> fix(kuma-dp): prevent watchers from being cleaned up unexpectedly (backport of #12886)

pkg/plugins/resources/k8s/native/api/v1alpha1/zz_generated.mesh.go, pkg/plugins/resources/k8s/native/api/v1alpha1/zz_generated.system.go, tools/resource-gen/pkg/generator/main.go
While working on another issue I noticed that we incorrectly set the scope for Kubernetes CRDs.
When `isNamespaced` set scope `Namespaced`
=> fix(k8s): fix scope assignment to the resource

pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go
If there is one invalid MeshExternalService we don't generate other valid services.
Skip invalid resource and process valid ones
Fix: https://github.com/kumahq/kuma/issues/12821
=> fix(kuma-cp): process other MES when one is invalid

test/e2e_env/kubernetes/meshcircuitbreaker/meshcircuitbreaker.go
We were using the same name as other policy. Let's see if it helps
=> test(e2e): use unique name of the resource

test/e2e_env/kubernetes/gateway/gateway.go
Noticed a flake: Once Envoy establishes a connection, it might continue routing traffic to the same instance, which is not expected by our MLBS. This happens because connections are persisted and reused. They can be closed by a timeout or a cluster reload. In the test, I observed that the test eventually passes, but initially, it takes time to start using the policy strategy.
I introduced a timeout policy to shorten connection durations. This should ensure that routing aligns with our strategy sooner.
=> test(e2e): make connections shorter when using MLBS

pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
Manual cherry-pick of #12948 to branch `release-2.7`
cherry-picked commit 4c0866462eacc77d1ca1e1b8e01fca4807fa1477
=> test(unit): check correctly active watchdogs (backport of #12948)

mk/k3d.mk
We noticed it a bit flaky so maybe using manifest is more stable
=> test(e2e): use manifest instead of operator to install calico

docs/generated/openapi.yaml, pkg/plugins/policies/meshaccesslog/api/v1alpha1/meshaccesslog.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/meshcircuitbreaker.go, pkg/plugins/policies/meshratelimit/api/v1alpha1/meshratelimit.go, pkg/plugins/policies/meshtimeout/api/v1alpha1/meshtimeout.go, pkg/plugins/policies/meshtls/api/v1alpha1/meshtls.go, tools/policy-gen/generator/pkg/parse/policyconfig.go
Renamed the descriptor field in my previous [PR](https://github.com/kumahq/kuma/pull/12713) but missed these policy markers.
=> fix(policy): rename `interpret_from_entries_as_rules` market to `is_from_as_rules`

pkg/gc/collector.go
Data race, since in the test we create multiple instances we hit a race condition.
The logger was on a package level, meaning each call for `NewCollector` overrides the logger. Move it to the structure
=> fix(kuma-cp): move package level variable to struct

.github/workflows/_provenance.yaml
fix the CI failure caused by out-dated provenance workflow:
https://github.com/kumahq/kuma/actions/runs/13560066168/job/37965057131
Upgrade the `slsa generator` to version `2.0.0`.
Consulted security experts.
=> ci(.github): fix the provenance workflow

pkg/core/managers/apis/dataplane/dataplane_manager.go, pkg/core/managers/apis/dataplane/dataplane_manager_test.go, pkg/core/resources/manager/manager.go, pkg/test/resources/builders/dataplane_builder.go, pkg/xds/server/callbacks/dataplane_lifecycle.go, pkg/xds/server/callbacks/dataplane_lifecycle_test.go, test/e2e_env/universal/auth/dp_auth.go, test/framework/interface.go, test/framework/setup.go
We need to handle dpp labels properly in order to be able to select them in policies
=> fix(dpp): save and update labels from Dataplane resource on Universal

test/e2e_env/multizone/connectivity/available_services.go
The zone name validation we currently have is not strict enough. This zone name was creating a lot of noise in the logs
xref: https://github.com/kumahq/kuma/issues/12988
=> test(e2e): fix invalid zone name

pkg/plugins/config/k8s/store.go, test/e2e/federation/federation_kubernetes.go, test/e2e/federation/federation_suite_test.go, test/e2e/federation/federation_universal.go
Other store return errors that are in core_store.
KDS relies on these errors to return errors or NACK.
This fixes a federation test
=> fix(secrets): return properky typed errors on conflict

pkg/util/files/files.go
Artifacts on github don't like `|` characters
=> fix(e2e): escape | character

api/mesh/v1alpha1/dataplane_helpers.go, pkg/core/resources/model/resource.go, pkg/kds/context/context.go, pkg/kds/context/full_sync_test.go, pkg/kds/context/testdata/full_sync/mesh-only/global.golden.yaml, pkg/kds/context/testdata/full_sync/mesh-only/global.input.yaml, pkg/kds/context/testdata/full_sync/mesh-only/zone-1.golden.yaml, pkg/kds/context/testdata/full_sync/mesh-only/zone-2.golden.yaml, pkg/kds/context/testdata/full_sync/policy-simple/global.golden.yaml, pkg/kds/context/testdata/full_sync/policy-simple/global.input.yaml, pkg/kds/context/testdata/full_sync/policy-simple/zone-1.golden.yaml, pkg/kds/context/testdata/full_sync/policy-simple/zone-1.input.yaml, pkg/kds/context/testdata/full_sync/policy-simple/zone-2.golden.yaml, pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/global.golden.yaml, pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/global.input.yaml, pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/zone-1.golden.yaml, pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/zone-1.input.yaml, pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/zone-2.golden.yaml, pkg/plugins/authn/api-server/tokens/admin_token_bootstrap.go, pkg/test/ginkgo.go, pkg/test/kds/setup/server.go, pkg/test/store/load.go, pkg/util/files/files.go, test/framework/debug.go, test/framework/ssh/ssh.go
There may be cases where either system or user may want to not sync a specific resource with KDS.
Until now this wasn't really possible. So we ended having specific hard coded config types.
This allows disabling KDS for specific resources by adding the label `kuma.io/kds-sync: disabled`
We add the filter as a check in both filters.
Also added functional testing around the whole KDS.
You can create a set of files of starting state and save end state.
This should make it easy to add a batch of non regression and exploratory tests to KDS.
Fix #12916
=> feat(kds): add support for kuma.io/kds-sync label

pkg/api-server/testdata/resources/crud/put_meshes_04.golden.json, pkg/api-server/testdata/resources/crud/put_meshexternalservice_01.golden.json, pkg/api-server/testdata/resources/crud/put_meshexternalservice_02.golden.json, pkg/api-server/testdata/resources/crud/put_meshmultizoneservice_01.golden.json, pkg/api-server/testdata/resources/crud/put_meshmultizoneservice_02.golden.json, pkg/api-server/testdata/resources/crud/put_meshservice_02.golden.json, pkg/core/resources/apis/mesh/deprecated.go, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/deprecated.go, pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/deprecated.go, pkg/core/resources/apis/meshservice/api/v1alpha1/deprecated.go, pkg/core/resources/apis/system/deprecated.go, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mes.federated.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mes.global.golden.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mes.input.yaml, pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mes.non-federated.golden.yaml
When running on k8s `r.GetMeta().GetName()` returns namespaces name which doesn't pass validation. We shouldn't use this value but instead `GetDisplayName()`
Check if `kuma.io/display-name` fulfill the requirement.
Fix https://github.com/kumahq/kuma/issues/13023
=> fix(resource): use kuma.io/display-name instead of name

.renovate/go-control-plane.json, renovate.json
- Added a custom Renovate manager for `github.com/kumahq/go-control-plane` (our fork of `envoy/go-control-plane`) dependencies in `go.mod`
- Ensured updates use a regex-based manager instead of the default Go module manager
- Disabled updates for `replace` dependencies in `gomod` to avoid conflicts
- Updated `renovate.json` to extend the new `go-control-plane` preset
- Upgraded `github>Kong/public-shared-renovate:backend` to version `1.2.0`
- Enabled Kubernetes and Helm `values.yaml` updates and improved `prBodyTemplate` (removed unnecessary content)
Part of: https://github.com/kumahq/kuma/issues/12529
=> feat(renovate): add custom manager for go-control-plane and update config

DEVELOPER.md
Adding notes for debugging E2E in IDE
Fix #XX
=> chore(dev): add notes for debugging E2E in IDE

pkg/kds/context/testdata/full_sync/mesh-only/global.golden.yaml, pkg/kds/context/testdata/full_sync/policy-simple/zone-1.golden.yaml, pkg/test/store/load.go
These tests were flaking
Sort resource names before building golden YAML
=> chore(test/unit): fix order in golden files for kds context sync tests

renovate.json
Added a package group for `kumactl install demo|observability` container images. This helps reduce the number of PRs since each update requires running `make format` and updating golden files, making singular PRs tedious.
Related to: https://github.com/kumahq/kuma/issues/12529
=> chore(renovate): group kumactl install k8s container images

pkg/core/resources/model/labels/labels.go, pkg/core/resources/model/resource.go
**This PR does not change anything from `kuma` perspective.**
Terraform will show changes to labels that are automatically generated, like `kuma.io/mesh` so applying:
```
resource "konnect_mesh_external_service" "my_meshexternalservice" {
cp_id = konnect_mesh_control_plane.my_meshcontrolplane.id
labels = {
environment = "production"
}
...
}
```
Will succeed but on the next `apply` we would see `kuma.io/mesh` because it's automatically generated:
```
~ resource "konnect_mesh_external_service" "my_meshexternalservice" {
~ labels            = {
- "kuma.io/mesh" = "mesh-9" -> null
}
name              = "external-service-example"
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
This PR allows the provider to import `AllComputedLabels` and remove them from terraform plan.
Export …
=> chore(api): export all computed labels to be used in another project

pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/testdata/bootstrap.gateway.golden.yaml, pkg/xds/bootstrap/testdata/generator.gateway.golden.yaml
We can see in the logs
```
Usage of the deprecated runtime key overload.global_downstream_max_connections, consider switching to `envoy.resource_monitors.global_downstream_max_connections` instead.This runtime key will be removed in future.
```
the field was deprecated.
Changed to `envoy.resource_monitors.global_downstream_max_connections`
=> fix(kuma-cp): change usage of deprecated global_downstream_max_connections

.renovate/go-control-plane.json
- Grouped all `go-control-plane` updates, including `envoyproxy` and `kumahq` (fork replaces)
- Switched package matching from regex to glob for better readability
- Fixed PR table links to correctly display updated dependencies
Related to: https://github.com/kumahq/kuma/issues/12529
=> feat(renovate): improve go-control-plane updates and grouping

pkg/kds/context/full_sync_test.go
- Increased `time.Sleep` from 2s to 5s to ensure sync completes before proceeding
- Debugging showed that lowering this value to 100ms increased flakiness, reproducing the same failures seen in CI
- If this change doesn't resolve the flakes, we will need to find a more reliable way to verify sync completion.
=> test(kds): increase wait time in full sync test to reduce flakiness

pkg/kds/context/full_sync_test.go, pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/global.golden.yaml, pkg/test/store/load.go
While debugging a flake I noticed that `MatchGoldenYAML` doesn't work correctly. In the match, it compares only the first element of the file. 
https://pkg.go.dev/gopkg.in/yaml.v3#section-readme
> Multi-document unmarshalling is not yet implemented, and base-60 floats from YAML 1.1 are purposefully not supported since they're a poor design and are gone in YAML 1.2.
Changed to `MatchGoldenEqual` since we are using it in other tests. Also, change sort to `strings.Cmp`
=> test(unit): compare file content instead of yaml

UPGRADE.md, pkg/core/resources/apis/meshservice/match.go, pkg/core/resources/apis/meshservice/status/updater.go, pkg/core/resources/apis/meshservice/status/updater_test.go, pkg/xds/topology/outbound.go
Fixing an issue on the MeshService updater
> update MeshService updater to take into account target port
fixes https://github.com/kumahq/kuma/issues/12042
=> fix(meshservice): fix inbound port selecting logic on MeshService

.renovate/go-control-plane.json, renovate.json
Our changelog automation relies on the dependabot commit/PR message format, so changing it would require updates to the automation.
- Removed custom semanticCommitScope for go-control-plane and GitHub Actions
- Bumped shared config to backend#1.3.0
- Ensures existing changelog automation that relies on dependabot-like commits continues working
=> chore(renovate): unify commit messages to match dependabot for changelog automation

test/e2e_env/gatewayapi/conformance_test.go
[PR](https://github.com/kumahq/kuma/pull/13104) broke gateway api test, since it requires secret access.
Enabled allow secrets in all namespaces for a gatewayapi test
=> test(gatewayapi): allow secrets in all namespaces

.github/workflows/release.yaml
Use the new `release-tool` which fixed a changelog generation bug. The old changelog generation would keep the PRs with "Changelog: skip" signs due to a wrong conditional check.
=> chore(deps): bump release-tool from v1.1.4 to v1.1.5

.renovate/github-actions.json, renovate.json
It's unnecessary to include github-actions dependency updates in changelog
- Upgraded `Kong/public-shared-renovate:backend` preset from `1.3.0` to `1.4.0`
- Removed unnecessary `prBodyTemplate`, now included in the updated preset
- Applied reusable GitHub Actions preset which adds `> Changelog: skip` footer
- Improved descriptions for Kubernetes image updates and GitHub Actions rules
Tested on fork
=> chore(renovate): upgrade backend preset to 1.4.0 and reuse GitHub Actions preset

test/e2e_env/multizone/healthcheck/healthcheck.go
Noticed a flake, while checking logs:
```
Error: Failed to generate Envoy bootstrap config. Invalid request: mesh: mesh "healthcheck-app-on-universal" does not exist
```
Wait for mesh to be synced first
=> test(e2e): wait for mesh to be synced

UPGRADE.md
We should have info about api changes and deprecations in upgrade.md
=> feat(docs): add information about new rules api and dataplane kind in upgrade md

pkg/test/ginkgo.go, test/e2e_env/gatewayapi/conformance_test.go, test/framework/config.go
Instead of https://github.com/kumahq/kuma/pull/13165 - because that did not work. Please review the parent PR first.
That way in a parent project we can get the default and overwrite only the parts of the config that we care about. So if a change happens like in https://github.com/kumahq/kuma/pull/12982/files#diff-4097df65e73d6b3a2813df0ea3c87f15a6c43ba3aca9b73b3e60346758ef0344R65 we won't need to modify the parent project.
Manually init the e2e configuration by moving the init function to `RunE2ESpecs`.
=> chore(e2e): rewrite e2e config init

test/e2e_env/multizone/meshhttproute/test.go
With GinkgoHelper there were wrong line numbers generated when generated list of disabled tests
=> refactor(e2e): remove unnecessary GinkgoHelper call in meshhttproute test

.github/workflows/_build_publish.yaml
Build binaries is nearly timing out (mostly on cleanup) in parent project. Let's bump the time while we investigate. Please take a look at the list of failing builds in the linked parent project PR.
Bump the time.
=> ci(publish): change timeout of build_publish to 50 min from 40 min

DEVELOPER.md, mk/k3d.mk
Better local dev flow
Split and renamed make targets for better structure and usability:
- Introduced `k3d/deploy/kumactl` as replacement for `k3d/deploy/kuma`
- Added modular wait targets for CP readiness
- Added `clean/install/upgrade` targets for Helm-based deployments
- Improved logging and cleanup behavior
- Kept backward-compatible aliases with clear deprecation messages
=> refactor(make): refactor k3d deploy targets

mk/docker.mk, tools/releases/dockerfiles/base-root.Dockerfile, tools/releases/dockerfiles/base.Dockerfile, tools/releases/dockerfiles/kuma-cni.Dockerfile, tools/releases/dockerfiles/kuma-cp.Dockerfile, tools/releases/dockerfiles/kuma-dp.Dockerfile, tools/releases/dockerfiles/kumactl.Dockerfile, tools/releases/dockerfiles/static.Dockerfile
We are using debian 11 for out base images
https://www.debian.org/releases/bullseye/
> The Debian 11 life cycle encompasses five years: the initial three years of full Debian support, until August 14th, 2024, and two years of Long Term Support (LTS), until August 31st, 2026.
which means it doesn't get some basic updates of the packages
Upgraded to debian 12
> The Debian 12 life cycle encompasses five years: the initial three years of full Debian support, until June 10th, 2026, and two years of Long Term Support (LTS), until June 30th, 2028.
=> chore(deps): upgrade debian11 to debian12 image

test/framework/k8s_cluster.go
Fixing the issue of not using specified chart version for the helm upgrade feature in the test framework.
The `K8sCluster` is always using the latest version of the chart to perform helm upgrade actions, instead of the specified chart version in the `opts`. This caused some issues when the new version chart is not compatible of the old version chart.
It is caused by a bug in `github.com/gruntwork-io/terratest`, and there is a workaround by specifying this `--version` manually using `helm.Options.ExtraArgs`. It does no harm to `helm.Install` as they use different key in `ExtraArgs`.
The bug in the mod is tracked using this issue:
https://github.com/gruntwork-io/terratest/issues/1531
=> test(framework): use specified chart version when helm upgrade

.github/codeql/codeql-config.yml
We can see a security warning 
> Use of insecure HostKeyCallback implementation
But it's in a test file that won't affect anyone and it's required for ssh in e2e test
Ignored specific failed from CodeQL check
=> chore(codeql): ignore security warning in test file

test/e2e_env/multizone/gateway/cross-mesh.go, test/e2e_env/multizone/meshservice/migration.go
Test fail
> 2025-04-01T13:23:51.147Z	INFO	dataplane	trying to fetch bootstrap configuration from the Control Plane
Error: Failed to generate Envoy bootstrap config. Invalid request: mesh: mesh "msmigration" does not exist
Added wait for mesh sync
=> test(e2e): wait for Mesh sync in multizone setup

pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go
At the moment, we don't support the configuration of ZoneEgress so we can remove the test.
Fix https://github.com/kumahq/kuma/issues/13257
xref:https://github.com/kumahq/kuma/issues/12849
=> test(unit): remove skipped MeshCircuitBreaker tests

pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go, pkg/test/resources/validators/validation.go
We don't support egress policies for MeshExternalService
xref: https://github.com/kumahq/kuma/issues/12849
Fix: https://github.com/kumahq/kuma/issues/13255
=> test(unit): remove skipped MeshLoadBalancingPolicy

pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
We don't need these skipped tests since we don't support egress matching. Also, it makes sense to create an empty list of rules in some cases but we should review them
Fix https://github.com/kumahq/kuma/issues/13258
xref: https://github.com/kumahq/kuma/issues/12849
=> test(unit): remove skipped MeshHealthCheck test

pkg/plugins/policies/core/matchers/egress.go, pkg/plugins/policies/core/rules/outbound/resourcerules.go, pkg/plugins/policies/core/rules/outbound/suite_test.go, pkg/plugins/policies/core/rules/rules.go
Same as https://github.com/kumahq/kuma/pull/12603, but for outbound rules
=> refactor(rules): use ResourceList instead of []Resource in function signatures

test/e2e_env/multizone/meshhttproute/test.go
We should verify these functionalities. I tested locally with `MustPassRepeatedly(100)` and had no fails
* Increase number of requests
* Change time to be less aggressive
Fix https://github.com/kumahq/kuma/issues/13236
=> test(e2e): enable multizone MeshHTTPRoute test

test/e2e_env/multizone/meshservice/migration.go
Otherwise [here](https://github.com/kumahq/kuma/actions/runs/14195942787/job/39772966862#step:12:17733) we're getting:
```
Error: unknown flag: --port
Usage:
test-server [command]
Available Commands:
completion   Generate the autocompletion script for the specified shell
echo         Run Test Server with generic echo response
grpc         GRPC testing
health-check Run Test Server for Health Check test
help         Help about any command
Flags:
-h, --help               help for test-server
--log-level string   log level: one of off|info|debug (default "info")
Use "test-server [command] --help" for more information about a command.
``` 
In the logs. The test is not failing but to avoid confusion in the future it's better to add it.
Add echo command.
=> chore(e2e): add echo argument otherwise test server never started

mk/build.mk
I think I saw errors similar to https://github.com/kumahq/kuma/actions/runs/14250742362/job/39944674349#step:7:38
```
mkdir -p build/artifacts-linux-amd64/envoy && [ -f build/artifacts-linux-amd64/envoy/envoy ] || curl -s --fail --location https://github.com/kumahq/envoy-builds/releases/download/v1.30.11/envoy-linux-amd64-v1.30.11.tar.gz | tar -C build/artifacts-linux-amd64/envoy -xz
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
a couple of times. This way we'll retry 3 times before failing.
Add ` --retry 3 --retry-delay 60` to curl command.
=> ci(deps): add retry to downloading envoy and coredns

test/e2e_env/multizone/trafficroute/trafficroute.go
The test was disabled, but it's probably worth checking if it works. TrafficRoute is deprecated but still supported. It's worth checking if nothing breaks.
* Increased number of requests
* Change time restrictions
Fix https://github.com/kumahq/kuma/issues/13235
=> test(e2e): enable trafficroute and lb test

test/e2e/helm/kuma_helm_deploy_global_zone.go
Test passes locally we should enable it. I don't really see reason to have it skipped 
Fix [#13224](https://github.com/kumahq/kuma/issues/13224)
=> test(e2e): enable skipped helm test for Global admin api

.golangci.yml, pkg/test/ginkgo.go
Adds `golangci-lint` rule to block `sigs.k8s.io/controller-runtime/pkg/log` due to global logger assignment issues causing cyclic dependency races and long delays in binaries; use root controller-runtime import instead
Followup for https://github.com/kumahq/kuma/issues/13299
=> chore(lint): add rule to deny `sigs.k8s.io/controller-runtime/pkg/log` usage

api/mesh/v1alpha1/builtincertificateauthorityconfig/schema.yaml, docs/generated/openapi.yaml, tools/resource-gen/pkg/generator/main.go
so it's generated as `rsa_bits` in the terraform provider (and not as `rs_abits`)
add a key mapper
Fix https://github.com/Kong/terraform-provider-kong-mesh/pull/6
=> fix(openapi): rename RSAbits to rsaBits

mk/k3d.mk, mk/kind.mk
We need a way to debug why coreDNS readiness probe is failing https://github.com/kumahq/kuma/actions/runs/14436371337/job/40478469657#step:12:649
make the target a bit easier to read and add invocation to print logs
=> chore(mk): print pod logs on wait failure

.github/workflows/_e2e.yaml
Because of https://github.com/actions/runner-images/issues/11985
Add if around "runs-on".
=> ci(ipv6): disable kind ip v6 because of a kernel bug

.github/workflows/_build_publish.yaml
Got an answer on slack that https://github.com/Kong/public-shared-actions/releases/tag/%40security-actions%2Fscan-docker-image%404.1.5 fixed this issue so let's try an re-enable it.
Change to false.
Closes https://github.com/kumahq/kuma/issues/11544
=> chore(scan): reenable skip_cis_scan since the issue was fixed upstream

.github/workflows/pr-comments.yaml
We didnt run a linter.
Changed a generate and format to check command
=> ci(pr-comments): fix format comment

test/framework/envs/multizone/env.go
Make the kuma e2e framework universal test helpers like `setupKubeZone` as public for smoke test using.
Switch `setupKubeZone` private function into public.
Also I implemented a new `SetupRemoteUniZone` function which allows you use a remote docker backend to set up a universal zone.
=> test(framework): expose universal test helpers as public

test/framework/report/report.go
Otherwise we're going to be seeing:
```
The path for one of the files in artifact is not valid: /e2e-debug/MeshTLS_should_set_cypher_and_version/kuma-3/universal/exec/kuma-3_mesh-tls-test-server/envoytunnelgetstats_listener.(.*)_80.ssl.ciphers.ECDHE-RSA-AES256-GCM-SHA384-10/cmd-debug.txt. Contains the following character:  Asterisk *
Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n
The following characters are not allowed in files that are uploaded due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.
```
from: …
=> fix(util): fix bad sanitization of report entry names

test/framework/debug.go
```
./kumactl get -h
Available Commands:
zone-ingress                Show a single ZoneIngress resource
zone-ingresses              Show ZoneIngress
-------
./kumactl inspect -h
Available Commands:
zone-ingresses            Inspect Zone Ingresses
zoneingress               Inspect ZoneIngress
```
There is no consistency so we need to support 2 different kind of naming.
=> test(e2e): fix zoneingress debug command

test/framework/deployments/kic/deployment.go, test/framework/deployments/kic/kubernetes.go
Fixing a bug in the KIC installer of the test framework which prevent us from specifying watch namespaces.
The issue was introduced by this PR  https://github.com/kumahq/kuma/pull/12848 which tried to isolate the impact between multiple test suites on the same cluster.
The issue is causing some integration test failures in child-repo projects.
In our test framework, add a new option `watchNamespaces` onto the `k8sDeployment` struct of the KIC installer. In this way, we differenciate the semantic of `ingressNamespace` and `watchNamespaces` in that struct.
The mentioned PR above made the KIC installer include `watchNamespaces` parameter and made its value to equal `ingressNamespace`. This design prevented the installed KIC to watch Kong Gateway resources/plugins from any other namespaces …
=> test(framework): allow specify watch namespaces for the KIC installer

test/e2e_env/universal/meshratelimit/meshratelimit.go
Noticed a flake
While checking the logs, I noticed that the metrics were present in the dump, but during the test, they couldn't be found. This might be caused by a delay in configuration delivery, as we only check once if the metrics are available. I added an Eventually block to wait until the metrics appear, which should help avoid issues due to config propagation delays.
=> test(e2e): wait for stat to show up for MeshRateLimit

pkg/xds/secrets/secrets.go, pkg/xds/secrets/secrets_test.go
While investigating test failures, I noticed a flake that caused the secret not to be loaded.
While reviewing the code, I found that we were only comparing the number of meshes, but not verifying whether a specific mesh still exists. I added a change to detect cases where a mesh was removed and another was added in a short period of time. I also added a test and a metric to track mesh generation changes.
=> fix(secrets): correctly compare other meshes secrets when using crossMesh

.github/workflows/_e2e.yaml
This reverts commit 5f96a0a5453bc177d2249584bb9ba56d30f3be5e.
According to https://github.com/actions/runner-images/issues/11985#issuecomment-2823503856 this should be resolved now
=> Revert "ci(ipv6): disable kind ip v6 because of a kernel bug (#13392)"

.github/workflows/_e2e.yaml
This reverts commit 49c6f49f72ce45b21e8682a92c2877231b55df2b.
It seems the underlying kernel issue was not fixed as we thought
=> Reapply "ci(ipv6): disable kind ip v6 because of a kernel bug (#13392…)" (#13445)

UPGRADE.md, app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/roleBindingInNamespaces.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/roleBindingInNamespaces.values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cni-rbac.yaml, deployments/charts/kuma/templates/cp-rbac.yaml, deployments/charts/kuma/values.yaml, docs/generated/raw/helm-values.yaml
`enabledNamespace` is not a good name, we decided to rename.
rename to `namespaceAllowList`
Fix #13459
=> fix(helm): rename enabledNamespace to namespaceAllowList

docs/madr/decisions/070-resource-identifier.md
Since we have some resource name limitations, we should sync them to the resource identifier MADR
=> docs(MADR): update resource identifier format limitations

test/framework/k8s.go
https://github.com/kumahq/kuma/pull/13477#pullrequestreview-2798952463
we should probably upgrade this
=> test(e2e): upgrade gateway-api test from 1.2.1 to 1.3.0

api/mesh/v1alpha1/dataplane/schema.yaml, api/mesh/v1alpha1/dataplaneoverview/schema.yaml, api/mesh/v1alpha1/meshgateway/schema.yaml, api/openapi/specs/api.yaml, docs/generated/openapi.yaml, tools/resource-gen/pkg/generator/main.go
After https://github.com/kumahq/kuma/pull/13479/files we noticed that overview endpoints are missing and some of the resources are using snake_case
add `/dataplanes/_overview` and `/dataplanes/{name}/_overview` add a name mapper
=> feat(oapi): add missing dataplane overview andpoints and fix casing

pkg/xds/server/callbacks/dataplane_lifecycle.go
Fixing the grace termination process of DPPs on Universal.
The issue does not apply  to Kubernetes mode, becasue we have the Pod delete event and DP objects are cleaned up correctly.
* use the app context instead of the gRPC stream context to delete DP objects
fixes https://github.com/kumahq/kuma/issues/13403
=> fix(xds): use correct context to cleanup dataplane object when the proxy is disconnecting

test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/setup.go, test/framework/universal_app.go, test/framework/universal_cluster.go
Adding the ability to customize docker volumes and arguments when installing Kuma on Universal. With this ability, we can attach certificates and other resources in E2E tests.
* Introducing helper method `WithCPDockerVolumes` to test framework
* Introducing helper method `WithCPDockerRunOptions` to test framework (to allow specify docker arguments like `--ip`)
An enahancement to https://github.com/kumahq/kuma/pull/13301
=> test(framework): add the ability to customize docker volumes and arguments

.github/workflows/_e2e.yaml
It was resolved for both GH actions and in private runners:
CC @Water-Melon 
```
The self-hosted runner has been bumped to version 20250504.1.
```
Revert https://github.com/kumahq/kuma/pull/13392/files
=> ci(ipv6): revert skip ipv6

api/mesh/v1alpha1/dataplaneoverview/schema.yaml, docs/generated/openapi.yaml, tools/resource-gen/pkg/generator/main.go
https://github.com/kumahq/kuma/pull/13542 did not help because I think I confused it with a fix for another cryptic error. The actual fix should be https://github.com/kumahq/kuma/pull/12329/files#diff-d719909e3a90ac11d2e421de4759332f4795fa80fa0a2d0635a599cdae2dadd6R449 the same as in this PR.
Add `structpb.Struct` to ignored types.
=> chore(oapi): ignore structpb.Struct from oas generation

pkg/api-server/server.go
- prevents panic when setting env `KUMA_API_SERVER_BASE_PATH` without `/`
- prefix check on `BasePath` and adding `/` if missing
Fix #12335
=> fix(api-server): ensure base path start with slash to prevent ServeMux panic

test/e2e_env/universal/envoyconfig/builtingateway.go, test/e2e_env/universal/envoyconfig/sidecars.go, test/e2e_env/universal/envoyconfig/utils.go
We want to write envoy config e2e tests in other projects like Kong Mesh. These changes make it easy to reuse
=> feat(e2e): rewrite envoy config e2e test to make it reusable in other projects

test/e2e_env/multizone/producer/producer.go
It constantly fails, i.e. https://github.com/kumahq/kuma/actions/runs/15022018662/job/42215564633
=> chore(e2e): disable MeshRetry on MeshHTTPRoute test

test/e2e_env/multizone/producer/producer.go
Apparently 100±5 wasn't enough:
```
• [FAILED] [74.044 seconds]
Producer Policy Flow [It] should sync producer MeshRetry that targets producer route to other clusters
github.com/kumahq/kuma/test/e2e_env/multizone/producer/producer.go:240
Captured StdOut/StdErr Output
[FAILED] Timed out after 30.000s.
The function passed to Eventually failed at github.com/kumahq/kuma/test/e2e_env/multizone/producer/producer.go:330 with:
Expected
<int>: 90
to be within 5 of ~
<int>: 100
Error: It 05/14/25 14:14:47.766
```
Changed to 100±10 and re-enable the test.
=> chore(e2e): re-enable MeshRetry on MeshHTTPRoute test with more permissive assertion

docs/generated/raw/rbac.yaml, mk/docs.mk
We’re updating the docs to include Kubernetes RBAC resources, so generating these files automatically will help with future maintenance.
Added make target to generate `docs/generated/raw/rbac.yaml` with control plane RBAC; includes ClusterRoles, RoleBindings, and related resources from Helm chart
Related to: https://github.com/kumahq/kuma/issues/13285
=> chore(docs/generated): export rendered RBAC manifests to docs for reuse

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/dnsConfigOption.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/envVarsDownwardApi.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix12847.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix13029.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/roleBindingInNamespaces.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml, deployments/charts/kuma/templates/cp-rbac.yaml, docs/generated/raw/rbac.yaml
Regular `kuma-control-plane` role also contains write permissions so `kuma-control-plane-write` is not appropriate name.
Update all golden test fixtures and Helm templates to rename `kuma-control-plane-writer` to `kuma-control-plane-workloads`. This aligns the name with its actual use and intent: granting permissions for the control plane to manage workloads across namespaces.
Solves issue mentioned during test Friday and:
- https://github.com/kumahq/kuma-website/pull/2305#discussion_r2095328543
- https://github.com/kumahq/kuma-website/pull/2305#discussion_r2095570218
=> refactor(kubernetes/rbac): rename control-plane-writer to control-plane-workloads

.github/workflows/_build_publish.yaml
`make build` in the parent project sometimes takes more time
Increase `timeout-minutes` in `_build_publish.yaml` to 70 to account for longer build times when running `make build` in the parent project.
=> ci(github): increase build timeout from 50 to 70 minutes

test/e2e_env/universal/envoyconfig/utils.go
Fix flaky e2e test. Old way of replacing didn't take into account json structure. The string we were trying to replace could be in the middle of a json object on at the end which adds or removes a trailing comma from it
=> fix(e2e): fix dnslookup regex from envoy config test to work properly with json structure

pkg/plugins/policies/core/matchers/dataplane.go, pkg/test/resources/builders/dataplane_builder.go
This allows us to match dataplanes with policies in projects based on Kuma
=> feat(merging): make method DppSelectedByPolicy public

pkg/core/xds/resource.go, pkg/plugins/policies/core/rules/outbound/context.go, pkg/plugins/policies/core/rules/outbound/context_test.go, pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go, test/e2e_env/universal/envoyconfig/sidecars.go, test/e2e_env/universal/envoyconfig/testdata/sidecars/meshretry/outbound-mix.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/sidecars/meshretry/outbound-mix.input.yaml, test/e2e_env/universal/envoyconfig/testdata/sidecars/meshretry/outbound-mix.test-server.golden.json, test/e2e_env/universal/envoyconfig/testdata/sidecars/meshtimeout/outbound-mix.demo-client.golden.json, test/e2e_env/universal/envoyconfig/testdata/sidecars/meshtimeout/outbound-mix.input.yaml, test/e2e_env/universal/envoyconfig/testdata/sidecars/meshtimeout/outbound-mix.test-server.golden.json
Method `Compute` is falling back to `Mesh` rules if `MeshHTTPRoute` doesn't exist. See the repro steps in https://github.com/kumahq/kuma/issues/13571.
When computing `MeshHTTPRoute` conf in `Compute` we can't fall back to its `MeshService`, because there might be an ambiguity – `MeshHTTPRoute` could be applied to several `MeshServices`. But when configuring the route, we always know the `MeshService` of the outbound listener. Computing `MeshHTTPRoute` conf is possible only in the context of `MeshService`.
Instead of passing both `MeshService` and `MeshHTTPRoute` to `Compute` I created a `ResourceContext`:
```go
// ResourceContext represents a hierarchical resource structure and
// is always ready to return the appropriate conf by using Conf method.
// The RootContext is always the mesh. …
```
=> fix(rules): incorrect behaviour of MeshTimeout/MeshRetry policies when referencing routes

.renovate/go-control-plane.json
Updates `extractVersionTemplate` to only match versions with build suffixes starting with `kong-`, avoiding accidental upgrades to test builds like `v0.13.4-ld-delta-test-1` (https://github.com/kumahq/kuma/pull/13431).
=> chore(renovate): restrict go-control-plane replace to kong-specific builds

pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/basic.listeners.golden.yaml, pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/default.listeners.golden.yaml, pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_otel.listeners.golden.yaml, pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_prometheus.listeners.golden.yaml, pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/openTelemetry.listeners.golden.yaml, pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.listeners.golden.yaml, pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/provided_tls.listeners.golden.yaml, pkg/xds/dynconf/listener.go, pkg/xds/envoy/listeners/filter_chain_configurers.go, pkg/xds/envoy/listeners/v3/direct_response_configurer.go, pkg/xds/envoy/listeners/v3/direct_response_configurer_test.go, pkg/xds/generator/testdata/dns/4-envoy-config.golden.yaml
Fix a warning shown on Envoy:
```
[2025-05-19 09:41:07.450][20][warning][misc] [source/extensions/filters/network/http_connection_manager/config.cc:88] internal_address_config is not configured. The existing default behaviour will trust RFC1918 IP addresses, but this will be changed in next release. Please explictily config internal address config as the migration step or config the envoy.reloadable_features.explicit_internal_address_config to true to untrust all ips by default
```
Add `internal_address_config` onto the HCM generated by the `DirectResponse` configurer based on CP config.
Listener name: `_kuma_dynamicconfig `
A followup of https://github.com/kumahq/kuma/issues/12190
=> fix(xds): add internal address config to  direct response configurer

test/e2e_env/multizone/producer/producer.go
Function `CollectResponsesAndFailures` sends requests concurrently and it can cause retry overflow. If we want to accurately check MeshRetry function we need to increase `maxRetries` using MeshCircuitBreaker policy at the beginning of the test. 
Added MeshCircuitBreaker with `maxRetries: 20`
=> fix(e2e): test failure due to insufficient MaxRetries

.github/workflows/backport.yaml
Otherwise I have to override this in parent repo. We have a variable, let's use that variable and only overwrite in one place.
=> ci(backport): use env.USE_APP_TOKEN variable everywhere

pkg/plugins/policies/meshtrafficpermission/graph/util/rule_builder.go
Because autoreachable services are based on tags, and we create fake dp without any meta, we cannot match policies with `targetRef.kind: Dataplane` ending in nil pointer, this is just temporary fix. We should update it after we design new workload identity 
Fix https://github.com/kumahq/kuma/issues/13584
=> fix(autoreachableservices): fix nil pointer by skipping policies with targetRef.kind Dataplane

test/e2e_env/multizone/producer/producer.go, test/framework/client/collect.go
https://github.com/kumahq/kuma/actions/runs/15219190859/job/42812693611#step:12:16882
```
• [FAILED] [71.816 seconds]
Producer Policy Flow [It] should sync producer MeshRetry that targets producer route to other clusters
github.com/kumahq/kuma/test/e2e_env/multizone/producer/producer.go:240
Captured StdOut/StdErr Output
[FAILED] Timed out after 30.000s.
The function passed to Eventually failed at github.com/kumahq/kuma/test/e2e_env/multizone/producer/producer.go:349 with:
Expected
<int>: 89
to be within 10 of ~
<int>: 100
Error: It 05/23/25 21:53:28.69
------------------------------
```
* replace MeshFaultInjection and MeshRetry code from 500 to 429
* change checker to see full responses map when it fails
=> test(e2e): fix `should sync producer MeshRetry that targets producer route to other clusters`

UPGRADE.md
Section mentioned `--skipRBAC` flag but this flag doesn't introduce any behaviour that'd require extra steps from user during the upgrade.
Removing the section from UPGRADE.md
Fix https://github.com/kumahq/kuma-website/issues/2311
=> docs(UPGRADE.md): remove mentioning of `--skipRBAC` file from UPGRADE.md

test/e2e_env/multizone/producer/producer.go
Fixes `should sync producer MeshRetry that targets producer route to other clusters` (for real this time).
Instead of MeshFaultInjection use `x-succeed-after-n` header
=> fix(e2e): use `x-succeed-after-n` header to test MeshRetry

pkg/core/tokens/meshed_signing_key_manager.go
closes https://github.com/Kong/kong-mesh/issues/7802
There can be a race condition where we wrote a mesh to a db and then tried to read it and it was read from a replica that did not have that mesh.
Add get consistent.
=> fix(defaults): ensure that we use consistent store to retrive signing key

pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/name-length-63.input.yaml, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go, pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator_test.go
Before the PR, we used the `("%s.%s", name, namespace)` combination string to verify its length. We should verify only name length
Fix #13648
=> fix(meshexternalservice): allow 63 length k8s MeshExternalService resource creation

pkg/core/resources/model/labels/labels.go
If this gets out of sync people using TF provider will experience configuration drift (unwanted changes)
=> chore(note): add note about syncing computed labels with speakeasy

pkg/dns/vips/global_view.go, pkg/dns/vips/global_view_test.go
When a user starts the control plane with the default IPAM configuration (CIDR 240.0.0.0/4), the control plane creates a ConfigMap containing service to VIP allocations. If the user later updates the CIDR range and redeploys the control plane, the control plane may fail with the error:
```
Address outside the CIDR
```
This happens because the control plane attempts to reallocate existing addresses that no longer fall within the updated CIDR range.
Instead of failing when encountering an address outside the configured CIDR (e.g., for MeshService resources), the allocator will now skip reserving such addresses and allocate new ones instead. This ensures continued operation and proper IP assignment without failinf due to invalid IP reuse.
=> fix(vip): don't fail once previous address is out of range of new range

tools/releases/helm.sh
Otherwise the job can't find the file: https://github.com/kumahq/kuma/actions/runs/15531336124/job/43730304100#step:10:19
```
PATH=/home/runner/work/kuma/kuma/.ci_tools/bin:$PATH ./tools/releases/helm.sh  --release
Cloning into 'charts'...
find: ‘.cr-release-packages/*.tgz’: No such file or directory
make: *** [mk/helm.mk:20: helm/release] Error 1
Error: Process completed with exit code 2.
```
This worked on my fork https://github.com/slonka/charts/releases/tag/kuma-2.11.0
Find does not take a glob like that, fixed the syntax.
xrel https://github.com/Kong/team-mesh/issues/400
=> ci(helm): fix release/helm.sh to properly find helm package

.github/workflows/lifecycle.yml
This version fixes issues with temporary skiping sha validation for slsa-framework/slsa-github-generator actions
=> chore(deps): bump lifecycle to 2e670e4083642dfa8f047fab84c6436d28ef81a4

mk/generate.mk
Without this we are failing in Kong Mesh on: 
```
for endpoint in api/openapi/specs/common/ api/openapi/specs/common/error_schema api/openapi/specs/global_insight api/openapi/specs/tenants; do \
DEST=${endpoint#"api/openapi/specs"}; \
/Users/marcin.skalski@konghq.com/.kuma-dev/kong-mesh-master/bin/oapi-codegen -config api/openapi/openapi.cfg.yaml -o api/openapi/types/$(dirname ${DEST}})/zz_generated.$(basename ${DEST}).go ${endpoint}.yaml  || { echo "Failed to generate $endpoint"; exit 1; }; \
done
error loading swagger spec in api/openapi/specs/common/.yaml
: failed to load OpenAPI specification: open api/openapi/specs/common/.yaml: no such file or directory
Failed to generate api/openapi/specs/common/
make: *** [generate/oas] Error 1
```
=> fix(oapi): fix generation of oapi schema by skipping not yaml files

docs/madr/decisions/074-mlbs-hash-policies.md
Required for https://github.com/kumahq/kuma/issues/13436
=> docs(MADR): move `hashPolicies` field out of the LB specific struct in MLBS

skaffold.yaml
We don't need to install crds on upgrade, this greatly speeds up Skaffold reload on k8s cluster
=> feat(skaffold): speedup redeploying kuma with Skaffold

pkg/util/xds/v3/fallback_node_hash.go
Without this mads call is throwing panic
added nil check
Fix #13730
=> fix(mads): adding nil check in FallBackNodeHash on mads call

.github/workflows/update-docs.yaml
Before this PR, we could trigger docs updating by pushing a tag. Sometimes, this CI action might fail and make the release manager feel confused when releasing. So, we should separate this behavior and once all of the tag pushed actions succeed, then we can trigger this docs updating manually.
=> ci(gha): remove tag pushing triggering behavior for docs updating

docs/madr/decisions/077-migrating-to-consistent-and-well-defined-naming-for-non-system-envoy-resources-and-stats.md
After merging the PR I found few mistakes and inconsistencies
- Clarifies wording around context vs proxy context
- Removes incorrect length constraint on `sectionName`
- Fixes regex
- Updates example resource and stat names to match final `self_inbound_<sectionName>` format
- Fixes outdated `MeshGlobalRateLimit` explanation and moves it under MADR-076
- Improves formatting and link references throughout the document
=> docs(MADR): fix wording, formatting, and examples in MADR-077 after merge

docs/madr/decisions/078-special-mtp-algo.md
While working on https://github.com/kumahq/kuma/issues/12374 I realized MeshTrafficPermission is just too different to try to invent a unified matching algo for all inbound policies.
This MADR aims to make MeshTrafficPermission a special case and justify custom matching algorithm.
=> docs(MADR): MeshTrafficPermission Is a Special Case of Inbound Policies and Requires a Custom Matching Algorithm

go.mod
upgrade golang from `1.24.4` to `1.24.5`
=> chore(deps): bump golang from 1.24.4 to 1.24.5

test/e2e_env/universal/meshtls/policy.go
@lukidzi noticed a flake:  https://github.com/kumahq/kuma/actions/runs/16269540267/job/45939071797
```
• [FAILED] [40.527 seconds]
MeshTLS [It] should set cypher and version
github.com/kumahq/kuma/test/e2e_env/universal/meshtls/policy.go:332
Captured StdOut/StdErr Output
[FAILED] Timed out after 30.001s.
The function passed to Eventually failed at github.com/kumahq/kuma/test/e2e_env/universal/meshtls/policy.go:411 with:
no stat found: &{[]}
Error: It 07/14/25 15:42:24.33
```
Which we think was caused by the policy not being propagated quickly enough so that the requests done in the previous lines did not trigger the stats change. We moved everything after policy application to be in eventually which should re-trigger stats if there is a failure in eventually.
=> test(meshtls): improve meshtls test by running requets between asserts

mk/build.mk
The current CoreDNS version (v1.12.0) includes vulnerabilities that are not exploitable in the context of Kuma but are still flagged by security scanners. Updating to v1.12.2 removes these false positives.
The `COREDNS_VERSION` in `mk/build.mk` was updated from v1.12.0 to v1.12.2. No additional changes were required. CoreDNS usage in Kuma remains minimal and does not involve the affected functionality, but this update helps reduce noise in reports.
Fixes included in CoreDNS v1.12.1 and v1.12.2:
* GHSA-v778-237x-gjrc
* GHSA-hcg3-q754-cr77
These were previously evaluated and confirmed as not exploitable.
=> chore(deps): bump CoreDNS to v1.12.2

app/kuma-dp/pkg/dataplane/metrics/profiles.go, pkg/core/system_names/system_names.go, pkg/hds/tracker/callbacks.go, pkg/hds/tracker/healthcheck_generator.go, pkg/hds/tracker/healthcheck_generator_test.go, pkg/hds/tracker/testdata/hds.4.golden.yaml, pkg/xds/envoy/names/system_names.go, pkg/xds/generator/admin_proxy_generator.go, pkg/xds/generator/admin_proxy_generator_test.go, pkg/xds/generator/proxy_template_profile_source_test.go, pkg/xds/generator/system_names/api.go, pkg/xds/generator/testdata/admin/08.dataplane.input.yaml, pkg/xds/generator/testdata/admin/08.envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/5-envoy-config.golden.yaml, test/e2e_env/multizone/inspect/inspect.go
Best described in https://github.com/kumahq/kuma/issues/13903 and related MADRs
Add a switch on top of a FF to rename envoy admin resources.
xrel https://github.com/kumahq/kuma/issues/13903
closes https://github.com/kumahq/kuma/issues/13966
=> feat(kuma-cp): rename envoy admin system resource to follow unified naming format

.github/workflows/build-test-distribute.yaml, api/mesh/v1alpha1/dataplane.proto, mk/check.mk
Move clang-format from `make check` to separate action as `golangci-lint`. This will allow us to speed up `mise` tools installation as we won't rely on clang-format any more. This will fail like this if not properly formatted:
https://github.com/kumahq/kuma/actions/runs/16418589385/job/46390718639?pr=14012
```
Ubuntu clang-format version 13.0.1-2ubuntu2.2
./api/mesh/v1alpha1/dataplane.proto:116:[42](https://github.com/kumahq/kuma/actions/runs/16418589385/job/46390718639?pr=14012#step:7:44): error: code should be clang-formatted [-Wclang-format-violations]
google.protobuf.Duration interval=1;
^
./api/mesh/v1alpha1/dataplane.proto:116:[43](https://github.com/kumahq/kuma/actions/runs/16418589385/job/46390718639?pr=14012#step:7:45): error: code should be clang-formatted …
```
=> feat(tools): move clang-format from `make check` to action

pkg/plugins/policies/meshratelimit/api/v1alpha1/deprecated.go
If the status is lower than 400 envoy fallback to 429. We shouldn't allow setting incorrect status
Added log information that setting status lower than 400 is not supported
part of: #https://github.com/kumahq/kuma/issues/13319
=> fix(meshratelimit): add warning log about status code

.github/workflows/build-test-distribute.yaml
We are still seeing golangci-lint OOMing:
- https://github.com/Kong/kong-mesh/actions/runs/16498801542/job/46651336957
- https://github.com/Kong/kong-mesh/actions/runs/16516391116/job/46708022916
- https://github.com/Kong/kong-mesh/actions/runs/16495938870/job/46641539526
- https://github.com/Kong/kong-mesh/actions/runs/16495938870/job/46641539526
- https://github.com/Kong/kong-mesh/actions/runs/16477097845/job/46581551551
- https://github.com/Kong/kong-mesh/actions/runs/16436573191/job/46447630542
- ...
In the parent project. 
PromCI repo uses ratio of 0.8 so setting to that https://github.com/prometheus/promci/blob/37fc2faf8f611b1cffd38d86ba9f813b88c82750/actions/setup_environment/action.yml#L18
and also setting GOGC to 80 to make the GC run more often (saw this suggestion on another …
=> ci(lint): set smaller gomemlimit to combat OOMs

.github/workflows/_e2e.yaml, mise.toml
After updating `mise.toml` to use full tool names supported by Renovate (see #14051), the name of `protoc-gen-go-grpc` changed to `aqua:grpc/grpc-go/protoc-gen-go-grpc`.
This PR updates the `_e2e.yaml` workflow to match the new name so the tool doesn't get installed during GitHub Actions runs.
To prevent similar issues in the future, the excluded tools in `mise.toml` were moved to the bottom and grouped under a dedicated comment that clearly lists which workflows use the `MISE_DISABLE_TOOLS` variable and should be updated if tool names change.
* Updated `_e2e.yaml` to use the new full tool name
* Moved excluded tools to the bottom of `mise.toml`
* Added a comment block listing all affected GitHub Actions workflows to keep `MISE_DISABLE_TOOLS` in sync
* Related PR: #14051
=> ci(gha): update disabled tool name in mise action to match full registry name

test/e2e_env/multizone/localityawarelb/locality_multizone_hybrid.go
Because of https://github.com/kumahq/kuma/issues/14070
Disable
=> test(flake): disable `requests should be routed directly through local sidecar when zone egress disabled` flaky test

.renovate/makefile.json, .renovate/mise.json, mk/dev.mk, renovate.json
The Renovate setup for `mise` and Makefile-based tools needed cleanup and improvements:
* `protoc` and `clang-format` are legacy tools in Kuma and not worth updating, so Renovate should not track them
* Some commit messages for tool updates were unnecessarily verbose due to long tool names; we want to simplify them
* We previously lacked support for updating tool versions defined in Makefiles (like `ENVOY_VERSION`)
* We also want to ensure that security-related vulnerabilities are labeled and assigned properly
* Replaced `overrideDepName` with `commitMessageTopic` template for most aqua/go tools
* Merged `clang-format` and `protoc` disable rules into one
* Added `.renovate/makefile.json` with regex manager to detect versioned vars in `Makefile` or `.mk` files
* Annotated `ENVOY_VERSION` …
=> ci(renovate): add Makefile preset and simplify mise config

mise.toml
Hadolint 2.12.0 crashes on macOS with a segmentation fault when run, making it unusable for local development. The issue is tracked here: https://github.com/hadolint/hadolint/issues/919
Bumped hadolint to 2.12.1-beta in `mise.toml`. This version includes a fix for the macOS crash and is the latest officially released version, even though it was published almost 3 years ago.
No other changes were needed.
Issue: https://github.com/hadolint/hadolint/issues/919
=> chore(deps/dev): bump hadolint to 2.12.1-beta to fix macOS crash

mk/test-container-structure.mk
Broken master
Added missing `--platform` flag to container structure test command
Fix #XX
=> ci(container-structure-tests): add missing platform flag

pkg/xds/generator/admin_proxy_generator.go, pkg/xds/generator/system_names/api.go, pkg/xds/generator/testdata/admin/07.envoy-config.golden.yaml, pkg/xds/generator/testdata/admin/08.envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/5-envoy-config.golden.yaml
Explained in https://github.com/kumahq/kuma/issues/13972
Use exiting system naming API.
Fix https://github.com/kumahq/kuma/issues/13972
=> feat(kuma-cp): rename readiness resources

pkg/api-server/resource_endpoints.go, pkg/core/managers/apis/dataplane/dataplane_manager.go, pkg/core/resources/model/labels/labels.go, pkg/core/resources/model/resource.go, pkg/core/resources/model/resource_test.go, pkg/plugins/resources/k8s/store.go, pkg/plugins/resources/k8s/store_test.go, pkg/plugins/runtime/k8s/controllers/gateway_converter.go, pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_converter.go, pkg/plugins/runtime/k8s/controllers/testdata/30.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/30.pod.yaml, pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/webhooks/defaulter.go
Support of MeshIdentity requires access to ServiceAccount of pod.
* propagate ServiceAccount in the annotation - service account might be longer than 63 characters so we cannot store it in the label
* refactor `ComputeLabels` to accept function instead of another parameter
* ComputeLabels for builtin gateway
Part of #13876
=> feat(k8s): propagate service account in the annotation

pkg/plugins/bootstrap/k8s/xds/hooks/api_server_bypass.go, pkg/plugins/bootstrap/k8s/xds/hooks/api_server_bypass_test.go, pkg/plugins/bootstrap/k8s/xds/hooks/testdata/api-server-bypass-unified-naming.yaml
In https://github.com/kumahq/kuma/issues/13975
Nothing out of the ordinary.
Fix https://github.com/kumahq/kuma/issues/13975
=> feat(kuma-cp): rename kube server bypass system resource to follow unified naming format

.github/workflows/_build_publish.yaml, .github/workflows/auto-merge.yaml, .github/workflows/ci-stability.yaml, .github/workflows/merge-release-to-master.yaml, .github/workflows/pr-comments.yaml, .github/workflows/release.yaml, .github/workflows/update-docs.yaml, .github/workflows/update-insecure-dependencies.yaml
Reverts kumahq/kuma#14187
`node24` is not yet supported on our custom runners
=> Revert "chore(deps): bump actions/create-github-app-token from v2.0.6 to v2.1.0"

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/values.yaml, docs/generated/raw/helm-values.yaml
Rancher tags their `kubectl` images with a `v` prefix (e.g., `v1.33.3`). Our Helm chart was using the tag without the prefix, which is inconsistent with Rancher’s convention and with the release branches where we already include the `v` prefix. While this is a cosmetic change only (the image digest is provided and takes precedence over the tag), keeping tags consistent improves clarity and avoids confusion.
Updated all references to the `rancher/kubectl` image tag from `1.33.3` to `v1.33.3` across Helm chart values, generated documentation, and related test data. The image digest remains unchanged.
=> chore(helm): add v prefix to the kubectl image tag for consistency

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/values.yaml, docs/generated/raw/helm-values.yaml
Bitnami will discontinue and remove the `bitnami/kubectl` image from their registry in 2 weeks. While kubectl is now available under the `bitnamisecure/kubectl` registry, it only contains new images, lacks tags corresponding to kubectl versions, and the publisher is not marked as verified. This makes it unsuitable for backporting changes to existing release branches.
Updated the Helm chart and generated documentation to use the `rancher/kubectl` image instead of `bitnami/kubectl`. Increased the patch version from `1.27.5` to `1.27.16` and set the corresponding image digest. Rancher provides versioned and tagged kubectl images, making it easier to align with our current and past releases.
Reference: https://github.com/bitnami/charts/issues/35164
Closes: …
=> chore(helm): switch kubectl image to rancher and bump patch

pkg/plugins/policies/core/xds/meshroute/clusters.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice-and-mzms-labels-unified-naming.clusters.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice-unified-naming.clusters.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls-and-custom-settings-unified-naming.clusters.golden.yaml, pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go, pkg/plugins/runtime/gateway/cluster_generator.go, pkg/plugins/runtime/gateway/filter_chain_generator.go, pkg/xds/envoy/clusters/configurers.go, pkg/xds/envoy/listeners/filter_chain_configurers.go, pkg/xds/envoy/listeners/v3/server_mtls_configurer.go, pkg/xds/envoy/listeners/v3/server_mtls_configurer_test.go, pkg/xds/envoy/tls/v3/tls.go, pkg/xds/envoy/tls/v3/tls_test.go, pkg/xds/generator/egress/external_services_generator.go, pkg/xds/generator/inbound_proxy_generator.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/prometheus_endpoint_generator.go, pkg/xds/generator/testdata/profile-source/5-envoy-config.golden.yaml
Some code paths missed updating secret resource names to use the unified naming feature introduced in #14166. This caused inconsistencies in how secrets were referenced during mTLS and filter chain configuration.
Added the `unifiedResourceNaming` flag to all relevant function calls and configurers that manage secrets, including server-side and client-side mTLS configurers. Updated inbound, outbound, gateway, and external service proxy generators to pass the flag consistently. Adjusted tests to account for the new parameter.
Related to:
- #14166
- #13973
=> feat(kuma-cp): fix missing unified naming for secret resources

test/transparentproxy/transparentproxy_test.go
Transparent proxy test were failing
Instead of `%q` we need to stick `"%s"` since it's correctly quoted
=> test(transparentproxy): changed back to %s since %q doesn't work

mk/docs.mk
Because we had to do it manually https://github.com/kumahq/kuma/pull/14226 and it costed us hours of dev time because of that.
Use makefile renovate updater.
=> chore(deps): automatically bump openapi-tool when a new release is out

pkg/core/naming/contextual.go, pkg/core/naming/naming.go, pkg/core/naming/naming_test.go, pkg/plugins/policies/core/xds/cluster.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go, pkg/xds/envoy/clusters/cluster_builder.go, pkg/xds/envoy/listeners/filter_chain_builder.go, pkg/xds/envoy/listeners/filter_chain_configurers.go, pkg/xds/envoy/listeners/v3/http_outbound_route_configurer.go, pkg/xds/envoy/listeners/v3/http_outbound_route_configurer_test.go, pkg/xds/envoy/listeners/v3/http_route_configurer.go, pkg/xds/envoy/listeners/v3/util.go, pkg/xds/envoy/routes/v3/retry_configurer_test.go, pkg/xds/envoy/types.go, pkg/xds/envoy/virtualhosts/routes_configurer.go, pkg/xds/generator/egress/external_services_generator.go, pkg/xds/generator/egress/internal_services_generator.go, pkg/xds/generator/outbound_proxy_generator.go
This change improves the outbound route configuration API and cluster handling in XDS to make it safer, clearer, and more flexible. The previous `HttpOutboundRoute` signature was prone to accidental name mismatches and lacked explicit parameters for route and virtual host names. Adding SNI support to the `Cluster` interface improves TLS interoperability, and new helpers like `naming.GetNameOrFallback` reduce boilerplate for safe name resolution.
- Introduced `naming.GetNameOrFallback` and `GetNameOrFallbackFunc` with tests to simplify name resolution when primary values are missing
- Relaxed generic constraint on contextual `sectionName` to `constraints.Unsigned` for broader applicability
- Added `SNI` to `Cluster` interface and cluster builder (`WithSNI`) for explicit TLS server name …
=> refactor(xds): rework outbound route API, add SNI, helpers

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/values.yaml, docs/generated/raw/helm-values.yaml
Switch to the official Kubernetes `kubectl` image from `registry.k8s.io` to align with upstream, reduce third-party risk, and keep using a pinned digest. v1.28 is the first version available in the official registry. We only use `kubectl` to install CRDs, so this bump is safe.
- Change registry: `docker.io` → `registry.k8s.io`
- Change repository: `rancher/kubectl` → `kubectl`
- Bump tag: `v1.27.16@sha256:51758d...` → `v1.28.15@sha256:498806...`
- Update `values.yaml`, generated docs, test data, and README values table
- No changes to Helm hooks or logic; charts will pull the new image and tag
- Context: https://github.com/bitnami/charts/issues/35164
=> feat(helm): switch kubectl image to `registry.k8s.io`

pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.clusters.golden.yaml, pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.listeners.golden.yaml, pkg/plugins/policies/meshtrace/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtrace/plugin/v1alpha1/testdata/inbound-outbound-zipkin-real-meshservice-unified-naming.cluster.golden.yaml, pkg/plugins/policies/meshtrace/plugin/v1alpha1/testdata/inbound-outbound-zipkin-real-meshservice-unified-naming.listener.golden.yaml, pkg/plugins/policies/meshtrace/plugin/v1alpha1/testdata/simple-gateway-with-unified-naming.listeners.golden.yaml, pkg/plugins/policies/meshtrace/plugin/xds/configurer.go
Having the
```
if len(policies.SingleItemRules.Rules[0].Origin) == 1 {
```
check does not make sense. If we only have one origin means we most likely have 1 policy. As mentioned before when we have anything else that can be merged besides `backends` we can't rely on the last origin to actually be the backend (like here - last origin is `metrics-prom-1` but the backends are defined in other policy)
<details>
<summary>policies</summary>
```
apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
name: metrics-prom-1
namespace: kuma-demo
labels:
kuma.io/mesh: default
spec:
default:
sidecar:
includeUnused: true
profiles:
appendProfiles:
- name: Basic
---
apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
name: metrics-prom-2
namespace: kuma-demo
labels:
kuma.io/mesh: default
spec: …
```
=> feat(kuma-cp): rename mesh metric and mesh trace from kri system to system

pkg/plugins/policies/core/xds/meshroute/clusters.go, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go, pkg/plugins/runtime/gateway/cluster_generator.go, pkg/xds/generator/egress/external_services_generator.go, pkg/xds/generator/egress/generator.go, pkg/xds/generator/egress/internal_services_generator.go, pkg/xds/generator/inbound_proxy_generator.go, pkg/xds/generator/inbound_proxy_generator_test.go, pkg/xds/generator/ingress_generator.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/prometheus_endpoint_generator.go, pkg/xds/generator/proxy_template_profile_source_test.go, pkg/xds/generator/transparent_proxy_generator.go, pkg/xds/generator/transparent_proxy_generator_test.go, pkg/xds/generator/zoneproxy/generator.go
Unified naming can't depend only on proxy features. It also needs to check mesh-level configuration. Unified naming currently can only work properly when the mesh is configured with `meshServices: Exclusive`. In other cases our GUI and inspect API are not ready to support unified names, so we must fall back to legacy naming.
- Add a `unifiedNaming` flag resolved from both proxy metadata and mesh configuration
- Check if the mesh is configured with `meshServices: Exclusive`; only then enable unified naming
- Replace direct calls to `proxy.Metadata.HasFeature(FeatureUnifiedResourceNaming)` with `unified_naming.Enabled(metadata, mesh)`
- Pass the `unifiedNaming` flag into listeners, clusters, and routes
- Use `naming.GetNameOrFallbackFunc(unifiedNaming)` in generators
- Update tests to allow …
=> chore(xds): mesh-aware (meshServices mode) unified naming switch in user resources

pkg/api-server/dataplane_layout_endpoint.go, pkg/api-server/resource_endpoints.go
This api does not make sense if MeshService mode is set to other than exclusive as we will be returning partial results
=> feat(inspect-api): make new api endpoint only available when MeshService mode is set to exclusive

test/e2e_env/kubernetes/kubernetes_suite_test.go, test/e2e_env/kubernetes/meshtrafficpermission/meshtrafficpermission.go
we need to add e2e test for new MTP with SpiffeId, after support for it was added with MeshIdentity
Fix https://github.com/kumahq/kuma/issues/14029
=> feat(MeshTrafficPermission): add e2e test for MTP with spiffe

pkg/plugins/runtime/k8s/controllers/pod_controller.go
When we use MS mode exclusive, we need to deduplicate inbounds on Dataplane. This works well if you start with this mode. This PR covers the situation when you start with MS mode other than exclusive and migrate to exclusive, or if you go back to old services from MS exclusive
Fix https://github.com/kumahq/kuma/issues/14322
=> fix(kuma-cp): reconcile pods if MeshService mode changed to remove duplicated inbounds

test/e2e_env/kubernetes/meshidentity/spire.go, test/e2e_env/multizone/meshservice/policies.go, test/e2e_env/multizone/meshtimeout/meshtimeout.go, test/framework/envoy_admin/config_dump/config_dump.go, test/framework/envoy_admin/interface.go, test/framework/envoy_admin/tunnel/k8s.go, test/framework/envoy_admin/tunnel/universal.go, test/framework/envs/kubernetes/env.go, test/framework/envs/multizone/env.go, test/framework/k8s_cluster.go, test/framework/k8s_controlplane.go, test/framework/portforward/portforward.go
The old `tunnel.NewK8sEnvoyAdminTunnel` API was limited and required manual port-forward handling. We are moving to the new `portforward` API which provides a simpler and unified way of creating and reusing admin tunnels. Additionally, we add `GetConfigDump` support to improve envoy config validation in tests.
- replaced all usages of `tunnel.NewK8sEnvoyAdminTunnel` with `Cluster.GetOrCreateAdminTunnel` using `portforward.Spec`
- removed old `tunnel` import and added new `portforward` import
- updated e2e tests in `spire` and multizone `meshservice` to use the new API
- extended the admin tunnel with a `GetConfigDump` function for easier envoy configuration checks
=> test(framework): migrate to `portforward` API and add `ConfigDump` support

.renovate/github-actions.json, .renovate/go-control-plane.json, .renovate/mise.json, .renovate/security.json, renovate.json
Some of our Renovate presets and the main repository configuration needed functional improvements and cleanup. The security preset contained custom hand written configuration and an incorrect team reference, so assignment of vulnerability alerts did not work. We also had custom handling in renovate.json for Makefile versions instead of reusing official presets. Improving these presets makes Renovate behavior more consistent, fixes broken assignments, and reduces maintenance.
- Added `:configMigration` to automatically apply Renovate’s recommended migrations
- Replaced the legacy Makefile preset with Renovate’s official `customManagers:makefileVersions`
- Updated manager name from `custom.regex` to `regex` to match Renovate naming
- Simplified and cleaned up rules for GitHub Actions and …
=> ci(renovate): improve presets and update managers for consistency

renovate.json
The `:assignAndReview(team:kuma-security-managers)` preset was previously applied at the top level of the Renovate configuration. This caused all Renovate PRs, including regular dependency updates, to be assigned to the security managers team. The intention was to assign only vulnerability alerts to the team.
- Removed `:assignAndReview(team:kuma-security-managers)` from the top-level `extends`
- Added `:assignAndReview(team:kuma-security-managers)` under the `vulnerabilityAlerts` block so it only applies to security-related PRs
=> ci(renovate): move security team assignment under vulnerabilityAlerts

test/e2e_env/kubernetes/meshidentity/spire.go
I've noticed a failure of the test
* Change the DNS name of the test server to use a full Kubernetes name. In some tests we are using custom HostnameGenerators which create a different domain name, maybe it has an impact on this since I've noticed in envoy config that we have a DNS entry `"{\"records\":[{\"name\":\"test-server.meshidentity-spire.default.meshcircuitbreaker\",\"ips\":[\"10.43.206.83\",\"::ffff:a2b:ce53\"]}],\"ttl\":30}"`
* Fixed a description of the test since it was incorrectly copied during the implementation
* Seems like it's some timeout on fetching secrets but we don't have logs from spire to know why, I've added a namespace of spire to `DebugKube`
=> test(e2e): define whole dns name and fix test description

renovate.json
The Renovate configuration in this repository contained redundant settings and custom rules that are no longer needed. Shared presets were used without pinning, the config explicitly listed enabled managers even though Renovate now applies defaults, and there were local rules for handling `go-control-plane` which have since been moved into shared presets. To simplify maintenance and align with current best practices, the configuration has been cleaned up.
- Pinned `Kong/public-shared-renovate:backend` to `1.13.1`
- Pinned `Kong/public-shared-renovate:security-extended(area/security,team:kuma-security-managers)` to `1.13.1`
- Removed explicit `enabledManagers` list and rely on default manager set
- Deleted custom regex manager routing for `github.com/kumahq/go-control-plane{/,}**`
- …
=> ci(renovate): simplify config, pin presets, drop local `go-control-plane` rules

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml
We want to stop relying on the Bitnami-provided kube-state-metrics image and switch to the official upstream image. This ensures we are using a supported and secure source, while also taking advantage of the latest release. It also aligns our dependencies with the Kubernetes community standards.
- Updated the kube-state-metrics image to use `registry.k8s.io/kube-state-metrics/kube-state-metrics`
- Bumped the version from 2.16.0 to 2.17.0
- Updated the digest to the upstream image’s published SHA256
Kuma now depends on the official kube-state-metrics image, gaining upstream fixes, security patches, and a more reliable source of updates.
=> chore(kumactl): update kube-state-metrics image source and version

docs/madr/decisions/083-finalized-schemes-for-unified-envoy-resources-and-stats-naming-formats.md
The unified naming work for Envoy resources and stats was spread across earlier MADRs, which created gaps and inconsistencies. Over time, some deviations were introduced without being clearly documented. This made it difficult for contributors to know which format was the final one to follow. To solve this, a new decision record was needed to consolidate the formats, capture deviations, and act as the single source of truth for the unified naming feature.
- Added a new decision record to serve as the central reference for unified naming  
- Summarizes the finalized schemes for key reporting indicators, contextual naming, and system-level metrics  
- Consolidates earlier decisions from MADRs 070, 076, and 077, and explicitly documents where deviations were made  
- Unifies naming …
=> docs(MADR): add MADR as the source of truth for unified naming formats

UPGRADE.md
There could be confusion between Kuma's system namespace (kuma-system) and k8s's system namespace (kube-system)
=> docs(UPGRADE.md): clarify what system namespace we're talking about

.github/workflows/build-test-distribute.yaml, mk/dev.mk, renovate.json
Reduce Renovate noise, keep our weekly cadence and safety checks, and remove manual updates in golden files and install manifests. Use the refactored shared presets so we inherit sensible defaults with room to override. Keep commit history clean by relying on squash auto-merge for routine updates and by shortening pseudo version strings in titles. Align version hints and drop unused variables so Renovate tracks the right sources.
- Switched to the refactored `Kong/public-shared-renovate` default preset and scoped helpers
- Limited Renovate to the managers we actually use and ignored unused custom managers
- Scheduled updates on Mondays using the shared preset
- Enabled squash auto-merge for minor and patch with all checks required
- Added `renovate/keep-updated` label to keep PRs rebased …
=> ci(renovate): adopt shared presets, trim managers, group tool updates

app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go, pkg/xds/bootstrap/parameters.go, pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/types/bootstrap_request.go
The app probe proxy field uses a historical wire key that does not match the field name. During rolling upgrades CP and DP can run with different versions. Changing the field name or JSON tag would invert behavior between versions and can break probes. We need explicit documentation in code to make the constraint visible and to prevent accidental changes.
Added comments in these places to document the contract and risks:
- DP remote bootstrap request construction
- CP bootstrap request type
- CP bootstrap parameters
- Bootstrap template metadata population
Alternatives like adding a new field or changing the tag were considered risky without a versioned endpoint and a deprecation window. The comments link to the issue that should guide any future versioned change.
Closes …
=> docs(bootstrap): document app probe proxy wire key to prevent upgrade flips

pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshfaultinjection/plugin/xds/legacy_configurer.go
Small refactoring to make future changes to MeshFaultInjection rules API easier to review 
=> chore(MeshFaultInjection): rename legacy configurer

renovate.json
We had a long, custom catch all rule that defined commit message templates in this repo. Keeping that in sync with shared standards is hard and noisy. Moving to the shared preset removes duplication and puts the logic in one place.
- Removed local `commitMessage*` fields plus the per update type action mappings from the catch all `packageRule`
- Extended `Kong/public-shared-renovate//scoped/kuma/commit-message-baseline` instead
- Kept the rule as the last packageRule to preserve precedence over earlier rules
- Renovate `packageRules` docs: https://docs.renovatebot.com/configuration-options/#packagerules
- Shared presets repo: https://github.com/Kong/public-shared-renovate
=> ci(renovate): use shared commit message baseline preset

mk/k3d.mk
Pulling k3s images from docker.io registry sometimes takes more than 2 minutes. Long-term fix will resolve the actual problem of long pulling, but for now we just want to have CI running on `master`.
Increased timeout up to 300s
=> ci(k3d): cluster creation timeout is insufficient

docs/madr/decisions/084-add-kri-to-rest-api-resources.md
The GUI and other clients need a stable machine generated identifier to reliably correlate REST API resources with the origins that produced their Envoy configuration. Reconstructing KRI on the client is fragile and inconsistent across endpoints.
This PR adds a MADR documenting the decision to compute and inject `meta.kri` during JSON marshalling of `ResourceMeta`. The decision explains why this is preferred over adding fields across many structs and code paths. It also notes that OpenAPI templates will be updated to document `meta.kri` as a readOnly string and clarifies that legacy protobuf resources are out of scope beyond existing Inspect API coverage.
- Technical Story: https://github.com/kumahq/kuma/issues/14462
- GUI Issue: https://github.com/kumahq/kuma-gui/issues/4220
=> docs(MADR): record decision to add KRI to REST API resources

app/kumactl/cmd/install/testdata/install-transparent-proxy.dns.no-conntrack.golden.txt, pkg/transparentproxy/iptables/builder/builder_table_nat.go
Allow DNS over TCP to bypass the mesh DNS and go to cluster DNS directly since DNS over TCP is usually happened when UDP truncation and Mesh DNS response is small and never truncates.
Exclude TCP traffic of DNS queries from transparent proxy rules
fixes https://github.com/kumahq/kuma/issues/14487
=> fix(dns): allow DNS traffic over TCP to bypass the mesh DNS

mk/check.mk
In #18081 PR, there is a error with fatal: Not a valid object name master
this PR fixes #14228 
now are referencing the origin/master instead of master
=> chore(make): fix reference to master in check/rbac target

docs/madr/decisions/085-active-branches-renovate-preset.md
We want one source of truth for active branches and the ability for Renovate to use it directly. The current file is a plain array that scripts can read, but Renovate cannot extend it as a preset. This limits Renovate features on release branches, like OSV alerts and controlled package updates.
This PR adds a MADR that formalizes the change from an array to an object with `baseBranchPatterns`. Renovate can then extend the preset with `kumahq/kuma:active-branches`. The document covers:
- The new JSON shape and how Renovate reads it
- The benefits of enabling OSV alerts on release branches
- A low risk migration plan that supports both shapes
- `jq` snippets to keep existing scripts working during rollout
- An example Renovate config to limit updates on release branches to OSV and Envoy …
=> docs(MADR): document switch to Renovate preset for active branches

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml
Bitnami registry changes caused friction and reliability issues when pulling kube-state-metrics. To reduce risk and align with upstream hosting, we switched to the upstream image on registry.k8s.io and pinned it by digest for deterministic deployments.
- Replaced the Bitnami kube-state-metrics image with the upstream image hosted on registry.k8s.io and pinned it by sha256 digest
- Updated all affected golden files so tests reflect the new image reference
=> feat(kumactl): switch from Bitnami to registry.k8s.io and pin

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml
Recent changes on the Bitnami registry introduced uncertainty around where the image is hosted and how it is packaged. To avoid surprises and stay close to the project defaults, we switch to the upstream kube-state-metrics image. We keep the same version and add a digest to make deployments repeatable.
- Replace the Bitnami kube-state-metrics image with `registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.15.0` and pin by sha256 digest
- Update kumactl install observability golden files to reflect the new image reference
=> feat(kumactl): switch kube-state-metrics to upstream image

test/framework/deployments/postgres/kubernetes.go
Some CloudNativePG chart tags in the upstream registry are mutable. When tags are re-pointed to new digests, our CI can start pulling different artifacts without any change on our side, which causes flaky and non-reproducible runs across branches.
- Updated Kubernetes Postgres test deployment constants to reference charts by immutable digest only
- Added an in-code note explaining why tag@digest was avoided and why digest-only pinning is used
- Preserved the previous tag information as inline comments for human context and easier auditing
- General practice: use immutable digests to guarantee reproducibility in CI
=> test(postgres): pin CNPG Helm charts by digest only for CI stability

test/e2e/helm/kuma_helm_deploy_global_and_zone_universal_mode.go, test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go, test/framework/deployments/postgres/deployment.go, test/framework/deployments/postgres/kubernetes.go
We need deterministic and stable Postgres deployments in tests. The CNPG controller requires an image tag to be present, but tags are mutable and can break CI when digests change behind them. E2E Helm values must reference the same secret that the Postgres deployment creates. We are also updating Postgres to version 18.0 to keep current and to verify compatibility. The e2e changes fix legacy tests, which is important for older release branches, and this will be backported.
- Use `<tag>@<digest>` for `cluster.imageName` to satisfy CNPG checks while pinning immutably for CI reproducibility
- Update Postgres version to `18.0`
- Switch from a single `initScript` string to `initScripts []string` and set Helm values as an indexed list for `cluster.initdb.postInitSQL`
- Add sane defaults in …
=> test(postgres): pin image, update to 18.0, fix legacy e2e secrets

api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, pkg/core/faultinjections/matcher_test.go, pkg/core/permissions/matcher_test.go, pkg/core/ratelimits/matcher_test.go, pkg/core/xds/inspect/attachments_test.go, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/testdata/old_policy.golden.yaml, pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go, pkg/xds/generator/inbound_proxy_generator.go, pkg/xds/generator/inbound_proxy_generator_test.go, pkg/xds/generator/testdata/inbound-proxy/8-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/5-envoy-config.golden.yaml
Right now we are having issue with `inbounds[].proxyResourceName` in `_layout` endpoint being different then actual inbound name in Envoy config and stats. Which makes it impossible for GUI to simply match them. They need to have the same name. 
According to the [MADR](https://github.com/kumahq/kuma/blob/master/docs/madr/decisions/077-migrating-to-consistent-and-well-defined-naming-for-non-system-envoy-resources-and-stats.md#option-1-use-the-contextual-format-defined-for-proxy-local-resources) This should be `sectionName` not port value, so we need to align Envoy config and stats with API. This change should be only applied to unified resource naming
Updating how we build inbound name for Envoy config and stats by extending `InboundInterface` with `sectionName`
Fix …
=> fix(envoy-naming): rename inbound Envoy resource names and stats to use `sectionName` instead of port value when using unified naming

test/e2e/helm/kuma_helm_upgrade_multizone.go, test/e2e/helm/kuma_helm_upgrade_standalone.go, test/framework/config.go, test/framework/ginkgo.go, versions.yml
CI on `release-2.9` was failing due to two issues: outdated test defaults and a `Bitnami` registry change that broke Helm upgrade tests for `2.8.x`. We needed to align our patch lines with current supported releases and ensure a stable upgrade flow unaffected by deprecated image sources.
- Bumped the default `Helm` version used in tests to match the compatibility level of the supported Kuma release line (`2.7.x`), as `2.6.x` is out of support and no longer relevant for CI.
- Updated `versions.yml` to use the latest patch releases that reference images from the official `registry.k8s.io` instead of the deprecated `Bitnami` registry. This ensures consistent `kubectl` image availability and resolves upgrade test failures.
- Adjusted the Helm upgrade e2e for standalone installs to set …
=> test(e2e/helm): fix upgrade test registry logic after `bitnami` changes
