kumahq/kuma

app/kumactl/cmd/get/get_meshes.go, app/kumactl/cmd/get/get_meshes_test.go, app/kumactl/cmd/get/testdata/get-meshes.golden.json, app/kumactl/cmd/get/testdata/get-meshes.golden.txt, app/kumactl/cmd/get/testdata/get-meshes.golden.yaml, app/kumactl/pkg/output/table/cells.go
=> kumactl: show mtls in meshes

app/kuma-dp/cmd/run.go, app/kuma-dp/cmd/run_test.go
The simplest solution would be to fill Config struct before passing to Load, but we want args to take precedence over env vars, therefore this need to be done after loading env vars.
Maybe we need to revisit https://github.com/spf13/viper at some point, but I remember I had issues with it.
=> kuma-dp: cli args

.circleci/config.yml, Makefile, app/kumactl/cmd/install/install_control_plane.go, app/kumactl/cmd/install/install_control_plane_test.go, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
changes:
* be default, `kumactl install` should use the same version of Docker images as `kumactl` itself
=> kumactl install: use Docker images of the same version as kumactl itself

app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go, pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/rest/model.go, pkg/xds/bootstrap/server.go
Bring down size of binary by excluding dependency from 40MB to 22MB. Good catch @yskopets !
=> kumadp: bring down size of binary by excluding dependency

app/kuma-injector/pkg/injector/injector.go, app/kuma-injector/pkg/injector/testdata/inject.01.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.02.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.03.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.04.golden.yaml, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-dp/testdata/default-config.golden.yaml, pkg/config/xds/config.go, pkg/xds/bootstrap/template.go, pkg/xds/bootstrap/testdata/bootstrap.golden.yaml
changes:
* to avoid constantly running into `port already in use` problem, turn off Envoy Admin interface by default
=> kuma-dp: turn off Envoy Admin interface by default

api/mesh/v1alpha1/mesh.pb.go, api/mesh/v1alpha1/mesh.proto, app/kumactl/cmd/get/get_meshes.go, app/kumactl/cmd/get/get_meshes_test.go, app/kumactl/cmd/get/testdata/get-meshes.golden.json, app/kumactl/cmd/get/testdata/get-meshes.golden.txt, app/kumactl/cmd/get/testdata/get-meshes.golden.yaml, pkg/xds/context/context.go, pkg/xds/envoy/envoy.go, pkg/xds/envoy/envoy_test.go, pkg/xds/server/components.go
Access logs that shows traffic. Due to L4, we are very limited what we can display
Format for now
```
❯❯❯ cat access.log
[2019-09-07T07:32:04.323Z] 127.0.0.1:50897->127.0.0.1:11012 took 1ms, sent 333 bytes, received: 79 bytes
[2019-09-07T07:32:06.407Z] 127.0.0.1:50901->127.0.0.1:11012 took 1ms, sent 333 bytes, received: 79 bytes
[2019-09-07T07:32:07.191Z] 127.0.0.1:50904->127.0.0.1:11012 took 1ms, sent 333 bytes, received: 79 bytes
[2019-09-07T07:32:07.653Z] 127.0.0.1:50907->127.0.0.1:11012 took 1ms, sent 333 bytes, received: 79 bytes
```
refernce: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log
Once we have outbound CDS, we can try `%UPSTREAM_CLUSTER%`
=> control-plane: access logs

pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/xds/config.go, pkg/xds/bootstrap/testdata/bootstrap.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml
Replace xDS default localhost with IP address so it will work on centos by default.
=> control-plane: xds - replace localhost with ip address

Makefile
changes:
* CI build is failing because `kumactl` combines a default image name `*.bintray` with version `unknown`. Obviously, there is no such image on `bintray`
* to avoid the issue, use `kuma/kuma-*` image names during CI
=> ci: fix failing build

pkg/xds/server/reconcile_test.go
This PR handles three error variables that were being assigned and then dropped in the unit tests.
pkg/xds/server: fix dropped errors in tests
=> pkg/xds/server: fix dropped errors in tests

app/kuma-dp/pkg/dataplane/envoy/envoy.go, app/kuma-dp/pkg/dataplane/envoy/envoy_test.go
=> kuma-dp: disable Envoy hot restart in order to support multiple Envoy instances on the same Linux machine

app/kuma-dp/cmd/run.go, app/kuma-dp/cmd/run_test.go, app/kuma-dp/cmd/testdata/envoy-mock.sleep.sh, pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-dp/config_test.go, pkg/config/app/kuma-dp/testdata/default-config.golden.yaml, pkg/config/app/kuma-dp/testdata/invalid-config.input.yaml
Previously, `kuma-dp` had `--config-dir` option set to `/tmp/kuma.io/envoy` by default.
If 2 `kuma-dp` instances were started on the same machine, both of them would persist generated config file at `/tmp/kuma.io/envoy/bootstrap.yaml`, overwriting each other.
* the new default value for `--config-dir` is empty
* in that case `kuma-dp` will create a temporary dir, use it to store generated Envoy config, and remove that directory on exit
=> kuma-dp: if `--config-dir` argument is not set, automatically create a temp dir

pkg/xds/generator/inbound_proxy_generator_test.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/proxy_template_profile_source_test.go, pkg/xds/generator/proxy_template_test.go
This PR fixes dropped errors in `pkg/xds/generator` tests. These errors would have broken the subsequent test statements, but their origins would have been obscured.
=> pkg/xds/generator: fix dropped errors in tests

.circleci/config.yml, tools/releases/distros.sh, tools/releases/docker.sh, tools/releases/dockerfiles/Dockerfile.kuma-cp, tools/releases/dockerfiles/Dockerfile.kuma-dp, tools/releases/dockerfiles/Dockerfile.kuma-injector, tools/releases/dockerfiles/Dockerfile.kuma-tcp-echo
- Add script to automate Docker images build and release
- Integrate Docker automation into Circle CI
=> ci: docker automation

app/kumactl/cmd/apply/testdata/apply-mesh-template.yaml, app/kumactl/cmd/apply/testdata/apply-mesh.yaml, dev/examples/k8s/meshes/pilot.yaml, pkg/plugins/resources/k8s/native/config/samples/mesh_v1alpha1_mesh.yaml
Rename embedded to builtin in sample YAMLs. At some point we've changed the name from embedded to builtin, but apparently we missed some example YAMLs.
* Fix example YAMLs
Fix #262
=> fix(kuma-cp) rename embded to builtin in sample yamls

app/kuma-dp/pkg/dataplane/envoy/envoy.go
- Search in configured path
- Fallback to same directory as kuma-dp and current working directory
Fixes #249
=> kuma-dp: improve envoy binary lookup

pkg/core/bootstrap/bootstrap.go
Fixes a dropped `error` under `core/bootstrap`.
=> core: fix dropped error

api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, api/mesh/v1alpha1/mesh.pb.go, api/mesh/v1alpha1/mesh.proto, pkg/core/logs/matcher.go, pkg/core/logs/matcher_suite_test.go, pkg/core/logs/matcher_test.go, pkg/core/xds/types.go, pkg/xds/envoy/access_logs.go, pkg/xds/envoy/envoy.go, pkg/xds/envoy/envoy_test.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/proxy_template.go, pkg/xds/server/components.go, pkg/xds/server/snapshot_generator_test.go
First version of traffic logging
This is first version of traffic logging. It only supports file backend in mesh. The next step is to support sending it to ELK stack.
For the matching part. We match all inbounds and service on outbound and we place access log on outbound listener. For now, we apply all rules that match, we don't choose the most relevant one.
I did not reuse logic from TrafficPermission for now, because it's different. Here we match all inbound + outbound, in TrafficPermission we match destinations to inbounds.  
* Implement Traffic Log matching.
#271
=> feat(kumacp) traffic logging matching

pkg/config/app/kuma-cp/config.go, pkg/config/core/config.go, pkg/config/loader_test.go, pkg/core/bootstrap/autoconfig.go, pkg/core/bootstrap/bootstrap.go, pkg/sds/server/components.go, pkg/xds/context/context.go
changes:
* move `EnvironmentType` into `config/core` package (to make it reusable in other parts of the configuration)
=> kuma-cp: move `EnvironmentType` into `config/core` package

pkg/plugins/resources/k8s/native/api/v1alpha1/dataplane_insight_types_helpers.go, pkg/plugins/resources/k8s/native/api/v1alpha1/dataplane_types_helpers.go, pkg/plugins/resources/k8s/native/api/v1alpha1/global_type_registry_test.go, pkg/plugins/resources/k8s/native/api/v1alpha1/mesh_types_helpers.go, pkg/plugins/resources/k8s/native/api/v1alpha1/proxytemplate_types_helpers.go, pkg/plugins/resources/k8s/native/api/v1alpha1/trafficlogging_types_helpers.go, pkg/plugins/resources/k8s/native/api/v1alpha1/trafficpermission_types_helpers.go
changes:
* set TypeMeta on prototype k8s resource (all other k8s resources get created by calling `DeepClone()` on them)
=> kuma-cp: set TypeMeta on all k8s resources (pre-requirement for k8s Admission WebHooks to work as expected)

pkg/core/plugins/interfaces.go, pkg/core/plugins/registry.go
changes:
* introduce a new plugin type - `RuntimePlugin` - which can be used to add arbitrary environment-specific features (e.g., Admission WebHook Server in `k8s` environment)
=> kuma-cp: introduce RuntimePlugin

tools/releases/distros.sh, tools/releases/docker.sh
changes:
* use `BINTRAY_REPOSITORY` env var to override repo with `*.tar.gz` files
* use `KUMA_DOCKER_REPO` env var to override repo with Docker images
=> ci: make Bintray release repositories configurable

CHANGELOG.md, pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/template.go, pkg/xds/bootstrap/testdata/bootstrap.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/envoy/access_logs.go, pkg/xds/envoy/envoy_test.go
* `Access Log Server` integrated into `kuma-dp` didn't work on Kubernetes
* Prolonged troubleshooting didn't reveal a root cause
* Replacing `Google gRPC client` with `Envoy gRPC client` was a hunch, but apparently it works
=> kuma-cp: fix an issue with Access Log Server on Kubernetes by replacing Google gRPC client with Envoy gRPC client

app/kumactl/cmd/config/config_control_planes_add.go, app/kumactl/cmd/config/config_control_planes_add_test.go, app/kumactl/cmd/config/testdata/config-control-planes-add.01.golden.yaml, app/kumactl/cmd/config/testdata/config-control-planes-add.02.golden.yaml, app/kumactl/pkg/config/validate.go, pkg/api-server/index_ws.go, pkg/api-server/types/index.go, pkg/config/app/kumactl/v1alpha1/config_helpers.go
Validation before the control plane is added that it is valid running API Server of Kuma.
* Implement validation that the control plane is running
Fix #181
=> feat(kumactl) validate that the control plane is running

pkg/xds/server/server.go, pkg/xds/server/server_test.go
* modify generic `go-control-plane` to always respond to `EDS` requests that are happening at `cluster warming stage`
We’ve run into an issue where `envoy` keeps updated `cluster` in a `warming state` for indefinite amount of time.
Such behaviour is explained in the `Resource warming` section of the `xDS Protocol` (https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#resource-warming):
> Clusters and Listeners go through warming before they can serve requests. This process happens both during Envoy initialization and when the Cluster or Listener is updated. Warming of Cluster is completed only when a ClusterLoadAssignment response is supplied by management server. … Management server is expected to provide the EDS/RDS updates during warming. If management server does not …
=> kuma-cp: modify generic `go-control-plane` to always respond to EDS requests that are happening at cluster warming stage

.circleci/config.yml, Makefile
* make `clang-format` an optional tool (which is handy for contributors)
* as part of CI, do NOT install `clang-format` on Mac since it takes unreasonable amount of time
=> ci: make `clang-format` an optional tool

pkg/sds/server/sds.go, pkg/sds/server/sds_test.go
* `SDS` server should support `DiscoveryRequests` with an empty list of resource names
Fix #328
=> kuma-cp: SDS server should support DiscoveryRequests with an empty list of resource names

NOTICE, tools/releases/dockerfiles/Dockerfile.kuma-cp, tools/releases/dockerfiles/Dockerfile.kuma-dp, tools/releases/dockerfiles/Dockerfile.kuma-injector, tools/releases/dockerfiles/Dockerfile.kuma-tcp-echo, tools/releases/templates/LICENSE, tools/releases/templates/NOTICE, tools/releases/templates/README
* use proper `LICENSE` and `NOTICE` files required by the Apache License v2.0 (according to http://www.apache.org/dev/apply-license.html#new)
Fix #320
=> license: use proper LICENSE and NOTICE files

DEVELOPER.md
* start Docker container under `root` to be able to install `unzip`
* exclude `--rm` option since re-downloading dependencies after container restart takes too much time
* install `unzip` on container start-up
Fix #345
=> docs: update DEVELOPER.md

.circleci/config.yml, Makefile
* test Minikube example on different versions of Kubernetes
=> ci: test Minikube example on different versions of Kubernetes

RELEASE.md
=> docs(*) release process

.circleci/config.yml, Makefile, examples/minikube/README.md, examples/minikube/kuma-demo/kuma-demo.yaml, examples/minikube/kumactl_workflow.sh, examples/minikube/policies/mtls.yaml
=> ci: test mTLS on Kubernetes

.circleci/config.yml, app/kuma-injector/pkg/injector/injector.go, app/kuma-injector/pkg/injector/injector_test.go, app/kuma-injector/pkg/injector/testdata/inject.02.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.03.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.04.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.05.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.05.input.yaml
* to support versions of `Kubernetes` prior to `v1.15.0`, mutating web hook must explicitly copy `ServiceAccount` volume mount into containers it creates
Fix #325
=> kuma-injector: mutating web hook must explicitly copy ServiceAccount volume mount into containers it creates

examples/kubernetes/kuma-demo/README.md
- Remove instruction for only using Kubernetes 1.15+ because the bug has been fixed. 
- Bumping docker image for kuma-demo.
Fix #325
=> docs: remove k8s 1.15 instruction

pkg/catalogue/client_test.go
This PR fixes a dropped error in the `catalogue_test` package.
=> pkg/catalogue_test: fix dropped error

app/kumactl/cmd/get/get_proxytemplates.go, app/kumactl/cmd/get/testdata/get-proxytemplates.golden.txt
Change output of
```
kumactl get proxytemplates
```
from:
```
NAME
custom-template
another-template
```
to:
```
MESH      NAME
default   custom-template
default   another-template
```
Fix #358
=> kumactl: add column MESH for get proxytemplates

.circleci/config.yml, .golangci.yml, Makefile, Makefile.dev.mk, pkg/catalogue/client/client.go
Introducing [golangci-lint](https://github.com/golangci/golangci-lint). It is run on `make check` and also checked on CI.
=> ci(*) introduce golangci-lint

app/kumactl/cmd/config/config_control_planes_add.go, app/kumactl/cmd/config/config_control_planes_add_test.go, app/kumactl/cmd/config/testdata/config-control-planes-add.03.golden.yaml, app/kumactl/cmd/config/testdata/config-control-planes-add.03.initial.yaml, docs/cmd/kumactl/HELP.md, pkg/config/app/kumactl/v1alpha1/config_helpers.go
Add the possibility to overwrite an existing control plane configuration.
Fix #380
=> Add overwrite option

app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go
Slight language revision for the error log message that appears when trying to run kuma-dp with no dataplane config supplied.
=> language revision for the config 404 message

pkg/plugins/discovery/k8s/controllers/pod_controller.go, pkg/plugins/discovery/k8s/controllers/pod_controller_test.go
* on `k8s`, reconcile on `Dataplane` delete to handle a case where a user manually deletes `Dataplane`
Fix #311
=> kuma-cp: reconcile on Dataplane delete to handle a case where a user manually deletes Dataplane

pkg/api-server/resource_ws_test.go, pkg/api-server/server.go, pkg/config/api-server/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go
Use support of CORS in go-restful.
Fix #409
=> feat(kuma-cp) support CORS in api server

Makefile.e2e.mk
* `e2e` tests are now failing due to the changes at `mockbin.org`
=> ci: fix failing e2e tests

dev/examples/universal/traffic-routes/web-to-backend.yaml, pkg/api-server/definitions/all.go, pkg/api-server/definitions/traffic_route.go, pkg/api-server/read_only_resource_ws_test.go, pkg/api-server/resource_api_client_test.go, pkg/api-server/resource_ws_test.go, pkg/api-server/sample_resource_definition_test.go, pkg/api-server/traffic_route_ws_test.go, pkg/core/resources/apis/mesh/traffic_route.go, pkg/plugins/resources/remote/store_test.go
* add `TrafficRouteResource` to core model
* update unit tests to avoid collisions with `sample.TrafficRouteResource`
=> kuma-cp: add `TrafficRouteResource` to core model

app/kumactl/cmd/apply/apply.go, app/kumactl/cmd/apply/apply_test.go
Kumactl apply should parse URLs, for example:
```
$ kumactl apply -f http://somewhere
```
* Implement URL parsing for kumactl apply
Fix #155
=> feat: kumactl parse url 

api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, pkg/core/xds/types.go, pkg/xds/envoy/envoy.go, pkg/xds/envoy/envoy_test.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/server/components.go, pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go, pkg/xds/topology/router.go, pkg/xds/topology/router_helper_test.go, pkg/xds/topology/router_test.go, pkg/xds/topology/topology_suite_test.go
* pick a single the most specific `TrafficRoute` for every outbound interface of a `Dataplane`
* match by an exact value is more specific than match by `*`
* e.g., `service: backend` wins over `service: *`
* match by `N+1` tags is more specific than match by `N` tags
* e.g., `service: backend, version: v1` wins over `service: backend`
* if 2 selectors have the same number of tags, the one that has more exact values is more specific
* e.g., `service: backend, version: v1` wins over `service: backend, version: *`
* to compare a combination of `source` and `destination` selectors we sum up their numbers of exact and wildcard matching tags
* e.g.,
* given `TrafficRoute 1`:
```yaml
sources:
- match:
service: web
version: '*'
destinations:
- match:
service: backend         
``` 
* and …
=> kuma-cp: pick a single the most specific TrafficRoute for every outbound interface of a Dataplane

api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, pkg/core/xds/types.go, pkg/core/xds/types_test.go, pkg/xds/envoy/envoy.go, pkg/xds/envoy/envoy_test.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/proxy_template.go, pkg/xds/generator/proxy_template_profile_source_test.go, pkg/xds/generator/resource_generator.go, pkg/xds/generator/resource_generator_test.go, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/05.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/06.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/07.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/08.envoy.golden.yaml, pkg/xds/server/components.go, pkg/xds/topology/router.go
* generate `tcp_proxy` configuration that routes to a list of weighted clusters according to `TrafficRoute`
* generate a separate `Cluster` for each unique subset referenced by `TrafficRoute`
* if an outgoing listener has more than 1 destination `Cluster`, configured `weighted clusters`
* if a destination has 0 weights in Kuma, don't include into Envoy config (Envoy doesn't support 0 weight)
=> kuma-cp: generate `tcp_proxy` configuration that routes to a list of weighted clusters according to TrafficRoute

app/kuma-ui/pkg/server/server.go, app/kuma-ui/pkg/server/server_test.go, app/kuma-ui/pkg/server/types/gui_config.go, pkg/config/gui-server/config.go, pkg/core/bootstrap/autoconfig.go, pkg/core/bootstrap/autoconfig_test.go
The problem is that even if we expose the GUI on some port, the API is on a different one. We need to deliver configuration about API coordinates. To do this, we can expose `/config` endpoint with configuration.
I used similar pattern to Catalog for now, which is keep it as Kuma Config, but don't expose env vars/yaml. Autoconfig everything.
Once we get more options for frontend, we can put it in the `GuiConfig` and use standard way to configure Kuma CP to configure embedded frontend.
Also I exposed the environment variable, to display if kuma is running on k8s or not on the GUI.
=> GUI server config

app/kumactl/cmd/config/config_control_planes_add_test.go, app/kumactl/pkg/config/validate.go, pkg/core/resources/apis/mesh/traffic_permission.go, pkg/core/resources/apis/mesh/traffic_permission_validator.go, pkg/core/resources/apis/mesh/traffic_permission_validator_test.go, pkg/core/resources/apis/mesh/traffic_route_validator.go, pkg/core/resources/apis/mesh/validators.go
Validate traffic permission. Only service tag is allowed in both cases for now.
Once this is merged, I'll fix the TrafficLog to also use `OnlyServiceTagAllowed`
=> feat(kuma-cp) validate traffic permission

pkg/core/resources/apis/mesh/traffic_log.go, pkg/core/resources/apis/mesh/traffic_log_validator.go, pkg/core/resources/apis/mesh/traffic_log_validator_test.go, pkg/core/resources/manager/manager_test.go
Traffic log validation.
Destination can only have service tag.
`conf` or `conf.backend` can be empty, because then we choose `defaultBackend` from the mesh.
Ideally we should also validate if the backend we are setting is specified in the mesh. Then we also need to think if we can remove the mesh if the backend is used in TrafficLog. This is dynamic validation (depends on some other resource) which we don't support yet. We can improve this in a separate PR.
=> feat(kuma-cp) validate traffic log

examples/kubernetes/kuma-demo/kuma-demo-aio.yaml
* split a single `demo-app` into 2 separate deployments: `frontend` and `backend`
=> workshop: split demo app into frontend and backend

examples/kubernetes/kuma-demo/kuma-demo-aio.yaml
* add more labels on `Pods` to showcase `TrafficRoute`
=> demo: add more labels on Pods to showcase TrafficRoute

examples/kubernetes/kuma-demo/README.md, examples/kubernetes/kuma-demo/kuma-demo-aio.yaml, examples/kubernetes/kuma-demo/kuma-demo.yaml
* rename `Service` objects to simplify `TrafficPermission`, `TrafficRoute`, `TrafficLogging` examples
=> demo: rename Service objects to simplify TrafficPermission, TrafficRoute, TrafficLogging examples

app/kumactl/cmd/config/config_control_planes_add_test.go, app/kumactl/cmd/generate/generate.go, app/kumactl/cmd/generate/generate_certificate.go, app/kumactl/cmd/generate/generate_certificate_test.go, app/kumactl/cmd/install/install_control_plane.go, app/kumactl/cmd/install/install_control_plane_test.go, docs/cmd/kumactl/HELP.md, pkg/core/bootstrap/autoconfig.go, pkg/tls/cert.go, tools/docs/kumactl/gen_help.sh
Generate certificate from `kumactl`.
Unfortunately, we cannot generate certificate for the server and client in the same way therefore we need to specify the purpose.
=> feat(kumactl) generate certificate

app/kuma-cp/cmd/run.go, pkg/api-server/config_ws.go, pkg/api-server/config_ws_test.go, pkg/api-server/resource_api_client_test.go, pkg/api-server/server.go, pkg/config/api-server/config.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-injector/config.go, pkg/config/config.go, pkg/config/core/discovery/config.go, pkg/config/core/resources/store/config.go, pkg/config/display.go, pkg/config/gui-server/config.go, pkg/config/loader.go, pkg/config/plugins/discovery/universal/config.go, pkg/config/plugins/resources/k8s/config.go, pkg/config/plugins/resources/postgres/config.go, pkg/config/plugins/runtime/config.go, pkg/config/plugins/runtime/k8s/config.go, pkg/config/sds/config.go, pkg/config/token-server/config.go, pkg/config/util.go, pkg/config/xds/bootstrap/config.go, pkg/config/xds/config.go
Starting as draft, because of open questions.
1) **Library**
I tried to switch from `gopkg.in/yaml.v2` to `github.com/ghodss/yaml`. It required to change `yaml` to `json` annotations, but it turned out that `ghodss` does not support `time.Duration`, therefore you cannot put in config stuff like `xdsConnectTimeout: 1s`. I'd say this is a decrease in UX.
2) **Secret values**
For now, we only want to hide the Postgres password, but who knows what will come next. I see 2 ways to implement this.
1. via annotation like `secret:"true"` next to `envconfig` and `yaml`. Then scan struct recursivly via reflection and replace it via placeholder. Extra tricky part, the value can be of many types.
2. Just like validation, we can add `func HideSecretValues()` method on `Config`, call that for every …
=> feat(kuma-cp) expose config

app/kumactl/cmd/config/config_control_planes_add_test.go
The error message here is not consistent. Sometimes it times out waiting for requests (socket timeout), sometimes it times out on the connection itself (connection timeout).
=> fix(kumactl) change assertion of flaky test

pkg/core/policy/matcher.go, pkg/core/policy/types.go, pkg/core/resources/apis/mesh/traffic_route.go, pkg/xds/topology/router.go
Refactor matching logic to common function so it can be used in traffic logging and other new policies.
=> feat(kuma-cp) Refactor matching logic to common function

.circleci/config.yml, Makefile.e2e.mk, dev/examples/k8s/traffic-routes/web-to-backend.yaml, tools/e2e/examples/docker-compose/README.md, tools/e2e/examples/docker-compose/backend.yaml, tools/e2e/examples/docker-compose/docker-compose.yaml, tools/e2e/examples/docker-compose/kuma-example-installer.sh, tools/e2e/examples/docker-compose/policies/everyone-to-everyone.traffic-permission.yaml, tools/e2e/examples/docker-compose/policies/mtls.yaml, tools/e2e/examples/docker-compose/policies/no-mtls.yaml, tools/e2e/examples/docker-compose/policies/web-to-backend.traffic-route.yaml, tools/e2e/examples/minikube/README.md, tools/e2e/examples/minikube/kuma-routing/kuma-routing.yaml, tools/e2e/examples/minikube/policies/mtls.yaml, tools/e2e/examples/minikube/policies/no-mtls.yaml, tools/e2e/examples/minikube/policies/web-to-backend.traffic-route.yaml
* add `e2e` tests for `TrafficRoute`
* both `universal` and `k8s` modes
* both with mTLS and without mTLS
=> ci: add e2e tests for TrafficRoute

pkg/core/logs/matcher.go, pkg/core/logs/matcher_test.go, pkg/core/policy/types.go, pkg/core/resources/apis/mesh/traffic_log.go, pkg/core/xds/types.go, pkg/xds/envoy/access_logs.go, pkg/xds/envoy/envoy.go, pkg/xds/envoy/envoy_test.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/proxy_template.go, pkg/xds/generator/proxy_template_profile_source_test.go, pkg/xds/server/snapshot_generator_test.go
Current implementation of Traffic Logs matcher workedn in a way that every Traffic Log that matched was applied. We want to have consistent behaviour in every policy therefore now only the most matched Traffic Log is applied, just like Traffic Route.
This is a breaking change since we alter the behaviour of applying Traffic Log policies.
=> feat(kuma-cp) Reuse matching logic for traffic logs

docs/proposals/HealthChecks-L4.md
* add design proposal for `L4 HealthCheck`
#393
=> docs: add design proposal for L4 HealthCheck

pkg/core/policy/matcher.go, pkg/core/resources/apis/mesh/health_check.go, pkg/core/xds/types.go, pkg/xds/server/components.go, pkg/xds/topology/healthchecks.go, pkg/xds/topology/healthchecks_test.go
* pick a single the most specific `HealthCheck` for every service reachable from a given a `Dataplane` (via outbound interfaces and `TrafficRoutes`)
=> kuma-cp: pick a single the most specific HealthCheck for every service reachable from a given a Dataplane (via outbound interfaces and TrafficRoutes)

CHANGELOG.md, tools/e2e/examples/docker-compose/docker-compose.yaml, tools/e2e/examples/minikube/kuma-routing/kuma-routing.yaml, tools/releases/distros.sh, tools/releases/dockerfiles/Dockerfile.kuma-dp
Update Envoy to v1.12.2
All new binaries are in the bintray.
=> feat(kuma-dp) update envoy to v1.12.2

CHANGELOG.md, app/kumactl/cmd/get/get_meshes.go, app/kumactl/cmd/get/get_meshes_test.go, app/kumactl/cmd/get/testdata/get-meshes.golden.json, app/kumactl/cmd/get/testdata/get-meshes.golden.txt, app/kumactl/cmd/get/testdata/get-meshes.golden.yaml
Display CA type in `kumactl get meshes`
Fix #492
=> feat(kumactl) display CA type in get meshes

CHANGELOG.md, dev/examples/k8s/meshes/prometheus.defaults.yaml, dev/examples/k8s/meshes/prometheus.manual.yaml, dev/examples/universal/meshes/prometheus.defaults.yaml, dev/examples/universal/meshes/prometheus.manual.yaml, pkg/core/managers/apis/mesh/mesh_manager_test.go, pkg/core/resources/apis/mesh/mesh_defaulter.go, pkg/core/resources/apis/mesh/mesh_defaulter_test.go
* automatically set default values for Prometheus settings in the Mesh resource
=> kuma-cp: automatically set default values for Prometheus settings in the Mesh resource

CHANGELOG.md, app/kumactl/cmd/get/get_meshes.go, app/kumactl/cmd/get/get_meshes_test.go, app/kumactl/cmd/get/testdata/get-meshes.golden.json, app/kumactl/cmd/get/testdata/get-meshes.golden.txt, app/kumactl/cmd/get/testdata/get-meshes.golden.yaml
* add `METRICS` column to the table output of `kumactl get meshes` to make it visible whether Prometheus settings have been configured
=> kumactl: add `METRICS` column to the table output of `kumactl get meshes` to make it visible whether Prometheus settings have been configured

docs/proposals/gateway.md
Overall, introducing a new entity seems cleaner, but it's more work and I'm not sure it's worth it.
On Kubernetes, a user won't even deal with it, because it will configure Gateway through annotation.
On Universal, the traffic can be just directed to the Gateway instead of Gateway's Envoy which is achievable right now.
=> docs(*) Gateway proposal

pkg/xds/context/context.go, pkg/xds/envoy/envoy.go, pkg/xds/envoy/envoy_test.go, pkg/xds/generator/inbound_proxy_generator_test.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/proxy_template_profile_source_test.go, pkg/xds/generator/proxy_template_test.go, pkg/xds/server/components.go, pkg/xds/server/snapshot_generator_test.go
* refactor Envoy config generators to have access to a complete `Mesh` resource
=> kuma-cp: refactor Envoy config generators to have access to a complete Mesh resource

CHANGELOG.md, pkg/core/xds/metadata.go, pkg/core/xds/metadata_test.go, pkg/xds/bootstrap/template.go, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml
* make port of Envoy Admin API available to Envoy config generators
=> kuma-cp: make port of Envoy Admin API available to Envoy config generators

pkg/core/xds/metadata.go, pkg/xds/envoy/envoy.go, pkg/xds/server/dataplane_metadata_tracker_test.go
* refactoring: use getter methods to avoid dereferencing a `nil` pointer
=> refactoring: use getter methods to avoid dereferencing a nil pointer

CHANGELOG.md, app/kuma-dp/cmd/run.go, app/kuma-dp/cmd/run_test.go, app/kuma-dp/pkg/dataplane/envoy/envoy.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap_test.go, pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-dp/config_test.go, pkg/config/app/kuma-dp/testdata/invalid-config.input.yaml, pkg/config/types/portrange.go, pkg/config/types/portrange_test.go, pkg/config/types/types_suite_test.go, pkg/test/network.go, pkg/util/net/net_suite_test.go, pkg/util/net/tcpsock.go, pkg/util/net/tcpsock_test.go
* `kuma-dp`
* enable `Envoy Admin API` by default with an option to opt out
* `--admin-port` option now accepts a port or range of ports to choose from, e.g.
* `9901`
* `9901-9999`
* `9901-`
* `-9901`
* the default value of `--admin-port` has changed from `` (empty) to `30001-65535`
* on startup, `kuma-dp` will pick the first available port from the range
=> kuma-dp: enable Envoy Admin API by default with an option to opt out

CHANGELOG.md, app/kuma-ui/pkg/server/server.go, app/kuma-ui/pkg/server/server_test.go, pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/gui-server/config.go, pkg/config/loader_test.go, pkg/core/bootstrap/autoconfig.go
Redirect requests from GUI on /api prefix to API Server. This simplifies setup since you don't have to coordinate exposing GUI and API server and configuring proper external address.
=> feat(kuma-cp) redirect requests from gui server to api server

pkg/core/xds/resource.go, pkg/core/xds/resource_test.go, pkg/xds/generator/inbound_proxy_generator_test.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/prometheus_endpoint_generator.go, pkg/xds/generator/prometheus_endpoint_generator_test.go, pkg/xds/generator/proxy_template.go, pkg/xds/generator/proxy_template_profile_source_test.go, pkg/xds/generator/proxy_template_raw_source_test.go, pkg/xds/generator/proxy_template_test.go, pkg/xds/generator/resource_generator.go, pkg/xds/generator/resource_generator_test.go, pkg/xds/generator/transparent_proxy_generator_test.go
* make `Resource` type reusable
* make `ResourceList` type reusable
* make `ResourceSet` type reusable
=> refactoring: make `Resource` types reusable by both primary ADS server and future MADS server

pkg/core/xds/context.go, pkg/util/xds/logger.go
* make `Logger` type reusable by both primary ADS server and future MADS server
=> refactoring: make `Logger` type reusable by both primary ADS server and future MADS server

CHANGELOG.md, pkg/mads/cache/cache_suite_test.go, pkg/mads/cache/snapshot.go, pkg/mads/cache/snapshot_test.go, pkg/mads/types.go, pkg/util/xds/cache.go, pkg/util/xds/cache_test.go
* add a custom version of `SnapshotCache` that supports arbitrary xDS resources
=> kuma-cp: add a custom version of SnapshotCache that supports arbitrary xDS resources

CHANGELOG.md, pkg/util/xds/versioner.go, pkg/util/xds/versioner_test.go
* add generic versioner for xDS resources
=> kuma-cp: add generic versioner for xDS resources

CHANGELOG.md, pkg/util/xds/watchdog_callbacks.go
* add a generic watchdog for xDS streams
=> kuma-cp: add a generic watchdog for xDS streams

CHANGELOG.md, api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, go.mod, go.sum, pkg/core/resources/apis/mesh/dataplane_helpers.go, pkg/core/resources/apis/mesh/dataplane_helpers_test.go, pkg/core/xds/resource.go, pkg/core/xds/resource_test.go, pkg/mads/generator/assignments.go, pkg/mads/generator/assignments_test.go, pkg/mads/generator/generator_suite_test.go, pkg/mads/generator/interfaces.go, pkg/mads/reconcile/interfaces.go, pkg/mads/reconcile/reconcile_suite_test.go, pkg/mads/reconcile/reconciler.go, pkg/mads/reconcile/snapshot_generator.go, pkg/mads/reconcile/snapshot_generator_test.go, pkg/mads/server/components.go, pkg/mads/server/grpc.go, pkg/mads/server/mads.go, pkg/mads/server/server.go, pkg/util/xds/watchdog_callbacks.go, pkg/xds/server/snapshot_generator_test.go
* kuma-cp: generate `MonitoringAssignment` for each `Dataplane` in a Mesh
=> kuma-cp: generate MonitoringAssignment for each Dataplane in a Mesh

CHANGELOG.md, pkg/api-server/catalog_ws_test.go, pkg/catalog/types.go, pkg/config/api-server/catalog/config.go, pkg/core/bootstrap/autoconfig.go, pkg/core/bootstrap/autoconfig_test.go
* advertise `MonitoringAssignment` server via `API Catalog`
=> kuma-cp: advertise MonitoringAssignment server via API Catalog

CHANGELOG.md, app/kuma-prometheus-sd/cmd/run.go, app/kuma-prometheus-sd/cmd/run_test.go, app/kuma-prometheus-sd/pkg/discovery/xds/xds.go, app/kuma-prometheus-sd/pkg/util/go-kit/log/log.go, go.mod, go.sum, pkg/mads/client/client.go, vendor/README.md, vendor/github.com/prometheus/prometheus/discovery/manager.go, vendor/github.com/prometheus/prometheus/discovery/targetgroup/targetgroup.go, vendor/github.com/prometheus/prometheus/documentation/examples/custom-sd/adapter/adapter.go, vendor/github.com/prometheus/prometheus/go.mod, vendor/github.com/prometheus/prometheus/util/strutil/strconv.go
* implement xDS client and integrate with `Prometheus` via `file_sd` discovery
=> kuma-prometheus-sd: implement xDS client and integrate with `Prometheus` via `file_sd` discovery

.circleci/config.yml
* exclude `clang-format` from CI builds due to temporary issues with LLVM's APT repository
=> ci: exclude `clang-format` from CI builds due to temporary issues with LLVM's APT repository

CHANGELOG.md, app/kuma-prometheus-sd/cmd/run.go, pkg/util/os/fs.go
* check write permissions on the output dir
=> kuma-prometheus-sd: check write permissions on the output dir

CHANGELOG.md, app/kuma-prometheus-sd/pkg/discovery/xds/config.go, app/kuma-prometheus-sd/pkg/discovery/xds/converter.go, app/kuma-prometheus-sd/pkg/discovery/xds/converter_test.go, app/kuma-prometheus-sd/pkg/discovery/xds/handler.go, app/kuma-prometheus-sd/pkg/discovery/xds/stream.go, app/kuma-prometheus-sd/pkg/discovery/xds/xds.go, app/kuma-prometheus-sd/pkg/discovery/xds/xds_suite_test.go
* support `MonitoringAssignments` with arbitrary `Target` labels (rather than only `__address__`)
=> kuma-prometheus-sd: support MonitoringAssignments with arbitrary `Target` labels (rather than only `__address__`)

app/kuma-prometheus-sd/README.md
* remove `refresh_interval` from the example Prometheus configuration (feedback from Prometheus maintainers)
=> docs: remove `refresh_interval` from the example Prometheus configuration

app/kuma-prometheus-sd/README.md
* fix broken link in the README of `kuma-prometheus-sd`
=> docs: fix broken link in the README of `kuma-prometheus-sd`

CHANGELOG.md, pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/config/plugins/resources/postgres/config.go, pkg/plugins/resources/postgres/store.go
* make maximum number of open connections to Postgres configurable
=> kuma-cp: make maximum number of open connections to Postgres configurable

CHANGELOG.md, go.sum, pkg/xds/bootstrap/template.go, pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml, pkg/xds/envoy/envoy_test.go, pkg/xds/envoy/rbac.go, pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/5-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/6-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/7-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/8-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/template-proxy/1-envoy-config.golden.yaml, pkg/xds/server/testdata/envoy-config.golden.yaml
Some metrics like this
```
envoy_inbound_192_168_16_2_39081rbac_shadow_denied{} 0
```
need some tuning so it will become usable, like this
```
envoy_rbac_shadow_denied{listener=inbound_192_168_16_2_39081}
```
I attach current metrics for statsd and prometheus output with the change
[example_prometheus_metrics.txt](https://github.com/Kong/kuma/files/4098539/example_prometheus_metrics.txt)
[example_statsd_metrics.txt](https://github.com/Kong/kuma/files/4098540/example_statsd_metrics.txt)
=> feat(kuma-cp) Reformat some Envoy metrics available in prometheus

.circleci/config.yml
The `deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch main` repo has now `clang-format-11` instead of `clang-format-10`. We can either install 11 or switch to repo with 10. I picked the first option and it seems to work.
=> ci(*) switch to clang format 11

CHANGELOG.md, Makefile.e2e.mk, pkg/util/xds/metric_sanitizer.go, pkg/util/xds/metric_sanitizer_test.go, pkg/xds/envoy/envoy.go, pkg/xds/envoy/envoy_test.go, pkg/xds/envoy/rbac.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/prometheus_endpoint_generator_test.go, pkg/xds/generator/proxy_template.go, pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/5-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/6-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/7-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/8-envoy-config.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/07.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/08.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/cluster-dots.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/template-proxy/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/template-proxy/1-proxy-template.input.yaml, pkg/xds/server/testdata/envoy-config.golden.yaml
Convertion from statsd to prometheus breaks when we have clusters with dots.
Example:
statsd:
```
cluster.backend.kuma-demo.svc_3001.assignment_stale: 0
```
prometheus
```
envoy_cluster_kuma_demo_svc_3001_assignment_stale{envoy_cluster_name="backend"}
```
There were several ways to fix it.
1) We could introduce `._.` suffix to clusters so you can skip extra part on Statsd and then build proper regex for Prometheus. 
2) We can replace every `.` in cluster name with `_`.
We picked second solution since it's less error prone. So the metric with this fix looks like following:
statsd:
```
cluster.backend_kuma-demo_svc_3001.assignment_stale: 0
```
prometheus
```
envoy_cluster_assignment_stale{envoy_cluster_name="backend_kuma-demo_svc_3001"}
```
We also have to sanitize metrics for StatsD as `:` …
=> Sanitize metrics

CHANGELOG.md, pkg/core/policy/matcher.go, pkg/xds/topology/healthchecks_test.go, pkg/xds/topology/router_test.go
Added ordering matching policies by modification time.
I think we should only resolve conflicts on final choice, otherwise we can eliminate valid policy.
=> feat(kuma-cp) order matching policies by modification time

CHANGELOG.md, app/kumactl/cmd/manage/ca/provided_test.go, pkg/core/ca/builtin/issuer/issuer.go, pkg/core/ca/provided/ca_cert_validator.go, pkg/core/ca/provided/ca_cert_validator_test.go, pkg/core/ca/provided/manager.go, pkg/core/ca/provided/manager_test.go, pkg/core/ca/provided/rest/webservice_test.go, pkg/core/managers/apis/mesh/mesh_manager_test.go, pkg/tls/cert.go, pkg/tls/keypair.go
* refactoring: refactor names and error messages in Provided CA Manager
* kuma-cp: validate certificates that users want to employ as a "provided" CA
=> kuma-cp: validate certificates that users want to employ as a "provided" CA

CHANGELOG.md, api/mesh/v1alpha1/dataplane.pb.go, api/mesh/v1alpha1/dataplane.proto, api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, pkg/core/resources/apis/mesh/dataplane_validator.go, pkg/core/resources/apis/mesh/dataplane_validator_test.go
* support IPv6 in `Dataplane` resource
=> kuma-api: support IPv6 in Dataplane resource

CHANGELOG.md, app/kuma-dp/pkg/dataplane/accesslogs/server.go
The main usecase of using TCP access logs is to use Logstash to send logs to Elasticsearch.
With current demo setup which is
```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
name: default
spec:
mtls:
ca:
builtin: {}
enabled: true
logging:
backends:
- name: logstash
format: |
{
"destination": "%KUMA_DESTINATION_SERVICE%",
"destinationAddress": "%UPSTREAM_HOST%",
"source": "%KUMA_SOURCE_SERVICE%",
"sourceAddress": "%KUMA_SOURCE_ADDRESS%",
"bytesReceived": "%BYTES_RECEIVED%",
"bytesSent": "%BYTES_SENT%"
}
tcp:
address: logstash.logging:5000
```
and
logstash config
```
input {
tcp {
port => 5000
codec => "json"
}
}
output{
loggly{
key => "API_KEY"
tag => "logstash"
}
}
```
We noticed that on K8S, Logstash has trouble parsing some logs (like 5-10% if you generate them quickly)
``` …
```
=> fix(kuma-dp) separate tcp access logs with a new line

app/kumactl/cmd/apply/apply.go
Fix typo in error message, change `200` to predefined constant for OK status code and sort imports.
=> Fix typo and get rid of magic number

CHANGELOG.md, pkg/plugins/discovery/k8s/controllers/pod_controller_test.go, pkg/plugins/discovery/k8s/controllers/pod_converter.go, pkg/plugins/discovery/k8s/controllers/pod_converter_test.go, tools/e2e/examples/docker-compose/kuma-example-installer.sh, tools/e2e/examples/minikube/kuma-demo/kuma-demo.yaml, tools/e2e/examples/minikube/kuma-routing/kuma-routing.yaml
* support `<port>.service.kuma.io/protocol` annotation on k8s as a way for users to indicate protocol of a service
=> kuma-cp: support `<port>.service.kuma.io/protocol` annotation on k8s as a way for users to indicate protocol of a service

CHANGELOG.md, pkg/core/resources/apis/mesh/dataplane_helpers.go, pkg/core/resources/apis/mesh/dataplane_validator.go, pkg/core/resources/apis/mesh/dataplane_validator_test.go, pkg/core/resources/apis/mesh/validators.go, pkg/core/resources/apis/mesh/validators_test.go
* validate value of `protocol` tag on a Dataplane resource
=> kuma-cp: validate value of `protocol` tag on a Dataplane resource

CHANGELOG.md, api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, pkg/core/permissions/matcher.go, pkg/core/permissions/matcher_test.go, pkg/core/resources/apis/mesh/dataplane_helpers.go, pkg/core/resources/apis/mesh/dataplane_helpers_test.go, pkg/mads/reconcile/snapshot_generator_test.go, pkg/plugins/discovery/k8s/controllers/pod_controller_test.go, pkg/plugins/discovery/k8s/controllers/pod_converter.go, pkg/plugins/discovery/k8s/controllers/pod_converter_test.go, pkg/xds/generator/inbound_proxy_generator_test.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/proxy_template.go, pkg/xds/server/snapshot_generator_test.go, pkg/xds/topology/outbound.go
Support the new format of the Dataplane across Kuma CP including scraping metrics from Gateway Dataplanes.
=> feat(kuma-cp) support new format of Dataplane

CHANGELOG.md, pkg/xds/envoy/listeners/http_inbound_route_configurer.go, pkg/xds/envoy/listeners/http_outbound_route_configurer.go, pkg/xds/envoy/listeners/http_outbound_route_configurer_test.go, pkg/xds/envoy/listeners/network_rbac_configurer_test.go, pkg/xds/envoy/names/resource_names.go, pkg/xds/envoy/routes/common_route_configuration_configurer.go, pkg/xds/envoy/routes/common_route_configuration_configurer_test.go, pkg/xds/envoy/routes/common_virtual_host_configurer.go, pkg/xds/envoy/routes/common_virtual_host_configurer_test.go, pkg/xds/envoy/routes/default_route_configurer.go, pkg/xds/envoy/routes/default_route_configurer_test.go, pkg/xds/envoy/routes/route_configuration_builder.go, pkg/xds/envoy/routes/routes_suite_test.go, pkg/xds/envoy/routes/virtual_host_builder.go, pkg/xds/envoy/routes/virtual_host_configurer.go, pkg/xds/envoy/routes/virtual_host_configurer_test.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/prometheus_endpoint_generator.go, pkg/xds/generator/protocol.go, pkg/xds/generator/protocol_private_test.go, pkg/xds/generator/protocol_test.go, pkg/xds/generator/proxy_template.go, pkg/xds/generator/resource_names.go, pkg/xds/generator/testdata/outbound-proxy/09.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/10.envoy.golden.yaml, tools/e2e/examples/docker-compose/kuma-example-installer.sh, tools/e2e/examples/minikube/kuma-routing/kuma-routing.yaml
* generate HTTP-specific outbound listeners for services tagged with `protocol: http`
=> kuma-cp: generate HTTP-specific outbound listeners for services tagged with `protocol: http`

CHANGELOG.md, app/kumactl/cmd/delete/delete.go, app/kumactl/cmd/delete/delete_test.go, app/kumactl/cmd/get/get.go, app/kumactl/cmd/get/get_traffic_traces.go, app/kumactl/cmd/get/get_traffic_traces_test.go, app/kumactl/cmd/get/testdata/get-traffic-traces.golden.json, app/kumactl/cmd/get/testdata/get-traffic-traces.golden.txt, app/kumactl/cmd/get/testdata/get-traffic-traces.golden.yaml, docs/cmd/kumactl/HELP.md, tools/docs/kumactl/gen_help.sh, tools/e2e/examples/minikube/kumactl_workflow.sh
Support for TrafficTrace in kumactl
=> feat(kumactl) TrafficTrace

CHANGELOG.md, api/mesh/v1alpha1/mesh.pb.go, api/mesh/v1alpha1/mesh.proto, pkg/api-server/mesh_ws_test.go, pkg/core/resources/apis/mesh/mesh_validator.go, pkg/core/resources/apis/mesh/mesh_validator_test.go, pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/generator_test.go, pkg/xds/bootstrap/testdata/bootstrap.tracing.yaml, pkg/xds/bootstrap/tracing.go, pkg/xds/bootstrap/tracing_test.go
Generate tracing config in Bootstrap config.
When we generate snapshot, we do traffic trace matching and get proper backend from the mesh. Then we convert this to bootstrap config.
Note: There is some bug in Envoy - Zipkin V2 version of the API is not compatible with Jaeger, because timestamp field in JSON is string and Jeager expects int64 there. We can look for it as a separate task and just use V1 for now which works fine.
=> feat(kuma-cp) Generate tracing config in Bootstrap config

CHANGELOG.md, pkg/core/resources/apis/mesh/mesh_validator.go, pkg/core/resources/apis/mesh/mesh_validator_test.go, pkg/envoy/accesslog/commands.go, pkg/envoy/accesslog/format.go, pkg/envoy/accesslog/format_parser.go, pkg/envoy/accesslog/format_parser_test.go, pkg/envoy/accesslog/interfaces.go, pkg/envoy/accesslog/placeholder_fragment.go, pkg/envoy/accesslog/placeholder_fragment_test.go
* add support for `%KUMA_*%` placeholders inside Envoy access log format
=> kuma-cp: add support for %KUMA_*% placeholders inside Envoy access log format

CHANGELOG.md, pkg/xds/envoy/listeners/access_log_configurer.go, pkg/xds/envoy/listeners/http_access_log_configurer.go, pkg/xds/envoy/listeners/http_access_log_configurer_test.go, pkg/xds/envoy/listeners/network_access_log_configurer.go, pkg/xds/envoy/listeners/util.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/proxy_template.go, pkg/xds/generator/testdata/outbound-proxy/09.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/10.envoy.golden.yaml
* generate HTTP-specific configuration of access log
=> kuma-cp: generate HTTP-specific configuration of access log

CHANGELOG.md, app/kuma-dp/pkg/dataplane/accesslogs/accesslogs_suite_test.go, app/kuma-dp/pkg/dataplane/accesslogs/factories.go, app/kuma-dp/pkg/dataplane/accesslogs/factories_private_test.go, app/kuma-dp/pkg/dataplane/accesslogs/handler.go, app/kuma-dp/pkg/dataplane/accesslogs/handler_private_test.go, app/kuma-dp/pkg/dataplane/accesslogs/helper_test.go, app/kuma-dp/pkg/dataplane/accesslogs/interfaces.go, app/kuma-dp/pkg/dataplane/accesslogs/sender.go, app/kuma-dp/pkg/dataplane/accesslogs/server.go
* extend embedded gRPC Access Log Server to support the entire Envoy access log format
=> kuma-dp: extend embedded gRPC Access Log Server to support the entire Envoy access log format

CHANGELOG.md, pkg/plugins/discovery/k8s/controllers/pod_converter.go, pkg/plugins/discovery/k8s/controllers/pod_converter_test.go, pkg/plugins/discovery/k8s/util/util.go, pkg/plugins/discovery/k8s/util/util_test.go
* remove the requirement to a `Pod` to explicitly list container ports in a case where a `Service` defines target port by number
=> fix: remove the requirement to a `Pod` to explicitly list container ports in a case where a `Service` defines target port by number

CHANGELOG.md, app/kuma-injector/pkg/injector/injector.go, app/kuma-injector/pkg/injector/injector_test.go, app/kuma-injector/pkg/injector/metadata/annotations.go, app/kuma-injector/pkg/injector/testdata/inject.10.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.10.input.yaml, app/kuma-injector/pkg/injector/testdata/inject.11.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.11.input.yaml
* add support for `kuma.io/sidecar-injection: disabled` annotation on Pods to let users selectively opt out of side-car injection
=> kuma-injector: add support for `kuma.io/sidecar-injection: disabled` annotation on Pods to let users selectively opt out of side-car injection

CHANGELOG.md, app/kumactl/cmd/apply/apply.go, pkg/core/resources/model/resource.go, pkg/mads/generator/assignments.go, pkg/mads/generator/assignments_test.go, pkg/plugins/common/k8s/k8s_suite_test.go, pkg/plugins/common/k8s/names.go, pkg/plugins/common/k8s/names_test.go, pkg/plugins/resources/k8s/store.go, pkg/plugins/resources/k8s/store_test.go, pkg/plugins/resources/memory/store.go, pkg/plugins/resources/postgres/store.go, pkg/plugins/resources/remote/unmarshalling.go, pkg/plugins/secrets/k8s/store.go, pkg/test/resources/model/resource.go, pkg/xds/topology/router.go
* include `k8s` namespace into a set of labels that describe a given `Dataplane` to `Prometheus`
=> kuma-cp: include k8s namespace into a set of labels that describe a given Dataplane to Prometheus

docs/proposals/L7-protocols.md
* add proposal how users should indicate application protocol of a service
=> docs: add proposal how users should indicate application protocol of a service

go.mod
`make dev/install/ginkgo` fails with 
```
go: gopkg.in/fsnotify.v1@v1.4.8: go.mod has non-....v1 module path "github.com/fsnotify/fsnotify" at revision v1.4.8
```
As a workaround added `replace` to `go.mod` file
Related issue: https://github.com/onsi/ginkgo/issues/650
=> go.mod: add replace for fsnotify dependency

CHANGELOG.md, app/kumactl/cmd/apply/apply.go, app/kumactl/cmd/apply/apply_test.go, app/kumactl/cmd/apply/testdata/apply-dataplane-template.yaml, docs/cmd/kumactl/HELP.md
Provide support of `--dry-run` mode to print out effective resources after all variables have been resolved
* kumactl apply: add support of --dry-run flag
Fix https://github.com/Kong/kuma/issues/615
=> kumactl apply: add support of --dry-run flag

CHANGELOG.md, pkg/core/logs/matcher_test.go, pkg/core/policy/matcher.go, pkg/core/resources/apis/mesh/dataplane_helpers.go, pkg/xds/generator/proxy_template.go, pkg/xds/generator/transparent_proxy_generator_test.go
For TrafficLog, we configure Dataplanes that match sources to log requests for a matching destination. We also want to log now the requests for external services. Such requests with transparent proxying (only on K8S for now) goes through `pass_through` L4 cluster and `catch_all` listener, therefore we want to configure such listener with access logs.
This will only be placed when in the destination section we will have the `*`.
In the future, this will be improved with more sophisticated handling of external services that will let apply L7 policies/metrics/logging etc.
=> feat(kuma-cp) log external services

CHANGELOG.md, app/kuma-injector/pkg/injector/injector.go, app/kuma-injector/pkg/injector/testdata/inject.01.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.02.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.03.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.04.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.05.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.06.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.07.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.08.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.09.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.11.golden.yaml
`kuma-init` didn't set `runAsUser` and `runAsGroup` explicitly, that's why pod-level securityContext could override them.
* Explicitly set `runAsUser` and `runAsGroup` to 0.
Fix https://github.com/Kong/kuma/issues/571
=> fix(injector) explicitly set parameters in securityContext

Makefile
I was following the steps of developers guide and faced issues with Kind v0.5.1.
The command `kind load ...` returned exit code 126 and nothing more.
=> chore(conf) update Kind version up to v0.7.0

CHANGELOG.md, app/kumactl/cmd/get/get_meshes.go, app/kumactl/cmd/get/get_meshes_test.go, app/kumactl/cmd/get/testdata/get-meshes.golden.json, app/kumactl/cmd/get/testdata/get-meshes.golden.txt, app/kumactl/cmd/get/testdata/get-meshes.golden.yaml
Closes #629.
Goes in hand with https://github.com/Kong/kuma-website/pull/158
=> chore(kumactl): merge mTLS and CA status into one column, closes #629

pkg/xds/envoy/listeners/network_access_log_configurer.go, pkg/xds/envoy/listeners/network_access_log_configurer_test.go, pkg/xds/generator/testdata/outbound-proxy/09.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/10.envoy.golden.yaml, pkg/xds/generator/transparent_proxy_generator_test.go
Add response flag to the default logging format.
Response flag for HTTP logging is already in place.
=> feat(kuma-cp) add response flag to default format

CHANGELOG.md, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap_test.go, pkg/plugins/discovery/k8s/controllers/pod_controller_test.go, pkg/plugins/discovery/k8s/controllers/pod_converter.go, pkg/plugins/discovery/k8s/controllers/pod_converter_test.go
This change covers a couple of things:
* Provide more descriptive error message in Kuma DP on K8S when Pod was not converted to Dataplane in K8S
* Prevent creating a Dataplane with Headless Service. Otherwise other dataplanes will create outbound listeners to it and they will fail with doing so, because outbound address is not valid.
* Provide a message suggesting what can be done with such situation (either change the service or exclude Pod from the mesh)
=> chore(*) prevent dataplane creation with a headless services and provide more descriptive error message on pod converter error

CHANGELOG.md, app/kumactl/cmd/root.go, docs/cmd/kumactl/HELP.md
* added shorthand message for mesh argument in kumactl
Fix #662
added the shorthand name for mesh argument
* Added shorthand name for mesh argument in kumactl
Fix #662
Open Question:
We don't have a test for `inspect dataplane` with mesh name other than the default name. Is it worth adding?
=> fix(kumactl) added shorthand command name for mesh

CHANGELOG.md, app/kuma-injector/pkg/injector/injector.go, app/kuma-injector/pkg/injector/testdata/inject.01.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.02.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.03.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.04.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.05.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.06.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.07.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.08.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.09.golden.yaml, app/kuma-injector/pkg/injector/testdata/inject.11.golden.yaml
`kuma-dp` refuses to work on Kind after updating Envoy up to 1.13.1, current PR fixes that issue
Readiness and liveness probes didn't work as expected and failed with: `Readiness probe failed: wget: can't connect to remote host: Connection refused`.
For some reason, `localhost` resolves to `127.0.0.1` on envoy-alpine 1.12.2 and resolves to `::1` on further versions.
According to envoy source code, admin server listener starts at `0.0.0.0:9901` so it binds to IPv4 interface. So in order to avoid ambiguous behavior, makes sense to change localhost to 127.0.0.1
=> fix(injector) change local address for probes

GOVERNANCE.md
I am very excited to introduce **open governance** guidelines for Kuma and a clear path for third-party contributors to become maintainers of the project!
⭐️ As part of this effort we will also start scheduling **bi-weekly community calls** on Kuma to determine the roadmap of the project, high-priority items and more generally to create an inclusive and diverse collaborative community around Kuma. 
I will update this PR with more information about this in the following days.
=> docs(governance): introducing open-governance to the project

Makefile.dev.mk, go.mod, go.sum
In our makefile we had
```
go get -u github.com/onsi/ginkgo/ginkgo
```
which means that on every `make dev/tools` run, we update Ginkgo to the newest version which may not be reliable.
In this case Ginkgo upgraded `github.com/golang/protobuf` which broke our code
=> chore(kuma-cp) do not upgrade ginkgo/gomega with every dev/tools run

CHANGELOG.md, pkg/api-server/read_only_resource_endpoints_test.go, pkg/api-server/resource_endpoints.go, pkg/api-server/server.go, pkg/plugins/resources/remote/store.go
When kuma-cp is run in Kubernetes mode, all the changes should happen through `kubectl`. Send an explanation in the response body, so clients (i.e. `kumactl` or the HTTP API) can show it to the user.
* feat(kuma-cp) friendly response in K8s mode
* feat(kumactl) do not show error code 405 on apply/delete
Fix #165
=> feat(kuma-cp) friendly response in K8s mode

tools/e2e/examples/docker-compose/docker-compose.yaml, tools/e2e/examples/minikube/kuma-routing/kuma-routing.yaml, tools/releases/distros.sh, tools/releases/dockerfiles/Dockerfile.kuma-dp
Just increment the version, check that `kuma-demo` works on `Kind`. 
Looks like no additional adjustments required
=> chore(kuma-dp) upgrade Envoy up to v1.14.1

pkg/xds/envoy/listeners/fault_injection_configurer_test.go, pkg/xds/envoy/tags/match.go, pkg/xds/envoy/tags/match_test.go, pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml
I thought the problem in envoy escaping of dot in regex. But escaping happens only for showing config_dump. The real problem was in the way safe_regex works. It checks that the whole header matches regex (not just its part).
So I updated regex and tests.
=> fix: fault injection regex

pkg/xds/generator/prometheus_endpoint_generator.go, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
Kuma could not scrape metrics from Gateway dataplane on K8S. The problem was that we were generating listeners with transparent proxy mode (bindToPort: false) but we do not enable transparent proxying on inbound connections with Gateways. The solution is to generate listeners without transparent proxy mode.
=> fix(kuma-cp) turn off transparent proxy for prometheus scraping

pkg/plugins/secrets/k8s/store.go, pkg/plugins/secrets/k8s/store_test.go
When retrieving Secret from K8S we need to check if mesh matches manually, otherwise Secrets won't be Mesh scoped.
I also test case that Secret without explicit mesh label works (just in case)
=> feat(kuma-cp) block retrieving secrets from another mesh

pkg/core/xds/types.go, pkg/sds/server/auth_callbacks.go, pkg/xds/sync/dataplane_sync_tracker.go, pkg/xds/sync/dataplane_sync_tracker_test.go
With ADS the relation was 1 DP = 1 gRPC stream. With SDS that uses Dataplane Sync Tracker the relation is that 1 DP can open many streams. We want to start only one watchdog for DP so we need to which DP the stream belongs. When closing the stream we need to cancel watchdog only if DP has no streams left.
=> feat(kuma-cp) dp sync tracker runs only one watchdog

pkg/core/resources/apis/mesh/dataplane_validator.go, pkg/core/resources/apis/mesh/dataplane_validator_test.go, pkg/core/resources/apis/mesh/fault_injection_validator_test.go, pkg/core/resources/apis/mesh/validators.go
Allow slash validation so standard K8S tags are supported
Fix #754
=> fix(kuma-cp) allow slash validation so standard K8S tags are supported

go.mod, go.sum, pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/core/bootstrap/bootstrap.go, pkg/core/managers/apis/dataplaneinsight/dataplane_insight_manager.go, pkg/core/managers/apis/dataplaneinsight/dataplane_insight_manager_suit_test.go, pkg/core/managers/apis/dataplaneinsight/dataplane_insight_manager_test.go
Today we don't limit the number of subscriptions that could be stored in DataplaneInsight and there is no way to disable it. 
This PR introduces the ability to configure that functionality. 
Here is new config section:
```json
"metrics": {
"dataplane": {
"enabled": true,
"subscriptionLimit": 10
}
}
```
Note: `Enable` flag works quite naive and straightforward - it doesn't prevent `dataplaneInsightSink` from Start, just cut off all subscriptions before adding them to storage. That was the simplest way to implement, but if needed I can provide full fair `Enable` support
=> feat: limit number subscription

docs/proposals/circuit-breaker.md
An initial version of the proposal for the new policy "CircuitBreaker"
=> feat(kuma-cp): CircuitBreaker proposal

pkg/plugins/discovery/k8s/controllers/pod_converter.go, pkg/plugins/discovery/k8s/controllers/pod_converter_test.go, pkg/plugins/discovery/k8s/controllers/testdata/07.dataplane.yaml, pkg/plugins/discovery/k8s/controllers/testdata/07.pod.yaml, pkg/plugins/discovery/k8s/controllers/testdata/07.services-for-pod.yaml
Some time ago overrides for port and path was done using `prometheus.io` annotations (Kuma prometheus annotations were converted to prometheus) because Kuma DP discovery was based on `prometheus.io` annotations. Later we changed this so discovery of Kuma DP is based on `kuma-prometheus-sd` and we leave `prometheus.io` annotations for apps.
In the process of this change, we lost the ability to override port and path of Kuma DP metrics on Pod. This PR restores this functionality, so we convert Kuma Metrics annotations to DP config.
Already there
=> chore(kuma-cp) prometheus overrides on Kubernetes

pkg/util/proto/marshal_any_test.go, pkg/xds/envoy/clusters/client_side_mtls_configurer.go, pkg/xds/envoy/clusters/client_side_mtls_configurer_test.go, pkg/xds/envoy/clusters/lb_subset_configurer.go, pkg/xds/envoy/clusters/lb_subset_configurer_test.go, pkg/xds/envoy/endpoints/endpoints.go, pkg/xds/envoy/endpoints/endpoints_test.go, pkg/xds/envoy/listeners/tcp_proxy_configurer.go, pkg/xds/envoy/metadata.go, pkg/xds/envoy/metadata_test.go, pkg/xds/envoy/routes/default_route_configurer.go, pkg/xds/envoy/tls.go, pkg/xds/envoy/tls/sni.go, pkg/xds/envoy/tls/sni_test.go, pkg/xds/envoy/tls/tls_suite_test.go, pkg/xds/envoy/types.go, pkg/xds/generator/direct_access_proxy_generator.go, pkg/xds/generator/ingress_generator.go, pkg/xds/generator/ingress_generator_test.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/testdata/ingress/01.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
This PR introduces support for many tag in Ingress - meaning you can apply TrafficRoute like this
```
type: TrafficRoute
mesh: default
name: tr-1
sources:
- match:
service: gateway
destinations:
- match:
service: backend
conf:
- weight: 80
destination:
service: backend
cluster: "1"
- weight: 20
destination:
service: backend
cluster: "2"
```
or this (when version: 2 is in different cluster)
```
type: TrafficRoute
mesh: default
name: tr-1
sources:
- match:
service: gateway
destinations:
- match:
service: backend
conf:
- weight: 100
destination:
service: backend
version: "2"
```
Will be a part of Multi Cluster docs/demo. From user perspective is just a regular TrafficRoute
=> feat(kuma-cp) Support many tags in Ingress

api/mesh/v1alpha1/metrics.pb.go, api/mesh/v1alpha1/metrics.proto, pkg/xds/generator/prometheus_endpoint_generator.go, pkg/xds/generator/prometheus_endpoint_generator_test.go
We introduced mTLS Metrics in Kuma 0.5.1, but we wanted to skipMTLS by default to not break upgrades from 0.5.0 to 0.5.1.
With the upcoming 0.6.0 we are ready to make this change.
=> chore(kuma-cp) Change default skipMTLS flag

api/mesh/v1alpha1/dataplane_helpers.go, pkg/dns/sync_test.go, pkg/dns/vips_allocator.go, pkg/xds/server/components.go, pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go, pkg/xds/topology/vip_outbounds.go
Outbound generator and DNS service map should take into account ingress.
Internal only
=> fix(kuma-cp) outbound generation and dns service map

pkg/kds/client/sink.go, pkg/kds/client/stream.go, pkg/kds/global/components.go, pkg/kds/global/components_test.go, pkg/kds/remote/components.go, pkg/kds/server/kds.go, pkg/kds/server/server_test.go, pkg/kds/types.go, pkg/kds/util/resource.go, pkg/test/kds/samples/resources.go, pkg/test/kds/setup/server.go
Sync DP insights.
DP insights does not have tags so I needed to add cluster ID into ControlPlane#identifier in `DiscoveryResponse`
Internal
=> feat(kuma-cp) sync dataplane insights

pkg/config/clusters/clusters.go, pkg/core/runtime/component/resilient.go, pkg/kds/client/client.go, pkg/kds/global/components.go, pkg/kds/remote/components.go, test/framework/k8s_controlplane.go
Deduplicate Ingress resources on the Global and small fixes.
* Fix bug in a resilient component 
* Set Port for Ingress on the Global (could cause a problem with a NodePort)
* Rename schema to `grpc/grpcs`, get rid of schema in Ingress' address
Fix #XXX
=> fix(kuma-cp) dedup Ingresses, small fixes

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/core/bootstrap/bootstrap.go, pkg/core/bootstrap/bootstrap_test.go, pkg/core/managers/apis/mesh/mesh_helpers.go, pkg/plugins/runtime/k8s/controllers/namespace_controller.go, pkg/plugins/runtime/k8s/controllers/namespace_controller_test.go, pkg/plugins/runtime/k8s/plugin.go
Adds the ability to skip default mesh creation, which will unblock using Helm to manage the default mesh (as noted in #887). Also removes the ability to customize the default mesh through configuration.
* adds config option `defaults.skipDefaultMeshCreation`, which defaults to `false`
* adds corresponding env variable `KUMA_DEFAULTS_SKIP_DEFAULT_MESH_CREATION`
* removes config option `defaults.mesh`
* adds corresponding flag in the `NamespaceReconciller` 
* adds helper method `FetchDefaultMeshIfExists` to faciliate easier testing 
* adds tests for default mesh creation and skipping in the `NamespaceReconciller` 
Fix #887
N/A
=> feat(*) add flag to skip default mesh creation, remove config option

pkg/core/resources/apis/mesh/dataplane_helpers.go, pkg/core/resources/apis/mesh/dataplane_helpers_test.go, pkg/core/resources/apis/mesh/dataplane_validator_test.go, pkg/plugins/runtime/k8s/webhooks/service_validator_test.go, pkg/xds/envoy/clusters/http2_configurer.go, pkg/xds/envoy/clusters/http2_configurer_test.go, pkg/xds/generator/inbound_proxy_generator.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/protocol.go, pkg/xds/generator/protocol_private_test.go, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/cluster-dots.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
Let's assume connection
```
web <--C1--> web's Envoy <--C2--> backend's Envoy <--C3--> backend
```
This PR sets HTTP/2 by default for connections between Envoys (C2 in the above example).
It also allows to set a `protocol: http2` tag for dataplane, so for example if such tag is set for `backend`, the C3 will also be on http2.
HTTP/2 support in Envoy can be enabled by setting `http2ProtocolOptions: {}` on a `cluster`.
SSL is recommended for HTTP/2, but it's not required. Connections between Envoy works on HTTP/2 without mTLS.
If `backend` is on HTTP/2 and there is no option to resign from TLS, TLS context can be configured with new ProxyTemplate modifications.
Fix #889
https://github.com/kumahq/kuma-website/pull/239
=> feat(kuma-cp) support for http2

app/kuma-cp/cmd/run.go, pkg/xds/server/components.go, pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go
We have to disable the generation of ingress endpoints if mTLS is off. Otherwise, some requests will be load balanced to Ingress and dropped (Ingress always require mTLS for work).
* [Fix] disable KDS in Standalone mode
Fix #XXX
=> chore(kuma-cp) disable ingress generation if mTLS is off

test/e2e/kuma_deploy_multi_apps_test.go
Policies might take some short period of time to be applied and propagated to Envoy. That's why all `curl` checks have to be done using `Eventually `
=> feat(kuma-cp) e2e stabilization

mk/dev.mk, mk/e2e.new.mk, mk/run.mk, mk/test.mk, test/dockerfiles/Dockerfile.universal, tools/releases/distros.sh
Parametrize makefiles and tools for more flexibility of running it.
=> chore(*) parametrize makefiles and tools

deployments/charts/kuma/templates/pre-delete-webhooks.yaml, deployments/charts/kuma/templates/pre-install-patch-namespace-job.yaml
The problem was that some K8S distros (especially in clouds) has `+` in minor version
```
❯❯❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
therefore `bitnami/kubectl` image in hooks could not be downloaded
```
Failed to apply default image tag "bitnami/kubectl:1.14+": couldn't parse image reference …
```
=> fix(kuma-cp) remove + from minor version of Kubernetes so bitnami kubectl can be fetched

deployments/charts/kuma/values.yaml
Although I understand that it is very likely that someone who uses HELM to deploy Kuma will also use HELM to manage Kuma CRDs, I still think it's better to create a Mesh by default. A couple of days ago I was testing charts and I was confused why sidecar was not added. It turned out that it was lack of the mesh.
I think behavior should be consistent with kumactl install control-plane which creates a default Mesh.
CC: @austince you may need to change this manually after charts upgrade
=> feat(kuma-cp) change skipMeshDefault to false in HELM charts

mk/test.mk, pkg/plugins/resources/k8s/native/api/v1alpha1/zone_insight_types_test.go
A side effect of the `test` make target unification, was that even if something in the listed test fails, only the last (and biggest) one was taken into account. We then overlooked a failing Zone Insights type test failure, which was easy to fix knowing that the resources are of Cluster scope and therefore does not have a namespace.
=> fix(*) zone insight failing test

deployments/charts/kuma/Chart.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/_helpers.tpl, deployments/charts/kuma/templates/cp-global-sync-service.yaml, deployments/charts/kuma/templates/cp-service.yaml, deployments/charts/kuma/templates/ingress-service.yaml, deployments/charts/kuma/values.yaml, test/framework/k8s_cluster.go
Fix #960
Instead of useNodePort you can now specify type. Additionaly you can add your own annotations.
=> feat(kuma-cp) pick service type and add custom annotations

pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml
Add support for HTTP/2 and gRPC on outbound proxy generator.
Fix #949
=> feat(kuma-cp) support HTTP/2 and gRPC on outbound

app/kumactl/cmd/completion/testdata/zsh.golden, app/kumactl/cmd/install/install_control_plane.go, app/kumactl/cmd/install/install_control_plane_test.go, docs/cmd/kumactl/HELP.md, pkg/core/resources/apis/system/zone_validator.go, pkg/core/resources/apis/system/zone_validator_test.go, test/framework/k8s_cluster.go
Better validation for zone address in zone resource (detect URL) and global address on CP install
=> feat(kuma-cp) validate zone address and global address

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/core/bootstrap/bootstrap.go, pkg/core/managers/apis/dataplane/dataplane_manager_suit_test.go, pkg/core/managers/apis/dataplaneinsight/dataplane_insight_manager_suit_test.go, pkg/core/managers/apis/zoneinsight/zone_insight_manager.go, pkg/core/managers/apis/zoneinsight/zone_insight_manager_suit_test.go, pkg/core/managers/apis/zoneinsight/zone_insight_manager_test.go
Add a ZoneInsight manager, so that we can enforce limits of the number of the subscriptions.
=> fix(kuma-cp) zone insights manager and limits

test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/kumactl.go
Add option to add custom values to `kumactl install`
=> feat(test) parametrize kuma deploy

pkg/plugins/discovery/k8s/controllers/pod_controller.go, pkg/plugins/discovery/k8s/controllers/pod_controller_test.go, pkg/plugins/discovery/k8s/util/util.go, pkg/plugins/discovery/k8s/util/util_test.go
Problem described in #977
The solution is to ignore all services without selector since this is an indication that it is a special service with endpoints managed by an external process.
Also added a comment on why we are picking Service port without matching containerPort since it was confusing to me.
Fix #977
- Nothing to change, it's an internal mechanism.
=> fix(kuma-cp) ignore services without selectors

deployments/charts/kuma/Chart.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cni-daemonset.yaml, deployments/charts/kuma/templates/cp-deployment.yaml, deployments/charts/kuma/values.yaml
Signed-off-by: austin ce <austin.cawley@gmail.com>
Adds `nodeSelector` fields to Kuma CP and CNI pod specs, and allows augmenting them via Helm values. Technically a breaking change, and moving the CNI pod selector out of the beta label.  
* Add `controlPlane.nodeSelector` option with default `{ kubernetes.io/os: linux, kubernetes.io/arch: amd64 }` 
* Add `cni.nodeSelector` option with default `{ kubernetes.io/os: linux, kubernetes.io/arch: amd64 }` 
Fix #988
=> feat(deployments) specify nodeSelectors for CP and CNI pods

pkg/admin-server/server.go, pkg/core/bootstrap/bootstrap.go, pkg/sds/auth/universal/auth_test.go, pkg/tokens/builtin/components.go, pkg/tokens/builtin/issuer/issuer.go, pkg/tokens/builtin/issuer/signing_key.go, test/e2e/kuma_deploy_hybrid_kube_global_test.go, test/e2e/kuma_deploy_hybrid_test.go, test/e2e/kuma_deploy_universal_test.go, test/e2e/tracing_universal_test.go, test/framework/constants.go, test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/k8s_clusters.go, test/framework/k8s_controlplane.go, test/framework/setup.go, test/framework/universal_cluster.go, test/framework/universal_clusters.go, test/framework/universal_controlplane.go
Dataplane Token is an identity that we give to Dataplanes and verify it on the CP on Universal deployments. On K8S we use service account tokens. Dataplane Token is a JWT token signed by Signing Token that is generated when CP starts.
With multizone setup when Global is on K8S and you connect Remote Universal, KDS syncs all the secrets from Global to Remote. Since Global is a centralized single source of truth for everything other than Dataplanes, if Secret is not available on Global, it will be removed from the Remote.  What happened is that we were generating token on Remote but not on Global so it was removed from Remote. This PR fixes this behavior.
This time we generate Signing Key with a multizone setup only on Global but in all environments. Even if Global is on K8S, we don't know …
=> fix(kuma-cp) signing token in multizone

.circleci/config.yml
Disable testing against Kubernetes 1.13. 
#990 introduces NodeSelectors for CP and CNI pods in the Helm Charts. #989 makes the Helm Charts the default installation templating for `kumactl install control-plane`. 
Kubernetes 1.14 introduces `kubernetes.io/os` and `kubernetes.io/arch` and [deprecates](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#deprecations) `beta.kubernetes.io/os` and `beta.kubernetes.io/arch`. This effectively makes Kuma Helm Charts and now `kumactl install control-plane` unusable on Kubernetes versions prior to 1.14, as the deployment hangs trying to find nodes labelled with  `kubernetes.io/os` and `kubernetes.io/arch`, while such does not exist (as 1.13 uses the `beta` labels).
As the `beta` labels are not supported at all since …
=> fix(*) drop k8s 1.13 support

DEVELOPER.md
Corrected setting PATH environment variable for make build/kumactl in DEVELOPER.md
In [developer doc](https://github.com/kumahq/kuma/blob/master/DEVELOPER.md),   step `export PATH=`pwd`/build/artifacts/kumactl:$PATH` does not match with the current value generated in make file for eg artifacts-linux-amd64 is generated instead of artifacts
Present: export PATH=`pwd`/build/artifacts/kumactl:$PATH
This PR: export PATH=`pwd`/build/artifacts-$(go env GOOS)-$(go env GOARCH)/kumactl:$PATH
Documentation https://github.com/kumahq/kuma/blob/master/DEVELOPER.md
https://github.com/kumahq/kuma/blob/master/DEVELOPER.md
=> Fixed set PATH environment variable for make build/kumactl in DEVELOPER.md

pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.01.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.02.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.03.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.04.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.05.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.06.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.07.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.08.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.09.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.11.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.12.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.13.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.14.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.15.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.16.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.17.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.18.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.19.golden.yaml
Use envoy's `/ready` endpoint for health-checks of `kuma-sidecar`.
* Added `/ready` endpoint to kuma-injector's `LivenessProbe` and `ReadinessProbe` config. 
Fix #359
=> feat(kuma-injector) health-check endpoint

OWNERS.md
Based on a discussion within the current maintainers, here is a proposal for Austin Cawley-Edwards (@austince) to officially join the project as a new maintainer.
He has demonstrated a strong commitment to the project by leading the efforts to adopt Helm as the main templating engine to deploy Kuma on Kubernetes. Here is a list of his most significant engagements so far:
* feat(deployments) add Helm chart for kuma #916
* feat(kumactl) merge install ingress into install control-plane #1038
* feat(kumactl) upgrade CRDs to apiextensions.k8s.io/v1 #890
He also was pro-active in the Kuma community Slack channels and is doing a presentation on his experience in adopting Kuma within their organisation/project.
According to our [GOVERNANCE.md](https://github.com/kumahq/kuma/blob/master/GOVERNANCE. …
=> chore(*) adding austince as a maintainer

app/kuma-dp/pkg/dataplane/accesslogs/server.go, pkg/kds/mux/server.go, pkg/mads/server/grpc.go, pkg/sds/server/grpc.go, pkg/xds/server/grpc.go
Makes sure the GRPC services are registered before the Listener is started.
Flaky SDS tests
https://app.circleci.com/pipelines/github/kumahq/kuma/4427/workflows/d996a2f4-a5b9-4dbf-8c4f-ab815afd0122/jobs/61040/parallel-runs/0/steps/0-107
=> fix(*) make sure the GRPC services are registered before listener

mk/check.mk, mk/e2e.new.mk, mk/kind.mk, mk/test.mk
Use `$(MAKE)` instead of `make` so we can use `make -j test/e2e`, this way K8S clusters are run in parallel.
=> chore(build) use make param to start kube clusters for e2e tests

pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_controller_test.go, pkg/plugins/runtime/k8s/plugin.go
Ingress should be only deployed in Kuma System namespace, otherwise anyone can deploy DP with `kuma.io/ingress: enabled` and act like an Ingress.
Users can still go and edit the Dataplane object adding ingress, but this is a broader problem. Users should not be able to touch Dataplane objects.
=> chore(kuma-cp) Ingress Dataplane on K8S can only be deployed in system namespace

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/plugins/runtime/k8s/config.go, pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/injector_test.go, pkg/plugins/runtime/k8s/webhooks/injector/probes.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.20.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.20.input.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.config.yaml
This PR introduces the capability to exclude individual pods from injection that match the given list of tags.
Use case:
On OpenShift when you use DeploymentConfig instead of Deployment, there is an additional Pod that does not match any Service, which is a requirement for Kuma. Now by default, we are excluding OpenShift Deployer Pods from Kuma injection.
Also, I added more logging to the injector
=> feat(kuma-cp) exclude pods that matches labels from injection

.github/dependabot.yml
Adds a Dependabot config file for `go.{mod,sum}` and all the release Dockerfiles. Updates are done on a weekly basis, could also change to daily or monthly.
Follow up from: https://github.com/kumahq/kuma/pull/1060#issuecomment-706409263
See: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
=> chore(*) add dependabot config

pkg/xds/envoy/listeners/http_access_log_configurer_test.go, pkg/xds/envoy/listeners/http_inbound_route_configurer_test.go, pkg/xds/envoy/listeners/http_outbound_route_configurer.go, pkg/xds/envoy/listeners/http_outbound_route_configurer_test.go, pkg/xds/envoy/listeners/prometheus_endpoint_configurer.go, pkg/xds/envoy/listeners/prometheus_endpoint_configurer_test.go, pkg/xds/envoy/routes/common_route_configuration_configurer.go, pkg/xds/envoy/routes/common_route_configuration_configurer_test.go, pkg/xds/generator/modifications/virtual_host.go, pkg/xds/generator/modifications/virtual_host_test.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/05.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/06.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/prometheus-endpoint/custom.envoy-config.golden.yaml, pkg/xds/generator/testdata/prometheus-endpoint/default-mtls.envoy-config.golden.yaml, pkg/xds/generator/testdata/prometheus-endpoint/default.envoy-config.golden.yaml
This PR changes that Routes for outbound listeners are send embedded in listeners instead of dynamically through RDS.
We already use embedded route in the inbound listener
RDS really makes sense when you have many routes to one listener and you change them a lot.
Right now we have 1 route per listener and we don't change it after we create it.
Listener does not need to wait for routes anymore (listener is warming before it receives routes through RDS)
This saves us extra discovery request/response and potential bugs of warming like this one #1012
Fix #1012 because there is no warming because of RDS anymore
I also turned `validateCluster` from Route as recommended in docs
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route.proto
_Users may wish to override the default behavior …
=> chore(kuma-cp) generate static outbound routes

pkg/xds/envoy/listeners/http_access_log_configurer_test.go, pkg/xds/envoy/listeners/http_inbound_route_configurer_test.go, pkg/xds/envoy/listeners/http_outbound_route_configurer.go, pkg/xds/envoy/listeners/http_outbound_route_configurer_test.go, pkg/xds/envoy/listeners/prometheus_endpoint_configurer.go, pkg/xds/envoy/listeners/prometheus_endpoint_configurer_test.go, pkg/xds/envoy/routes/common_route_configuration_configurer.go, pkg/xds/envoy/routes/common_route_configuration_configurer_test.go, pkg/xds/generator/modifications/virtual_host.go, pkg/xds/generator/modifications/virtual_host_test.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/prometheus-endpoint/custom.envoy-config.golden.yaml, pkg/xds/generator/testdata/prometheus-endpoint/default-mtls.envoy-config.golden.yaml, pkg/xds/generator/testdata/prometheus-endpoint/default.envoy-config.golden.yaml
=> chore(kuma-cp) generate static outbound routes (#1098)

.circleci/config.yml
Master workflow should not run on tags because it always fails.
=> chore(ci) skip master workflow for release commits

app/kuma-dp/cmd/run.go, app/kuma-dp/cmd/run_test.go, pkg/xds/bootstrap/components.go, pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/generator_test.go, pkg/xds/bootstrap/handler.go, pkg/xds/bootstrap/server_test.go, pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml
2 reasons
1) To be able to remove catalog request on kuma dp
2) overall client should be as thin as possible and validation should be done on the server side.
=> chore(kuma-dp) move token validation to server side

app/kuma-dp/cmd/run.go, app/kuma-dp/pkg/config/validate.go, app/kuma-dp/pkg/config/validate_test.go, pkg/api-server/auth_test.go
Validate the DP token in `kuma-dp`
=> fix(*) validate the token in kuma-dp

.circleci/config.yml, mk/dev.mk, pkg/plugins/resources/k8s/native/Dockerfile, tools/releases/dockerfiles/Dockerfile.kuma-init
Upgrading go 1.15.2 -> 1.15.5
[Changelog 1.15.3](https://github.com/golang/go/issues?q=milestone%3AGo1.15.3+label%3ACherryPickApproved)
[Changelog 1.15.4](https://github.com/golang/go/issues?q=milestone%3AGo1.15.4+label%3ACherryPickApproved)
[Changelog 1.15.5](https://github.com/golang/go/issues?q=milestone%3AGo1.15.5+label%3ACherryPickApproved)
=> chore(*) bump go 1.15.5

pkg/core/managers/apis/mesh/mesh_manager_test.go, pkg/defaults/mesh/traffic_permission.go, test/e2e/kuma_deploy_hybrid_test.go
We changed the scope of Traffic Permissions on K8S to Cluster, so we can drop the prefix.
=> chore(kuma-cp) drop default sufix on the default traffic permission

test/framework/interface.go, test/framework/universal_cluster.go
In e2e, add Environment setting option used in kuma-cp universal deployment
=> test(e2e) add env to deployment options

mk/e2e.new.mk, test/e2e/e2e_suite_test.go, test/e2e/externalservices_kubernetes_test.go, test/e2e/externalservices_universal_test.go, test/e2e/kuma_deploy_global_remote_test.go, test/e2e/kuma_deploy_hybrid_kube_global_test.go, test/e2e/kuma_deploy_hybrid_test.go, test/e2e/kuma_deploy_universal_test.go, test/e2e/kuma_helm_deploy_global_remote_test.go, test/e2e/kuma_helm_deploy_multi_apps_test.go, test/e2e/tracing_kubernetes_test.go, test/e2e/tracing_universal_test.go
When I'm developing and want to check if my code passes E2E I want to receive feedback as quickly as possible (exit after first failed test)
Additionally, if something is wrong, I don't want clusters to be gone, but I want to inspect them and current test deployment.
=> chore(ci) debug e2e test for quicker feedback loop

pkg/xds/envoy/listeners/tcp_proxy_configurer.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/generator/testdata/outbound-proxy/07.envoy.golden.yaml
Since 1.0 traffic is only routed when there is a TrafficRoute in the cluster. It is legal to remove it and see no traffic.
Before this PR, the Envoy config generation would fail, but what we want to do is to generate a config that does not route to the cluster.
My prediction is that 99% of cases when user will see this log is when they will delete TrafficRoute by accident therefore I'm putting a link in logs to the website where there will be a section with default TrafficRoute and an explanation that this will be required.
=> fix(kuma-cp) handle missing TrafficRoute

pkg/core/resources/manager/manager.go, pkg/insights/resyncer.go, pkg/plugins/resources/memory/store.go, pkg/plugins/runtime/k8s/controllers/mesh_controller.go
Two things
* Mesh resyncer was reacting on Mesh and MeshInsights events. That results in error messages when Mesh was deleted
* Mesh reconciller is executing MeshManager#Delete to delete secrets. Ideally, we should remove it completely and rely on ownership of secrets that we need to build (described #1137 ). Ignoring ErrorResourceNotFound should be enough for now.
=> chore(kuma-cp) handle mesh delete more gracefully

pkg/core/managers/apis/mesh/mesh_manager.go, pkg/defaults/mesh/mesh.go, pkg/defaults/mesh/mesh_suite_test.go, pkg/defaults/mesh/mesh_test.go, pkg/defaults/mesh/signing_key.go, pkg/defaults/mesh/traffic_permission.go, pkg/defaults/mesh/traffic_route.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go, test/e2e/kuma_helm_deploy_multi_apps_test.go, test/framework/interface.go, test/framework/k8s_cluster.go
Default Mesh resources are created only when a Mesh is created. Default Mesh is created using ResourceManager which is in charge of executing `CreateDefaultMeshResources`. At the same time, there is a K8S Controller that picks up new meshes and executes this method. To not double this effort I skipped the default mesh from K8S Controller.
The problem was that if someone uses SkipDefaultMesh and creates it manually, resources were not created.
Fix:
* Change `CreateDefaultMeshResources` to `EnsureDefaultMeshResources` which can handle a case that resources were already created
* Remove the if in K8S Controller
* Change HELM E2E test to use SkipDefaultMesh since it's a common case with HELM deployment
=> fix(kuma-cp) create default mesh resources when default mesh is skipped

pkg/plugins/runtime/k8s/webhooks/injector/injector_test.go, pkg/plugins/runtime/k8s/webhooks/injector/probes.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.23.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.23.input.yaml
Kubernetes supports named ports for probes. This PR adds support to such kinds of probes. 
Fix https://github.com/kumahq/kuma/issues/1216
=> fix(kuma-cp) resolve probe's named port before converting to virtual

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/config/multizone/kds.go, pkg/config/multizone/multicluster.go, pkg/config/xds/config.go, pkg/config/xds/testdata/default-config.golden.yaml, pkg/kds/server/components.go
Lower default flush intervals of Zone Insights and Dataplane Insights. We don't need to refresh the status that often, it's not critical for Kuma to function. Change it from 1s to 10s, to save an order of magnitude requests to the DB when there are many config changes.
Tradeoff - we will see DP online / offline and all stats changes with latency of 10s, not 1s.
I also parametrized Zone Insight since it was hardcoded.
=> chore(kuma-cp) change default flush intervals

pkg/api-server/dataplane_overview_endpoints.go, pkg/api-server/pagination.go, pkg/api-server/resource_endpoints.go, pkg/api-server/service_insight_endpoints.go, pkg/api-server/service_insight_endpoints_test.go, pkg/api-server/zone_overview_endpoints.go, pkg/core/resources/model/rest/resource.go
Expand ServiceInsight API so it returns `ServiceInsight` for the individual service. This makes GUI implementation much easier.
Just like the comment in the code says, we keep all services in one ServiceInsight for the Mesh but on the GUI and from the API perspective it's better to have one per service, so I expand the resources in the API.
In the future, we might change the internal `ServiceInsight` representation to 1 per Service. This way API will stay the same.
=> feat(kuma-cp) expand service insight endpoints

test/framework/universal_app.go
In the e2e test for Universal, make sure we always select the IPv4 addresses. IPv6 seems to be problematic for now.
=> test(e2e) make sure we use IPv4 addresses in Universal

pkg/core/resources/apis/mesh/fault_injection_validator.go, pkg/core/resources/apis/mesh/fault_injection_validator_test.go
FaultInjection source protocol is irrelevant. Remove the excessive check that it is `http`.
Fix #1281
=> fix(*) FaultInjection will not valide source protocol

pkg/plugins/runtime/k8s/probes/probe.go, pkg/plugins/runtime/k8s/probes/probe_test.go
Signed-off-by: Lennart Querter <lennart.querter@durstexpress.eu>
If liveness probe (or readiness) httpGet path does not begins with "/", we add it automatically.
Fix #1288
=> fix(kuma-dp) HttpGet readiness (and liveness) probe path gets a "/" prepended if not supplied

pkg/core/resources/apis/mesh/retry_validator.go, pkg/core/resources/apis/mesh/retry_validator_test.go
There were two bugs, one was happening when there was only seconds in
timeout durations provided (`1s`) as the validator was not checking if
seconds are provided and assuming that if nanoseconds field is empty, it
means the value is equal 0 and then rejecting valid values.
The second bug was that we were not validating `maxInterval` values of
the backOff properties
=> fix(kumactl) backoff durations validation

pkg/envoy/accesslog/commands.go, pkg/envoy/accesslog/field_operator.go, pkg/envoy/accesslog/field_operator_test.go
Signed-off-by: Tharun <rajendrantharun@live.com>
Right now the way to get grpc status is by using the format string `%TRAILER%` and it returns grpc code as a number. This pr improves it by adding a command `GRPC_STATUS` which will return the respective string representation of the code.
Added `GRPC_STATUS` command
Added tests
Fix #621
=> feat(envoy-accesslog) Added grpc status command to accesslog

pkg/core/resources/apis/mesh/fault_injection_validator.go, pkg/core/resources/apis/mesh/fault_injection_validator_test.go
We support FaultInjection in outbound proxy generator but validation of entity prevents to place it on such protocols.
This PR changes the validation on protocol from `http` to `http`, `http2` and `grpc`
=> fix(kuma-cp) allow fault injection for http2 and grpc

pkg/plugins/resources/k8s/native/api/v1alpha1/trafficlogging_types_helpers.go
Apparently, we have missed updating the TrafficLog helper to reflect that the resources are now Cluster scoped.
Unable to query TrafficLog through API + non-functioning TrafficLog GUI.
- Not needed
=> fix(*) traffic log scope

pkg/config/app/kuma-prometheus-sd/config.go, pkg/config/app/kuma-prometheus-sd/config_test.go, pkg/config/app/kuma-prometheus-sd/testdata/valid-grpcs-config.input.yaml
The configuration validation was only allowing `grpc` schemes
in practice `grpc` and `grpcs` should both be allowed.
* improve validation to allow grpcs scheme in the kube-prometheus-sd config
=> fix(kube-prometheus-sd) allow kuma-cp config to grpcs scheme

app/kuma-cp/cmd/run.go, pkg/core/bootstrap/bootstrap.go, pkg/core/runtime/builder.go, pkg/plugins/bootstrap/k8s/plugin.go, pkg/plugins/extensions/k8s/context.go, pkg/plugins/runtime/k8s/plugin.go, pkg/plugins/secrets/k8s/plugin.go, pkg/test/runtime/runtime.go
See the explanation in the comment of the code. We used non-cached client for Secrets on Kubernetes because we could not use the regular cached client in ControllerManager. This was ok until we introduced Secrets into reconciliation loop (Secrets are taken into account of Mesh Hash, because Secrets are used for TLS settings of External Service).
This change brings a separate cached client for Secrets.
=> perf(kuma-cp) cached client for fetching secrets on k8s

app/kuma-dp/cmd/run.go, app/kuma-dp/pkg/dataplane/accesslogs/server.go, pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml, pkg/xds/envoy/access_log.go
#894 actually broke TrafficLogs with TCP logger. It actually created a discrepancy in the naming of the UNIX socket between `kuma-dp` and the bootstrap generator in `kuma-cp`. In effect, Envoy was not able to find the GRPC logging service as provided by `kuma-dp` and the logs are never sent to the TCP logger.
Revert it and shorten the UNIX socket name by removing the not needed prefix `kuma-access-logs-`.
Fix #853 (again)
- Not needed
=> fix(*) traffic logging to tcp backends

app/kuma-dp/pkg/dataplane/envoy/envoy.go, pkg/xds/bootstrap/handler.go, test/dockerfiles/Dockerfile.universal, tools/releases/distros.sh, tools/releases/dockerfiles/Dockerfile.kuma-dp
Upgrade to Envoy 1.17.
https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.17.0
The most important changes
* V2 is only supported if you pass `--bootstrap-version` as CLI arg (therefore this PR is not against master for now)
* Some depreciations in V3 which will be fixed in the following PRs
This PR is meant to be merged only to master, not `release-1.0`.
Envoy binaries are uploaded to bintray.
=> chore(kuma-dp) upgrade Envoy version to 1.17.0

go.mod, go.sum, pkg/kds/cache/snapshot.go, pkg/mads/cache/snapshot.go, pkg/sds/server/v2/reconciler.go, pkg/sds/server/v3/reconciler.go, pkg/util/cache/v2/cache.go, pkg/util/cache/v3/cache.go, pkg/util/xds/cache.go, pkg/xds/envoy/listeners/v3/original_dst_forwarder_configurer.go, pkg/xds/envoy/listeners/v3/transparent_proxying_configurer.go, pkg/xds/envoy/listeners/v3/transparent_proxying_configurer_test.go, pkg/xds/server/v2/reconcile.go, pkg/xds/server/v2/reconcile_test.go, pkg/xds/server/v3/reconcile.go, pkg/xds/server/v3/reconcile_test.go, pkg/xds/server/v3/testdata/envoy-config.golden.yaml
This PR uses restores support for transparent proxy in V3.
To do this we had to upgrade to Envoy 1.17 (done) and use new Envoy config that has bind_to_port undeprecated.
For those new proto I had to upgrade the go-control-plane to the newest version from master. They introduced changes in Snapshot so I had to update our modified Snapshot as an interface.
=> feat(kuma-cp) transparent proxy v3

pkg/insights/resyncer_test.go, pkg/insights/test/test_event_reader.go, pkg/metrics/store/counter.go, pkg/metrics/store/counter_test.go, pkg/test/kds/samples/resources.go
Signed-off-by: Jacek Ewertowski <jacek.ewertowski1@gmail.com>
Fix #1165
@jakubdyszkiewicz please check if it is what you expected?
=> feat(kuma-cp): Resource counter based on Mesh insights

.circleci/config.yml, mk/e2e.new.mk, test/framework/constants.go, test/framework/k8s_cluster.go
This PR introduces parallel E2E tests that runs on V3 Envoy configuration. We want to only execute those tests on master to reduce CI on every commit on the branch.
=> chore(ci) test V3 in E2E tests

pkg/xds/generator/proxy_template.go
Populating the `predefinedProfiles` map was not possible publicly.
This is limiting for anyone wanting to make custom profiles
=> feat(kuma-dp) Expose the possibility to add ProxyTemplates publicly

go.sum, pkg/dns/resolver/resolver.go, pkg/dns/server_test.go, pkg/plugins/resources/k8s/native/go.sum
When specifying a `kuma.io/service` with a "." DNS resolution would not work
because it would only look at the first part of the DNS name.
This would also cause `foo.bar.mesh` and `foo.mesh` to resolve to the same thing
which may give a false sense of isolation of meshes in the DNS
We now only strips the last part of the DNS name if it matches the `.mesh` domain suffix.
=> fix(dns) allow resolution of service names with "."

go.sum, pkg/insights/resyncer.go, pkg/insights/resyncer_test.go, pkg/plugins/resources/k8s/native/go.sum, pkg/plugins/runtime/universal/outbound/outbound.go
MeshInsight had information about dataplanes in 2 places: Policy section and Dataplane section itself.
* Avoid counting Dataplane as a policy
* Delete noisy log line `outbounds updated due to VIP changes`
Fix #XXX
=> fix(kuma-cp) meshInsight has info about Dataplane twice

pkg/plugins/runtime/universal/outbound/outbound.go
Vips are not needed for ingresses so we shouldn't try to compute them
=> fix(dns) Avoid computing vips for ingress

docs/proposals/dns-using-envoy.md
=> docs(proposal) DNS using Envoy's DNSFilter

pkg/dns/components.go, pkg/dns/name_modifier.go, pkg/dns/name_modifier_test.go, pkg/dns/server.go, pkg/dns/server_test.go, test/e2e/kuma_deploy_universal_transparent_proxy_test.go
Add a resolve for `.mesh` names with `.` instead of `_`. The latter is not compliant with the canonical DNS RFCs and therefore not supported by Kubernetes and other dev frameworks to be referred to.
Example: `kuma-test_namespace_svc_80.mesh` will resolve to the same VIP as `kuma-test.namespace.svc.80.mesh`
-[x] #1519
=> chore(*) generate both DNS compliant and non-compliant names

pkg/hds/authn/callbacks.go, pkg/hds/authn/callbacks_test.go, pkg/hds/components.go, pkg/sds/server/v2/server.go, pkg/sds/server/v3/server.go, pkg/xds/auth/callbacks.go, pkg/xds/auth/callbacks_test.go, pkg/xds/server/v2/components.go, pkg/xds/server/v3/components.go
Retry on HDS auth to avoid logs in Envoy that DP is not found. Also, add the same capability to auth callbacks on XDS.
```
[2021-02-05 14:10:33.372][1927][info][main] [source/server/server.cc:679] starting main dispatch loop
[2021-02-05 14:10:33.569][1927][warning][upstream] [source/common/upstream/health_discovery_service.cc:262] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
[2021-02-05 14:10:33.569][1927][warning][upstream] [source/common/upstream/health_discovery_service.cc:71] HdsDelegate stream/connection failure, will retry in 776 ms.
```
(Yes, functional args for this might be cleaner, but I think it's not worth for 1 arg).
=> chore(kuma-cp) retry auth when dp is not found

test/framework/k8s_controlplane.go
The logic was missing from K8S framework.
=> chore(kuma-cp) generate ingress token in e2e tests using global K8S

app/kumactl/pkg/client/api_server_client.go, app/kumactl/pkg/resources/apiserver_client.go, app/kumactl/pkg/resources/dataplane_overview_client.go, app/kumactl/pkg/resources/service_overview_client.go, app/kumactl/pkg/resources/store.go, app/kumactl/pkg/resources/zone_overview_client.go, app/kumactl/pkg/tokens/client.go, pkg/core/bootstrap/bootstrap.go, pkg/core/runtime/builder.go, pkg/core/runtime/runtime.go, pkg/kds/context/context.go, pkg/kds/global/components.go, pkg/kds/mux/client.go, pkg/kds/mux/server.go, pkg/kds/remote/components.go, pkg/kds/remote/components_test.go, pkg/test/runtime/runtime.go
This PR provides a way to extend KDS
* Introduce KDS context so you can change which resources are synced between CPs
* Plug a custom callback when KDS session is iniated
* Small refactor in kumactl to reuse api server client across all clients
=> chore(kuma-cp) kds extensions

app/kuma-dp/pkg/dataplane/accesslogs/server.go
Sanitize the Unix domain socket used by kuma-dp for providing the access-log service.
=> fix(kuma-dp) close/unlink the dp access log unix socket

app/kuma-cp/cmd/run.go, pkg/clusterid/cluster_id_test.go, pkg/clusterid/clusterid_suite_test.go, pkg/clusterid/components.go, pkg/clusterid/creator.go, pkg/clusterid/reader.go, pkg/core/runtime/reports/reports.go, pkg/kds/remote/components.go
This PR fixes two problems
* Report proper number of zones. We were reporting meshes as zones and only when zones > 0. We want to report zones as 1 on standalone and real number of zones on global
* Cluster ID was only set on leader on standalone and global. I refactored the code so we set the cluster ID in consistent way in all use cases.
=> fix(kuma-cp) set cluster ID to followers

mk/e2e.new.mk, pkg/xds/envoy/clusters/v3/http2_configurer.go, pkg/xds/envoy/clusters/v3/http2_configurer_test.go, pkg/xds/envoy/clusters/v3/timeout_configurer.go, pkg/xds/envoy/listeners/v3/access_log_configurer.go, pkg/xds/envoy/listeners/v3/http_access_log_configurer_test.go, pkg/xds/envoy/listeners/v3/network_access_log_configurer_test.go, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/05.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/06.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/cluster-dots.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/transparent-proxy/03.envoy.golden.yaml, test/e2e/compatibility/compatibility_suite_test.go, test/e2e/compatibility/dp_compatibility_universal_test.go, test/e2e/compatibility/foo.go, test/framework/interface.go, test/framework/universal_app.go, test/framework/universal_cluster.go
Fix compatibility issue with this scenario:
* Use Kuma CP 1.0.8 and Kuma DP 1.0.8
* Upgrade Kuma CP to 1.1.x (DP still works and is on V2)
* Restart Kuma DP 1.0.8 (this will fetch V3 config which is not compatible with Envoy 1.16.x)
This would not be a problem on K8S since when you update CP, the next DP restart will spawn a new Kuma DP.
This PR changes the code to use Envoy's deprecated settings in 1.17.x to keep compatibility with Kuma DP 1.0.x (Envoy 1.16.x).
Another solution would be to
* Put DP version in `DataplaneMetadata` structure
* Change interface of all `Configure(X)` of envoy configurers to `Configure(X, EnvoyVersion)`
* Use proper Envoy settings depending on the Envoy version
This requires a refactor so I implemented a simpler solution at the cost of some warnings in 1.1.0. …
=> chore(kuma-cp) keep backward compatibility with Kuma DP 1.0.x

.github/ISSUE_TEMPLATE.md
Adds a line item to the "Additional Details & Logs" section of the GH issue template, as it is frequently left out.
=> chore(github) add Installation Method line item to issue template

api/mesh/v1alpha1/mesh.pb.go, api/mesh/v1alpha1/mesh.proto, docs/proposals/tracing.md, go.mod, go.sum, pkg/core/resources/apis/mesh/mesh_validator_test.go, pkg/xds/envoy/listeners/v2/tracing_configurer.go, pkg/xds/envoy/listeners/v3/tracing_configurer.go
Signed-off-by: ericmustin <mustin.eric@gmail.com>
(Sorry, had pushed up some unwanted changes to go.mod on other branch.)
This PR addresses https://github.com/kumahq/kuma/issues/1656 by adding support for zipkins `shared_span_context`
* [Implement shared_span_context configuration for envoy zipkin tracer]
Closes https://github.com/kumahq/kuma/issues/1656
=> feat: zipkin config add shared span context option

pkg/core/bootstrap/autoconfig.go
If $HOME is not defined error message will look like this:
```
Error: failed to create working directory inside $HOME: $HOME is not defined, please pick a working directory by setting KUMA_GENERAL_WORK_DIR manually
```
=> fix(kuma-cp) improve err message if $HOME is not defined

test/framework/k8s_cluster.go
Sometimes the deletion of the Namespace might take much more time than any other operation on the K8s cluster in the e2e tests.
This is specifically true in CPU-restricted environments like the CI. Especially with the Hybrid tests. We increase both the timeout and the
retry count making the total timeout 4 times larger. That should be enough or otherwise, there is probably an issue with the test.
=> test(e2e) permissive namespace delete

.circleci/config.yml
As `check` is running in parallel with `build/images` jobs,
and according to my experience looking at some of the last CI/CD
runs `build/images` is taking slightly more time than the `check`
itself, so it doesn't make sense if the only expectation from
not `requiring` it before running `e2e`-related jobs was to speed
it up.
What we are gaining by waiting for `check` to finish is much
quicker feedback when we forgot to run `make check` before pushing
new changes. It's not very rare to happen and without this
requirement, even if `check` fails, the whole spectrum of heavy
e2e tests will still run without a need, as we will have to still
run it again with the `make check` results.
Of course we can manually cancel that kind of job, but to achieve
this we would have to be always present at …
=> feat(ci/cd) wait for check before e2e/integration

pkg/xds/topology/outbound.go
Kuma CP was panicking with `concurrent map read and map write` because of race condition. It was clearly seen on Universal with TransparentProxy enabled with ~100 data plane proxies and at least 1 external service.
* replace an in-place write to map with 'WithTags' method
=> fix(kuma-cp) race condition with ExternalService

pkg/plugins/resources/memory/store.go
A small problem that may cause a deadlock on Memory storage. 
* call `eventWriter.Send` in a separate goroutine
=> fix(kuma-cp) call eventWriter.Send in a separate goroutine

pkg/xds/envoy/clusters/configurers.go, pkg/xds/envoy/clusters/v2/health_check_configurer.go, pkg/xds/envoy/clusters/v2/health_check_configurer_test.go, pkg/xds/envoy/clusters/v3/health_check_configurer.go, pkg/xds/envoy/clusters/v3/health_check_configurer_test.go, pkg/xds/generator/outbound_proxy_generator.go
When configuring `HealthCheck.Http` Kuma implied it always HTTP2. That didn't work well with `httpbin.org`. 
The current fix takes into account `protocol` which was set on the Service. But the fix has shortcomings. It doesn't allow creating an HTTP2 health checker for traffic that is treated as TCP or HTTP1.
Alternatively, we can introduce a new field `version` in `HealthCheck.Http` section:
```yaml
type: HealthCheck
mesh: default
name: internalhttpbin-check
sources: 
- match: 
kuma.io/service: '*'
destinations: 
- match: 
kuma.io/service: externalhttpbin
conf: 
interval: 10s
timeout: 2s
unhealthyThreshold: 1
healthyThreshold: 1
healthyPanicThreshold: 0
http: 
version: v1
path: /
```
Fix https://github.com/kumahq/kuma/issues/1700
=> fix(kuma-cp) pick HTTP health checker version depending on service protocol

pkg/xds/envoy/listeners/configurers.go, pkg/xds/envoy/listeners/v2/http_access_log_configurer_test.go, pkg/xds/envoy/listeners/v2/http_outbound_route_configurer_test.go, pkg/xds/envoy/listeners/v2/inbound_listener_configurer_test.go, pkg/xds/envoy/listeners/v2/max_connect_attempts_configurer_test.go, pkg/xds/envoy/listeners/v2/network_access_log_configurer_test.go, pkg/xds/envoy/listeners/v2/original_dst_forwarder_configurer_test.go, pkg/xds/envoy/listeners/v2/outbound_listener_configurer.go, pkg/xds/envoy/listeners/v2/outbound_listener_configurer_test.go, pkg/xds/envoy/listeners/v2/retry_configurer_test.go, pkg/xds/envoy/listeners/v2/timeout_configurer.go, pkg/xds/envoy/listeners/v3/http_access_log_configurer_test.go, pkg/xds/envoy/listeners/v3/http_outbound_route_configurer_test.go, pkg/xds/envoy/listeners/v3/max_connect_attempts_configurer_test.go, pkg/xds/envoy/listeners/v3/network_access_log_configurer_test.go, pkg/xds/envoy/listeners/v3/original_dst_forwarder_configurer_test.go, pkg/xds/envoy/listeners/v3/outbound_listener_configurer.go, pkg/xds/envoy/listeners/v3/outbound_listener_configurer_test.go, pkg/xds/envoy/listeners/v3/retry_configurer_test.go, pkg/xds/generator/direct_access_proxy_generator.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/transparent_proxy_generator.go
This enables generators to add outbound listeners.
This is not first class support for UDP and only enables generators
to create listeners using UDP
Signed-off-by: Charly Molter <charly@koyeb.com>
=> feat(XDS): Add internal support for outbound UDP listeners

app/kumactl/cmd/install/install_control_plane.go
Fix a copy-paste error with `kumactl install control-plane --ingress-enabled`.
Interesting how this is even working today?
=> fix(kumactl) fix ingress-enabled

mk/e2e.new.mk
The e2e tests should fail when a particular test folder fails.
Today it does not see (look for `[Fail] Test Kubernetes/Universal deployment [It] should access allservices`:
https://app.circleci.com/pipelines/github/kumahq/kuma/6597/workflows/17010313-67fe-49ec-af0c-f39a72b81070/jobs/79119/parallel-runs/1/steps/1-108
=> fix(e2e) should fail on particular group test failure

app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap_test.go
On Kubernetes when Dataplane is not converted from Pod we got 404 and we retry it on kuma-dp.
When we retry we print msg
`Dataplane entity is not yet found in the Control Plane. If you are running on Kubernetes, CP is most likely still in the process of converting Pod to Dataplane. Retrying.`
and eventually if the problem persist we end a process with
`Dataplane entity not found. If you are running on Universal please create a Dataplane entity on kuma-cp before starting kuma-dp. If you are running on Kubernetes, please check the kuma-cp logs to determine why the Dataplane entity could not be created by the automatic sidecar injection.`
We should hint the users that they should check CP logs while waiting for Dataplane (not only after all the retries). It most likely something wrong on the …
=> chore(kuma-dp) better error messages when there is problem with pod convertion

pkg/kds/context/context.go, pkg/kds/remote/components.go, pkg/kds/remote/components_test.go
If Kuma CP Global filters Configs before sending to the Remote, then Remote has to Prefilter Configs when Sync resources.
* Add `PrefilterBy` on Remote for Configs
* Add test
Fix #XXX
=> fix(kuma-cp) KDS may delete ConfigMaps on Control Plane restarts

app/kuma-dp/cmd/run.go, app/kuma-dp/cmd/run_test.go, pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-dp/testdata/default-config.golden.yaml
having an option to provide `--name` and `--mesh` with `--dataplane-file` is confusing because mesh and name in dataplane definition takes precedence. Added validation that you cannot use `--name` or `--mesh` with `--dataplane-file`.
This is a slightly breaking change because I had to change that `--mesh` not by default is not `default` but needs to be explicitly provided.
=> chore(kuma-dp) validate --name and --mesh when dataplane is provided

app/kuma-dp/cmd/run.go, app/kuma-dp/pkg/dataplane/dnsserver/config_file.go, app/kuma-dp/pkg/dataplane/dnsserver/config_file_test.go, app/kuma-dp/pkg/dataplane/dnsserver/dnsserver.go, app/kuma-dp/pkg/dataplane/dnsserver/dnsserver_suite_test.go, app/kuma-dp/pkg/dataplane/dnsserver/dnsserver_test.go, app/kuma-dp/pkg/dataplane/dnsserver/testdata/binary-mock.exit-0.sh, app/kuma-dp/pkg/dataplane/dnsserver/testdata/binary-mock.exit-1.sh, mk/build.mk, mk/docker.mk, pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-dp/config_test.go, pkg/config/app/kuma-dp/testdata/default-config.golden.yaml, tools/builds/coredns/templates/plugin.cfg, tools/releases/distros.sh, tools/releases/dockerfiles/Dockerfile.kuma-dp, tools/releases/dockerfiles/Dockerfile.kuma-dp.dockerignore
- Functionality to run DNS Server (CoreDNS) alongside kuma-dp
- Added to our current build/release workflow building our version of coredns which was stripped from any unnecessary plugins
=> feat(kuma-dp) add coredns server to kuma-dp

mk/check.mk
If you ever forgot to get rid of `FIt` or `FEntry` before the commit, then it's not the case anymore!
* add `make ginkgo/unfocus` as a part of `make check`
=> chore(kuma-cp) add 'ginkgo unfocus'

pkg/dns/outbound.go, pkg/dns/outbound_test.go, pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_controller_test.go, test/e2e/externalservices/externalservices_kubernetes_test.go
Generate VIP outbound with port `:80` for ExternalServices that have another port
* additional outbound for ExternalServices 
* check port `:80` in e2e
* add watcher of ExternalService resources for PodController
Fix #XXX
=> feat(kuma-cp) backward compatibility for external-service VIPs

pkg/xds/sync/components.go, pkg/xds/sync/dataplane_proxy_builder.go, test/e2e/healthcheck/healthcheck_hybrid_test.go
Comment implied that we have to get Dataplane from a non-cached Store, but in practice, it was taken from a cached store:
```go
// we use non-cached ResourceManager to always fetch fresh version of the Dataplane.
// Otherwise, technically MeshCache can use newer version because it uses List operation instead of Get
if err := p.ResManager.Get(ctx, dataplane, core_store.GetBy(key)); err != nil {
return nil, err
}
```
* pass the second (non-cached) store to the proxy builder
* refactor e2e checker
Fix #XXX
=> fix(kuma-cp) Envoy config is created based on old Dataplane

pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go
Kuma has a locality-aware loadbalancing feature that uses priority under the hood. We could even not set zone on endpoints and just use priority but we do this anyways. The only profit right now from setting this is the visibility of the zone in `/clusters`.
Right now there is a problem that if you have `localityAwareLoadbalancing` on the mesh to `false` and then switch it to `true`, we send EDS with proper settings but for some reason, Envoy does not reflect `zone`, `subzone` and `region` change in EDS settings. The most important for our feature is `priority` which **IS** reflected dynamically after we change endpoints.
This might be the caused by this issue https://github.com/envoyproxy/envoy/issues/12392
The problem only affects changing locality of endpoint. If we remove endpoint and …
=> fix(kuma-cp) always set locality on endpoint in multizone

app/kuma-ui/pkg/resources/fs.go, deployments/go.mod, go.mod
* Ability to override Kuma GUI
* Remove Go module for deployments. It's not needed
=> chore(kuma-cp) restore ability to extend GUI via embed

app/kumactl/cmd/root.go
The version comparison in kumactl was not working - it would attempt to connect to kuma-cp to retrieve version prior to loading config and that retrieval would silently fail. This fix moves the API call to happen after config loads.
Also changed the error message to conform to what is specified in the ticket.
* Fix kumactl / kuma-cp version comparison in kumactl.
=> fix(kumactl) Check version after loading config.

go.sum, test/e2e/externalservices/externalservices_kubernetes_test.go, test/e2e/externalservices/externalservices_universal_test.go, test/e2e/hybrid/kuma_hybrid_test.go, test/e2e/tracing/tracing_kubernetes_test.go, test/framework/env.go
The Builtin DNS functionality is disabled for the deprecated APIv2. Skip the relevant tests in the E2E.
As the future is to completely move to Builtin DNS, we might just revert this logic and skip all tests for V2 with a couple of small exceptions.
=> test(e2e) skip all builtin DNS tests for APIv2

test/e2e/helm/kuma_helm_upgrade_test.go
As a result of https://github.com/kumahq/kuma/pull/1879 generated manifests from `kumactl install dns` contains:
```
WARNING: You are using kumactl version latest for Kuma, but the server returned version: Kuma 1.0.3
```
so the tests were failing.
During these tests DNS is not necessary, so I decided to remove it
=> tests(*) don't install DNS on helm upgrade

test/framework/kumactl.go
Changing one of the kumactl methods in e2e framework to run kumactl and get output only from stdout instead of combining them with stderr
=> fix(e2e) collect stdout only in kumactl e2e

app/kumactl/cmd/apply/apply_test.go, app/kumactl/cmd/generate/generate_dataplane_token_test.go, app/kumactl/cmd/get/get_circuit_breakers_test.go, app/kumactl/cmd/get/get_dataplanes_test.go, app/kumactl/cmd/get/get_external_services_test.go, app/kumactl/cmd/get/get_fault_injections_test.go, app/kumactl/cmd/get/get_global_secrets_test.go, app/kumactl/cmd/get/get_healthchecks_test.go, app/kumactl/cmd/get/get_meshes_test.go, app/kumactl/cmd/get/get_proxytemplates_test.go, app/kumactl/cmd/get/get_retries_test.go, app/kumactl/cmd/get/get_secrets_test.go, app/kumactl/cmd/get/get_single_resource_test.go, app/kumactl/cmd/get/get_traffic_logs_test.go, app/kumactl/cmd/get/get_traffic_routes_test.go, app/kumactl/cmd/get/get_traffic_traces_test.go, app/kumactl/cmd/get/get_trafficpermissions_test.go, app/kumactl/cmd/get/get_zones_test.go, app/kumactl/cmd/inspect/inspect_dataplanes_test.go, app/kumactl/cmd/inspect/inspect_meshes_test.go, app/kumactl/cmd/inspect/inspect_services_test.go, app/kumactl/cmd/inspect/inspect_zones_test.go, app/kumactl/cmd/root_test.go
Test fix for kumactl as with https://github.com/kumahq/kuma/pull/1879/files#diff-51a6a652c3bb67a29021ea8a2773a31955ea8bbe9116113f34afcd91f50aca34R65 https://github.com/kumahq/kuma/blob/b02e60fcabbbc5b082766f77358b1feb9aad0981/app/kumactl/pkg/cmd/root_context.go#L35 have to be defined in RootContext
=> fix(tests) kumactl tests fix

pkg/dns/outbound.go, pkg/dns/outbound_test.go, pkg/plugins/runtime/universal/outbound/outbound_test.go
Generate outbound entries for the service itself, to be able to
communicate with the local service through envoy
Fix https://github.com/kumahq/kuma/issues/1742
=> feat(kuma-cp) generate outbounds for itself

docs/guides/README.md, docs/guides/e2e-test-tips.md, docs/guides/new-feature.md, docs/guides/upgrade-dependencies.md
Here is an idea. I see that sometimes we lack formal process or we have what is called [tribal knowledge](https://en.wikipedia.org/wiki/Tribal_knowledge)
I'd like to have a place that we can share tips and write some guides that can help develop the project.
Automation is always better than manual steps but sometimes we cannot avoid it.
More examples:
* Refresh RELEASE.md and move it here
* Create notes how to debug AKS/EKS tests
=> docs(*) introduce guides

app/kuma-prometheus-sd/pkg/discovery/xds/v1/converter.go, app/kuma-prometheus-sd/pkg/discovery/xds/v1/converter_test.go, pkg/config/app/kuma-prometheus-sd/config.go, pkg/config/app/kuma-prometheus-sd/testdata/default-config.golden.yaml
Though `targetgroup.Group.Source` is constant in the native Prometheus SD implementations, the kuma-prometheus-sd
does target diff tracking using this field in order to remove groups from the written file, and expects it to be unique.
* Ensure that kuma-prometheus-sd uses namespaced source names for targetgroup.Groups, so diffs can be calculated
Fixes #1886
=> fix(prometheus-sd) namespace source names for v1 API

pkg/mads/server/server.go
During graceful shutdown `mads-server` printed errors.
For some reason `cmux.Serve` returns `use of closed network connection`, instead of `cmux.ErrListenerClosed`, probably it relates to https://github.com/soheilhy/cmux/issues/39
=> fix(kumactl) mads-server graceful shutdown

pkg/plugins/bootstrap/k8s/xds/hooks/api_server_bypass.go, pkg/xds/hooks/resource_set.go
When creating normal Dataplanes and Ingress ones method `Modify`
is being called but in later scenario (Ingress) the passed
xds.Context is empty.
Here is the fix for K8s API Passthrough Bypass and also I'm adding
the comment with a warning about this fact
=> fix(kuma-cp) check for xds.Context in Bypass hook

.circleci/config.yml
As there where changes related to moving away from bintray, which
was sunset, I had to adjust EKS e2e tests configuration, as there
were wrong docker images being tagged during the process, as there
was mismatch between images build jobs and EKS tests
According to CircleCI, currently the only option to manually
trigger the workflow is to add pipeline parameters with default
values set to true, which then let's you manually call the API
endpoint with parameters set according to needs.
ref:
https://support.circleci.com/hc/en-us/articles/360050351292-How-to-trigger-a-workflow-via-CircleCI-API-v2
=> fix(e2e) eks e2e tests docker registry fix + add option to manually trigger workflows

app/kumactl/cmd/completion/testdata/bash.golden, app/kumactl/cmd/completion/testdata/zsh.golden, app/kumactl/cmd/install/context/install_gateway_context.go, app/kumactl/cmd/install/install.go, app/kumactl/cmd/install/install_gateway.go, app/kumactl/cmd/install/install_gateway_test.go, app/kumactl/cmd/install/testdata/install-gateway.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.overrides.golden.yaml, app/kumactl/data/fs.go, app/kumactl/data/install/k8s/gateway/kong/kong.yaml, app/kumactl/data/install/k8s/gateway/namespace.yaml, app/kumactl/pkg/cmd/root_context.go
Add option to install an ingress gateway to kubernetes. Currently only supports Kong ingress, but takes type on command line.
`kumactl install gateway --type kong | kubectl apply -f -`
* Add option to install an ingress gateway.
=> feat(kumactl) Add option to install Kong ingress

test/e2e/externalservices/externalservices_multizone_universal.go
External services multizone test is not compatible with V2 because of builtin DNS
=> ci(*) fix external services V2 E2E tests

test/e2e/hybrid/kuma_hybrid.go
I think due to the slower propagation of policies on CircleCI, sometimes we had a problem with `should sync traffic permissions`.
The test `should sync traffic permissions` diverged to not be about syncing traffic permissions, but many different things.
For traffic permissions, we now have a dedicated test suite including hybrid deployment, so I don't think it belongs here.
I changed this and the previous test and this one to be about Jobs, because it's what we testing here.
I noticed that for failing job we are waiting for very long time! I don't think it's ok to slow down tests by a couple of minutes to just to check that CP does not remove job. I did not found a clean way to test it, so in the end I removed this case, it is covered by unit test.
If you think that it is essential to …
=> test(*) change E2E test of jobs

pkg/xds/ingress/dataplane.go, pkg/xds/ingress/dataplane_test.go
The wrong order was causing Ingresses to get regenerated when it
wasn't necessary
Signed-off-by: Charly Molter <charly@koyeb.com>
=> fix(kuma-cp): Fix bug in order of dataplane for ingress

pkg/hds/server/server.go
This a copy of https://github.com/envoyproxy/go-control-plane/pull/430
which fixes a possible goroutine leak
Partly fixes #2004
Signed-off-by: Charly Molter <charly@koyeb.com>
=> fix(kuma-cp): fix goroutine leak in hds

mk/dev.mk
Signed-off-by: Jacek Ewertowski <jacek.ewertowski1@gmail.com>
When I was building Kuma in the alpine container I encountered a problem with:
```
unzip /tmp/protoc-$(PROTOC_VERSION)-$(PROTOC_OS)-$(PROTOC_ARCH).zip bin/protoc -d /tmp/protoc-$(PROTOC_VERSION)-$(PROTOC_OS)-$(PROTOC_ARCH)
```
This command fails due to "file or directory does not exist". Creation of a target directory before unzipping is the only workaround I know.
What do you think about to fix this problem?
=> fix(conf): fix building Kuma in alpine container

pkg/sds/server/v2/reconciler.go, pkg/sds/server/v2/server.go, pkg/sds/server/v2/server_test.go, pkg/sds/server/v3/reconciler.go, pkg/sds/server/v3/server.go, pkg/sds/server/v3/server_test.go, test/e2e/trafficpermission/hybrid/traffic_permission_hybrid.go
When we change DP (ex. adding extra inbound) we were not regenerating the certificate for mTLS.
This can happen on Kubernetes when
* adding new service for the pod
* labeling pod with `kubectl label pod`
Change `shouldGenerateSnapshot` in SDS to take into account dataplane.
I changed the logic so we are no longer encoding info in the version of SDS, but we are keeping it in memory.
It does not make sense to keep this as a version, if CP restarts, the snapshot is not there so we need to regenerate certs anyways.
We also check now not only the enabled backend but the backend settings so if someone changes the secret of provided CA, we regenerate certs.
=> fix(kuma-cp) regenerate cert on DP change

app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cp-rbac.yaml, deployments/charts/kuma/templates/ingress-deployment.yaml, deployments/charts/kuma/templates/pre-delete-webhooks.yaml, deployments/charts/kuma/templates/pre-install-patch-namespace-job.yaml, deployments/charts/kuma/templates/pre-upgrade-install-missing-crds-job.yaml, deployments/charts/kuma/values.yaml
Added node selectors to Ingress and HELM hooks. There was already setting to CP and CNI.
=> feat(conf) nodeselector across all pods with HELM

test/framework/setup.go
Add missing option WithIPv6 when deploy test-server
* [Fix ...]
Fix #XXX
=> fix(test) add missing option WithIPv6 when deploy test-server

pkg/sds/metrics/metrics.go, pkg/sds/server/v2/reconciler.go, pkg/sds/server/v2/server.go, pkg/sds/server/v2/server_test.go, pkg/sds/server/v3/reconciler.go, pkg/sds/server/v3/server.go, pkg/sds/server/v3/server_test.go
As a follow-up to a previous PR. We should also clear snapshot when mTLS is disabled, otherwise, we can delete watches.
- No docs, internal fixes
=> fix(kuma-cp) clear snapshot on mTLS disable

test/e2e/resilience/resilience_multizone_universal.go, test/e2e/resilience/resilience_multizone_universal_test.go, test/e2e/resilience/resilience_suite_test.go
Add test for universal multizone (both - global and remote zones
are universal) when we will forcefully kill remote control-plane
=> tests(*) add universal multizone resilience tests

app/kuma-dp/pkg/dataplane/dnsserver/dnsserver.go, app/kuma-dp/pkg/dataplane/envoy/envoy.go
Set the death signal on Envoy and CoreDNS child processes. This causes
the kernel to send SIGKILL to these processes if the kuma-dp process exits
unexpectedly (e.g. panics or is killed). This improves the resiliency of
the dataplane since restarting would not encounter stale child processes.
* Improve crash recovery by ensuring that Envoy and CoreDNS child processes are killed when kuma-dp dies unexpectedly.
N/A
N/A
=> fix(kuma-dp) set death signal on child processes

test/e2e/healthcheck/universal/policy_http.go, test/e2e/healthcheck/universal/policy_tcp.go
* `WithBuiltinDNS` doesn't work with V2, so get rid of this flag for health check tests. 
* when the host becomes unhealthy there is one more check to make sure requests won't work:
```go
stdout, _, err = cluster.ExecWithRetries("", "", "dp-demo-client", "/bin/bash", "-c", "\"echo request | nc test-server.mesh 80\"")
Expect(err).ToNot(HaveOccurred())
Expect(stdout).To(BeEmpty())
```
There is no traffic indeed, but sometimes `ExecWithRetries` returns `err` which is not `nil`. I dropped the error check and left only `stdout` check.
* [Fix ...]
Fix #XXX
=> fix(test) disable builtin dns for tests

app/kuma-dp/pkg/dataplane/command/build_command_darwin.go, app/kuma-dp/pkg/dataplane/command/build_command_linux.go, app/kuma-dp/pkg/dataplane/dnsserver/dnsserver.go, app/kuma-dp/pkg/dataplane/envoy/envoy.go
As `Pdeathsig` is a property of `syscall.SysProcAttr` available
only on linux, this PR is introducing conditional compilation
of these bits only for linux
This is a followup of https://github.com/kumahq/kuma/pull/2045
=> fix(kuma-dp) conditional compile syscall for linux

app/kuma-cp/cmd/cmd_k8s_test.go, app/kuma-cp/cmd/run_test.go, app/kuma-dp/pkg/dataplane/dnsserver/dnsserver_test.go, app/kuma-dp/pkg/dataplane/envoy/envoy_test.go, app/kuma-prometheus-sd/cmd/run_test.go, pkg/api-server/index_endpoints_test.go, pkg/core/resources/manager/cache_test.go, pkg/kds/mux/session_test.go, pkg/plugins/config/k8s/k8s_suite_test.go, pkg/plugins/leader/postgres/leader_elector_test.go, pkg/plugins/resources/k8s/k8s_suite_test.go, pkg/plugins/resources/k8s/native/api/v1alpha1/suite_test.go, pkg/plugins/resources/k8s/native/controllers/suite_test.go, pkg/plugins/resources/k8s/native/pkg/test/within.go, pkg/plugins/runtime/k8s/controllers/suite_test.go, pkg/plugins/runtime/k8s/webhooks/injector/injector_suite_test.go, pkg/plugins/secrets/k8s/k8s_suite_test.go, pkg/sds/server/v2/server_test.go, pkg/sds/server/v3/server_test.go, pkg/test/within.go, pkg/util/watchdog/watchdog_test.go, pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
As per the [Ginkgo v2 upgrade guide](https://github.com/onsi/ginkgo/blob/v2/docs/MIGRATING_TO_V2.md#removed-async-testing), using the Done type to signal
timed, asynchronous test functions is deprecated and doesn't work
correctly. Replacing all these usages with a local test helper removes
the Ginkgo deprecation warnings and (at least for my environment) makes
the tests reliably pass.
N/A
N/A
N/A
=> chore(test) stop using the Ginkgo Done type

pkg/transparentproxy/istio/tools/istio-iptables/pkg/cmd/root.go
Before we are proceeding with all iptables rules I have added
validation if there is `nat` table present in the machine, which
is assumption to be sure if `ip6tables_nat` kernel module
is present and loaded.
Fix https://github.com/kumahq/kuma/issues/2046
I have tested the solution on GKE with nodes with `COS_CONTAINERD` and `UBUNTU_CONTAINERD` images and also to check for potential regressions also testes on AWS/EKS
=> fix(*) fix transparent-proxy for GCP/GKE

test/e2e/trafficroute/universal_multizone/traffic_route.go
When using `memory` store it enumerates the version always starting from "1".  If someone tries to quickly delete and create a resource with the same name, but with a different `conf` then the old `conf` might be cached, because resources are not distinguishable for the Cache. That's exactly what happened with the new e2e tests for TrafficRoute. 
As a solution, I just renamed policies in every test of the same suite. 
Failed CI: https://app.circleci.com/pipelines/github/kumahq/kuma/7627/workflows/5545f5e1-0f97-4d1d-af5c-8d02f6fcec4c/jobs/88377
@kumahq/kuma-maintainers this is a quickfix to make CI work, but maybe we should consider using random autogenerated versions for memory and postgres? 
* [Fix ...]
Fix #XXX
=> fix(test) TestE2ETrafficRouteUniversalMultizone is flaky

test/e2e/kic/kubernetes/kong_ingress.go, test/kind/cluster-ipv6-kuma-1.yaml
- There was a small mistake in the structure of kind cluster config manifest file for ipv6
- Also DNS are available on API v3 only, so we have to skip `KIC` tests for API v2 e2e tests
=> fix(tests) e2e master

test/kind/cluster-ipv6-kuma-1.yaml
Cluster config should use the same ports for ipv4 and ipv6. This doesn't fully fix the  IPV6 tests, but is necessary.
=> tests(*) Use consistent ports in ipv4 and ipv6

app/kumactl/cmd/config/config_control_planes_add.go, pkg/util/maps/maps_suite_test.go, pkg/util/maps/sorted_keys.go, pkg/util/maps/sorted_keys_test.go
Order of headers in the config was not deterministic
- No docs
=> tests(kumactl) fix flaky order of headers

Makefile, docs/guides/e2e-test-tips.md, mk/docker.mk, mk/e2e.new.mk, test/framework/deployments/externalservice/universal.go, test/framework/env.go, test/framework/universal_app.go
* Prettify the "make help" to improve readability
* Add docstrings to useful make targets
* Simplify e2e test package discovery
* Add some more e2e test documentation
* Remove most uses of the "kuma-universal:latest" tag
* Consistently use the Kuma universal image name constant
N/A
N/A
N/A
=> fix(e2e) various e2e tooling fixes

pkg/core/xds/types.go, pkg/core/xds/types_test.go
We had a bug in `ContainsTags` function.
The problem was only visible if we had a traffic route over the tag that was only available in one instance. Then we mistakenly were picking instances that did not have the tag at all. 
Fixed the bug, added a bunch of tests.
=> fix(kuma-cp) matching endpoints by tags

test/e2e/kic/kubernetes/kong_ingress.go
IPv6 not supported by KIC. Turning off e2e test when testing IPv6.
=> tests(kumactl) IPv6 not supported on KIC; skip test.

api/Makefile
In the main build, TOOLS_DIR means the ./tools directory in the
repository, and CI_TOOLS_DIR is where build and test tools are
downloaded and installed.
Update the API Makefile to follow the same policy so that developers
can set consistent environment variables.
N/A
N/A
N/A
=> fix(build) use CI_TOOLS_DIR consistently

.circleci/config.yml
After changing names of env vars for tests in makefiles
(related to bintray deprecation) we forgot to change the name
of BINTRAY_REGISTRY -> DOCKER_REGISTRY for aks e2e job
=> fix(e2e) aks push images command fix

pkg/util/os/limits.go
On Darwin, we have to look at kernel systunes to find the real open
file limit. Rather than adding a lot of extra code for a non-production
platform, just clip it to a sensible default.
N/A
Fix #2091 
N/A
=> fix(*) clip open files limit on Darwin

test/e2e/trafficroute/universal_standalone/traffic_route.go
This functionality is not supported in API V2
=> tests(kuma-cp) skip header modification on API V2

pkg/util/os/limits.go, pkg/util/os/limits_test.go
- Test was not working on macos as the max ulimit was set manually
- I bumped the number of default "reasonable" value of ulimit
for macos to 10240 as it was the default for my system and
when it was smaller we couldn't restore the value after our tests
because we were trying to set higher value then the "max" we set
=> fix(tests) dev_macos tests

Makefile
Improve readability by automatically splitting the output
of `make help` into sections.
Signed-off-by: James Peach <james.peach@konghq.com>
N/A
N/A
N/A
```
$ make help
check                          Dev: Run code checks (go fmt, go vet, ...)
clean                          Dev: Clean
docs                           Dev: Generate all docs
fmt                            Dev: Run various format tools
generate                       Dev: Run code generators
golangci-lint                  Dev: Runs golangci-lint linter
helm-docs                      Dev: Runs helm-docs generator
help                           Display this help screen
images                         Dev: Rebuild release and tesst Docker images
imports                        Dev: Runs goimports in order to organize imports …
```
=> chore(build) split build documentation into sections

docs/proposals/L7-traffic-route.md
Proposal on how we can introduce L7 HTTP routing to Kuma.
=> Traffic Route L7 proposal

app/kuma-dp/pkg/dataplane/metrics/merge_test.go, app/kuma-dp/pkg/dataplane/metrics/metrics_suite_test.go, app/kuma-dp/pkg/dataplane/metrics/server.go, app/kuma-dp/pkg/dataplane/metrics/server_test.go
The Envoy Prometheus endpoint supports passing a filtering regex in
the query parameters to limit the set of metrics that are returned.
This feature lets a metrics scraper scrape different sets of metrics
at different intervals.
* Pass query parameters through the DP metrics endpoint so that metrics scrapers can sample subsets of the available metrics.
Updates #1755.
N/A
=> fix(kuma-dp) pass query parameters through the metrics hijacker

pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.ipv6.golden.yaml
Even though regex program sizes are deprecated, Envoy still enforces
the default limit of 100 in the layered runtime. Since users have no
reasonable way to predict the size of some arbitrary regex or know
how that affect performance, just max out the limit. We have to use
UINT32_MAX here, because the actual check truncates the value. We also
set a warning limit to an arbitrary size value in case anyone looks at
logs and wants to optimize their regexes.
N/A
Fix #2103.
N/A
After applying the new bootstrap, Envoy accepts a regex with a large program size, but logs a warning:
```
[2021-06-09 23:52:07.442][19][warning][misc] [source/common/common/regex.cc:100] regex '/static/[a-zA-Z0-9._-]{0,200}/[a-zA-Z0-9._-]{0,200}' RE2 program size of 2013 > max program size of 1000 set for the warn level …
```
=> fix(kuma-cp) raise the regex program size limit

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/config/mads/config.go, pkg/mads/v1/service/http.go, pkg/mads/v1/service/mads.go, pkg/mads/v1/service_test.go, pkg/util/xds/v3/cache.go
Adds support for HTTP long polling by making the xds rest server Fetch call block until there is an update, or the operation times out.
Currently, it just uses the configuration to define default timeouts for updates. I've got an open question in envoy 
to see if there is a standard way to set this timeout in the REST-JSON spec (see https://github.com/envoyproxy/envoy/issues/16859), but if they
don't get back to us soon we can just add a simple `timeout` query param or request header.
This will unblock the native Prometheus SD efforts here: https://github.com/prometheus/prometheus/pull/8844
* Implement a blocking Fetch call using context timeouts 
* Change config option `monitoringAssignmentServer.fetchTimeout` to `monitoringAssignmentServer.defaultFetchTimeout`
n/a
n/a – need to finish …
=> feat(mads) add support for HTTP long polling

tools/releases/dockerfiles/Dockerfile.kuma-cp, tools/releases/dockerfiles/Dockerfile.kuma-dp, tools/releases/dockerfiles/Dockerfile.kuma-init, tools/releases/dockerfiles/Dockerfile.kuma-prometheus-sd, tools/releases/dockerfiles/Dockerfile.kumactl
* "kuma-cp run" needs a home directory to store state, so run it using
a standard unprivileged Kuma user account.
* Adjust all the Dockerfile COPY commands to minimize the image layers.
* Fix missing home directories in the Kuma Docker images.
Fix #2128.
N/A
=> fix(dockerfiles) add a user for kuma-cp

go.sum, pkg/mads/v1/service/http.go, pkg/mads/v1/service_test.go
Follow up on #2121, adds a query parameter (`fetch-timeout`) to allow clients to specify how long a single HTTP long polling request should wait. 
Originally was thinking a [GRPC TimeoutValue and TimeoutUnit](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests) made sense as the format, but we use golang's `time.Duration` format elsewhere in the config, and a parser already exists for it, so went with that instead. 
If the timeout value is less than or equal to 0, the request does a sync fetch instead.
* Add `fetch-timeout` query parameter to the MADS V1 HTTP endpoint
* Also fixes a bug with the error responses continuing the request even after a response has been sent
- Will document after native Prometheus SD is in
=> feat(mads) allow specifying fetch-timeout via query param

pkg/xds/envoy/clusters/configurers.go, pkg/xds/envoy/clusters/v3/http2_configurer.go, pkg/xds/envoy/clusters/v3/http2_configurer_test.go, pkg/xds/envoy/clusters/v3/http_configurer.go, pkg/xds/envoy/clusters/v3/http_configurer_test.go, pkg/xds/envoy/clusters/v3/timeout_configurer.go, pkg/xds/envoy/clusters/v3/update_common_http_protocol_options.go, pkg/xds/envoy/listeners/v3/access_log_configurer.go, pkg/xds/envoy/listeners/v3/http_access_log_configurer_test.go, pkg/xds/envoy/listeners/v3/network_access_log_configurer_test.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/05.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/06.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/cluster-dots.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/transparent-proxy/03.envoy.golden.yaml, test/e2e/compatibility/dp_compatibility_universal.go
Remove some deprecated Envoy options that were kept for compatibility with Kuma 1.x
=> chore(*) drop deprecated Envoy options

pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.01.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.02.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.03.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.04.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.05.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.06.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.07.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.08.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.09.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.11.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.12.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.13.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.14.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.15.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.16.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.17.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.18.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.19.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.21.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.22.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.23.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.24.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.25.golden.yaml
With this change, kuma-init which will be injected to k8s pods
will be run in verbose mode, which will make debugging much
easier
=> feat(kuma-cp) add --verbose flag to kuma-init

app/kuma-dp/cmd/run_test.go, pkg/core/resources/apis/mesh/zone_ingress_validator_test.go
`bytes.Buffer`  is not thread-safe. We are using it in kuma-dp `run_test` to replace stdout. Then both Envoy and built-in DNS writes to this buffer which results in data race detection.
The solution is to use `io.Pipe()` which returns reader and writer which are thread-safe.
=> tests(kuma-dp) fix concurrent access to buffer

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/Chart.yaml, deployments/charts/kuma/README.md
Change HELM chart version to RC1. This way we can upgrade stable Kuma to RC1 using HELM without releasing the chart.
Keep in mind that when we tag `1.2.0-rc1`, the chart is not released because we have regex on `number.number.number`
=> chore(kuma-cp) HELM 1.2.0-rc1

.circleci/config.yml, RELEASE.md, tools/releases/make-release-tag.sh
Add a script to ensure that the release tag is an annotated tag that
contains a summary of commits since the previous release. The tag name
is required to match Go module semantic version numbering.
* Fix version tagging to work with Go modules.
Fix #2073 
None.
```
$ ./tools/releases/make-release-tag.sh 1.1.6 v99.99.0
Created tag 'v99.99.0'
Testing whether tag 'v99.99.0' can be pushed
To github.com:kumahq/kuma.git
* [new tag]           v99.99.0 -> v99.99.0
Run 'git push origin v99.99.0' to push the tag if you are happy.
```
```
$ git show v99.99.0
tag v99.99.0
Tagger: James Peach <james.peach@konghq.com>
Date:   Tue Jun 15 07:56:43 2021 +1000
Tag v99.99.0 release.
Austin Cawley-Edwards (6):
chore(*) add Installation Method line item to issue template (#1661)
chore(crds) upgrade to …
```
=> fix(*) add release tagging script

test/e2e/hybrid/kuma_hybrid.go
Because of failing netcat this test constantly fails. In order to fix it, we need to migrate to our test-server which requires creating a test-server deployment
=> chore(tests) skip flaky E2E test for now

pkg/core/resources/apis/mesh/traffic_route_validator.go, pkg/core/resources/apis/mesh/traffic_route_validator_test.go, test/e2e/trafficroute/universal_standalone/traffic_route.go
With Envoy 1.18.3 we can no longer modify host header in `requestHeaders` and `responseHeaders`.
This should have been caught in upgrade PR but it slipped out because of flaky support jobs test.
=> chore(kuma-cp) add validators of pseudoheader and host modifications

pkg/defaults/signing_key.go, pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_controller_test.go
During the upgrade to Kuma 1.2.0 a new Ingress pod may make a request to the old-versioned PodController.
This will inevitably cause a generation of both Dataplane Ingress resource and Zone Ingress resource.
That's why here we're deleting Dataplane Ingress resource.
* [Fix ...]
Fix #XXX
=> fix(kuma-cp) delete old dataplane-based ingress in PodController

pkg/sds/server/v3/reconciler.go, pkg/xds/server/v3/reconcile.go, pkg/xds/server/v3/reconcile_test.go
Previously we were pushing an empty snapshot on the cache when a dp was disconnecting.
This was causing the dp to get an empty snapshot after a restart.
This would cause listeners to disappear for a short time and causing the traffic going through the dp to fail.
We now clear the snapshot from the dp to avoid this behaviour.
Fix #2171
=> fix(kuma-cp) Clear snapshots from cache on disconnect

app/kumactl/cmd/install/testdata/install-gateway-enterprise.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway-enterprise.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.overrides.golden.yaml, app/kumactl/data/install/k8s/gateway-kong-enterprise/kong-enterprise/kong-enterprise.yaml, app/kumactl/data/install/k8s/gateway-kong/kong/kong.yaml
Validation service is not required since there is no validation hook.
=> chore(kumactl) remove validation service from install kong

deployments/charts/kuma/README.md, deployments/charts/kuma/templates/_helpers.tpl, deployments/charts/kuma/templates/pre-delete-webhooks.yaml, deployments/charts/kuma/templates/pre-install-patch-namespace-job.yaml, deployments/charts/kuma/templates/pre-upgrade-install-missing-crds-job.yaml, deployments/charts/kuma/values.yaml
The `kubectl` image needed for Helm upgrades, is now configurable in the values.yaml
=> chore(helm) parametrize bitnami/kubectl

app/kumactl/cmd/install/testdata/install-gateway-enterprise.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway-enterprise.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-logging.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-logging.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-tracing.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-tracing.overrides.golden.yaml, app/kumactl/data/install/k8s/gateway-kong-enterprise/kong-enterprise/kong-enterprise.yaml, app/kumactl/data/install/k8s/gateway-kong/kong/kong.yaml, app/kumactl/data/install/k8s/logging/loki/loki.yaml, app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml, app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml, app/kumactl/data/install/k8s/metrics/prometheus/node-exporter.yaml, app/kumactl/data/install/k8s/metrics/prometheus/pushgateway.yaml, app/kumactl/data/install/k8s/metrics/prometheus/server.yaml, app/kumactl/data/install/k8s/tracing/jaeger/all-in-one-template.yaml
Loki 2.1.0 -> 2.2.1
Grafana 7.4.3 -> 7.5.8
Prometheus 2.25.0 -> 2.27.1
Jaeger 1.22 -> 1.23
Kong GW 2.3 -> 2.4
KIC 1.2 -> 1.3
=> chore(*) bump versions of logging, metrics, tracing

test/e2e/externalservices/testdata/externalservice-http-server.yaml, test/e2e/externalservices/testdata/externalservice-https-server.yaml
Add the namespace resource to the external service deployment YAML so
that it can be applied as a single step without any manual prerequisites.
N/A
N/A
N/A
```
$ k get ns
NAME                 STATUS   AGE
default              Active   2d18h
kube-node-lease      Active   2d18h
kube-public          Active   2d18h
kube-system          Active   2d18h
kuma-system          Active   2d17h
local-path-storage   Active   2d18h
```
```
$ k apply -f test/e2e/externalservices/testdata/externalservice-http-server.yaml
namespace/externalservice-namespace created
service/externalservice-http-server created
deployment.apps/externalservice-http-server created
```
```
$ k apply -f test/e2e/externalservices/testdata/externalservice-https-server.yaml
namespace/externalservice-namespace unchanged …
```
=> chore(tests) add namespace to test deployments

go.mod, go.sum, pkg/kds/server/server_test.go
Drop the accidental dependency on gogo/protobuf, since we are using
golang/protobuf everywhere.
N/A
N/A
N/A
=> chore(*) drop gogo/protobuf dependency

docs/proposals/rate-limit.md
Proposal on the new Rate Limit policy (or maybe Rate Limiting?)
=> Rate Limit proposal

.circleci/config.yml
Upload coverage data in the integration test job.
There's a little subtlety here that we may want to clean up. Since codecov stores coverage data for comparison, we want the comparison base to be consistent. However, the integration job takes the test targets as parameters, so for the `kuma-commit` workflow we will get coverage for both "integration" and "test" targets, but for `kuma-master` and `kuma-release` workflows the coverage for the "test" target will be omitted.
Since the integration job looks like a superset of the test job, we could just combine these into the same job. We need the "test" target for coverage since that's the only thing that crosses module boundaries.
N/A
Fix #2058 
N/A
Checked out the codecov comments below.
=> chore(*) upload coverage data to codecov

app/kumactl/cmd/install/install_control_plane.go, app/kumactl/cmd/install/install_crds.go, app/kumactl/cmd/install/install_dns.go, app/kumactl/pkg/install/k8s/client_config.go
For the purposes of the CNI, we need this function to be more configurable.
=> chore(*) extend Default K8s client

pkg/xds/envoy/clusters/v3/client_side_tls_configurer.go, pkg/xds/envoy/clusters/v3/client_side_tls_configurer_test.go, pkg/xds/envoy/tls/v3/tls.go
Some External Services like AWS Lambda are hidden behind a load balancer that requires SNI to route the traffic.
This PR adds an SNI header when TLS is enabled.
=> feat(kuma-cp) add SNI to TLSed ExternalServices

pkg/xds/generator/dns_generator.go, pkg/xds/generator/dns_generator_test.go, pkg/xds/generator/testdata/dns/1-dataplane.input.yaml, pkg/xds/generator/testdata/dns/1-envoy-config.golden.yaml, test/e2e/deploy/kuma_deploy_global_zone.go, test/e2e/externalservices/externalservices_kubernetes.go, test/e2e/externalservices/externalservices_multizone_universal.go, test/e2e/externalservices/externalservices_universal.go, test/e2e/healthcheck/hybrid/healthcheck_hybrid.go, test/e2e/healthcheck/universal/policy_http.go, test/e2e/healthcheck/universal/policy_tcp.go, test/e2e/helm/kuma_helm_deploy_autoscaling.go, test/e2e/helm/kuma_helm_deploy_global_zone.go, test/e2e/helm/kuma_helm_deploy_multi_apps.go, test/e2e/helm/kuma_helm_deploy_multi_apps_test.go, test/e2e/hybrid/kuma_hybrid.go, test/e2e/kic/kubernetes/kong_ingress.go, test/e2e/tracing/tracing_kubernetes.go, test/e2e/trafficpermission/hybrid/traffic_permission_hybrid.go, test/framework/interface.go, test/framework/setup.go, test/framework/universal_cluster.go
Kuma CP DNS resolved `echo-server_kuma-test_svc_80.mesh` as well as `echo-server.kuma-test.svc.80.mesh`. Kuma DP builtin DNS resolver only resolved the first option.
=> fix(kuma-cp) builtin DNS resolve alias with dots

.circleci/config.yml
To upload multiple coverage files, we need to pass the glob to the codecov -f flag, and not let the shell expand the glob beforehand.
N/A
N/A
N/A
Manually inspected codecov logs and coverage data.
=> fix(ci) fix codecov coverage file quoting

pkg/plugins/resources/k8s/native/pkg/test/within.go
This fix was accidentally dropped from the review feedback in #2043. It
serves me right that I had to debug this when an assertion failed and
Ginkgo paniced.
N/A
N/A
N/A
=> fix(*) enable Ginkgo recovery in goroutines

deployments/charts/kuma/templates/cni-configmap.yaml
As the binary is always called `kuma-cni` it will cause problems with the different names
=> fix(*) cni config - set constant name

api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, pkg/core/resources/apis/mesh/dataplane_overview_helpers.go, pkg/kds/util/resource.go
Remove the (*Dataplane) ProxyType(), which makes the concept of proxy
types confusing.
Since the introduction of ZoneIngress, there are two distinct proxy
types used by kuma-dp - Dataplane and ZoneIngress. Since these are
distict Go and Protobuf types, (*Dataplane) ProxyType() can't ever
return `IngressProxyType`, and by extension should never return
anything other than `DataplaneProxyType`.
To clarify the distinction, we use (*Dataplane) IsGateway(), which
indicates a Dataplane proxy type operating in gateway mode and matches
the existing IsIngress() API.
N/A
N/A
N/A
=> chore(*) remove Dataplane ProxyType accessor

app/kuma-dp/cmd/run.go, app/kuma-dp/cmd/run_test.go, pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-dp/config_test.go
Validate that the kuma-dp proxy type nust be "ingress" or "dataplane".
* Fix kuma-dp `--proxy-type` flag validation
N/A
N/A
=> fix(kuma-dp) validate the DP proxy type

CHANGELOG.md, UPGRADE.md
Leaving the note that during the multizone upgrade ZoneIngress will be offline, which does not affect the cross-zone traffic.
We are not releasing the version with `v` this time so removing this entry from the changelog.
=> docs(*) upgrade guide for 1.2.1

app/kuma-dp/cmd/dataplane.go, app/kuma-dp/cmd/run.go, app/kuma-dp/cmd/run_test.go, pkg/core/resources/model/rest/resource.go
Refactor the dataplane resource loading to make it oblivious to
the underlying resource types. This will later allow us to add
support for more dataplane resource types without changing any
code.
N/A
N/A
N/A
=> chore(kuma-dp) refactor dataplane resource loading

pkg/sds/server/v3/server.go, pkg/xds/auth/callbacks.go, pkg/xds/server/v3/components.go
Authentication callbacks don't need to update a resource manager,
so narrow the required interface to ReadOnlyResourceManager.
N/A
N/A
N/A
=> chore(kuma-dp) narrow the resource manager interface for auth

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/config/multizone/kds.go, pkg/config/multizone/multicluster.go, pkg/kds/mux/client.go, pkg/kds/mux/server.go
The default message limit for the gRPC stream is 4MB, which may not be enough for KDS. All resources of a given type are sent in one message (wildcard xDS subscription).
I changed the limit to 10MB and added a parameter to change it.
Without the change, I managed to hit a limit by putting gigantic TrafficPermissions (1000 lines for 1 resource) into global CP. After 350 resources the limit was hit. After the change, I hit the limit after 800 resources.
In practice, we can hit this limit with DataplaneInsights which are pretty big. In the next PR, I'll change the subscription limit for dataplane insights which will be a second thing to help with this problem.
=> feat(kuma-cp) change KDS max message limit

pkg/kds/global/components.go, pkg/kds/server/server_test.go, pkg/kds/types.go, pkg/kds/zone/components.go
Sort some of the lists of resource types that need to be updated when
adding new resources. This makes it easier to scan for duplicates and
absentees. Update some of the corresponding godoc comments.
This is a functional no-op of changes I've extracted from a private branch.
The main thing to look at is the godoc comments, where my explanations
might be wrong. 
N/A
N/A
N/A
=> chore(*) sort lists of resource types

pkg/core/xds/metadata.go, pkg/xds/server/callbacks/dataplane_lifecycle.go
Rather than keeping separate typed fields in the Dataplane metadata
for the Dataplane and ZoneIngress resources, store a generic Resource
interface and return the underlying type through the accessors.
N/A
N/A
N/A
=> chore(kuma-cp) refactor xDS metadata to store a generic resource

pkg/xds/bootstrap/generator.go
Hds would be globally disabled on the dpserver when bootstraping a zone-ingress
Hds would be globally disabled on the dpserver when bootstraping a zone-ingress
* fix(kuma-cp) fix hds disabled on dpserver
=> fix(kuma-cp) fix hds disabled on dpserver

pkg/hds/authn/callbacks_test.go, pkg/xds/auth/callbacks.go, pkg/xds/auth/callbacks_test.go, pkg/xds/auth/interfaces.go, pkg/xds/auth/k8s/authenticator.go, pkg/xds/auth/universal/authenticator.go, pkg/xds/auth/universal/noop_authenticator.go
There are two proxy types that can be authenticated and in the future there may be more. Rather than adding a new method for authenticating each proxy type, switch to authenticating a generic model Resource and allow each authenticator implentation to type switch internally.
This allows the xDS authentication callbacks to be insensitive to the DP proxy type, except when fetching an existing resource, which needs to allocate an instance of the concrete type.
The other approach I considered was making each `Authenticator` implementation responsible for a authenticating a single type, then using a factory interface to choose the right instance. I didn't go with that, since there was more scaffolding and the benefits over the internal type switch weren't very clear.
N/A
N/A
N/A
=> chore(*) make the authentication interface type oblivious

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
I think we overestimated the usefulness of DataplaneInsights subscriptions history.
Most of the time we check the current subscription for online/offline status, but not the previous ones.
Currently, there is a limit of 10 subscriptions in Insight. This can result in fairly big insight objects. Especially when we have many dataplanes and we are syncing Insights over KDS to global.
I think it's better to change the default subscriptions to 2. One for the current one and one before that.
For ZoneInsight I think we can leave 10, because we usually have only a few zones, maybe tens, not thousands like dataplanes. Also, we don't sync this over KDS.
=> chore(kuma-cp) change default number of insights subscriptions

tools/releases/make-release-tag.sh
Update the release tagging script to allow an optional qualifier string
after a hyphen.
N/A
N/A
N/A
```bash
$ ./tools/releases/make-release-tag.sh 1.2.0 v9.9.0-rc1
Created tag 'v9.9.0-rc1'.
Testing whether tag 'v9.9.0-rc1' can be pushed.
To github.com:kumahq/kuma.git
* [new tag]           v9.9.0-rc1 -> v9.9.0-rc1
Run 'git push origin v9.9.0-rc1' to push the tag if you are happy.
$ git show v9.9.0-rc1 | head
tag v9.9.0-rc1
Tagger: James Peach <james.peach@konghq.com>
Date:   Tue Jun 29 07:56:15 2021 +1000
Tag v9.9.0-rc1 release.
Bart Smykla (4):
chore(kuma-cp) new version of gui (#2187)
fix(kuma-cp) supported versions fix (#2193)
chore(kuma-cp) new gui version (#2219)
```
=> fix(*) allow RC tags in the release tagging script

pkg/log/logger.go
While stress testing KDS I noticed that some logs about creating resources are missing.
After more investigation, it turned out that even with a simple loop
```
for i := 0; i < 200; i++ {
core.Log.Info("test", "x", i)
}
```
we are dropping logs after 100.
It's because we have log sampling enabled.
>Why sample application logs?
Applications often experience runs of errors, either because of a bug or because of a misbehaving user. Logging errors is usually a good idea, but it can easily make this bad situation worse: not only is your application coping with a flood of errors, it's also spending extra CPU cycles and I/O logging those errors. Since writes are typically serialized, logging limits throughput when you need it most.
>
>Sampling fixes this problem by dropping repetitive log …
=> chore(kuma-cp) disable log sampling

pkg/core/policy/connection_matcher.go
Return a ServiceIterator interface rather than a concrete
ServiceItoratorFunc, since the former is the abstraction
that matters.
N/A
N/A
N/A
=> chore(*) clean up ServiceIterator usage

pkg/xds/generator/proxy_template_raw_source_test.go
Protobuf error strings are deliberately unstable in order to discourage
code from binding to their contents. Stop binding to the full error string
in this test, since unrelated changes can trigger changes in the protobuf
error strings (the deterministic random package that enables error string
instability is seeded from a hash of the Go binary).
N/A
N/A
N/A
=> test(*) fix protobuf error string comparison

docs/guides/e2e-test-tips.md, mk/build.mk, mk/dev.mk, mk/e2e.new.mk, mk/k3d.mk, mk/kind.mk
The integration tests depend on kubeconfig files being written to ~/.kube,
so remove the Makefile configurability of these since it can't ever work.
Add a target to generate a .envrc file to work with the e2e clusters
more easily.
N/A
N/A
N/A
E2E tests are failing for me locally with a docker problem, but CI seems happy.
=> fix(e2e) clean up KUBECONFIG handling

.github/PULL_REQUEST_TEMPLATE.md
Add a reminder to think about backwards compatibility and either add `backport-to-stable` or list breaking changes.
=> docs(*) add backwards compatibility to PR template

pkg/core/runtime/component/component.go, pkg/plugins/leader/postgres/leader_elector.go, pkg/plugins/runtime/universal/outbound/outbound.go, test/e2e/resilience/leader_election_postgres.go, test/e2e/resilience/leader_election_postgres_test.go, test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/k8s_clusters.go, test/framework/k8s_controlplane.go, test/framework/universal_cluster.go, test/framework/universal_clusters.go, test/framework/universal_controlplane.go
We were not stopping leader components on the lost leader event. 
This only affects Universal deployments, Kubernetes CP is killed when the leader is lost.
In a case when there are 2 instances (CP1, CP2)
1) CP1 is a leader, CP2 is not
2) Postgres is down
3) CP1 was still running leader components although there should be no leader in this case
4) CP1 has troubles connecting to Postgres but CP2 can connect
5) CP1 and CP2 is now a leader.
It's not that CP1 leader without Postgres connection can do much, but that should not be the case.
=> fix(kuma-cp) stop components on leader election lost

app/kumactl/cmd/completion/completion_test.go, app/kumactl/cmd/install/install_control_plane_test.go, app/kumactl/cmd/install/install_crds_test.go, app/kumactl/cmd/install/install_demo_test.go, app/kumactl/cmd/install/install_gateway_test.go, app/kumactl/cmd/install/install_logging_test.go, app/kumactl/cmd/install/install_metrics_test.go, app/kumactl/cmd/install/install_tracing_test.go, app/kumactl/cmd/install/install_transparent_proxy_test.go, app/kumactl/cmd/uninstall/uninstall_transparent_proxy_test.go
If we assert that kumactl standard error is empty using a byte buffer,
then the Ginkgo error shows a hex dump, which isn't that easy to read.
Switch to checking for an empty standard error string so that Ginkgo
shows any error messages directly in the test failure.
N/A
N/A
N/A
=> fix(kumactl) use strings for stderr output test check

pkg/dns/outbound.go, pkg/dns/outbound_test.go, pkg/dns/resolver/resolver.go, pkg/dns/server_test.go, pkg/dns/vips/interfaces.go, pkg/dns/vips/persistence.go, pkg/dns/vips/persistence_test.go, pkg/dns/vips/vips_suite_test.go, pkg/dns/vips_allocator.go, pkg/dns/vips_allocator_test.go, pkg/dns/vips_synchronizer_test.go, pkg/plugins/runtime/universal/outbound/outbound_test.go, pkg/xds/generator/dns_generator.go, pkg/xds/generator/dns_generator_test.go, test/e2e/externalservices/externalservices_universal.go, test/framework/deployments/externalservice/deployment.go, test/framework/deployments/externalservice/kubernetes.go, test/framework/deployments/externalservice/universal.go, test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/k8s_clusters.go, test/framework/universal_cluster.go, test/framework/universal_clusters.go
Kuma allocates VIP on every new service. Every ExternalService represents a single Kuma service. If we have 2 ExternalServices:
```yaml
type: ExternalService
mesh: default
name: external-service-1
tags:
kuma.io/service: external-service-1
networking:
address: host.com:80
---
type: ExternalService
mesh: default
name: external-service-2
tags:
kuma.io/service: external-service-2
networking:
address: host.com:81
```
Then 2 VIPs will be allocated: `external-service-1: 240.0.0.1, external-service-2: 240.0.0.2`.
It will work fine while we consume services using `.mesh` domain. But if we'd like to consume services using `host.com`. Built-in DNS feature will resolve `host.com` either to `240.0.0.1` or `240.0.0.2`, so one of the services won't work properly.
Current PR introduces a new type of …
=> fix(kuma-cp) allocate a new VIP for ExternalService host

mk/k3d.mk, mk/kind.mk
In #2084, we unexported KUBECONFIG so that targets would not use
the setting from the external environment. However, "kumactl install"
depends on KUBECONFIG, and not all the makefile targets were setting it
explictly. Update the remaining uses so that "kumactl install" always
targets the correct test cluster.
N/A
N/A
N/A
=> fix(ci) set KUBECONFIG for kumactl install

pkg/core/bootstrap/bootstrap.go, pkg/core/resources/manager/customizable_manager.go
This refactoring is a bit gratuitous, so I'm not that concerned if we don't want to merge it :-)
I was reading the resource manager setup and it was confusing how the type map was still being initialized after already being "consumed" by customizable resource manager.
N/A
N/A
N/A
=> chore(*) improve resource manager initialization readability

pkg/log/logger.go
When we are in debug logging mode, update the underlying zap log level
so that verbose logs up to level 10 will be emitted.
This fixes #2350
N/A
N/A
N/A
```
2021-07-12T15:53:53.666+1000	LEVEL(-2)	proxy-template-resolver	falling back to the default ProxyTemplate since there is no best match	{"dataplane": {"Mesh":"default","Name":"greenling"}, "templates": null}
```
=> fix(*) allow verbose log levels

app/kumactl/cmd/install/context/install_tracing_context.go, app/kumactl/cmd/install/install.go, app/kumactl/cmd/install/install_tracing.go, app/kumactl/pkg/cmd/root_context.go
refactor kumactl install tracing to move arguments to separate context
* [Fix ...]
Fix #XXX
=> refactor(kumactl) add install tracing context

CHANGELOG.md
Update the changelog for the latest release of kuma (1.2.2)
* [Fix ...]
Fix #XXX
=> chore(*) update CHANGELOG.md for kuma 1.2.2

pkg/dns/vips/interfaces.go
Improve the VIP entry stringer so that it show the name of the entry
type. This is shown in logs, where having the type name is a lot clearer.
N/A
N/A
N/A
=> chore(kuma-cp) improve VIP interface logging

pkg/xds/envoy/listeners/v3/tls_inspector_configurer.go, pkg/xds/generator/testdata/admin/01.envoy-config.golden.yaml, pkg/xds/generator/testdata/ingress/01.envoy.golden.yaml, pkg/xds/generator/testdata/ingress/02.envoy.golden.yaml, pkg/xds/generator/testdata/ingress/03.envoy.golden.yaml, pkg/xds/generator/testdata/ingress/04.envoy.golden.yaml, pkg/xds/generator/testdata/ingress/05.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
The TLS Inspector has its own typed config protobuf that we should use
for the filter rather than an empty protobuf.
N/A
N/A
N/A
=> fix(*) use the typed config for TLS Inspector

pkg/xds/envoy/listeners/configurers.go, pkg/xds/envoy/listeners/filter_chain_builder.go, pkg/xds/envoy/listeners/listener_builder.go
Add adaptors for the listener and filter chain configurers so that every
call site doesn't need to bounce through the the corresponding builder
configuration API.
N/A
N/A
N/A
=> chore(*) add xDS configurer adaptors

api/mesh/v1alpha1/dataplane_helpers.go, pkg/config/app/kuma-dp/config_test.go, pkg/xds/bootstrap/generator.go, pkg/xds/sync/dataplane_watchdog.go
The GatewayProxyType constant is not actually used anywhere, and creates
some confusion with a dataplane operating in gateway mode. Delete it to
remove any ambiguity.
N/A
N/A
N/A
=> chore(*) remove the GatewayProxyType constant

pkg/xds/envoy/listeners/configurers.go, pkg/xds/envoy/listeners/v3/http_route_configurer_test.go
Update the remaining listener configurer helpers. These were omitted from
previous PRs due to merge conflicts.
N/A
N/A
N/A
=> chore(*) update remaining listener filter helpers

pkg/xds/envoy/listeners/configurers.go, pkg/xds/envoy/listeners/v3/configurer.go, pkg/xds/envoy/listeners/v3/listener_configurer_test.go
Add listener configurer helper adapters and some miscellaneous
configurers to set Listener fields.
N/A
N/A
N/A
=> fix(kuma-cp) add more listener configurers

pkg/xds/server/callbacks/dataplane_status_tracker.go
Signed-off-by: Aadhav Vignesh <aadhav.n1@gmail.com>
rename logger names to be consistent in the xDS server package 
* [Fix ...]
Updates #2313
=> refactor(xds) rename logger to have consistent naming style

app/kuma-cp/cmd/root.go, app/kuma-dp/cmd/root.go, app/kuma-prometheus-sd/cmd/root.go
When using a log output directory, the informational startup message
did not end in a newline, which causes garbled output if there is a
subsequent error. Add a newline and take the opportunity to quote and
emit the absolute log output path.
N/A
This updates #2391.
N/A
=> chore(*) fix information log output message format

pkg/mads/server/server_test.go
It was using a sequential port selection which was causing
problems when running tests in parallel
=> fix(test): use port 0 binding for mads test

pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.ipv6.golden.yaml
In some cases, when zone-ingress pod in kubernetes was restarted in parallel with zone-cp and if it was very quickly recreated it was able to connect to old instance of zone-cp and as the default values for keep-alive stands that it will start sending keep-alive probes after 2h, so it was possible that our TCP connection will be in half-closed state.
=> fix(kuma-cp) set better keep-alive for bootstrap

pkg/xds/sync/dataplane_watchdog.go, pkg/xds/sync/xds_context_builder.go
https://github.com/kumahq/kuma/pull/2342/files#diff-4e677d8a7546b3383197877f4c14437d4b356b1ef10a13d7c81fdc8e05b45632R65 was merged without resolving the todo.
In a case when we spin down data plane proxy, technically we can remove connection info from the map and still have one more `Sync` in DP watchdog. When this happens, CP fails.
=> fix(kuma-cp) handle missing connection info

app/kumactl/cmd/config/config_control_planes_switch_test.go
This test failure is a result of the combination of #2419 and #2438.
The fix is to test for error output using a substring match, which was
already done in most places in #2438, but this instance was overlooked.
N/A
N/A
NA
=> fix(ci) kumactl test output matching

CHANGELOG.md
=> chore(*) Kuma 1.2.3 changelog

pkg/core/resources/apis/mesh/dataplane_validator.go, pkg/core/resources/apis/mesh/dataplane_validator_test.go, pkg/core/resources/apis/mesh/externalservice_validator.go, pkg/core/resources/apis/mesh/externalservice_validator_test.go, pkg/core/resources/apis/mesh/mesh_validator.go, pkg/core/resources/apis/mesh/validators.go, pkg/core/resources/apis/mesh/zone_ingress_validator.go, pkg/core/resources/apis/mesh/zone_ingress_validator_test.go
Introduce a helper to make TCP/UDP port validation checks
consistent across the API.
N/A
N/A
N/A
=> chore(*) make port validation consistent

.circleci/config.yml, .golangci.yml, mk/check.mk, mk/kind.mk, mk/run.mk
govet already runs as part of golangci-lint, so we can save some time
by not running the stand-alone version.
N/A
N/A
N/A
N/A
=> chore(ci) drop explicit govet runs

pkg/api-server/definitions/all.go, pkg/api-server/definitions/api.go, pkg/api-server/definitions/circuit_breaker.go, pkg/api-server/definitions/dataplane.go, pkg/api-server/definitions/dataplane_insight.go, pkg/api-server/definitions/definition.go, pkg/api-server/definitions/external_service.go, pkg/api-server/definitions/fault_injection.go, pkg/api-server/definitions/global_secret.go, pkg/api-server/definitions/health_check.go, pkg/api-server/definitions/mesh.go, pkg/api-server/definitions/mesh_insight.go, pkg/api-server/definitions/proxytemplate.go, pkg/api-server/definitions/rate_limit.go, pkg/api-server/definitions/retry.go, pkg/api-server/definitions/secret.go, pkg/api-server/definitions/service_insight.go, pkg/api-server/definitions/timeout.go, pkg/api-server/definitions/traffic_log.go, pkg/api-server/definitions/traffic_permission.go, pkg/api-server/definitions/traffic_route.go, pkg/api-server/definitions/traffic_trace.go, pkg/api-server/definitions/zone-ingress.go, pkg/api-server/definitions/zone.go, pkg/api-server/definitions/zone_insight.go, pkg/api-server/resource_endpoints.go, pkg/api-server/sample_resource_definition_test.go, pkg/api-server/server.go, pkg/api-server/service_insight_endpoints.go
- Remove unused `Name` and extract methods to remove repetitive factory code
- Add readOnly switches in the server init rather than split in 2 different places
It's a refactor and the original coverage is pretty good already.
=> chore(kuma-cp): simplify resourceWsDefinition and server init

api/mesh/v1alpha1/dataplane_helpers.go
Add TextMarshaler implementations for types that are uses as map keys.
These types are marshaled to JSON for logging, and the map key conversion
in this case requires encoding.TextMarshaler to be implemented. It is
quite confusing for users to see a marshaling error in the Kuma logs,
since it is difficult to distinguish from a real Kuma error.
* Fix the error message formatting for xDS snapshot generation failure
Fix #2374.
N/A
=> fix(*) implement TextMarshaler for JSON keys

pkg/core/resources/registry/registry.go
Fix the invalid resource type error message to include the type
that was requested.
N/A
N/A
N/A
=> fix(*) clarify invalid resource type message

app/kumactl/cmd/gateway.go, app/kumactl/cmd/root.go, app/kumactl/pkg/cmd/find.go, app/kumactl/pkg/cmd/plugin.go, mk/build.mk, pkg/kds/global/components_test.go, pkg/kds/server/server_test.go, pkg/kds/zone/components_test.go, pkg/plugins/resources/k8s/consistent_kind_type_test.go, pkg/plugins/runtime/gateway/enabled.go, pkg/plugins/runtime/gateway/kumactl/plugin.go, pkg/test/kds/samples/resources.go
When the build flag is enabled, register the Gateway resource in the
kuma-cp and in kumactl. The latter adds a simple hook to let the plugin
modify the kumactl commands. This is likely to be refactored away as
more of the type bindings are generated.
N/A
N/A
N/A
=> feat(*) register the gateway resource type

pkg/plugins/runtime/k8s/util/util.go, pkg/plugins/runtime/k8s/util/util_test.go
The default sort in k8s is by CreationTimestamp.
In the case of a deployment created in 2 different k8s clusters if
the services were not created in the same order the inbounds would be
generated in a different order which was confusing to the user.
We therefore sort services by name which will always be correct across zones.
- For regular dataplanes it ensures that the resources are the same regardless of the order in which k8s services were created
- For gateways it ensures that the service name of the gateway is the same (as it's derived from the first service that matches).
Fix #2500 and #2170
=> fix(kuma-cp): Sort services by name when selecting them

test/e2e/compatibility/dp_compatibility_universal.go, test/e2e/deploy/kuma_deploy_global_zone.go, test/e2e/deploy/kuma_deploy_universal.go, test/e2e/deploy/kuma_deploy_universal_transparent_proxy.go, test/e2e/healthcheck/hybrid/healthcheck_hybrid.go, test/e2e/healthcheck/universal/panic.go, test/e2e/healthcheck/universal/policy_http.go, test/e2e/healthcheck/universal/policy_tcp.go, test/e2e/healthcheck/universal/service_probes.go, test/e2e/helm/kuma_helm_deploy_global_zone.go, test/e2e/helm/kuma_helm_deploy_multi_apps.go, test/e2e/hybrid/kuma_hybrid.go, test/e2e/hybrid/kuma_hybrid_kube_global.go, test/e2e/kic/kubernetes/kong_ingress.go, test/e2e/ratelimit/ratelimit_universal.go, test/e2e/retry/retry_universal.go, test/e2e/timeout/timeout_universal.go, test/e2e/tracing/tracing_kubernetes.go, test/e2e/tracing/tracing_universal.go, test/e2e/trafficpermission/hybrid/traffic_permission_hybrid.go, test/e2e/trafficpermission/universal/traffic_permission_universal.go, test/e2e/trafficroute/universal_multizone/traffic_route.go, test/e2e/trafficroute/universal_standalone/traffic_route.go, test/framework/deployments/testserver/deployment.go, test/framework/deployments/testserver/kubernetes.go, test/framework/setup.go, test/framework/universal_cluster.go
So far we were using netcat as our "HTTP server", but this has caused several problems with testing.
Sometimes netcat was randomly failing. One time we forgot to add content-length header to the response etc, etc.
In the end, we figured out that we should use real HTTP server that has valid RFC implementation that supports connection pooling etc.
Some time ago, @lobkovilya introduced Test Server that is just Go application that uses HTTP server.
This PR replaces all usages of ncat as a test server.
It's already hard enough to get stable E2E tests, so this PR eliminates one of the problems.
I implemented Test Server on K8S as Deployment. I would love to do the same for Universal but it requires further refactor.
Note that netcat is still used for DemoClient but it's not really used, since …
=> chore(tests) replace ncat with test server

app/kumactl/cmd/install/context/install_logging_context.go, app/kumactl/cmd/install/install.go, app/kumactl/cmd/install/install_logging.go, app/kumactl/pkg/cmd/root_context.go
Move kumactl logging args out into context. This is needed for parameterization and consistent with other commands.
=> chore(logging) Move args to where they can be parameterized

mk/build.mk, mk/dev.mk
Automatically add the test-server build to the local path using the
`dev/envrc` build target.
N/A
N/A
N/A
=> chore(ci) add test-server envrc support

pkg/plugins/runtime/gateway/listener_generator.go, pkg/plugins/runtime/gateway/listener_generator_test.go, pkg/plugins/runtime/gateway/route_generator.go, pkg/plugins/runtime/gateway/suite_test.go, pkg/plugins/runtime/gateway/testdata/01-gateway-listener.yaml, pkg/plugins/runtime/gateway/testdata/02-gateway-listener.yaml, pkg/plugins/runtime/gateway/testdata/03-gateway-listener.yaml, pkg/plugins/runtime/gateway/testdata/04-gateway-listener.yaml, pkg/plugins/runtime/gateway/testdata/dataplane-logging.yaml, pkg/plugins/runtime/gateway/testdata/dataplane-tracing.yaml, pkg/plugins/runtime/gateway/testdata/mesh-logging.yaml, pkg/plugins/runtime/gateway/testdata/mesh-tracing.yaml, pkg/plugins/runtime/gateway/testdata/trafficlog.yaml, pkg/plugins/runtime/gateway/testdata/traffictrace.yaml, pkg/xds/envoy/listeners/v3/configurer.go, pkg/xds/envoy/names/resource_names.go, pkg/xds/sync/components.go, pkg/xds/sync/dataplane_proxy_builder.go, pkg/xds/sync/dataplane_watchdog.go
Implement the initial Gateway listener generator. Match Gateway resources
to the corresponding Dataplanes and generate listener xDS resources.
N/A
N/A
N/A
=> feat(kuma-cp) generate gateway listeners

pkg/core/resources/store/options.go, pkg/kds/store/sync.go, pkg/plugins/common/k8s/names.go, pkg/plugins/resources/k8s/store.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller_test.go, test/e2e/trafficpermission/kubernetes/e2e_suite_test.go, test/e2e/trafficpermission/kubernetes/traffic_permission_k8s.go, test/e2e/trafficpermission/kubernetes/traffic_permission_k8s_test.go
In the k8s controller, we're filtering events by their type (Create, Update, ...), but apparently, these events are related to the underlying Informer, so in our case, we will receive Create event every time Kuma CP restarts. This means that the default policy deleted by the user will be recreated after the Kuma CP restart.
Current PR annotates every mesh that was processed.
* add `k8s.kuma.io/processed` annotation for Meshes
* cleanup stuff related to `k8s.kuma.io/synced` annotations since it's not used anymore
N/A
=> fix(kuma-cp) deleted default policy is created on Kuma CP restart

app/kuma-dp/pkg/dataplane/command/build_command.go, pkg/util/os/limits.go, pkg/util/os/limits_windows.go
With this changes `kuma-cp` and `kuma-dp` can be compiled on and for windows
no issue resolved, but I think these one are related:
- https://github.com/kumahq/kuma/issues/365
- https://github.com/kumahq/kuma/issues/366 (this one at least partially)
no documentation changes
=> feat(*) prepare kuma-[cd]p for windows compilation

pkg/xds/server/callbacks/dataplane_lifecycle.go, pkg/xds/server/callbacks/dataplane_lifecycle_test.go
In the DataplaneLifecycle tracker, consistently lock the map that
tracks whether the dataplane has been successfully registered.
* Fix a crash when multiple Dataplanes register concurrently
Fix 2566
N/A
=> fix(kuma-cp) Fix DP tracking lock consistency

test/e2e/deploy/kuma_deploy_universal.go, test/e2e/trafficroute/universal_multizone/traffic_route.go
Locality aware loadbalancing tests were flaky because they were assuming that config is propagated from CP to DP in 0ms.
I've rewritten and moved the test to TrafficRoutes where we have proper test infra to test loadbalancing.
When I did that, I noticed that we have a problem with fair loadbalancing, for which I filed an issue on Github.
The solution is not in the scope of this PR, with this PR I wanted to fix flaky test.
No issues
=> tests(*) fix flaky test for locality aware loadbalancing

.golangci.yml, pkg/plugins/ca/builtin/manager.go, pkg/plugins/ca/builtin/manager_test.go, pkg/tokens/builtin/issuer/issuer.go, pkg/tokens/builtin/issuer/signing_key.go, pkg/tokens/builtin/server/webservice.go, pkg/tokens/builtin/server/webservice_test.go, pkg/tokens/builtin/zoneingress/signing_key.go
The default configuration for golangci-lint skips directories named
"builtin" (see the `--skip-dirs-use-default` flag). Disable that so
that we can get full lint coverage.
N/A
N/A
N/A
=> chore(ci) lint "builtin" directories

pkg/core/resources/apis/mesh/dataplane_validator.go, pkg/core/resources/apis/mesh/dataplane_validator_test.go
When the `networking` section was not set we were panicking
* add a nil check and a validation error.
=> fix(cp): Avoid nil dereferencing in dp validator

pkg/plugins/ca/provided/ca_cert_validator.go, pkg/plugins/ca/provided/ca_cert_validator_test.go, test/e2e/mtls/universal/e2e_suite_test.go, test/e2e/mtls/universal/mtls_backends.go, test/e2e/mtls/universal/mtls_backends_test.go
Introduce support for Intermediate CA in Provided backend.
* Remove CA validators
* Add Intermediate CA test
Fix #759
=> feat(kuma-cp) Intermediate CA support

test/framework/constants.go, test/framework/deployments/tracing/kubernetes.go
This constant needs to be up in the global constants list to be overridden.
=> tests(kumactl) Allow kuma-specific const to be overridden

test/framework/k8s_controlplane.go
Signed-off-by: Bart Smykla <bartek@smykla.com>
it was wrong, as with just UseLoadBalancer set it was ignored
and the local port of kuma-cp used instead, which broke e2e tests
on AKS
no changelog
no issue
- no documentation
=> fix(e2e) get kds address for k8s fix

app/kumactl/cmd/root.go, pkg/api-server/customization/customization_suite_test.go, pkg/api-server/index_endpoints.go, pkg/api-server/index_endpoints_test.go, pkg/api-server/resource_api_client_test.go, pkg/api-server/server.go, pkg/api-server/types/index.go
Return instance and cluster IDs in kuma-cp API status.
=> feat(kuma-cp) Return instance and cluster IDs

pkg/xds/envoy/routes/configurers.go, pkg/xds/envoy/routes/virtual_host_builder.go, pkg/xds/envoy/routes/virtual_host_configurer_test.go
- [-] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.
=> feat(kuma-cp) add virtual host domain name configurer

pkg/xds/envoy/listeners/configurers.go, pkg/xds/envoy/listeners/http_connection_manager_configurer_test.go
Add a few HTTP connection manager configurers that are helpful
for gateway use cases.
N/A
N/A
N/A
=> feat(kuma-cp) add simple HTTP connection configurers

pkg/core/runtime/reports/reports.go
We were missing "cause" in logging which caused panic on log-level error.
Partially fix #2594 but we need some general approach to avoid this in the future.
=> fix(kuma-cp) missing key for kv in reports logging

app/kuma-dp/pkg/dataplane/envoy/envoy.go, app/kuma-dp/pkg/dataplane/envoy/envoy_test.go, app/kuma-dp/pkg/dataplane/envoy/testdata/envoy-mock-windows.exit-0.sh
it fixes version parsing for windows
I also added test for windows
no changelog
no issue
=> fix(kuma-dp) improve envoy version parsing

pkg/log/logger.go
This causes DPanic log level to panic which is something we never want
Discovered in: https://github.com/kumahq/kuma/issues/2594
=> fix(log): Don't set zap.Development() in debug log

.circleci/config.yml
Signed-off-by: Bart Smykla <bartek@smykla.com>
The tests for aks/eks were meant to run only for master, so this fixes it, and stops running cleaning jobs twice, every day
no changelog
no issues
=> chore(*) run {a,e}ks e2e workflows only on master

mk/dev.mk
Old link for `make dev/install/kubebuilder` returns 404
* [Fix ...]
Fix #XXX
=> chore(*) replace link to kubebuilder

pkg/core/managers/apis/mesh/mesh_helpers.go, pkg/core/managers/apis/mesh/mesh_manager.go, pkg/core/managers/apis/mesh/mesh_manager_test.go, pkg/core/resources/apis/mesh/mesh_validator.go, pkg/core/resources/apis/mesh/mesh_validator_test.go, pkg/core/secrets/manager/validator_test.go, pkg/plugins/runtime/k8s/controllers/mesh_controller.go, test/e2e/trafficroute/universal_multizone/traffic_route.go
During conversations with our users, we found out that it's confusing to define many backends. Since you cannot switch between them without disabling mTLS at this moment, we can just as well support one.
No fixes.
=> feat(kuma-cp) validate that mesh has only one mtls backend

test/framework/deployments/tracing/kubernetes.go
Parametrize Kuma tracing namespace in ZipkinCollectorURL
No issues.
No docs.
=> chore(tests) parametrize kuma tracing in ZipkinCollectorURL

test/framework/universal_app.go
Not all Docker configurations end up generating a `DOCKER_OUTPUT`
iptables chain. Check whether that chain exists before attempting
to use it for transparent DNS forwarding.
N/A
Fix #2585.
N/A
=> fix(ci) detect whether Docker is using an output chain

test/framework/constants.go, test/framework/env.go
Depending on the makefiles to set the `KUMACTLBIN` environment variable
so that the e2e tests can find kumactl makes it harder to run individual
tests using `go test`. We can automatically detect where the build
artifacts are, and use that path if `KUMACTLBIN` isn't set.
N/A
N/A
N/A
=> fix(ci) improve kumactl path detection

app/kumactl/cmd/install/install_transparent_proxy.go
Add a newline to the transparent proxy install message.
N/A
Update #2625.
N/A
=> fix(kumactl) print a newline with transparent proxy setup message

.golangci.yml, app/kuma-cp/cmd/root.go, app/kuma-cp/cmd/run_test.go, app/kuma-dp/cmd/run_test.go, app/kuma-prometheus-sd/cmd/run_test.go, app/kumactl/cmd/root.go, pkg/core/runtime/reports/reports.go, pkg/dns/vips_synchronizer.go, pkg/envoy/accesslog/v3/field_operator.go, pkg/envoy/accesslog/v3/field_operator_test.go, pkg/envoy/accesslog/v3/format.go, pkg/envoy/accesslog/v3/format_parser_test.go, pkg/kds/server/type_adjust_callbacks.go, pkg/plugins/runtime/k8s/controllers/pod_converter_test.go, pkg/plugins/runtime/k8s/webhooks/defaulter.go, pkg/util/proto/any.go, pkg/util/xds/v3/versioner.go, pkg/util/xds/versioner.go, pkg/xds/bootstrap/generator.go, pkg/xds/cache/cla/cache_test.go, pkg/xds/envoy/listeners/v3/access_log_configurer.go, pkg/xds/generator/prometheus_endpoint_generator.go, test/e2e/trafficroute/universal_multizone/traffic_route.go
Use US locale for the misspell linter.
N/A
N/A
N/A
=> chore(ci) use US locale for misspelling checks

pkg/xds/generator/inbound_proxy_generator.go, pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/template-proxy/1-envoy-config.golden.yaml, pkg/xds/server/v3/testdata/envoy-config.golden.yaml
Just the fact that TLSInspector is configured is causing TCP health checks to fail (mTLS is off)
* configure TLSInspector only when required
N/A
=> fix(kuma-cp) TLSInspector is causing tcp healthcheck failures

pkg/plugins/ca/provided/ca_cert_validator.go, pkg/plugins/ca/provided/ca_cert_validator_test.go
With these changes sub ca be used as provided ca
* [Implement ...] subca
* [Fix ...] https://github.com/kumahq/kuma/issues/2063
Fix https://github.com/kumahq/kuma/issues/2063
=> feat(kuma-cp) remove provided ca cert validation

test/dockerfiles/Dockerfile.universal, tools/releases/distros.sh, tools/releases/dockerfiles/Dockerfile.kuma-dp
It includes latest security patch for high severity cve: https://nvd.nist.gov/vuln/detail/CVE-2021-32779
no changelog
no issue
no documentation change
=> chore(*) update envoy to 1.18.4

.circleci/config.yml
minikube jobs need kumactl image to be present, so I updates this workflow
no changelog
no issues fix
no documentation changes
=> fix(ci) fix kuma-release workflow (minikube jobs)

test/dockerfiles/Dockerfile.universal
rsync is handy for copying binaries into running containers,
so make sure it's already installed.
N/A
N/A
N/A
=> ci(*) add rsync to the kuma-universal container

.circleci/config.yml
docker-images path fix for images-kumactl
no changelog
=> fix(ci) docker-images path fix for images-kumactl

test/e2e/mtls/permissive/e2e_suite_test.go, test/e2e/mtls/permissive/permissive_mode.go, test/e2e/mtls/permissive/permissive_mode_test.go, test/e2e/mtls/standalone_universal_test.go, test/framework/universal_app.go
Why parse IPs if we already have them in UniversalApp. This should fix permissive mTLS tests for ipv6, but I wasn't able to run IPv6 tests on Docker for Mac. 
* move tests to separate suite, otherwise it's not possible to focus a specific test
* get rid of parsing using regex
N/A
N/A
=> fix(kuma-cp) get rid of regex for parsing IPs

pkg/plugins/runtime/k8s/webhooks/validation.go, pkg/plugins/runtime/k8s/webhooks/validation_test.go, test/e2e/deploy/kuma_deploy_global_zone.go
Webhook didn't check DELETE operations on Zone CP
* fix webhook for DELETE
* add unit tests
* extend e2e test
N/A
N/A
=> fix(kuma-cp) possible to delete resources on Zone CP

pkg/insights/resyncer.go, pkg/insights/resyncer_test.go
We were hidding gateway in service-insights.
This was unintuitive and also caused problems by not showing
up in the serviceMap in grafana
* add gateway in service insights computation.
=> fix(service-insights): Show gateway services in service-insights

pkg/xds/cache/cla/cache_test.go
The ClusterLoadAssignment tests were manually doing what the golden JSON
matcher does, so update them to use it.
N/A
N/A
N/A
=> fix(ci) use the golden JSON matcher in CLA tests

pkg/kds/zone/components_test.go, pkg/test/kds/setup/client.go, pkg/test/kds/setup/server.go
When trying to debug KDS tests, it's not very obvious where log
messages are coming from. Make sure to set the logger name on all
the test machinery so that it is easier to find a starting point.
N/A
N/A
N/A
=> fix(ci) set logger names for KDS tests machinery

test/e2e/trafficroute/universal_multizone/traffic_route.go, test/framework/interface.go, test/framework/setup.go, test/framework/universal_app.go, test/framework/universal_cluster.go
Bump the concurrency of Envoy in E2E TrafficRoute tests to have a loadbalancing to every endpoint through ZoneIngress.
- No docs
=> tests(*) bump concurrency to have better loadbalancing

pkg/xds/generator/probe_generator.go, pkg/xds/generator/probe_generator_test.go, pkg/xds/generator/testdata/probe/04.envoy.golden.yaml, test/e2e/healthcheck/kubernetes/e2e_suite_test.go, test/e2e/healthcheck/kubernetes/healthcheck_kubernetes_test.go, test/e2e/healthcheck/kubernetes/virtual_probes.go, test/framework/deployments/testserver/deployment.go, test/framework/deployments/testserver/kubernetes.go, test/framework/setup.go, test/server/cmd/echo.go
When configuring readiness or liveness httpGet probes in Kubernetes `path` could consist of `path + query`, but when configuring `path` for Envoy route matching it's strictly only `path` (without `query`). That's why for probes with `query` matching didn't work properly.
* Fix Envoy configuration
* Add e2e test
N/A
N/A
=> fix(kuma-cp) virtual probes with query

pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.ipv6.golden.yaml
We can save traffic on the wire by setting Node only on the first DiscoveryRequest. The Control Plane is ready to support such a setting, we just never enabled it.
No issue.
=> perf(*) set Node only on the first DiscoveryRequest

pkg/kds/context/context.go, pkg/kds/global/components.go, pkg/kds/mux/server.go
The ability to add many Callbacks was removed here https://github.com/kumahq/kuma/pull/2573
This PR brings back this functionality as more explicit Filters.
=> chore(kuma-cp) KDS global mux filters

pkg/plugins/runtime/gateway/generator.go, pkg/plugins/runtime/gateway/match/gateway.go, pkg/plugins/runtime/gateway/match/routes.go
Add a couple of minor updates to the Gateway plugin that don't change
any functionality:
* use the meshed manager to find Gateway resources
* cache and match GatewayRoute resources
N/A
N/A
N/A
=> chore(kuma-cp) minor Gateway updates

.circleci/config.yml, pkg/dns/server.go, pkg/dns/server_test.go, pkg/util/net/ips.go, pkg/util/net/ips_test.go, pkg/xds/envoy/listeners/listener_configurers.go, pkg/xds/envoy/listeners/v3/dns_configurer.go, pkg/xds/envoy/listeners/v3/dns_configurer_test.go, pkg/xds/generator/dns_generator.go, pkg/xds/generator/dns_generator_test.go, pkg/xds/generator/testdata/dns/1-envoy-config.golden.yaml
In the past we were sometimes running into issues in dual stack setup
because we would only assign a v4 address and only A records would work.
Leverage Envoy's :ffff prefix to be able to have AAAA and an A record
when using a v4 cidr
* Add multiple ips to envoy dns filter
* Add v6 address when using v4 only leveraging [envoy :ffff prefix](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto.html#config-core-v3-socketaddress)
=> feat(dns) internal dns should resolve AAAA records

pkg/plugins/runtime/gateway/gateway_route_generator.go, pkg/plugins/runtime/gateway/gateway_route_generator_test.go, pkg/plugins/runtime/gateway/generator.go, pkg/plugins/runtime/gateway/hostname_match_test.go, pkg/plugins/runtime/gateway/match/hostnames.go, pkg/plugins/runtime/gateway/merge/routes.go, pkg/plugins/runtime/gateway/plugin.go, pkg/plugins/runtime/gateway/suite_test.go, pkg/plugins/runtime/gateway/testdata/01-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/02-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/03-gateway-route.yaml, pkg/plugins/runtime/gateway/traffic_route_generator.go, pkg/plugins/runtime/gateway/traffic_route_generator_test.go
Update the binding between Gateway and GatewayRoute resources. This can
be a bit complex because both size can have an optional hostname and we
have to map that to Envoy's slightly different concept of virtual host.
N/A
N/A
N/A
=> feat(kuma-cp) match gateway routes

test/e2e/resilience/resilience_suite_test.go
KDS tests don't seem to be running reliably.
Disabling them until we investigate why they are unstable
Related to #2781
=> chore(test) disable flaky tests for KDS

pkg/core/faultinjections/matcher.go, pkg/core/faultinjections/matcher_test.go, pkg/core/xds/types.go, pkg/xds/envoy/listeners/filter_chain_configurers.go, pkg/xds/envoy/listeners/v3/fault_injection_configurer.go, pkg/xds/envoy/listeners/v3/fault_injection_configurer_test.go, pkg/xds/generator/inbound_proxy_generator.go, pkg/xds/generator/inbound_proxy_generator_test.go, test/e2e/matching/matching_suite_test.go, test/e2e/matching/matching_universal.go, test/e2e/matching/matching_universal_test.go
Today if you apply 2 Fault Injections:
```yaml
type: FaultInjection
mesh: default
name: fi1
sources:
- match:
kuma.io/service: demo-client-1
destinations:
- match:
kuma.io/service: test-server
kuma.io/protocol: http
conf:
abort:
httpStatus: 401
percentage: 100
---
type: FaultInjection
mesh: default
name: fi2
sources:
- match:
kuma.io/service: demo-client-2
destinations:
- match:
kuma.io/service: test-server
kuma.io/protocol: http
conf:
abort:
httpStatus: 402
percentage: 100
```
Only the latest one will be applied and replace another one. 
* Select all matched policies for the inbound and apply them all. We can do that because we rely on the HttpFault header matching
N/A
=> fix(kuma-cp) fault injection matching

app/kuma-cp/cmd/root.go, app/kuma-dp/cmd/root.go, app/kumactl/cmd/root.go
Cobra defaults to writing all output to stderr. Change each root command
to set the standard output stream to stdout so that normal and error
output is separated as expected.
```
$ kumactl version 
WARNING: Unable to confirm the server supports this kumactl version
Kuma: 1.2.0-233-g731d6e34
$ kumactl version 2>/dev/null
Kuma: 1.2.0-233-g731d6e34
$ 
```
* Fix the Kuma command-line tools to correctly send normal output to standard out and errors to standard error.
Fix #2786
N/A
=> fix(*) send tool output to stdout

.github/dependabot.yml
These go.mod were removed, there's no good reason to keep them around
=> chore(ci) remove from dependabot conf reference to go.mod

.golangci.yml, pkg/plugins/bootstrap/k8s/plugin.go, pkg/plugins/bootstrap/k8s/scheme.go, pkg/plugins/config/k8s/k8s_suite_test.go, pkg/plugins/config/k8s/plugin.go, pkg/plugins/resources/k8s/k8s_suite_test.go, pkg/plugins/runtime/k8s/controllers/configmap_controller.go, pkg/plugins/runtime/k8s/controllers/mesh_controller.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go, pkg/plugins/runtime/k8s/controllers/namespace_controller.go, pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_status_controller.go, pkg/plugins/runtime/k8s/controllers/service_controller.go, pkg/plugins/runtime/k8s/controllers/suite_test.go, pkg/plugins/runtime/k8s/webhooks/injector/injector_suite_test.go, pkg/plugins/runtime/k8s/webhooks/service_validator_test.go, pkg/plugins/runtime/k8s/webhooks/webhook_suite_test.go, pkg/plugins/secrets/k8s/k8s_suite_test.go, pkg/plugins/secrets/k8s/plugin.go, test/framework/setup.go
We were modifying the same scheme in many places when configuring the
controllers. This is unecessary and is likely to introduce bugs.
We now use the same scheme for everything and modify it at initialization
=> chore(k8s) Use a single scheme for all of k8s

pkg/xds/envoy/clusters/configurers.go, pkg/xds/envoy/clusters/v3/client_side_mtls_configurer.go
The service name that is passed to the `ClientSideMTLS` configurer
is the used to validate the name the upstream provides in its server
certificate. It's less confusing if we call this field `UpstreamService`.
N/A
N/A
N/A
=> chore(kuma-cp) rename mTLS configuration parameter for clarity

pkg/insights/resyncer.go
Service insights were being applied prior to checking rate limit. Moved the rate limit check up so that it would apply to both service and mesh insight generation.
* Fix internal service postgres access rate limiting
=> fix(kuma-cp) Apply ratelimit to service insights

go.mod, pkg/insights/components.go, pkg/insights/resyncer.go
Wrapping the Go rate limiter in an interface from go-kit doesn't have
any advantages at this point. Getter to just remove the dependency.
N/A
N/A
N/A
=> chore(*) remove unnecessary go-kit dependency

docs/proposals/permissive-mtl.md
Proposal for permissive mTLS mode
* add `permissive-mtls.md`
N/A
N/A
=> docs(kuma-cp) permissive mtls proposal

pkg/transparentproxy/config/config.go, pkg/transparentproxy/istio/config/config.go, pkg/transparentproxy/istio/istio.go, pkg/xds/envoy/sockets.go
Had to move config.go to separate package as when it was in istio
dirictory, when compiling for windows it was failing as it was
trying to compile all transparent proxy logic, which is unix os
specific
Also adjusted sockets code to produce valid paths of unix sockets
for envoy logs for any os
no changelog
=> chore(*) small adjustments for windows compilation

app/kumactl/cmd/apply/apply.go, app/kumactl/cmd/delete/delete.go, app/kumactl/cmd/generate/generate.go, app/kumactl/cmd/get/get.go, app/kumactl/cmd/inspect/inspect.go, app/kumactl/cmd/root.go, app/kumactl/pkg/cmd/root_context.go, app/kumactl/pkg/cmd/util.go
Warn for: apply, delete, generate, get, inspect
Don't warn for: completion, config, install, uninstall, version
* Only warn about version compatibility where it makes sense
=> fix(kumactl) Only warn about version compatibility where it makes sense

pkg/insights/components.go
The token burst that is configured for the insight update rate limit
allows the update rate to burst up to 50 times before stabilizing to the
desired rate. This would typically happen when kuma-cp starts up and all
the dataplanes reconnect, which is precisely the time when you want the
rate limit to apply for operational stability.
N/A
N/A
N/A
=> fix(kuma-cp) remove insight update rate limit burst

api/mesh/v1alpha1/dataplane_helpers.go, pkg/core/xds/types.go, pkg/plugins/runtime/k8s/controllers/configmap_controller_test.go, pkg/xds/envoy/endpoints/v3/endpoints.go, pkg/xds/envoy/endpoints/v3/endpoints_test.go, pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go
Until proper support of locality weighted load balancing https://github.com/kumahq/kuma/issues/2689 these tags may confuse users, because they have no effect on how envoy load balance requests.
* delete `kuma.io/region`
* delete `kuma.io/sub-zone`
* update unit tests
N/A
Already fixed
=> fix(kuma-cp) delete kuma.io/region and kuma.io/sub-zone

app/kuma-dp/pkg/config/validate.go, go.mod, go.sum, pkg/tokens/builtin/issuer/issuer.go, pkg/tokens/builtin/zoneingress/issuer.go, vendored/github.com/prometheus/prometheus/go.sum
The github.com/golang-jwt/jwt/v4 package is the active package with fix of vulnerability.
With this change, secure version of jwt-go package is used
Fix #XXX
NA
=> Changed the package dep version to fix  security vulternability

app/kumactl/cmd/install/testdata/install-metrics.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.overrides.golden.yaml
Failing after #2845 
tests(integration) fix kumactl install metrics test
=> tests(integration) fix kumactl install metrics test

app/kumactl/cmd/install/testdata/install-metrics.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/grafana/kuma-service.json
Add zone selector to Kuma Service Grafana dashboard:
standalone:
=> feat(metrics) add zone selector to Kuma Service dashboard

.golangci.yml, pkg/core/managers/apis/external_service/externalservice_manager_test.go, pkg/core/managers/apis/ratelimit/ratelimit_manager_test.go, pkg/core/permissions/matcher_test.go, pkg/core/xds/metadata_test.go, pkg/plugins/runtime/gateway/merge/traffic_route_test.go, pkg/plugins/runtime/gateway/suite_test.go, pkg/util/xds/v3/callbacks_chain_test.go, pkg/xds/envoy/listeners/v3/http_outbound_route_configurer_test.go, pkg/xds/server/callbacks/dataplane_callbacks_test.go, pkg/xds/server/callbacks/dataplane_metadata_tracker_test.go, tools/docs/generate.go
Enable gofmt in simplify mode in the linter config and let it update
all the sources.
N/A
N/A
N/A
- [ x Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.
=> chore(*) enable gofmt simplify mode

.circleci/config.yml
* Change the parallelism and test splitting. It is not clear whether
this actually fixes the underlying problem but it does (experimentally)
make tests pass.
* Consistently and correctly add the Go install to $PATH.
* Upload coverage even when test fail.
N/A
Fix  #2854
Fix  #2855
N/A
=> fix(ci) update CircleCI config

app/kumactl/cmd/install/testdata/install-metrics.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/grafana/kuma-dataplane.json
Adds the zone selector
Standalone:
=> feat(metrics) add zone selector to Kuma Dataplane dashboard

go.mod, go.sum, pkg/plugins/runtime/gateway/builder.go, pkg/plugins/runtime/gateway/gateway_route_generator_test.go, pkg/plugins/runtime/gateway/route_table_generator.go, pkg/plugins/runtime/gateway/suite_test.go, pkg/plugins/runtime/gateway/testdata/01-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/01-traffic-route.yaml, pkg/plugins/runtime/gateway/testdata/02-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/02-traffic-route.yaml, pkg/plugins/runtime/gateway/testdata/03-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/03-traffic-route.yaml, pkg/plugins/runtime/gateway/testdata/04-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/04-traffic-route.yaml, pkg/plugins/runtime/gateway/testdata/06-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/07-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/08-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/09-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/10-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/11-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/12-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/13-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/14-gateway-route.yaml, test/e2e/gateway/gateway_suite_test.go, test/e2e/gateway/gateway_universal.go, test/e2e/trafficroute/testutil/collect.go, test/framework/interface.go, test/framework/setup.go, test/framework/testing.go, test/framework/universal_cluster.go
Add cluster and load assignment support to the Gatewayroute generator.
This makes simple end-to-end Gateway configuratinos work.    
N/A
N/A
N/A
=> feat(kuma-cp) generate GatewayRoute clusters

tools/releases/dockerfiles/Dockerfile.kuma-dp
Update base image to alpine:3.14
* update base image
N/A
N/A
=> chore(*) update base image for kuma-dp

app/kumactl/cmd/install/testdata/install-gateway-enterprise.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway-enterprise.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.overrides.golden.yaml, app/kumactl/data/install/k8s/gateway-kong-enterprise/kong-enterprise/kong-enterprise.yaml, app/kumactl/data/install/k8s/gateway-kong/kong/kong.yaml, app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml, app/kumactl/data/install/k8s/metrics/prometheus/alertmanager.yaml, app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml, app/kumactl/data/install/k8s/metrics/prometheus/pushgateway.yaml, app/kumactl/data/install/k8s/metrics/prometheus/server.yaml
This version was removed in k8s v1.22 which makes using the `install` command difficult, v1 has been available since k8s 1.8.
=> chore(kumactl) migrate install resources from rbac API v1beta1 to v1

app/kumactl/cmd/install/testdata/install-metrics.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/grafana/kuma-service-to-service.json
Add Zone selector to the Service to Service dashboard:
standalone:
=> feat(metrics) add zone selector to Kuma Service to Service dashboard

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/plugins/resources/postgres/config.go
CP previously did not limit number of postgres connections. In our performance benchmarking, we determined this can cause significant problems when connecting large numbers of dataplanes. This is configurable via env variables, but this PR limits by default.
* Limit number of postgres connections by default.
=> fix(kuma-cp) Limit number of postgres connection by default

pkg/plugins/config/k8s/store_test.go, pkg/plugins/resources/k8s/store_test.go, pkg/plugins/secrets/k8s/store_test.go
Use `google/uuid` to generate UUIDs
=> chore(deps) use google/uuid instead of k8s.io/apimachinery/pkg/util/uuid

pkg/kds/context/context.go, pkg/kds/util/resource.go, test/e2e/deploy/kuma_deploy_universal.go
A bug that didn't allow users to disable a zone.
* add e2e test
* fix the bug
N/A
N/A
=> fix(kuma-cp) disable zone

app/kumactl/cmd/install/install_control_plane.go, app/kumactl/cmd/install/install_demo.go, app/kumactl/cmd/install/install_gateway.go, app/kumactl/cmd/install/install_gateway_kong.go, app/kumactl/cmd/install/install_gateway_kong_enterprise.go, app/kumactl/cmd/install/install_logging.go, app/kumactl/cmd/install/install_metrics.go, app/kumactl/cmd/install/install_tracing.go, docs/cmd/kumactl/kumactl_install_control-plane.md, docs/cmd/kumactl/kumactl_install_demo.md, docs/cmd/kumactl/kumactl_install_gateway.md, docs/cmd/kumactl/kumactl_install_gateway_kong-enterprise.md, docs/cmd/kumactl/kumactl_install_gateway_kong.md, docs/cmd/kumactl/kumactl_install_logging.md, docs/cmd/kumactl/kumactl_install_metrics.md, docs/cmd/kumactl/kumactl_install_tracing.md
Because it's configurable via a CLI switch.
=> fix(kumactl) don't refer to a specific namespace in install cmd help

.circleci/config.yml
This alters the circleci to ensure sudo is available for the dev_ubuntu-focussed pipeline.
* Fix circleci config to ensure dev_ubuntu has sudo installed
=> fix(dev_ubuntu): ensure sudo is available

app/kuma-prometheus-sd/README.md, app/kuma-prometheus-sd/cmd/root.go, docs/cmd/kuma-prometheus-sd/kuma-prometheus-sd.md, docs/cmd/kuma-prometheus-sd/kuma-prometheus-sd_run.md, docs/cmd/kuma-prometheus-sd/kuma-prometheus-sd_version.md
Signed-off-by: austin ce <austin.cawley@gmail.com>
Having multiple SD mechanisms is causing confusion (see [slack thread](https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1634897635033500)).
This starts the process of deprecating and removing the old `kuma-prometheus-sd` adapter.
* Add deprecation log message to `kuma-prometheus-sd`
Fix #2852
Could break people's scripts if they are relying on the stdout of `kuma-prometheus-sd` anywhere, but that seems unlikely / not a true public interface.
=> feat(kuma-prometheus-sd) add deprecation notice

pkg/core/datasource/loader.go, pkg/test/runtime/runtime.go
Building a core Runtime object has non-obvious dependencies. The ordering
for building the test runtime was broken because we need to ensure that
the resource manager and its dependencies are present before adding the
datasource loader. The previous order resulted in the datasource loader
failing in tests because it had a nil resource manager.
N/A
N/A
N/A
=> fix(ci) correct runtime builder ordering

app/kumactl/cmd/apply/apply_test.go, pkg/core/resources/model/rest/unmarshaller.go
Update the REST unmarshaler errors to be more specific about what
went wrong. This makes it easier debug things going wrong in tests.
N/A
N/A
N/A
=> chore(*) improve REST unmarshaler errors

test/e2e/hybrid/globalkubernetes/e2e_suite_test.go, test/e2e/hybrid/globalkubernetes/kuma_hybrid_kube_global.go, test/e2e/hybrid/globaluniversal/e2e_suite_test.go, test/e2e/hybrid/globaluniversal/kuma_hybrid.go, test/e2e/hybrid/kuma_hybrid_kube_global_test.go, test/e2e/hybrid/kuma_hybrid_test.go
Don't recreate CP and apps for every tests as we're only asserting that things are
the way we want
* [Fix ...]
Fix #XXX
=> chore(ci) refactor hybrid e2e tests to speed them up

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
There is reporting code in Kuma that sends data to
`kong-hf.konghq.com` by default. This commit switches
the default to false for now.
See also: #3050
=> Disable reporting by default

mk/dev.mk
It seems like we were pulling from somewhere that is no longer supported
=> chore(ci) Update minikube release url

pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.01.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.02.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.03.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.04.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.05.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.06.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.07.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.08.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.09.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.11.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.12.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.13.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.14.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.15.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.16.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.17.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.18.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.19.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.21.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.22.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.23.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.24.golden.yaml
KUMA_RUNTIME_KUBERNETES_INJECTOR_BUILTIN_DNS_ENABLED was not working
because we were simply not setting any env var if it was set.
As kuma-dp starts the builtin dns by default we need to explictly disable it by setting the env var on injection.
=> fix(dns) explicitly disable dns in env when disabled in injector

.circleci/config.yml, app/kuma-cp/cmd/cmd_suite_test.go, pkg/plugins/leader/postgres/postgres_suite_test.go, pkg/plugins/resources/postgres/store_suite_test.go
Some tests targets were redundant and not useful anymore so we removed them.
In some cases docker is not available within the targets. In this case we simply skip the test
=> chore(ci) remove some circleci jobs, skip testcontainer if no docker

app/kumactl/pkg/tokens/client_test.go, app/kumactl/pkg/tokens/zoneingress_client_test.go, pkg/api-server/customization/customization_suite_test.go, pkg/api-server/resource_api_client_test.go, pkg/api-server/server.go, pkg/core/bootstrap/bootstrap.go, pkg/core/runtime/runtime.go, pkg/test/runtime/runtime.go, pkg/tokens/builtin/access/access.go, pkg/tokens/builtin/access/noop.go, pkg/tokens/builtin/access/static.go, pkg/tokens/builtin/server/webservice.go, pkg/tokens/builtin/server/webservice_test.go
Access to generate Zone Ingress token
* Add access validation to generate zone ingress token
* Remove `tokenType` from generate dp token action since it should be long gone.
No issue
=> feat(kuma-cp) access to generate zone ingress token

pkg/xds/generator/dns_generator.go, pkg/xds/generator/dns_generator_test.go, pkg/xds/generator/testdata/dns/3-dataplane.input.yaml, pkg/xds/generator/testdata/dns/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/tracing/zipkin.envoy-config-https.golden.yaml
If there's no port forward for v6 we shouldn't add v6 ips in the config
=> feat(disableipv6) don't add v6 in DNS when v6 is disabled

.golangci.yml, pkg/core/ca/issuer/issuer.go, pkg/plugins/authn/api-server/tokens/issuer/signing_key.go, pkg/plugins/ca/builtin/ca.go, pkg/tls/cert.go, pkg/tokens/builtin/issuer/signing_key.go, pkg/tokens/builtin/zoneingress/signing_key.go, pkg/util/rsa/keygen.go
Consolidate the RSA default key length policy into a single
helper utility.
N/A
Fix #3017.
N/A
=> chore(*) consolidate RSA key generation policy

pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-prometheus-sd/config.go
Open DefaultConfig to modify from projects that build on top of Kuma
* DefaultConfig is now a var to a func. Why not just var to struct? I had race conditions in `./app/kuma-cp/cmd/...` because tests were overriding `DefaultConfig` var. 
No issue
=> chore(kuma-cp) default config open to extensions

pkg/plugins/runtime/k8s/webhooks/secret_validator.go, pkg/plugins/runtime/k8s/webhooks/secret_validator_test.go
Allow creating secrets for the mesh which does not exists. This will unblock the flow where mesh have to be created with the mTLS turned on as otherwise secrets can't be created before the mesh exists.
* Fix #2722
Fix #2722
=> Allow creating secrets for the not yet existing mesh

pkg/api-server/global_insights_endpoints.go, pkg/api-server/global_insights_endpoints_test.go, pkg/api-server/server.go
Any global resource, which is not `Config` or suffixed by `Insight`
will be returned in GlobalInsights endpoint
Example response:
```json
{
"type": "GlobalInsights",
"creationTime": "2021-11-05T08:11:37.880477+01:00",
"resources": {
"GlobalSecret": {
"total": 3
},
"Mesh": {
"total": 1
},
"Zone": {
"total": 0
},
"ZoneIngress": {
"total": 0
}
}
}
```
no changelog
=> feat(*) add more global resources to GlobalInsights

pkg/api-server/resource_endpoints.go
We passed the old spec to `ValidateUpdate`
No issue
=> fix(kuma-cp) pass the new spec when updating resource on universal

pkg/util/proto/any.go, pkg/xds/envoy/listeners/filter_chain_builder.go, pkg/xds/envoy/listeners/v3/fault_injection_configurer.go, pkg/xds/envoy/listeners/v3/grpc_stats_configurer.go, pkg/xds/envoy/listeners/v3/http_connection_manager_configurer.go, pkg/xds/envoy/listeners/v3/rate_limit_configurer.go, pkg/xds/envoy/listeners/v3/static_endpoints_configurer.go, pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/5-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/6-envoy-config.golden.yaml, pkg/xds/generator/testdata/tracing/zipkin.envoy-config-https.golden.yaml
The HTTP connection manager filter chain must terminate with the router
filter. Each time a filter is added, the configurer needs to be careful
to prepend itself to the chain to ensure that the router remains last.
This makes it hard to reason about the ordering of filters, since it
will be the reverse of the configurer application order, and it makes
it unnecessarily tricky to write new configurers.
So the easiest approach is for the builder to simply ensure that there
is always a router filter appended when it builds the filter chain.
Since it is a filter chain builder, it's reasonable for it to know
something about filter chain semantics. We might need to do something
more complicated if we ever need to set any fields in the router, but
for now it seems reasonable to stick with …
=> fix(kuma-cp) ensure HTTP router filter ordering

pkg/plugins/runtime/gateway/route_table_generator.go, pkg/xds/envoy/names/resource_names.go
When we generate Envoy resource names, we usually use a sequence of
strings joined by a colon. Formalize this into the Envoy names API by
adding a constant for the separator, and a helper API to do the joining.
N/A
Updates #2363.
N/A
=> chore(*) formalize the Envoy name separator

tools/postgres/pg_hba.conf
Otherwise we get an error like:
```
cannot connect to DB: pq: no pg_hba.conf entry for host "fd00::1", user "kuma", database "kuma", SSL encryption
```
=> tests: fix postgres in tests if using IPv6 locally

pkg/core/resources/apis/mesh/resource_descriptor_test.go, pkg/core/resources/model/resource.go, pkg/core/resources/registry/registry.go
It is not an issue with the current code but it's a trap that we can easily fall into.
`ResourceDescriptor` has a method `NewObject()`, but in order to call it, it needs to set internal `objectType` and `listType` fields. Those fields are set by `InitDescriptor()` method which is only called when the descriptor is put into `ResourceRegistry`.
The problem is that the `ResourceDescriptor` can also be retrieved from `.Descriptor()` method of the object and this copy of an object does not contain initiated `objectType` and `listType` which results in panic.
I moved the retrieving resource type to `NewObject` itself, I don't think we should be able to create an object which requires extra initialization, especially if the object is copied around instead of passing a pointer.
The alternative …
=> fix(kuma-cp) create new object from resource descriptor

test/e2e/auth/auth_universal.go, test/e2e/gateway/gateway_universal.go, test/framework/universal_cluster.go
Remove conditions on auth type since `tokens` is a default value.
No issues
No docs
=> test(*) remove conditions on auth type

pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_controller_test.go, pkg/plugins/runtime/k8s/controllers/service_controller.go, pkg/plugins/runtime/k8s/controllers/service_controller_test.go, pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/util/util.go, pkg/plugins/runtime/k8s/util/util_test.go
This annotation ignores a kubernetes resource when generating kuma configuration
It currently only works for service and it's meant to be used when migrating to kuma
where you might have services that are used outside of kuma and that will be removed
once migration is complete
* Add annotation
* Add support in serviceController
* Add support in podController
=> feat(kuma-cp) Add kuma.io/ignore annotation

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/dns-server/config.go, pkg/config/loader_test.go, pkg/dns/vips_allocator.go, pkg/dns/vips_allocator_test.go, pkg/dns/vips_synchronizer_test.go, pkg/plugins/runtime/k8s/plugin.go, pkg/plugins/runtime/universal/plugin.go, test/e2e/virtualoutbound/virtualoutbound_k8s.go
Add a switch to make `<kuma.io/service>.mesh` generation optional.
Motivation:
- It is only useful in a restricted set of cases (mix universal/k8s, universal only...).
- It generates a lot of configuration (1 listener per service, entries in the dns filter...)
- VirtualOutbound can do all this and more
This adds a switch to turn the generation of these off.
In future versions we should remove it altogether and suggest generating specific virtual-outbound instead.
=> feat(kuma-dp) Add conf to disable service vip

app/kumactl/cmd/install/context/install_crds_context.go, app/kumactl/cmd/install/install_crds.go
When kumactl tries to install CRDs that aren't already present, we don't
need to filter the names of the CRDs that are already installed to. The
map of installation candidates already contains only Kuma CRDs, and if we
attempt to delete an entry that is not present, that's a harmless no-op.
N/A
N/A
N/A
=> chore(kumactl) remove install CRDs filter function

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
There is reporting code in Kuma that sends data to
kong-hf.konghq.com by default. This commit switches
the default to false for now.
Updates #3050.
Signed-off-by: Hart Hoover <hart.hoover@gmail.com>
=> Disable reporting by default (#3070)

.github/workflows/pr-merged.yaml
It's OK to use `pull_request_target` because we're not checking out/executing any code from forks.
See [the warning about this event type](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target)
=> fix(.github) use `pull_request_target` in GH workflow

.gitignore, Makefile, mk/build.mk, mk/docker.mk, mk/envoy.mk, test/dockerfiles/Dockerfile.universal, test/dockerfiles/Dockerfile.universal.dockerignore, tools/common.sh, tools/envoy/Dockerfile.build-centos7, tools/envoy/Dockerfile.build-centos7.dockerignore, tools/envoy/Dockerfile.build-ubuntu, tools/envoy/Dockerfile.build-ubuntu.dockerignore, tools/envoy/README.md, tools/envoy/build_centos7.sh, tools/envoy/build_darwin.sh, tools/envoy/build_linux.sh, tools/envoy/fetch.sh, tools/envoy/fetch_sources.sh, tools/envoy/publish.sh, tools/releases/distros.sh, tools/releases/docker.sh, tools/releases/dockerfiles/Dockerfile.kuma-dp, tools/releases/dockerfiles/Dockerfile.kuma-dp.dockerignore, tools/releases/helm.sh
Current PR introduces targets `make build/envoy` that allows to build and fetch Envoy binaries (see [README.md](https://github.com/kumahq/kuma/blob/6b19d6d4fe620bca2c3de36175b758df26fe2885/tools/envoy/README.md)).
Also, current PR changes the way `kuma-dp` image obtains Envoy binary. Previously we copied Envoy binary from `envoyproxy/envoy-alpine` image:
```
COPY --from=envoyproxy/envoy-alpine:v1.18.4 /usr/local/bin/envoy /usr/local/bin
```
Now we copy the binary from `build/artifact-*` directory:
```
ADD $KUMA_ROOT/build/artifacts-linux-amd64/envoy /usr/bin
```
In order for Envoy binary to appear in `build/artifacts-*` directory, we must call `make build/artifacts-darwin-amd64/envoy` target. This is not a `.PHONY` target which means it won't run if binary already exists. 
Target …
=> chore(*) scripts for build, publish and fetch Envoy binaries

.mergify.yml
It's unnecessary to have approval on backport PRs, as well when kuma-commit succeed we can safely merge the PR
no changelog
no documentation change
=> feat(ci) auto merge backport PRs after kuma-commit

.mergify.yml
As mergify is the autor of this PRs it cannot aprove its own PRs
no changelog
=> fix(ci) disable auto approve backport prs

pkg/version/compatibility.go
Right now, the release is failing the `test/release/compatibility_test.go` (rightly). Apparently this test isn't executed for RCs (and should probably run on `master`)
=> fix(pkg/version) add 1.4.0 to compatibility matrix

mk/dev.mk
`make dev/install/kubebuilder` installs kubectl so `make dev/install/kubectl` does nothing because `kubectl` already exists. On top of that, kubectl is with outdated version.
The fix is to execute `make dev/install/kubectl` before `make dev/install/kubebuilder`.
In case you are asking whether we even need kubebuilder. I think we don't but it installs etcd and kube-apiserver which is used for kubernetes unit tests. 
No reported issues
=> chore(ci) install latest kubectl version

.circleci/config.yml
We need at least Big Sur to get rid of expired LetsEncrypt cert.
=> build(circleci) fix dev_mac

tools/releases/make-release-tag.sh
The script is otherwise useless atm.
See https://github.com/kumahq/kuma/issues/2073
=> build: fix make-release-tag to allow skipping v prefix

pkg/plugins/runtime/gateway/gateway_route_generator.go, pkg/plugins/runtime/gateway/testdata/http/10-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/11-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/10-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/11-gateway-route.yaml, pkg/xds/server/v3/reconcile.go, pkg/xds/server/v3/reconcile_test.go
The xDS resource validation is built in to the Go packages, as well as the
Envoy xDS client. Running the validation before we swap the xDS snapshot
in the cache prevents Kuma from sending known-bad configuration to Envoy.
Validation is particularly helpful in tests, since we can ensure that
Kuma is generating valid xDS resources even without a running Envoy to
send them to. This check found a case where the Gateway generator would
generate routes without the require path match.
N/A
Fix #2537.
N/A
=> fix(kuma-cp) validate newly generated xDS snapshots

.github/workflows/pr-merged.yaml
Although the `repository_dispatch` _payload_ includes the branch, it's not possible to _specify_ the branch, it's always the `master` branch.
=> fix(.github) don't send dispatch for release branch

pkg/core/xds/metadata.go, pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.ipv6.golden.yaml, pkg/xds/envoy/clusters/v3/client_side_mtls_configurer_test.go, pkg/xds/server/callbacks/dataplane_metadata_tracker_test.go
Remove DP token from XDS Metadata since it's not needed anymore.
It was used when secrets were served over separate SDS connections.
No issues.
=> chore(kuma-cp) remove dp token from xds metadata

pkg/core/resources/apis/mesh/gateway_validator.go, pkg/core/resources/apis/mesh/gateway_validator_test.go
There's no strong reason to require Gateway listeners to specify tags
(though it is useful), so remove the requirement that they must have tags.
N/A
N/A
N/A
=> chore(kuma-cp) allow gateway listeners to omit tags

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/templates/_helpers.tpl, pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/config/plugins/runtime/k8s/config.go, pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml, pkg/plugins/runtime/k8s/plugin.go, pkg/plugins/runtime/k8s/webhooks/validation.go, pkg/plugins/runtime/k8s/webhooks/validation_test.go
When checking if we can modify resources on Zone CP we were checking just a namespace of service account.
We should check an explicit name of a service account that is used to run Kuma CP, so it's more secure.
No reported issues.
=> chore(kuma-cp) check explicit service account name

pkg/core/runtime/reports/reports.go
Instead of sending data as a raw bytes to tcp endpoint, now they
will be sent to TLS protected endpoint
no changelog
no documentation changes
=> chore(kuma-dp) send reports to tls endpoint

app/kumactl/cmd/install/testdata/install-gateway-enterprise.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway-enterprise.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.overrides.golden.yaml, app/kumactl/data/install/k8s/gateway-kong-enterprise/kong-enterprise/kong-enterprise.yaml, app/kumactl/data/install/k8s/gateway-kong/kong/kong.yaml
Bump KIC versions to 2.0
Resources adapted from https://bit.ly/k4k8s and https://bit.ly/k4k8s-enterprise-install
* Added `{{ .Namespace }}` template
* Added sidecar injection annotation to namespace
* Added license secret creation from `--license-path` as before
- Ran through https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/guides/getting-started/
- It's breaking if users are expecting consistent behavior across patch versions and isn't urgent enough to backport.
=> feat(kumactl) upgrade KIC to 2.0

pkg/core/xds/resource.go, pkg/xds/generator/testdata/ingress/01.envoy.golden.yaml, pkg/xds/generator/testdata/ingress/03.envoy.golden.yaml, pkg/xds/generator/testdata/ingress/04.envoy.golden.yaml, pkg/xds/generator/testdata/ingress/05.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/cluster-dots.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml, pkg/xds/server/v3/reconcile.go
There are a couple of places where we assumed that xDS snapshots have
a fixed set of types. Remove these so that we can gracefully handle the
addition new xDS types. This specifically matters when we want to emit
`ScopedRouteConfiguration` resources.
N/A
Update #3299.
N/A
=> chore(kuma-cp) remove type indices from xDS snapshots

pkg/plugins/runtime/k8s/controllers/gateway_converter.go, pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/util/names.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/util/k8s/name_converter.go
This PR adds the Gateway analog of Dataplane creation for injected sidecar proxies.
Continued in #3109
=> feat(gateway) add dataplane creation for gateway deployments

go.mod, go.sum
`go mod tidy` currently fails with go 1.17, this PR runs
`go mod tidy -go=1.16 && go mod tidy -go=1.17` as advised by the error
message so that `go mod tidy` no longer fails.
=> fix(go.mod): run go mod tidy

test/e2e/kic/kubernetes/kong_ingress.go, test/framework/env.go
Disable KIC tests on Kind.
No issues.
- No docs.
=> test(*) disable KIC E2E tests on Kind

.github/commitlint.config.js, .github/workflows/check.yaml, CONTRIBUTING.md
This check enforces a commit message and PR title format. Almost all formats include the `:` between the type/scope and message (what Dependabot creates for example) but we can of course tweak the details if we prefer.
=> feat(.github): add commit message linting

.circleci/config.yml
We are not allowed to use "large" mac instances so let's use "medium"
- Only CI change (added the job here to check it was working).
=> ci: fix failing mac CI because of unsupported instance size

.golangci.yml, pkg/core/config/manager/manager.go, pkg/core/secrets/manager/global_manager.go, pkg/core/secrets/manager/manager.go, pkg/hds/authn/callbacks.go, pkg/plugins/bootstrap/k8s/plugin.go, pkg/plugins/runtime/k8s/controllers/ingress_converter.go, pkg/plugins/runtime/k8s/controllers/outbound_converter.go, pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_converter.go, pkg/plugins/runtime/k8s/controllers/pod_converter_test.go, pkg/plugins/secrets/k8s/store.go
This at least checks we don't make the mistake of missing an existing
context.
=> ci: enable contextcheck

.github/workflows/check.yaml
Only `edited` is not [a default event type](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request).
=> ci(.github): run PR checks when edited

.github/commitlint.config.js
We don't care about line lengths ever
=> ci(.github): remove unnecessary commit message rules

pkg/plugins/runtime/gateway/filter_chain_generator.go, pkg/plugins/runtime/gateway/testdata/04-gateway-listener.yaml
Gateway listeners can forward to any destination, and don't have
outbounds. This means that the only available log policy is the one that
matches the implict "pass_through" outbound. In practice, the this means
that the matching policy should have a wildcard destination service.
N/A
Fix #3316
N/A
=> fix(kuma-cp): set the accesslog policy for Gateway listeners

UPGRADE.md, app/kumactl/cmd/install/context/install_control_plane_context.go, app/kumactl/cmd/install/install_control_plane.go, app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml, deployments/charts/kuma/values.yaml, docs/cmd/kumactl/kumactl_install_control-plane.md, pkg/plugins/runtime/k8s/controllers/inbound_converter.go, pkg/plugins/runtime/k8s/controllers/testdata/01.pod.yaml, pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go, test/e2e/compatibility/cp_compatibility_kubernetes_multizone.go, test/framework/setup.go
Added 2 webhooks with the condition on `kuma.io/sidecar-injection` *label*.
This is the only way of filtering pods to which we can inject the sidecar. Right now we are relying on annotation, but to have this guarantee of sidecar injection, we need to rely on label.
I added 2 new hooks
* hook with the condition on namespace with labels `kuma.io/sidecar-injection: enabled` with policy Fail
* hook with the condition on pod with labels `kuma.io/sidecar-injection: enabled` with policy Fail
For backwards compatibility, we still support annotation, so the current hook with Ignore strategy stays as is.
Fix #3293
It is still backwards compatible with annotations although we recommend (upgrade.md, docs, logs) using labels now.
=> feat(kuma-cp): sidecar injection webhook based on labels

tools/postgres/Dockerfile
Postgres tests were failing on my local machines. It turned out it was a problem with permissions.
No docs
=> test(*): fix postgress tests permissions

pkg/config/plugins/runtime/k8s/config.go, pkg/plugins/runtime/k8s/containers/factory.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go
Previously part of #3109, this allows creating `kuma-dp` containers outside of the injector package.
=> refactor(runtime/k8s): refactor dp container handling

pkg/plugins/resources/k8s/native/api/v1alpha1/dataplane_insight_types.go, pkg/plugins/resources/k8s/native/api/v1alpha1/dataplane_types.go, pkg/plugins/resources/k8s/native/api/v1alpha1/externalservice_types.go, pkg/plugins/resources/k8s/native/api/v1alpha1/gateway_route_types.go, pkg/plugins/resources/k8s/native/api/v1alpha1/gateway_types.go, pkg/plugins/resources/k8s/native/api/v1alpha1/virtual_outbound_types.go, pkg/plugins/resources/k8s/native/api/v1alpha1/zone_ingress_insight_types.go
Minor formatting update to the CRD types.
N/A
N/A
N/A
=> chore(kuma-cp): minor CRD type cleanups

pkg/core/resources/apis/mesh/dataplane_overview_helpers.go
=> fix(kumactl): don't show builtin gateway spuriously offline

pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
Remove the call to `Get` which resets the previous `updateStatus`
=> fix(gateway): don't reset status when reconciling

pkg/plugins/runtime/k8s/controllers/inbound_converter.go, pkg/plugins/runtime/k8s/controllers/pod_controller_test.go, pkg/plugins/runtime/k8s/controllers/pod_converter_test.go, pkg/plugins/runtime/k8s/controllers/testdata/01.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/02.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/03.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/04.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/05.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/06.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/07.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/08.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/09.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/10.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/11.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/12.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/13.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/14.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/15.dataplane.yaml, test/e2e/trafficpermission/hybrid/traffic_permission_hybrid.go
Add `k8s.kuma.io/namespace` tag automatically so we can build policy based on it.
Fix #3367
=> feat(kmesh-cp) add kubernetes tags automatically

tools/releases/docker.sh
Currently if these env vars are missing, we are printing `required` as the env vars are interpolated to empty strings
* [Fix ...]
Fix #XXX
=> fix(ci): display name of vars not interpolate them

UPGRADE.md, pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/loader_test.go, pkg/core/managers/apis/dataplaneinsight/dataplane_insight_manager.go, pkg/core/managers/apis/dataplaneinsight/dataplane_insight_manager_test.go, pkg/core/managers/apis/zoneingressinsight/zone_ingress_insight_manager.go, pkg/core/managers/apis/zoneingressinsight/zone_ingress_insight_manager_test.go, pkg/core/managers/apis/zoneinsight/zone_insight_manager.go, pkg/core/managers/apis/zoneinsight/zone_insight_manager_test.go
remove `kuma.metrics.dataplane.enabled` and `kuma.metrics.zone.enabled` as insights are required internally anyway.
Fix #2565
- config are not updated
- ~~[x] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.~~ BREAKING CHANGE: it's now impossible to disable insights and the related configuration was removed
=> chore(config): remove ability to disable insights

.circleci/config.yml
Not all build vms have wget
* [Fix ...]
Fix #XXX
=> fix(ci): Don't use wget to install runc

pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/mesh_controller.go, pkg/plugins/runtime/k8s/plugin.go, pkg/plugins/runtime/k8s/plugin_gateway.go
None of the Kubernetes code ever used the uncached readers that
are returned from `GetAPIReader`, so we can remove them.
N/A
N/A
N/A
=> chore(kuma-cp): remove uncached Kubernetes readers

.circleci/config.yml
=> chore(ci): bump patch versions of minikube/k8s

CHANGELOG.md, app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/Chart.yaml, deployments/charts/kuma/README.md, go.mod, go.sum
Release the Kuma 1.4.1
No changelog
No issues resolved
=> chore(*) release Kuma 1.4.1

test/e2e/deploy/kuma_deploy_global_zone.go, test/e2e/externalservices/externalservices_kubernetes.go, test/e2e/healthcheck/hybrid/healthcheck_hybrid.go, test/e2e/helm/kuma_helm_deploy_global_zone.go, test/e2e/helm/kuma_helm_deploy_multi_apps.go, test/e2e/hybrid/globaluniversal/kuma_hybrid.go, test/e2e/k8s_api_bypass/k8s_api_bypass.go, test/e2e/kic/kubernetes/kong_ingress.go, test/e2e/tracing/tracing_kubernetes.go, test/e2e/trafficpermission/hybrid/traffic_permission_hybrid.go, test/e2e/virtualoutbound/virtualoutbound_k8s.go
A number of places in the e2e test suite were manually applying the test
namespace to enable sidecar injection. There is already a framework
helper to so that, so apply it consistently to make it obvious which
approach is preferred.
N/A
N/A
N/A
=> chore(e2e): apply test namespace helper

test/e2e/compatibility/cp_compatibility_kubernetes_multizone.go, test/e2e/helm/kuma_helm_deploy_autoscaling.go, test/e2e/helm/kuma_helm_deploy_multi_apps.go, test/e2e/helm/kuma_helm_upgrade.go, test/e2e/k8s_api_bypass/k8s_api_bypass.go, test/e2e/tracing/tracing_kubernetes.go, test/e2e/virtualoutbound/virtualoutbound_k8s.go, test/framework/exec_util.go, test/framework/k8s_cluster.go, test/framework/k8s_clusters.go
Make initializing a Kubernetes cluster have the same function signature as
initializing a Universal cluster. This also lets us remove the additional
timeout helper for Kubernetes clusters, and makes code that uses the
different cluster types more similar.
N/A
N/A
N/A
=> chore(e2e): regularize test framework cluster creation

mk/e2e.new.mk, pkg/util/proto/proto.go, pkg/xds/auth/callbacks.go, pkg/xds/server/callbacks/dataplane_lifecycle.go, pkg/xds/server/callbacks/dataplane_lifecycle_test.go, pkg/xds/server/v3/components.go, test/e2e/auth/dp/auth_dp_suite_test.go, test/e2e/auth/dp/dp_auth_universal.go, test/e2e/auth/dp/dp_auth_universal_test.go, test/framework/universal_controlplane.go
With the current implementation of DP lifecycle, you could override other DP when the new token is was issued for mesh + kuma.io/service tag
No issue reported.
=> fix(kuma-cp) do not override other dataplane with dp lifecycle

pkg/mads/v1/service_test.go
This test was making timing assumptions which causes can cause CI to be flaky
It seems this test still makes sense with the dataplane creation race.
=> fix(ci): fix flaky mads test

pkg/kds/mux/client.go
With gRPC communication there are 2 types of keepalive healthchecks in place:
* L4 TCP keepalive
* L7 (application level) gRPC keepalive
Almost a year ago we enabled L7 keepalive on the server-side (Global CP) with [this PR](https://github.com/kumahq/kuma/pull/1580).
This enables Global CP to detect whether Zone CP is down in case that it was not gracefully shut down.
However, we did not enable gRPC keepalive on the client side. After experimenting with the following setup:
* Global CP deployed on the server connected to the local network
* Zone CP deployed on my Macbook connected to the local network
When I plug out the network cable from my server, I noticed that eventually (after a couple of minutes) Zone CP on my Macbook detected that Global CP is down. Wireshark confirmed that is the …
=> feat(kuma-cp): enable client side gRPC keepalive

mk/build.mk
Building CoreDNS on EVERY `make build` does not make sense, especially since it clones GitHub repo, adds stuff, etc. every time.
CoreDNS has not changed once since we introduced it half a year ago.
I propose a change to only build CoreDNS when it's not already built. This way CI will always build the newest version, but on a local machine, I can execute several `make build` and it's not doing all those operations every time. 
No reported issues.
CI changes.
=> ci(*): build CoreDNS only if binary is not present

test/e2e/auth/dp/auth_dp_suite_test.go, test/e2e/auth/dp/dp_auth_universal.go
Fix package names to be consistent.
No reported issues
No docs
=> chore(*): fix package names in Auth DP E2E tests

mk/dev.mk, mk/test.mk, pkg/plugins/resources/k8s/native/Makefile
The `dev/tools` make target installs testing dependencies into
`$CI_TOOLS_DIR`, but the wiring between this and the kubebuilder envtest
framework was broken. Make sure that we set the `KUBEBUILDER_ASSETS`
environment variable so that the envtest framework can find its
dependencies correctly.
N/A
N/A
N/A
=> fix(ci): set kubebuilder assets directory

app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, deployments/charts/kuma/templates/cp-global-sync-service.yaml
CP selector in Global Remote Sync service was missing.
It was ok, because in Global CP was the only component that was running with `app.kubernetes.io/name: kuma`, so it was always selected, but we should select the control plane explicitly in case a new component will arrive in the future next to Global CP.
No reported issues.
No docs.
=> fix(kuma-cp): add cp selector to global sync service

.circleci/config.yml, mk/docker.mk, mk/e2e.new.mk, mk/k3d.mk, mk/kind.mk
This PR adds `test/e2e/debug-fast` target. I spent some time on how to optimize the time for E2E to start to increase our development velocity.
With this target, a full E2E test (build binaries, images, load them to k8s cluster) with both Kubernetes clusters can start in only **40 seconds** on my machine.
Just a simple `k3d/start` (1 K8S cluster) even without image loading takes 30s.
`image*` targets were not compatible with parallel execution.
For example: `image/kuma-cp` depends on both `build/kuma-cp/linux-amd64` and `docker/build/kuma-cp`.
`docker/build/kuma-cp` depends on a binary build by `build/kuma-cp/linux-amd64`.
Execute it with `-j` and see that `docker/build/kuma-cp` complains because there is no binary yet.
That's why I forced order of those targets within `image*`. This way …
=> test(*): add test/e2e/debug-fast target

pkg/plugins/resources/k8s/native/api/v1alpha1/gateway_instance.go, pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
Closes https://github.com/kumahq/kuma/issues/3509
=> feat(gateway): watch Gateway for tag changes in GatewayInstance reconciler

tools/releases/helm.sh
We don't want to release these CRDs yet. There are also some parts of the RBAC resources that exist because of Gateway stuff which we could also remove, perhaps via a Helm value + templates but that's less crucial.
Closes https://github.com/kumahq/kuma/issues/3475
=> chore(tools/releases/helm.sh): don't release Gateway-related CRDs

test/e2e/gateway/gateway_kubernetes.go, test/e2e/gateway/gateway_suite_test.go, test/e2e/gateway/gateway_universal.go, test/e2e/trafficroute/testutil/collect.go
Start adding Kubernetes e2e tests for the builting Gateway. We take
advantage of the fact that GatewayInstance supports ClusterIP services
to be able to rendevous with the gateway address. The intention is to
duplicate the Universal cluster tests (where appropriate), so there is
probably some scope for refactoring and consolidation in the future.
N/A
Update #3510
N/A
=> tests(kuma-cp): add initial Gateway tests for Kubernetes

pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
Unfortunately tag values can't contain slashes. The previous format is at least consistent with `Service`'s `_svc`.
=> Revert "refactor(gateway): change to prefixed autogenerated tag (#3585)"

app/kumactl/cmd/get/testdata/get-mesh.golden.txt, app/kumactl/cmd/get/testdata/get-meshes.golden.txt, app/kumactl/cmd/get/testdata/get-meshes.pagination.golden.txt, pkg/core/resources/apis/mesh/mesh_helpers.go, pkg/core/resources/apis/mesh/mesh_helpers_test.go
This PR introduces tracing and logging backend type in the cli table output along with its name.
* Updated mesh_helpers file to include `type`
Fix #3345
=> feat(kumactl) Add Tracing and Logging Backend Type in CLI

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Add backporting policy in PR template and CONTRIBUTING.md
Also remove unnecessary outdated TOC (github provides an autogenerated on already).
- ~~[ ] Update [`UPGRADE.md`](UPGRADE.md) with any steps users will need to take
when upgrading.~~
- ~~[ ] Add `backport-to-stable` label if the code is backwards compatible. Otherwise, list breaking changes.~~
=> docs: document new backporting policy

Makefile, mk/api.mk, mk/generate.mk
Merge `api/Makefile` back to `mk/api.mk`. This consolidates the build and
removes some duplication of protobuf configuration.  The main issue is
that protoc binds the proto search path and the output path in surprising
and undocumented ways. So, depending on the context, we have to either
change into the "api" directory, or add it to the search path.
N/A
Fix #2495.
N/A
=> fix(build): move API makefile to the main build system

test/e2e/gateway/gateway_kubernetes.go, test/e2e/trafficroute/testutil/collect.go, test/framework/exec_util.go, test/framework/k8s_controlplane.go
Enable the mTLS permissions test for Gateway in Kubernetes zones. This
exercises a couple of new code paths in the test framework, so we needed
to fix a bug in the mesh deployment update option and improve debugging
and option handling in some other places.
N/A
Update #3510
N/A
=> tests(kuma-cp): add kubernetes mTLS permissions test

app/kumactl/cmd/apply/apply_test.go, app/kumactl/cmd/get/testdata/get-circuit-breaker.golden.yaml, app/kumactl/cmd/get/testdata/get-dataplane.golden.yaml, app/kumactl/cmd/get/testdata/get-fault-injection.golden.yaml, app/kumactl/cmd/get/testdata/get-global-secret.golden.yaml, app/kumactl/cmd/get/testdata/get-healthcheck.golden.yaml, app/kumactl/cmd/get/testdata/get-mesh.golden.yaml, app/kumactl/cmd/get/testdata/get-proxytemplate.golden.yaml, app/kumactl/cmd/get/testdata/get-rate-limit.golden.yaml, app/kumactl/cmd/get/testdata/get-retry.golden.yaml, app/kumactl/cmd/get/testdata/get-secret.golden.yaml, app/kumactl/cmd/get/testdata/get-traffic-log.golden.yaml, app/kumactl/cmd/get/testdata/get-traffic-permission.golden.yaml, app/kumactl/cmd/get/testdata/get-traffic-route.golden.yaml, app/kumactl/cmd/get/testdata/get-traffic-trace.golden.yaml, app/kumactl/pkg/output/yaml/printer.go, app/kumactl/pkg/output/yaml/testdata/mesh.golden.yaml, app/kumactl/pkg/output/yaml/yaml_test.go, test/framework/kumactl.go
When printing Kuma resources as YAML, it's a better user experience to
show the metadata fields (including the type and name) up front, rather
than the fields being in an arbitrary order.
This change is not a complete fix for the issue, but by tweaking the
kumactl get printer, we can make a small change that improves the user
experience in most cases.
N/A
Update #679
N/A
=> fix(kumactl): print meta before spec for Kuma resources

mk/test.mk
`make` targets for running test for individual components is broken. This PR introduces the correct targets for the components.
N/A
N/A
N/A
=> fix(build): fix make test targets for individual components

app/kumactl/cmd/install/render_helm_files.go
We were filtering out unregistered CRDs too loosely.
=> fix(kumactl): ignore any unregistered CRDs, not only from the root chart

.github/dependabot.yml
As we're not systematically backporting changes we shouldn't do dependabot
on release branches
=> ci: stop applying dependabot on release branches

app/kumactl/cmd/get/testdata/get-dataplanes.golden.txt, app/kumactl/cmd/install/testdata/install-logging.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-logging.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.overrides.golden.yaml, app/kumactl/data/install/k8s/logging/loki/loki.yaml, app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml, app/kumactl/data/install/k8s/metrics/prometheus/alertmanager.yaml, app/kumactl/data/install/k8s/metrics/prometheus/node-exporter.yaml, app/kumactl/data/install/k8s/metrics/prometheus/pushgateway.yaml, app/kumactl/data/install/k8s/metrics/prometheus/server.yaml
Update to the latest versions all logging/metrics dependencies,
which are part of generated manifests via `kumactl install logging`
and `kumactl install metrics`, like grafana, prometheus or loki
Updating loki involved some more complex changes related to non
backward compatible changes in the newest version
no changelog
Closes https://github.com/kumahq/kuma/issues/3409
=> chore(*): bump logging and metrics dependencies

test/framework/k8s_cluster.go, test/framework/k8s_controlplane.go
The Kubernetes cluster object update helper works by doing a "kubectl
get", updating the deserialized result, then doing a "kubectl replace".
The intention is to set exactly what the test specifies without worrying
about patch and merge behavior.
Howwever, replacement requires the resource version to be current and when
Kuma converts Kubernetes objects to internal API resources, it does not
preserve all the Kubernetes metadata. It seems like this can lead to test
failures where the wrong resource version is used, though my understanding
was that kubectl internally ought to fetch the latest resource version
(though maybe it only does that once, and can lose race conditions).
At any rate, switching to "kubectl apply" ought to be OK for the current
uses of this mechanism, and should be more …
=> chore(e2e): switch Kubernetes update helper to use apply

app/kumactl/cmd/inspect/inspect_dataplanes_test.go, app/kumactl/cmd/inspect/inspect_meshes_test.go, app/kumactl/cmd/inspect/inspect_services_test.go, app/kumactl/cmd/inspect/inspect_zoneingresses_test.go, app/kumactl/cmd/inspect/inspect_zones_test.go, app/kumactl/cmd/inspect/testdata/inspect-services.golden.yaml
Currently, the `inspect` command has some dead code related to the old `gomega matchers` and also matcher's for `JSON` and `YAML` referring to old matcher's.
This PR introduces the latest gomega wrappers to inspect resources test cases and clean up dead code.
* [Fix ...]
Fix #XXX
=> fix(build): fix gomega matchers for inspect resources command test

test/e2e/gateway/gateway_kubernetes.go, test/e2e/gateway/gateway_universal.go, test/e2e/gateway/utils.go, test/e2e/trafficroute/testutil/collect.go
Refactor the Gateway e2e tests so that they follow a more consistent code
structure and we can hoist out common parts of the tests. This makes it
easier to see what tests are enabled for universal and gateway zones, and
reduces the amount of code we need to copy between the two test suites.
N/A
Update #3510
N/A
=> chore(e2e): consolidate gateway tests

test/e2e/helm/kuma_helm_deploy_global_zone.go, test/framework/constants.go, test/framework/deployments/tracing/kubernetes.go, test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/k8s_clusters.go, test/framework/k8s_controlplane.go, test/framework/universal_controlplane.go
This removes duplicated code and might fix flakiness on the helm upgrade tests
=> ci(e2e): use tunnel from terratest instead of our own

.circleci/config.yml
Remove parallelism limit on dev_mac job which likely slowed down the whole build
Tests of this showed tests taking about half the time it does currently.
=> ci(circleci): speed up dev_mac job

pkg/core/managers/apis/mesh/mesh_manager.go, pkg/defaults/mesh/circuit_breaker.go, pkg/defaults/mesh/mesh.go, pkg/defaults/mesh/mesh_test.go, pkg/defaults/mesh/retry.go, pkg/defaults/mesh/signing_key.go, pkg/defaults/mesh/timeout.go, pkg/defaults/mesh/traffic_permission.go, pkg/defaults/mesh/traffic_route.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go
replace ensureDefaultXXX functions with a single generic function
* [Fix ...]
Fix #2540
=> refactor(*): replace ensureDefaultXXX functions with a single generic function

go.mod, pkg/plugins/bootstrap/k8s/plugin.go
This PR adds an intercept to `Manager.Add` calls to save `Controller`s to be `Add`ed after leader election.
Closes #3611
=> fix(k8s): make sure controllers start after leader election

app/kuma-dp/pkg/dataplane/dnsserver/dnsserver.go, app/kuma-dp/pkg/dataplane/envoy/envoy.go, pkg/util/files/lookup_binary.go
I got into edge case when running kuma-dp with docker containers.
Assuming that the workdir is `/home/kuma-dp` with permission that only `kuma-dp` can access. I'm running `kuma-dp` with different user, the `os.Getwd()` fails because it cannot access `.`
The lookup functions should be more defensive. It should not fail on trying to resolve the current directory, especially when I prefer to use configured path instead.
No reported issues.
=> fix(kuma-dp): binary lookup function skips not available directories

mk/docker.mk, mk/k3d.mk, mk/kind.mk, test/framework/k8s_cluster.go, tools/releases/docker.sh
Enable projects that build on top of Kuma to be able to include new docker containers
* Add possibility to add new image targets when `make images`, `make docker/save` and `make docker/load`, `make k3d/load`, `make kind/load` are executed
* Remove load target separation in Kind to be consistent with K3D
* Add explicit images to `kumactl install control-plane`, so we are able to override images. it's already done for HELM install.
* Add possibility to override list of images in `docker.sh` script.
No docs, internal changes only.
=> chore(*): add posibility to customize Kuma images

pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy_suite_test.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy_test.go
This PR adds [CORE conformance level support](https://gateway-api.sigs.k8s.io/v1alpha2/references/cross-namespace-references/#conformance-level) for checking `ReferencePolicy`s when handling `HTTPRoute` references.
Part of #3615
=> feat(gateway): support Gateway API ReferencePolicy for HTTPRoutes

tools/releases/docker.sh
There is no way to override bash array with env var. Switching to string.
No issues
- ~[X] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.~
- ~[X] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)~
=> chore(*): add posibility to customize images on release

test/framework/k8s_controlplane.go
we switched around the message and the regex so the retry wasn't working
=> ci(e2e): correct bad retry on apply

pkg/defaults/mesh/circuit_breaker.go, pkg/defaults/mesh/mesh.go, pkg/defaults/mesh/retry.go, pkg/defaults/mesh/timeout.go, pkg/defaults/mesh/traffic_permission.go, pkg/defaults/mesh/traffic_route.go
Further consolidate the code that creates default mesh resources.
N/A
Update #2540
N/A
=> chore(kuma-cp): consolidate mesh defaults creation

pkg/plugins/runtime/k8s/controllers/gatewayapi/common.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/plugin_gateway.go
This simulates owner references so that deletion of namespaced Gateway API objects causes cluster-scoped Kuma objects to be garbage collected.
Closes #3517
=> refactor(gateway): garbage collect Kuma Gateway resources owned by Gateway API resources

UPGRADE.md, pkg/core/resources/apis/mesh/dataplane_validator.go, pkg/core/resources/apis/mesh/dataplane_validator_test.go
This doesn't really makes sense, is error prone and might accidently
expose services outside of the mesh, we therefore disallow it.
Fix #3640
=> fix(dataplane)!: disallow using 0.0.0.0 in networking.address for dp

pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/metadata/annotations_test.go
Signed-off-by: ChinYing-Li <chinying.li@mail.utoronto.ca>
Introduce a new error message template when casting of annotation value failed. Introduced unit tests for `GetUint32` and `GetBool`.
Any suggestion is appreciated!
* Include name of annotation to parse error message
Fix #2690
=> improvement(metadata): Include name of annotation to parse error message

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cp-configmap.yaml, deployments/charts/kuma/templates/cp-deployment.yaml, deployments/charts/kuma/values.yaml
The initial motivation for this is to allow the appropriate
CA file for the Postgres instance to be specified when
running kuma-cp in universal mode and then configured with
KUMA_STORE_POSTGRES_TLS_CA_PATH
Signed-off-by: Will Betts <will.betts@equalexperts.com>
=> feature(kuma-cp): allow custom files in chart cm

pkg/plugins/runtime/k8s/containers/factory.go, pkg/plugins/runtime/k8s/controllers/gateway_converter.go, pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_controller_test.go, pkg/plugins/runtime/k8s/controllers/pod_converter.go, pkg/plugins/runtime/k8s/controllers/pod_converter_test.go, pkg/plugins/runtime/k8s/util/util.go, pkg/plugins/runtime/k8s/util/util_test.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go
~I'm not yet quite sure if this change can break anything...~
In fact I think it fixes a bug when computing the mesh of pods when there's a mesh annotation on the Namespace.
Closes #3514
=> refactor(kuma-cp): unify mesh determination for k8s objects

pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
The motivation here is keeping the `HTTPRoute` object statuses up to date.
=> feat(gateway): reconcile relevant HTTPRoutes when Gateways change

pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/service_controller.go, pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/metadata/annotations_test.go, pkg/plugins/runtime/k8s/util/util.go
This PR removed the `GetBool method` and uses `GetEnabled` as a replacement.
P.S - (50th PR 😄)
* [Fix ...]
Fix #2338
=> refactor(k8s): remove GetBool method and use GetEnabled

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, pkg/plugins/runtime/k8s/controllers/util/controlled.go
Reduces noisy error messages/unnecessary reconciliations.
=> refactor(gateway): use Patch to reconcile GatewayInstances's owned objects

pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment_suite_test.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment_test.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
This PR enforces the `AllowedRoutes` field on `Gateway` `Listeners` and sets the status accordingly on `HTTPRoute` `RouteParentStatus`.
Closes #3624 
~Blocked by https://github.com/kumahq/kuma/pull/3709~
=> feat(gateway): respect AllowedRoutes on Gateways

mk/run.mk
Signed-off-by: Tomasz Wylężek <tomwylezek@gmail.com>
Adjust running script with experimental flag set to true
- Change `make run/universal/memory` & `make run/universal/postgres` to have flag `KUMA_EXPERIMENTAL_GATEWAY` set to true
Fix #XXX
=> chore(scripts) adjust run scripts to set experimental gateway flag

app/kumactl/cmd/install/testdata/install-demo.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-demo.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway-enterprise.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway-enterprise.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-gateway.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.overrides.golden.yaml, app/kumactl/data/install/k8s/demo/demo.yaml, app/kumactl/data/install/k8s/gateway-kong-enterprise/kong-enterprise/kong-enterprise.yaml, app/kumactl/data/install/k8s/gateway-kong/kong/kong.yaml, app/kumactl/data/install/k8s/metrics/namespace.yaml, app/kumactl/data/install/k8s/metrics/prometheus/node-exporter.yaml, pkg/plugins/runtime/k8s/controllers/namespace_controller.go, pkg/plugins/runtime/k8s/controllers/namespace_controller_test.go, pkg/plugins/runtime/k8s/controllers/service_controller.go, pkg/plugins/runtime/k8s/controllers/service_controller_test.go
We can now use either labels or annotations for the kuma.io/sidecar-injected
annotation. We were missing the support for label in the service and namespace controllers.
We also switched the demo to use labels instead of annotations
=> fix(kuma-cp): fix missing label sidecar injection

deployments/charts/README.md, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cni-rbac.yaml, deployments/charts/kuma/templates/cp-rbac.yaml, deployments/charts/kuma/templates/ingress-rbac.yaml, deployments/charts/kuma/templates/pre-delete-webhooks.yaml, deployments/charts/kuma/templates/pre-install-patch-namespace-job.yaml, deployments/charts/kuma/templates/pre-upgrade-install-missing-crds-job.yaml, deployments/charts/kuma/values.yaml
This PR adds support to specify `imagePullSecrets`
for all Kuma component Service Accounts.
It also deprecates the individual `imagePullSecrets`
field for the CRD install job, maintaining backward
compatibility while instructing users to use the new
field.
Resolves #3751
Signed-off-by: John Harris <john.harris@konghq.com>
=> feat(helm): add imagePullSecrets support

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
The Patch created by ManageControlledObject from this function causes errors when reconciling as is.
=> fix(gateway): don't replace Service spec in GatewayInstance controller

pkg/core/xds/types.go, pkg/xds/generator/ingress_generator.go, pkg/xds/generator/ingress_generator_test.go, pkg/xds/sync/ingress_proxy_builder.go, test/e2e/gateway/gateway_universal.go, test/e2e/gateway/hybrid/gateway_hybrid.go, test/e2e/gateway/hybrid/gateway_hybrid_suite_test.go, test/e2e/gateway/utils.go
Support multizone routing when using builtin Gateway.
* Write hybrid E2E test to test it (Global on Universal, Universal Zone with Gateway, Universal Zone without Gateway, Kubernetes Zone)
* Fix filter match generator to take into account GatewayRoute
* Extract shared E2E install funcs to gateway e2e test utils. 
Fix #3314
Maybe fixed 3511 ?
=> feat(kuma-cp): multizone routing using builtin Gateway

pkg/api-server/inspect_endpoints.go, pkg/api-server/testdata/inspect_changed_state_after.json, pkg/api-server/testdata/inspect_changed_state_before.json, pkg/api-server/testdata/inspect_circuit-breaker.json, pkg/api-server/testdata/inspect_dataplane.json, pkg/api-server/testdata/inspect_fault-injection.json, pkg/api-server/testdata/inspect_health-check.json, pkg/api-server/testdata/inspect_rate-limit.json, pkg/api-server/testdata/inspect_retry.json, pkg/api-server/testdata/inspect_timeout.json, pkg/api-server/testdata/inspect_traffic-log.json, pkg/api-server/testdata/inspect_traffic-permission.json, pkg/api-server/testdata/inspect_traffic-route.json, pkg/api-server/testdata/inspect_traffic-trace.json, pkg/api-server/types/inspect.go, pkg/api-server/types/inspect_test.go, pkg/api-server/types/testdata/empty.json, pkg/api-server/types/testdata/full_example.json, pkg/core/xds/matched_policies.go, pkg/core/xds/matched_policies_test.go
I tested the new policy matching visible in the GUI and it's great. However
Inbound / Outbound attachments are really cryptic to end-user. I added `service` field to the API, so we know which inbound/outbound is represented by which service. This way we can improve the GUI so instead of `240.0.0.0:80` we can say `240.0.0.0:80 (demo-app_kuma_svc_500)` or `demo-app_kuma_svc_500 (240.0.0.0:80)`
=> feat(kuma-cp): add service name to inspect API

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, test/e2e/gateway/gateway_helm.go
After discussion with @michaelbeaumont we figured out that the best way is to do 1:1 port to nodeport, so this PR implements this behavior.
Fix #3578
No docs for Gateway yet.
=> feat(kuma-cp): support NodePort in GatewayInstance

test/framework/client/collect.go, test/framework/deployments/externalservice/universal.go, test/framework/setup.go, test/framework/universal_app.go, test/framework/universal_cluster.go, test/framework/universal_controlplane.go, test/framework/utils/utils.go
- This was causing issues when passing a json in env var
- Also do some minor cleanup on the framework
=> fix(e2e): escape env vars in e2e test

test/e2e/inspect/inspect_k8s_multizone.go, test/e2e/inspect/inspect_k8s_standalone.go, test/e2e/inspect/inspect_universal.go
Avoid hardcoding project-specific constants in e2e tests
* update e2e tests to use e2e config
N/A
=> test(e2e): use names from e2e config

test/e2e/inspect/inspect_suite_test.go
We don't want to use `wget` to work with Inspect API in e2e tests, `kumactl` is more preferable. So disable tests while `kumactl` support is not there. 
* disable `Test Inspect API on Kubernetes Standalone`
* disable `Test Inspect API on Kubernetes Multizone`
N/A
=> test(e2e): disable k8s Inspect API tests

pkg/config/plugins/resources/postgres/config.go, pkg/config/plugins/resources/postgres/config_test.go, pkg/plugins/common/postgres/connection.go, pkg/plugins/common/postgres/listener.go
Passwords with `'` break the connection string as is.
See https://www.postgresql.org/docs/10/libpq-connect.html#id-1.7.3.8.3.5
=> fix(kuma-cp): properly escape DB password when creating postgres connection string

.circleci/config.yml, test/e2e/inspect/inspect_k8s_multizone.go, test/e2e/inspect/inspect_k8s_standalone.go
Using flag `--total` in 
```
export E2E_PKG_LIST=$(circleci tests glob ./test/e2e/* | circleci tests split --total=$(ls test/e2e | wc -l) | xargs printf "./%s/... ")
```
is incorrect. According to circle-ci, it defines how many workers you have rather than how many tests you have:
```
By default, the number of containers is specified by the parallelism key. You can manually set this by using the --total flag.
```
* [Fix ...]
Fix #XXX
=> chore(ci): tests are not properly distributed across workers

test/e2e/inspect/inspect_k8s_multizone.go
Test checks envoy config dump and tries to find filterChainMatch rule, that could be available not immediately.
* [Fix ...]
Fix #XXX
=> fix(inspect-api): flaky multizone k8s test

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, pkg/plugins/runtime/k8s/controllers/service_controller.go, pkg/plugins/runtime/k8s/controllers/service_controller_test.go
Do not annotate gateway instance service with `ingress.kubernetes.io/service-upstream: true`
=> fix(*): do not annotate gateway services with ingress upstream

pkg/api-server/inspect_endpoints.go, pkg/core/xds/matched_policies.go
Add ability to add custom inbound policies to MatchedPolicies structure.
* New `CustomInboundPolicies` field
N/A
=> feat(kuma-cp): add support for custom inbound policies

pkg/kds/context/context.go, pkg/kds/context/context_test.go
DataplaneInsights-related resources include a monotonically increasing "generation" field, which is updated regardless of whether the resource has changed. This causes reconciliation within KDS to see them as changing when they have not. Added a ResourceMapper to zero out this field on Global control plane.
* Fix issue where Dataplane-related Insights are unnecessarily reconciled.
Fix #3783
=> fix(kuma-cp): do not update unchanged insights

test/e2e/ratelimit/ratelimit_universal.go
The bucket interval is 10s so if we only wait 1s inbetween tries, we
won't ever let the bucket empty.
=> test(e2e/ratelimit): increase polling interval

pkg/plugins/runtime/gateway/cluster_generator.go, pkg/plugins/runtime/gateway/connection_policy_generator.go, pkg/plugins/runtime/gateway/filter_chain_generator.go, pkg/plugins/runtime/gateway/gateway_route_generator.go, pkg/plugins/runtime/gateway/generator.go, pkg/plugins/runtime/gateway/listener_generator.go, pkg/plugins/runtime/gateway/route_configuration_generator.go, pkg/plugins/runtime/gateway/route_table_generator.go
`Host` isn't mutated inside `GenerateHost` and both `Host` and `RouteTable`
are replaced on `GatewayResourceInfo` each time we call `GenerateHost`.
Behavior doesn't change.
=> refactor(gateway): refactor `GatewayResourceInfo` to `GatewayListenerInfo`

pkg/kds/client/stream.go, pkg/kds/context/context.go, pkg/kds/context/context_test.go, pkg/kds/features.go, pkg/kds/reconcile/snapshot_generator.go, pkg/kds/types.go, pkg/kds/zone/components.go
There were two problems with syncing zone token
1. In zone CP we had a filter on `SigningKeyPrefix` instead of `SigningPublicKeyPrefix` so whenever either of cp restarted, zone cp was trying to recreate the new zone token public signing key, but it was already there so zone CP responded in NACK, global cp was trying to send those resources again and we had a loop.
The fix for that is in pkg/kds/zone/components.go
2. There was the same problem but with the newest global cp and old zone cp. I think that KDS filtering in Sync is faulty and we need to figure out a better solution for it. In the meantime, we need to provide a way for users to upgrade CP, so I introduced a concept of _features_ similar to what I want to do for XDS https://github.com/kumahq/kuma/issues/3713
This way Global CP …
=> fix(kuma-cp): handle zone token sync with old versions of cp

.github/workflows/release.yaml, tools/releases/make-release-tag.sh
This creates new tags with a `v` prefix and supports old tags with and without the prefix.
Part of #2073
=> ci: use v tag prefix in create release branch workflow

pkg/xds/generator/egress/generator.go, pkg/xds/sync/egress_proxy_builder.go
Fix order for zoneegresses + don't create listener when no listener filters
n/a
n/a
=> fix(*): fix order for zoneegress

pkg/xds/generator/secrets_generator.go, pkg/xds/generator/testdata/secrets/envoy-config-egress.golden.yaml, pkg/xds/secrets/secrets.go
The certs were always returned the same as the cache key was not
considering the mesh name (was always asking identifying itself
with the cache key "zone egress")
+ removal of cleaning resource list in a loop, which was a bug
n/a
n/a
n/a
=> fix(kuma-cp): fix getting certs for zoneegress

test/e2e/ratelimit/ratelimit_universal.go
Like https://github.com/kumahq/kuma/pull/3828, the bucket interval is 10s so if we only wait 1s
inbetween tries, we won't ever let the bucket empty. This covers the
other tests with interval 10s
=> test(e2e/ratelimit): increase polling interval for flaky tests

pkg/kds/context/context.go, pkg/kds/context/context_test.go, pkg/kds/zone/components.go
Global CP does not provide Insights with generations, Zone CP does.
I could remove CompositeResourceMapper, but I have a feeling that it will be used soon.
Fix #3840
No docs
=> fix(kuma-cp): zero generation on insights provided by zone cp

pkg/xds/generator/egress/external_services_generator.go, pkg/xds/generator/egress/testdata/03.mixed-services.golden.yaml, pkg/xds/generator/egress/testdata/05.mixed-services-with-custom-trafficpermissions.golden.yaml, pkg/xds/generator/egress/testdata/input/03.mixed-services.yaml, pkg/xds/generator/egress/testdata/input/05.mixed-services-with-custom-trafficpermissions.yaml, pkg/xds/generator/secrets_generator.go, pkg/xds/generator/secrets_generator_test.go, pkg/xds/generator/testdata/secrets/envoy-config-egress.golden.yaml
We discovered two problems with external services and zone egress
1. We took the name of the external service instead of kuma.io/service tag from the service
2. We cannot provide all secrets to ZoneEgress. We can only use the ones that are referenced by the rest of the config. Otherwise, all secrets are stuck in a warming state.
No docs.
=> fix(kuma-cp): filter out secrets that are not used

test/e2e/ratelimit/e2e_suite_test.go
=> test(e2e/ratelimit): mark as pending while we investigate flakiness

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go
=> chore(*): rename experimental gateway in kuma-cp.default.config

pkg/kds/util/meta.go, pkg/kds/util/resource.go
The receiver of KDS resources replaces version, creation and modification time.
Right now, if any of them has changed, we were sending the resource over KDS. But the resource itself might not have changed (for example, resource mapper cleared generation in insights).
There is no point in sending those parts of resource meta over KDS
Fix #3840
No docs
=> fix(*): drop additional meta in KDS

pkg/defaults/components.go
The logs say
```
2022-02-21T13:29:34.894Z	INFO	defaults	default signing key created
```
This PR add context to those messages 
No docs
=> chore(kuma-cp): better logging on signing key creation

test/e2e/matching/matching_universal.go
After running this test in a loop with 10s timeout I managed to reproduce a problem after ~10 mins.
Because we don't wait for data plane proxies to be ready, 10s may not be enough. When the test failed for me, I saw that bootstrap configuration generation was ~2s after we started sending requests which indicate that 10s may not be enough with a low number of cores. Especially that we are running this with 100ms interval which also "steals" some CPU time to run the mesh.
After increasing the timeout to 60s, I run the test in a loop for 40min and it did not fail.
No reported issue.
No docs.
~- [ ] Add `backport-to-stable` label if the code follows our [backporting …
=> test(*): increase timeouts on flaky test

go.mod
Ends up being removed by `go mod tidy`.
=> chore(go.mod): remove ginkgo v1

.circleci/config.yml
Merge kuma-commit and kuma-master who were doing the same thing. Simply ignore the publish steps where we don't want to publish things.
Also merge images in build jobs as they are pretty tightly related anyway.
=> ci: simplify circleci jobs

tools/envoy/build_centos.sh, tools/envoy/build_darwin.sh
It wasn't possible to build Envoy for darwin and centos without excluding these extensions. 
* [Fix ...]
Fix #XXX
=> chore(*): update envoy build scripts

go.mod, go.sum, pkg/xds/envoy/listeners/v3/tags_metadata_configurer_test.go, test/e2e/proxytemplate/e2e_suite_test.go, test/e2e/proxytemplate/proxy_template_universal.go
See https://github.com/kumahq/kuma/pull/3910
=> chore(deps): fix bad merge with ginkgo v1/v2

pkg/plugins/runtime/gateway/cluster_generator.go, pkg/plugins/runtime/gateway/filter_chain_generator.go, pkg/plugins/runtime/gateway/gateway_route_generator.go, pkg/plugins/runtime/gateway/generator.go, pkg/plugins/runtime/gateway/listener_generator.go, pkg/plugins/runtime/gateway/route_configuration_generator.go
Simplify more code, extract pure logic and reverse a change introduced in #3834.
* fix(gateway): remove duplicate routes before generating any resources 
* refactor(gateway): extract more pure logic from envoy resource building
=> refactor(gateway): extract more pure logic from envoy resource building 

pkg/xds/envoy/sockets.go
Linux limit is 108 but it looks like BSD and OS X are 104
Signed-off-by: Nicolas Chariglione <nicolas@koyeb.com>
Fix https://github.com/kumahq/kuma/issues/3950
Fix #3950
Let me know if we need a test there
=> fix(kuma-dp): reduce max unix socket length to 104

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
The semantics of this are handled by `MeshGateway`
=> fix(gateway): don't fail to create MeshGatewayInstance with multiple MeshGateway listeners on same port

pkg/dns/vips_allocator.go, pkg/dns/vips_allocator_test.go
`createOrUpdateVIPConfigs` executed with single mesh only reserved existing addresses based on this one mesh instead of all meshes.
When allocating a new address, we were allocating an IP that was already issued for a service in a different mesh. I think that technically it's not a problem, `frontend.mesh` from `mesh-1` can receive `240.0.0.1` and `backend.mesh` from `mesh-2` can resolve to `240.0.0.1` as well and it will work because there is no cross mesh communication. I'd argue that it's better to try to keep separate VIPs because
* It's consistent with Universal. Notice how Universal calls `CreateOrUpdateVIPConfigs()` and then `createOrUpdateVIPConfigs(mesh)` with all the meshes. They never overlap in that scenario
* It's easier to troubleshoot
* It get rid of potential blocker to …
=> fix(kuma-cp): reserve VIPs from all meshes before allocating a new one

.circleci/config.yml, .github/workflows/helm-release.yaml, RELEASE.md, tools/releases/helm.sh, tools/releases/version.sh
- Add a GH workflow to manage Helm charts separately from `kuma` releases
- Package the helm chart for every commit on `master` and `release-*`
- Tweak `appVersion` and `version` depending on commit
- Each chart is available as a `.tar.gz` artifact that can be installed with `helm install`
- We could optionally update the index of a chart repo with these commits as well
- A full chart release can be manually triggered from any commit
- Uses [Github environments](https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions#using-environments) for history and to restrict secret use (optional, just trying it out)
- Option to add a required approval (probably most useful if we do something like auto release charts)
- The entire workflow can be end-to-end …
=> ci(helm): add helm release action 

pkg/xds/envoy/listeners/v3/http_inbound_routes_configurer_test.go, pkg/xds/envoy/listeners/v3/http_outbound_route_configurer_test.go, pkg/xds/envoy/listeners/v3/retry_configurer_test.go, pkg/xds/envoy/routes/v3/routes_configurer.go, pkg/xds/envoy/routes/v3/routes_configurer_test.go, pkg/xds/generator/egress/testdata/01.externalservice-only.golden.yaml, pkg/xds/generator/egress/testdata/03.mixed-services.golden.yaml, pkg/xds/generator/egress/testdata/04.mixed-services-custom-trafficroute.golden.yaml, pkg/xds/generator/egress/testdata/05.mixed-services-with-custom-trafficpermissions.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/5-envoy-config.golden.yaml, pkg/xds/generator/testdata/inbound-proxy/6-envoy-config.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/05.envoy.golden.yaml, pkg/xds/generator/testdata/outbound-proxy/06.envoy.golden.yaml, pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml, pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
If we don't have Timeout for Cluster then it should be set to zero rather than nil.
* set timeout to 0
Fix https://github.com/kumahq/kuma/issues/3934
=> fix(kuma-cp): set inbound route timeout to zero instead of nil

app/kumactl/cmd/install/testdata/install-metrics.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-metrics.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/grafana/kuma-cp.json, mk/kind.mk, pkg/kds/reconcile/interfaces.go, pkg/kds/reconcile/reconciler.go, pkg/kds/server/components.go, pkg/plugins/runtime/gateway/gateway_route_generator_test.go, pkg/plugins/runtime/gateway/listener_generator_test.go, pkg/util/xds/stats_callbacks.go, pkg/util/xds/stats_callbacks_test.go, pkg/xds/server/v3/components.go, pkg/xds/server/v3/reconcile.go, pkg/xds/server/v3/reconcile_test.go
Add config delivery metrics.
So far we had a metric called `xds_generation`, which indicates how long did it took for us to generate config including:
* building MeshContext (it may be cached)
* building Proxy object
* going through ProxyGenerators
* applying ProxyTemplates modifications, hooks, etc.
* Versioning, validation, and setting the snapshot in the SnapshotCache
From this moment we don't know how long it took for the CP to actually send it to Envoy and how long did it take for Envoy to apply this.
Ideally, we would have a metric to count the time between we apply a policy (via kubectl or API) to the time Envoy starts to respect the changed config. This is hard in a distributed environment with two different systems (Kuma CP / Envoy). Because the clock skews, it would need to …
=> feat(kuma-cp): config delivery metrics

pkg/kds/store/sync.go, pkg/kds/store/sync_test.go
Before the fix, if you introduce a new Secret provided by Global CP, the old version of Zone CP would try to create it on every KDS reconnection because it was filtered out from the downstream list.
Zone CP should only accept resources that it knows are managed by Global CP (and the other way around).
Fix #3854
No docs
=> fix(kuma-cp): ignore non-provided KDS resources

app/kumactl/cmd/config/config_control_planes_add_test.go
We're seeing rare cases where the client doesn't timeout on macOS
guessing that having less sensitive timeouts should fix the flakiness
=> fix(test): increase timeout in control_plane kumactl test

pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
Part of the Gateway API spec (https://github.com/kumahq/kuma/issues/3617):
https://github.com/kubernetes-sigs/gateway-api/blob/bdfbb8d9a43c0ef3b9cd7d9239dd95fe9d101f1d/apis/v1alpha2/gateway_types.go#L678-L735
~Blocked by https://github.com/kumahq/kuma/pull/3954~
=> feat(gatewayapi): check for Gateway listener detached

app/kuma-dp/cmd/run.go
Users often get confused when they end up starting with an invalid token
We improve the error message with some extra info to help user get on the right track.
Fix #3943
N/A
=> fix(kuma-dp): better error message when the token is invalid

pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion_test.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gatewayapi_suite_test.go
Before the first listener wasn't set to be conflicted.
Also added some tests.
=> refactor(gatewayapi): set conditions for every conflicting listener

go.mod, pkg/plugins/runtime/k8s/controllers/configmap_controller.go, pkg/plugins/runtime/k8s/controllers/configmap_controller_test.go, pkg/plugins/runtime/k8s/controllers/suite_test.go
We were not looking at annotations on the namespace when looking
at config map that need to be reconciled when service changes.
This would cause issue if pods were not individually annotated.
=> fix(k8s): reconcile serviceMaps when using mesh namespace annotation

.circleci/config.yml, mk/docker.mk
Always use `kumahq` docker registry by default.
When we rebuild and push images, we use other env var anyways.
No docs
=> ci(*): do not require DOCKER_REGISTRY env

pkg/core/bootstrap/bootstrap.go, pkg/core/runtime/builder.go, pkg/core/runtime/reports/reports.go, pkg/core/runtime/runtime.go, pkg/test/runtime/runtime.go
Add uptime of CP and number of policies and gateway DPs to reports.
I won't merge this without testing, but I'm not sure how to do that. Any advice is appreciated.
* Add Kuma CP uptime, number of gateways and policy info to reports.
Fix #436
=> feat(kuma-cp): add uptime, policies, gateway dps to reports

.circleci/config.yml
To save some CI credits we will skip IPV6 and old K8S tests for PRs
No docs.
=> ci(*): disable IPV6 and old K8S test for PR

pkg/core/xds/metadata.go, pkg/core/xds/metadata_test.go
Guard the nil version.dependencies.
I went through code a couple of times and it seems that the only place where we can get a nil panic.
Fix #3968
No docs.
=> fix(kuma-cp): guard the nil version in metadata

pkg/api-server/inspect_endpoints.go, pkg/api-server/inspect_endpoints_test.go, pkg/api-server/testdata/inspect_gateway_dataplane.json
=> fix(api-server): set TrafficeLog/Trace on gateway inspect result

app/kumactl/cmd/inspect/inspect_dataplane_test.go, app/kumactl/pkg/resources/dataplane_inspect_client.go, pkg/api-server/types/inspect.go, pkg/api-server/types/inspect_test.go, pkg/core/resources/model/rest/resource.go
Not being able to know what `Spec` we want makes decoding JSON very painful (see the deleted helper `struct`s).
This is blocking `kumactl` support for [`dataplanes/<gateway>/policies`](#3916) (#3720)
=> refactor(core/resources/model): use global registry to unmarshal rest.Resource

app/kumactl/cmd/inspect/inspect_dataplane.go, app/kumactl/cmd/inspect/inspect_dataplane_test.go, app/kumactl/cmd/inspect/inspect_policy.go, app/kumactl/cmd/inspect/inspect_policy_test.go, app/kumactl/cmd/inspect/testdata/inspect-gateway-dataplane.golden.txt, app/kumactl/cmd/inspect/testdata/inspect-gateway-dataplane.server-response.json, app/kumactl/cmd/inspect/testdata/inspect-health-check-1.5.golden.txt, app/kumactl/cmd/inspect/testdata/inspect-health-check-1.5.server-response.json, app/kumactl/cmd/inspect/testdata/inspect-health-check.server-response.json, app/kumactl/pkg/resources/dataplane_inspect_client.go, pkg/api-server/types/inspect.go
Add builtin gateway `Dataplanes` support to `kumactl inspect <policy>` and `kumactl inspect dataplane`
Ready ~but blocked by #3971 and #3966~
Part of #3720
=> feat(kumactl): add gateway support to inspect dataplane and policy

tools/releases/docker.sh
Pass ARCH explicitly for docker release scripts.
* [Fix ...]
Fix #XXX
=> chore: pass ARCH for docker release

api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/core/resources/apis/mesh/dataplane_helpers.go, pkg/dns/vips/interfaces.go, pkg/dns/vips/virtual_outbound.go, pkg/dns/vips/virtual_outbound_view.go, pkg/dns/vips_allocator.go, pkg/dns/vips_allocator_test.go, pkg/plugins/runtime/k8s/controllers/configmap_controller.go, pkg/plugins/runtime/k8s/controllers/kube_hosts_converter.go, pkg/plugins/runtime/k8s/controllers/outbound_converter.go, pkg/plugins/runtime/k8s/controllers/pod_converter.go, pkg/plugins/runtime/k8s/plugin.go, pkg/xds/generator/inbound_proxy_generator.go, pkg/xds/sync/dataplane_proxy_builder.go, pkg/xds/topology/dns.go, test/e2e/reachableservices/reachableservices_k8s.go, test/e2e/trafficpermission/kubernetes/traffic_permission_k8s.go
This PR changes the way how we persist outbound for Kubernetes.
So far, we were persisting them in the `outbound` section in the `Dataplane` object.
With large deployments, this results in big `Dataplane` objects with the information that is common for the whole mesh.
The change is to use ConfigMap which we already use for storing Kuma VIPs. This way the `outbound` section is empty and we can reuse any logic for VIPs.
The feature is opt-in because we cannot switch it in a stable, backward-compatible way. It will be default in the next+1 minor version of Kuma.
In my testing, I haven't seen a radical improvement in performance. However, my cluster contained 100 services.
With 1000+ services we probably would see it a bit more.
Also, as a result, Pod Controller in the future can just watch …
=> perf(kuma-cp): move outbounds from Dataplane to Config

app/kumactl/cmd/install/testdata/install-demo.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-demo.overrides.golden.yaml, app/kumactl/data/install/k8s/demo/demo.yaml, dev/examples/k8s/example-app/example-app.yaml, examples/kafka/manifest.yaml, test/e2e/externalservices/testdata/externalservice-http-server.yaml, test/e2e/externalservices/testdata/externalservice-https-server.yaml, test/framework/deployments/testserver/kubernetes.go
See https://github.com/kumahq/kuma-website/pull/731
https://github.com/kumahq/kuma-website/pull/731
=> chore(kuma-cp): use appProtocol by default

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/plugins/runtime/k8s/plugin_gateway.go
Gateway API behind a config flag.
xref #3702
Docs are in progress for the whole feature.
=> feat(kuma-cp): Gateway API behind experimental flag

pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
In http route controller we convert API Gateway's HTTPRoute to Kuma's MeshGatewayRoute.
HTTP route looks like this
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
name: echo
namespace: kuma-demo
spec:
parentRefs:
- group: gateway.networking.k8s.io
kind: Gateway
name: kuma
rules:
- backendRefs:
- group: ""
kind: Service
name: demo-app
port: 5000
weight: 1
matches:
- path:
type: PathPrefix
value: /
```
We can only consider HTTPRoute valid if it has a valid `parentsRef`. See `case attachment.Allowed:` in this file.
The problem was that I used this HTTPRoute with this Gateway
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
name: kuma
namespace: default
spec:
gatewayClassName: kuma
listeners:
- name: proxy
port: 8080
protocol: HTTP
``` …
=> fix(kuma-cp): skip creating MeshGateways without proper attachmenet

mk/k3d.mk
Because of https://github.com/k3d-io/k3d/issues/900
we're getting failures in `k3d import images` until it's fixed
we'll retry on failures
=> fix(ci): retry k3d image load
