kumahq/kuma

- Makefile
changes:
* update version of `KIND`
* cleanup `Makefile`
> chore: update version of KIND

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Add templates for GitHub issues and PRs.
Fixes #119
> docs(github) add pr/issue templates

- DEVELOPER.md
- app/kumactl/cmd/cmd_suite_test.go
- app/kumactl/cmd/root.go
- app/kumactl/cmd/root_test.go
- app/kumactl/pkg/cmd/root_context.go
- app/kumactl/pkg/config/defualt.go
- app/kumactl/pkg/config/io.go
Create default config when the ~/.kumactl/config file does not exist
Solves #195
> kumactl: create default config

- CODE_OF_CONDUCT.md
Adding a community Code of Conduct file.
> docs: add community code of conduct

- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
> fix(*) renaming kuma-cp configuration

- .gitignore
> chore(gitignore) ignoring .DS_Store

- app/kumactl/cmd/get/get_meshes.go
- app/kumactl/cmd/get/testdata/get-meshes.golden.txt
- app/kumactl/pkg/output/table/cells.go
changes:
* change column name
* change cell value
> kumactl: improve output of `get meshes`

- pkg/xds/envoy/envoy.go
- pkg/xds/envoy/envoy_test.go
- pkg/xds/generator/inbound_proxy_generator_test.go
- pkg/xds/generator/proxy_template.go
- pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/5-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/6-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/7-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/8-envoy-config.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/06.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/08.envoy.golden.yaml
- pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml
- pkg/xds/generator/testdata/template-proxy/1-envoy-config.golden.yaml
- pkg/xds/server/snapshot_generator_test.go
- pkg/xds/server/testdata/3-envoy-config.golden.yaml
- pkg/xds/server/testdata/4-envoy-config.golden.yaml
- pkg/xds/server/testdata/5-envoy-config.golden.yaml
- pkg/xds/server/testdata/6-envoy-config.golden.yaml
- pkg/xds/server/testdata/7-envoy-config.golden.yaml
- pkg/xds/server/testdata/8-envoy-config.golden.yaml
changes:
* configure mTLS on client side (at Cluster resource)
* require client certificate on server side (as Listener resource)
> control-plane: configure mTLS on client side (at Cluster resource)

- Dockerfile.kuma-cp
- Dockerfile.kuma-injector
- Dockerfile.kuma-tcp-echo
- Dockerfile.kumactl
- Makefile
- app/kuma-tcp-echo/go.mod
- app/kuma-tcp-echo/go.sum
- app/kuma-tcp-echo/main.go
Adding a sample `kuma-tcp-echo` application to be used in demos and getting started guides.
> feat(tcp-echo) adding kuma-tcp-echo sample application

- api/mesh/v1alpha1/dataplane_helpers.go
- api/mesh/v1alpha1/dataplane_helpers_test.go
- dev/examples/universal/dataplanes/example.yaml
- dev/examples/universal/trafficpermissions/trafficpermission-2.yaml
- pkg/core/permissions/matcher.go
- pkg/core/xds/types.go
- pkg/xds/envoy/envoy.go
- pkg/xds/envoy/envoy_test.go
- pkg/xds/envoy/rbac.go
- pkg/xds/generator/inbound_proxy_generator_test.go
- pkg/xds/generator/proxy_template.go
- pkg/xds/generator/proxy_template_profile_source_test.go
- pkg/xds/generator/proxy_template_test.go
- pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/5-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/6-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/7-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/8-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml
- pkg/xds/generator/testdata/template-proxy/1-envoy-config.golden.yaml
- pkg/xds/server/components.go
- pkg/xds/server/snapshot_generator_test.go
- pkg/xds/server/testdata/3-envoy-config.golden.yaml
- pkg/xds/server/testdata/4-envoy-config.golden.yaml
- pkg/xds/server/testdata/5-envoy-config.golden.yaml
- pkg/xds/server/testdata/6-envoy-config.golden.yaml
- pkg/xds/server/testdata/7-envoy-config.golden.yaml
- pkg/xds/server/testdata/8-envoy-config.golden.yaml
- Match TrafficPermissions against dataplane
- Create RBAC configuration for matched TrafficPermissions
- Update tests for TrafficPermissions
> feature: traffic permissions

- pkg/config/app/kuma-cp/config.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/core/bootstrap/bootstrap.go
- pkg/core/runtime/reports/reports.go
> kuma-cp: phone home logging

- examples/kubernetes/sample-service.yaml
Kubernetes example for Getting Started
> docs(*) adding example

- DEVELOPER.md
- Makefile
Updated the DEVELOPER.md file to be more comprehensive on the dependencies such as clang-format. Also added a few more tests tasks in the Makefile and organized it to be consistent with how the `make build` is structured.
* fix DEVELOPER.md to mention clang-format dependency
* add `make test/kumactl` and `make test/kuma-cp` 
Fix #214
> Fix: issue 214

- .circleci/config.yml
- Makefile
changes:
* fix `make check`
* fix `make deploy/control-plane/k8`
> dev: fixes for development environment

- pkg/plugins/discovery/k8s/controllers/pod_controller.go
changes:
* on `k8s`, `Dataplane` definition should be re-generated as soon as relevant `Service` changes
> control-plane: re-generate Dataplane definition on k8s Service update

- pkg/core/bootstrap/bootstrap.go
Fix issue leading to duplicated anonymous reports.
> control-plane: fix duplicated anonymous reports

- .circleci/config.yml
- DEVELOPER.md
- Dockerfile.kuma-cp
- Dockerfile.kuma-dp
- Dockerfile.kuma-injector
- Dockerfile.kuma-tcp-echo
- Dockerfile.kumactl
- Makefile
- api/DEVELOPER.md
- pkg/plugins/resources/k8s/native/Dockerfile
* upgrade version of Golang up to `1.12.9` 
Fix #244
> chore: update version of Golang

- app/kuma-dp/pkg/dataplane/envoy/envoy.go
Improve error reporting on failure to find Envoy binary.
> kuma-dp: improve envoy binary lookup error reporting

- tools/releases/docker.sh
- tools/releases/dockerfiles/Dockerfile.kuma-cp
- tools/releases/dockerfiles/Dockerfile.kuma-dp
- tools/releases/dockerfiles/Dockerfile.kuma-injector
- tools/releases/dockerfiles/Dockerfile.kuma-tcp-echo
Thanks @yskopets for the review.
> ci: address docker automation pr feedback

- app/kuma-injector/cmd/cmd_suite_test.go
- pkg/cmd/version/version_test.go
- pkg/plugins/discovery/k8s/controllers/suite_test.go
- pkg/plugins/resources/k8s/k8s_suite_test.go
- pkg/plugins/secrets/k8s/k8s_suite_test.go
Remove variables that look to be copy-pasta from other tests.
> Remove Unused Config Variables

- pkg/plugins/discovery/k8s/controllers/suite_test.go
- pkg/plugins/resources/k8s/k8s_suite_test.go
- pkg/plugins/secrets/k8s/k8s_suite_test.go
> core: remove unused imports

- pkg/core/ca/builtin/manager.go
- pkg/core/resources/apis/mesh/mesh_helpers.go
- pkg/plugins/runtime/k8s/controllers/mesh_controller.go
- pkg/plugins/runtime/k8s/plugin.go
* introduce `Mesh` Controller to automate creation of `Builtin CA` 
Fix #262
> kuma-cp: use Controller to create Builtin CA on k8s

- LICENSE
Add apache license file
Fix #320
> docs(*) add license file

- CHANGELOG.md
- tools/releases/distros.sh
Changelog for a new version of Kuma
> docs(*) changelog for 0.2.2

- .circleci/config.yml
* implement best practices from https://circleci.com/docs/2.0/caching/
> ci: optimize caching of Golang dependencies on CircleCI

- examples/kubernetes/kuma-demo/README.md
- examples/kubernetes/kuma-demo/kuma-demo-aio.yaml
- examples/kubernetes/kuma-demo/kuma-demo-log.yaml
- examples/kubernetes/kuma-demo/kuma-demo-policy.yaml
Add k8s deployment guide for new kuma-demo
> chore: add k8s deployment guide

- examples/minikube/kumactl_workflow.sh
* refactor kumactl workflow script
> ci: refactor kumactl workflow script

- pkg/tokens/builtin/server/dataplane_token_server_test.go
This fixes a dropped test error.
> pkg/tokens/builtin/server: fix dropped error

- RELEASE.md
Corrected Grammer Mistake and Errors in RELEASE.md file
> Corrected Grammer Mistake and Errors in RELEASE.md file

- Makefile
- Makefile.e2e.mk
* split e2e test for kubernetes into a dedicated Makefile
* groundwork for a complete rework of `Docker Compose` example
> ci: split e2e test for kubernetes into a dedicated Makefile

- Makefile
- Makefile.dev.mk
* split commands that setup dev environment into a dedicated Makefile
> chore: split commands that setup dev environment into a dedicated Makefile

- pkg/core/resources/apis/mesh/traffic_route.go
- pkg/core/resources/apis/mesh/traffic_route_validator.go
- pkg/core/resources/apis/mesh/traffic_route_validator_test.go
- pkg/core/resources/apis/mesh/validators.go
- pkg/core/validators/types.go
- pkg/core/validators/types_test.go
* add validation for `TrafficRoute`
> kuma-cp: validate TrafficRoute

- pkg/core/resources/apis/mesh/mesh.go
- pkg/core/resources/apis/mesh/mesh_validator.go
- pkg/core/resources/apis/mesh/mesh_validator_test.go
> feat(kuma-cp) mesh validation

- app/kumactl/cmd/apply/apply.go
- app/kumactl/cmd/apply/apply_test.go
- app/kumactl/pkg/resources/client.go
- app/kumactl/pkg/tokens/client.go
- pkg/catalogue/client/client.go
- pkg/util/http/client.go
Fix failing tests from PR #402 
* Checks response's status code
> fix parse url test

- api/mesh/v1alpha1/traffic_log.pb.go
- api/mesh/v1alpha1/traffic_log.proto
- app/kumactl/cmd/get/get_traffic_logs_test.go
- app/kumactl/cmd/get/testdata/get-traffic-logs.golden.json
- app/kumactl/cmd/get/testdata/get-traffic-logs.golden.yaml
- pkg/core/logs/matcher.go
- pkg/core/logs/matcher_test.go
Removes multiple rules for one TrafficLogs entity. It simplifies model and logic connected with logging.
⚠️ This is breaking change.
> feat(api) remove multiple rules for logging

- examples/kubernetes/kuma-demo/README.md
- examples/kubernetes/kuma-demo/kuma-demo-local.yaml
Fix deployment yaml for minikube environment
> fix minikube instructions

- pkg/plugins/resources/remote/store.go
- pkg/plugins/resources/remote/store_test.go
Implement delete method in remote store so the request is sent to the control plane
> fix(kumactl) implement delete method in remote store

- CHANGELOG.md
[ci skip]
* add release notes for version `0.3.0`
> docs: add release notes for 0.3.0

- tools/releases/distros.sh
- tools/releases/dockerfiles/Dockerfile.kuma-dp
Update Envoy to v1.12.1
New binaries are available in Bintray https://bintray.com/kong/envoy
Fix #420
> feat(kuma-dp) update envoy to v1.12.1

- app/kumactl/cmd/delete/delete.go
- pkg/api-server/mesh_ws_test.go
- pkg/api-server/resource_ws_test.go
- pkg/core/managers/apis/mesh/mesh_manager_test.go
- pkg/plugins/resources/k8s/store.go
- pkg/plugins/resources/k8s/store_test.go
- pkg/plugins/resources/memory/store.go
- pkg/plugins/resources/postgres/store.go
- pkg/test/store/store_test_template.go
Support 404 not found when deleting resources
Fix #190
> feat(kuma-cp) support not found on delete resources

- app/kumactl/cmd/config/config_control_planes_add.go
- app/kumactl/cmd/config/config_control_planes_add_test.go
Use override msg when adding a control plane
> feat(kumactl) use override msg when adding a control plane

- RELEASE.md
Updating the release checklist for every new version of Kuma.
> docs(release) updating release checklist

- docs/proposals/external-ca.md
Proposal for introducing external CA to Kuma.
> External CA proposal

- dev/examples/universal/health-checks/active+passive.yaml
- dev/examples/universal/health-checks/active.yaml
- dev/examples/universal/health-checks/passive.yaml
- pkg/api-server/definitions/all.go
- pkg/api-server/definitions/health_check.go
- pkg/api-server/health_check_ws_test.go
- pkg/core/resources/apis/mesh/health_check.go
- pkg/plugins/resources/k8s/consistent_kind_type_test.go
* add `HealthCheck` to core model
> kuma-cp: add HealthCheck to core model

- pkg/core/resources/apis/mesh/health_check.go
- pkg/core/resources/apis/mesh/healthcheck_validator.go
- pkg/core/resources/apis/mesh/healthcheck_validator_test.go
- pkg/core/resources/apis/mesh/validators.go
* add validation logic for `HealthCheck` resource
> kuma-cp: validate HealthCheck resource

- app/kumactl/cmd/delete/delete.go
- app/kumactl/cmd/delete/delete_test.go
- app/kumactl/cmd/get/get.go
- app/kumactl/cmd/get/get_healthchecks.go
- app/kumactl/cmd/get/get_healthchecks_test.go
- app/kumactl/cmd/get/testdata/get-healthchecks.golden.json
- app/kumactl/cmd/get/testdata/get-healthchecks.golden.txt
- app/kumactl/cmd/get/testdata/get-healthchecks.golden.yaml
- docs/cmd/kumactl/HELP.md
- tools/docs/kumactl/gen_help.sh
- tools/e2e/examples/minikube/kumactl_workflow.sh
* add `kumactl get healthchecks` command
> kumactl: add `get healthchecks` command

- pkg/core/logs/matcher.go
- pkg/core/policy/matcher.go
- pkg/core/policy/types.go
- pkg/core/xds/types.go
* generalize `SelectOutboundConnectionPolicies()` into `SelectConnectionPolicies()` with a given list of destination services
> kuma-cp: generalize SelectOutboundConnectionPolicies() into SelectConnectionPolicies() with a given list of destination services

- dev/examples/universal/health-checks/active.yaml
- pkg/core/resources/apis/mesh/healthcheck_validator.go
- pkg/xds/envoy/envoy.go
- pkg/xds/envoy/envoy_test.go
- pkg/xds/generator/proxy_template.go
- pkg/xds/generator/proxy_template_profile_source_test.go
- pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml
* include `health checks` into generated `Envoy` configuration
> kuma-cp: include health checks into generated Envoy configuration

- pkg/core/bootstrap/bootstrap.go
- pkg/core/managers/apis/mesh/mesh_manager.go
- pkg/core/managers/apis/mesh/mesh_manager_test.go
- pkg/core/managers/apis/mesh/mesh_validator.go
- pkg/core/validators/apis/mesh/mesh_validator.go
- pkg/test/runtime/runtime.go
Validate that CA can be set to provided or can be changed.
> feat(kuma-cp) Validate CA on Universal

- pkg/core/bootstrap/bootstrap.go
- pkg/core/managers/apis/mesh/mesh_manager.go
- pkg/core/managers/apis/mesh/mesh_manager_test.go
- pkg/core/managers/apis/mesh/mesh_validator.go
- pkg/test/runtime/runtime.go
https://github.com/Kong/kuma/pull/475 was not merged to master
> feat(kuma-cp) Validate CA on Universal (#475)

- pkg/admin-server/server.go
- pkg/core/ca/provided/manager.go
- pkg/core/ca/provided/rest/webservice.go
- pkg/core/ca/provided/rest/webservice_test.go
- pkg/core/resources/apis/mesh/mesh_helpers.go
Validate that mTLS is disabled or the type is different than PRovided when deleting signing certs
> feat(kuma-cp) validate enabled Provided CA when deleting signing cert

- CHANGELOG.md
* docs: add CHANGELOG for 0.3.1 release
> docs: add CHANGELOG for 0.3.1 release

- UPGRADE.md
* docs: add `UPGRADE.md` similarly to `Kong/kong`
> docs: add UPGRADE.md

- docs/proposals/prometheus-metrics.md
* add proposal for collecting `Prometheus` metrics out of `Envoys`
> docs: add proposal for collecting Prometheus metrics out of Envoys

- openapi/swagger20.yaml
Added Swagger 2.0 Spec for Kuma HTTP APIs (https://kuma.io/docs/0.3.1/documentation/#http-api)
* New Swagger Spec
* Added REST Endpoints
* Created Tags
Fix #XXX
> Added Swagger 2.0 for Kuma HTTP APIs

- pkg/core/managers/apis/mesh/mesh_manager.go
- pkg/core/resources/store/options.go
- pkg/core/resources/store/store.go
- pkg/core/rest/errors/error_handler.go
- pkg/plugins/resources/k8s/store.go
- pkg/plugins/resources/memory/store.go
- pkg/plugins/resources/postgres/store.go
- pkg/test/store/store_test_template.go
Add support to get resource by version and fix optimistic locking issue in mesh manager
Fix #487
> feat(kuma-cp) get resource by version

- app/kuma-injector/pkg/injector/injector.go
- app/kumactl/cmd/get/get_meshes.go
- pkg/core/resources/apis/mesh/dataplane_helpers.go
- pkg/core/resources/apis/mesh/dataplane_helpers_test.go
- pkg/core/resources/apis/mesh/mesh_helpers.go
- pkg/core/resources/apis/mesh/mesh_helpers_test.go
- pkg/xds/generator/prometheus_endpoint_generator.go
- pkg/xds/generator/prometheus_endpoint_generator_test.go
- pkg/xds/generator/proxy_template_profile_source_test.go
- pkg/xds/generator/proxy_template_test.go
- pkg/xds/server/snapshot_generator_test.go
* refactor out `dataplane.GetPrometheusEndpoint(mesh)` method
> refactoring: refactor out `dataplane.GetPrometheusEndpoint(mesh)` method

- .circleci/config.yml
- CHANGELOG.md
- Makefile
- Makefile.e2e.mk
- app/kuma-prometheus-sd/cmd/cmd_suite_test.go
- app/kuma-prometheus-sd/cmd/root.go
- app/kuma-prometheus-sd/cmd/root_helper_test.go
- app/kuma-prometheus-sd/cmd/root_test.go
- app/kuma-prometheus-sd/cmd/run.go
- app/kuma-prometheus-sd/cmd/run_test.go
- app/kuma-prometheus-sd/main.go
- tools/releases/distros.sh
- tools/releases/docker.sh
- tools/releases/dockerfiles/Dockerfile.kuma-prometheus-sd
- tools/releases/templates/README
* skaffold a new binary - `kuma-prometheus-sd`
> kuma-prometheus-sd: skaffold a new binary

- CHANGELOG.md
- app/kuma-prometheus-sd/cmd/run.go
- pkg/config/app/kuma-prometheus-sd/config.go
- pkg/config/app/kuma-prometheus-sd/config_test.go
- pkg/config/app/kuma-prometheus-sd/kuma_prometheus_sd_test.go
- pkg/config/app/kuma-prometheus-sd/testdata/default-config.golden.yaml
- pkg/config/app/kuma-prometheus-sd/testdata/invalid-config.input.yaml
- pkg/config/app/kuma-prometheus-sd/testdata/valid-config.input.yaml
* add configuration options to `kuma-prometheus-sd run`
> kuma-prometheus-sd: add configuration options

- CHANGELOG.md
- pkg/core/bootstrap/autoconfig.go
- pkg/core/bootstrap/autoconfig_test.go
* enable proxying of `Kuma REST API`
> kuma-gui: enable proxying of Kuma REST API

- CHANGELOG.md
* update CHANGELOG for 0.3.2 release
> docs: update CHANGELOG for 0.3.2 release

- CHANGELOG.md
* highlight major new features in the CHANGELOG of 0.3.2 release
> docs: highlight major new features in the CHANGELOG of 0.3.2 release

- app/kuma-prometheus-sd/README.md
* document `kuma-prometheus-sd` tool
> docs: document `kuma-prometheus-sd` tool

- README.md
Improvements to the `README.md`.
> docs(readme) improvements to the readme

- pkg/test/xds/client/app/main.go
- pkg/test/xds/client/client.go
* create a test client for `Kuma` xDS server to simulate a fleet of `Envoys`
> test: create a test client for Kuma xDS server to simulate a fleet of Envoys

- pkg/xds/envoy/listeners/network_access_log_configurer.go
- pkg/xds/envoy/listeners/prometheus_endpoint_configurer.go
- pkg/xds/envoy/listeners/tcp_proxy_configurer.go
- pkg/xds/envoy/listeners/util.go
- pkg/xds/envoy/listeners/util_test.go
* refactor out a reusable func
> refactoring: refactor out a reusable func

- docs/proposals/tracing.md
> docs(proposal) tracing

- app/kuma-ui/pkg/server/server.go
- pkg/admin-server/server.go
- pkg/api-server/server.go
- pkg/mads/server/grpc.go
- pkg/sds/server/grpc.go
- pkg/xds/bootstrap/server.go
- pkg/xds/server/diagnostics.go
- pkg/xds/server/grpc.go
Fix #408
Added Logging of Interface of each server kuma-cp starts
Issues resolved
Fix #408
> fix(kuma-cp) log network interface for all server kuma-cp starts

- CHANGELOG.md
- pkg/api-server/definitions/all.go
- pkg/api-server/definitions/traffic_trace.go
- pkg/api-server/traffic_trace_ws_test.go
Support for TrafficTrace in Kuma REST API
> feat(kuma-cp) TrafficTrace in Kuma REST API

- pkg/xds/envoy/listeners/filter_chain_builder.go
- pkg/xds/envoy/listeners/filter_chain_configurer.go
- pkg/xds/envoy/listeners/filter_chain_configurer_test.go
- pkg/xds/envoy/listeners/http_connection_manager_configurer.go
- pkg/xds/envoy/listeners/http_connection_manager_configurer_test.go
- pkg/xds/envoy/listeners/http_inbound_route_configurer.go
- pkg/xds/envoy/listeners/http_inbound_route_configurer_test.go
- pkg/xds/envoy/listeners/inbound_listener_configurer.go
- pkg/xds/envoy/listeners/listener_builder.go
- pkg/xds/envoy/listeners/network_access_log_configurer.go
- pkg/xds/envoy/listeners/network_access_log_configurer_test.go
- pkg/xds/envoy/listeners/network_rbac_configurer.go
- pkg/xds/envoy/listeners/network_rbac_configurer_test.go
- pkg/xds/envoy/listeners/original_dst_forwarder_configurer_test.go
- pkg/xds/envoy/listeners/outbound_listener_configurer.go
- pkg/xds/envoy/listeners/outbound_listener_configurer_test.go
- pkg/xds/envoy/listeners/prometheus_endpoint_configurer.go
- pkg/xds/envoy/listeners/prometheus_endpoint_configurer_test.go
- pkg/xds/envoy/listeners/server_mtls_configurer.go
- pkg/xds/envoy/listeners/server_mtls_configurer_test.go
- pkg/xds/envoy/listeners/tcp_proxy_configurer.go
- pkg/xds/envoy/listeners/tcp_proxy_configurer_test.go
- pkg/xds/envoy/listeners/transparent_proxying_configurer_test.go
- pkg/xds/envoy/listeners/util.go
- pkg/xds/envoy/listeners/util_test.go
- pkg/xds/envoy/types.go
- pkg/xds/generator/prometheus_endpoint_generator.go
- pkg/xds/generator/proxy_template.go
* introduce `FilterChainBuilder` in addition to `ListenerBuilder`
> refactoring: introduce FilterChainBuilder in addition to ListenerBuilder

- CHANGELOG.md
- app/kumactl/pkg/output/json/testdata/mesh.golden.json
- pkg/core/resources/model/rest/resource.go
- pkg/core/resources/model/rest/resource_test.go
- pkg/plugins/resources/remote/store_test.go
Fix order of Meta elements in Resource JSON.
> feat(kuma-cp) order of meta in resource JSON

- docs/proposals/TrafficRoute-L4.md
add design proposal for L4 `TrafficRoute` implementation
> docs: add design proposal for L4 TrafficRoute implementation

- CHANGELOG.md
> docs: update CHANGELOG for 0.4.0 release

- UPGRADE.md
> docs(*) UPGRADE notes on Kuma 0.4.0

- pkg/envoy/accesslog/commands.go
- pkg/xds/envoy/listeners/access_log_configurer.go
- pkg/xds/envoy/listeners/http_access_log_configurer.go
- pkg/xds/envoy/listeners/http_access_log_configurer_test.go
- pkg/xds/envoy/listeners/network_access_log_configurer.go
- pkg/xds/envoy/listeners/network_access_log_configurer_test.go
- pkg/xds/generator/outbound_proxy_generator_test.go
- pkg/xds/generator/proxy_template.go
- pkg/xds/generator/testdata/outbound-proxy/09.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/10.envoy.golden.yaml
Included the `Mesh name` in the access log. 
Modified the format of 
1. defaultHttpAccessLogFormat
1. defaultNetworkAccessLogFormat
Fix #599
> added the mesh to the access logs - http and network

- api/Makefile
- api/go.mod
- api/go.sum
- go.mod
- go.sum
- pkg/plugins/resources/k8s/native/go.sum
Update protoc validation. Newest version of Envoy API requires changes from master
> chore(*) update protoc validation version to master

- docs/proposals/fault-injection.md
Proposal for implementing Fault Injection in Kuma
> docs(kuma-cp) Fault Injection proposal

- pkg/xds/envoy/clusters/clusters.go
- pkg/xds/envoy/clusters/clusters_test.go
- pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
- pkg/xds/generator/testdata/template-proxy/1-envoy-config.golden.yaml
- pkg/xds/generator/transparent_proxy_generator_test.go
- pkg/xds/server/testdata/envoy-config.golden.yaml
Backporting https://github.com/Kong/kuma/pull/466
> Replace deprected field ORIGINAL_DST_LB  to CLUSTER_PROVIDED

- CHANGELOG.md
- Makefile.e2e.mk
- tools/e2e/examples/docker-compose/docker-compose.yaml
- tools/e2e/examples/minikube/kuma-routing/kuma-routing.yaml
- tools/releases/distros.sh
- tools/releases/dockerfiles/Dockerfile.kuma-dp
> chore(*) upgrade Envoy to 1.13.1

- docs/cmd/kumactl/HELP.md
Additional `make check` for master
> fix(*) make check

- CHANGELOG.md
- app/kumactl/cmd/get/get_meshes.go
- app/kumactl/cmd/get/get_meshes_test.go
- app/kumactl/cmd/get/testdata/get-meshes.golden.json
- app/kumactl/cmd/get/testdata/get-meshes.golden.txt
- app/kumactl/cmd/get/testdata/get-meshes.golden.yaml
- pkg/core/resources/apis/mesh/mesh_helpers.go
- pkg/core/resources/apis/mesh/mesh_helpers_test.go
Feature #628
Added Logging and Tracing Information for meshes
*Implemented logging and tracing information for meshes
* added helper functions for getting logging and tracing information and tests
* updated tests
Fix #628
> feature(kumactl) added logging and tracing information

- Makefile.e2e.mk
Minor change to the `Makefile` to add deploying Kuma on Minikube without the demo application.
> chore(makefile): adding deploy command for Kuma on Minikube

- app/kuma-cp/cmd/run.go
- app/kuma-dp/cmd/root.go
- app/kuma-dp/cmd/run.go
Log the Kuma version number on `kuma-cp` and `kuma-dp`.
> chore(cli): print Kuma version number

- .circleci/config.yml
- tools/releases/dockerfiles/Dockerfile.kuma-init
Updating to latest `1.1.x` version (and adding test for Kubernetes `1.17.0`).
> chore(proxy_init): updating to version 1.1.17

- CODE_OF_CONDUCT.md
Adopting the CNCF code of conduct.
> docs: adopting CNCF code of conduct

- app/kumactl/cmd/apply/apply.go
- app/kumactl/cmd/apply/apply_test.go
- app/kumactl/cmd/get/testdata/get-secret.golden.json
- app/kumactl/cmd/get/testdata/get-secret.golden.yaml
- app/kumactl/cmd/get/testdata/get-secrets.golden.json
- app/kumactl/cmd/get/testdata/get-secrets.golden.yaml
- pkg/api-server/fault_injection_endpoints_test.go
- pkg/api-server/health_check_endpoints_test.go
- pkg/api-server/traffic_route_endpoints_test.go
- pkg/api-server/traffic_trace_endpoints_test.go
- pkg/core/alias.go
- pkg/core/resources/manager/manager.go
GitHub did not run tests on the last PR that was merged (I was tricked by "all checks are ok"). There were some problematic tests.
> chore(*) fix time in tests

- Makefile.e2e.mk
Some leftovers after removing TCP Echo
> chore(ci) remove TCP Echo deploy

- CHANGELOG.md
> contributed by 

- CHANGELOG.md
- app/kuma-cp/cmd/migrate.go
fix kuma-cp migrate text
Fix #632
> fix kuma-cp migrate help text

- CHANGELOG.md
- UPGRADE.md
- tools/migrations/0.5.0/kuma-0.5.0-k8s-remove_injector_resources.sh
- tools/migrations/0.5.0/kuma-0.5.0-k8s-set_owner_references.sh
- tools/releases/docker.sh
Updte the changelog and the upgrade instructions for 0.5.0. Add the new folder to host
the migration scripts per release version: `tools/migrations/`
> chore(*) update changelog and upgrade instructions for 0.5.0

- .dockerignore
Exclude all build but the linux artifacts
> chore(*) more dockerignore improvements

- pkg/core/runtime/reports/reports.go
Send additional start signal using Splunk
> feat(kuma-cp) send start signal

- .github/PULL_REQUEST_TEMPLATE.md
Update the PR template to request for documentation PR.
> chore(*) update PR template

- CHANGELOG.md
Add a note in the CHANGELOG.md about the deprecation of Health Checks in the next version.
> chore(*) add Health Check deprecation note in the CHANGELOG.md

- pkg/admin-server/secrets_ws.go
- pkg/admin-server/server.go
- pkg/core/bootstrap/bootstrap.go
- pkg/core/bootstrap/bootstrap_test.go
- pkg/core/datasource/loader.go
- pkg/core/datasource/loader_test.go
- pkg/core/managers/apis/mesh/mesh_manager.go
- pkg/core/managers/apis/mesh/mesh_manager_test.go
- pkg/core/runtime/builder.go
- pkg/core/runtime/runtime.go
- pkg/core/secrets/manager/manager.go
- pkg/plugins/ca/builtin/manager.go
- pkg/plugins/ca/builtin/manager_test.go
- pkg/plugins/ca/builtin/plugin.go
- pkg/sds/server/server_test.go
- pkg/test/runtime/runtime.go
- pkg/tokens/builtin/components.go
- pkg/tokens/builtin/issuer/signing_key.go
This PR aims to simplify the implementation of syncing Secrets over KDS. Secret synchronization over KDS will be done in the next PR
> feat(kuma-cp) make secretManager to implement ResourceManager

- pkg/api-server/dataplane_overview_endpoints.go
- pkg/api-server/dataplane_overview_endpoints_test.go
- pkg/core/resources/apis/mesh/dataplane_overview.go
Add `?ingress=true` to datplane overviews
> API ingress filter

- app/kumactl/cmd/install/install_dns.go
Cleanup old `mesh:53` configs when proposing CoreDNS Config Map on k8s with `kumactl install dns`
> chore(kumactl) install dns clean ups before installing the new DNS

- CHANGELOG.md
- UPGRADE.md
Changelog and Upgrade docs for 0.6.0
> docs(*) changelog for 0.6.0

- test/dockerfiles/Dockerfile.universal
- test/e2e/kuma_deploy_global_remote_test.go
- test/e2e/kuma_deploy_hybrid_test.go
- test/e2e/kuma_deploy_ingress_test.go
- test/e2e/kuma_deploy_multi_apps_test.go
- test/e2e/kuma_deploy_universal_test.go
- test/framework/config.go
- test/framework/constants.go
- test/framework/interface.go
- test/framework/k8s_cluster.go
- test/framework/k8s_controlplane.go
- test/framework/kumactl.go
- test/framework/setup.go
- test/framework/universal_app.go
- test/framework/universal_cluster.go
- test/framework/universal_controlplane.go
More e2e testing:
* Universal Global + 2x Remotes
* Universal Global + 2x Remotes + 2x K8s remotes
> test(e2e) add Universal Distributed and Hybrid tests

- pkg/core/runtime/reports/reports.go
> feat(kuma-cp) add mode to logging

- app/kuma-dp/pkg/dataplane/accesslogs/server.go
> fix(*) after #894

- pkg/xds/envoy/routes/default_route_configurer.go
- pkg/xds/envoy/routes/default_route_configurer_test.go
Added totalWeight to `default_route_configurer`.
* [Fix ...]
Fix #898
> Added total weight for route configurer

- test/e2e/kuma_deploy_global_remote_test.go
This fixes the flaky e2e test.
> fix(e2e) global/remote zone status retries

- CONTRIBUTING.md
Updated contributing readme for signed commit
> docs: update contributing readme

- test/e2e/kuma_deploy_global_remote_test.go
- test/e2e/kuma_deploy_hybrid_test.go
- test/e2e/kuma_deploy_universal_test.go
- test/framework/universal_app.go
leftover after service tag rename
> fix(tests) fix e2e service tag

- pkg/plugins/discovery/k8s/controllers/inbound_converter.go
- pkg/plugins/discovery/k8s/controllers/pod_converter_test.go
Fixed InboudTagsFor to remove empty labels and ignore it
Fixes #753
Signed-off-by: Tharun <rajendrantharun@live.com>
> fix(kuma-cp) Fix Empty Labels on kuma-cp pod converter

- test/dockerfiles/Dockerfile.universal
- tools/e2e/examples/docker-compose/docker-compose.yaml
- tools/e2e/examples/minikube/kuma-routing/kuma-routing.yaml
- tools/releases/distros.sh
- tools/releases/dockerfiles/Dockerfile.kuma-dp
Update Envoy to v1.15.0.
New binaries are up in Bintray
> feat(kuma-dp) update envoy to v1.15.0

- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/validation_test.go
> tests(*) fix install cp and webhook validation

- CHANGELOG.md
- UPGRADE.md
> chore(*) changelog for 0.7.0

- tools/releases/distros.sh
Parametrize distros script for release name.
> chore(ci) parametrize distros script

- .circleci/config.yml
> chore(*) improve Circle CI resource utilization

- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/_helpers.tpl
- deployments/charts/kuma/templates/cp-deployment.yaml
- deployments/charts/kuma/templates/cp-service.yaml
- deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
- deployments/charts/kuma/templates/ingress-deployment.yaml
- deployments/charts/kuma/templates/ingress-rbac.yaml
- deployments/charts/kuma/templates/ingress-service.yaml
- deployments/charts/kuma/values.yaml
- test/e2e/kuma_helm_deploy_global_remote_test.go
- test/framework/interface.go
- test/framework/k8s_cluster.go
Add option to install Ingress.
Fix #953
> feat(kuma-cp) Ingress helm chart

- CHANGELOG.md
> chore(*) changelog for 0.7.1

- tools/releases/distros.sh
> fix(ci) fix KUMA_CONFIG_PATH parameter

- pkg/api-server/resource_endpoints.go
- pkg/api-server/server.go
Enabling a more elaborate message when accessing the API, depending on the Kuma CP mode.
> fix(kumacp) API readonly message according to Mode

- docs/cmd/kumactl/HELP.md
- tools/docs/kumactl/gen_help.sh
> chore(docs) get and inspect in zone cli help

- pkg/dns/vips_allocator.go
> rely only on original hostname to free IPs

- .circleci/config.yml
- README.md
- RELEASE.md
> chore(*) use stable branch badge

- RELEASE.md
Co-authored-by: Austin Cawley-Edwards <austin.cawley@gmail.com>
Signed-off-by: austin ce <austin.cawley@gmail.com>
> docs(*) update typos in RELEASE.md 

- CHANGELOG.md
- app/kuma-dp/cmd/run.go
- app/kuma-dp/pkg/dataplane/envoy/envoy.go
- app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go
- app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap_test.go
- deployments/charts/kuma/Chart.yaml
- mk/dev.mk
- pkg/config/app/kuma-dp/config.go
- pkg/config/app/kuma-dp/config_test.go
- pkg/config/app/kuma-dp/testdata/default-config.golden.yaml
- pkg/config/app/kuma-dp/testdata/invalid-config.input.yaml
- pkg/config/app/kuma-dp/testdata/valid-config.input.yaml
- pkg/config/util.go
- pkg/core/runtime/component/component.go
- pkg/plugins/leader/postgres/leader_elector.go
- tools/releases/changelog/go.mod
- tools/releases/changelog/go.sum
- tools/releases/changelog/root.go
> chore(*) release 0.7.2

- dev/examples/universal/dataplanes/example.yaml
Signed-off-by: nikita15p <nikita15p@gmail.com>
Fixed following error in step `kumactl apply -f dev/examples/universal/dataplanes/example.yaml`
```
Error: Could not update a resource (Resource is not valid)
* networking.inbound[0].tags["kuma.io/service"]: tag has to exist
```
Before: service: backend
Now: kuma.io/service: backend
Fix #XXX
> fixed tag in dataplane manifest

- app/kumactl/cmd/install/install_control_plane.go
- pkg/api-server/config_ws_test.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/plugins/runtime/k8s/config.go
- pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/injector.go
- pkg/plugins/runtime/k8s/webhooks/injector/injector_test.go
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.01.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.02.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.03.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.04.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.05.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.06.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.07.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.08.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.09.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.11.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.12.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.13.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.17.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.18.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.19.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.20.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.20.input.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.config.yaml
Backport of
* Exclude injection by labels
* Ready endpoints
* A small change that make Kuma work with the newest K8S
> Backporting fixes

- test/framework/constants.go
- test/framework/k8s_cluster.go
- test/framework/k8s_controlplane.go
- tools/releases/helm.sh
> chore(*) parametrise the Helm release script

- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
Few variables were missing, added them
> fix: config-cp added missing variables

- test/framework/constants.go
- test/framework/k8s_cluster.go
- test/framework/k8s_controlplane.go
- test/framework/kumactl.go
- test/framework/setup.go
- tools/releases/helm.sh
Parametrize helm.sh and enable parametrization for the e2e tests.
> chore(*) parametrise helm.sh

- app/kumactl/cmd/apply/apply.go
- app/kumactl/cmd/apply/apply_test.go
- app/kumactl/cmd/apply/testdata/apply-multiple-resource-different-type.yaml
- app/kumactl/cmd/apply/testdata/apply-multiple-resource-same-type.yaml
Backport of https://github.com/kumahq/kuma/pull/1057
(do not squash when merging to preserve original PR number)
> feat(kumactl) apply multiple resources (#1057)

- .github/dependabot.yml
Add more targets to the dependabot config
> chore(*) add more targets to the dependabot

- .circleci/config.yml
> chore(ci) skip master workflow for release commits (#1106)

- test/dockerfiles/Dockerfile.universal
- tools/e2e/examples/docker-compose/docker-compose.yaml
- tools/e2e/examples/minikube/kuma-routing/kuma-routing.yaml
- tools/releases/distros.sh
- tools/releases/dockerfiles/Dockerfile.kuma-dp
> chore(*) envoy 1.16.0

- .github/workflows/bump_homebrew_formulae.yml
- RELEASE.md
Signed-off-by: Tharun <rajendrantharun@live.com>
Added workflow to automate `homebrew` formula updation.
> chore(cd) added update homebrew formula github workflow

- .mergify.yml
This change has been made by @nickolaev from https://mergify.io config editor.
> chore(*) introduce mergify

- app/kuma-cp/cmd/root.go
- app/kuma-dp/cmd/root.go
- app/kuma-prometheus-sd/cmd/root.go
- test/framework/constants.go
- test/framework/k8s_cluster.go
Unify the rootCmd creation in all our binaries.
Helm e2e customization.
- Not needed
> chore(*) customizable rootCmd in binaries and helm e2e

- test/e2e/externalservices_kubernetes_test.go
- test/e2e/testdata/externalservice-http-server.yaml
- test/e2e/testdata/externalservice-https-server.yaml
Change the container to the real HTTP app since we have problems with ncat on the CI.
> chore(test) change external services test container

- pkg/kds/store/sync.go
KDS logs were missing the type. Also, name and mesh as separate values are easier to read
> chore(kuma-cp) log type of created resources in KDS

- app/kumactl/cmd/generate/generate_dataplane_token_test.go
> feat(kuma-cp) fix integration tests

- UPGRADE.md
The UPGRADE.md notes for Kuma 1.0.x releases.
> docs(*) upgrade 1.0.x

- pkg/xds/cache/cla/testdata/cla.get.1.json
- pkg/xds/envoy/endpoints/endpoints.go
- pkg/xds/envoy/endpoints/endpoints_test.go
We did not sort the EDS config which resulted in unnecessary XDS traffic.
> fix(kuma-cp) generate stable EDS config

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.remote.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
> fix(*) install control plane tests

- pkg/defaults/mesh/mesh.go
On the first start of Kuma, sometimes we saw an error with creating default resources.
> fix(kuma-cp) handle concurrent ensure default resource invocations

- .circleci/config.yml
- tools/releases/helm.sh
Improve Helm Charts releaser
- Not needed
> chore(*) improve helm chart releaser

- pkg/defaults/components.go
Increase default retry for creating default mesh
> chore(kuma-cp) increase default mesh retry timeout

- pkg/api-server/index_endpoints.go
> chore(*) customizable API Index Ws

- pkg/xds/envoy/listeners/http_inbound_route_configurer_test.go
- pkg/xds/envoy/listeners/http_outbound_route_configurer_test.go
- pkg/xds/envoy/routes/default_route_configurer.go
- pkg/xds/envoy/routes/default_route_configurer_test.go
- pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/4-envoy-config.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/05.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/06.envoy.golden.yaml
- pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
Disable Route timeout to ensure longlived and streaming connections
https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#route-timeouts
This shall be replaced by a proper timeout management resource.
> chore(*) disable timeout on route level

- pkg/core/resources/apis/mesh/meta_validator.go
- pkg/plugins/runtime/k8s/webhooks/owner_reference_mutator.go
- pkg/plugins/runtime/k8s/webhooks/owner_reference_mutator_test.go
- pkg/plugins/runtime/k8s/webhooks/validation.go
- pkg/plugins/runtime/k8s/webhooks/validation_test.go
Validate that mesh is not empty on K8S.
Fix #683
> fix(kuma-cp) validate empty mesh on Kubernetes

- OWNERS.md
Add our new maintainer to OWNERS.md
> chore(*) add Bart Smykla to maintainers

- pkg/insights/resyncer_test.go
Data race: https://app.circleci.com/pipelines/github/kumahq/kuma/5706/workflows/208aafab-b005-451c-917c-8bc058c39306/jobs/71674
> fix(kuma-cp) fix data race in tests

- app/kuma-dp/cmd/run.go
- app/kuma-dp/pkg/dataplane/envoy/envoy.go
- go.sum
Make `kuma-dp` quit once Envoy exits.
> chore(*) quit kuma-dp when envoy exits

- .circleci/config.yml
- app/kuma-dp/cmd/context.go
- app/kuma-dp/cmd/root.go
- app/kuma-dp/cmd/root_test.go
- app/kuma-dp/cmd/run.go
- app/kuma-dp/cmd/run_test.go
Expose `RootContext` for users to be able to extend Kuma DP.
> chore(kuma-dp) extensible context

- docs/proposals/timeouts.md
Proposal for the new Timeout policy
> docs(kuma-cp) timeouts proposal

- pkg/xds/bootstrap/generator_test.go
- pkg/xds/bootstrap/template_v3.go
- pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml
- pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config-minimal-request.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml
- test/framework/universal_cluster.go
* Added V3 E2E tests on Universal (take into account `API_VERSION` env var)
* Fixed bootstrap config on V3 (HDS)
* Goldenized bootstrap tests
> fix(ci) test V3 E2E on Universal

- docs/proposals/dns-naming-compliance.md
A proposal for generating DNS compliant names.
> doc(*) compliant DNS names

- go.sum
- pkg/core/runtime/reports/reports.go
Report the number of zones.
- Internal
> chore(*) report number of zones

- .circleci/config.yml
- test/e2e/deploy/deploy_suite_test.go
- test/e2e/externalservices/externalservices_suite_test.go
- test/e2e/healthcheck/e2e_suite_test.go
- test/e2e/helm/helm_suite_test.go
- test/e2e/tracing/tracing_suite_test.go
Try again to parallelize Circle CI.
> test(*) improve e2e split in Circle CI

- OWNERS.md
Adding Charly Molter as a maintainer. Welcome!
> chore(*) add Charly Molter to maintainers

- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
The values have been updated to show available options, rather than what gets translated to postgres.
Reference /pkg/config/plugins/resources/postgres/config.go:57
> Fix Postgres TLS modes in kuma-cp.defaults.yaml

- tools/releases/templates/README
Updating the README template for our distributions.
> docs: updating release readme template

- pkg/api-server/versions_ws.go
Expose versions variable so endpoint can be customized.
> chore(kuma-cp) expose versions endpoint to extension

- test/dockerfiles/Dockerfile.universal
- tools/releases/distros.sh
- tools/releases/dockerfiles/Dockerfile.kuma-dp
> chore(*) envoy 1.17.1

- pkg/kds/global/components.go
- pkg/kds/global/components_test.go
- pkg/kds/remote/components.go
- pkg/kds/remote/components_test.go
- Add Timeout to KDS synchronization
- Add unit test
> fix(kuma-cp) KDS add Timeout to sync

- docs/proposals/extend_circuit-breaker.md
Proposal to extend CircuitBreaker policy
> docs(kuma-cp) proposal to extend CircuitBreaker

- pkg/dns/server.go
- pkg/dns/server_test.go
Have a better message when Kuma DNS can not bind to the port.
> chore(*) improve the DNS server bind message

- pkg/core/resources/manager/customizable_manager.go
- pkg/core/runtime/builder.go
- pkg/events/eventbus.go
- pkg/events/interfaces.go
- pkg/insights/resyncer.go
- pkg/kds/context/context.go
- pkg/kds/remote/components.go
- pkg/plugins/bootstrap/k8s/plugin.go
- pkg/plugins/common/k8s/composite_validator.go
- pkg/plugins/common/k8s/composite_validator_test.go
- pkg/plugins/extensions/k8s/context.go
- pkg/plugins/runtime/k8s/plugin.go
- pkg/plugins/runtime/k8s/webhooks/mesh_validator.go
- pkg/plugins/runtime/k8s/webhooks/validation.go
- pkg/plugins/runtime/k8s/webhooks/zone_validator.go
- pkg/test/runtime/runtime.go
* Add ability to add or override custom resource manager
* Add ability to add custom validators on K8S
* More graceful events stop
> chore(kuma-cp) add extension points to res manager and webhooks

- .circleci/config.yml
This is followup for: https://github.com/kumahq/kuma/commit/f77edec742f2f75c2e3b8be4ec4f65d34def541a which fixes filters for EKS e2e workflow
> fix(*) circleci config filters for eks

- .circleci/config.yml
> test(ci) fix api check by using go1.16

- .circleci/config.yml
- pkg/dns/server_test.go
> test(ci) fix tests in CI

- .circleci/config.yml
Certs expired. Will reenable on monday
> chore(ci) disable integration tests

- .circleci/config.yml
Enable integration tests for `release-1.1`
> chore(ci) enable integration tests

- test/framework/env.go
Getting value of Env var which is used to specify universal image was broken
> fix(e2e) universal image env var fix

- tools/releases/docker.sh
Interpolation fails in some specific environment 🤔
> chore(release) fix docker login script

- tools/releases/helm.sh
> chore(release) parametrize helm url

- tools/releases/docker.sh
- tools/releases/helm.sh
Port CI changes from `release-1.1`
> chore(ci) adjust release scripts

- CHANGELOG.md
- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.remote.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
> chore: prepare 1.1.6

- CHANGELOG.md
- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.remote.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
> chore(*) after release 1.1.6 (#1980)

- .github/PULL_REQUEST_TEMPLATE.md
Add a "testing" section to the PR template so we won't forget and merge PRs without proper tests.
> docs(*) add testing section to PR template

- mk/kind.mk
Signed-off-by: Nikolay Nikolaev <nicknickolaev@gmail.com>
> test(*) bump kind version to 0.11.0

- .circleci/config.yml
Added DOCKER_REGISTRY variable to docker/save make target
* Added DOCKER_REGISTRY variable to docker/save make target
no issue created
not applicable
no tapplicable
> fix(cicd) {A,E}KS cicd workflow fixes (images job)

- NOTICE
- OWNERS.md
Update OWNERS.md with the new member of the team @parkanzky
> docs(*) update OWNERS

- mk/dev.mk
* Use consistent curl options when downloading developer tools
* Install helm into the CI tools directory rather than the default of /usr/local
* Fix the download location for kustomize, which appears to have changed over time.
N/A
N/A
N/A
> chore(deps) improve developer tool downloading

- pkg/config/loader_test.go
> fix: test case fix

- pkg/api-server/config_ws_test.go
This is followup PR fixing test (adjusting expected json) after: https://github.com/kumahq/kuma/commit/f502241a8f6b1f35d9f8fbbf8ab6c6a7df2b8b35
> fix(tests) config_ws test - json fix

- api/mesh/v1alpha1/traffic_route.pb.go
Fixes failing `make check -C api`
> test(*) fix make check -C api

- pkg/defaults/mesh/traffic_route.go
We have shorter syntax to achieve the same behavior as the current TrafficRoute
> feat(kuma-cp) change default traffic route policy

- test/e2e/trafficroute/universal_standalone/traffic_route.go
PR did not have latests origin/master
> tests(*) fix test after removing API V2

- app/kumactl/cmd/install/context/install_control_plane_context.go
- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- deployments/charts/kuma/README.md
- deployments/charts/kuma/values.yaml
- docs/cmd/kumactl/HELP.md
> chore(*) bump cni version to 0.0.9

- test/e2e/kic/kubernetes/kong_ingress.go
- test/e2e/resilience/resilience_multizone_universal.go
- test/e2e/trafficroute/universal_multizone/traffic_route.go
- test/e2e/trafficroute/universal_standalone/traffic_route.go
fix(*) set unified deployOpts in some of the tests
> fix(*) set unified deployOpts in some of the tests

- pkg/xds/envoy/clusters/configurers.go
- pkg/xds/envoy/clusters/v3/http2_configurer.go
- pkg/xds/envoy/clusters/v3/http2_configurer_test.go
- pkg/xds/envoy/clusters/v3/http_configurer.go
- pkg/xds/envoy/clusters/v3/http_configurer_test.go
- pkg/xds/envoy/clusters/v3/timeout_configurer.go
- pkg/xds/envoy/clusters/v3/update_common_http_protocol_options.go
- pkg/xds/envoy/listeners/v3/access_log_configurer.go
- pkg/xds/envoy/listeners/v3/http_access_log_configurer_test.go
- pkg/xds/envoy/listeners/v3/network_access_log_configurer_test.go
- pkg/xds/generator/outbound_proxy_generator.go
- pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/05.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/06.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/cluster-dots.envoy.golden.yaml
- pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
- pkg/xds/generator/testdata/transparent-proxy/03.envoy.golden.yaml
- test/dockerfiles/Dockerfile.universal
- test/e2e/compatibility/dp_compatibility_universal.go
- tools/releases/distros.sh
- tools/releases/dockerfiles/Dockerfile.kuma-dp
Draft for now to check E2E tests. We need to upload binaries for this to merge.
> chore(kuma-dp) upgrade Envoy version to 1.18.3

- CHANGELOG.md
> chore(*) changelog 1.2.0-rc1

- .mergify.yml
- CHANGELOG.md
- README.md
> chore(*) changelog for 1.2.0

- pkg/xds/generator/outbound_proxy_generator.go
> fix(kuma-cp) minor fix typo

- UPGRADE.md
follow up for https://github.com/kumahq/kuma/pull/2165
> chore(*) UPGRADE.md instructions after renaming remote cp to zone cp #2

- pkg/xds/cache/once/cache.go
> fix(kuma-cp) panic intermittently

- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
> fix(kuma-cp) minor fix commented env name

- pkg/plugins/runtime/k8s/metadata/annotations.go
- pkg/plugins/runtime/k8s/webhooks/injector/injector.go
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.01.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.02.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.03.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.04.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.05.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.06.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.07.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.08.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.09.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.11.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.12.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.13.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.14.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.15.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.16.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.17.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.18.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.19.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.21.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.22.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.23.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.24.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.25.golden.yaml
- pkg/transparentproxy/kubernetes/kubernetes.go
- pkg/transparentproxy/kubernetes/kubernetes_suite_test.go
- pkg/transparentproxy/kubernetes/kubernetes_test.go
> chore(kuma-cp) refactor K8s transparent proxy injector

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
> chore(*) Kuma v1.2.1

- CHANGELOG.md
> chore(*) Kuma v1.2.1 changelog

- OWNERS.md
> docs(*) change Nikolay's affiliation

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
Final commit to release Kuma 1.2.2
* [Fix ...]
Fix #XXX
> chore(*) Kuma 1.2.2

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
> chore(*) Kuma 1.2.3

- .mergify.yml
- README.md
Update mergify config and README.md with new `release-1.3` branch
no changelog
no documentation change necessary
> chore(*) Update configs with new release branch

- .circleci/config.yml
fix paths for kuma-release workflow of docker images
no changelog
> fix(ci) kuma-release docker images paths fix

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
fix helm chart version for Kuma 1.3.0
no changelog
no documentation changes
> fix(*) fix helm chart version for Kuma 1.3.0

- deployments/charts/kuma/templates/cp-deployment.yaml
- deployments/charts/kuma/templates/cp-service.yaml
Parametrize label on the deployment
No issues
> chore(kuma-cp) parametrize label on the deployment

- pkg/test/matchers/golden.go
When the Gomega YAML matcher fails to match, it keeps some information
about the error in the match instance. When the golden output matcher
generates a new mather instance on each ginkgo call, that internal state
is dumped and we get less error context.
The result of this fix is that the golden YAML matcher will now emit the
first mismatched key in the error, just like the underlying gomega YAML
matcher does.
N/A
N/A
N/A
> fix(ci) improve golden YAML matcher errors

- deployments/charts/kuma/README.md
> Fix static checks.

- OWNERS.md
Add Mike Beaumont as new maintainer
> docs(OWNERS.md) add Mike Beaumont

- app/kumactl/data/install/k8s/metrics/grafana/kuma-service.json
from
to
* fix(grafana) fix duplicates in dataplane list in Kuma Services dashboard
> fix(grafana) fix duplicates in dataplane list in Kuma Services dashboard

- test/e2e/compatibility/cp_compatibility_kubernetes_multizone.go
The e2e compatibility tests use helm to install an older version of
Kuma using helm. That means that we need to ensure that the Kuma helm
repository is added and updated, even if there are side-effects on the
test execution environment.
N/A
Fix #2853.
N/A
> fix(ci) ensure helm repo is present for compatibility tests

- pkg/api-server/config_ws_test.go
- pkg/config/app/kuma-cp/config.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
Revert changing the telemetry defaults pending discussion with CNCF.
This reverts commit c259c6c63b57410101ffef595cfb7ecf0b9b6d06. Updates #3050.
> Revert "Disable reporting by default (#3070)"

- pkg/plugins/runtime/gateway/cluster_generator.go
- pkg/plugins/runtime/gateway/listener_generator.go
- pkg/plugins/runtime/gateway/route/configurers.go
- pkg/plugins/runtime/gateway/route_configuration_generator.go
- pkg/plugins/runtime/gateway/route_table_generator.go
Update some comments.
N/A
N/A
N/A
> chore(kuma-cp) update some TODO comments

- CHANGELOG.md
> docs(changelog) changelog for 1.4.0 RC2

- CHANGELOG.md
Revert changelog for RC2, merge everything to 1.4.0 RC1 section
> docs(changelog) merge changelog for 1.4.0 RC2 to changelog for 1.4.0 RC1

- pkg/plugins/runtime/k8s/controllers/pod_controller.go
- pkg/plugins/runtime/k8s/controllers/pod_converter.go
- pkg/plugins/runtime/k8s/controllers/pod_converter_test.go
- pkg/plugins/runtime/k8s/util/util.go
- pkg/plugins/runtime/k8s/util/util_test.go
See https://github.com/kumahq/kuma/pull/3109#discussion_r749889921
> chore(pkg/plugins/runtime/k8s) move utility function to util package

- tools/envoy/fetch.sh
Making script to support various OS
> chore(*) add file extension

- tools/envoy/fetch.sh
> Revert "chore(*) add file extension"

- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
Bump helm chart version to 0.8
no changelog
> chore(*) bump helm chart version to 0.8

- .github/workflows/lifecycle.yml
- labels.yml
As agreed on https://docs.google.com/document/d/1k4Y-u54fBoquCv2ROaz_cNu45lmrZsuySxDVqCk2ud8/edit#
this is a bunch of automatic actions to help setting up triage
> chore(ci) add lifecycle actions for triage

- pkg/util/error/error.go
- pkg/xds/envoy/listeners/v3/util_test.go
I may be missing something but I don't think we need this helper.
Closes #2996
> chore(tests) remove unnecessary error helper

- pkg/plugins/runtime/k8s/controllers/inbound_converter.go
- pkg/plugins/runtime/k8s/controllers/pod_converter_test.go
- pkg/plugins/runtime/k8s/util/util.go
- pkg/plugins/runtime/k8s/util/util_test.go
There's probably more that should be moved out of `k8s/controllers` but this is needed for #3109
> feat(k8s/util) move ServiceTag for k8s Service to utils

- .mergify.yml
https://docs.mergify.com/conditions/
> fix(.mergify.yml) don't merge if conflicts label is present

- labels.yml
Add a `anrea/gateway` label.
N/A
N/A
N/A
N/A
> chore(ci) add area/gateway label

- RELEASE.md
Indicate that we should upgrade dependencies and to check UPGRADE.md
> chore(release) update RELEASE.md with upgrade instructions

- .github/PULL_REQUEST_TEMPLATE.md
- UPGRADE.md
This document should be kept up to date rather than updated before a release.
> docs(UPGRADE.md) add note to PR template

- pkg/plugins/runtime/gateway/filter_chain_generator.go
https://github.com/kumahq/kuma/pull/3461 was out of date and didn't have https://github.com/kumahq/kuma/pull/3484
> chore(gateway): fix gateway FilterChain after MatchedPolicies refactor

- CHANGELOG.md
Add changelog for Kuma 1.4.1
* [Fix ...]
Fix #XXX
> chore(*): add changelog for Kuma 1.4.1

- pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
- pkg/plugins/runtime/k8s/controllers/util/controlled.go
Refactor with no behavioral changes
> refactor(gateway): move CreateOrUpdateControlled to package

- test/framework/setup.go
VirtualOutbound E2E was failing on my machine because on the older Kubernetes versions there is no availableReplicas field. I could not find a solution that customizes a serializer so it skips the status.
No reported issues
No docs
> tests(*): skip status when applying K8S object

- pkg/core/resources/apis/mesh/circuit_breaker_validator.go
- pkg/core/resources/apis/mesh/dataplane_validator.go
- pkg/core/resources/apis/mesh/dataplane_validator_test.go
- pkg/core/resources/apis/mesh/external_service_validator.go
- pkg/core/resources/apis/mesh/external_service_validator_test.go
- pkg/core/resources/apis/mesh/fault_injection_validator.go
- pkg/core/resources/apis/mesh/gateway_route_validator.go
- pkg/core/resources/apis/mesh/gateway_validator.go
- pkg/core/resources/apis/mesh/health_check_validator.go
- pkg/core/resources/apis/mesh/proxytemplate_validator.go
- pkg/core/resources/apis/mesh/rate_limit_validator.go
- pkg/core/resources/apis/mesh/retry_validator.go
- pkg/core/resources/apis/mesh/timeout_validator.go
- pkg/core/resources/apis/mesh/traffic_log_validator.go
- pkg/core/resources/apis/mesh/traffic_permission_validator.go
- pkg/core/resources/apis/mesh/traffic_route_validator.go
- pkg/core/resources/apis/mesh/traffic_trace_validator.go
- pkg/core/resources/apis/mesh/validators.go
- pkg/core/resources/apis/mesh/validators_test.go
- pkg/core/resources/apis/mesh/virtual_outbound_validator.go
- pkg/core/resources/apis/mesh/zone_ingress_validator.go
- pkg/core/resources/apis/mesh/zone_ingress_validator_test.go
Spawned from https://github.com/kumahq/kuma/pull/3564
This fixes some validation errors and changes the wording of others.
> refactor(pkg/core): unify tag and selector validation

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
- pkg/plugins/runtime/k8s/plugin.go
- pkg/plugins/runtime/k8s/plugin_gateway.go
- pkg/plugins/runtime/k8s/webhooks/gateway_instance_validator.go
- pkg/plugins/runtime/k8s/webhooks/validation.go
> feat(gateway): validate GatewayInstance resources 

- tools/releases/helm.sh
Just a small improvement for testing
> chore(tools/releases/helm.sh): don't unnecessarily require GH_TOKEN

- pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
A Kubernetes service only has a LoadBalancer status field if it is
of type "LoadBalancer". For other service types, checking the cluster
IP is a reasonable way to tell whether there is an address assigned,
though that is not necessarily the address we want for "NodePort".
N/A
N/A
N/A
> fix(kuma-dp): update GatewayInstance readiness

- app/kuma-dp/cmd/testdata/envoy-mock.sleep.sh
- app/kuma-dp/pkg/dataplane/dnsserver/testdata/binary-mock.exit-0.sh
- app/kuma-dp/pkg/dataplane/envoy/testdata/envoy-mock-windows.exit-0.sh
- app/kuma-dp/pkg/dataplane/envoy/testdata/envoy-mock.exit-0.sh
- app/kuma-dp/pkg/dataplane/envoy/testdata/envoy-mock.with-label.sh
- tools/common.sh
- tools/e2e/examples/docker-compose/kuma-example-installer.sh
- tools/e2e/examples/minikube/kumactl_workflow.sh
- tools/envoy/build_centos.sh
- tools/envoy/build_darwin.sh
- tools/envoy/build_linux.sh
- tools/envoy/fetch.sh
- tools/envoy/fetch_sources.sh
- tools/envoy/publish.sh
- tools/postgres/wait-for-postgres.sh
- tools/releases/distros.sh
- tools/releases/docker.sh
- tools/releases/helm.sh
- tools/releases/make-release-tag.sh
Preparation for checking scripts with shellcheck in CI.
> chore(*): fix shellcheck warnings 

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/templates/cp-rbac.yaml
- pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
- pkg/plugins/runtime/k8s/controllers/util/controlled.go
We leave the Deployment alone since it doesn't depend on the `Gateway`, but I'm not sure this is the expected behavior.
Blocked by #3570
Closes #3597
> fix(gateway): delete service if Gateway unattached

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
> refactor(gateway): change to prefixed autogenerated tag

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_class_controller.go
- pkg/plugins/runtime/k8s/plugin_gateway.go
> feat(gateway): add GatewaysExist finalizer to GatewayClasses

- DEVELOPER.md
- docs/guides/e2e-test-tips.md
These docs were outdated and needed to be refreshed
Fix #2626
Fix #3634
> docs: update and refresh DEVELOPER.md and e2e-test-tips.md

- test/framework/k8s_controlplane.go
Sometime when doing an update to a resource the entity is updated
somewhere else and the apply fails (example meshes get added an annotation).
We now retry on conflicts to make sure we progress
> ci(e2e): retry update to resource in case of conflicts

- test/framework/k8s_controlplane.go
In the case of autoscaling we run the tests as soon as 1 pod is available.
In practice we're starting 3 pods.
This patch ensures we're selecting a pod that's fully started when tunneling.
This should make the helm autoscale test more stable
> ci(e2e): make sure the pod selected for tunnel is available

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
Not all load balancers set IP addresses.
> feat(gateway): support Service addresses with hostname in GatewayInstances

- pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy_test.go
Also tweaked tests to test this path.
From #3672
> fix(gateway): fix NPE in policy code

- pkg/plugins/runtime/k8s/controllers/gatewayapi/common.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy.go
This PR covers the `ResolvedRefs` (i.e. checking certificate references for `ReferencePolicy`) and `Ready` conditions.
Part of https://github.com/kumahq/kuma/issues/3617
> feat(gateway): initial support for GatewayStatus.Listeners

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_class_controller.go
Log on error, fix variable names and error messages.
> refactor(gateway): cleanup GatewayClass controller

- pkg/plugins/runtime/k8s/controllers/gatewayapi/common.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
This step was missing, the mesh needs to be set. It may be possible to avoid setting the mesh on `HTTPRoute` objects but instead creating however many `GatewayRoute` objects are needed based on how many different meshes are referenced in the `ParentRef`s.
> fix(gateway): set mesh of internal objects owned by Gateway API objects

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/templates/cp-rbac.yaml
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_class_controller.go
We need to explicitly patch the subresource + add RBAC.
#3701
> fix(gateway): use subresource patch for GatewayClass status

- pkg/plugins/runtime/k8s/controllers/gatewayapi/common/common.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/common/reconcile.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_class_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_status.go
No observable changes, just moving code.
> refactor(gateway): move gatewayapi/common.go to package

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
The `Gateway` status depends on the attached `HTTPRoute`s, so we need to recalculate if they change.
Part of #3617, similar to #3699
> feat(gateway): reconcile Gateways when a Route changes

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
This PR adds updating `Gateway` statuses with information about attached routes.
Part of #3617
~Blocked by #3709~
> feat(gateway): complete Gateway Listener status with route info

- app/kumactl/pkg/tokens/client_test.go
- app/kumactl/pkg/tokens/zone_client_test.go
- app/kumactl/pkg/tokens/zoneingress_client_test.go
- pkg/api-server/config_ws_test.go
- pkg/api-server/server.go
- pkg/config/access/config.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/core/bootstrap/bootstrap.go
- pkg/core/runtime/runtime.go
- pkg/tokens/builtin/access/access.go
- pkg/tokens/builtin/access/noop.go
- pkg/tokens/builtin/access/static.go
- pkg/tokens/builtin/server/webservice.go
- pkg/tokens/builtin/server/webservice_test.go
- pkg/tokens/builtin/zone/access/access.go
- pkg/tokens/builtin/zone/access/noop.go
- pkg/tokens/builtin/zone/access/static.go
Introduce Access interface for generating Zone Token.
> feat(kuma-cp): zone token access

- .circleci/config.yml
- mk/check.mk
- mk/dev.mk
- tools/envoy/fetch.sh
- tools/releases/distros.sh
- tools/releases/docker.sh
- tools/releases/version.sh
Also add install targets and fix lint errors.
Closes #3116
> ci: check shell scripts with shellcheck

- test/e2e/gateway/gateway_kubernetes.go
Implement missing test on Kubernetes
Fix #3510
> test(*): https and external service e2e test for gateway

- test/e2e/gateway/gateway_kubernetes.go
Fix hardcoded namespace.
No issues
No docs
> test(*): fix hardcoded namespace

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
The resources weren't being validated.
Closes #3844
> fix(gateway): make sure resources are validated

- .mergify.yml
> ci: update mergifyio to backport to release-1.5

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
- test/e2e/compatibility/cp_compatibility_kubernetes_multizone.go
- test/framework/config.go
> fix(helm): update helm chart version

- mk/k3d.mk
I'm using our k3d make targets to spawn more than 2 k3d/kuma
clusters, which was broken with current `PORT_PREFIX` variable
assignment.
This will generate `PORT_PREFIX` from provided `KIND_CLUSTER_NAME`
variable
n/a
n/a
n/a
> chore(*): change PORT_PREFIX generation for k3d

- pkg/plugins/runtime/gateway/builder.go
- pkg/plugins/runtime/gateway/cluster_generator.go
- pkg/plugins/runtime/gateway/connection_policy_generator.go
- pkg/plugins/runtime/gateway/filter_chain_generator.go
- pkg/plugins/runtime/gateway/gateway_route_generator.go
- pkg/plugins/runtime/gateway/generator.go
- pkg/plugins/runtime/gateway/listener_generator.go
- pkg/plugins/runtime/gateway/plugin.go
- pkg/plugins/runtime/gateway/route_configuration_generator.go
- pkg/plugins/runtime/gateway/route_table_generator.go
Previously there was a "hold and mutate everything object", making the logic and flow of data hard to follow.
> refactor(gateway): avoid mutation in generators

- UPGRADE.md
> chore(upgrade.md): update to refer 1.5.0 as latest release

- pkg/api-server/testdata/versions.json
- pkg/version/compatibility.go
> fix(*): compat matrix test

- .golangci.yml
- app/kuma-dp/pkg/dataplane/accesslogs/v3/factories.go
- app/kumactl/cmd/completion/completion.go
- app/kumactl/cmd/root.go
- pkg/api-server/inspect_endpoints_test.go
- pkg/core/bootstrap/bootstrap.go
- pkg/core/dns/lookup/cache_test.go
- pkg/envoy/accesslog/v3/format_parser.go
- pkg/plugins/resources/memory/store.go
- pkg/plugins/runtime/gateway/connection_policy_generator.go
- pkg/plugins/runtime/gateway/filter_chain_generator.go
- pkg/plugins/runtime/gateway/gateway_route_generator.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_status.go
- pkg/plugins/runtime/k8s/plugin.go
- pkg/plugins/runtime/k8s/webhooks/validation.go
- pkg/test/runtime/runtime.go
- pkg/transparentproxy/firewalld/firewalld.go
- pkg/xds/auth/universal/authenticator.go
- pkg/xds/envoy/tls/v3/tls.go
- pkg/xds/generator/direct_access_proxy_generator.go
- pkg/xds/generator/inbound_proxy_generator.go
- pkg/xds/generator/outbound_proxy_generator.go
- pkg/xds/sync/ingress_proxy_builder.go
- tools/releases/changelog/generator.go
- tools/releases/changelog/root.go
[unparam](https://github.com/mvdan/unparam) checks for unused function parameters and results.
> ci(golangci-lint): enable unparam linter

- pkg/plugins/runtime/k8s/controllers/pod_status_controller.go
> refactor(controllers): use predicates in PodStatusReconciler

- test/e2e/ratelimit/e2e_suite_test.go
- test/e2e/ratelimit/ratelimit_universal.go
Rework the check for rate limiting and remove flakiness
Closes #3874
> test(e2e/ratelimit): fix rate limit check

- pkg/core/permissions/matcher.go
- pkg/core/permissions/matcher_test.go
- pkg/plugins/runtime/gateway/cluster_generator.go
- pkg/plugins/runtime/gateway/generator.go
- pkg/plugins/runtime/gateway/match/external.go
- pkg/plugins/runtime/gateway/plugin.go
- pkg/xds/generator/outbound_proxy_generator.go
- pkg/xds/sync/dataplane_proxy_builder.go
Consolidate logic here `Dataplane`s and `Gateway`s.
There are potentially performance implications here.
~Blocked by #3834~
Closes #3024
> fix(gateway): let Dataplanes take precedence over ExternalServices

- pkg/xds/bootstrap/handler.go
- pkg/xds/bootstrap/server_test.go
Closes https://github.com/kumahq/kuma/issues/3941
> fix(kuma-cp): fix bootstrap with implicit port

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
Part of the Gateway API spec (#3617):
https://github.com/kubernetes-sigs/gateway-api/blob/bdfbb8d9a43c0ef3b9cd7d9239dd95fe9d101f1d/apis/v1alpha2/gateway_types.go#L634-L676
> feat(gatewayapi): check for Gateway listener conflicts 

- pkg/plugins/runtime/gateway/gateway_route_generator_test.go
- pkg/plugins/runtime/gateway/generator.go
- pkg/plugins/runtime/gateway/testdata/http/22-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/http/23-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/http/24-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/22-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/23-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/24-gateway-route.yaml
Added more tests with wildcards.
Check the third commit for the effects of this change.
Closes #3959
> feat(gateway): support partial wildcards in GatewayRoute http hostnames

- go.mod
- pkg/plugins/runtime/gateway/cluster_generator.go
- pkg/plugins/runtime/gateway/filter_chain_generator.go
- pkg/plugins/runtime/gateway/generator.go
- pkg/plugins/runtime/gateway/listener_generator.go
- pkg/plugins/runtime/gateway/plugin.go
> refactor(gateway): cleanup datasource.Loader usage

- test/e2e/ratelimit/ratelimit_universal.go
The current Rate Limit E2E tests are really flaky. After looking at them more, I believe there is no reasonable stable way to test them, because of the time that we don't control and the moment of filling buckets by Envoy.
I simplified the tests so that we check whether we can hit a specific rate limit. The specific rate limit is marked by status code configured in RateLimit policy.
No docs.
> test(*): simplify rate limiting tests

- docs/generated/cmd/kuma-cp/kuma-cp.md
> fix(docs): add missing file in docs generation

- pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
MeshGatewayInstance was looping reconciliation forever.
We were updating Service with new ServicePort objects, but the existing ones had NodePort defined (even if the service is of a type LoadBalancer). 
Fix is to reuse existing ServicePorts if there any to preserve NodePort.
No issues reported, noticed during development.
> fix(kuma-cp): gateway instance service reconciliation loops forever

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion_test.go
Now it tests the reason in the conditions for non valid listeners.
> test(gatewayapi): refactor upstream object validation tests

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
And bump it to 1.6.0 for `master` in advance.
> feat(helm): set version to track appVersion

- pkg/api-server/inspect_endpoints.go
- pkg/api-server/inspect_endpoints_test.go
- pkg/api-server/testdata/inspect_gateway_dataplanes.json
- pkg/api-server/types/inspect.go
Lists dataplanes matched by this MeshGateway
Part of #3720
> feat(api-server): add inspect gateway dataplanes endpoint 

- mk/dev.mk
it's used in different scripts
> chore(dev/tools): add yq

- app/kumactl/cmd/completion/testdata/bash.golden
- app/kumactl/cmd/inspect/inspect.go
- app/kumactl/cmd/inspect/inspect_meshgateway.go
- app/kumactl/cmd/inspect/inspect_meshgateway_test.go
- app/kumactl/cmd/inspect/testdata/inspect-meshgateway-dataplanes.server-response.json
- app/kumactl/cmd/inspect/testdata/inspect-meshgateway.golden.txt
- app/kumactl/pkg/cmd/root_context.go
- app/kumactl/pkg/resources/meshgateway_inspect_client.go
- docs/generated/cmd/kumactl/kumactl_inspect.md
- docs/generated/cmd/kumactl/kumactl_inspect_meshgateway.md
List Dataplanes with `kumactl inspect meshgateway`
~Blocked on #4088~
Closes #3720
> feat(kumactl): add inspect meshgateway

- UPGRADE.md
Changed in https://github.com/kumahq/kuma/pull/4097, accidentally merged that PR early
> docs(UPGRADE.md): add note about names of MeshGatewayInstance-generated objects

- test/e2e/gateway/gatewayapi/gateway_api.go
Added E2E test of Gateway API + external service
In progress
> test(e2e): gateway API with external service

- pkg/api-server/inspect_endpoints.go
> refactor(api-server): use request Context

- deployments/charts/kuma/templates/_helpers.tpl
It's not possible to override the "expected" version of the chart from a parent chart because [we can't override `.Chart.AppVersion` from the parent chart](https://github.com/helm/community/pull/242).
We can however override *templates* because they are global. So we can override the default app version and the default registry from a parent chart.
> feat(helm): add templates to modify expected registry and compatible version

- .mergify.yml
- CHANGELOG.md
- README.md
- RELEASE.md
- tools/releases/changelog/graphql.go
- tools/releases/changelog/root.go
* Update Release.md to make it more current
* Add Changelog for 1.6.0 and 1.5.1
* Add tool to help creation of a nice changelog
> chore(changelog): add changelog tool and update docs

- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
- deployments/charts/kuma/templates/egress-deployment.yaml
- deployments/charts/kuma/templates/egress-service.yaml
- deployments/charts/kuma/templates/ingress-deployment.yaml
- deployments/charts/kuma/templates/ingress-service.yaml
> fix(helm): fix other template prefix in ingress/egress

- test/e2e/externalservices/localityawarelb_multizone/locality_multizone_hybrid.go
> ci(e2e): fix e2e externalservice tests

- CHANGELOG.md
> ci(CHANGELOG.md): update changelog with latest changes

- UPGRADE.md
> docs(UPGRADE.md): update next release

- tools/releases/helm.sh
Unpublished versions of a chart may depend on unpublished versions of other charts, this allows those other charts to be embedded without overwriting them with the version in `.dependencies`.
> build(helm): when using dev version, use embedded charts, not fetched versions

- CHANGELOG.md
> docs(changelog): update changelog with latest patches

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
Important now because of #4157 but generally more correct.
> feat(gateway): only reconcile Gateway when GatewayClass is Ready

- pkg/plugins/runtime/gateway/filter_chain_generator.go
- pkg/plugins/runtime/gateway/testdata/05-gateway-listener.yaml
- pkg/plugins/runtime/gateway/testdata/https/03-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/04-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/05-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/06-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/07-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/08-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/09-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/10-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/11-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/12-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/13-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/14-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/15-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/16-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/17-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/18-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/19-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/20-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/21-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/25-gateway-route.yaml
- pkg/plugins/runtime/gateway/testdata/https/26-gateway-route.yaml
Signed-off-by: Will Betts <will.betts@equalexperts.com>
Fix #4198
> fix(kuma-cp): don't match on ALPN in gateway (#4198)

- docs/proposals/cross-mesh-ux.md
This is a proposal for a UX to allow for cross-mesh traffic.
[Rendered](https://github.com/michaelbeaumont/kuma/blob/docs/cross-mesh_proposal/docs/proposals/cross-mesh-ux.md)
See also #3323
> docs(proposal): cross-mesh communication UX

- test/e2e_env/kubernetes/graceful/graceful.go
Added test that checks if we don't miss any request when scaling up and down a gateway.
Fix #3310
No extra docs.
> test(e2e): graceful scaling of gateway

- docs/madr/README.md
- docs/madr/decisions/000-template.md
- docs/madr/decisions/001-adopt-madr.md
- docs/proposals/README.md
> docs: add MADR process

- .circleci/config.yml
`circleci-agent step halt` which avoids the complex "unless" that was error prone.
> ci: improve premature stop of e2e tests

- .circleci/config.yml
> ci: fix substring matching in circleci

- tools/releases/distros.sh
Introduced map of arch for a specific build because we don't have centos arm build
* [added map of envoy distribution to build arch]
Fix #XXX
> chore(*): introduced map of arch for a specific build

- app/kumactl/cmd/config/config_control_planes_add_test.go
- app/kumactl/pkg/config/validate.go
Previously the error was cryptic and complex for folks to troubleshoot
Fix #4347
> fix(kumactl): make error more explicit when CLI and CP product differ

- test/e2e_env/kubernetes/gateway/cross-mesh.go
- test/e2e_env/kubernetes/gateway/utils.go
> test(e2e): fix cross-mesh gateway test on ipv6

- test/e2e/gateway/gateway_kubernetes.go
- test/e2e/gateway/gateway_universal.go
- test/e2e_env/universal/gateway/cross-mesh.go
- test/e2e_env/universal/gateway/utils.go
- test/e2e_env/universal/universal_suite_test.go
- test/framework/client/collect.go
- test/framework/setup.go
Same as the k8s test for now, I'll add transparent proxy tests in another PR.
> test(e2e): add universal cross-mesh tests

- test/e2e_env/universal/gateway/cross-mesh.go
- test/e2e_env/universal/gateway/utils.go
- test/framework/setup.go
> test(e2e): add cross-mesh test without transparent proxy

- test/e2e_env/kubernetes/gateway/cross-mesh.go
- test/e2e_env/kubernetes/gateway/utils.go
- test/e2e_env/multizone/gateway/cross-mesh.go
- test/e2e_env/multizone/multizone_suite_test.go
- test/e2e_env/universal/gateway/cross-mesh.go
- test/e2e_env/universal/gateway/utils.go
NOTE: this only tests intrazone cross-mesh
> test(e2e/multizone): add intrazone cross-mesh test

- test/e2e_env/kubernetes/gateway/cross-mesh.go
- test/e2e_env/kubernetes/gateway/utils.go
- test/e2e_env/multizone/gateway/cross-mesh.go
> test(e2e/multizone): add test that cross-mesh doesn't work crosszone yet

- mk/envoy.mk
- tools/envoy/fetch.sh
- tools/releases/distros.sh
- tools/releases/docker.sh
> chore(release-1.5): upgrade Envoy to 1.21.3

- docs/madr/decisions/004-metric-filter.md
MADR about filter metrics.
xref #1755
> docs(madr): filter metrics

- .circleci/config.yml
> ci: fix caching of go

- pkg/plugins/runtime/gateway/gateway_route_generator_test.go
- pkg/plugins/runtime/gateway/testdata/http/cross-mesh-gateway.yaml
- pkg/plugins/runtime/gateway/testdata/https/cross-mesh-gateway.yaml
> test(gateway): cross-mesh config generation

- pkg/plugins/runtime/gateway/testdata/http/cross-mesh-gateway.yaml
- pkg/plugins/runtime/gateway/testdata/https/cross-mesh-gateway.yaml
> test(gateway): fix cross mesh tests after x-kuma-tags merge

- api/mesh/v1alpha1/dataplane_helpers.go
- pkg/core/xds/types.go
- pkg/dns/vips_allocator.go
- pkg/plugins/runtime/k8s/metadata/labels.go
- pkg/plugins/runtime/k8s/webhooks/secret_validator.go
- pkg/plugins/secrets/k8s/store.go
- pkg/xds/context/mesh_context_builder.go
- pkg/xds/context/resources.go
- pkg/xds/generator/ingress_generator.go
- pkg/xds/generator/ingress_generator_test.go
- pkg/xds/generator/outbound_proxy_generator.go
- pkg/xds/generator/testdata/ingress/meshgateway.envoy.golden.yaml
- pkg/xds/ingress/dataplane.go
- pkg/xds/ingress/dataplane_test.go
- pkg/xds/ingress/outbound.go
- pkg/xds/ingress/outbound_test.go
- pkg/xds/sync/ingress_proxy_builder.go
- pkg/xds/sync/proxy_builder_test.go
- pkg/xds/sync/testdata/input/default_resources.yaml
- pkg/xds/topology/outbound.go
- test/e2e_env/multizone/gateway/cross-mesh.go
- test/e2e_env/multizone/healthcheck/healthcheck.go
- test/e2e_env/multizone/multizone_suite_test.go
- test/e2e_env/multizone/trafficroute/trafficroute.go
- Uses `kuma.io/mesh` to mark an available service as being available from other meshes
~Blocked on https://github.com/kumahq/kuma/pull/4439~
> feat(gateway): multi-zone cross-mesh MeshGateway

- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
A branch got merged without updating this test
> chore(ci): add missing test result

- pkg/plugins/runtime/gateway/cluster_generator.go
Closes https://github.com/kumahq/kuma/issues/4484
> fix(gateway): npe without any timeout

- go.mod
- go.sum
- pkg/plugins/resources/k8s/native/api/v1alpha1/container_patch.go
- pkg/plugins/runtime/k8s/webhooks/injector/injector.go
- pkg/plugins/runtime/k8s/webhooks/injector/injector_test.go
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.30.golden.yaml
This updates to json-patch/v5.
@parkanzky that should be ok, right?
Closes https://github.com/kumahq/kuma/issues/4525
> feat(containerpatch): add operations now create non-existent path elements

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
> chore(helm): update to 1.7.1

- .github/workflows/helm-release.yaml
- tools/releases/helm.sh
Otherwise we still need to do the Chart.yaml appVersion bump manually.
> fix(.github): always run Helm version update 

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.cni-experimental-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- deployments/charts/kuma/templates/cp-rbac.yaml
This resource was renamed, part of #4597
> fix(gatewayapi): rbac permissions for ReferenceGrant

- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
> fix(gatewayapi): improve HTTPRoute statuses with unresolved BackendRefs

- go.mod
- go.sum
Fixes a couple dependabot alerts
> build(go.mod): update containerd to v1.5.13

- app/kuma-dp/pkg/dataplane/metrics/server.go
Instead of setting a timeout, we rely on context. When the client interrupts the request we are going to cancel all pending requests.
* [Removed timeout]
* [Added context propagation]
Fix #4608
> fix(*): propagate context for metrics aggregate

- mk/build.mk
Signed-off-by: Ashish Amarnath <ashish.amarnath@gmail.com>
* [Fix ...]
Fix #XXX
> (chore) fix makefile comments

- .github/PULL_REQUEST_TEMPLATE.md
Remove standard body and replace by a checklist as an array
> fix(docs): update PR template to make it simpler

- .github/PULL_REQUEST_TEMPLATE.md
> chore(.github): put PR template instructions in comments

- .mergify.yml
- CONTRIBUTING.md
> docs: update backport policy to use comments instead of label

- docs/madr/decisions/005-policy-matching.md
> docs(MADR): policy matching, replace 'conf' with 'default'

- pkg/xds/envoy/listeners/v3/dns_configurer.go
- pkg/xds/envoy/listeners/v3/dns_configurer_test.go
- pkg/xds/generator/testdata/dns/1-envoy-config.golden.yaml
- pkg/xds/generator/testdata/dns/3-envoy-config.golden.yaml
See [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/data/dns/v3/dns_table.proto#envoy-v3-api-field-data-dns-v3-dnstable-known-suffixes)
> chore(xds): don't set deprecated known_suffixes

- .github/workflows/update-changelog.yaml
> fix(ci): correct bad path in update-changelog action

- .github/workflows/update-changelog.yaml
> fix(.github): fix PR title in update-changelog action

- pkg/xds/topology/dataplanes_test.go
Missing from https://github.com/kumahq/kuma/pull/4718
> test(xds/topology): fix expect call

- test/e2e/gateway/gateway_kubernetes.go
- test/e2e_env/kubernetes/gateway/mtls.go
- test/e2e_env/kubernetes/kubernetes_suite_test.go
> test(e2e): migrate mtls gateway

- docs/generated/resources/other_mesh.md
- docs/generated/resources/policy_circuit-breaker.md
- docs/generated/resources/policy_external-service.md
- docs/generated/resources/policy_fault-injection.md
- docs/generated/resources/policy_meshgateway.md
- docs/generated/resources/policy_proxy-template.md
- docs/generated/resources/policy_rate-limit.md
- docs/generated/resources/policy_traffic-route.md
- docs/generated/resources/proxy_dataplane.md
- docs/generated/resources/proxy_zoneingress.md
- go.mod
- go.sum
Blocked on https://github.com/kumahq/protoc-gen-kumadoc/pull/12
> build(docs): update protoc-gen-kumadoc to generate correct field names

- api/mesh/v1alpha1/gateway_helpers.go
- go.mod
- pkg/core/resources/apis/mesh/gateway_validator.go
- pkg/core/resources/apis/mesh/gateway_validator_test.go
- pkg/core/resources/apis/mesh/mesh_suit_test.go
- pkg/plugins/runtime/gateway/gateway_route_generator.go
- pkg/plugins/runtime/gateway/generator.go
- pkg/plugins/runtime/gateway/listener_generator_test.go
Previously we just threw errors during generation which is not ideal.
Blocking #4755 
> feat(gateway): validate listeners for collapsibility

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
Found this migrating the e2e tests!
> fix(gatewayapi): create MeshGatewayInstance in same Mesh as Gateway

- app/kuma-prometheus-sd/pkg/discovery/xds/v1/converter.go
- pkg/core/logs/matcher.go
- pkg/core/ratelimits/matcher.go
- pkg/core/resources/apis/mesh/validators.go
- pkg/core/resources/model/resource.go
- pkg/envoy/accesslog/v3/format_parser.go
- pkg/envoy/admin/tls/pki.go
- pkg/plugins/runtime/gateway/generator.go
- pkg/plugins/runtime/gateway/match/hostnames.go
- pkg/transparentproxy/istio/tools/istio-iptables/pkg/cmd/run.go
- pkg/xds/envoy/clusters/configurers.go
- pkg/xds/hooks/resource_set.go
- pkg/xds/server/v3/resource_warming_forcer.go
- pkg/xds/topology/outbound.go
Just the result of `make format`/`make check` command
> chore: adjust format after running make format cmd

- test/e2e/zoneegress/externalservices/zoneegress_externalservices_hybrid.go
I don't want to expose this setting in CP yet, so proxy template to the rescue.
> test(e2e): disable warm on init for zone egress hybrid test

- test/framework/k8s_cluster.go
> fix(cni): retry loading images

- tools/releases/helm.sh
> chore: fix gh action script

- .github/workflows/helm-release.yaml
- tools/releases/helm.sh
> fix(tools): support both GitHub app tokens and PATs

- README.md
> docs: update README with 1.8 badge

- UPGRADE.md
> chore: upgrade md changes

- deployments/charts/kuma/Chart.yaml
Chart update, none of these are related:
> chore(helm): update helm chart version

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.cni-experimental-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- deployments/charts/kuma/README.md
> chore(helm): fix chart README

- test/e2e_env/multizone/sync/sync.go
It's flaky on CI. Debugging...
> test(e2e): temporary disable sync update test

- test/e2e/deploy/kuma_deploy_universal.go
Basic connectivity is tested multiple times in other places. No need to waste time
> test(e2e): remove duplicate e2e test

- .circleci/config.yml
> test(e2e): filter arm test on legacy tests

- test/e2e/README.md
- test/e2e_env/README.md
Adds a bit of doc about e2e tests, so first-time contributors are less confused.
> test(e2e): readme

- pkg/xds/auth/k8s/authenticator.go
This makes it clear that they're authenticated the same way when reading the implementation.
> refactor(xds/auth): remove duplicate code in k8s Authenticator

- docs/guides/new-policies.md
Just a docs change.  [ci skip]
Signed-off-by: Krzysztof Słonka <slonka@users.noreply.github.com>
> docs: update new-policies.md [ci skip]

- pkg/api-server/inspect_endpoints.go
- pkg/core/bootstrap/bootstrap.go
- pkg/core/plugins/registry.go
- pkg/core/xds/matched_policies.go
- pkg/plugins/bootstrap/k8s/plugin.go
- pkg/plugins/bootstrap/universal/plugin.go
- pkg/plugins/runtime/gateway/suite_test.go
- pkg/plugins/runtime/k8s/plugin.go
- pkg/plugins/runtime/universal/plugin.go
- pkg/xds/sync/dataplane_proxy_builder.go
> chore(plugins): remove some unecessary interfaces and methods

- app/kumactl/cmd/install/context/install_control_plane_context.go
- app/kumactl/cmd/install/install_control_plane.go
- app/kumactl/cmd/install/install_control_plane_test.go
- app/kumactl/cmd/install/render_helm_files.go
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- deployments/charts/kuma/templates/gateway-class.yaml
> feat: install `kuma` `GatewayClass` if gateway API CRDs present

- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- pkg/api-server/testdata/policies_list.golden.json
There was a merge with golden files update that was from a branch that was not up to date.
> fix(kumactl): update golden files

- api/mesh/v1alpha1/gateway_route.pb.go
- api/mesh/v1alpha1/gateway_route.proto
- docs/generated/resources/policy_meshgatewayroute.md
> docs(gateway): explain the semantics of a PREFIX match

- docs/madr/decisions/005-policy-matching.md
> fix(MADR): typo with 'spec'

- pkg/core/resources/manager/customizable_manager.go
Adds the ability to wrap customizable resource manager with another manager.
> chore(kuma-cp): resource manager wrapper

- pkg/plugins/runtime/gateway/gateway_route_generator_test.go
- pkg/plugins/runtime/gateway/route/configurers.go
- pkg/plugins/runtime/gateway/route_table_generator.go
- pkg/plugins/runtime/gateway/testdata/http/retry-policy.yaml
- pkg/plugins/runtime/gateway/testdata/https/retry-policy.yaml
- pkg/xds/envoy/listeners/v3/retry_configurer.go
> fix(gateway): add support for retryOn

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
> chore(*): update helm version

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.cni-experimental-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
> Revert "chore(*): update helm version"

- test/e2e_env/universal/meshaccesslog/meshaccesslog.go
This tests the same functionality correctly but the fact that the previous test was flaky still points to an issue.
> test(e2e): remove MeshAccessLog tests flakiness

- .github/workflows/pr-comments.yaml
> ci(.github): fix pr-comments action

- pkg/api-server/inspect_endpoints_test.go
> test: add missing target ref to access log

- test/e2e_env/kubernetes/gateway/cross-mesh.go
- test/e2e_env/kubernetes/kubernetes_suite_test.go
> test(e2e): skip gateway API on ARM

- app/kumactl/cmd/apply/apply_test.go
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
- app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
- deployments/charts/kuma/crds/kuma.io_meshtrafficpermissions.yaml
- pkg/core/resources/model/rest/list_test.go
- pkg/core/xds/rules_test.go
- pkg/core/xds/testdata/rules/03.golden.yaml
- pkg/core/xds/testdata/rules/03.policy.yaml
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/meshtrafficpermission.pb.go
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/meshtrafficpermission.proto
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/schema.yaml
- pkg/plugins/policies/meshtrafficpermission/k8s/crd/kuma.io_meshtrafficpermissions.yaml
- pkg/plugins/policies/validation/schema_test.go
- test/e2e_env/kubernetes/meshtrafficpermission/api.go
This action was deleted only from enum, but not from the actual proto.
> chore: remove DENY_WITH_SHADOW_ALLOW

- UPGRADE.md
> docs(UPGRADE.md): add note about `MeshGatewayRoute` validation

- tools/releases/version.sh
> feat(build): ignore index changes in CI

- pkg/api-server/dataplane_overview_endpoints.go
- pkg/api-server/dataplane_overview_endpoints_test.go
- pkg/api-server/filtering.go
- pkg/core/resources/store/options.go
- pkg/plugins/resources/k8s/store.go
- pkg/plugins/resources/memory/store.go
- pkg/plugins/resources/postgres/store.go
- pkg/test/store/store_test_template.go
Add search with the `?name` parameter which will do prefix based filtering
Fix #4663 
> feat(api-server): add name search to dataplane overview

- docs/madr/decisions/012-health-check-policy.md
> docs(MADR): mesh health check madr

- app/kuma-ui/pkg/resources/data/index.html
- pkg/version/version_test.go
> fix(gui): correct index.html with templates

- tools/releases/docker.sh
> feat(build): fix prune in docker sh

- tools/releases/helm.sh
This wasn't updated properly so the badge wasn't right.
> fix(helm): update README.md on release

- tools/releases/helm.sh
This reverts commit cd2b6844cde2f867ed0b8fb96fc0f191ccde9e91.
> Revert "fix(helm): update README.md on release (#5421)"

- pkg/core/resources/apis/mesh/external_service_helpers.go
- pkg/core/resources/apis/mesh/mesh_helpers.go
> feat(kuma-cp): fixed error when logging ExternalServiceResourceList and MeshResourceList

- pkg/core/resources/apis/mesh/external_service_helpers.go
- pkg/core/resources/apis/mesh/mesh_helpers.go
> fix(kuma-cp): fixed error when logging ExternalServiceResourceList and MeshResourceList

- docs/madr/decisions/011-multizone-envoy-admin.md
MADR to solve https://github.com/kumahq/kuma/issues/5080
> docs: madr multizone envoy admin operations

- deployments/charts/kuma/Chart.yaml
> chore(helm): fix logo URL

- .github/workflows/helm-release.yaml
- tools/releases/helm.sh
> ci(helm): update README.md badges

- .github/workflows/pr-merged.yaml
> ci: send repo update when tags are created

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
> chore(helm): update chart to 1.5.3

- docs/madr/decisions/015-retry-policy.md
Based on https://github.com/kumahq/kuma/pull/5478#discussion_r1045754065
> docs: follow up for MeshRetry MADR

- docs/madr/decisions/016-policy-array-merging.md
MADR for solving array merging.
> docs: madr of policy array merging

- SECURITY.md
> docs(SECURITY.md): update to use GH's reports

- docs/guides/new-policies.md
Currently there are policies that don't follow these rules. I'll open other PRs to adjust the existing policies.
> docs: memo on how to map API to Go struct

- pkg/plugins/policies/meshtimeout/plugin/testdata/gateway_listener.golden.yaml
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
This doesn't really solve the issue because there needs to be some validation to prevent misunderstanding but it at least makes things less broken.
> fix(MeshTimeout): don't alter MeshGateway listeners

- pkg/core/xds/merge.go
- pkg/core/xds/merge_test.go
> fix(kuma-cp): handle nil when merging append lists

- .github/workflows/auto-merge.yaml
- labels.yml
> ci: add auto approve and merge on ci/auto-merge

- .circleci/config.yml
- .github/workflows/update-changelog.yaml
> build: update to go 1.18.9

- pkg/core/resources/store/options.go
> chore: fix merge error in store options

- deployments/charts/kuma/templates/_helpers.tpl
Needed by the enterprise project.
> feat: allow injecting env from parent projects

- test/testenvconfig/envconfig.go
Found this looking at https://github.com/kumahq/kuma/pull/5473 and couldn't resist rewriting it. I'm 99% sure it has the same behavior.
> refactor(test/testenvconfig): rewrite `interfaceFrom`

- docs/generated/cmd/kumactl/kumactl_get_meshhttproute.md
- docs/generated/cmd/kumactl/kumactl_get_meshhttproutes.md
- docs/generated/cmd/kumactl/kumactl_inspect_meshhttproute.md
Add some files that are missing on master.
> chore(policy): add files missing from master

- .github/workflows/update-insecure-dependencies.yaml
> feat(build): revert scan output and add matrix branch to title

- mk/generate.mk
- tools/policy-gen/generate-policy-helm.sh
- tools/policy-gen/generate-policy-import.sh
> feat(kuma-cp): make policy generation more generic

- .github/workflows/update-insecure-dependencies.yaml
> feat(build): disable fail fast

- README.md
- UPGRADE.md
> chore(release): update readme file

- pkg/plugins/policies/meshtimeout/api/v1alpha1/validator.go
> fix(policy): fix meshtimeout static validation

- .github/workflows/lifecycle.yml
> ci(.github): fix bad if in refresh-active-releases

- pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
> fix(policy): meshtimeout for GRPC

- docs/madr/decisions/019-offline-signing-tokens.md
> docs(madr): offline signing tokens

- test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
> feat(helm): fix namespace in test

- .github/workflows/helm-release.yaml
> ci(helm): add KUMA_DIR env for tools prefix

- .github/workflows/helm-release.yaml
- .github/workflows/pr-comments.yaml
- Makefile
- mk/dependencies/deps.lock
- mk/dependencies/helm.sh
- mk/helm.mk
- tools/releases/helm.sh
> ci(helm): add `--dev` when doing pull_request too

- .circleci/config.yml
- .github/workflows/update-changelog.yaml
> build(go): update to 1.18.10

- .circleci/config.yml
They were expensive and didn't bring a lot
> ci(.circleci): remove dev jobs

- tools/releases/helm.sh
> chore: fix helm.sh script

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- deployments/charts/kuma/Chart.yaml
- deployments/charts/kuma/README.md
> chore: bump helm version

- .github/workflows/release.yaml
> ci(.github): fix typo in release.yaml

- .github/PULL_REQUEST_TEMPLATE.md
> ci(.github): update PR template to make it smaller

- .github/workflows/release.yaml
> ci(.github): fix job with Changelog.md

- pkg/core/xds/types.go
- pkg/xds/generator/ingress_generator.go
- pkg/xds/generator/ingress_generator_test.go
- pkg/xds/generator/testdata/ingress/with-meshhttproute.envoy.golden.yaml
- pkg/xds/sync/ingress_proxy_builder.go
- pkg/xds/sync/proxy_builder_test.go
- test/e2e_env/multizone/meshhttproute/test.go
- test/e2e_env/multizone/multizone_suite_test.go
> feat(MeshHTTPRoute): cross-zone support

- app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
> test(kumactl): fix golden files bad merge

- .circleci/config.yml
> ci(.circleci): edit config, refresh cache key

- UPGRADE.md
- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/pre-delete-webhooks.yaml
- deployments/charts/kuma/templates/pre-install-patch-namespace-job.yaml
- deployments/charts/kuma/templates/pre-upgrade-install-missing-crds-job.yaml
- deployments/charts/kuma/values.yaml
> refactor(helm): use values instead of dict in template

- .circleci/config.yml
- Makefile
- mk/distribution.mk
- mk/envoy.mk
- tools/envoy/fetch.sh
> ci(build): add build/distributions to replace distros.sh

- CONTRIBUTING.md
- README.md
> docs(links): fix chat link

- .github/workflows/lifecycle.yml
- .github/workflows/release.yaml
> ci(changelog): update ci-tools to latest

- pkg/plugins/resources/postgres/listener_test.go
- pkg/plugins/resources/postgres/migrate.go
- pkg/plugins/resources/postgres/migrate_test.go
- pkg/plugins/resources/postgres/migrations/fs.go
- pkg/plugins/resources/postgres/plugin.go
- pkg/plugins/resources/postgres/store_template_test.go
- pkg/test/store/postgres/test_container.go
- pkg/util/files/project.go
Parent project PR should be reviewed first.
> feat(persistence): allow redefining migrations

- mk/build.mk
- mk/envoy.mk
- mk/k3d.mk
- mk/run.mk
> ci(mk): fix some dev commands that were broken

- pkg/xds/envoy/tls/sni.go
- pkg/xds/envoy/tls/sni_test.go
> feat(kuma-cp): add util function to convert SNI to tags

- mk/envoy.mk
- tools/releases/version.sh
> chore(deps): upgrade envoy to v1.22.10

- docs/generated/kuma-cp.md
- mk/docs.mk
- kuma-cp.md auto generated from kuma-cp.defaults.yaml to be more easily embedded in the docs
- rewrite make to make it more straightforward and work with -j
> ci(docs): simplify and add kuma-cp.md config docs

- .github/workflows/release.yaml
https://github.com/kumahq/kuma/pull/6487 introduced invalid syntax
> ci(.github): fix invalid syntax in release.yaml

- tools/releases/version.sh
> chore(envoy): update to 1.25.4

- pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
> fix(gateway): don't fail on unexpected version

- mk/docker.mk
See https://app.circleci.com/pipelines/github/kumahq/kuma/21517/workflows/64b3a145-0462-4e1b-b9e9-69f820dd87f6/jobs/389676
> build(mk): fix docker login/logout

- .circleci/config.yml
> ci(.circleci): don't run test/container-structure

- pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
This just completes the conversion between resources
> feat(GatewayAPI): convert all matches and filters for GAMMA HTTPRoutes

- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/cni-daemonset.yaml
- deployments/charts/kuma/values.yaml
- docs/generated/kuma-cp.md
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/config/plugins/runtime/k8s/config.go
- pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml
- pkg/plugins/runtime/k8s/controllers/cni_taint_controller.go
- pkg/plugins/runtime/k8s/plugin.go
> feat(cni): k8s make namespace configurable

- .github/workflows/backport.yaml
Needs https://github.com/kumahq/.github/pull/98
> ci(.github): update backport workflow secret names

- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/cp-hpa.yaml
- deployments/charts/kuma/templates/egress-hpa.yaml
- deployments/charts/kuma/templates/ingress-hpa.yaml
- deployments/charts/kuma/values.yaml
> fix(helm): update HPA API version

- mk/kind.mk
- mk/metallb-k3d-kuma.yaml
xref: https://github.com/kumahq/kuma/issues/6713
> chore(build): add mk/metallb-k3d-kuma.yaml

- pkg/insights/resyncer.go
> feat(insights): include tenant id in rate limitter key

- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/basic.gateway_cluster.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/basic.gateway_listener.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/basic.gateway_route.golden.yaml
> feat(MeshLoadBalancingStrategy): add builtin gateway support

- pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
Trying to be clever with number of declared variables... 🤦 
> fix(GatewayAPI): npe errors

- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go
> chore(MeshTCPRoute): remove log "apply not implemented"

- pkg/envoy/admin/kds_client.go
- pkg/envoy/admin/kds_client_test.go
- pkg/intercp/envoyadmin/forwarding_kds_client.go
- pkg/intercp/envoyadmin/multitenancy.go
- pkg/intercp/envoyadmin/server.go
- pkg/kds/service/server.go
> feat(intercp): pass tenant id

- pkg/intercp/envoyadmin/forwarding_kds_client.go
> feat(intercp): use global tenant for catalog request

- test/e2e_env/kubernetes/meshtcproute/test.go
When we have a clash of `MeshHTTPRoute` and `MeshTCPRoute` policies, `MeshTCPRoute` should be applied when the destination's (`to[].targetRef`) protocol is `tcp` or uncpecified. Added e2e test is handling this case.
This test is related to my answer for @slonka question: https://github.com/kumahq/kuma/pull/6857#issuecomment-1567732015
- https://github.com/kumahq/kuma/pull/6857#issuecomment-1567732015
- it won't
- this PR introduces an e2e test
- there is no need as it's only e2e test + the policy is not yet released
- there is no need as it's only e2e test + the policy is not yet released
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue- …
> test(MeshTCPRoute): add e2e case for clash when destination is tcp

- docs/guides/new-feature.md
- docs/guides/upgrade-dependencies.md
- docs/madr/decisions/001-adopt-madr.md
> chore(docs): fix grammar

- go.mod
- go.sum
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
Also revert changes made in #6696 (not yet released), now that GAMMA conformance tests are updated. 
> chore(deps): bump gateway-api with conformance test fixes 

- README.md
- Adding OpenSSF badge 
- Adding CNCF Slack channel 
- Adding Community Call link 
Requirements to improve CLOMonitor score referenced in #6456
> docs(readme): updating links in README

- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_clusters.go
> chore(MeshTCPRoute): fix bad merge

- app/kumactl/pkg/tokens/client.go
- app/kumactl/pkg/tokens/zone_client.go
- app/kumactl/pkg/tokens/zoneingress_client.go
- pkg/plugins/authn/api-server/tokens/ws/client/client.go
- pkg/tokens/client.go
> feat(client): Consolidate HTTP Client

- pkg/core/resources/apis/mesh/gateway_validator.go
- pkg/core/resources/apis/mesh/gateway_validator_test.go
- pkg/plugins/runtime/gateway/filter_chain_generator.go
- pkg/plugins/runtime/gateway/gateway_route_generator_test.go
- pkg/plugins/runtime/gateway/testdata/tls/tcp-route.yaml
- test/e2e_env/kubernetes/gateway/mtls.go
- test/framework/client/collect.go
> feat(MeshGateway): support termination on TLS listeners

- test/e2e_env/multizone/meshhttproute/test.go
Attempts to test https://github.com/kumahq/kuma/issues/6905
> test(e2e): add additional multizone MeshHTTPRoute test

- pkg/plugins/runtime/gateway/route/configurers.go
> chore(MeshGateway): sort weighted clusters

- pkg/plugins/policies/core/xds/http_filters.go
- pkg/plugins/policies/meshfaultinjection/plugin/xds/configurer.go
- pkg/plugins/policies/meshratelimit/plugin/xds/configurer.go
> chore(xds): util to insert filters before router

- pkg/config/app/kuma-cp/config.go
> fix(config): add json tag to runtime section

- pkg/core/rest/errors/error_handler.go
- pkg/core/rest/errors/errors.go
> feat(rest): add conflict error

- docs/generated/kuma-cp.md
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
Fixes https://github.com/kumahq/kuma-website/issues/1351
> fix(config): add delta xds flag to defaults

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.cni-legacy-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
- deployments/charts/kuma/templates/cp-service.yaml
Fixes https://github.com/kumahq/kuma/issues/7086
> fix(helm): correct appProtocol configurations for https

- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/basic-gateway.gateway.cluster.golden.yaml
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/basic-gateway.gateway.listener.golden.yaml
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/basic-gateway.gateway.route.golden.yaml
> test(MeshAccessLog): refactor Gateway tests with golden files

- go.mod
- go.sum
- pkg/plugins/runtime/opentelemetry/plugin.go
> feat(kuma-cp): support Datadog propagation for tracing

- .github/workflows/update-docs.yaml
Remove cache and create directory
> ci(.github): fix update-docs job

- pkg/api-server/server.go
> fix(api-server): ensure tracing is setup before any HTTP calls

- pkg/gc/collector.go
- pkg/gc/collector_test.go
- pkg/gc/components.go
- pkg/gc/finalizer.go
- pkg/gc/finalizer_test.go
- pkg/intercp/catalog/heartbeat_component.go
- pkg/intercp/catalog/heartbeat_component_test.go
- pkg/intercp/catalog/writer.go
- pkg/intercp/catalog/writer_test.go
- pkg/intercp/components.go
- pkg/metrics/store/counter.go
Adds metrics for various components. What we are missing:
* insights
* event listener?
> feat(observability): components metrics

- api/mesh/v1alpha1/dataplane_helpers.go
- pkg/xds/generator/testdata/outbound-proxy/09.envoy.golden.yaml
> fix(xds): getTagsIncludingLegacy does not return service tag

- api/mesh/v1alpha1/dataplane_helpers.go
- pkg/core/policy/connection_matcher.go
- pkg/core/ratelimits/matcher.go
- pkg/core/xds/inspect/attachments.go
- pkg/core/xds/inspect/rules.go
- pkg/plugins/policies/core/xds/clusters.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtrace/plugin/v1alpha1/plugin.go
- pkg/xds/generator/outbound_proxy_generator.go
- pkg/xds/sync/dataplane_proxy_builder.go
- pkg/xds/topology/router.go
- pkg/xds/topology/timeouts.go
> refactor(xds): define GetServiceName for dataplane networking outbound

- go.mod
- go.sum
- pkg/plugins/resources/postgres/pgx_store.go
> feat(kuma-cp): add opentelemetry traces to pgx

- app/cni/pkg/install/main.go
> feat(cni): add retry for CNI config file check

- .github/workflows/update-docs.yaml
> ci(.github): move changelog versions.yaml in a `raw` dir

- pkg/plugins/resources/remote/store.go
> fix(kumactl): treat 404 as resource not found error

- Makefile
For consistency and relying on bash features when writing makefiles
> build(Makefile): use bash in make

- go.mod
- go.sum
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
- test/e2e/gateway/gatewayapi/conformance_test.go
So we can run conformance profiles on the main branch
> chore(deps): bump sigs.k8s.io/gateway-api

- pkg/util/watchdog/watchdog.go
> feat(watchdog): don't call onError if error was Canceled

- mk/check.mk
> ci(check): show git diff if changes exist

- pkg/intercp/catalog/heartbeat_component.go
- pkg/intercp/catalog/server.go
> chore(logs): switch heartbeat and ping logs to debug

- .github/workflows/auto-backport.yaml
> ci(actions): fix autolabel workflow

- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/config/plugins/runtime/k8s/config.go
- pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml
- pkg/plugins/bootstrap/k8s/plugin.go
Context is described in https://github.com/Kong/mesh-perf/issues/67.
> feat(kuma-cp): add 'renewDeadline' and 'leaseDuration' config params

- .github/PULL_REQUEST_TEMPLATE.md
> docs(actions): update PULL_REQUEST_TEMPLATE with autolabel docs

- .gitignore
Used by [`asdf`](https://asdf-vm.com/)
> chore(gitignore): add asdf-specific file

- test/framework/resources.go
Earlier it was ignoring descriptors other than the first one
- There is no relevant issue
- It won't
- Manually tested with one of the e2e tests using this function
- It seems there is no need as in no other places we were using more than one descriptor to be deleted
- There i no need
> chore(e2e): fix DeleteMeshResources function in e2e framework

- app/kumactl/cmd/install/testdata/install-control-plane.zone-universal-on-k8s.golden.yaml
- test/e2e/helm/e2e_suite_test.go
- test/e2e/helm/kuma_helm_deploy_global_and_zone_universal_mode.go
> fix(helm): fix helm tests

- app/kumactl/cmd/install/render_helm_files.go
> chore(kumactl): don't print info warnings when running Helm

- README.md
> fix(doc): broken link and align titles

- pkg/api-server/inspect_endpoints.go
> fix(api-server): always remove empty array in inspect gw api

- pkg/plugins/policies/meshretry/plugin/xds/configurer.go
It will make CodeQL happy
- it won't
- no tests
> chore(kuma-cp): fix incorrect conversion between integer types

- pkg/api-server/testdata/inspect/empty_resources_dataplanes.golden.json
- pkg/api-server/testdata/inspect/match_mesh_dataplanes.golden.json
- pkg/api-server/testdata/inspect/match_meshservice_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshgateway_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshgatewayroute_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshhttproute_absent_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshhttproute_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshtimeouthttproute.golden.json
- pkg/api-server/testdata/inspect/namefilter_dataplanes.golden.json
- pkg/api-server/testdata/inspect/pagination_dataplanes.golden.json
- pkg/api-server/testdata/inspect/policy_not_found_dataplanes.golden.json
- pkg/api-server/testdata/inspect/proxytemplate_dataplanes.golden.json
- pkg/api-server/testdata/inspect/retry_dataplanes.golden.json
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/dataplanepolicies/06.golden.yaml
> test(golden): reformat golden files

- pkg/plugins/policies/core/xds/endpoints.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/basic.gateway_endpoint.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/locality_aware.gateway_cluster.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/locality_aware.gateway_endpoint.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/locality_aware.gateway_listener.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/locality_aware.gateway_route.golden.yaml
- pkg/test/resources/builders/dataplane_builder.go
- pkg/test/xds/cla_cache.go
- pkg/test/xds/meshcontext.go
- pkg/xds/generator/testdata/outbound-proxy/cluster-dots.envoy.golden.yaml
- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_gateway.go
- test/e2e_env/multizone/multizone_suite_test.go
> feat(kuma-cp): add support for Gateway in MeshLoadBalancingStrategy

- .github/workflows/helm-release.yaml
> ci(actions): fix helm release

- .github/actions/e2e/action.yaml
- .github/workflows/build-test-distribute.yaml
- mk/check.mk
> ci(actions): fixing make check failure caused by YAML formatting 

- docs/madr/decisions/032-zone-to-global-policy-sync.md
> docs(MADR): zone to global policy sync

- pkg/kds/mux/zone_watch.go
- pkg/kds/mux/zone_watch_test.go
As is I believe if a Zone doesn't disconnect properly and is then deleted, then we'll forever check on it in a loop in `ZoneWatch`.
> fix(kds): don't error in ZoneWatch if the ZoneInsight is gone

- docs/madr/decisions/033-deprecate-standalone.md
> docs(MADR): deprecate standalone mode

- .circleci/config.yml
- .github/workflows/build-test-distribute.yaml
- pkg/plugins/resources/postgres/listener_test.go
- pkg/plugins/resources/postgres/migrate_test.go
- pkg/plugins/resources/postgres/store_template_test.go
- pkg/test/store/postgres/test_container.go
> ci(.github): migrate to github action instead of circleCI

- .github/workflows/build-test-distribute.yaml
> ci(.github): fix typo in bash script

- .circleci/config.yml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/e2e.yaml
- api/mesh/v1alpha1/dataplane.pb.go
- api/mesh/v1alpha1/dataplane.proto
> ci(.github): move runsOn to build-test-distribute

- go.mod
- go.sum
> chore(deps): bump github.com/bakito/go-log-logr-adapter from v0.0.2 to latest commit

- docs/madr/decisions/032-zone-to-global-policy-sync.md
> docs(MADR): update zone to global policy sync madr

- pkg/plugins/resources/postgres/pgx_store.go
- pkg/plugins/resources/postgres/pq_store.go
> fix(kuma-cp): use column names in sql insert

- api/openapi/specs/api.yaml
- api/openapi/specs/common/resource.yaml
- api/openapi/types/common/zz_generated.resource.go
- api/openapi/types/zz_generated.api.go
- docs/generated/openapi.yaml
- pkg/api-server/resource_endpoints.go
- pkg/api-server/resource_endpoints_test.go
- pkg/api-server/testdata/inspect/dataplanes/_rules/meshhttprouteabsent.golden.json
- pkg/api-server/testdata/inspect/dataplanes/_rules/overriding_meshtimeout.golden.json
- pkg/api-server/testdata/inspect/meshgateways/_rules/empty.golden.json
- pkg/api-server/testdata/inspect/meshgateways/_rules/empty.input.yaml
- pkg/api-server/testdata/inspect/meshgateways/_rules/gw_not_found.golden.json
- pkg/api-server/testdata/inspect/meshgateways/_rules/gw_not_found.input.yaml
- pkg/api-server/testdata/inspect/meshgateways/_rules/meshgateway.golden.json
- pkg/api-server/testdata/inspect/meshgateways/_rules/meshgateway.input.yaml
- pkg/api-server/testdata/inspect/meshgateways/_rules/meshhttproute.golden.json
- pkg/api-server/testdata/inspect/meshgateways/_rules/meshhttproute.input.yaml
- pkg/api-server/testdata/inspect/meshgateways/_rules/meshtrace_on_mesh.golden.json
- pkg/api-server/testdata/inspect/meshgateways/_rules/meshtrace_on_mesh.input.yaml
- pkg/plugins/policies/core/rules/rules.go
- pkg/plugins/policies/meshhttproute/api/v1alpha1/helpers.go
- pkg/plugins/policies/meshhttproute/api/v1alpha1/meshhttproute.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
- pkg/plugins/policies/meshhttproute/xds/configurer.go
- pkg/xds/cache/sha256/hash.go
- test/e2e_env/kubernetes/inspect/inspect.go
- test/e2e_env/multizone/inspect/inspect.go
This is useful to get all the policies that apply to a mesh gateway.
> feat(api-server): add _rules api to meshgateways

- CONTRIBUTING.md
**Not creating to avoid extra toil**
**None of the above needed as it is just a documentation change**
> docs(readme): update slack community link

- mk/kind.mk
> ci(mk): remove unused targets

- .github/workflows/auto-merge.yaml
- .github/workflows/backport.yaml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/e2e.yaml
- .github/workflows/pr-comments.yaml
- .github/workflows/pr-merged.yaml
- .github/workflows/release.yaml
- pkg/test/resources/samples/global_secret_samples.go
> ci(github): set minimal permissions on tokens

- .clomonitor.yaml
- .github/workflows/bom.yaml
- README.md
A basic version of an SBOM that enables us to provide a version file with some info for CLOMonitor
The SBOM is probably invalid but it was useful to extract the license.
> ci(github): add periodic sbom and license check

- pkg/kds/v2/reconcile/reconciler.go
We don't need to fill tenant metadata in hasher because `tenancyCallbacks` already fills this. This caused race condition because reconciler was modifying a metadata map in Node and in other places concurrently we read this map (for example to print log).
Additionally `snapshot, _ := r.cache.GetSnapshot(id)` because the if after this line checked previous error.
Fix https://github.com/kumahq/kuma/issues/8844
> fix(kds): race condition on fill metadata

- pkg/kds/service/server.go
When a new client connects, we right away start checking its health in the Zone, and then we go through all the filters. It's better to check the filters first and reject the client if it's not allowed, before we start watching the Zone.
> fix(kds): run filters before ZoneWatcher

- .github/workflows/helm-release.yaml
> chore(helm): added action for helm release

- pkg/insights/resyncer.go
I extracted the processing event to function so I don't have to repeat `!errors.Is(ctx.Err(), context.Canceled)` for every `err != nil`. There is a slight change in the behavior. Previously when `createOrUpdateServiceInsight` failed, we were still processing mesh insight. Now we don't. I don't think it matters. Usually, if it fails there is a problem with DB, so it's very likely that mesh insight would fail too.
> chore(insights): better handling of context cancelled

- .github/workflows/release.yaml
backport of https://github.com/kumahq/kuma/pull/6487
> ci(.github): fix schedule for release.yaml (backport #6487)

- test/e2e_env/kubernetes/meshtimeout/meshtimeout.go
I think there's a race condition that sometimes the MeshGateway timeout isn't present yet and `BeEmpty()` succeeds, sometimes it fails. We don't care about the MeshGateway timeout though.
> test(e2e): ignore MeshGateway MeshTimeout when testing inbound/outbound MeshTimeouts

- docs/madr/decisions/011-mesh-traffic-route.md
Nothing really, it's really a small fix.
> docs(MADR): fixed grammatical error

- app/kuma-dp/pkg/dataplane/meshmetrics/component.go
This can happen when you remove the policy.
> fix(kuma-dp): return default configuration for meshmetric when envoy stops listening on socket

- .github/workflows/_build_publish.yaml
- .github/workflows/build-test-distribute.yaml
> ci(github): update public-shared-actions

- .github/workflows/_e2e.yaml
Reverts kumahq/kuma#9673
Looks like this is making e2e tests fail
> ci(github): add back free disk space in e2e tests

- deployments/charts/kuma/Chart.yaml
> docs(helm): update `maintainers` in `Chart.yaml`

- docs/madr/decisions/039-meshservice-api.md
> docs(MADR): mesh service api

- pkg/core/runtime/component/resilient.go
Introduce exponential backoff when resilient component fails.
Components that are using resilient component:
* KDS
* OTEL
* Postgres events
* Zone watcher
* Insights resync
In all cases, it makes sense to have exponential backoff because those components relies on external systems - API/DB etc.
I tested it manually.
> feat(components): exponential backoff for resilient components

- docs/madr/decisions/011-mesh-traffic-route.md
- docs/madr/decisions/014-multizone-envoy-admin.md
- docs/madr/decisions/021-kds-redesign.md
- docs/madr/decisions/027-meshgateway-targetref.md
> docs(MADR): fix some typos

- .github/workflows/_build_publish.yaml
- .github/workflows/build-test-distribute.yaml
> ci(update): upload sbom to gh release/tag assets

- .github/workflows/_build_publish.yaml
- .github/workflows/build-test-distribute.yaml
backport pr: https://github.com/kumahq/kuma/pull/9963
> chore(deps): upload sbom to gh release/tag assets

- .github/workflows/_build_publish.yaml
- .github/workflows/build-test-distribute.yaml
Fixes the below warning in https://github.com/kumahq/kuma/actions/runs/8718225773/job/23915005504
```
Warning: Unexpected input(s) 'github-token', valid inputs are ['image', 'path', 'sbom', 'fail-build', 'output-format', 'severity-cutoff', 'only-fixed', 'add-cpes-if-none', 'by-cve', 'grype-version', 'vex']
Run anchore/scan-action@v3.6.4
with:
sbom: sbom.spdx.json
output-format: table
fail-build: false
add-cpes-if-none: true
severity-cutoff: critical
github-token: ***
only-fixed: false
by-cve: false
```
This should be backported to 2.7
> ci(update): fix sca extra opts

- docs/madr/README.md
Closes https://github.com/kumahq/kuma/issues/10031
> docs(MADR): fix madr docs hyperlink mismatch problems

- pkg/plugins/runtime/k8s/controllers/gateway_converter.go
- pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
- pkg/plugins/runtime/k8s/controllers/pod_status_controller.go
Merge release 2.7.2 fixes to master
> Merge release 2.7.2 master

- README.md
I need a commit on release branch so I can test action to automatically merge release to master
> chore(docs): fix typo in README

- test/framework/resources.go
we have a couple of occurrences of tests failing in the parent project that could be caused by not retrying here
> ci(stability): add retry to DeleteMeshResources

- docs/madr/decisions/053-sni.md
> docs(MADR): multizone sni

- test/e2e_env/universal/meshservice/meshservice.go
> test(e2e): add second hostname generator to MeshService test

- pkg/xds/topology/outbound.go
- pkg/xds/topology/outbound_test.go
Fix #10459
If you deploy the same app in both Kube clusters and use MeshServices, the traffic would still flow to both clusters. This is incorrect since we want to pin MeshService to a specific cluster.
The reason is that when we build endpoints, we first use kuma.io/service and ZoneIngress#availableServices. Only then we use MeshServices if it endpoints are not already there. It should be other way around. If we build endpoints using MeshService, we should not use kuma.io/service, nor ZoneIngress.
E2E test will land in a separate PR because it needs refactoring.
Aside of unit test, tested manually with demo app in both clusters
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue# …
> feat(meshservice): prefer MeshService over kuma.io/service routing

- UPGRADE.md
> chore(upgrade.md): added information about the token

- docs/madr/decisions/055-meshservice-subset.md
Related to https://github.com/kumahq/kuma/issues/10506
> docs(MADR): MeshService subsets

- pkg/core/resources/apis/meshservice/status/updater.go
- pkg/core/resources/apis/meshservice/status/updater_test.go
- pkg/insights/components.go
- pkg/test/resources/builders/meshservice_builder.go
**Do NOT squash on merging.** Allow merge commit first in the [repository settings](https://github.com/kumahq/kuma/settings).
> chore(merge): release-2.8 branch to master

- pkg/core/resources/store/transactions.go
We were observing `conn closed` errors on transaction rollback when context was cancelled. I've found in pgx issues that if context is cancelled pgx will close the connection. So we should not run Rollback as it will end up in errors. [pgx issue link](https://github.com/jackc/pgx/issues/679#issuecomment-586521209). When connection is closed, Postgres will automatically rollback the transaction
> fix(kuma-cp): fix conn closed error on transaction rollback

- test/framework/envs/multizone/env.go
I'm preparing to add an additional cluster and couldn't bring myself to copy paste.
This reduces duplication and removes a bunch of global state accesses.
> test(e2e): refactor multizone env creation

- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_gateway.go
This test is flaky. I want to make it a bit more stable by:
* increase the number of requests, and a bit increase the range of potential mismatch
* rename resource because it seems the same name was used in a different test
* rename gateway
> test(e2e): rename test resources, increase number of requests

- pkg/intercp/client/client.go
- pkg/intercp/server/server.go
These traces don't bring any value.
> feat(kuma-cp): don't trace intercp pings

- mk/k3d.mk
Closes https://github.com/kumahq/kuma/issues/10030
> ci(k3d): make sure the docker network is IPv4

- app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
- app/kumactl/data/install/k8s/metrics/grafana/kuma-dataplane.json
- app/kumactl/data/install/k8s/metrics/grafana/kuma-service-to-service.json
- app/kumactl/data/install/k8s/metrics/grafana/kuma-service.json
> fix(observability): use internal and external requests in outgoing status code panel

- test/framework/debug.go
See `kuma-1` namespace exports in https://github.com/kumahq/kuma/actions/runs/10252016473?pr=11046 for example:
```
kubectl get for namespace connectivity failed with error: error while running command: exit status 1; error: the server doesn't have a resource type "gateway-api"
```
> test(e2e): fix debug output if Gateway API CRDs aren't installed in the cluster

- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
> chore(policy): reuse code from MeshHTTPRoute in MeshTCPRoute

- pkg/plugins/runtime/k8s/webhooks/validation.go
> chore(kuma-cp): remove no longer needed validation

- test/e2e_env/universal/meshaccesslog/meshaccesslog.go
No matter what case is used inside `%REQ()%` the value is successfully returned
> test(e2e): document that header name case in `%REQ()%` doesn't matter

- mk/k3d.mk
Improve k3d/deploy make targets (mostly for helm deployment)
- it won't
- locally/manually tested
> chore(dev): improve k3d/deploy make targets

- test/e2e_env/kubernetes/appprobeproxy/probe_proxy.go
Fixing flakiness on the "application probe proxy" E2E test case by correcting the way of making assertions.
- CI flakiness: https://github.com/kumahq/kuma/actions/runs/10777627132/job/29887568328?pr=11356#step:12:18601
- Confirmed
- Tested
- No
- No
> test(e2e): use gomega when assert in Eventually statements of app probe proxy cases

- test/e2e_env/gatewayapi/conformance_test.go
Gateway API conformance tests flakinesses are widely seen, here are two examples:
* https://github.com/kumahq/kuma/actions/runs/10790251438/job/29932838255#step:12:8008
* https://github.com/kumahq/kuma/actions/runs/10933846592/job/30354678824#step:12:6631
This PR tries to stabilize the test suite by ignoring headless service cases temporarily.
It's found by some recent work that these headless service cases are cause differences between successful runs and fail runs. 
With the changes in this PR, we got 4 consecutive successful runs:
https://github.com/kumahq/kuma/actions/runs/10936141162
- CI flakiness
- No
- Tested
- No
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking …
> fix(e2e): stabilize the gatewayapi E2E conformance tests by ignoring headless service cases

- test/e2e_env/universal/trafficroute/traffic_route.go
Systematically have a way to check that route was applied before running the test.
This provides a deterministic logical barrier which can be retried then the assertions after to not need to be retried which makes code simpler and likely less flaky
> test(e2e): improve traffic route tests

- test/framework/universal_app.go
Reverts kumahq/kuma#11564
because a bunch of things failed https://github.com/kumahq/kuma/actions/runs/11048780712/
I'm not convinced it's related but let's just have this ready to revert :|
> Revert "chore(debug): get envoy logs in docker logs on universal tests"

- .github/workflows/check.yaml
> ci(github): fix checklist comment

- .github/workflows/ci-stability.yaml
Ranges are not supported. This time I run "action-validator" on the file.
I noticed failing Action
> ci(gha): fix cron for ci stability

- .github/workflows/check.yaml
It's broken and I don't have time to fix it yet
xrel: #11654 #11666 #11674
> ci(github): disable PR checklist

- DEVELOPER.md
- docs/guides/e2e-test-tips.md
When going through the `DEVELOPER.md` onboarding, I noticed that I missed to install `jq` and `yq` as prerequisites when executing `make check`.
Also fixed typo and improved highlighting of scripts in md.
> chore(docs): update dev onboarding

- DEVELOPER.md
We had a knowledge session around this so let's have this in docs so other people can use it.
Fix https://github.com/kumahq/kuma/issues/11759
> docs(debug): add debugging on k8s and universal docs

- .github/workflows/_build_publish.yaml
- test/e2e_env/universal/trafficroute/traffic_route.go
I made one mistake to merge https://github.com/kumahq/kuma/pull/11776 with `squash` which dropped some commits for master branch. So, I create this PR manually and merge them in a normal way to supplement the commits for master branch
Fix #XX
> chore(merge): release-2.9 branch to master

- .github/workflows/ci-stability.yaml
I was aiming for 7-7 but CEST.
No issue
> ci(gha): adjust cron in ci stability

- docs/madr/decisions/061-meshtls.md
> docs(MADR): update 061-meshtls.md

- mk/k3d.mk
We weren't exiting with an error if `docker network create` failed.
Avoid repeating the network handling logic by using a Makefile variable.
> ci(k8s): don't ignore errors on docker network create

- mk/build.mk
> chore(deps): bump coredns from v1.11.3 to v1.11.4

- go.mod
> chore(deps): upgrade go from 1.22.8 to 1.22.9

- go.mod
> chore(deps): upgrade go from 1.23.2 to 1.23.3

- go.mod
> chore(deps): upgrade golang from 1.23.3 to 1.23.4

- tools/releases/version.sh
> chore(deps): upgrade envoy to version v1.29.11

- go.mod
> chore(deps): upgrade golang from 1.22.9 to 1.22.10

- .github/dependabot.yml
Closes https://github.com/kumahq/kuma/issues/7657
Switch to `directories` and search recursively for any charts.
> ci(dependabot): update helm template images

- test/e2e_env/kubernetes/meshexternalservice/meshexternalservice.go
We support `MeshExternalService` only with egress enabled so there was no point to create use a different mesh for this case.
We use the same `Mesh` for all tests; we just changed it to disable traffic for MeshExternalService.
Fix #XX
> test(e2e): remove unused mesh

- pkg/intercp/catalog/writer.go
This isn't an error.
Just log this on info
> chore: remove unnecessary drop leader error log

- api/openapi/specs/api.yaml
- api/openapi/specs/common/error_schema.yaml
- docs/generated/openapi.yaml
Reverts kumahq/kuma#12416
It doesn't work correctly and it breaks `generate/oas` make target
> Revert "chore(sync): sync errors schema"

- tools/releases/version.sh
New patch release with CVE fix: https://github.com/envoyproxy/envoy/releases/tag/v1.29.12
> chore(deps): upgrade envoy from v1.29.11 to v1.29.12

- .github/workflows/pr-modification.yaml
This was causing issues when there were no pr modified.
The indirection with include was hard to read so we removed it
> ci(github): use include in pr-modification.yaml

- mk/build.mk
> chore(deps): bump coredns from v1.11.4 to v1.12.0

- mk/build.mk
> chore(deps): bump coredns from v1.11.3 to v1.12.0

- .github/workflows/pr-modification.yaml
Job reads PRs in the first step so permission should be clear
Fix #XX
> chore(gha): add read pull requests permissions

- test/e2e_env/universal/meshretry/grpc.go
Noticed some flakes and that test takes around 2-3minutes
* Removed unnecessary consistent check and replaced with eventually with `MustPassRepeatedly`
* Clean counters to not be dependent on keeping counters
* reduced time from 2min to around 1min
> test(e2e): refactor meshretry grpc test

- .github/workflows/_build_publish.yaml
- .github/workflows/_e2e.yaml
- .github/workflows/_provenance.yaml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/ci-stability.yaml
- .github/workflows/codeql.yaml
- .github/workflows/scorecard.yml
- mk/dependencies/deps.lock
- mk/dependencies/golangci-lint.sh
- mk/dependencies/helm.sh
- mk/dependencies/k3d.sh
It's a backport of changes which resolved most of the scorecard alerts in master
- #12466 
- #12477 
- #12480
> ci(security): resolve security alerts from scorecard

- .github/workflows/pr-modification.yaml
We need to define it on the job level
> chore(action): move permissions to specific job

- docs/madr/decisions/069-inbound-policies.md
Fix https://github.com/kumahq/kuma/issues/11885
> docs(MADR): inbound policies

- .github/workflows/_build_publish.yaml
Backport of https://github.com/kumahq/kuma/pull/12512
> chore(images): add permissions for build-images

- test/e2e_env/kubernetes/externalservices/externalservices.go
- test/e2e_env/kubernetes/meshtcproute/test.go
noticed flake (backport #11524)
> test(e2e): avoid name conflict and simplfy logic (backport #11524)

- pkg/insights/resyncer.go
We saw this issue multiple times on live environment:
```
unable to resync MeshInsight: failed to execute query: INSERT INTO resources (name, mesh, type, version, spec, creation_time, modification_time, owner_name, owner_mesh, owner_type, labels, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12);: ERROR: insert or update on table "resources" violates foreign key constraint "owner_fk" (SQLSTATE 23503)
```
We probably can just skip this error, as it won't be fixed with retry.
> fix(mesh-insights): skip error on mesh insight creation race condition

- .github/workflows/release.yaml
Release-tool has some new additions and fixes. It would be nice to upgrade
> chore(deps): upgrade release-tool from v1.0.0 to v1.1.0

- api/mesh/v1alpha1/mesh/rest.yaml
- api/mesh/v1alpha1/meshgateway/rest.yaml
- docs/generated/openapi.yaml
- pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
- pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
- pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
- tools/openapi/templates/endpoints.yaml
So that we can create a terraform provider out of it.
Just add it in the template.
xrel: https://github.com/Kong/kong-mesh/issues/7201
> chore(oapi): add x-speakeasy-entity-operation to all operations

- api/mesh/v1alpha1/mesh/rest.yaml
- api/mesh/v1alpha1/meshgateway/rest.yaml
- docs/generated/openapi.yaml
- pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
- pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
- pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
- tools/openapi/templates/endpoints.yaml
Reverts kumahq/kuma#12562
xrel: https://github.com/Kong/kong-mesh/issues/7309
> Revert "chore(oapi): add x-speakeasy-entity-operation to all operations"

- test/e2e/federation/federation_suite_test.go
Flaking federation tests
Related to: https://github.com/kumahq/kuma/issues/12584
> test(e2e): disable flaking federation tests

- api/mesh/v1alpha1/mesh/rest.yaml
- api/mesh/v1alpha1/meshgateway/rest.yaml
- docs/generated/openapi.yaml
- pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
- pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
- pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
- tools/openapi/templates/endpoints.yaml
Reverts kumahq/kuma#12558
caused an error in parent project, need to fix it but don't have time now
> Revert "chore(oapi): move CreateOrUpdateSuccessResponse under `components.responses`"

- app/cni/pkg/install/installer_config.go
- app/cni/pkg/install/main.go
Manual backport of #12592 to `release-2.9`
Fix #XX
> fix(cni): support bound service account token by reloading periodically (backport of #12592)

- mk/docs.mk
I need another target to modify the copied Kuma schema in parent project for https://github.com/Kong/kong-mesh/pull/7370
Add a target dependency as a variable.
> feat(oapi): add docs prerequisite

- pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_cluster.golden.yaml
- pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_listener.golden.yaml
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
- test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound.demo-client.golden.json
- test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound.test-server.golden.json
- test/e2e_env/universal/envoyconfig/testdata/meshtimeout/outbound.demo-client.golden.json
- test/e2e_env/universal/envoyconfig/testdata/meshtimeout/outbound.test-server.golden.json
Explained in https://github.com/kumahq/kuma/issues/12667
Fix https://github.com/kumahq/kuma/issues/12667
> fix(meshtimeout): set default inbound timeouts correctly

- test/e2e_env/universal/envoyconfig/envoyconfig.go
- test/e2e_env/universal/envoyconfig/testdata/meshaccesslog/inbound.demo-client.golden.json
- test/e2e_env/universal/envoyconfig/testdata/meshaccesslog/inbound.test-server.golden.json
- test/e2e_env/universal/envoyconfig/testdata/meshaccesslog/outbound.demo-client.golden.json
- test/e2e_env/universal/envoyconfig/testdata/meshaccesslog/outbound.test-server.golden.json
> fix(e2e): properly cleanup policies after envoyconfig test

- test/e2e/federation/federation_kubernetes.go
I noticed a flake in the last run. 
Backporting changes from the master branch
> test(e2e): increase time and use correct option

- pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_cluster.golden.yaml
- pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_listener.golden.yaml
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
Manual backport of #12692
Fix #12667
> fix(meshtimeout): set default inbound timeouts correctly (backport of #12692)

- pkg/plugins/policies/meshtimeout/api/v1alpha1/validator.go
- pkg/plugins/policies/meshtimeout/api/v1alpha1/validator_test.go
Forgot to add when implemented https://github.com/kumahq/kuma/pull/12696
> fix(meshtimeout): missing `rules` validation

- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
- test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshtimeout/mt-with-rules.gateway-proxy.golden.json
- test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshtimeout/mt-with-rules.input.yaml
We need to be able to configure gateway using new rules api
Fix #12792
> chore(MeshTimeout): implement rules api for configuring gateway with MeshTimeout

- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
- test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshaccesslog/mal-with-rules.gateway-proxy.golden.json
- test/e2e_env/universal/envoyconfig/testdata/builtingateway/meshaccesslog/mal-with-rules.input.yaml
Since we introduced new api, we need support for gateway
Fix #12817
> feat(MeshAccessLog): implement rules api for configuring gateway with MeshAccessLog

- mk/k3d.mk
After upgrading k3d to 5.8.1, the installation mode of calico has changed and now requires an operator.
Instead of yaml installation (is not available anymore) we are using operator as recommended in docs 
https://k3d.io/v5.8.1/usage/advanced/calico/#2-install-calico
> test(e2e): fix calico installation

- pkg/util/watchdog/watchdog_test.go
Flake https://github.com/kumahq/kuma/actions/runs/13263208578/job/37024960701
There is still a potential for a race condition, particularly when the message is processed, but the channel has not yet been closed.
> test(unit): use eventually for watchdog channel check

- pkg/xds/auth/callbacks.go
- pkg/xds/auth/k8s/authenticator.go
- test/e2e_env/universal/auth/dp_auth.go
> fix(xds): only auth once per xds gRPC stream in kuma-cp (backport of #12788)

- .github/workflows/build-test-distribute.yaml
- pkg/plugins/policies/meshaccesslog/api/v1alpha1/deprecated.go
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/deprecated.go
- pkg/plugins/policies/meshratelimit/api/v1alpha1/deprecated.go
- pkg/plugins/policies/meshtimeout/api/v1alpha1/deprecated.go
- pkg/plugins/policies/meshtls/api/v1alpha1/deprecated.go
Two PRs were out of date with master and after merge the project stopped building.
Fix compilation.
> ci(lint): fix the linter by fixing the build

- pkg/plugins/policies/core/rules/merge/merge.go
- pkg/plugins/policies/core/rules/merge/merge_test.go
Otherwise we get errors like this:
https://github.com/kumahq/kuma/actions/runs/13330989378/job/37235605477?pr=12844#step:12:17511
```
call of unknown method on zero Value
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick.func1
github.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:75
runtime.gopanic
runtime/panic.go:785
reflect.flag.mustBe
reflect/value.go:218
reflect.AppendSlice
reflect/value.go:2947
github.com/kumahq/kuma/pkg/plugins/policies/core/rules/merge.appendSlices
github.com/kumahq/kuma/pkg/plugins/policies/core/rules/merge/merge.go:366
github.com/kumahq/kuma/pkg/plugins/policies/core/rules/merge.Confs
github.com/kumahq/kuma/pkg/plugins/policies/core/rules/merge/merge.go:49
github.com/kumahq/kuma/pkg/plugins/policies/core/rules.BuildRules …
```
> fix(merging): fix merging pointers to slices of struct

- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix12847.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix12847.values.yaml
- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/cni-daemonset.yaml
- deployments/charts/kuma/values.yaml
- docs/generated/raw/helm-values.yaml
We were always overriding custom settings of tolerations do CNI
I've changed the parameter to add additional tolerations instead of overriding them, as the first three are required for Kuma-CNI.
Fix https://github.com/kumahq/kuma/issues/12847
> chore(helm): fix CNI tolerations

- pkg/core/resources/model/resource.go
manual backport of https://github.com/kumahq/kuma/pull/12908
> fix(kuma-cp): clone labels (backport #12908)

- .github/workflows/_test.yaml
- mk/test.mk
I noticed our unit tests take 14-17 minutes and sometimes timeout.  Increased timeouts to 25min
> test(unit): increase unit test timeout

- test/e2e_env/kubernetes/meshcircuitbreaker/meshcircuitbreaker.go
- test/server/cmd/echo.go
Errors returned by the Circuit Breaker do not counts towards outlier detection. It checks only upstream errors that's why we didn't get correctly into panic mode.
Added `x-set-response-code` to return specific error code and change to 1 failure
> test(e2e): introduce x-set-response-code to simulate upstream error

- test/e2e_env/universal/resilience/leader_election_postgres.go
While analyzing the flake, I noticed that our test assumes the first instance is always the leader. This is mostly true, but in some cases, high CPU usage or network failures can cause the leader to be lost. In the flake we observed, the first instance was initially the leader but missed a heartbeat, causing leadership to switch to another instance and resulting in a failed assertion.
leader1
```
2025-02-25T05:23:54.685Z	ERROR	postgres-leader	heartbeat missed: lock is already released	{"error": "lock is already released"}
2025-02-25T05:23:54.685Z	INFO	bootstrap	leader lost
```
leader2
```
2025-02-25T05:24:00.125Z	INFO	bootstrap	leader acquired
```
Changed the logic to assume any of these 2 instances can be a leader and store information about the leader and follower.
> test(e2e): rewrite leader election with postgres

- test/e2e_env/multizone/meshservice/policies.go
recent flake https://github.com/kumahq/kuma/actions/runs/13527148660/job/37801304192
Increased the number of requests from 100 to 200
Fix #XX
> test(e2e): increase number of requests

- pkg/plugins/runtime/k8s/webhooks/injector/injector.go
Previously, if a custom ConfigMap specified on a workload via the `traffic.kuma.io/transparent-proxy-configmap-name` annotation was not found in the workload or kuma system namespace, the default config was used. Now, with the new configuration method enabled, sidecar injection fails when the custom ConfigMap is missing.
Addresses https://github.com/kumahq/kuma-website/pull/2064#discussion_r1834437949
> feat(kuma-cp/transparent-proxy): fail injection if custom ConfigMap missing

- renovate.json
- test/e2e_env/kubernetes/gateway/delegated/meshtrace.go
- test/e2e_env/kubernetes/observability/meshtrace.go
- test/e2e_env/kubernetes/observability/tracing.go
- test/e2e_env/universal/observability/meshtrace.go
- test/e2e_env/universal/observability/tracing.go
Our branch protection rules didn't work properly and I pushed by mistake 2 wrong commits
> chore(git): fix improperly pushed commits

- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix13029.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix13029.values.yaml
- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/cni-daemonset.yaml
- deployments/charts/kuma/values.yaml
- docs/generated/raw/helm-values.yaml
We are setting it for Ingress/Egress/Control-plane but we didn't expose it for CNI
Add option to configure affinity
Fix #13029
> feat(helm): expose CNI affinity setting

- test/e2e/federation/federation_suite_test.go
xrel https://github.com/kumahq/kuma/issues/13217
skip test
> ci(flake): skip federation kube flaky test

- pkg/util/files/files.go
- pkg/util/files/files_suite_test.go
- pkg/util/files/files_test.go
> fix(util): fix bad sanitization of unix file names

- go.mod
> chore(deps): upgrade golang version from 1.23.6 to 1.23.7

- test/e2e_env/universal/transparentproxy/transparent_proxy.go
We should remove or fix skipped tests
* fix install command and assertion
* fix uninstall assertion and command
* added one more condition to check if traffic is broken
Fix https://github.com/kumahq/kuma/issues/13232
> test(e2e): enable and fix tp universal test

- test/e2e_env/multizone/meshhttproute/test.go
Noticed a flake
Maybe with more time it's going to improve stability
> test(e2e): extend time of Multizone test

- pkg/transparentproxy/validate/validator.go
Closes https://github.com/kumahq/kuma/issues/13335
Add more info to log message.
> chore(logs): add more info to kuma-validation failure logs

- docs/madr/decisions/000-template.md
We recently changed how we work and how we write our MADRs, we should reflect this in template
> docs(MADR): update MADR template to our current workflow

- docs/madr/decisions/060-rework-mesh-routes-matching.md
It's wasn't clear from the document how to pick a role for policy that references MeshHTTPRoute. We decided to go with the same approach we're using for MeshService referencing. I'm just adding this into the document so it's easier to understand the decision in the future.
> docs(MADR): update MeshHTTPRoute matching MADR with more details on policy's role

- docs/madr/decisions/072-computed-api-endpoints.md
This has always been an informal, unpersisted decision. Adding this as a MADR to more easily reference it
> docs(MADR): computed endpoints

- test/e2e_env/universal/envoyconfig/utils.go
Since we run e2e tests on both ipv4 and ipv6, `dnsLookupFamily` is different. In ipv4 `dnslookupFamily` is set to V4_ONLY,
and in the case of ipv6 this field is default, so it is missing in the config. Which causes e2e tests to fail on ipv6 in some cases
> fix(e2e): remove dnsLookupFamily from e2e envoy config test response

- go.mod
> chore(deps): bump golang version from 1.24.2 to 1.24.3

- UPGRADE.md
Improving some wording in the `UPGRADE.md`
> chore(UPGRADE.md): minor enhancement to UPGRADE.md

- .github/workflows/backport.yaml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/lifecycle.yml
to address security issues and to fix build: https://github.com/kumahq/kuma/actions/runs/15528883691/job/43713484350
> fix(actions): pin actions to sha

- mk/k3d.mk
`make k3d/restart` and `make k3d/deploy/kuma` was not working and as it's deprecated, we can just print the message about deprecation and exit with code 1
- Allow overriding project name via `PROJECT_NAME` and `KUMA_SETTINGS_PREFIX`
- Replace hardcoded names in Helm and wait targets with dynamic values
- Add support for extra Helm settings with `K3D_HELM_DEPLOY_ADDITIONAL_SETTINGS`
- Print renamed target messages to stderr and exit with code 1
---
Example usage:
```sh
make k3d/deploy/helm \
KIND_CLUSTER_NAME="kuma" \
K3D_DONT_LOAD="true" \
K3D_HELM_DEPLOY_NO_CNI="true" \
K3D_HELM_DEPLOY_ADDITIONAL_SETTINGS="
installCrdsOnUpgrade.enabled=false \
controlPlane.service.type=LoadBalancer \
"
```
> chore(make/k3d): support project name override and stderr output for old targets

- test/e2e_env/universal/envoyconfig/sidecars.go
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/no-policies.demo-client.golden.json
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/no-policies.test-server.golden.json
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/outbound-la-affinitytags.demo-client.golden.json
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/outbound-la-affinitytags.input.yaml
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/outbound-la-affinitytags.test-server.golden.json
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/outbound-maglev.demo-client.golden.json
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/outbound-maglev.input.yaml
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/outbound-maglev.test-server.golden.json
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/outbound-ringhash.demo-client.golden.json
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/outbound-ringhash.input.yaml
- test/e2e_env/universal/envoyconfig/testdata/sidecars/meshloadbalancingstrategy/outbound-ringhash.test-server.golden.json
Preserve existing behaviour in `envoyconfig` tests before implementing https://github.com/kumahq/kuma/issues/13436
> test(e2e): add envoyconfig tests for MeshLoadBalancingStrategy

- api/mesh/v1alpha1/zone/schema.yaml
- docs/generated/openapi.yaml
- tools/resource-gen/pkg/generator/main.go
To showcase how to do this https://github.com/kumahq/kuma/pull/13759.
Add and generate.
> feat(oapi): add zone proto to oas

- go.mod
> chore(deps): upgrade golang version from 1.23.8 to 1.23.10

- docs/madr/decisions/000-template.md
We discussed doing this to be more thorough about these in our designs
> docs(MADR): update template to add security and reliability section

- test/transparentproxy/testdata/debian-13-default.ip6tables-nft.golden
- test/transparentproxy/testdata/debian-13-with-multiple-config-flags.ip6tables-nft.golden
- test/transparentproxy/testdata/debian-13-with-multiple-flags.ip6tables-nft.golden
> test(transparentproxy): add missing files

- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
The PR #13965 missed to update the unit test golden files, this PR will fix it.
> test(helm): update unit test golden files

- docs/madr/decisions/081-datasource-api.md
As discussed in #13804 we want to introduce common DataSource structure
Here I discuss how should it be designed and potential issues
xref: https://github.com/kumahq/kuma/issues/13875
Rendered: https://github.com/lukidzi/kuma/blob/madr-datasource/docs/madr/decisions/081-datasource-api.md
> docs(MADR): introduction of common DataSource struct

- pkg/api-server/testdata/resources/inspect/dataplanes/_layout/empty_reachable_backend.golden.json
- pkg/api-server/testdata/resources/inspect/dataplanes/_layout/missing_reachable_backend.golden.json
- pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_mixed_destinations.golden.json
- pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_ms_destinations.golden.json
- pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_ms_destinations_reachable_backend.golden.json
- pkg/api-server/testdata/resources/inspect/dataplanes/_layout/single_dp.golden.json
- pkg/api-server/testdata/resources/inspect/dataplanes/_layout/single_ms_destination.golden.json
Forgot in https://github.com/kumahq/kuma/pull/14102
Update golden files
> feat(kuma-cp): update golden files for proxyResourceName

- pkg/core/kri/kri.go
- pkg/core/system_names/system_names.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/system_names/api.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.clusters.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.listeners.golden.yaml
https://github.com/kumahq/kuma/issues/13968
Rename Mesh Metric resources.
Fix https://github.com/kumahq/kuma/issues/13968
> feat(kuma-cp): rename mesh metric system resource to follow unified naming format

- pkg/envoy/builders/README.md
- pkg/envoy/builders/common/builder.go
- pkg/envoy/builders/common/modifier.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshaccesslog/plugin/xds/configurer.go
I hope in the near future `pkg/envoy/builders` package will be used a lot to implement MeshTrafficPermision and MeshIdentity functionality :) 
* add README.md explaining the motivation and how to add new builders
* remove ConfigureIf methods as they're replaced with Configure(If(...))
> docs(builders): add README.md

- pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtrafficpermission/xds/legacy_rbac_configurer.go
- pkg/plugins/policies/meshtrafficpermission/xds/legacy_rbac_configurer_test.go
To streamline review of: https://github.com/kumahq/kuma/pull/14147
> feat(MeshTrafficPermission): rename plugin rbac configurer

- pkg/xds/generator/dns_generator.go
- pkg/xds/generator/dns_generator_test.go
- pkg/xds/generator/testdata/dns/6-dataplane.input.yaml
- pkg/xds/generator/testdata/dns/6-envoy-config.golden.yaml
In https://github.com/kumahq/kuma/issues/13974
Nothing out of standard.
Fix https://github.com/kumahq/kuma/issues/13974
> feat(kuma-cp): rename dns resources

- CONTRIBUTING.md
These have changed and the instructions were not up to date.
> docs(CONTRIBUTING.md): update backport instructions

- docs/generated/openapi.yaml
- mk/docs.mk
https://github.com/kumahq/ci-tools/pull/89
now it takes 7 seconds: https://github.com/kumahq/kuma/actions/runs/16933076161/job/47984263913?pr=14226#step:10:407
bump dep
> chore(deps): bump openapi-tool to v1.1.6

- pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go
fixing failing check on master
> fix(build): fix failing check on master

- pkg/core/naming/unified-naming/unified_naming.go
> chore(kuma-cp): add helper to check if unified naming enabled

- tools/policy-gen/generator/cmd/core_resource.go
In https://github.com/kumahq/kuma/issues/12861
Add check for alphanum
Closes https://github.com/kumahq/kuma/issues/12861
> feat(kuma-cp): add validation on resourceType

- pkg/xds/bootstrap/generator.go
- pkg/xds/bootstrap/generator_test.go
- pkg/xds/bootstrap/template_v3.go
- pkg/xds/bootstrap/template_v3_test.go
- pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request-with-unified-resource-naming-feature-flag.golden.yaml
In https://github.com/kumahq/kuma/issues/14362
Rename resources
Fix https://github.com/kumahq/kuma/issues/14362
> feat(kuma-cp): rename access log sink system resource to follow unified naming format

- pkg/core/resources/apis/mesh/validators.go
- pkg/core/resources/apis/mesh/validators_test.go
- pkg/plugins/policies/meshaccesslog/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshhttproute/api/v1alpha1/validation_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator.go
- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshproxypatch/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshratelimit/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshretry/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshtcproute/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshtimeout/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshtls/api/v1alpha1/testdata/full-invalid.output.yaml
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/validator_test.go
The message was missing a invalid kind
added a kind to the message
> fix(policy): add invalid kind to the error msg

- test/e2e_env/kubernetes/gateway/gateway.go
I've checked the configuration of package and cannot find obvious flake, let's try it for a some time
xref: https://github.com/kumahq/kuma/issues/14072
> test(e2e): enable Gateway MLBS test
