kumahq/kuma

app/kumactl/cmd/config/config_control_planes_add_test.go, mk/k3d.mk
- Fix k3d/load/images retries
- Increase timeout on config_control_planes_add (causing mac_test to fail)
=> fix(ci): improve some failing bits of CI

test/e2e/gateway/gatewayapi/gateway_api.go, test/e2e/gateway/gatewayapi/gatewayapi_suite_test.go, test/framework/client/collect.go
First E2E tests of Gateway API
xref #3468
No docs
=> test(*): e2e tests of Gateway API

test/e2e/gateway/gatewayapi/gateway_api.go, test/framework/client/collect.go
Skip Gateway API tests for IPV6 and increase timeout for loadbalancer since I noticed it timeout out once.
No issues reported - flaky test.
=> test(*): skip gatewayapi tests for IPV6

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
Gateway API reconciliation was stuck in a loop (reconciling forever) because GatewayInstance was constantly updated.
We should only update Status of objects if there is any change to the status.
=> fix(kuma-cp): gateway reconciliation loops forever

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
Revert #4034 and use `SetStatusCondition`
The problem fixed by #4034 appears to be that `LastTransitionTime` was always updated with the current time. `SetStatusCondition` handles this and it's already in use for the Gateway API objects, `GatewayInstanceReconciler` hadn't been updated.
=> fix(gateway): fix status updating in MeshGatewayInstance reconciliation

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml, pkg/plugins/runtime/k8s/plugin.go, pkg/plugins/runtime/k8s/webhooks/gatewayapi_multizone_validator.go, pkg/plugins/runtime/k8s/webhooks/gatewayapi_multizone_validator_test.go
Provide validation that Gateway API cannot be used with Zone and Global CP.
I validate only GatewayClass, otherwise, it's kind of hard to figure out if Gateway or GatewayRoute is used only with Kuma or not. GatewayClass is the required resource for Kuma Gateway to work anyways.
Fix #3905
There is already docs that you cannot use GatewayAPI with mutlizone
=> feat(kuma-cp): validate GatewayAPI with multizone

test/e2e/gateway/gatewayapi/gateway_api.go
=> test(e2e): set Gateway API HTTPS test to pending

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/templates/cp-deployment.yaml, deployments/charts/kuma/templates/cp-service.yaml
This PR updates both the kuma-cp deployment, and service template by exposing the metrics port (TCP/5680) so that metrics can easily be scraped by self-deployed Prometheus.  This configuration supports both Prometheus Operator configured PodMonitors, and ServiceMonitors configuration options.
* Helm - Exposed kuma-cp's metric port via deployment and service configurations
N/A
- [ x ] Manual testing on Kubernetes
- Does not effect backwards compatibility.
=> feat(helm): Expose kuma-cp's metric port so it can be scraped by self-deployed prometheus.

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
If the service of a mesh gateway instance had TargetPort set, we need to override it again.
Fixed flakiness of Gateway E2E test.
=> fix(kuma-cp): mesh gateway instance service target port

app/kumactl/cmd/inspect/testdata/inspect-gateway-dataplane.server-response.json, app/kumactl/cmd/inspect/testdata/inspect-health-check.server-response.json, pkg/api-server/testdata/inspect_gateway_dataplane.json, pkg/api-server/testdata/inspect_retry.json, pkg/api-server/testdata/inspect_traffic-trace.json, pkg/api-server/types/inspect.go
=> chore(api-server): use MeshGatewayDataplane instead of GatewayDataplane in inspect endpoint output

pkg/plugins/runtime/k8s/controllers/inbound_converter.go, pkg/plugins/runtime/k8s/controllers/pod_converter_test.go, pkg/plugins/runtime/k8s/controllers/testdata/01.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/02.other-services.yaml, pkg/plugins/runtime/k8s/controllers/testdata/04.other-services.yaml, pkg/plugins/runtime/k8s/controllers/testdata/05.other-services.yaml, pkg/plugins/runtime/k8s/controllers/testdata/06.other-services.yaml, pkg/plugins/runtime/k8s/controllers/testdata/06.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/07.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/10.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/11.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/12.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/17.other-services.yaml, pkg/plugins/runtime/k8s/controllers/testdata/18.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/18.pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/18.services-for-pod.yaml
This has always been a tricky bit for the provided gateway with often
the dataplane generation failing with:
```
controllers.Pod	unable to create/update Dataplane	{"pod": "kong-mesh-system/kong-gateway-kong-9k8zc", "operationResult": "unchanged", "error": "admission webhook \"validator.kuma-admission.kuma.io\" denied the request: spec.networking.gateway.tags[\"kuma.io/protocol\"]: other values than TCP are not allowed"}
```
We now simply drop and log whenever a protocol is set on a gateway that is not tcp
=> fix(gateway): ignore non TCP protocol for provided gateway

pkg/xds/generator/proxy_template.go, pkg/xds/generator/proxy_template_test.go, pkg/xds/server/v3/reconcile.go, pkg/xds/server/v3/snapshot_generator_test.go
Hooks should be executed before Proxy Template modifications.
Fix #3929
No docs.
=> fix(kuma-cp): execute hooks before proxy template modifications

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml, go.sum, pkg/plugins/runtime/k8s/plugin.go, test/e2e/gateway/gatewayapi/gateway_api.go
Add upstream validation of Gateway API
Fix #3416
=> feat(kuma-cp): upstream validation of Gateway API

pkg/defaults/mesh/circuit_breaker.go, pkg/defaults/mesh/mesh.go, pkg/defaults/mesh/retry.go, pkg/defaults/mesh/timeout.go, pkg/defaults/mesh/traffic_permission.go, pkg/defaults/mesh/traffic_route.go, test/e2e/deploy/e2e_suite_test.go, test/e2e/deploy/kuma_deploy_kubernetes.go
Store operation `Create` writes Meta to the global variables like `defaultCircuitBreakerResource`. That's why it failed to create default resources for the new mesh with the error `resourceVersion should not be set on objects to be created`
* wrap global resources into builder functions
* add e2e tests
N/A
=> fix(kuma-cp): default policy creation

app/kumactl/cmd/inspect/inspect_dataplane.go, app/kumactl/cmd/inspect/testdata/inspect-gateway-dataplane.golden.txt
The output is otherwise confusing if the route's name doesn't make it clear it's a route.
=> chore(kumactl): prefix MeshGatewayRoutes with ROUTE in inspect dataplane output

test/e2e/gateway/gatewayapi/gateway_api.go
I did not catch that Gateway TLS test was disabled here https://github.com/kumahq/kuma/pull/4066 but it was fixed here https://github.com/kumahq/kuma/pull/4071
Also changed BeforeEach to BeforeAll since that's the thing now in Ginkgo 2.
=> chore(*): reenable gateway e2e tls test

pkg/plugins/runtime/k8s/controllers/probes.go, pkg/plugins/runtime/k8s/controllers/testdata/10.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/10.pod.yaml, pkg/plugins/runtime/k8s/webhooks/injector/probes.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.21.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.21.input.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.22.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.22.input.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.23.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.23.input.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.28.golden.yaml
Support startProbes like we support livenessProbes and readinessProbes
Fix #4020
=> feat(k8s): support startupProbes

deployments/charts/kuma/templates/_helpers.tpl
Explicitly setting `global.image.tag` (and thus causing its value to not be upgraded without `--reset-values`):
```
$ helm install kuma kuma/kuma --version 0.9.0 --set-string global.image.tag=1.5.0
...
You can access the control-plane via either the GUI, kubectl, the HTTP API, or the kumactl CLI.
$ helm upgrade kuma deployments/charts/kuma
Error: UPGRADE FAILED: execution error at (kuma/templates/pre-upgrade-install-missing-crds-job.yaml:131:20):
This chart only supports Kuma version "1.6.0" but global.image.tag is set to "1.5.0". Set global.image.tag to "1.6.0" or skip this check by setting *.image.tag for each individual component.
```
Leaving `global.image.tag` unset:
```
$ helm install kuma kuma/kuma --version 0.9.0
...
You can access the control-plane via either the GUI, kubectl, the …
```
=> feat(helm): fail if global.image.tag and appVersion incompatible

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
Fixes https://github.com/kumahq/kuma/issues/3938
=> feat(gateway): use MeshGatewayInstance name for generated objects

pkg/plugins/runtime/k8s/controllers/pod_status_controller.go
When `kuma-dp` is deployed with a different type than `Job` and containers are stopped, `kuma-sidecar` is still running. Changed behavior that does not check only `Job` type.
* Implement `kuma-sidecar` shutdown for other types than `Job`
Fix #2848
=> feat(kuma-cp): shutdown kuma-dp container for any owner kind

pkg/core/resources/apis/mesh/proxytemplate_profiles.go, pkg/core/resources/apis/mesh/proxytemplate_validator.go, pkg/core/resources/apis/mesh/proxytemplate_validator_test.go, pkg/xds/generator/proxy_template.go, test/e2e/gateway/gateway_universal.go
This PR resolves https://github.com/kumahq/kuma/issues/3935
Not sure if tests are needed for this change or what would be the best way of going about adding them
=> fix(*): proxyTemplate validation error

pkg/api-server/inspect_endpoints.go, pkg/api-server/inspect_endpoints_test.go, pkg/api-server/testdata/inspect_gatewayroutes_dataplanes.json
Part of https://github.com/kumahq/kuma/issues/4103
=> feat(api-server): add inspect meshgatewayroute dataplanes endpoint

test/e2e/inspect/inspect_k8s_multizone.go, test/framework/k8s_cluster.go
This is useful for places where we reuse these e2e tests
=> ci(e2e): use Config.Zone{In,E}gress app instead of strings

UPGRADE.md, pkg/core/resources/apis/mesh/mesh_helpers.go, pkg/xds/generator/egress/external_services_generator.go, pkg/xds/generator/egress/internal_services_generator.go, pkg/xds/generator/egress/testdata/06.mixed-services-with-external-in-other-zone.golden.yaml, pkg/xds/generator/egress/testdata/input/06.mixed-services-with-external-in-other-zone.yaml, pkg/xds/sync/ingress_proxy_builder.go, pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go, test/e2e/externalservices/localityawarelb_multizone/locality_multizone_hybrid.go
Do not require `localityAwareLoadBalancing` property to be `true` for external communication through zone where `ExternalService` is defined.
* removed condition for`routing.localityAwareLoadBalancing` 
Fix #3901
=> feat(kuma-cp): do not require lb property external service routing

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, deployments/charts/kuma/templates/egress-deployment.yaml, deployments/charts/kuma/templates/ingress-deployment.yaml, test/e2e/externalservices/localityawarelb_multizone/locality_multizone_hybrid.go
This was missing when using a `kuma.name` in the template
=> fix(helm): add prefix to `app` label in ingress/egress deployment

deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cp-ingress.yaml, deployments/charts/kuma/values.yaml
expose kuma-cp gui/api through ingress
* [Implement helm ingress definition]
Fix #1117
=> feat(kuma-cp): expose kuma-cp gui through ingress

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/Chart.yaml, deployments/charts/kuma/README.md
Update helm charts in Kuma
* [Fix ...]
Fix #XXX
=> fix(kuma-cp): update helm charts for 1.5.1

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/core/resources/store/config.go, pkg/config/loader_test.go, pkg/core/bootstrap/bootstrap.go, pkg/core/datasource/dynamic_test.go, pkg/core/managers/apis/mesh/mesh_manager.go, pkg/core/managers/apis/mesh/mesh_manager_test.go, pkg/core/managers/apis/zone/zone_manager.go, pkg/core/managers/apis/zone/zone_manager_test.go, pkg/core/secrets/manager/manager.go, pkg/core/secrets/manager/validator_test.go, pkg/plugins/ca/builtin/manager_test.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller_test.go, pkg/plugins/runtime/k8s/plugin.go, pkg/plugins/runtime/k8s/webhooks/mesh_validator.go, pkg/plugins/runtime/k8s/webhooks/secret_validator.go, pkg/plugins/runtime/k8s/webhooks/secret_validator_test.go, pkg/plugins/runtime/k8s/webhooks/zone_validator.go, pkg/test/runtime/runtime.go, pkg/xds/secrets/secrets_test.go, pkg/xds/topology/outbound_test.go
Add ability to delete resources unsafe way. Why?
* With tests we don't want to wait for all Dataplane object to be deleted, we just want to delete Mesh and forget about the rest
* On prod, we may get into an undefined state in which you may want to bypass validators. On Kubernetes you can always remove the webhook temporarily, on universal there is no such thing.
I was considering supporting this on Validator level, but I believe this is the responsibility of manager/webhook rather than validator. You should be able to swap a validator without worrying about this flag.
~- [ ] Add …
=> feat(kuma-cp): unsafe delete

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/templates/cp-rbac.yaml
Replaces uses of the wildcard in CP RBAC with a concrete set of verbs.
This is to placate security tooling that often blocks wildcard allow.
Signed-off-by: John Harris <john@johnharris.io>
=> fix(helm): remove wildcard rbac verbs

test/dockerfiles/Dockerfile.universal, tools/releases/docker.sh, tools/releases/dockerfiles/Dockerfile.kuma-cp, tools/releases/dockerfiles/Dockerfile.kuma-dp, tools/releases/dockerfiles/Dockerfile.kuma-init, tools/releases/dockerfiles/Dockerfile.kuma-prometheus-sd, tools/releases/dockerfiles/Dockerfile.kumactl
I may be missing something but it's not declared via the `ARG` instruction in any `Dockerfile` and is thus always empty, no matter whether we set it via `--build-arg`.
Docker spits out warnings like:
```
[Warning] One or more build-args [KUMA_ROOT] were not consumed
```
=> build(dockerfiles): remove always empty build arg KUMA_ROOT

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cni-daemonset.yaml, deployments/charts/kuma/templates/cp-deployment.yaml, deployments/charts/kuma/templates/egress-deployment.yaml, deployments/charts/kuma/templates/ingress-deployment.yaml, deployments/charts/kuma/templates/pre-delete-webhooks.yaml, deployments/charts/kuma/templates/pre-install-patch-namespace-job.yaml, deployments/charts/kuma/templates/pre-upgrade-install-missing-crds-job.yaml, deployments/charts/kuma/values.yaml
Currently, there is no place to specify/customize
the securityContext for following components:
kuma-cp/ Jobs (crd/webhook/ns)/ Ingress / Egress / CNI
This PR provides the option to specify securityContext
for all of the above components.
cc. @gdasson @johnharris85 
* Added option to specify securityContext for :
kuma-cp/ Jobs (crd/webhook/ns)/ Ingress / Egress / CNI
* Fix(partially) #https://github.com/kumahq/kuma/issues/3989
* Refer https://github.com/kumahq/kuma/pull/4111
* Fix(partially) #https://github.com/kumahq/kuma/issues/3989
Does not affect backward compatibility
=> feat(helm): allow specifying security context

tools/releases/distros.sh
There's a refactor in here around not having a `$distro` set. The difference is a new archive `kuma-$version-$system-$arch.tar.gz`, i.e. without a `$distro`, containing only `kumactl`:
```
$ tar tvf build/artifacts-linux-amd64/kuma-dev-7557228b6-linux-amd64.tar.gz | awk '{print $6}'
./
./kuma-dev-7557228b6/
./kuma-dev-7557228b6/bin/
./kuma-dev-7557228b6/bin/kumactl
./kuma-dev-7557228b6/LICENSE
./kuma-dev-7557228b6/NOTICE-kumactl
```
Part of #3814
=> build: package and release static kumactl binary

test/e2e/compatibility/cp_compatibility_kubernetes_multizone.go
Demo client was not cleaned up which caused other test to fail.
No issue reported.
=> test(e2e): fix compatibility test cleanup

.golangci.yml, app/kuma-cp/cmd/run.go, pkg/defaults/components.go, pkg/dns/components.go, pkg/dp-server/components.go, pkg/gc/components.go, pkg/hds/components.go, pkg/insights/components.go, pkg/insights/resyncer.go, pkg/kds/context/context.go, pkg/kds/global/components.go, pkg/kds/zone/components.go, pkg/kds/zone/components_test.go, pkg/mads/server/server.go, pkg/xds/components.go
We were running the GC in global when we should only delete dataplanes in zones.
We also moved all the conditions for setting up components inside the Setup methods to make things
easier to read.
In the future I'd like to move all the setup methods in `app/kuma-cp/cmd` this would avoid each package to depend on runtime also setting up the runtime has nothing to do with what the original packages do anyway
* move all runtime checks inside the setup method of each component
* make kds_zone. Callbacks not depend on `runtime` but directly on the map it needs.
Fix https://github.com/kumahq/kuma/issues/2015
=> fix(kuma-cp): don't run dataplane gc in global

test/e2e/externalservices/e2e_suite_test.go, test/e2e_env/universal/externalservices/externalservices_hostheader.go, test/e2e_env/universal/universal_suite_test.go
Migrate external service test to Universal environment.
=> test(e2e): migrate external service host header test

pkg/plugins/resources/memory/store.go, pkg/test/store/owner_test_template.go
Memory store has a problem with deleting a resource in the following scenario:
* Create a parent with a child
* Delete the child
* Delete the parent
No issues reported. I noticed this while writing a multizone test.
=> fix(kuma-cp): memory store cannot delete a parent

test/e2e/gateway/gatewayapi/conformance_test.go
=> test(gateway): skip conformance tests on IPv6

mk/dev.mk
Previous changes caused that build for `dev_ubuntu` starts to fail. It seems that it is caused by https://discuss.circleci.com/t/tar-cannot-change-ownership/28766. 
* [Added flag for getting tar]
=> fix(*): fix the owner for dev_ubuntu build

pkg/test/runtime/runtime.go, pkg/xds/sync/egress_proxy_builder.go, pkg/xds/sync/proxy_builder_test.go, pkg/xds/sync/testdata/input/default_resources.yaml, pkg/xds/topology/dataplanes.go, pkg/xds/topology/dataplanes_test.go
We were not resolving the address which was causing to send an invalid envoy config
as EDS can't accept hostnames.
Also refactor the topology/dataplanes to avoid redundant code and remove unecessary calls
when the ip already resolved
Fix #4218
=> fix(zone-egress): resolve zone-ingress advertized address

mk/generate.mk
```
$ make build
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
find: warning: you have specified the global option -mindepth after the argument -type, but global options are not positional, i.e., -mindepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options …
```
=> ci(mk): fix warning about find arguments

.github/workflows/pr-comments.yaml, CONTRIBUTING.md, mk/check.mk, mk/docs.mk, tools/releases/version.sh
You can now comment on a pr with `/format` or `/golden_files` and it will run
the generation and formating or the tests with `UPDATE_GOLDEN_FILES=true` and
add a commit to the PR
This aims to make it easier for contributors to quickly fix their PRs when code gen
or equivalent changes things
=> ci(.github): add pr comment actions for golden files and format

deployments/charts/kuma/templates/pre-delete-webhooks.yaml, deployments/charts/kuma/templates/pre-install-patch-namespace-job.yaml, deployments/charts/kuma/templates/pre-upgrade-install-missing-crds-job.yaml
Currently, crd/webhook/ns jobs don't have
resource management (requests and limits)
context. Adding resource management to
these jobs.
* add resource management for jobs
* Implement resource management for crd/webhook/ns jobs
Doesn't impact backward compatibility
=> feat(helm): add resource management for jobs

.circleci/config.yml
This way flaky tests don't affect whether `master` commits have images available.
=> ci(.circleci): publish commit artifacts without waiting for tests

pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/transparentproxy/istio/config/config.go, pkg/transparentproxy/kubernetes/kubernetes.go, pkg/transparentproxy/kubernetes/kubernetes_test.go
Add pod annotation to use experimental transparent proxy engine on kuma-init container. 
Also needs to be added to annotation docs.
* Add pod annotation to use experimental transparent proxy engine.
Fix #4150
=> feat(kuma-cp): experimental transparent proxy annotation

.circleci/config.yml, mk/dev.mk
Because executor changed to golang for release job we need to setup remote docker.
* [Added setup of docker remote]
Fix #XXX
=> fix(*): added docker remote setup for release pipeline

mk/e2e.new.mk
Increase timeout while https://github.com/kumahq/kuma/issues/4259 is not done
* [Fix ...]
Fix #XXX
=> chore(e2e): increase timeout from 45m to 60m

docs/proposals/app-metrics.md
Added proposal of metrics from the application better experience.
Original https://github.com/kumahq/kuma/pull/4185, had to reopen because of DCO not passing - it shows that every commit need to be signed
* [added proposal]
Proposal for larger task https://github.com/kumahq/kuma/issues/3457
=> docs(*): application metrics hijacking proposal

pkg/xds/cache/mesh/cache.go, pkg/xds/cache/mesh/cache_test.go
Without this change, whenever multiple meshes are in use, the `MeshContext` is always rebuilt regardless of the hashes.
=> fix(kuma-cp): don't always recompute mesh contexts

test/e2e/gateway/gatewayapi/gateway_api.go
The first command's output (all resources) is logged and `kubectl` has the `-k` switch now.
=> test(gateway): reduce logger output in Gateway API conformance test

app/kuma-dp/pkg/dataplane/command/build_command.go, app/kuma-dp/pkg/dataplane/command/build_command_windows.go
@lukidzi noticed that compilation fails on Windows, because of a lack of arguments.
At the same time, I noticed that I missed the args on Linux.
I'm not sure how to implement this on Windows this time. I'd rather create an issue and figure it out later.
No docs
=> feat(kuma-cp): intercept signal for different platforms

app/kumactl/cmd/apply/apply_test.go, app/kumactl/cmd/generate/generate_dataplane_token_test.go, app/kumactl/cmd/generate/generate_zone_token_test.go, app/kumactl/cmd/generate/generate_zoneingress_token_test.go, app/kumactl/cmd/get/get_single_resource_test.go, app/kumactl/cmd/root.go, app/kumactl/cmd/root_test.go, app/kumactl/pkg/cmd/root_context.go, pkg/test/kumactl/context.go
This is an improved version of #4257 - instead of adding the auth plugin we make the tests independent of the contents of `~/.kuma/config` which is a better approach.
* Fix tests failing on user machine by adding in-memory config to test so that they are independent of what resides on disk
Fix #XXX
=> fix: add in-memory config to tests

.kube-linter.yaml, mk/check.mk, mk/dev.mk
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Support kube-linter tools to analyzes Kubernetes YAML files and Helm charts and checks them against various best practices.
* [Fix ...]
Fix #4266
=> feature: support kube-linter tools to analyzes Kubernetes YAML files

pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go
I noticed that sometimes on scaling zone ingress from 1 to 5 instances for a short period of time (~2s) we can see a problem with the traffic.
Fix #4251
No extra docs.
=> fix(kuma-cp): graceful start of many ZoneIngresses

test/e2e_env/kubernetes/graceful/graceful.go, test/e2e_env/kubernetes/kubernetes_suite_test.go
In K8S tests, the main process can finish first and break port-forward.
I also saw one problem with the graceful test that it was stuck on the request. We should have an explicit timeout (it's infinite by default)
The SynchronizedAfterSuite is not needed in Multizone and Universal env, because it has DeferCleanup which acts like SynchronizedAfterSuite
No docs.
=> test(e2e): fix broken port-forward

tools/releases/distros.sh
Download arch-specific envoy version
* [add arch to envoy binary url]
Fix #XXX
=> fix(*): release should download arch specific envoy binary

test/e2e_env/kubernetes/metrics/applications_metrics.go, test/e2e_env/universal/metrics/applications_metrics.go
Changed way how create `host:port` to support ipv6.
* [changed string concatenation to `JontHostPort`]
Fix #XXX
=> fix(*): added join host port to support ipv6

test/framework/deployments/testserver/kubernetes.go, test/framework/setup.go
Half of the vCPU for the test server is too much if we are running many of them in parallel. Removing a namespace with pods takes time, I suspect we are running into resources limits.
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
> Note: If you specify a limit for a resource, but do not specify any request, and no admission-time mechanism has applied a default request for that resource, then Kubernetes copies the limit you specified and uses it as the requested value for the resource.
No issues reported, flaky test on master.
~- [ ] Add `backport-to-stable` label if …
=> test(e2e): lower resources limits for test servers

mk/docker.mk
Sometimes we might need to pass more build args for docker image if we have parametrized more elements in `Dockerfile`.
* [allow to pass more args for build script]
Fix #XXX
=> chore(*): allow to pass more build args for docker image

.mergify.yml
=> chore(*): update mergify backport branch

pkg/core/xds/metadata_test.go, pkg/xds/server/callbacks/dataplane_status_tracker_test.go
We don't want to validate KumaDpVersion.KumaCpCompatible
as compatibility checks are currently checked in insights
n/a
n/a
=> fix(tests): don't check version comp. in dp status

pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/injector_test.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.31.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.31.input.yaml
When some container patches are annotated, but don't exist,
we were silently failing, which caused annotations being completely
removed. Now we are logging error, that patch doesn't exist,
but not failing the whole injection
n/a
Fix https://github.com/kumahq/kuma/issues/4356
=> fix: container patches annotated but non-existent

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
Or should `MeshGatewayInstance` have a `.mesh` field like `MeshGateway`/`MeshGatewayRoute`? 
Since it's namespaced though, it will need to respect the Namespace annotation either way.
=> fix(gateway): use MeshGatewayInstance mesh annotation when matching

pkg/core/bootstrap/bootstrap.go, pkg/envoy/admin/kds_client.go, pkg/envoy/admin/kds_client_test.go
Trim namespace suffix before making a `/config_dump` request if Global CP is on Kubernetes
* trim namespace suffix
Fix https://github.com/kumahq/kuma/issues/4357
=> fix(kuma-cp): '/config_dump' request if Global CP is on Kubernetes

.github/workflows/check.yaml
See [the GH docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#merge-message-for-a-squash-merge) for more info. We have "Default to PR title for squash merge commits" enabled.
=> feat(.github): only check PR titles for commit format

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/logging/loki/loki.yaml, app/kumactl/data/install/k8s/logging/namespace.yaml, app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml, app/kumactl/data/install/k8s/metrics/namespace.yaml, app/kumactl/data/install/k8s/metrics/prometheus/server.yaml, app/kumactl/data/install/k8s/tracing/namespace.yaml
This was causing problems as prometheus doesn't get the sidecar
fix #4410
=> fix(kumactl): define namespace only once in install obs

pkg/config/app/kuma-cp/config.go, pkg/config/dns-server/config.go, pkg/core/resources/apis/mesh/gateway_validator.go, pkg/core/resources/apis/mesh/gateway_validator_test.go, pkg/dns/vips_allocator.go, pkg/dns/vips_allocator_test.go, pkg/plugins/runtime/k8s/plugin.go, pkg/plugins/runtime/universal/plugin.go
Use `internal.<gateway-name>.<mesh-of-gateway-name>.mesh`.
=> feat(gateway): auto generate hostname for crossMesh listeners

pkg/dns/vips_allocator.go, pkg/plugins/runtime/k8s/controllers/configmap_controller.go
These logs are confusing in my opinion.
Log says `updating VIPs`, but we are really reconciling VIPs, it does not mean that we are making any change.
`VIPs updated` suggest that VIPs were updated, but that might not be the case if nothing has changed.
Processes like watchdogs, reconcilers etc. are executed periodically or on some action, but very often they don't change the state of the system. IMHO we should log the activity on V1 to reduce the noise and we should log the actual action on V0.
Change of state action is already logged in `vips_allocator`.
=> chore(kuma-cp): change config map reconciler log level

app/kuma-dp/cmd/run.go, app/kuma-dp/pkg/dataplane/envoy/envoy.go, app/kuma-dp/pkg/dataplane/envoy/envoy_test.go, docs/generated/cmd/kuma-dp/kuma-dp_run.md, pkg/config/app/kuma-dp/config.go, pkg/config/app/kuma-dp/config_test.go, pkg/config/app/kuma-dp/testdata/valid-config.input.yaml, pkg/plugins/runtime/k8s/containers/factory.go, pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.30.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.30.input.yaml
Expose Envoy log level. I did not want to introduce meaningless log levels to kuma-dp itself, so it's a separate flag.
On Kubernetes, you can customize it with annotation `kuma.io/envoy-log-level`.
If you want to customize it on all envoys, you can either use `KUMA_RUNTIME_KUBERNETES_INJECTOR_SIDECAR_CONTAINER_ENV_VARS` or ContainerPatch.
Fix #1820
=> feat(kuma-cp): customize envoy log level

UPGRADE.md
Update UPGRADE.md file
* [Fix ...]
Fix #XXX
=> docs(*): update UPGRADE.md with timeouts

deployments/charts/kuma/templates/cp-deployment.yaml, deployments/charts/kuma/templates/egress-deployment.yaml, deployments/charts/kuma/templates/ingress-deployment.yaml
This PR fixes cp-deployment.yaml replica count when `controlPlane.autoscaling.enabled == true`.
* Added conditional replica count in `cp-deployment.yaml` when `controlPlane.autoscaling.enabled`
* Added conditional replica count in `egress-deployment.yaml` when `egress.autoscaling.enabled`
* Added conditional replica count in `ingress-deployment.yaml` when `ingress.autoscaling.enabled`
=> fix(chart): remove replica from cp-deployment.yaml when autoscaling enabled

mk/envoy.mk, tools/envoy/fetch.sh, tools/releases/distros.sh, tools/releases/docker.sh
=> chore(release-1.6): upgrade Envoy to 1.21.3

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/Chart.yaml, deployments/charts/kuma/README.md
=> chore: upgrade helm chart to v1.6.1

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, deployments/charts/kuma/Chart.yaml, deployments/charts/kuma/README.md
Upgrade help chart to v1.52/0.9.2
n/a
n/a
=> chore: upgrade helm chart to v1.5.2/0.9.2

pkg/plugins/policies/donothingpolicy/k8s/v1alpha1/zz_generated.types.go, pkg/plugins/resources/k8s/caching_converter.go, pkg/plugins/resources/k8s/converter.go, pkg/plugins/resources/k8s/native/api/v1alpha1/zz_generated.mesh.go, pkg/plugins/resources/k8s/native/api/v1alpha1/zz_generated.system.go, pkg/plugins/resources/k8s/native/pkg/model/resources.go, pkg/plugins/resources/k8s/native/test/api/sample/v1alpha1/sample_types_helpers.go, pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, tools/policy-gen/protoc-gen-kumapolicy/crd.go, tools/resource-gen/main.go
Trying to set, for example, a negative weight on a `TrafficRoute` split results in a confusing error for users:
```
error: trafficroutes.kuma.io "route-all-default" could not be patched: Internal error occurred: failed calling webhook "validator.kuma-admission.kuma.io": failed to call webhook: Post "https://kuma-control-plane.kuma-system.svc:443/validate-kuma-io-v1alpha1?timeout=10s": EOF
```
and a panic in the webhook goroutine in `kuma-cp`:
```
2022/06/10 06:42:31 http: panic serving 172.17.0.1:8216: failed to unmarshal *v1alpha1.TrafficRoute: json: cannot unmarshal number -1 into Go value of type uint32
goroutine 1247 [running]:
net/http.(*conn).serve.func1()
/usr/lib/go/src/net/http/server.go:1825 +0xbf
panic({0x1e1dde0, 0xc0013482b0})
/usr/lib/go/src/runtime/panic.go:844 +0x258 …
```
=> fix(kuma-cp): don't panic in webhook if k8s object can't convert to core resource

mk/envoy.mk, tools/releases/distros.sh, tools/releases/docker.sh
Upgrade Envoy to 1.22.1
* [Fix ...]
Fix #XXX
=> chore(*): upgrade Envoy to 1.22.1

.circleci/config.yml
These were required for `release` so we needed to add a circleci filter
=> ci(circleci): fix bad tags glob on dev jobs

pkg/dns/vips_allocator.go, pkg/dns/vips_allocator_test.go, pkg/plugins/runtime/k8s/plugin.go, pkg/plugins/runtime/universal/plugin.go
At the moment, this shouldn't change any behavior. But when `MeshGateway`s are exposed on `.availableServices`, depending on the implementation this (may) break things. In that case, there will be conflicting clusters created for the same service + tags in the same mesh (the other being from `addFromMeshGateway`).
IMO it's more correct either way not to reference a `ZoneIngress` for services in your own zone. The entries created are duplicates.
=> refactor(dns): don't allocate virtual outbound entries from ZoneIngress for own zone

pkg/plugins/runtime/k8s/webhooks/validation.go, pkg/plugins/runtime/k8s/webhooks/validation_test.go
Special treatment for GC service account when checking if an operation on resources is allowed
* [Fix ...]
Fix https://github.com/kumahq/kuma/issues/4434
=> fix(kuma-cp): support GC service account

pkg/plugins/authn/api-server/tokens/ws/server/webservice.go, pkg/plugins/authn/api-server/tokens/ws/ws_test.go
I noticed it when I was rewriting docs.
Not reported.
=> fix(kuma-cp): validation error with user tokens

docs/madr/decisions/003-logging.md
I'd like to standardize a little bit a way how we handle logging in Kuma.
Please post suggestions!
xref #879
=> docs(madr): logging standard

pkg/xds/generator/secrets/generator.go, pkg/xds/secrets/secrets.go, test/e2e_env/kubernetes/gateway/cross-mesh.go
=> fix(kuma-cp): don't fail generation if other mesh CAs are misconfigured

app/kuma-dp/cmd/context.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap_test.go, pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/generator_test.go, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/types/bootstrap_request.go
When CP is deployed on linux VM and DP is on windows VM, there we set `/dev/null` to access log path which crashes Envoy.
=> fix(kuma-dp) access log path on windows when cp is on linux

go.mod, go.sum, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/policy/policy_test.go, test/e2e/gateway/gatewayapi/conformance_test.go
This uses a fork with a change [that's waiting on being merged upstream](https://github.com/kubernetes-sigs/gateway-api/pull/1217).
This way we can ensure we keep passing the tests, except for one recent one that apparently fails which I've marked TODO.
=> build: update gateway-api version to v0.5.0-rc1

pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config-token-path.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.ipv6.golden.yaml, pkg/xds/bootstrap/testdata/generator.metrics-config.kubernetes.golden.yaml
=> chore: remove deprecated Cluster.Http2ProtocolOptions

pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment_suite_test.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment_test.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
The [HTTPRoute docs specify this behavior](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRoute). It's one part of the remaining failing test from #4523
=> fix(gateway): check hostname intersection between HTTPRoute and Gateway listener

pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml, pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config-token-path.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml, pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.ipv6.golden.yaml, pkg/xds/bootstrap/testdata/generator.metrics-config.kubernetes.golden.yaml
Use correct access logging instead using access_log
Fix #2114
=> cleanup(bootstrap): replace deprecated admin_access_log_path

pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment_test.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
Fixed matching logic and use new upstream status `Reason`s.
Part of #4532
=> fix(gateway): hostname intersections, use new RouteReasons

Makefile, app/kuma-dp/cmd/run.go, app/kuma-dp/pkg/dataplane/envoy/bootstrap_file_test.go, app/kuma-dp/pkg/dataplane/envoy/compatibility.go, app/kuma-dp/pkg/dataplane/envoy/compatibility_test.go, app/kuma-dp/pkg/dataplane/envoy/envoy_suite_test.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap_test.go, mk/build.mk, mk/dev.mk, mk/envoy.mk, pkg/test/const.go, pkg/version/compatibility_test.go, pkg/version/version.go, pkg/version/version_test.go, tools/envoy/README.md, tools/envoy/version.sh, tools/releases/distros.sh, tools/releases/docker.sh
- Stop having to update envoy version in many places
- Add test to check that the dp compatibility check works
- Add tests to check that build arguments are set correctly
=> fix(kuma-dp): have envoy version check always work

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, pkg/plugins/runtime/k8s/plugin_gateway.go, tools/releases/dockerfiles/Dockerfile.kuma-dp
Closes #4084. 
* [\>= v1.22 set `net.ipv4.ip_unprivileged_port_start` to `0`](https://github.com/kubernetes/kubernetes/pull/103326) so that all ports are unprivileged
* < v1.22
* build `kuma-dp` using `setcap` to add `cap_net_bind_service` to `envoy`
* add `NET_BIND_SERVICE` capability to gateway container
I've tested as working on GKE.
=> feat(gateway): allow MeshGateway Dataplane Pods to bind privileged ports

pkg/plugins/runtime/k8s/controllers/gatewayapi/common/reconcile.go
We can't use namespace/name as a label value because the character limits are different.
One downside here is that we can no longer look at the label value and
check whether the owner exists without checking all potential owners.
This logic isn't implemented yet, however.
=> fix(gateway): workaround label value max length with hash

test/e2e/gateway/gatewayapi/conformance_test.go
Closes #4532 
Blocked on #4544 and #4545
=> test(gateway): enable Gateway API conformance test HTTPRouteHostnameIntersection

.github/dependabot.yml, .github/workflows/dependabot.yml
This will add dependabot for github actions in .github. This can help with keeping the versions up to date, and providing changelogs for the versions before you merge a PR.
*Adds dependabot for github actions in the .github directory.
N/A (No testing, just made these changes on the GitHub website)
=> chore(dependabot): add dependabot for github actions

pkg/api-server/resource_endpoints.go, pkg/core/resources/access/admin_resource_access.go, pkg/core/resources/access/admin_resource_access_test.go, pkg/core/resources/access/resource_access.go
This enables validators to check both specs.
=> fix(core): validate both old and new objects on Update

pkg/xds/sync/proxy_builder_test.go, pkg/xds/topology/outbound.go
We were plugging in the map of tags from `ExternalService` object to `core_xds.Endpoint` object. Then we enriched `core_xds.Endpoint` with `mesh` tag for internal purposes. Since this map was shared, the end result was that AvailableServices in ZoneIngress were getting `mesh` tags.
I don't believe this can cause any problem in production. However, it caused instability in tests.
No issues were reported.
=> fix(kuma-cp): do not modify external service tags

test/e2e_env/universal/retry/retry.go
Noticed that `e2e_env/universal/retry/retry.go` is failing because of default connection timeout. Curl was using `3 sec` while the default is `5 sec`. Changed to higher value to beat default.
* [Increased curl timeout for retry E2E test]
Fix #XXX
=> fix(*): extended timeout for curl to beat default 5 sec timeout for Retry E2E test

pkg/test/store/postgres/test_container.go, test/e2e_env/universal/auth/dp_auth.go, test/e2e_env/universal/externalservices/externalservices.go, test/e2e_env/universal/healthcheck/panic.go, test/e2e_env/universal/inspect/inspect.go, test/e2e_env/universal/mtls/mtls.go, test/e2e_env/universal/ratelimit/ratelimit.go, test/e2e_env/universal/retry/retry.go, test/framework/deployments/externalservice/universal.go, test/framework/interface.go, test/framework/setup.go, test/framework/universal_app.go, test/framework/universal_cluster.go
- Retry wait on postgres container startup
- Add simpler api for universal e2e external services
- Ensure we destroy all apps after tests
- Fix timeouts on mtls tests
=> fix(e2e): improve external service to bring stability on universal

.github/workflows/helm-release.yaml
Otherwise we still need to crate a "bump helm version" commit.
=> fix(helm): always run Helm version update

.github/workflows/helm-release.yaml
This should have been in #4603 :disappointed: 
This reverts commit 6bd83ed1955bb29168420a45b99547a1d3419dc2.
=> Revert "fix(helm): always run Helm version update (#4604)"

test/e2e/gateway/gatewayapi/gateway_api.go
Looks like the webhook image isn't published for ARM.
=> test(e2e): skip Gateway API tests on ARM

app/kumactl/cmd/install/testdata/install-control-plane.cni-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/values.yaml
Instead of hardcoding registry, we leave it empty so we can infer this from image.global.registry
=> fix(helm): use image.global.registry for imageExperimental

app/cni/pkg/cni/injector_linux.go, pkg/transparentproxy/transparentproxy_experimental.go
Check if ipv6 can be enabled and pass the value to the config
* [Fix failing ipv6 build https://app.circleci.com/pipelines/github/kumahq/kuma/15351/workflows/cb3322ce-4881-40a7-b8f4-1cd7cef2b07f/jobs/185366/parallel-runs/4
No issue created, build failing.
~~- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)~~
~~- [ ] Unit tests~~
~~- [ ] E2E tests~~
~~- [ ] Manual testing on Universal~~
~~- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to take when upgrading.~~
~~- [ ] Add `backport-to-stable` label if the code follows our [backporting policy](/CONTRIBUTING.md#backporting)~~
=> fix(cni): check to enable ipv6 flag on transparent proxy engine

test/framework/k8s_cluster.go
Namespaces take a while to delete...
=> test(e2e): print fewer waiting on Namespace to delete logs

tools/releases/changelog/graphql.go, tools/releases/changelog/root.go
The changelog script was not working properly due to a badly
written graphql query when using `--from-tag`
=> fix(ci): fix tag bug in changelog script

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/prometheus/server.yaml
We have a PVC of 8GB on prom and the data would grow without limit.
This would eventualy cause prometheus to run out of disk space and crash
This limits the data size using a prometheus commandline flag
=> chore(kumactl): add a limit to the prom TSDB size

pkg/core/resources/apis/mesh/external_service_validator.go, pkg/core/resources/apis/mesh/external_service_validator_test.go, pkg/core/resources/apis/system/validators.go, pkg/xds/topology/outbound.go, test/e2e/externalservices/externalservices_multizone_universal.go, test/e2e/zoneegress/externalservices/zoneegress_externalservices_universal.go, test/e2e_env/universal/externalservices/externalservices.go, test/framework/setup.go
* Remove misleading log and return an error
* Validate external service better to eliminate the case when we can fall into this error
* Fix E2E test to not set invalid external service (empty caCert.inline)
Noticed while debugging other things.
- ~[ ] Manual testing on Universal~
- ~[ ] Manual testing on Kubernetes~
=> fix(kuma-cp): external service datasource validation

pkg/api-server/config_ws_test.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/config/xds/config.go, pkg/config/xds/testdata/default-config.golden.yaml, pkg/xds/server/callbacks/dataplane_callbacks.go, pkg/xds/server/callbacks/dataplane_callbacks_test.go, pkg/xds/server/callbacks/dataplane_lifecycle.go, pkg/xds/server/callbacks/dataplane_lifecycle_test.go, pkg/xds/server/callbacks/dataplane_metadata_tracker.go, pkg/xds/server/callbacks/dataplane_status_sink.go, pkg/xds/server/callbacks/dataplane_status_sink_test.go, pkg/xds/server/callbacks/dataplane_sync_tracker.go, pkg/xds/server/v3/components.go
* Changed the status sink to flush when it's started so we can get an info that DP is connected to the CP without status flush interval delay.
* Introduced configuration of deregistration delay with 10s by default.
Fix #4616
- ~[ ] E2E tests~ (no idea how to try to write test with this race)
- ~[ ] Manual testing on Kubernetes~
=> fix: registering dp on reconnect

test/dockerfiles/Dockerfile.universal
Ubuntu 21.04 is no longer maintained (see: https://ubuntu.com/about/release-cycle) and the build is failing with:
```
E: The repository 'http://security.ubuntu.com/ubuntu hirsute-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
I'm updating it to 22.04 which is LTS release supported until 2032.
* Fix kuma-universal image building 
Not reported yet.
~~- [ ] Link to the website [documentation PR](https://github.com/kumahq/kuma-website/pull/XXX)~~
~~- [ ] Unit tests~~
~~- [ ] E2E tests~~
~~- [ ] Manual testing on Universal~~
~~- [ ] Manual testing on Kubernetes~~
~~- [ ] Update [`UPGRADE.md`](/UPGRADE.md) with any steps users will need to …
=> chore: update kuma universal image to ubuntu 22.04

docs/madr/decisions/006-additional-retry-logic.md
Signed-off-by: John Harris <john@johnharris.io>
Create MADR for Additional Retry fields
* [Fix ...]
Fix #4494
=> docs(madr): create MADR for Additional Retry fields

.circleci/config.yml, pkg/api-server/api_server_suite_test.go, pkg/api-server/resource_endpoints_test.go, pkg/test/store/postgres/test_container.go, tools/postgres/Dockerfile
This was because if the server fails to bind we try it again with a different port.
Except that when we do this the metrics are already initialized which causes this issue
Example: https://app.circleci.com/pipelines/gh/kumahq/kuma/15380/workflows/fb9e1ebf-1388-4df1-a034-255a86800d25/jobs/186308
Error was: Sometimes tests would fail with: "duplicate metrics collector registration attempted"
Add a uniqueId to make each image different, this was causing flakiness as test-container
deletes the image that it builds unconditionally during teardown and fails if the image doesn't exist.
In the case of parallel tests it's possible that the same image was used in multiple tests and the second teardown would fail.
Example: https://app.circleci.com/pipelines/github/kumahq/kuma/15434/workflows/07c6c425 …
=> ci(test): fix flaky unit tests

app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
Is there a reason to keep them?
=> fix(kuma-cp): don't deploy Pod/Service webhooks in global

pkg/plugins/runtime/k8s/containers/factory.go, pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go
- The error was sometimes confusing and presence of the meshName would help
- Only use meshName whenever is possible to simplify code and
avoiding unecessary lookups
Each of these sections need to be filled by the author when opening the PR.
If something doesn't apply please check the box and add a justification after the `--`
=> chore: mention mesh name in gateway instance status

app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-tracing.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-tracing.overrides.golden.yaml, app/kumactl/data/install/k8s-deprecated/tracing/jaeger/all-in-one-template.yaml, app/kumactl/data/install/k8s/tracing/jaeger/all-in-one-template.yaml, deployments/charts/kuma/templates/egress-deployment.yaml, deployments/charts/kuma/templates/ingress-deployment.yaml
`kuma.egressLabels` and `kuma.ingressLabels` already include
`kuma.selectorLabels`. The first `Service` `selector` was being
overwritten anyway.
Blocking https://github.com/kumahq/kuma/pull/4671 but I think this should be an explicit PR.
=> chore(helm): remove duplicate keys in resources

go.mod, go.sum
Dependabot is incapable of creating this PR for some reason...
=> build(go.mod): update containerd to v1.6.6

deployments/charts/kuma/templates/cni-daemonset.yaml
=> fix(helm): add containersecuritycontext to CNI daemonset

test/framework/k8s_cluster.go
See [this CircleCI run](https://app.circleci.com/pipelines/github/kumahq/kuma/15528/workflows/4cd8a03f-f04a-4a52-836c-e88f272a5c19/jobs/190865)
=> test(e2e): don't panic if an `Install` fails before `Kuma` is called

tools/releases/distros.sh
We were including the `./` dir in the distro tgz files, which was causing problems. This tars up the appropriate dirs now.
Results like this:
```
% tar -tzf .//build/artifacts-darwin-amd64/kuma-0.0.0-preview.2e025c981-darwin-amd64.tar.gz
kuma-0.0.0-preview.2e025c981/
kuma-0.0.0-preview.2e025c981/LICENSE
kuma-0.0.0-preview.2e025c981/bin/
kuma-0.0.0-preview.2e025c981/README
kuma-0.0.0-preview.2e025c981/NOTICE
kuma-0.0.0-preview.2e025c981/NOTICE-kumactl
kuma-0.0.0-preview.2e025c981/conf/
kuma-0.0.0-preview.2e025c981/conf/kuma-cp.conf.yml
kuma-0.0.0-preview.2e025c981/bin/kuma-cp
kuma-0.0.0-preview.2e025c981/bin/kumactl
kuma-0.0.0-preview.2e025c981/bin/kuma-prometheus-sd
kuma-0.0.0-preview.2e025c981/bin/envoy …
```
=> fix(kuma-cp): don't tar up ./

app/cni/pkg/cni/injector_linux.go, go.mod, go.sum, pkg/transparentproxy/transparentproxy_experimental.go
Update kuma-net to 0.4.2 to fix failing test with experimental CNI
=> fix: update kuma-net to fix failing cni test

.circleci/config.yml, test/e2e_env/universal/matching/matching.go, test/e2e_env/universal/mtls/mtls.go, test/e2e_env/universal/ratelimit/ratelimit.go
- Use flakeAttempt and reference an issue to fix tests for good
- Don't run ci for test/e2e-universal on k8s clusters
=> ci(e2e): remove test/e2e-universal flakiness

pkg/xds/envoy/listeners/v3/dns_configurer.go, pkg/xds/envoy/listeners/v3/dns_configurer_test.go, pkg/xds/generator/testdata/dns/1-envoy-config.golden.yaml, pkg/xds/generator/testdata/dns/3-envoy-config.golden.yaml
=> chore(xds): don't set deprecated dns_resolver_config

app/kuma-dp/pkg/dataplane/metrics/server.go, test/e2e_env/universal/observability/applications_metrics.go
`kuma-dp` scrapes metrics from the applications, aggregates them, and returns. Unfortunately we were not setting correct `content-type` and some applications could file while scraping. Added setting of content type based on https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#basic-info. Also, added passing of prometheus requests header to the application. based on the code (https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L772)
~- [ ] Link to docs PR or issue~ --
~- [ ] Link to UI issue or PR~ --
~- [ ] Unit Tests~ --
~- [ ] Do you need to update [`UPGRADE.md`](/UPGRADE.md)?~ --
~- [ ] Does it need to be backported according to the [backporting policy](/CONTRIBUTING.md#backporting)?~ --
=> fix(kuma-dp): set prometheus content-type when returning metrics

test/framework/deployments/externalservice/universal.go, test/framework/envoy_admin/tunnel/universal.go, test/framework/ssh/ssh.go, test/framework/universal_app.go, test/framework/universal_cluster.go, test/framework/universal_controlplane.go
Right now, all the logs from universal containers are logged on stdout. This makes debugging tests very hard, because you cannot see logs from one container. Parallelization only makes this problem more difficult.
This PR introduces better logging for universal containers.
1) Redirecting to stdout/stderr of containers
So we could use `docker logs kuma-cp_hash` and see logs of kuma cp.
I haven't found a way to implement this, since it's not a main process in the container
2) Logging to a file in the container
I tried to use `tee` to have logs both visible in tests as well as in the file in the container.
`tee` messes up with stderr+stdout. If think it redirects stderr to stdout by default. Bunch of tests were failing because of that.
Also, when container is gone, logs are also gone.
3) …
=> test(e2e): universal logs

app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap_test.go, go.mod, go.sum, pkg/config/app/kuma-dp/config.go, pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/parameters.go, pkg/xds/bootstrap/server_test.go, pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/testdata/bootstrap.gateway.golden.yaml, pkg/xds/bootstrap/types/bootstrap_request.go
As suggested by [the Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge)
This PR checks both Kubernetes limits (via Downward API) directly as well as `cgroup` limits if they're available.
=> feat(gateway): configure overload_manager based on max memory

app/kuma-dp/pkg/dataplane/envoy/memory_limit_darwin.go, app/kuma-dp/pkg/dataplane/envoy/memory_limit_linux.go, app/kuma-dp/pkg/dataplane/envoy/memory_limit_windows.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go
cgroups does not work on MacOS (and Windows).
=> feat(kuma-dp): detect memory limit only on linux

pkg/core/tokens/meshed_signing_key_accessor.go, pkg/core/tokens/public_key_secret_signing_key_accessor.go, pkg/core/tokens/revocations.go, pkg/core/tokens/signing_key.go, pkg/core/tokens/signing_key_accessor.go, pkg/tokens/builtin/components.go, pkg/xds/auth/callbacks.go, pkg/xds/auth/callbacks_test.go, pkg/xds/auth/components/components.go, pkg/xds/auth/k8s/authenticator.go, test/e2e_env/universal/auth/dp_auth.go, test/framework/dataplane.go
Authenticate DP on every DiscoveryRequest.
It is done so we can throw out of mesh DPPs with an expired or revoked token.
On Kubernetes, we don't have expiration or revocation and auth is expensive, therefore we need to have a cache for SATs.
Kubernetes - not affected.
Universal - worst-case scenario (multiple DiscoveryRequests / s):
* GET request for revocation list
* GET request for signing key
* parsing token - should be lightweight
Both requests are cached with ReadOnlyResourceManager so the max overhead is an extra 2 req/s.
DPP with an expired or revoked tokens will be disconnected on the next DiscoveryRequest which means that if there are no changes in the config, the DPP can stay in the mesh for some time.
If we want to be reactive about this, we need some other mechanism to trigger …
=> feat(kuma-cp): authenticate DP every time

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/grafana/kuma-dataplane.json, app/kumactl/data/install/k8s/metrics/grafana/kuma-gateway.json, app/kumactl/data/install/k8s/metrics/grafana/kuma-service-to-service.json, app/kumactl/data/install/k8s/metrics/grafana/kuma-service.json, app/kumactl/data/install/k8s/metrics/prometheus/server.yaml
- Have no panels collapsed by default
- Fix scraping to get back `pod` and `namespace` label of Kuma scraping
- Don't list gateways in service dashboards
- Show envoy_cluster_name in gateway status code dashboards
=> fix(kumactl): fixes to dashboards

go.mod, pkg/kds/context/context_test.go, pkg/test/matchers/proto.go, pkg/util/proto/any_test.go
Use go-cmp for getting better output when protobuf matcher fails
Fix #2583
=> ci(pkg/test): better error on protobuf test matchers

mk/k3d.mk
`k3d/load` had a race when running with `-j`. If you run `images` and `k3d/load/images` in parallel, you may not have images built yet.
This PR forces order to build images first and then load them
=> chore: remove race on k3d/load with parallelization

mk/k3d.mk
We should wait for default mesh in k3d/deploy/kuma. Otherwise if we execute k3d/deploy/demo immediately we may fail, because there is no mesh in Kuma.
Ideally, this should be a check in `/ready` endpoint, but that's a bigger issue
https://github.com/kumahq/kuma/issues/1001
We cannot add this check currently to `/ready` because creating default mesh triggers the webhook to CP and if CP is not ready then the webhook will fail. Chicken and egg problem.
=> chore: wait for default mesh in k3d/deploy/kuma

test/e2e_env/universal/auth/dp_auth.go
=> test(e2e): fix flaky dp auth revocation

.github/workflows/helm-release.yaml
The app is installed on `kumahq/charts` and the secrets are available on this repo. This makes the workflow a little harder to test since you can't just fork `kumahq/kuma` and `kumahq/charts` and run it but creating an app is quite straightforward.
=> ci(helm): use GitHub app to release charts

pkg/plugins/runtime/k8s/controllers/namespace_controller.go, pkg/plugins/runtime/k8s/controllers/namespace_controller_test.go
Removed check if the value of annotation `kuma.io/sidecar-injection` is `enabled`, now we check if the annotation is present.
=> fix(kuma-cp): check if kuma annotation or label is set but ignore value 

app/kuma-dp/pkg/dataplane/accesslogs/server.go, app/kuma-dp/pkg/dataplane/accesslogs/server_windows.go
=> fix(kuma-dp): fix multi OS build of accesslogs

pkg/plugins/runtime/k8s/controllers/pod_converter.go, pkg/plugins/runtime/k8s/controllers/pod_converter_test.go, pkg/plugins/runtime/k8s/controllers/testdata/20.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/20.pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/20.replicasets-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/20.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/21.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/21.pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/21.services-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/22.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/22.pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/22.replicasets-for-pod.yaml, pkg/plugins/runtime/k8s/controllers/testdata/22.services-for-pod.yaml, pkg/plugins/runtime/k8s/plugin.go
Implements https://github.com/kumahq/kuma/issues/4052
=> feat(kuma-cp): identify gateway service by deployment

.circleci/config.yml, CONTRIBUTING.md, tools/ci/has_label.sh
This PR gives the contributor an ability to run the whole matrix test suite by adding "ci/run-full-matrix" label to the PR.
The master branch is broken now because of https://github.com/kumahq/kuma/pull/4769 but you can see from the [history](https://app.circleci.com/pipelines/github/kumahq/kuma?branch=pull%2F4770) that all targets were triggered.
=> feat(ci): add a special label to run full test matrix

test/e2e_env/multizone/localityawarelb/locality_multizone_hybrid.go
I think 15s might not be enough in the end on the first step, because we do not check before if the external service is available through egress.
=> test(e2e): increase timeout in localityawarelb test

pkg/plugins/runtime/gateway/cluster_generator.go, pkg/plugins/runtime/gateway/testdata/http/19-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/cross-mesh-gateway.yaml, pkg/plugins/runtime/gateway/testdata/http/external-service-with-timeout-no-egress.yaml, pkg/plugins/runtime/gateway/testdata/https/19-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/cross-mesh-gateway.yaml, pkg/plugins/runtime/gateway/testdata/https/external-service-with-timeout-no-egress.yaml, pkg/xds/envoy/clusters/configurers.go, pkg/xds/envoy/clusters/v3/http2_configurer.go
Part of https://github.com/kumahq/kuma/issues/4692
=> feat(gateway): set cluster HTTP2 stream and connection window size

pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/config/xds/config.go, pkg/xds/bootstrap/components.go, pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/generator_test.go, pkg/xds/bootstrap/server_test.go, pkg/xds/bootstrap/template_v3.go, pkg/xds/bootstrap/template_v3_test.go, pkg/xds/bootstrap/testdata/bootstrap.gateway.golden.yaml, pkg/xds/bootstrap/testdata/generator.gateway.golden.yaml
Blocked on https://github.com/kumahq/kuma/pull/4755
From the example in [best practices](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge).
We also have:
> The connection limit is recommended to be less than half of the system’s file descriptor limit, to account for upstream connections, files, and other usage of file descriptors.
so we could theoretically try to get this limit and derive a connection limit but the value in `/proc/sys/fs/file-max` seems unreliably high, at least on my machine/`minikube`.
Or otherwise make it customizable now rather than later.
=> feat(gateway): set global_downstream_max_connections to 50000

test/e2e_env/multizone/healthcheck/healthcheck.go
We should use `TriggerDeleteNamespace` to not waste time waiting for the namespace to be deleted.
=> test(e2e): trigger delete namespace in hc multizone

test/e2e/zoneegress/externalservices/e2e_suite_test.go, test/e2e/zoneegress/externalservices/zoneegress_externalservices_hybrid.go
Unfortunately, this one cannot be migrated to e2e_env because it relies on the absence of zone egress.
However, the current test is not optimal because of `BeforeEach`.
=> test(e2e): rewrite zoneegress hybrid tests

.circleci/config.yml, mk/docker.mk, mk/e2e.new.mk
Save ~1m30s (on each E2E job) by reusing images that were built in the `build` step.
=> test(e2e): reuse images

test/e2e_env/kubernetes/gateway/gatewayapi.go
Skip does not work in this place
=> test(e2e): fix skip of gateway api for arm and ipv6

.circleci/config.yml, mk/e2e.new.mk, mk/k3d.mk, test/e2e_env/multizone/multizone_suite_test.go, test/framework/config.go, test/framework/k8s_cluster.go, test/k3d/calico.yaml, test/k3d/calico.yaml.kubelint-excluded
A PR showing that our CNI works with calico CNI, it is not meant to be a replacement for flannel. The idea here is to show how I will generally look which means:
- a new target to start k3d with calico
- some minor adjustments in the e2e config and tests
- some tests (probably taint container ones) will be run twice, once with flannel (the way it's run now) and once with calico (the thing we want to test)
Closes #4648
=> feat(cni): use our cni with calico

pkg/xds/envoy/endpoints/v3/endpoints.go, pkg/xds/envoy/endpoints/v3/endpoints_test.go
I'm not sure how to get into this state by using Kuma. Locality in endpoints is always nil (standalone) or always present (multizone). Maybe some mix of external service with kuma.io/zone tag (missing/present)
Fix #4816
=> fix(kuma-cp): protect sort from empty locality

app/cni/pkg/cni/injector_linux.go
closes #4659 
For some reason [restoreIPTables](https://github.com/kumahq/kuma-net/blob/ca5a91321affe7ab11992af796202f598e12e4d5/iptables/builder/builder.go#L119) returns an empty string when called inside a namespace. This PR uses `RuntimeStdout` to write to the buffer and then we print the contents of that buffer and that contains iptables rules.
Example log output:
```
2022-08-15T09:35:53.029Z        DEBUG   kuma-cni        generated iptables rules        {"pod": "test-server-84cdb5864-g4s5r", "namespace": "kuma-test", "podInfraContainerId": "06b35c8a192828555ce2585b6e2dd51ebacece4c70e2a21287c389636901024d", "ip": "", "containerId": "06b35c8a192828555ce2585b6e2dd51ebacece4c70e2a21287c389636901024d", "args": "K8S_POD_NAME=test-server-84cdb5864-g4s5r;K8S_POD_INFRA_CONTAINER_ID=06b35c8a192 …
```
=> fix(cni): pass buffer to kuma net iptables engine to get logs out

test/e2e/compatibility/e2e_suite_test.go
Pulp (our binary registry) is sometimes flaky.
=> test(e2e): retry tests with pulp

test/e2e/zoneegress/externalservices/e2e_suite_test.go
Created a separate issue to debug this since it's quite difficult. The flake only happens on arm (once every ~10 times)
https://github.com/kumahq/kuma/issues/4822
=> test(e2e): skip legacy zone egress hybrid on arm

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/values.yaml
As merbridge was released with support of Kuma in its CNI plugin
we can switch to use upstream image instead our own
=> chore: switch merbridge image registry to upstream

app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml, app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml, app/kumactl/data/install/k8s/metrics/grafana/kuma-dataplane.json, app/kumactl/data/install/k8s/metrics/grafana/kuma-service-to-service.json
The change here https://github.com/kumahq/kuma/pull/4727 was supposed to expand collapsed panels. However, for some reason a simple change `"collapsed": true` -> `"collapsed": false` does not fix that. The result is that all panels in this row are missing. In this PR:
1) I reverted the changes to `kuma-dataplane` and `kuma-service-to-service`
2) I applied all changes aside from `"collapsed": true` -> `"collapsed": false`
3) I expanded all the panels and re-exported dashboards
4) I replaced the dashboard with the export
=> fix(kuma-cp): collapsed grafana dashboards

pkg/plugins/runtime/gateway/gateway_route_generator.go, pkg/plugins/runtime/gateway/gateway_route_generator_test.go, pkg/plugins/runtime/gateway/generator.go, pkg/plugins/runtime/gateway/match/routes.go, pkg/plugins/runtime/gateway/merge/routes.go, pkg/plugins/runtime/gateway/route/util.go, pkg/plugins/runtime/gateway/testdata/http/http-tcp-route.yaml, pkg/plugins/runtime/gateway/testdata/https/http-tcp-route.yaml
=> fix(gateway): don't create invalid envoy config when routes and listeners don't match

app/kumactl/cmd/install/context/install_control_plane_context.go
Add empty registry so that it can be overwritten in depending projects
=> fix(cni): add empty registry to experimental cni

deployments/charts/kuma/templates/cni-configmap.yaml, deployments/charts/kuma/templates/cni-daemonset.yaml
After the discussion during the testing before the release there was
a suggestion to remove requirement of `experimental.cni=true` to enable
`ebpf` version of `cni`. So to run cni plubin with ebpf (merbridge)
instead of:
```sh
[...]
--set "cni.enabled=true" \
--set "experimental.cni=true" \
--set "experimental.ebpf.enabled=true"
```
you would have to do:
```sh
[...]
--set "cni.enabled=true" \
--set "experimental.ebpf.enabled=true"
```
so as a result:
To install default/old CNI plugin:
```sh
[...]
--set "cni.enabled=true"
```
To install new/experimental CNI:
```sh
[...]
--set "cni.enabled=true" \
--set "experimental.cni=true"
```
To install merbridge CNI with eBPF
```sh
[...]
--set "cni.enabled=true" \
--set "experimental.ebpf.enabled=true"
```
[1]: …
=> refactor(cni): remove one requirement for ebpf

pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/config/plugins/runtime/k8s/config.go, pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml, pkg/plugins/runtime/k8s/plugin.go
=> feat(kuma-cp): add flag to disable taint controller

test/e2e_env/kubernetes/kubernetes_suite_test.go
=> test(e2e): skip KIC tests on arm

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, tools/releases/changelog/root.go
This was not well explained and therefore not followed.
This change adds:
- An entry in the PR template to remind people and reviewer to maybe add this
- An explanation of how it works in the CONTRIBUTING.md docs
- Change the tool to still add to changelog if there's a `> Changelog:` marker on a by default ignored PR.
=> ci(docs): add more info about `> Changelog:` marker

.github/workflows/update-changelog.yaml
We were not explicitly setting a ref which made the action default to the tag pushed
We now explictly set master
=> fix(ci): checkout master in changelog auto update action

.github/PULL_REQUEST_TEMPLATE.md
The links now don't work when viewing the markdown file but do when viewed in PRs. I couldn't find another way to express these links.
Observe:
=> fix(.github): links in PR template

pkg/gc/collector.go, pkg/gc/collector_test.go, pkg/gc/components.go, pkg/gc/finalizer.go, pkg/gc/finalizer_test.go
- Always provide ticker as a parameter to both finalizer and gc
- Use the time of the ticker instead of `core.Now()`
- Rewrite tests to create synthetic ticks
- Improve logging
Motivation:
- Tests would have to rely mutexes and some would expose a race because
of the shared global variable. .e.g: https://app.circleci.com/pipelines/gh/kumahq/kuma/16160/workflows/e5332335-a44e-451f-8942-51a8909156bf/jobs/213638
- We can write very precise tests as we trigger the ticks ourselves
- Not relying on global vars is always an improvement
=> chore(pkg/gc): don't rely on core.Now var for time

pkg/plugins/runtime/k8s/controllers/service_controller.go, pkg/plugins/runtime/k8s/metadata/annotations.go
Nginx seems to only support `nginx.ingress.kubernetes.io/service-upstream`. This proposes setting it unchecked but I suppose we could try to discover if the user is using nginx.
=> feat(gateway): add service-upstream annotation for delegated nginx

test/e2e/gateway/gatewayapi/conformance_test.go
Apparently this wasn't solved by #4871 
=> test(e2e): disable flaky Gateway API conformance test

pkg/plugins/policies/donothingpolicy/api/v1alpha1/schema.yaml, tools/policy-gen/crd-extract-openapi.sh
This is the best you can do to express a constant with OpenAPI apparently.
=> build(generate): set OpenAPI .type property in policy schemas

pkg/plugins/runtime/k8s/controllers/gatewayapi/common/reconcile.go
There's no reason these shouldn't be deterministic and predictable.
=> refactor(gatewayapi): don't use GenerateName for generated Kuma resources

pkg/test/store/postgres/test_container.go
Might [this be the reason](https://pkg.go.dev/math/rand#pkg-overview) we still see [flakiness in the postgres suite](https://app.circleci.com/pipelines/github/kumahq/kuma/16207/workflows/124126f7-9a65-4df6-8a49-f85b1ed7fdbc/jobs/215132/tests) after https://github.com/kumahq/kuma/pull/4668?
=> ci: make postgres container ID non-deterministic

pkg/core/plugins/interfaces.go, pkg/core/plugins/registry.go, pkg/core/xds/matched_policies.go, pkg/core/xds/matched_policies_test.go, pkg/xds/server/v3/reconcile.go, pkg/xds/sync/dataplane_proxy_builder.go
Rework the way policy plugins work to be able to handle policy matching in the plugin
=> feat(policy): add interfaces for policy plugins

pkg/xds/server/v3/reconcile.go
There was a change of return type that the PR wasn't udpated to
=> chore: fix bad merge of not updated branch

pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, test/e2e/gateway/gatewayapi/conformance_test.go
This should fix the flakiness.
=> fix(gatewayapi): reconcile Gateways and HTTPRoutes on ReferenceGrant changes

test/e2e_env/kubernetes/kic/kong_ingress.go, test/framework/deployments/kic/deployment.go, test/framework/deployments/kic/kubernetes.go
There's no need to test from outside the cluster here, just outside the mesh. This should fix [some flakes](https://app.circleci.com/pipelines/github/kumahq/kuma/16284/workflows/c617e3a3-61fd-46c5-87a5-0018ae512a63/jobs/217809/steps).
=> test(e2e): use ClusterIP instead of NodePort for KIC tests

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-experimental-enabled.golden.yaml, deployments/charts/kuma/templates/cni-daemonset.yaml
kubectl warns on apply with:
```
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
```
=> chore(helm): remove unused `critical-pod` annotation

mk/generate.mk
Removes the upgrade/gui command because we now have a GitHub Actions workflow that automatically create update PRs.
See https://github.com/kumahq/kuma-gui/issues/367.
Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>
=> chore: removes update/gui command

pkg/api-server/inspect_endpoints_test.go, pkg/api-server/inspect_envoy_admin_endpoints.go
content-type of XDS inspect endpoints was missing which caused an unreadable GUI panel.
=> fix(kuma-cp): return content type of inspect endpoints

pkg/core/xds/types.go, pkg/plugins/runtime/gateway/generator.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/generator/outbound_proxy_generator_test.go, pkg/xds/sync/dataplane_proxy_builder.go, pkg/xds/topology/outbound.go, pkg/xds/topology/outbound_test.go
This PR removes rebuilding endpoint map in `DataplaneProxyBuilder`.
We already compute endpoint map for all data plane proxy in the mesh and cache it in `MeshContext`.
However, we were rebuilding the map in `DataplaneProxyBuilder`, because if we had no zone egress we decided if we want to include external service endpoints based on traffic permission. I changed the logic to only compute external services endpoint for each data plane proxy and share the endpoint map for the rest of services.
This saves a significant amount of CPU (2-3x when benchmarking with in-memory storage and mock Envoys)
Before:
After:
Fix #2989
=> perf(kuma-cp): avoid rebuilding endpoint map

.circleci/config.yml
For some reason the same executor can return different values for `{{ arch }}` this would make cache missed in some places.
We remove this as the info in already in the executor-name part of the cache key
=> fix(ci): remove `{{ arch }}` from circleci cache key

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, deployments/charts/kuma/templates/cp-deployment.yaml
Because there is no prioritization of probe requests, under heavy load, CP can struggle to answer on probe endpoint within the default timeout of 1s. This can result in CP being killed, recreated, and killed again.
=> chore(kuma-cp): adjust timeout in cp probes

UPGRADE.md, app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.values.yaml, deployments/charts/README.md, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/_helpers.tpl, deployments/charts/kuma/templates/cni-daemonset.yaml, deployments/charts/kuma/templates/cp-deployment.yaml, deployments/charts/kuma/templates/egress-deployment.yaml, deployments/charts/kuma/templates/ingress-deployment.yaml, deployments/charts/kuma/values.yaml
- Deprecated `annotations` everywhere in favour of `podAnnotations`
- Add test to validate all `annotations` values
- Add `cni.podAnnotations`
- Add README for helm chart tests
Fix #4935
Co-authored-by: Deepak Mohandas <deepak.mohandas@konghq.com>
=> fix(helm): use `podAnnotations` everywhere possible

test/e2e_env/kubernetes/kubernetes_suite_test.go
=> test(e2e_env): enable experimental transparent proxy v2 on k8s

pkg/plugins/ca/builtin/manager.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/common/reconcile.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/mesh_controller.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller_test.go, pkg/plugins/runtime/k8s/controllers/pod_status_controller.go, pkg/plugins/runtime/k8s/plugin.go
As a follow-up of https://github.com/kumahq/kuma/pull/4964#discussion_r965701767 and conversation with @michaelbeaumont offline.
I went through all controllers and added missing logs for significant events that change the system state.
=> chore(kuma-cp): improve logging in K8S controllers

tools/releases/version.sh
This is necessary because a commit can begin with 0, which would otherwise result in a non-semver compliant string according to https://semver.org/#spec-item-9.
For example, the [helm package validation fails](https://github.com/kumahq/kuma/actions/runs/3052381378/jobs/4921705942).
I'll update `preview.sh` in `kuma-website` after.
=> fix: add 'v' prefix to preview version format

pkg/plugins/runtime/gateway/route/route_suite_test.go, pkg/plugins/runtime/gateway/route/sorter.go, pkg/plugins/runtime/gateway/route/sorter_test.go
Sorting isn't totally solved but this at least makes it not completely broken.
=> fix(gateway): route sorting

pkg/test/runtime/runtime.go
=> test: set XDSAuthenticator in test runtime

tools/releases/dockerfiles/Dockerfile.kuma-init
Ubuntu 22.04 comes with iptables 1.8.7 which in default (non legacy) mode appears to sometimes crash (tested on GKE), so we manually set the legacy (non iptables->nftables translation) mode
=> chore(kuma-init): use iptables-legacy in kuma-init

.circleci/config.yml
=> fix(ci): remove extra `fi` typo in circleci conf

test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/universal_cluster.go
objects in lists and maps in CP config cannot be configured via env. This Pr adds a possibility to add CP config with YAML file.
=> test(e2e): add possibility to pass YAML cp config

pkg/test/runtime/runtime.go
This reverts commit 29248a659d600b3b93d05fa78e83eebbc0f1b80a.
It was unnecessary and it's better to leave it unset.
=> Revert "test: set XDSAuthenticator in test runtime (#5030)"

pkg/xds/sync/proxy_builder_test.go, pkg/xds/topology/outbound.go
It fixes potential data race (iterating and writing to tags map)
We are adding tag `mesh` during [building remote endpoint map](https://github.com/kumahq/kuma/blob/b9819c1c5b33b3ea64f854053bf8a476cf744d7a/pkg/xds/topology/outbound.go#L66) which is done after [building ingress outbounds](https://github.com/kumahq/kuma/blob/b9819c1c5b33b3ea64f854053bf8a476cf744d7a/pkg/xds/topology/outbound.go#L54), so the tests were valid only by having reference for map with tags inside ingress resources, which was also pointing to the same map inside endpoint map.
xref: https://github.com/kumahq/kuma/pull/4591
=> fix(kuma-cp): deep copy tags when gen. outbounds

pkg/plugins/ca/builtin/manager.go, pkg/plugins/ca/builtin/manager_test.go
Backend name for builtin CA should be lowercase and must be valid dns name. Because we are creating k8s secret from this name, which has strict naming rules.
Fix #5012
=> feat(kuma-cp): added validation for backend name

pkg/clusterid/creator.go, pkg/clusterid/reader.go, pkg/core/runtime/reports/reports.go, pkg/core/tokens/default_signing_key.go, pkg/core/user/user.go, pkg/defaults/components.go, pkg/defaults/envoy_admin_ca.go, pkg/gc/collector.go, pkg/gc/finalizer.go, pkg/hds/authn/callbacks.go, pkg/hds/components.go, pkg/hds/tracker/callbacks.go, pkg/hds/tracker/healthcheck_generator.go, pkg/insights/resyncer.go, pkg/kds/global/components.go, pkg/kds/server/status_sink.go, pkg/kds/store/sync.go, pkg/metrics/store/counter.go, pkg/plugins/authn/api-server/tokens/admin_token_bootstrap.go, pkg/plugins/runtime/gateway/filter_chain_generator.go, pkg/plugins/runtime/universal/plugin.go, pkg/xds/auth/callbacks.go, pkg/xds/generator/outbound_proxy_generator.go, pkg/xds/secrets/secrets.go, pkg/xds/sync/components.go, pkg/xds/sync/dataplane_watchdog_factory.go, pkg/xds/template/proxy_template_resolver.go
Add implicit Control Plane user to background contexts, so we can later retrieve this information in components.
=> feat(kuma-cp): control plane user

pkg/api-server/api_server_suite_test.go, pkg/api-server/customization/customization_suite_test.go, pkg/api-server/server.go, pkg/core/bootstrap/bootstrap.go, pkg/core/runtime/builder.go, pkg/core/runtime/runtime.go, pkg/plugins/authn/api-server/tokens/issuer/issuer.go, pkg/plugins/authn/api-server/tokens/issuer/token.go, pkg/plugins/authn/api-server/tokens/issuer/validator.go, pkg/plugins/authn/api-server/tokens/plugin.go, pkg/test/runtime/runtime.go, pkg/tokens/builtin/issuers.go, pkg/tokens/builtin/zone/issuer.go, pkg/tokens/builtin/zone/token.go, pkg/tokens/builtin/zone/validator.go, pkg/tokens/builtin/zoneingress/issuer.go, pkg/tokens/builtin/zoneingress/token.go, pkg/tokens/builtin/zoneingress/validator.go
Open Issuers to extensions so they can be overridden in projects that are based on Kuma.
Also, expose Claims of tokens.
=> feat(kuma-cp): extensible token issuers

UPGRADE.md, app/kumactl/cmd/generate/generate_zone_token.go, app/kumactl/cmd/generate/generate_zoneingress_token.go, docs/generated/cmd/kumactl/kumactl_generate_zone-ingress-token.md, docs/generated/cmd/kumactl/kumactl_generate_zone-token.md, pkg/core/xds/rules.go, pkg/tokens/builtin/zone/scope.go, pkg/tokens/builtin/zoneingress/zone_validator_adapter.go, pkg/xds/auth/components/components.go, pkg/xds/auth/universal/auth_test.go, pkg/xds/auth/universal/authenticator.go, test/e2e_env/multizone/multizone_suite_test.go, test/framework/interface.go, test/framework/k8s_controlplane.go, test/framework/universal_controlplane.go
Give the capability to use a zone token to authenticate ingress. This will help us drop zone ingress in the future to simplify our security story.
=> feat(kuma-cp): use zone token to auth zone ingress

test/e2e_env/universal/meshaccesslog/meshaccesslog.go
=> test(e2e): mark MeshAccessLog outgoing passthrough test pending

test/framework/k8s_controlplane.go
Fix token generation on k8s. We don't use it in tests in Kuma (we always generate tokens on global universal). That's why it passed CI.
the extra `'` makes this invalid JSON
=> test(e2e): fix generate tokens on k8s

pkg/plugins/policies/matchers/match.go, pkg/plugins/policies/matchers/match_test.go, pkg/plugins/policies/matchers/testdata/match/meshgateways/01.dataplane.yaml, pkg/plugins/policies/matchers/testdata/match/meshgateways/01.golden.yaml, pkg/plugins/policies/matchers/testdata/match/meshgateways/01.policies.yaml, pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go
Really a blocker for #5101 but is worth merging alone since this might break other policy plugins
Note that in particular in the case of `MeshGateway`s, policies match the union of `Dataplane` tags, `MeshGateway` tags and `MeshGateway` listener tags.
`> Changelog: skip`
=> feat: match new policies to MeshGateways

pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go, test/e2e_env/universal/gateway/gateway.go, test/e2e_env/universal/gateway/utils.go, test/e2e_env/universal/meshaccesslog/meshaccesslog.go
=> feat: add MeshGateway support to MeshAccessLog

tools/ci/has_label.sh
CIRCLE_PR_NUMBER wasn't working on PRs not coming from forks which happens for autogenerated PRs like GUI updates
=> ci(.circleci): fix has_label to extract PR number correctly

.github/workflows/pr-comments.yaml
=> fix(.github): use github app in pr-comment action

app/kuma-dp/pkg/dataplane/accesslogs/streamer.go, pkg/plugins/policies/meshaccesslog/plugin/xds/configurer.go, test/e2e_env/universal/meshaccesslog/meshaccesslog.go
For TCP we now always embed log lines as JSON messages for the log streamer. It still supports old style log lines for now.
=> feat: support JSON with MeshAccessLog

pkg/plugins/resources/postgres/store_suite_test.go, pkg/test/store/postgres/test_container.go
=> ci(test): improve reliability of postgres tests

pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
Rationale being that there's no way to even _specify_ `from` rules that would match traffic sent over the inbound listener. `Mesh` doesn't apply, `MeshService` doesn't apply, etc.
Does this make sense to people?
=> chore(MeshAccessLog): don't log on inbound passthrough listeners

test/e2e_env/kubernetes/observability/meshtrace.go, test/e2e_env/multizone/healthcheck/healthcheck.go, test/e2e_env/universal/observability/meshtrace.go
- meshtrace and trace tests were using the same namespace/mesh
- healthcheck test is flaky with curl exit code 52, it's not super clear what happens so rewrote the test in a way that may bubble error more clearly to figure out what's wrong
=> test(e2e): remove flakiness in trace tests, add info in healthcheck

app/kuma-ui/pkg/resources/fs.go
GUI now comes with files that starts with `_`. We need to embed them.
=> chore(gui): embed files that starts underscore

pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
=> fix(gatewayapi): don't NPE if the `GatewayClass` ref doesn't exist

app/kumactl/cmd/install/install_control_plane.go, app/kumactl/cmd/install/install_control_plane_test.go, test/e2e/gateway/gatewayapi/conformance_test.go, test/e2e_env/kubernetes/gateway/gatewayapi.go, test/e2e_env/kubernetes/kubernetes_suite_test.go
This wasn't being set correctly when using actual clusters so `.Capabilities.APIVersions` in templates wasn't working correctly with `kumactl`. Which meant that the `GatewayClass` in the templates wasn't ever created, even if Gateway API CRDs are in the cluster.
This code is more or less directly [inlined from helm](https://github.com/helm/helm/blob/5cb9af4b1b271d11d7a97a71df3ac337dd94ad37/pkg/action/action.go#L239) because these aren't public functions.
=> fix(kumactl): get APIVersions from k8s server

app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshgatewayconfigs.yaml, deployments/charts/kuma/templates/gateway-class.yaml, pkg/plugins/resources/k8s/native/api/v1alpha1/mesh_gateway_config.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion_test.go, test/e2e_env/kubernetes/gateway/cross-mesh.go, test/framework/setup.go
This is an alternative to #4911 for using cross mesh and Gateway API.
- ~[ ] Blocker: adding a `MeshGatewayConfig` to the `install control-plane` resources breaks `kumactl install control-plane | kubectl apply -f -` because `kubectl apply` does not ensure that CRDs are installed first, leading to a race condition with errors like `unknown resource MeshGatewayConfig, ensure CRDs exist`~
I'll handle ensuring this `GatewayClass` exists in another PR
=> feat: add `crossMesh` to `MeshGatewayConfig`

app/kumactl/cmd/install/render_files.go, go.mod, go.sum
Hi !
github.com/Masterminds/sprig is not a go 1.13 module,, this is migrating to github.com/Masterminds/sprig/v3 which is one.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> chore(deps): bump github.com/Masterminds/sprig to 3.2.2

pkg/api-server/inspect_endpoints_test.go, pkg/api-server/testdata/inspect_dataplane.json, pkg/core/xds/rules.go, pkg/core/xds/testdata/rules/06.policy.yaml, pkg/core/xds/testdata/rules/07.policy.yaml, pkg/plugins/policies/matchers/match.go, pkg/plugins/policies/matchers/testdata/match/dataplanepolicies/01.golden.yaml, pkg/plugins/policies/matchers/testdata/match/dataplanepolicies/01.policies.yaml, pkg/plugins/policies/matchers/testdata/match/dataplanepolicies/02.golden.yaml, pkg/plugins/policies/matchers/testdata/match/dataplanepolicies/02.policies.yaml, pkg/plugins/policies/matchers/testdata/match/dataplanepolicies/03.policies.yaml, pkg/plugins/policies/matchers/testdata/match/dataplanepolicies/04.policies.yaml, pkg/plugins/policies/matchers/validators/validator.go, pkg/plugins/policies/matchers/validators/validator_test.go, pkg/plugins/policies/meshaccesslog/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/validator_test.go, test/e2e_env/kubernetes/observability/meshtrace.go, test/e2e_env/universal/observability/meshtrace.go
- disallow setting name with `kind: Mesh` as it's unclear what it will mean
- disallow setting mesh with all kinds as it's unclear what it will mean too
- disallow using `MeshHTTPRoute` the thing is not even defined
- rewrite validator for targetRef to use the same wording everywhere
Fix #5165
=> fix(policies): improve targetRef validation

api/mesh/v1alpha1/dataplane.pb.go, api/mesh/v1alpha1/dataplane.proto, docs/generated/resources/proxy_dataplane.md
Rewrite the data plane proto docs.
One thing that we need to do for proto docs is to repeat Message docs with field docs. For example, `Gateway` message docs were descriptive, but the field `gateway` was not. The problem is that the Message doc is not appearing in the end docs, therefore we need to repeat it.
=> docs: rewrite dataplane proto docs

pkg/xds/sync/components.go, pkg/xds/sync/dataplane_watchdog.go, pkg/xds/sync/dataplane_watchdog_test.go
Admin TLS certs were issued once. We need to reissue it when DP address changes.
Fix #5221
=> fix(kuma-cp): reissue admin tls cert on dp address change

pkg/plugins/runtime/k8s/webhooks/policy_namespace_validator.go, test/e2e_env/kubernetes/meshtrafficpermission/api.go
=> fix(kuma-cp): correct namespace policy validation error message

pkg/plugins/runtime/gateway/cluster_generator.go, test/e2e_env/kubernetes/gateway/gateway.go
=> fix(gateway): skip ExternalService if none match

UPGRADE.md, pkg/xds/envoy/listeners/v3/grpc_stats_configurer.go, pkg/xds/envoy/listeners/v3/grpc_stats_configurer_test.go, pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml, test/e2e_env/universal/grpc/grpc.go, test/e2e_env/universal/universal_suite_test.go, test/framework/setup.go, test/server/cmd/grpc_client.go
It does not make sense to use `statsForAllMethods` at this moment, because it's very common to use dots in grpc package which breaks the StatsD to Prometheus conversion.
There is a feature to replace dots with underscores, but Envoy with this feature is not yet released
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_stats/v3/config.proto#envoy-v3-api-field-extensions-filters-http-grpc-stats-v3-filterconfig-stats-for-all-methods `replace_dots_in_grpc_service_name`.
If someone wants to still use it, they can reenable this with ProxyTemplate.
In the future, we can reenable this when Kuma will upgrade to Envoy with `replace_dots_in_grpc_service_name` feature.
* Disable `statsForAllMethods`
* Add E2E test to check if gRPC client and server emits stats
* Change …
=> fix(kuma-cp): disable statsForAllMethods in grpc stats

test/e2e/gateway/gatewayapi/conformance_test.go, test/e2e_env/kubernetes/kubernetes_suite_test.go
Not sure if this is flaky in CI but it is locally for me.
=> test(e2e): wait longer for Gateway API webhook to be ready

deployments/charts/kuma/templates/post-delete-cleanup-ebpf-job.yaml
Added passing of registry and repository to do not break other projects 
- [X ] Manual Kubernetes Tests --
=> fix(helm): now we provide value to repo of image

mk/e2e.new.mk
*  add `E2E_DEPS_TARGETS` to debug targets so you can plug extra dependency targets for debug e2e too
* set `--proc` to 1 for `debug-universal`. When you run this, there is high change you are debugging e2e test that is not from e2e env, so we can't run this with parallelization.
=> test(e2e): add E2E_DEPS_TARGETS to debug targets

test/e2e_env/universal/meshaccesslog/meshaccesslog.go
=> test(e2e): add `ExternalService` with `MeshAccessLog`

pkg/plugins/policies/meshtrace/plugin/v1alpha1/plugin.go, test/e2e_env/universal/observability/meshtrace.go
=> feat(MeshTrace): `MeshGateway` support 

pkg/xds/generator/outbound_proxy_generator.go, test/e2e_env/kubernetes/gateway/cross-mesh.go, test/e2e_env/kubernetes/gateway/utils.go
If two cross mesh gateways exist in different meshes with the same `kuma.io/service` tag, XDS was broken.
=> fix(MeshGateway): cross-mesh gateways with same service

UPGRADE.md, api/mesh/v1alpha1/dataplane.pb.go, api/mesh/v1alpha1/dataplane.proto, docs/generated/resources/proxy_dataplane.md
Split information about Universal and Kubernetes in UPGRADE docs, fixed default binding address in docs of Dataplane proto
=> docs(proto): fixed default serviceAddress and upgrade docs 

README.md, UPGRADE.md
Added label to `README.md` and `2.x` section to `UPGRADE.md`.
=> docs(release): created section 2.0 and upcoming release

.github/commitlint.config.js
This disallow some common misspell, * and some scopes that are actually types
=> ci(commitlint): restrict some scopes

tools/releases/changelog/main.go, tools/releases/changelog/root.go
When there's multiple PRs with successive updates to the same dependency this will roll them together in the changelog.
=> ci(changelog): add dependabot rollup

pkg/api-server/dataplane_overview_endpoints.go, pkg/api-server/resource_endpoints.go, pkg/api-server/zone_overview_endpoints.go, pkg/api-server/zoneegressoverview_endpoints.go, pkg/api-server/zoneingress_overview_endpoints.go, pkg/core/resources/access/admin_resource_access.go, pkg/core/resources/access/admin_resource_access_test.go, pkg/core/resources/access/resource_access.go
=> fix(access): make validate list aware of the mesh - WIP

test/e2e_env/kubernetes/defaults/defaults.go
`defaults.go` test is flaky.
5s for creating resources may not be enough when many tests are run in parallel (Kube API Server can throttle Kuma)
=> test(e2e): increase eventually timeouts in defaults tests

pkg/core/resources/apis/mesh/gateway_route_validator.go, pkg/core/resources/apis/mesh/gateway_route_validator_test.go, pkg/plugins/runtime/gateway/gateway_route_generator_test.go, pkg/plugins/runtime/gateway/testdata/http/rewrite-prefix-trailing-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/rewrite-prefix-trailing-gateway-route.yaml, test/e2e_env/kubernetes/gateway/mtls.go
This check breaks existing resources so we should remove it. No logic is changed here because the validation was more of a guide rail to prevent misunderstandings around how exactly prefixes are matched.
The trailing slash is essentially ignored and so the new golden file should be identical to the existing `pkg/plugins/runtime/gateway/testdata/http/rewrite-prefix-gateway-route.yaml` golden file.
This adds e2e tests for trailing slashes too.
=> fix(gateway): be more lenient with prefix paths trailing slashes

test/e2e_env/kubernetes/graceful/eviction.go
CI fails https://app.circleci.com/pipelines/github/kumahq/kuma/17304/workflows/2314dfbb-afc2-4ce6-8a06-2a52a3ab3a40/jobs/252269
The checks in the test are not really correct:
1. Create a "bad" Pod
2. Check the DPP is created
3. Check the Pod has an "Evicted" status
4. Check the DPP is removed
It may happen that Pod is evicted so quickly that "Step 2" fails. I think we should check only the final "stable" state of the system. That's why the current PR removes "Step 2".
=> test(e2e): flaky "remove Dataplane of evicted Pod"

UPGRADE.md, pkg/config/loader_test.go, pkg/config/plugins/resources/postgres/config.go, pkg/config/plugins/resources/postgres/config_test.go
=> fix(kuma-cp): add option to disable `sslsni` in universal

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshaccesslogs.yaml, pkg/plugins/policies/meshaccesslog/api/v1alpha1/meshaccesslog.go, pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshaccesslog/k8s/crd/kuma.io_meshaccesslogs.yaml, pkg/plugins/policies/meshaccesslog/plugin/xds/configurer.go
Fixes #5290
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> feat(MeshAccessLog): add OmitEmptyValues to MeshAccessLog format

app/kumactl/cmd/apply/apply.go, app/kumactl/cmd/apply/apply_test.go, app/kumactl/cmd/apply/testdata/apply-many-dataplane-template.golden.yaml, app/kumactl/cmd/apply/testdata/apply-many-dataplane-template.yaml, app/kumactl/cmd/get/get_resource.go, app/kumactl/cmd/get/get_single_resource_test.go, app/kumactl/pkg/output/yaml/printer.go
We were creating a new http client for each resource which was causing an out of fd error when applying a lot of entities at once.
This moves client creation outside of the loop and ensure context is passed in everywhere.
Also fix --dry-run to output a valid set of yaml with `---` separators
=> fix(kumactl): use the same client in `kumactl apply`

test/e2e_env/multizone/healthcheck/healthcheck.go
`should not load balance requests to unhealthy instance` was flaky sometimes.
It turned out that it is a regression that was hidden behind retries that were not removed.
It still works with `KUMA_DEFAULTS_ENABLE_LOCALHOST_INBOUND_CLUSTERS=false` which is not a default setting.
I considered just disabling the test for now, but it's probably still good to run this and see that it's not flaky under "right" setting.
I refactored the test to use `CollectResponsesByInstance` which was used exactly for the case of checking which instances we did hit.
xref #5335
=> test(e2e): run probes test on universal cluster 2

pkg/api-server/dataplane_overview_endpoints.go, pkg/api-server/dataplane_overview_endpoints_test.go
DP overview endpoint can filter by tags but wasn't supporting `:` values
=> fix(api-server): fix tags filter value with `:`

app/kuma-ui/pkg/resources/data/index.html, pkg/api-server/gui_handler.go, pkg/api-server/gui_handler_test.go, pkg/api-server/server.go, pkg/api-server/testdata/gui_other_files.html, pkg/api-server/testdata/gui_with_base_path.html, pkg/api-server/testdata/gui_with_base_path_with_slash.html, pkg/api-server/testdata/gui_with_root_url.html, pkg/api-server/testdata/gui_with_root_url_and_base_path.html, pkg/api-server/testdata/index.html, pkg/api-server/testdata/robots.txt
- remove config.json
- use a templated index.html to dynamically set base paths
- serve index.html whenever the path points to a file that doesn't exist
Fix #5306
=> feat(gui): serve index from all paths without extension

.mergify.yml, CONTRIBUTING.md, labels.yml
This may be causing an invalid config error and isn't used anyway
=> ci: remove unused rule from `.mergify.yml`

pkg/plugins/resources/memory/store.go, pkg/test/store/owner_test_template.go, test/e2e_env/multizone/sync/sync.go
Memory store was not keeping children after owner update.
Production is not affected, because memory store is not used on prod, only in tests and local development.
This Postgres and K8S is NOT affected.
That was the real cause of flaky update policy on KDS.
Default mesh resources created by tr-test mesh (TrafficRoute suite) were there after the test was done. 
Then Global CP was syncing them down to Zone CP and Zone CP was rejecting all TrafficRoute resources because mesh was absent.
```
2022-11-24T13:30:04.268Z	INFO	kds-zone	creating a new resource from upstream	{"type": "CircuitBreaker", "name": "circuit-breaker-all-tr-test", "mesh": "tr-test"}
2022-11-24T13:30:04.270Z	INFO	kds-zone	error during callback received, sending NACK	{"peer-id": "global", "err": "failed to create k8s …
```
=> fix(kuma-cp): memory store keeps children after owner update

tools/releases/changelog/github.go
Use a regexp instead of random splits as it's more robust Fix badly implemented min/max functions
Now the changelog look like: 
```
* chore(deps): bump github.com/onsi/gomega from 1.23.0 to 1.24.1 [#5275](https://github.com/kumahq/kuma/pull/5275) [#5313](https://github.com/kumahq/kuma/pull/5313) @dependabot
* chore(deps): bump github.com/prometheus/client_golang from 1.13.0 to 1.14.0 [#5274](https://github.com/kumahq/kuma/pull/5274) [#5323](https://github.com/kumahq/kuma/pull/5323) @dependabot
* chore(deps): bump github.com/prometheus/prometheus from 0.39.1 to 0.40.2 [#5320](https://github.com/kumahq/kuma/pull/5320) [#5353](https://github.com/kumahq/kuma/pull/5353) @dependabot
```
And changes like: `* chore(deps): update to emicklei/go-restful/v3 v3.10.1 and remove `/tokens` …
=> ci(changelog): fix changelog script for dependabot rollups

tools/releases/docker.sh
=> feat(build): fix prune in docker sh

tools/releases/docker.sh
Just make sure that the path is from the script directory otherwise it will fail
=> feat(build): fix docker publish in enterprise project

pkg/api-server/inspect_endpoints.go, pkg/plugins/runtime/gateway/suite_test.go, pkg/xds/server/v3/snapshot_generator_test.go, pkg/xds/sync/components.go, pkg/xds/sync/dataplane_proxy_builder.go, pkg/xds/sync/dataplane_watchdog.go, pkg/xds/sync/dataplane_watchdog_test.go, pkg/xds/sync/egress_proxy_builder.go, pkg/xds/sync/ingress_proxy_builder.go, pkg/xds/sync/proxy_builder_test.go
We were using a `DataplaneMetadataTracker` in all proxy builders. This was causing issues as the proxy may disconnect while reconciliation is in progress.
We now set the proxy metadata in the DataplaneWatchdog so that it's read once only and nil checked. We therefore protect ourselves against this race
=> fix(xds): don't read metadata in ProxyBuilders

pkg/config/plugins/resources/postgres/config.go, pkg/config/plugins/resources/postgres/config_test.go
This option is apparently relatively new, postgres 14, so we should skip including it unless it's explicitly disabled and let `libpg` handle the default.
=> fix(universal): don't set sslsni option if not disabled

pkg/plugins/runtime/k8s/controllers/configmap_controller.go, pkg/plugins/runtime/k8s/controllers/gateway_converter.go, pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_converter.go, pkg/plugins/runtime/k8s/util/util.go, pkg/plugins/runtime/k8s/util/util_test.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go
This is more in line with the plans for `targetRef` policies.
We need to decide on whether to move to labels everywhere (i.e. Pods/Namespaces)!
=> feat(MeshGatewayInstance): respect `kuma.io/mesh` label

tools/releases/docker.sh
some dockerfiles are still separate (mirror) directory so I need to check for these
=> feat(build): fix docker publish for ubi enterprise

.github/workflows/helm-release.yaml
What I get for moving the command from one step to the previous without testing again...
=> ci(helm): fix run command

.github/workflows/helm-release.yaml
We should run this on PRs but the uploaded charts don't need to stick around more than a day. I also don't think we need any charts longer than 30 days (default is 90).
=> ci(helm): run workflow on PRs, keep chart max of 30 days

test/framework/k8s_cluster.go
I noticed that for no real reason we are checking whether the namespace is deleted every 30s by default. That's quite a lot and can potentially introduce 30s latency on a single test suite.
It only affects non-shared-env E2E tests 
=> test(e2e): lower delete namespace check interval

test/e2e/ownership/e2e_suite_test.go, test/e2e/resilience/e2e_suite_test.go, test/e2e/trafficpermission/kubernetes/e2e_suite_test.go, test/e2e/zoneegress/externalservices/e2e_suite_test.go
Ilya reenabled resilience test which caused a disproportion
This PR tries to fix it
In some other PR I will try to optimise the resilience K8S test, because it's very long and I have an idea how to improve it.
=> test(e2e): redistribute test jobs

docs/madr/decisions/015-retry-policy.md
[Formated version](https://github.com/lobkovilya/kuma/blob/5984660bb1e6c0d0de6f7f90550bbd9412d007fb/docs/madr/decisions/015-retry-policy.md)
=> docs: create MADR for MeshRetry

pkg/intercp/catalog/heartbeat_component_test.go
=> test: fix data race in heatbeat component tests

pkg/intercp/catalog/catalog.go, pkg/intercp/catalog/catalog_test.go
=> feat(kuma-cp): support IPV6 in intercp

mk/e2e.new.mk
`make test/e2e/debug-fast` started as an experiment to shorten the feedback loop when developing E2E tests.
The experiment was a success so we can replace the old `test/e2e/debug` with it.
=> chore: graduate debug-fast target

test/e2e_env/universal/gateway/gateway.go, test/e2e_env/universal/meshaccesslog/meshaccesslog.go, test/e2e_env/universal/observability/meshtrace.go
`gateway-client` wasn't in a mesh so it is not removed at the end of the tests
=> chore(e2e): cleanup gateway client which is not in mesh

pkg/plugins/resources/k8s/store.go, pkg/test/store/store_test_template.go
Fix for filtering name prefix
fix #5512 
=> fix(kuma-cp): filtering of name prefix on K8S

pkg/core/xds/merge.go, pkg/core/xds/merge_test.go, pkg/core/xds/rules.go
=> feat(kuma-cp): append policy slices

pkg/core/tokens/compatibility_test.go, pkg/core/tokens/issuer_test.go, pkg/core/tokens/token.go, pkg/core/tokens/validator.go, pkg/plugins/authn/api-server/tokens/admin_token_bootstrap_test.go, pkg/plugins/authn/api-server/tokens/issuer/token.go, pkg/plugins/authn/api-server/tokens/plugin.go, pkg/plugins/authn/api-server/tokens/ws/ws_test.go, pkg/tokens/builtin/components.go, pkg/tokens/builtin/issuer/token.go, pkg/tokens/builtin/zone/token.go, pkg/tokens/builtin/zoneingress/token.go
Tracking removal with #5519
Fix #4006
- x ] The PR will work for both Linux and Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
=> fix: warn when using deprecated token id

UPGRADE.md, app/kumactl/cmd/generate/generate_dataplane_token.go, app/kumactl/cmd/generate/generate_zoneingress_token.go, app/kumactl/pkg/tokens/client.go, docs/generated/cmd/kumactl/kumactl_generate_dataplane-token.md, docs/generated/cmd/kumactl/kumactl_generate_zone-ingress-token.md, pkg/plugins/authn/api-server/tokens/ws/server/webservice.go, pkg/plugins/authn/api-server/tokens/ws/ws_test.go
The goal is to have users think about tokens a little more
Fix #4001 
=> chore(kumactl): remove default `--valid-for` for tokens

test/e2e_env/kubernetes/graceful/graceful.go, test/e2e_env/kubernetes/meshcircuitbreaker/api.go, test/e2e_env/kubernetes/meshcircuitbreaker/meshcircuitbreaker.go, test/e2e_env/kubernetes/meshtimeout/meshtimeout.go, test/e2e_env/kubernetes/meshtrafficpermission/api.go, test/e2e_env/kubernetes/virtualoutbound/virtualoutbound.go, test/e2e_env/multizone/healthcheck/healthcheck.go, test/e2e_env/multizone/meshtrafficpermission/meshtrafficpermission.go, test/e2e_env/multizone/trafficpermission/trafficpermission.go, test/e2e_env/multizone/trafficroute/trafficroute.go, test/e2e_env/universal/zoneegress/external_services.go, test/framework/resources.go
Unify method to delete all mesh resources for both universal and kubernetes clusters.
Additionally, I replaced usages like this
```
k8s.RunKubectlE(env.Cluster.GetTesting(), env.Cluster.GetKubectlOptions(), "delete", "meshtrafficpermissions", "-A", "--all"),
```
That could create flakiness in other tests because it does not take into account the mesh.
=> chore: unify delete mesh resources

mk/dev.mk, tools/dev/install-dev-tools.sh
=> chore(deps): install dev tools and split if more repos

test/e2e_env/kubernetes/meshcircuitbreaker/meshcircuitbreaker.go
Because of running many tests in parallel on the machine with just a couple of cores, it might happen that those parallel requests were executed sequentially. Delaying processing makes it much easier to trip maxPendingReqeust circuit breaker.
=> test(e2e): delay processing request to trigger connection limit

tools/releases/helm.sh
Less of a chance of getting stuck in an invalid state if the checkout fails.
=> ci(helm): checkout charts repo before doing anything

test/e2e_env/kubernetes/meshcircuitbreaker/api.go, test/e2e_env/kubernetes/meshcircuitbreaker/meshcircuitbreaker.go
There was a name collision between two tests.
=> test(e2e): fix name collision in mesh circuit breaker

pkg/plugins/policies/policies.go, pkg/xds/server/v3/reconcile.go
If someone inherits Kuma and wants to create a new policy and set it in a specific order that wasn't possible. Added function that allows setting order of the policies.
=> fix(kuma-cp): allow to set policies order from others projects

test/e2e_env/kubernetes/graceful/graceful.go, test/framework/deployments/testserver/kubernetes.go
I managed to reproduce this flake on my VM with 14 threads when I run the tests with "--procs 30".
Sometimes the app container is just marked as unhealthy (and killed) because of "quite aggressive" probes.
The test was flakier with time which would indicate that the more test we add - the more flaky the graceful test is.
Because we are running many test in parallel and we hammer the app with requests, it was quite likely that the app would respond on the probe longer than 1 second (default, it was not set) 3 times in a row.
I adjusted the probes to be the same as kuma-sidecar. This helped to pass the test on my machine every single time.
Additionally, I introduced slight delay with every request.
If we still experience fails with this test, I'd move it from `e2e_env` to `e2e` to have a …
=> test(e2e): adjust probes, add delay to graceful test

tools/policy-gen/generator/cmd/helpers.go, tools/policy-gen/generator/pkg/parse/policyconfig.go
This allows for custom implementations of `GetDefault`, which allow for a more flexible schema that can still be merged using the generic policy code. See https://github.com/kumahq/kuma/blob/5aec8ae01195f02ead983e139d988877a87f6c28/pkg/plugins/policies/meshhttproute/api/v1alpha1/zz_generated.helpers.go#L20-L28
=> build: add skipDefault to policy generation

mk/generate.mk
I was confused why my policy files were not updated. It turned out that I had an error, but it was hidden in between logs and the command returned status 0.
=> chore: do not hide errors when generating policy

pkg/core/resources/model/resource.go, pkg/insights/resyncer.go, pkg/insights/resyncer_test.go
We were not filtering types correctly and MeshInsight was showing Secret and ServiceInsight.
Fix #5570
=> fix(kuma-cp): only put policies in MeshInsight

pkg/test/resources/samples/dataplane_samples.go
=> test(e2e): add `kuma.io/protocol: HTTP` to web sample `Dataplane`

pkg/plugins/resources/postgres/store_suite_test.go
CI fail https://app.circleci.com/pipelines/github/kumahq/kuma/18318/workflows/275912cc-d897-486b-a21b-82c71436d81b/jobs/286531
=> fix: wrong assertion in test

app/kumactl/cmd/root.go, go.mod
Logs from klog would go to stdout which was ruining the output of commands like install-control-plane
Fix #5554
=> fix(kumactl): set klog to avoid logs from k8s

pkg/core/resources/model/display_name.go, tools/policy-gen/generator/pkg/parse/policyconfig.go, tools/resource-gen/genutils/util.go
=> build: add ability to set explicit name for policies

test/e2e_env/multizone/localityawarelb/locality_multizone_hybrid.go, test/e2e_env/multizone/trafficroute/trafficroute.go
fail examples: 
* https://app.circleci.com/pipelines/github/kumahq/kuma/18347/workflows/64f6bd25-616a-429c-82f0-01ca12321dbc/jobs/287437/tests
* https://app.circleci.com/pipelines/github/kumahq/kuma/18353/workflows/2e25f459-3f0d-4416-937b-72ca0bb17143/jobs/287750
=> fix: always call 'CollectResponse' inside 'Eventually'

api/mesh/v1alpha1/dataplane_helpers.go, api/mesh/v1alpha1/dataplane_helpers_test.go, pkg/api-server/dataplane_overview_endpoints.go, pkg/api-server/dataplane_overview_endpoints_test.go, pkg/api-server/filtering.go, pkg/core/permissions/matcher.go, pkg/core/policy/dataplane_matcher.go, pkg/core/resources/store/options.go, pkg/plugins/resources/k8s/store.go, pkg/plugins/resources/memory/store.go, pkg/plugins/resources/postgres/store.go, pkg/test/store/store_test_template.go
The api now takes `?name` to filter on subset of the dpp name it also works on subset for tag value
=> feat(api-server): contain matches on name and tags

.circleci/config.yml
This makes sure if we change the go minor version, defined in `.circleci/config.yml`, the cache is refreshed because a different minor means we use a different image, which may not be compatible with the cache.
It seems to have worked here https://github.com/kumahq/kuma/compare/fix/generate_2.0:
- without: https://app.circleci.com/pipelines/github/kumahq/kuma/18480/workflows/9a2b5a02-8335-4542-a326-c1b4ec8ea5b1/jobs/290628
- with: https://app.circleci.com/pipelines/github/kumahq/kuma/18483/workflows/1b5738e0-4fb8-45ec-9537-a14e0ab5caa0/jobs/290689
=> build: use circleci config in cache key

pkg/plugins/policies/donothingpolicy/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshaccesslog/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshratelimit/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshretry/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshtimeout/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshtrace/api/v1alpha1/zz_generated.resource.go, pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/zz_generated.resource.go, tools/policy-gen/generator/cmd/core_resource.go
- Remove unnecessary pkg level var declaration
- Reset pkg level var, once we are done using it
Signed-off-by: AyushSenapati <a.p.senapati008@gmail.com>
=> fix: remove superfluous var usage

pkg/core/resources/manager/cache_test.go
There was some race after adding another test. Added lock for counter increment and made one test wait for the goroutine to be done before finishing the test.
> Changelog skip
=> test(kuma-cp): fix wait for goroutine to be done

test/framework/k8s.go, test/framework/setup.go
Implement https://github.com/gruntwork-io/terratest/pull/1223 to get better error messages quicker.
=> test(e2e): better error when pod is not available

pkg/plugins/policies/meshhttproute/api/v1alpha1/meshhttproute.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshhttproute/k8s/crd/kuma.io_meshhttproutes.yaml
=> fix(MeshHTTPRoute): weight should be a minimum of 0

pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
=> fix(MeshHealthCheck): only add health check at most once to cluster

.github/workflows/auto-merge.yaml
=> ci: include all release branches in auto-merge actions

pkg/core/validators/types.go, pkg/core/validators/types_test.go
See the test before and after, without this fix there is a spurious second `.` in `spec.fields.[2]`.
=> chore: validation error path merging with index/keys

mk/generate.mk, tools/policy-gen/crd-extract-openapi.sh, tools/policy-gen/generator/cmd/k8s_resource.go, tools/policy-gen/generator/cmd/root.go, tools/policy-gen/generator/pkg/parse/policyconfig.go
=> feat(tools): add possibility to generate policy with different gomodule

pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go
This isn't actually a bug because configure only overwrites properties of the cluster but nevertheless.
=> refactor(MeshCircuitBreaker): only configure clusters at most once

test/e2e_env/multizone/multizone_suite_test.go, test/framework/deployments/kic/kubernetes.go, test/framework/deployments/observability/kubernetes.go, test/framework/k8s_cluster.go
also changed `wg.Done` to `defer`. When it was after `Expect`, it would not be called in case of failure and the `BeforeSuite` was stuck forever.
=> test(e2e): use wait for pod available everywhere

test/e2e/compatibility/cp_compatibility_kubernetes_multizone.go, test/e2e/compatibility/dp_compatibility_universal.go, test/framework/deployments/kic/kubernetes.go, test/framework/setup.go
Because compatibility tests are fetching Kuma from the internet, there might be a failure.
For example https://app.circleci.com/pipelines/github/kumahq/kuma/18663/workflows/bb4e95a1-4e22-4839-a3a4-22170672e5e5/jobs/295000
=> test(e2e): retry install kuma in compatibility tests

pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
They were being removed by the assignment of the existing object.
=> fix(MeshGateway): properly apply Service template annotations to existing Service

test/e2e/externalservices/externalservices_kubernetes_without_egress.go, test/framework/interface.go, test/framework/k8s_clusters.go, test/framework/universal_clusters.go
I rewrite the external service without kubernetes
* I removed TLS part, it's tested in `e2e_env` anyways
* I changed `deployments/externalservice` with test server for more robust server
* spotted bug here https://app.circleci.com/pipelines/github/kumahq/kuma/18557/workflows/b446f1d1-c4c1-4bc1-a519-42ca115bafca/jobs/292690 In 116 line the communication should not work, because we set passthrough=false and do not have external service. It worked for majority of time because of XDS reconciliation delay of 1s, whereas the assertion was executed immediately.
This test still needs to live here because we need to test the case where Mesh#egress is set to true, but we don't have egress deployed.
I want to get rid of `k8s_clusters.go` and `universal_clusters.go`, but I don't want to do it in this …
=> test(e2e): rewrite external service without kubernetes

pkg/core/xds/merge.go, pkg/core/xds/merge_test.go
This allows us to move the logic from `MeshHTTPRoute` into `core_xds`
=> feat(policies): allow merging by a complex key

.github/workflows/codeql.yml
I see no reason to run this on every PR. It takes quite a lot of time to execute.
=> chore: run CodeQL only on master

CONTRIBUTING.md
Signed-off-by: Krzysztof Słonka <slonka@users.noreply.github.com>
=> docs: add ci/cd to backporting policy

docs/guides/new-policies.md, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/cluster_mod.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/cluster_mod_test.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/http_filter_mod.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/http_filter_mod_test.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/listener_mod.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/listener_mod_test.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/network_filter_mod.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/network_filter_mod_test.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/suite_test.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/virtual_host_mod.go, pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/virtual_host_test.go, pkg/plugins/policies/policies.go, test/e2e_env/kubernetes/kubernetes_suite_test.go, test/e2e_env/kubernetes/meshproxypatch/meshproxypatch.go, test/e2e_env/universal/meshproxypatch/meshproxypatch.go, test/e2e_env/universal/universal_suite_test.go
MeshProxyPatch implementation. It does not contain the new `jsonPatches` yet. The logic is pretty much the same as `pkg/xds/generator/modifications`
=> feat(kuma-cp): mesh proxy patch xds

go.mod, go.sum, test/framework/deployments/kic/kubernetes.go, test/framework/deployments/observability/kubernetes.go, test/framework/k8s.go, test/framework/k8s_cluster.go, test/framework/setup.go
Reporting reason for failed container is now done in Terratest
- [ x Link to docs PR or issue --
=> chore(deps): bump github.com/gruntwork-io/terratest from 0.41.7 to 0.41.8

pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
`GetDefault` wraps the rules into a struct
=> chore(MeshHTTPRoute): use correct return type of GetDefault

mk/build.mk, mk/check.mk
In the build the stacktraces had a prefix like `home/circleci/.go_workspace` Use `-trimpath` to not have these
=> chore: strip paths from stacktraces

.github/workflows/update-changelog.yaml
=> ci(.github): auto merge and skip tests for changelog changes

app/kuma-dp/pkg/config/validate.go, app/kuma-dp/pkg/config/validate_test.go, app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go
This is overly strict validation is causing more problems than it is solving. We now simply trim the token data
Fix #4567
=> fix(kuma-dp): tolerate endline in token file

pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhealthcheck/plugin/xds/configurer.go, pkg/plugins/runtime/gateway/route/configurers.go, pkg/xds/envoy/listeners/v3/fault_injection_configurer.go, pkg/xds/envoy/listeners/v3/http_inbound_routes_configurer_test.go, pkg/xds/envoy/routes/v3/reset_tags_header_configurer.go, pkg/xds/envoy/routes/v3/tags_header_configurer.go, pkg/xds/envoy/tags/match.go, pkg/xds/generator/egress/external_services_generator.go, pkg/xds/generator/inbound_proxy_generator.go
We add x-kuma-tags to all requests that way things like faultInjection can also apply to health checks
Fix #5718
=> feat(meshhealthcheck): add x-kuma-tags to requests

pkg/core/resources/store/store.go, pkg/core/rest/errors/error_handler.go, pkg/plugins/resources/k8s/store.go, pkg/plugins/resources/k8s/store_test.go, test/e2e_env/kubernetes/inspect/inspect.go
Before we were returning 500 when resource was not in the format `<name>.<namespace>`
We now return a typed error in the store and have the api-server map the error to a 400
Fix #5705
Fix #4985
=> fix(api-server): return 400 on invalid resource name

pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/xds/testutil.go, pkg/test/api_types.go
We have 3 functions that are doing exactly the same thing. Use function from the `pointer` package.
=> fix: replace 'test.PointerOf' with 'pointer.To'

.github/dependabot.yml
the last one was probably merged too late
=> feat(security): update security updates time

tools/releases/changelog/github.go
include chore except chore(deps) and rely on the fact we're using conventional commits
=> ci(CHANGELOG.md): improve excluded patterns for commits

.circleci/config.yml
We need to run arm when full matrix is enabled.
=> chore: run arm on branch when full test matrix is enabled

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshratelimits.yaml, pkg/plugins/policies/meshratelimit/api/v1alpha1/meshratelimit.go, pkg/plugins/policies/meshratelimit/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshratelimit/k8s/crd/kuma.io_meshratelimits.yaml, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/testdata/basic_listener_1.golden.yaml, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/testdata/gateway_basic_routes.golden.yaml, pkg/plugins/policies/meshratelimit/plugin/xds/configurer.go
In Envoy if `Append` is not set then it's true by default:
> **_Append_** 
_Should the value be appended? If true (default), the value is appended to existing values. Otherwise it replaces any existing values. This field is deprecated and please use [append_action](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-field-config-core-v3-headervalueoption-append-action) as replacement._
We already have this behavior in MeshHealthCheck.
=> fix: 'append' in MeshRateLimit should be 'true' by default

.github/workflows/update-insecure-dependencies.yaml
Example PRs:
- https://github.com/slonka/kuma/pull/9
- https://github.com/slonka/kuma/pull/10
Example output:
- https://github.com/slonka/kuma/actions/runs/3956613355/jobs/6776020642
Once the PR is merged a new one won't be created. Also running action multiple times just updates the PR if there are things to update.
=> feat(build): automatically apply security updates for release branches

mk/build.mk
Due to refactor in #5701 the `go test` also gets `-v` which produces verbose and noisy output.
=> chore: revert verbose test output

mk/k3d.mk
There are two modes of importing images in K3D, "direct" and "node-tools".
Because "direct" mode was not reliable enough, K3D team switched back to "node-tools" by default in K3D 5.4.0 that we [recently upgraded to](https://github.com/kumahq/kuma/pull/5518). The problem is that "node-tools" also can fail and in a worse way because it returns exit code 0, so we cannot retry. See https://github.com/k3d-io/k3d/issues/1072
Our CI is really flaky recently because of this. Here is [an example](https://circleci.com/api/v1.1/project/github/kumahq/kuma/304857/output/109/0?file=true&allocation-id=63c91ee2f9823b684de59c4b-0-build%2FOMN51VPD).
This PR switches image import to "direct" once again, but with more retries.
We already use direct mode …
=> chore: use direct mode to import images in k3d

test/e2e/cni/old_cni_race_condition.go, test/framework/dataplane.go
I noticed that we have a flake https://app.circleci.com/pipelines/github/kumahq/kuma/19011/workflows/5523f07e-d7d0-47a1-961e-0a5ecd716a6d/jobs/305878
It's because when we spin up K3D node and load images. It may take more than the 40s (thanks to retries) which the initial CNI delay was set to.
I changed this to 40000s (it does not matter when it comes up).
Additionally, I rewrote this test, because `Install(TestServer)` has retries. We were waiting 6 minutes (!) for test server to fail. I changed the logic so we check that DPP received the config, but test-server container is consistently not ready. This way we do this in ~15s and we save 6 mins.
On top of that, I noticed that we don't really need to spin up a new node to check this behavior, so I removed the logic of creating a new node. …
=> test(e2e): rewrite old CNI race condition test

.github/workflows/update-insecure-dependencies.yaml
aws-sdk is released daily and this bug https://osv.dev/vulnerability/GO-2022-0646 has no fix since Feb 2022. This might be a bug in osv or an actuall bug on aws-sdk. Let's disable it for now and if dependabot detects a bug on master we will update manually release branches.
Action output here: https://github.com/kumahq/kuma/actions/runs/3966613586. No PRs were created because there were no changes.
=> feat(build): add regex disable for packages in security update

pkg/core/xds/merge.go, pkg/core/xds/merge_test.go
=> fix(kuma-cp): fix appending of pointer to slice in policies config

.github/dependabot.yml
remove dependabot branch updates since they do not work
=> chore: remove dependabot branch updates since they do not work

mk/k3d.mk
`{1..5}` results in retires not being executed.
Here is an example of this https://app.circleci.com/pipelines/github/kumahq/kuma/19097/workflows/717ee01b-9664-46b1-80cf-238538a74f31/jobs/308760 also confirmed on my VM.
=> ci: fix load image retries

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshretries.yaml, pkg/plugins/policies/meshretry/api/v1alpha1/meshretry.go, pkg/plugins/policies/meshretry/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshretry/api/v1alpha1/validator.go, pkg/plugins/policies/meshretry/api/v1alpha1/zz_generated.deepcopy.go, pkg/plugins/policies/meshretry/k8s/crd/kuma.io_meshretries.yaml, pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshretry/plugin/xds/configurer.go
* Make `default.http.rateLimitBackoff.resetHeaders` mergeable (added pointer)
* Make `default.http.rateLimitBackoff.resetHeaders.name` required (removed omitempty)
* Make `default.http.rateLimitBackoff.resetHeaders.format` required (removed omitempty)
=> fix: update MeshRetry API with mergeable slice

app/kumactl/cmd/inspect/inspect_dataplane_test.go, app/kumactl/cmd/inspect/inspect_meshgateway_test.go, app/kumactl/cmd/inspect/inspect_policy_test.go, pkg/test/kumactl/context.go
Apparently, there is a race condition with `time.Now()` for inspect tests visible in arm64
```
[1674482952] Inspect Cmd Suite - 36/36 specs - 4 procs ••••••••••••••••••••••••••••••••••••
------------------------------
[ReportAfterSuite] PASSED [0.152 seconds]
[ReportAfterSuite] Autogenerated ReportAfterSuite for --junit-report
autogenerated by Ginkgo
Captured StdOut/StdErr Output >>
==================
WARNING: DATA RACE
Read at 0x000005393530 by goroutine 90:
time.Now()
time/time.go:1079 +0xc8
time.sendTime()
time/sleep.go:145 +0x44
Previous write at 0x000005393530 by goroutine 65:
[failed to restore the stack]
Goroutine 90 (running) created at:
[failed to restore the stack]
==================
<< Captured StdOut/StdErr Output
------------------------------
SUCCESS! 365.685157ms 
coverage: …
```
=> test(unit): use mock clock in inspect tests

tools/releases/version.sh
The old version (release-2.0) of [envoy/version.sh](https://github.com/kumahq/kuma/blob/release-2.0/tools/envoy/version.sh#L3-L4) and [releases/version.sh](https://github.com/kumahq/kuma/blob/release-2.0/tools/releases/version.sh) had different settings for `pipefail` and `errexit`. When this got merged together in this [PR](https://github.com/kumahq/kuma/pull/5291/files#diff-19e661817a5cc3d4d91d0e62ac68a4a68ffbecac0d64b7a4e8a680a34e8b7f08L1) I didn't know it made a difference so I merged that. Now it should be fine since I only set `pipefail` and `errexit` in the envoy_version function.
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-k …
=> chore: fix version sh pipe exit

pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator.go
`To-targretRef` supports only `Mesh` and `MeshService`.
=> fix: validator for MeshHealthCheck to-targetRef

tools/envoy/fetch.sh
[CI sometimes fails](https://app.circleci.com/pipelines/github/kumahq/kuma/19014/workflows/918e91e5-548e-4596-b949-735722615eae/jobs/306006) with "no such a file" on rm, but if the download does not succeed (status != 200) then there won't be any file to remove. 
This won't make the CI pass but at least there will be a correct error message.
=> chore: fix file not found

pkg/test/grpc/serverstream.go
In a [PR created](https://github.com/kumahq/kuma/pull/5373/files#diff-2104f7b8e3347efa0b0a472b5414d92f6e20e072479e7ac6416080e6f26b176bR130) by @jakubdyszkiewicz he uses a buffer of size `len(registry.Global().ObjectTypes())` but in our tests we still use still use `10` and I think that's why the job `dev-linux` and `dev-darwin` failed on `make test` via a deadlock:
- https://app.circleci.com/pipelines/github/kumahq/kuma/19121/workflows/58598d2c-afdc-4f2e-a8c5-6c3085f714d5/jobs/309710?invite=true#step-108-185
- https://app.circleci.com/pipelines/github/kumahq/kuma/19052/workflows/54d02b1b-0e67-431d-9964-e2c3cd6f8f0c/jobs/307144?invite=true#step-108-185
- https://app.circleci.com/pipelines/github/kumahq/kuma/18819/workflows/55f1f2f4-791 …
=> fix(kuma-cp): kds deadlock in unit tests

pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/testdata/basic_listener_1.golden.yaml, pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/testdata/gateway_basic_listener.golden.yaml, pkg/plugins/runtime/gateway/testdata/http/04-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/06-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/04-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/06-gateway-route.yaml, pkg/xds/envoy/listeners/v3/fault_injection_configurer_test.go, pkg/xds/envoy/listeners/v3/util.go, pkg/xds/envoy/listeners/v3/util_test.go
[FractionalPercent](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/v3/percent.proto#type-v3-fractionalpercent) works as a `x/100`, `x/10_000` or `x/1_000_000`. In case the value is bigger than Denominator then it is 100%. Our percentage didn't work properly because e.g. 50.5 was mapped to (50.5 * 10_000)/ 10_000 which is higher 10_000 which makes it 100% always. 
=> fix(kuma-cp): fix the way how we set FractionalPercent in envoy

UPGRADE.md, app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, deployments/charts/kuma/templates/cp-deployment.yaml, go.mod, go.sum, pkg/plugins/bootstrap/k8s/plugin.go
Switching for leader for life brought more problems than solutions https://github.com/kumahq/kuma/pull/3023
One of the problems was noticed on GCP and AWS where Node migration happened and the old leader CP Pod was stuck. The result was that no new leader was chosen and Pod with sidecar injection was never up.
One of the reasons for leader for life migration was Kube API throttling when CP was under big pressure. Since then, we reduced calls to storage. If this is still a problem, we can bump the lease duration and lease renewal time.
Fix #5709
=> feat(kuma-cp): restore default leader election mechanism

pkg/plugins/runtime/gateway/cluster_generator.go
It's strange to have this log on `V(0)`. It's the only `V(0)` INFO log in xDS generation process.
=> chore: change gateway log to V1

pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go
Revert https://github.com/kumahq/kuma/pull/5825 as further testing spotted that we can drop requests in multizone deployment during the upgrade.
=> feat(kuma-cp): disable kube outbounds as vips by default

.github/workflows/update-insecure-dependencies.yaml
It's not allowed to pass secrets around jobs.
We only needed to github app token in the main job anyway
=> ci(.github): don't pass token between jobs

pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshratelimit/plugin/v1alpha1/testdata/basic_listener_1.golden.yaml, pkg/plugins/policies/meshratelimit/plugin/xds/configurer.go
=> fix(kuma-cp): should set only once header for MeshRateLimit

.github/workflows/update-insecure-dependencies.yaml
needed to use an `id` for the step to be able to get the output
=> ci(.github): fix update-insecure-dependencies matrix

pkg/plugins/policies/meshratelimit/api/v1alpha1/validator.go, pkg/plugins/policies/meshratelimit/api/v1alpha1/validator_test.go
=> fix(kuma-cp): meshratelimit doesn't support MeshGatewayRoute

pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/testdata/outbound_split_cluster_0_connection_limits_outlier_detection.golden.yaml, pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/testdata/outbound_split_cluster_connection_limits_outlier_detection.golden.yaml, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/basic_grpc_health_check_cluster.golden.yaml, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/basic_http_health_check_cluster.golden.yaml, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/basic_http_health_check_split_cluster.golden.yaml, pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/basic_tcp_health_check_cluster.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/http_outbound_split_cluster.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/xds/clusters.go, test/e2e_env/universal/meshhealthcheck/policy.go, test/e2e_env/universal/universal_suite_test.go
New policies are not applied for split clusters because names are not matching a service name. Added change to group split clusters by service name.
=> fix(kuma-cp): configure split clusters for new policies

.github/workflows/pr-merged.yaml
=> ci: use "ref_name" instead of "refName" in GH action

.github/commitlint.config.js, .github/workflows/lifecycle.yml, CONTRIBUTING.md
This makes changelog generation better at the small cost
of more restrictive PR message format
=> ci(commitlint): disallow scope `policies` and empty scopes

.github/workflows/helm-release.yaml
This will make it easier for child repo to reuse this
=> ci(.github): modify helm-release to allow inheriting action

pkg/xds/generator/outbound_proxy_generator.go, test/e2e_env/universal/trafficroute/traffic_route.go
Kuma configures RateLimit on the outbound side only when there is an external service with no egress. Since RateLimit is configured on the `envoy.Route`, Kuma created 2 separate `envoy.Route` for the internal/external split and this doesn't work properly.
In order to fix this we need to configure RateLimit for the `destination` in TrafficRoute even if one of the services in split doesn't have RateLimit.
For example, given the policy:
```yaml
type: TrafficRoute
sources:
- match:
kuma.io/service: "*"
destinations:
- match:
kuma.io/service: service-WITH-rate-limit
conf:
split:
- weight: 50
destination:
kuma.io/service: service-WITH-rate-limit
- weight: 50
destination:
kuma.io/service: service-WITHOUT-rate-limit
```
we should configure the rate limit on the `envoy.Route` with split, because …
=> fix(kuma-cp): traffic split with internal and external service

mk/build.mk, mk/generate.mk
This was making it harder to depend on this
=> ci(make): make some parameters optional in Makefile

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/values.yaml
Generally it is better to use objects/dicts over lists because the former can be used in the exact same way as the latter and the former adds the functionality of being able to specify which element by name. 
Also, in Helm, lists are overridden completely when using subsequent values.yaml files. On the other hand, objects/dicts are merged, making it easier to create a base values.yaml and override it with values-{env}.yaml without having to copy/paste a lot of stuff. 
See this StackOverflow question: https://stackoverflow.com/questions/59394422/helm-charts-with-multiple-lists-in-multiple-values-files
=> fix(helm): dont specify a default type for extraSecrets

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshhttproutes.yaml, pkg/plugins/policies/meshhttproute/api/v1alpha1/meshhttproute.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshhttproute/api/v1alpha1/zz_generated.deepcopy.go, pkg/plugins/policies/meshhttproute/k8s/crd/kuma.io_meshhttproutes.yaml, pkg/plugins/policies/meshhttproute/xds/filters.go, test/e2e_env/kubernetes/meshhttproute/test.go, test/framework/client/collect.go
=> feat(meshhttproute): add path modifier to redirect

pkg/core/managers/apis/mesh/mesh_manager_test.go, pkg/core/tokens/compatibility_test.go, pkg/core/tokens/file_signing_key_manager.go, pkg/core/tokens/issuer.go, pkg/core/tokens/issuer_test.go, pkg/core/tokens/meshed_signing_key_accessor.go, pkg/core/tokens/meshed_signing_key_manager.go, pkg/core/tokens/public_key_secret_signing_key_accessor.go, pkg/core/tokens/signing_key.go, pkg/core/tokens/signing_key_accessor.go, pkg/core/tokens/signing_key_manager.go, pkg/core/tokens/token.go, pkg/core/tokens/validator.go, pkg/defaults/mesh/mesh.go, pkg/defaults/mesh/mesh_test.go
Because of offline signing, users can now bring their own tokens to the system. That means that `kid` can be more than just a number and we should allow to put anything here. Vault for example uses UUID. 
I did a bunch of renaming from "serial number" to keyID to be more JWT native. I also adjusted the naming to `keyID` instead of `kid`.
=> feat(tokens): allow kid to be a string

pkg/api-server/server.go, pkg/config/api-server/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go
Adds the ability to enable mTLS to HTTPS API Server. It does not require to use deprecated authentication method of adminClientCert. You can use it with any auth method including user tokens.
I tested manually. I'm figuring out E2E test.
Fix #5976
=> feat(api-server): manual mTLS

app/kumactl/cmd/install/install_control_plane_test.go, app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
We were using matchGoldenYaml which would only compare the content of the yaml. We also want to get the comments in this case
=> test(helm): use matchGoldenEqual for --dump-values

app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.values.yaml, deployments/charts/kuma/templates/cp-deployment.yaml, deployments/charts/kuma/templates/egress-deployment.yaml, deployments/charts/kuma/templates/ingress-deployment.yaml
While we've always been able to pass a specific CA for control-plane certs it wasn't possible to use it for egress and ingress. Now we just use whatever is set. We also simplified the template when handling CAs
Fix #5978 
=> fix(helm): use custom CA in egress and ingress too

test/e2e_env/universal/meshhealthcheck/policy.go, test/framework/universal_cluster.go
* MeshHTTPRoute creates 2 clusters `test-server_-0-` and `test-server_-1-`, we have to check both to be unhealthy
* Make it impossible to create 2 universal apps with the same names, because 1 of them won't be cleaned up after the test
Affects: `MeshHealthCheck HTTP with MeshHTTPRoute should mark host as unhealthy if it doesn't reply on health checks`
=> fix(e2e): check both clusters of MeshHTTPRoute to be unhealthy

tools/releases/docker.sh
I adjusted `distros.sh` but not `docker.sh`. It's only checked during the release. Very unfortunate that it's not part of the CI.
=> chore: fix docker.sh script

.github/workflows/pr-merged.yaml
Switches to using a PAT generated using a dedicated bot account instead of a real user PAT.
Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>
=> ci(.github): uses bot PAT instead of real user PAT

pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go, test/e2e/gateway/gatewayapi/conformance_test.go
=> feat(GatewayAPI): support ResponseHeaderModifier in HTTPRoute

pkg/plugins/policies/meshhttproute/api/v1alpha1/validation.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/validation_test.go
=> refactor(MeshHTTPRoute): check if a prefix match is defined when rewriting prefix

.github/workflows/pr-merged.yaml
context has no `github` variable.
=> fix(github): pr merged workflow

pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.03.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.03.input.yaml
Kubernetes is [replacing the k8s.gcr.io registry](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/). Besides it just becoming frozen soon the new registry.k8s.io registry is also less costly to use so the sooner we can stop using the old one the better to help out upstream.
=> chore: replace k8s.gcr.io registry usage

.github/workflows/release.yaml
=> ci(.github): don't check for kuma cni image in version < 1.8

.golangci.yml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/clusters.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshhttproute/xds/builder.go, pkg/plugins/policies/meshhttproute/xds/configurer.go, pkg/plugins/policies/xds/cluster.go, pkg/plugins/policies/xds/clusters.go, pkg/plugins/policies/xds/split.go, pkg/xds/envoy/listeners/v3/tcp_proxy_configurer.go, pkg/xds/envoy/routes/v3/routes_configurer.go, pkg/xds/envoy/types.go, pkg/xds/generator/outbound_proxy_generator.go
We leaked unnecessary information into the `Cluster` abstraction:
```go
type Cluster struct {
service           string
name              string
weight            uint32
tags              tags.Tags
mesh              string
isExternalService bool
lb                *mesh_proto.TrafficRoute_LoadBalancer
timeout           *mesh_proto.Timeout_Conf
}
``` 
* `lb` and `timeout` are old policies protos
* `weight` is not a Cluster's attribute, it's route's attribute (2 routes can point to the same cluster with different weights)
This PR deprecates `Cluster` type and introduces 2 new types:
```go
type Cluster struct {
service           string
name              string
tags              tags.Tags
mesh              string
isExternalService bool
}
type Split struct {
clusterName string
weight      uint32 …
```
=> chore(MeshHTTPRoute): refactor cluster builder

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/values.yaml, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
=> fix(kuma-cp): change default value for KubeOutboundsAsVIPs and fix multizone upgrade

app/kumactl/cmd/inspect/inspect_dataplanes.go, app/kumactl/cmd/inspect/inspect_dataplanes_test.go, app/kumactl/cmd/inspect/inspect_meshes_test.go, app/kumactl/cmd/inspect/inspect_services_test.go, app/kumactl/cmd/inspect/inspect_zoneegresses_test.go, app/kumactl/cmd/inspect/inspect_zoneingresses_test.go, app/kumactl/cmd/inspect/inspect_zones_test.go, app/kumactl/pkg/output/table/cells.go
Chasing https://app.circleci.com/pipelines/github/kumahq/kuma/19774/workflows/f1a3081a-9dde-4006-9ed9-e2bf9f3dac65/jobs/331186 flake.
`inspect` package is the only one that overrides locale `time.Local = time.UTC`.
I changed the logic that `cells.go#Date` does not use it anymore and the date that we pass there has a locale of the current clock that we safely pass via context without overriding global variables.
It's just a hypothesis that this might be the cause since this flake is not reproducable outside of CI.
=> chore(kumactl): use location of the current clock

pkg/core/bootstrap/bootstrap.go, pkg/core/runtime/builder.go, pkg/core/runtime/runtime.go, pkg/hds/components.go, pkg/plugins/bootstrap/k8s/plugin.go, pkg/test/runtime/runtime.go, pkg/xds/auth/per_proxy_type_authenticator.go, pkg/xds/runtime/context.go, pkg/xds/server/v3/components.go
Introduce the possibility to have a separate authenticator for dp and zone proxy.
This is in line with schemas https://github.com/kumahq/kuma/blob/master/docs/madr/decisions/019-offline-signing-tokens.md
Currently, we have to set `KUMA_DP_SERVER_AUTH_TYPE` to `dpToken` so Zone Ingress and Zone Egress authenticate with zone proxy which is strange.
I didn't want to add another method to RuntimeContext so I refactored xds components into the `XDSRuntimeContext`, a similar pattern as we did with KDS https://github.com/kumahq/kuma/blob/master/pkg/kds/context/context.go
I did not want to name it `XDSContext` to avoid the confusion with `XDSContext` used for xds generation.
I think long term proper name for this would be `XDSModule` and KumaCP RuntimeContext would depend on multiple modules, but …
=> feat(auth): separate authenticators for dp and zone proxy

test/framework/network/netns/builder.go, test/framework/network/netns/netns.go, test/framework/network/netns/wrap_linux.go, test/framework/network/netns/wrap_other.go
There were functions that would exist only in Linux. This would cause golangci-lint to fail when running on macOS.
We extracted these into sub functions and provided stubbed to be able to run checks without problems
=> ci(golangci-lint): fix make check on macOS

go.mod, go.sum
=> chore(deps): bump github.com/vishvananda/netns to 0.0.4

test/e2e/cni/taint_controller_race.go, test/framework/config.go, test/framework/k8s_cluster.go
Allow to set CNI image (repository) in e2e config and modify CNI taint e2e test to load images with repositories set from the e2e config
=> test(e2e/framework): allow to set CNI image in e2e conf

.github/workflows/update-insecure-dependencies.yaml, mk/check.mk, tools/ci/update-vulnerable-dependencies.sh
Tested by copy pasting the step contents into `update.sh` and running it on a previous commit, it seems to do the right thing.
=> ci(.github): take least fixed version for security updates

test/e2e_env/kubernetes/gateway/gatewayapi.go
I suspect the ServiceLB can sometimes take much longer to reconcile LoadBalancer Services, I want to see if this can eliminate the flakes.
=> test(e2e): increase timeout for getting Gateway API Gateway IP

pkg/api-server/server.go, pkg/api-server/whoami_endpoint.go, pkg/api-server/whoami_endpoint_test.go
It's quite annoying that there is no convenient way to check if you successfully authenticated as user X. This PR adds an endpoint to check it.
=> feat(api-server): whoami endpoint

.gitignore, mk/ebpf.mk, pkg/transparentproxy/ebpf/programs/amd64/programs.go, pkg/transparentproxy/ebpf/programs/arm64/programs.go, pkg/transparentproxy/ebpf/programs/programs.go, pkg/transparentproxy/ebpf/programs/programs_amd64.go, pkg/transparentproxy/ebpf/programs/programs_arm64.go
Previously when building multiple arch at a time programs would be wrongly packages (we were packaging the host arch ebpf program regardless of the GOOS).
We now always add ebpf program for each arch and use build flags to set the correct set of programs
=> ci(ebpf): correctly build ebpf programs for each arch

tools/kubectl/Dockerfile, tools/kubectl/docker-build-and-publish.sh
This makes it unnecessary to set `runAsUser: ` in the various k8s `securityContexts` because it otherwise ran as root.
=> build(tools/kubectl): remove default version and run as non root

UPGRADE.md
Update UPGRADE.md file with the section about tproxy/cni v2 which are now default
=> docs(UPGRADE.md): add section about tproxy/cni v2

pkg/core/validators/types.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/validation.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/validation_test.go, pkg/test/resources/validation.go
=> chore(meshhttproute): add extra validation

docs/madr/decisions/021-lb-policy.md
[Rendered](https://github.com/lobkovilya/kuma/blob/madr/lb-policy/docs/madr/decisions/021-lb-policy.md)
=> feat(policy): create MADR for LB policy

pkg/core/validators/types.go, pkg/core/validators/types_test.go
=> fix(validators): make Root().Field() == RootedAt()

app/kumactl/cmd/config/config_control_planes_add.go
Remove the requirement of providing ca-cert or skip-verify when https is used.
The user may just want to use a CA bundle in the system.
=> feat(kumactl): remove ca-cert or skip-verify requirement

.circleci/config.yml, test/e2e/gateway/gatewayapi/conformance_test.go
=> test(e2e): reenable Gateway API conformance tests

app/kumactl/cmd/install/testdata/install-transparent-proxy.defaults.golden.txt, app/kumactl/cmd/install/testdata/install-transparent-proxy.dns.golden.txt, app/kumactl/cmd/install/testdata/install-transparent-proxy.overrides.golden.txt
Fix kumactl install transparent-proxy input golden files
=> fix(tests/golden): fix install tproxy golden files

app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, deployments/charts/kuma/templates/_helpers.tpl
We shouldn't include taint controller envs when CNI is not enabled. With recent changes we've started injecting them and that causes error messages in control-plane.
=> fix(helm): don't include taint controller env when cni disabled

test/e2e/gateway/gatewayapi/conformance_test.go
=> test(e2e): temporarily disable flaky Gateway API conformance test

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-legacy-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, deployments/charts/kuma/templates/cp-global-sync-service.yaml, deployments/charts/kuma/templates/cp-service.yaml
This is useful as some Kubernetes tools rely on this
=> fix(helm): add appProtocol to services we create

test/e2e/gateway/gatewayapi/conformance_test.go
=> test(e2e): enable passing Gateway API conformance test

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-legacy-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml, deployments/charts/kuma/templates/cp-deployment.yaml
Fix #6121, the CP needs `/tmp`. We could theoretically [use `medium: Memory`](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir).
=> fix(helm): use emptyDir at /tmp with CP

test/e2e_env/kubernetes/gateway/gatewayapi.go
=> test(e2e): set Gateway API TLS test to pending

pkg/api-server/resource_endpoints.go
"default" should not be taken account into the limit.
On Universal Global CP does not add "default".
On Kubernetes "default" is a namespace.
=> fix(kuma-cp): change validation of resources synced to global

pkg/plugins/resources/k8s/native/api/v1alpha1/zz_generated.mesh.go, tools/resource-gen/main.go
A small annoyance that `make generate` generated diffs until `make check` was run.
=> build(generate): gofumpt compliant code

tools/kubectl/Dockerfile
=> build(kubectl): use UID instead of username

tools/releases/dockerfiles/Dockerfile.base, tools/releases/dockerfiles/Dockerfile.base-root, tools/releases/dockerfiles/Dockerfile.static
Without this command, anything that uses [the "default shell" of the image, which is `["/bin/sh", "-c"]`](https://docs.docker.com/engine/reference/builder/#shell) will fail because this binary doesn't exist in images derived from this `Dockerfile`.
For example, if another `Dockerfile` `FROM`s these images and it uses the "shell form" of commands as described above, the image will be broken:
```
diff --git i/tools/releases/dockerfiles/Dockerfile.kuma-cp w/tools/releases/dockerfiles/Dockerfile.kuma-cp
index c6f1a6ce6..27893776a 100644
--- i/tools/releases/dockerfiles/Dockerfile.kuma-cp
+++ w/tools/releases/dockerfiles/Dockerfile.kuma-cp
@@ -3,4 +3,4 @@ FROM kumahq/static-debian11:no-push
ARG ARCH
COPY /build/artifacts-linux-$ARCH/kuma-cp/kuma-cp /usr/bin
-ENTRYPOINT ["kuma-cp"]
+ENTRYPOINT …
```
=> fix(docker): set `SHELL` to an existing binary

go.mod, go.sum, test/e2e_env/universal/universal_suite_test.go, test/framework/config.go, test/framework/deployments/externalservice/deployment.go, test/framework/deployments/externalservice/universal.go, test/framework/envoy_admin/tunnel/universal.go, test/framework/envs/universal/env.go, test/framework/setup.go, test/framework/ssh/ssh.go, test/framework/universal_app.go, test/framework/universal_cluster.go, test/framework/universal_controlplane.go, test/framework/universal_logs/universal_logs.go
Logs which were for convinience saved under /tmp/e2e, now are wrapped by directories which names constists of suite start time.
Each universal component logs are also placed under directory with the name of the test (which is easier to find when needed).
When test fails, the logs are written to GinkgoWriter, so in CI we'll have access to them stright away.
=> feat(e2e/universal): display full logs after fail

mk/check.mk
=> ci(mk): make update-vulnerable-dependencies respect KUMA_DIR

go.mod, go.sum, pkg/mads/util.go
We were maintaining this dependency for a label check that is very simple and unlikely to change. Opted for duplicating it instead
=> chore(deps): remove dependency on github.com/prometheus/prometheus

UPGRADE.md, api/mesh/v1alpha1/dataplane.pb.go, api/mesh/v1alpha1/dataplane.proto, api/mesh/v1alpha1/dataplane_helpers.go, docs/generated/resources/proxy_dataplane.md, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/core/bootstrap/bootstrap.go, pkg/xds/bootstrap/components.go, pkg/xds/bootstrap/generator.go, pkg/xds/bootstrap/generator_test.go, pkg/xds/bootstrap/server_test.go, test/e2e_env/multizone/inbound_communication/inbound_passthrough_disabled.go, test/framework/envs/multizone/env.go
Remove deprecation config options to enable binding inbound clusters to localhost.
Closes https://github.com/kumahq/kuma/issues/4772
=> chore(dp/cp/config): remove EnableLocalhostInboundClusters option

pkg/core/resources/store/store.go, pkg/plugins/ca/builtin/manager.go
There's always a race condition possible using the k8s store between checking whether a resource exists and trying to create it, leading to superfluous errors on startup like:
```
2023-03-07T10:58:59.597Z	ERROR	kube-manager	Reconciler error	{"controller": "mesh", "controllerGroup": "kuma.io", "controllerKind": "Mesh", "Mesh": {"name":"default"}, "namespace": "", "name": "default", "reconcileID": "90c63204-743b-48a2-b37b-0082ac351117", "error": "could not update default mesh resources: could not ensure CA backends of type builtin: failed to create CA for mesh \"default\" and backend \"ca-1\": Resource already exists: type=\"Secret\" name=\"default.ca-builtin-cert-ca-1\" mesh=\"default\"
```
We can leave the initial check in to avoid creating a CA if unnecessary.
[1]: …
=> fix(ca/builtin): be less verbose when creating CA secrets

test/framework/config.go, test/framework/universal_app.go
There is no `DOCKER_OUTPUT` chain in Docker for Mac. So we don't have to redirect traffic to it. 
=> chore(e2e): avoid redirecting DNS in Docker on darwin

.github/workflows/pr-comments.yaml
We were not using --paginate so there was only the first 30 collaborators (the first page), this paginates over all pages
=> ci(pr-comments): handle more than 30 collaborators

UPGRADE.md, app/cni/pkg/cni/annotations.go, pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.23.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.24.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.25.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.29.golden.yaml, pkg/transparentproxy/kubernetes/kubernetes.go, pkg/transparentproxy/kubernetes/kubernetes_test.go
These were deprecated since 1.8.0
Fix #4675
=> chore(cleanup): remove old builtindns annotations

mk/docker.mk
By adding `--quiet` flag to docker load make targets, we are saving a lot of unnecessary logs from the CI, which makes debugging it easier.
=> ci(docker): quietly load docker images

mk/docker.mk
=> ci(docker): quietly load docker images (backport #6229)

mk/build.mk
=> chore(deps): bump coredns from 1.10.0 to 1.10.1

.circleci/config.yml, mk/kind.mk
CI for ibv6 e2e tests is broken since: https://github.com/kumahq/kuma/commit/f70345cfd0e595891dfa62d13a16eb509b94236f
=> fix(ci): fix kind path for ipv6 e2e tests

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/post-delete-cleanup-ebpf-job.yaml, deployments/charts/kuma/values.yaml, mk/build.mk
ebpf-cleanup hook needs write access to the root filesystem to clean ebpf programs
=> fix(helm): security contexts for ebpf cleanup hook

Makefile, mk/check.mk, mk/deps.mk
=> ci(mk): move update-vulnerable-dependencies target to own file

pkg/api-server/index_endpoints.go
Proposed change to add a dedicated health endpoint to serve health information about the CP. Related to Kong/mink-charts#120. 
=> feat(kuma-cp): add a dedicated health endpoint

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-legacy-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, deployments/charts/kuma/templates/cni-daemonset.yaml
=> chore(helm): add kube-linter ignore annotations for CNI DaemonSet

pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go
Feels more like this is how the annotation should work, given that we need it in the first place. There's no reason to filter only for `Create` events, which requires a restart to retrigger reconciliation.
WDYT?
=> feat(kuma-cp): allow Mesh default resources regeneration without deletion and restart

mk/check.mk
This enables overriding it more easily in sub projects
=> ci(mk): use GOENV on golangci-lint and do kubelint on all charts

.circleci/config.yml, .github/workflows/blackbox-tests.yaml, .github/workflows/lifecycle.yml, .github/workflows/pr-comments.yaml, .github/workflows/update-insecure-dependencies.yaml
Looks like this flake started to happen after Go upgrade
https://app.circleci.com/pipelines/github/kumahq/kuma/20498/workflows/5ee41e83-46f2-4536-b2d0-ba7ecf18febc/jobs/355715
only on arm64, looks like a bug in code coverage code. In 1.20.2 release note I see
```
go1.20.2 (released 2023-03-07) includes a security fix to the crypto/elliptic package, as well as bug fixes to the compiler, the covdata command, the linker, the runtime, and the crypto/ecdh, crypto/rsa, crypto/x509, os, and syscall packages. See the [Go 1.20.2 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.20.2+label%3ACherryPickApproved) on our issue tracker for details.
```
`the covdata command`. Let's try to update Go to see if that's the reason
[1]: …
=> chore(deps): bump go from 1.20.1 to 1.20.2

pkg/api-server/index_endpoints.go
Accidentally created the health endpoint with the wrong path. This fixes it. 
=> fix(kuma-cp): specified the incorrect health endpoint

api/mesh/v1alpha1/mesh.pb.go, api/mesh/v1alpha1/mesh.proto, docs/generated/resources/other_mesh.md, pkg/xds/secrets/ca_provider.go, pkg/xds/secrets/secrets.go
This PR adds a default timeout to calls of `GetRootCert` for the case that the CA manager takes too long, so that it doesn't block generation, especially in the cross-mesh case.
=> fix(kuma-cp): don't let CA requests for other meshes block generation

pkg/test/ginkgo.go
Here for example we cannot see the full Pod definition on failure
https://app.circleci.com/pipelines/github/kumahq/kuma/20510/workflows/76b48c2c-7445-44cc-9006-a01690491857/jobs/356156
=> test(e2e): bump max length of gomega messages

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/egress-deployment.yaml, deployments/charts/kuma/values.yaml
Allow egress resources to be configurable via the Helm values file
Signed-off-by: Joe Dascole <joe.dascole@konghq.com>
=> feat(helm): make egress resources configurable

tools/envoy/BUILD-darwin-arm64.patch, tools/envoy/build_darwin.sh
As described in https://github.com/bazelbuild/bazel/issues/13514#issuecomment-847917936
=> build(mk): fix Envoy build for darwin arm64

mk/build.mk
When we follow this `$(MAKE) dependency` pattern, it seems that the order is not preserved so when we call this
```
.PHONY: test/something
test/something: build/kumactl build/kumactl/linux-${GOARCH}
```
We see that eBPF files are fetched twice.
With the change in the PR, the order is preserved and parallelization is still in place.
This was visible when running e2e-universal that runs `build/kumactl build/kumactl/linux-${GOARCH}`. Go complained that embedded ebpf programs has changed  which results in flaky CI https://app.circleci.com/pipelines/github/kumahq/kuma/20469/workflows/43b4152a-f794-4ba2-aca8-71ef5828fba2/jobs/354836
The other alternative would be to solve this on the "client" side so do this
```
.PHONY: test/e2e-universal
test/e2e-universal: images/test k3d/network/create …
```
=> ci(make): refactor targets to have a dependency on other target

.circleci/config.yml, labels.yml, mk/distribution.mk, mk/e2e.new.mk, tools/ci/has_label.sh
This PR aims to make it easier to reuse the circleci config in sub repository
- Move arm64 ginkgo label to Makefile so it also works locally
- Support using tokens in `tools/ci/has_label.sh` script
- add KUMA_DIR envvar in circleci config
- add ci/force-publish label to be test publishing on PRs
- build helpers for halting jobs depending on params or labels
- improve when building distribution on linux
=> ci(circle): simplify config to make it reusable

.github/dependabot.yml
=> ci(.github): increase dependabot limit

app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml, deployments/charts/kuma/templates/cp-deployment.yaml
~Waiting on #6253~
This just reapplies the same resource requests/limits as the main CP container, do we think this makes sense? Or do we need a separate `resources`?
=> fix(helm): set migration container resources and securityContext

UPGRADE.md, app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-legacy-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cni-daemonset.yaml, deployments/charts/kuma/values.yaml
=> feat(helm): add default CNI resources

mk/check.mk
=> ci(mk): run kube-lint on `install control-plane` golden files

mk/k3d.mk
This just leads to confusion otherwise. 
=> ci(mk): use the same default k8s version as with CircleCI

mk/docker.mk
this is to avoid PRs to try to login with creds they don't have
=> ci(mk): gate `docker/{login,logout}` with GATE_PUSH

test/e2e_env/kubernetes/gateway/gatewayapi.go
=> test(e2e): cleanup Gateway API test HTTPRoute resources

pkg/core/bootstrap/bootstrap.go, pkg/dp-server/server/server.go, pkg/test/runtime/runtime.go, pkg/xds/bootstrap/server_test.go
Thanks to this change, projects based on Kuma will be able to modify flow of requests to dp server.
=> fix(kuma-cp): add possibility to filter requests to dp server. 

app/cni/pkg/cni/injector_linux.go, test/e2e_env/multizone/connectivity/cni_v2_ipv6_gateway.go, test/e2e_env/multizone/multizone_suite_test.go
Fix #6017
`cfg.IPv6` was set only for non-gateways.
=> fix(kuma-cni): ipv6 iptables with provided gateway and CNI V2

pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_status.go
It doesn't have `omitempty` so this leads to update errors
=> fix(gatewayapi): always set an explicit HTTPRoute Parents in status

pkg/core/runtime/component/component.go, pkg/core/runtime/component/component_manager_test.go, pkg/core/runtime/component/component_suite_test.go, test/e2e_env/universal/intercp/intercp.go, test/e2e_env/universal/universal_suite_test.go
Fix #6349
This inlines our universal component manager to work just like kubernetes component manager, which means that we can add components in runtime and they are run.
However, currently with a limitation that we cannot add leader components after Start(). This is quite complicated to manage and we don't need it now (or never). At least this time we return an explicit error.
I also added a simple e2e test to see that inter cp server is actually running on universal.
=> fix(kuma-cp): add components in runtime

test/e2e_env/kubernetes/gateway/gatewayapi.go
We weren't waiting for the Gateway to be ready which lead to 30s+ times until requests succeeded.
=> test(e2e): fix and reenable Gateway API TLS test

pkg/dp-server/server/server.go
=> fix(kuma-cp): add set filter method, so we could modify it easily in runtime

deployments/charts/kuma/templates/pre-upgrade-install-crds-job.yaml, test/e2e/helm/kuma_helm_upgrade.go, test/framework/config.go
Fix #6201
Helm by default does not manage CRDs aside from installing them on the first Helm install.
That's why a long time ago we created a Helm pre-upgrade job that installs missing CRDs.
This solution worked so far because CRDs for the old policies did not have "content" in them.
With new policies, the CRDs have a definition of all the fields. In Kuma 2.1.0 we changed an enum in `MeshTrafficPermission` from `ALLOW` to `Allow`.
However, our job did not upgrade CRDs it only installed them if they were missing.
This PR changes the job to reapply CRDs and not only create them.
* I changed the job name from `install-missing-crds` to `install-crds`, to avoid confusion.
* I removed `--only-missing` arg to reapply all crds
* I added `--no-config` because the job was failing with `Error: Failed …
=> fix(helm): upgrade CRDs instead of installing missing CRDs

pkg/events/eventbus.go, pkg/events/interfaces.go, pkg/insights/resyncer.go, pkg/insights/test/test_event_reader.go, pkg/plugins/resources/postgres/listener_test.go
Having access to the channel makes it much easier to compose receiving events with reacting to other channels.
=> refactor(events): use channel for Recv instead of blocking

pkg/insights/resyncer.go
#6401 was merged early this bug was still present
=> chore(insights): fix closed channel check

test/e2e/helm/kuma_helm_upgrade.go
Until I figure out why it fails on CI, but not locally
=> test(e2e): ignore upgrade HELM test

test/e2e/helm/kuma_helm_upgrade.go, test/framework/interface.go
Before my recent PR https://github.com/kumahq/kuma/pull/6403 Helm Upgrade test did not even upgrade Kuma. It was executing Upgrade on the same Helm Kuma version.
Helm opts are stored in the ControlPlane object, therefore there are carried to Upgrade command. The problem was that the first install was calling `WithoutHelmOpt("global.image.tag")` so that it disable default override of `global.image.tag` https://github.com/kumahq/kuma/blob/master/test/framework/k8s_cluster.go#L409 . However, it was carried to `Upgrade()` call. Therefore it was using the default app version from helm which is https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/Chart.yaml#L6
This worked on my machine, because as I develop I had images with `0.0.0-preview.vlocal-build` tag locally.
I also removed …
=> test(e2e): fix helm upgrade test

mk/k3d.mk
=> ci(mk): use same default k8s version as .circleci

docs/madr/decisions/023-gateway-custom-deploy.md
=> feat(meshgateway): create MADR for deployment customization

pkg/core/xds/rules.go, pkg/core/xds/rules_test.go
=> fix(policy): matcher with same key not the same value

CONTRIBUTING.md
This was unclear and people were wrongly using feat/fix
=> docs(CONTRIBUTING.md): clarify feat and fix in commit types

tools/envoy/version.sh
=> chore(ci): bump envoy to 1.22.10 envoy/version.sh

pkg/plugins/policies/meshretry/api/v1alpha1/validator.go, pkg/plugins/policies/meshretry/api/v1alpha1/validator_test.go
Adds validation for the case where someone specifies `OmitPreviousPriorities` more than once. This wouldn't error today, but might result in unexpected behavior (we'll always just use the last one specified in the list).
=> fix(MeshRetry): guard against multiple previous priorities

tools/releases/helm.sh
Chart Releaser is always packaging dependencies specified in Chart.yaml file first. The archives with packaged dependencies lands inside "charts" directory (i.e. deployments/[...]/charts/[dependency_name]-[version].tgz). When building the final chart package, it includes inside, the content of the "charts" directory. When it finds an archive there, it flattens it and includes in the final package as well. It means if the chart have any dependencies, the final chart's archive will contain duplicated manifests. To mitigate this issue we are unarchiving (which would remove duplicates) and archiving the chart again.
> Changelog: Modify helm.sh script to make sure no duplicate manifests will be present in packaged chart
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linki …
=> ci(helm): no duplicates in helm chart package

mk/distribution.mk
Without a `release` first argument pulp would get confused with the `--dist-version release`
=> ci(pulp): fix pulp publish command

mk/distribution.mk
=> ci(distributions): avoid adding `.` to tar

pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.02.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.16.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.17.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.18.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.22.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.23.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.24.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.25.golden.yaml
This reverts commit 6cf964869c0987152ad2e760bf78bd6bfa2cf5e9.
reverts https://github.com/kumahq/kuma/pull/5857
=> fix(kuma-cp): don't make init container first by default

app/kumactl/cmd/root.go
When `ConfigType` is `InMemory` we should return and use the default configuration. Previously we were overriding this with host configuration if it exists instead of returning one loaded from memory.
=> fix(kumactl): return after loading configuration from memory

mk/k3d.mk
When this target is run as a dependency, like with `make test/e2e/debug`, it fails for me with:
```
/Library/Developer/CommandLineTools/usr/bin/make k3d/configure/ebpf
docker exec -it k3d-kuma-1-server-0 mount bpffs /sys/fs/bpf -t bpf && \
docker exec -it k3d-kuma-1-server-0 mount --make-shared /sys/fs/bpf
the input device is not a TTY
make[3]: *** [k3d/configure/ebpf] Error 1
make[2]: *** [k3d/start] Error 2
make[1]: *** [test/e2e/k8s/start/cluster/kuma-1] Error 2
```
I don't think we want or need `-it` here.
=> ci(mk): don't use `-it` in `docker exec` commands

test/framework/constants.go, test/framework/interface.go, test/framework/k8s_controlplane.go, test/framework/universal_controlplane.go
- Allow getting XDS server address in e2e framework
- Add option to generate zone token with manually specifying scope
- Add validation that `&K8sControlPlane{}` and `&UniversalControlPlane{}` fulfill `ControlPlane` interface 
This is necessary if we would like to test anything that relies on XDS, like ratelimit
> Changelog: ci(e2e/framework): add in e2e framework option to get xds address and generate zone token with manually specified scope
=> ci(e2e/framework): allow getting xds address +more

.circleci/config.yml, mk/build.mk, mk/distribution.mk
The distributions are already part of build we should need to rebuild them. Also split build and distributions in 2 different tasks to be able to use -j for `make build/distributions`
=> ci(mk): don't rebuild distributions in publish

docs/madr/decisions/022-retry-host-selection.md
[Rendered](https://github.com/johnharris85/kuma/blob/cc904ea2bd850897baa704e94555016779a8c9d2/docs/madr/decisions/022-retry-host-selection.md)
=> feat(retry): create MADR for host selection

.circleci/config.yml, test/dockerfiles/universal.Dockerfile, test/e2e_env/universal/mtls/mtls.go
It's supposed to be quicker and cheaper
=> ci(circleci): use docker build job instead of vm

UPGRADE.md, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml, app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml, deployments/charts/kuma/crds/kuma.io_meshhttproutes.yaml, pkg/plugins/policies/meshhttproute/api/v1alpha1/meshhttproute.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshhttproute/api/v1alpha1/validation.go, pkg/plugins/policies/meshhttproute/api/v1alpha1/validation_test.go, pkg/plugins/policies/meshhttproute/k8s/crd/kuma.io_meshhttproutes.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhttproute/xds/configurer.go, pkg/xds/generator/ingress_generator_test.go, test/e2e_env/kubernetes/meshhttproute/test.go, test/e2e_env/multizone/meshhttproute/test.go, test/e2e_env/universal/meshhealthcheck/policy.go
Name should match upstream Gateway API
=> fix(MeshHTTPRoute): rename Prefix to PathPrefix

tools/releases/dockerfiles/kumactl.Dockerfile
Without specifying entrypoint inside the Dockerfile, it was impossible to use the image without having to do it explicitly during the container start
It was impossible to do:
```sh
docker run kumahq/kumactl:2.2.0 kumactl version
```
and you had to explicitly specify entrypoint
```sh
docker run --entrypoint /usr/bin/kumactl kumahq/kumactl:2.2.0 version
```
before:
```sh
docker run kumahq/kumactl:2.0.0 kumactl version
```
Closes: https://github.com/kumahq/kuma/issues/6566
=> fix(docker/kumactl): add entrypoint to kumactl img

test/framework/constants.go, test/framework/interface.go, test/framework/k8s_controlplane.go, test/framework/setup.go, test/framework/universal_controlplane.go
This conflicts with the default `nodePort` for the `global-zone-sync` `Service` and a Helm install is run concurrently with this test leading to flakes:
https://app.circleci.com/pipelines/github/kumahq/kuma/20794/workflows/68999f88-2cef-49e3-8a68-332c1a9fb6c8/jobs/365684
The `kdsPort` constants were messy and being used for both Helm and Universal tests.
=> test(e2e): use different KDS port

test/e2e_env/multizone/externalservices/externalservices_multizone_universal.go, test/e2e_env/universal/externalservices/externalservices.go, test/e2e_env/universal/externalservices/zoneegress_externalservices.go, test/e2e_env/universal/ratelimit/ratelimit.go, test/e2e_env/universal/trafficroute/traffic_route.go, test/framework/setup.go
See https://app.circleci.com/pipelines/github/kumahq/kuma/21477/workflows/8c964ced-ff4a-440e-a22b-684acc13df40/jobs/388320
=> test(e2e): fix app name collision flake

tools/releases/dockerfiles/kuma-cni.Dockerfile, tools/releases/dockerfiles/kuma-cp.Dockerfile, tools/releases/dockerfiles/kuma-dp.Dockerfile
To be consistent now all docker images have entrypoints in the form of absolute path.
I also adjusted the style of the kuma-cni dockerimage to be consistent with others in regards of new lines between instructions and spacing around item in entrypoint.
> Changelog: ci(dockerfiles): make entrypoins absolute path + adjust style in regards of empty lines and spacing around value of entrypoint in kuma-init dockerfile
=> ci(dockerfiles): make entrypoints absolute

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-legacy-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cni-daemonset.yaml, deployments/charts/kuma/values.yaml
Also make the `runAsNonRoot: false` more visible.
=> feat(helm): set readOnlyRootFilesystem on CNI, more explicit templates

pkg/core/bootstrap/bootstrap.go, pkg/test/runtime/runtime.go, pkg/xds/runtime/context.go
This behavior was unintentionally changed in [#5991](https://github.com/kumahq/kuma/pull/5991/files#diff-b3cc8955e22d15be8a676a46643ccffc5283d26f2c0ef2fb21a73894d4933912L149-R151
)
=> chore(xds): don't overwrite auth handlers in runtime context

tools/container-structure-test/kuma-init.yaml, tools/container-structure-test/kumactl.yaml
The entrypoint for kumactl image changed. I also adjusted iptables check in kuma-init container structure test and removed check if iptables is "legacy" or not as it's irrelevant.
xref: https://github.com/kumahq/kuma/pull/6596
=> ci(docker/tests): update container structure tests

tools/container-structure-test/kuma-init.yaml
Don's check if iptables are legacy, as this check is irrelevant and makes reusability if container structure tests harder.
xref. https://github.com/kumahq/kuma/pull/6621
=> ci(test/docker): don't check for legacy iptables

pkg/envoy/admin/tls/pki.go, pkg/xds/sync/dataplane_watchdog.go
As Egress doesn't have advertisedAddress.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> feat(mtls): generate certificates for Address and AdvertisedAddress for Dataplane and Ingress

test/e2e_env/universal/matching/matching.go, test/e2e_env/universal/mtls/mtls.go, test/e2e_env/universal/ratelimit/ratelimit.go
Now we store artifacts for failed Universal tests. Let's remove FlakeAttempts and try to catch failures on CI.
=> test(e2e): remove FlakeAttempts

pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go, pkg/plugins/runtime/k8s/controllers/inbound_converter.go, pkg/plugins/runtime/k8s/util/util.go, pkg/plugins/runtime/k8s/util/util_test.go, test/e2e/gateway/gatewayapi/conformance_test.go
See https://gateway-api.sigs.k8s.io/geps/gep-1426/ for any questions about how this should actually work.
~Blocked by https://github.com/kumahq/kuma/pull/6614~
=> feat(GatewayAPI): initial GAMMA support

app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.cni-legacy-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml, app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cp-deployment.yaml, deployments/charts/kuma/values.yaml
---
This PR is to add support for setting the Kuma CP log path when deploying via helm.
=> feat(helm): Add logOutputPath support to chart

mk/test-container-structure.mk
=> test(container-structure): don't run kuma-init test

mk/k3d.mk, mk/metallb-k3d-kuma-1.yaml, mk/metallb-k3d-kuma-2.yaml, mk/metallb-k3d.yaml
This keeps us independent of servicelb changes arbitrarily depending on the k8s version, see https://github.com/kumahq/kuma/pull/6365
It also appears to allocates a separate IP for each LoadBalancer as opposed to a port on the same IP for each LoadBalancer... 
=> ci(k8s): use metallb instead of servicelb

pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
This is the default for this field so don't be strict about setting `: ""`.
=> chore(GatewayAPI): allow gatewayapi group name for GAMMA parentRefs

go.mod, go.sum, test/e2e/gateway/gatewayapi/conformance_test.go
=> chore(deps): bump gateway-api to v0.7.0-rc1

mk/k3d.mk
=> ci(mk): use KUMA_DIR in metallb resources path

pkg/kds/server/components.go, pkg/kds/server/status_sink.go, pkg/kds/server/status_tracker.go, pkg/kds/v2/server/components.go, pkg/kds/v2/server/status_tracker.go
Fixing changes from the PR merged in the last week. There was a wrong assumption about zone sink. It does not make sense to iterate through all tenants in the context of zone sink. Zone sink is run for every single zone, so proper approach is to propagate the context.
=> fix(kds): multitenancy sink

mk/k3d.mk, test/e2e_env/universal/auth/offline_auth.go, test/e2e_env/universal/auth/user_auth.go, test/framework/deployments/postgres/deployment.go, test/framework/deployments/postgres/kubernetes.go, test/framework/envs/kubernetes/env.go, test/framework/envs/multizone/env.go, test/framework/envs/universal/env.go, test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/k8s_controlplane.go, test/framework/kumactl.go, test/framework/universal_cluster.go, test/framework/universal_controlplane.go
* Add functionality to add headers to API requests.
* Skip retrieving admin tokens if auth type is different.
* Add functionality to configure postgres password.
* Don't know exactly why volume mount was added, see PR below.
Deprecates https://github.com/kumahq/kuma/pull/6642
=> test(e2e): configurable headers to api requests

mk/k3d.mk
If `~` has an `@` in it this is broken otherwise:
```
FATA[0000] Invalid flag '/Users/michael.beaumont@konghq.com/projects/kuma/test/framework/deployments:/tmp/deployments@server:0': only one unescaped '@' allowed for node filter(s) (Escape literal '@' with '\')
```
=> ci(k3d): escape @ in volume path

pkg/kds/context/context.go, pkg/kds/global/components.go, pkg/kds/mux/server.go
Add a way to configure server stream interceptors using KDS Context.
=> feat(kds): configurable server stream interceptors

pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
=> fix(GatewayAPI): respect Service port in parentRef

test/e2e/gateway/gatewayapi/conformance_test.go, test/framework/k8s.go
=> test(e2e): install v0.7.0-rc1 Gateway API CRDs

app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml, app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml, app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml, deployments/charts/kuma/templates/_helpers.tpl, deployments/charts/kuma/templates/egress-deployment.yaml, deployments/charts/kuma/templates/ingress-deployment.yaml
IIUC currently there is a bug that appears when the user has set `secretName` but not `caSecretName`, which is allowed. In this case, the `Secret` `secretName` is supposed to have the `ca.crt` value so the CA should be fetched from there. But the chart as is uses the default `Secret`, which won't have been created, leading to an error starting the ingress/egress `Pods`.
=> fix(helm): use correct secret for CP CA in ingress/egress

pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
At the moment this silently fails, which is bad. For `MeshHTTPRoute` I think we can assume that destinations are HTTP.
=> fix(MeshHTTPRoute): assume protocol is HTTP

docs/madr/decisions/024-disable-default-policies.md
=> feat(mesh): MADR for disabling default policy creation

pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go
=> fix(GatewayAPI): don't panic if an HTTPRoute references a Gateway with a nonexistent GatewayClass

pkg/kds/v2/reconcile/reconciler.go, pkg/kds/v2/server/components.go, pkg/kds/v2/server/server_suite_test.go, pkg/kds/v2/server/tenant_callback.go, pkg/kds/v2/server/tenant_callback_test.go, pkg/kds/v2/util/multitenancy.go, test/framework/interface.go, test/framework/k8s_cluster.go, test/framework/kumactl.go, test/framework/universal_cluster.go
Make KDS multitenant. Propagate tenant from context to node metadata via callbacks.
Additionally, I made adjustments to E2E framework to be able to pass zone name.
Fix #6632
=> feat(kds): multitenancy

pkg/metrics/components/cp_info.go, pkg/metrics/store/counter.go, pkg/metrics/store/counter_test.go
Fix #6622
If there are multiple tenants, produce metrics for each tenant.
=> feat(kuma-cp): multitenant counter metrics

.github/workflows/backport.yaml, CONTRIBUTING.md
We use this when adding the `backport` label
=> ci(.github): add backport action to replace mergify

pkg/api-server/resource_endpoints.go, pkg/api-server/server.go, pkg/plugins/resources/k8s/mapper.go, pkg/plugins/resources/k8s/mapper_test.go, test/e2e_env/kubernetes/api/api.go, test/e2e_env/kubernetes/kubernetes_suite_test.go
For any GET call an optional parameter `?format=k8s` can be passed to get the resource as a k8s resource.
You can also use `?namespace=<whatever>` to use a override the namespace.
This aims to have the UI always show universal resources and only provide a `copy as k8s` button that does this call.
Fix #6658
=> feat(api-server): add ability to get k8s format of a resource

pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
Important for example if a Secret appears or disappears and it's used in an HTTPS listener.
=> fix(GatewayAPI): reconcile Gateways on Secret changes

app/kumactl/cmd/install/install_control_plane_test.go, deployments/charts/kuma/templates/_helpers.tpl
=> feat(helm): validate zone name on install

.circleci/config.yml, mk/k3d.mk
The CircleCI UI is horrible and everything after `:` is hidden.
See [before](https://app.circleci.com/pipelines/github/kumahq/kuma/21807/workflows/dfa05249-ea74-4a76-9f62-6fe5901b7d67) vs ~[after](https://app.circleci.com/pipelines/github/kumahq/kuma/21815/workflows/f54ff654-affe-4474-bd22-4c9a82205e96)~ [after](https://app.circleci.com/pipelines/github/kumahq/kuma/21895/workflows/820c2cb7-da85-4e3b-ba46-a1346c783dc6)
=> ci(.circleci): don't prefix all jobs with 'test/e2e'

test/framework/deployments/postgres/deployment.go, test/framework/deployments/postgres/kubernetes.go
=> test(e2e): add option to set init scripts for postgres

docs/madr/decisions/026-meshgateway-targetref.md
This just addresses the gateway and its listeners, not routes.
I think it's also a good place to discuss what it could or would mean for `spec.to.targetRef.kind: MeshGateway`.
[Rendered](https://github.com/michaelbeaumont/kuma/blob/docs/madr-meshgateway-kind/docs/madr/decisions/026-meshgateway-targetref.md)
=> docs(MADR): `MeshGateway` as `targetRef.kind`

pkg/intercp/components.go
=> fix(multitenancy): global tenant in intercp when creating certs

pkg/plugins/policies/meshtimeout/plugin/testdata/basic_inbound_listener.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/default_inbound_listener.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/default_outbound_listener.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/http_outbound_listener.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/modified_inbound_listener.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/modified_outbound_listener.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/outbound_with_defaults_listener.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
=> fix(kuma-cp): reset idleTimeout from the old Timeout policy

.golangci.yml
`staticcheck` and `gosec` don't see any errors anymore
=> ci(lint): clean up useless excluded-rules from golangci-lint.yml

pkg/events/eventbus.go, pkg/events/interfaces.go, pkg/insights/resyncer.go, pkg/plugins/resources/postgres/events/listener.go, pkg/plugins/resources/postgres/migrations/data/1610445956_update_notify_event.up.sql
Fix #6746
Remove iterating over all tenants in resyncer.
Give possibility to plug in tenant to events.
=> feat(multitenancy): postgres events

pkg/insights/resyncer.go
Take into account tenant id when storing info about insights.
=> feat(insights): include tenant id in insights info key

test/framework/deployments/testserver/deployment.go, test/framework/deployments/testserver/kubernetes.go
It's functionality helpful for writing e2e tests for MeshTCPRoute in the future
- there are no relevant issues
- I tested it manually on k3d cluster
- no need as it's a change for e2e tests framework
- it doesn't
=> test(e2e/framework): allow to set protocol for test-server

pkg/plugins/policies/meshtcproute/api/v1alpha1/meshtcproute.go, pkg/plugins/policies/meshtcproute/api/v1alpha1/schema.yaml, pkg/plugins/policies/meshtcproute/api/v1alpha1/validator.go, pkg/plugins/policies/meshtcproute/api/v1alpha1/validator_test.go, pkg/plugins/policies/meshtcproute/api/v1alpha1/zz_generated.deepcopy.go, pkg/plugins/policies/meshtcproute/k8s/crd/kuma.io_meshtcproutes.yaml
There is currently no validation if the
`to.rules[].default.backendRefs` doesn't direct the traffic to the same target as matched in `to.targetRef`.
It means the configuration as below is valid:
```yaml
targetRef:
kind: MeshService
name: frontend
to:
- targetRef:
kind: MeshService
name: backend
rules:
- default:
backendRefs:
- targetRef:
kind: MeshService
name: backend
```
Why are we not disallowing it during the validation you might ask? We don't as:
- it's non-breaking behaviour to have a route which direct the traffic to the same destination
- it would involve doing very heavy validation otherwise (we would have to compute potential splits and check it summarized backendRefs don't point to the same destination etc.)
- there is assumption that route-policies like `MeshTCPRoute` will in …
=> chore(MeshTCPRoute): make to[].rules optional

app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml, deployments/charts/kuma/README.md, deployments/charts/kuma/templates/cp-global-sync-service.yaml, deployments/charts/kuma/templates/cp-service.yaml, deployments/charts/kuma/values.yaml
=> feat(helm): enable NodePort customization

go.mod, go.sum
=> chore(deps): bump gateway-api to have more conformance tests

mk/e2e.new.mk
It wasn't guaranteed that even the nodes exist by the time we try to load the images here.
=> ci(mk): fix cluster starting and image loading dependencies

go.mod, go.sum, pkg/plugins/runtime/gateway/route/sorter.go, pkg/plugins/runtime/gateway/route/sorter_test.go, pkg/plugins/runtime/gateway/route/table.go
=> fix(MeshGateway): tweak route precedence to match Gateway API

pkg/plugins/policies/meshtcproute/api/v1alpha1/helpers.go
Rules may be empty, which might cause out of index access errors. In this case we are constructing the rule with the values from the `to[].targetRef`.
- it won't
- there is no need as the policy was not yet released
- there is no need as the policy was not yet released
=> chore(MeshTCPRoute): fix GetDefault for the policy

pkg/plugins/policies/xds/cluster.go, pkg/xds/envoy/listeners/v3/tcp_proxy_configurer.go, pkg/xds/envoy/types.go
This setting is necessary to allow MeshTCPRoute to create "splits" without the need of using deprecated abstractions like ClusterImpl. I also think it's quite elegant solution which allows to remove type assertion to ClusterImpl in TcpProxyConfigurator, when there are more clusters provided as parameters.
- it won't
- tested manually
- there is no need, as so use this feature, it has to be explicit
- it doesn't
=> chore(kuma-cp): add weights to xds.Cluster interface

test/e2e_env/kubernetes/meshtcproute/test.go
When both `MeshHTTPRoute` and `MeshTCPRoute` sources and destination matches, `MeshHTTPRoute` should take precedence.
- It won't as this PR contains only new e2e test
- This PR contains e2e test, which is currently "paused", till the full implementation will be finished
- You don't as it's only e2e test + this policy was not yet released
- You don't as it's only e2e test + this policy was not yet released
=> test(MeshTCPRoute): add e2e test for colision with MeshHTTPRoute

test/e2e_env/kubernetes/meshtcproute/test.go
Very small fix in the name of service in e2e test case for MeshTCPRoute
- it won't
- it's a fix in an e2e test case actually
=> test(MeshTCPRoute): small name fix in e2e test case

pkg/plugins/runtime/k8s/controllers/gatewayapi/common/reconcile.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go, pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
=> fix(GatewayAPI): properly handle owned MeshHTTPRoutes

pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin.go, pkg/plugins/policies/xds/meshroute/clusters.go, pkg/plugins/policies/xds/meshroute/endpoints.go, pkg/plugins/policies/xds/meshroute/listeners.go
As for `MeshTCPRoute` endpoints and clusters generation will be the same instead of copying this code, I took it out and made it reusable.
I had also changed `GetClusterName` definition, to be reusable, so instead of taking concrete targetRefs from `MeshHTTPRoute`, now we need to provide `name` and `tags` as separate arguments.
- It will not, as these changes are not modifying functionality and touches only internal API
- That's the good question - should I add unit tests for now exported functions? 🤔 
- there is no need, as it's not changing any logic
- there is no need as these changes are necessary only for non-released yet `MeshTCPRoute` policy, which won't be backported
[1]: …
=> refactor(MeshHTTPRoute): pull up parts of xds generation

pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/mixed-tcp-and-http-outbounds.clusters.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/mixed-tcp-and-http-outbounds.endpoints.golden.yaml, pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/mixed-tcp-and-http-outbounds.listeners.golden.yaml
Closes: https://github.com/kumahq/kuma/issues/6860
=> fix(MeshHTTPRoute): only configure HTTP outbounds or with an explicit matching rule

pkg/core/plugins/registry.go
This check defeats the purpose of resource store plugin. You can put resource store in BeforeBootstrap, but it's then overridden by plugin. You cannot put your resource store in AfterBootstrap because it's used across all components during bootstrap
=> feat(kuma-cp): allow to override resource store plugin

tools/releases/dockerfiles/kuma-init.Dockerfile
Update iptables dependency version in kuma-init docker image
- no relevant issue, but it fixes filing CI (i.e. https://app.circleci.com/pipelines/github/kumahq/kuma/22376/workflows/6ffa62a1-0551-4be7-9aaf-317b151fa849/jobs/417059)
- it won't
- it's just dependency update for the kuma-init docker image - no tests
- that's the good question - I'm not sure to be honest
=> chore(image/kuma-init): update iptables depencendy version

pkg/plugins/runtime/gateway/route/configurers.go, pkg/plugins/runtime/gateway/testdata/http/05-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/06-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/09-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/10-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/11-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/13-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/drop-prefix-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/response-header-set-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/rewrite-prefix-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/http/rewrite-prefix-trailing-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/05-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/06-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/09-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/10-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/11-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/13-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/drop-prefix-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/response-header-set-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/rewrite-prefix-gateway-route.yaml, pkg/plugins/runtime/gateway/testdata/https/rewrite-prefix-trailing-gateway-route.yaml
1. Setting `EngineType` is optional from Envoy v1.24 (ref. https://github.com/envoyproxy/envoy/issue/24256#issuecomment-1333078240) so we can safely remove:
```
EngineType: &envoy_type_matcher.RegexMatcher_GoogleRe2{
GoogleRe2: &envoy_type_matcher.RegexMatcher_GoogleRE2{},
}
``` 
it means I was also able to remove redundant now helper function `regexOf`.
3. Usage of `HeaderMatcher_SafeRegexMatch` is deprecated in favor of `HeaderMatcher_StringMatch`
4. `HeaderValueOption` instead of `Append` there is suggestion to use: `AppendAction: envoy_config_core.HeaderValueOption_OVERWRITE_IF_EXISTS_OR_ADD`
5. Small typo fix in the comment of `RouteDeleteResponseHeader` function
- it shouldn't
- updated golden files
- I don't believe it does …
=> chore(gateway): remove deprecated envoy APIs from route configurers

pkg/plugins/runtime/gateway/route/configurers.go
1. The logic was wrong - if there is ***NO*** retry policy, we should skip applying retriable methods, not the other way around
2. Before it might crash with nil pointer dereference when we provided httpMethods, but there was no retry policy
- there is no relevant issue
- it won't
- it does I believe
=> fix(gateway): don't skip retry policy with retry methods

deployments/charts/kuma/templates/_helpers.tpl, deployments/charts/kuma/templates/cp-deployment.yaml
=> feat(helm): add possibility to extend secrets for cp in helm charts when reusing kuma charts

pkg/plugins/policies/xds/testutil.go, pkg/test/xds/name_configurer.go, pkg/xds/envoy/clusters/cluster_builder.go, pkg/xds/envoy/clusters/configurers.go, pkg/xds/envoy/listeners/filter_chain_builder.go, pkg/xds/envoy/listeners/listener_builder.go, pkg/xds/envoy/routes/route_configuration_builder.go, pkg/xds/envoy/routes/virtual_host_builder.go
In the quest of simplifying our code base I found that structures `*BuilderConfig` are completely unnecessary and only obscure our code base to the point I had to draw on paper all the structures necessary to build one portion of envoy configuration.
I believe removing them doesn't remove any functionality and make everything a bit simpler.
When moving `*BuilderConfig.AddV3` methods to `*Builder` structs, instead of using the name `AddV3`, I changed it to `AddConfigurer` and stripped V3 from the name, as we currently don't have any V2 configurers.
- there is no relevant issue
- it won't
- it's a refactor, so existing tests should be enough
- there is no need, as it's not an user facing change
- it doesn't
[1]: https://docs.github.com/en/issues/tracking-your-work-with-iss …
=> refactor(xds/builders): remove redundant structures

pkg/kds/server/status_sink.go, test/e2e_env/multizone/resilience/resilience_multizone_universal_postgres.go
When we are using parent context and the stream is canceled function responsible for flushing stats to the database is also canceled and fails. We need a separate context that still can flush data after the parent context is closed but the stream is not fully destroyed. That happens when using pgx and postgres. I am not sure if this is the best way to fix it.
=> fix(kuma-cp): make zone insight context independent from parent

mk/build.mk, mk/docker.mk
That allows other projects using Kuma to define test-specific binaries without overriding the default one.
=> chore(build): append values of test binaries and images

pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
We need to apply configuration to clusters regardless of whether there is a corresponding outbound listener.
=> refactor(MeshTimeout): untangle cluster and listener configuration

pkg/intercp/envoyadmin/forwarding_kds_client.go, pkg/kds/service/server.go
ZoneInsight sets ownership to Zone therefore we cannot create ZoneInsight without Zone. When Zone CP starts it initiates KDS, xds config, stats and cluster streams at the same time. There is a high chance that the zone was not yet created by KDS stream and xds config, stats, cluster is terminated. 
=> fix(kuma-cp): wait for zone to create insights with admin streams

pkg/plugins/runtime/k8s/controllers/pod_controller.go
=> perf(k8s): omit fetching other dataplanes when vips are in the config map

mk/check.mk
use git diff for diff and disable pager so the ci is not stuck waiting for exit
=> ci(mk): disable pager in `make check`

pkg/gc/finalizer.go
Finalizer keeps state between comparisons in the map that has a key `mesh` and `name(zone name)`. In case there are multiple tenants with the same zone name, that might cause changes to one tenant and impact another with the same name.
=> fix(kuma-cp): make finalizer tenant aware

tools/releases/version.sh
=> chore(deps): upgrade envoy to 1.25.7

pkg/plugins/runtime/gateway/filter_chain_generator.go
Accidentally resolved a comment on #6952 before GH picked up the new commit.
=> chore(MeshGateway): remove old comment

pkg/plugins/policies/meshtimeout/plugin/testdata/no-route-level-timeouts.gateway.cluster.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/no-route-level-timeouts.gateway.listener.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/testdata/no-route-level-timeouts.gateway.route.golden.yaml, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go, pkg/test/resources/builders/gateway_route_builder.go
See the test expectation difference.
=> fix(MeshTimeout): only apply Mesh targeted HTTP timeouts for MeshGateway

pkg/plugins/runtime/k8s/controllers/pod_controller.go, pkg/plugins/runtime/k8s/controllers/pod_controller_test.go
- only reconcile pods that are selected by this service
- don't reconcile pods when external services are updated
Fix #6985
=> perf(k8s): don't reconcile all pods when a service changes

mk/generate.mk
I tend to sync code across my MacBook and linux VM. Because tools are synced, the binaries don't work on the other system. This PR adds GOOS and GOARCH to tools directory name just like we do for other build artifacts
=> ci(makefile): build platform dependent tools

pkg/kds/context/context.go
Remove function nesting for `MapZoneTokenSigningKeyGlobalToPublicKey` resource mapper as we were not using any of the provided arguments.
- It won't as it doesn't change the functionality
- No new tests, as this is just pure, small refactor, without changes in functionality
> Changelog: refactor(kuma-cp/kds): remove unnecessary function nesting for MapZoneTokenSigningKeyGlobalToPublicKey resource mapper in kds context
=> refactor(kuma-cp/kds): remove unnecessary function nesting for mapper

go.mod, go.sum, test/framework/k8s.go
=> chore(deps): bump gateway-api with more conformance tests

pkg/core/bootstrap/bootstrap.go, pkg/kds/context/context.go, pkg/kds/context/context_test.go, pkg/kds/util/resource.go, pkg/kds/util/resource_test.go, pkg/kds/util/util_suite_test.go, pkg/kds/v2/client/zone_sync_test.go, pkg/kds/zone/components_test.go, pkg/test/resources/model/resource.go, pkg/test/runtime/runtime.go
Trim system namespace suffix from names of plugin originated policies when syncing resources from global to zones in multizone mode.
Closes: https://github.com/kumahq/kuma/issues/6999
- https://github.com/kumahq/kuma/issues/6999
- It won't
- Added unit tests + manually tested on k3d clusters
> Changelog: fix(kuma-cp/multizone): trim system namespace suffix from names of plugin originated policies when syncing resources from global to zones in multizone mode.
=> fix(kuma-cp/multizone): trim namespace suffix from plugin policies names

pkg/core/resources/manager/manager.go
We retry upsert on resource conflict, but in a case when there are two parallel upserts that creates a resource, the error will be resource already exist, not resource conflict
=> feat(resources): retry upsert on resource already exist

api/mesh/v1alpha1/dataplane_helpers.go, pkg/xds/generator/ingress_generator.go, pkg/xds/ingress/dataplane.go, pkg/xds/ingress/outbound.go
It's unnecessary to assume concrete type if underlying one is `map[string]string`. It makes it slightly more reusable.
- There is no relevant issue
- It won't
- There are no new tests and all existing unit tests are passing
- There is no need as this change should be transparent
=> refactor(helper): make mesh_proto.Merge helper function generic

pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshretry/plugin/v1alpha1/testdata/gateway.http.routes.golden.yaml, pkg/plugins/policies/meshretry/plugin/v1alpha1/testdata/grpc.listeners.golden.yaml, pkg/plugins/policies/meshretry/plugin/v1alpha1/testdata/http.listeners.golden.yaml, pkg/plugins/policies/meshretry/plugin/xds/configurer.go
The gateway plugin sets them on the routes so these weren't taking effect given the default retry.
=> fix(MeshRetry): set MeshGateway retry on routes not virtual hosts

pkg/plugins/policies/core/matchers/dataplane.go
If we return an error when unable to resolve TargetRef (i.e. typo in MeshHTTPRoute name) then:
* Unable to build DPP config
* Inspect API returns error
Current PR replaces err with a log. Ideally we need a mechanism like https://github.com/kumahq/kuma/issues/5870 to process such kind of errors.
=> fix(kuma-cp): replace err with log when TargetRef can't be resolved

api/mesh/v1alpha1/dataplane_helpers.go
Very small optimization in dataplane helpers for tags merging, to not iterate over the whole map if only one argument is passed, as we can safely return the argument itself then.
- https://github.com/kumahq/kuma/pull/7030#discussion_r1230725147
- It won't as it's very small optimization
- There is no new tests as it's very small optimization
> Changelog: feat(kuma-cp/helpers): skip iteration over the whole map when only one argument is passed in dataplane helper function: `TagSet.Merge`
=> feat(kuma-cp/helpers): skip iteration when only one arg. in tags merge

go.mod, go.sum
=> chore(deps): bump k8s.io/apiextensions-apiserver from 0.27.2 to 0.27.3

pkg/plugins/policies/core/xds/listeners.go, pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go, pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/testdata/apply-egress.golden.yaml, pkg/test/resources/builders/mesh_builder.go, pkg/xds/envoy/listeners/filter_chain_configurers.go, pkg/xds/envoy/listeners/v3/filter_chain_name_configurer.go, pkg/xds/envoy/names/resource_names.go, pkg/xds/generator/egress/external_services_generator.go, pkg/xds/generator/egress/generator.go, pkg/xds/generator/egress/testdata/01.externalservice-only.golden.yaml, pkg/xds/generator/egress/testdata/03.mixed-services.golden.yaml, pkg/xds/generator/egress/testdata/04.mixed-services-custom-trafficroute.golden.yaml, pkg/xds/generator/egress/testdata/05.mixed-services-with-custom-trafficpermissions.golden.yaml, pkg/xds/generator/egress/testdata/06.mixed-services-with-external-in-other-zone.golden.yaml, test/e2e_env/multizone/meshtrafficpermission/meshtrafficpermission.go
=> feat(kuma-cp): implement MeshTrafficPermisson for ExternalServices with ZoneEgress

pkg/plugins/runtime/k8s/controllers/kube_hosts_converter.go, test/e2e_env/kubernetes/connectivity/headless_services.go, test/e2e_env/kubernetes/kubernetes_suite_test.go
We took target port instead of port for headless services, so whenever there was a headless service with port != target port it wouldn't work.
=> fix(kuma-cp): use port instead of target port of a headless service

CODEOWNERS, GOVERNANCE.md, OWNERS.md
As part of our aim to apply for incubation we need to revamp our Governance process.
As there's no steering committee yet. This will be submitted to a 1/2 vote from the current active maintainers.
=> chore(community): update governance.md

.github/workflows/lifecycle.yml
=> ci(.github): ignore sync of CONTRIBUTING.md

test/e2e_env/kubernetes/connectivity/headless_services.go, test/e2e_env/kubernetes/kubernetes_suite_test.go
I also changed the order of a test to see if this is really caused by this headless test or is it just because it's the first test
=> test(e2e): fix mesh in headless service test

pkg/plugins/runtime/k8s/metadata/annotations.go, pkg/plugins/runtime/k8s/webhooks/injector/injector.go, pkg/plugins/runtime/k8s/webhooks/injector/injector_test.go, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.32.golden.yaml, pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.32.input.yaml
Fixes #6082 
Docs: https://github.com/kumahq/kuma-website/pull/1365
=> feat(webhook): make init ordering configurable first/last

docs/generated/kuma-cp.md, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/dns/vips/persistence.go, pkg/dns/vips/persistence_test.go
=> fix(kuma-cp): add backward compatible reading of virtual outbound from config

UPGRADE.md
=> docs(UPGRADE.md): new mandatory fields for MeshTrace and MeshAccessLog

app/kuma-dp/pkg/dataplane/metrics/server.go, app/kuma-dp/pkg/dataplane/metrics/server_test.go, test/e2e_env/universal/observability/applications_metrics.go
This reverts commit b178614aa2bcbd02691b4f016c1499df43229d30.
Reverted PR: https://github.com/kumahq/kuma/pull/6783
=> Revert "fix(kuma-dp): honour app content-type (#6783)"

pkg/plugins/policies/meshhttproute/xds/builder.go, pkg/plugins/runtime/gateway/route_configuration_generator.go, pkg/xds/envoy/listeners/v3/http_inbound_routes_configurer.go, pkg/xds/envoy/listeners/v3/http_outbound_route_configurer.go, pkg/xds/envoy/routes/configurers.go, pkg/xds/envoy/routes/route_configuration_builder.go, pkg/xds/envoy/routes/v3/common_route_configuration_configurer.go, pkg/xds/envoy/routes/v3/reset_tags_header_configurer_test.go, pkg/xds/envoy/routes/v3/tags_header_configurer_test.go, pkg/xds/envoy/virtualhosts/virtual_host_configurer_test.go, pkg/xds/generator/probe_generator.go, pkg/xds/generator/testdata/probe/01.envoy.golden.yaml, pkg/xds/generator/testdata/probe/03.envoy.golden.yaml, pkg/xds/generator/testdata/probe/04.envoy.golden.yaml
Defines the route configuration name as a required field for the builder constructor function and adds a validation in the final build function to throw an error if the field is blank.
It also removes the name assignation from common route configuration configurers. It asserts that the name shall be known when the builder is instantiated.
=> feat(xds): named resources (routes configuration) builders require name

pkg/api-server/server.go
In this PR https://github.com/kumahq/kuma/pull/5979 we introduced a change when user can set mTLS and still use tokens.
With this change, we set `VerifyClientCertIfGiven` always which is not correct if someone does not want to do mTLS. `VerifyClientCertIfGiven` was required in the first place for adminClientCert auth method.
=> fix(kuma-cp): do not require certs on https api port

pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/basic-gateway.gateway.listener.golden.yaml
=> chore(MeshAccessLog): fix bad merge of #7112

test/framework/k8s_cluster.go
=> feat(e2e): add possibility to configure kubeconfig location in e2e test cluster

pkg/plugins/runtime/k8s/controllers/inbound_converter.go, pkg/plugins/runtime/k8s/controllers/pod_converter_test.go, pkg/plugins/runtime/k8s/controllers/testdata/01.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/10.dataplane.yaml, pkg/plugins/runtime/k8s/controllers/testdata/11.dataplane.yaml
Also allow the `kuma.io` annotation to set the protocol if the `appProtocol` isn't understood.
=> fix(k8s): tolerate unknown `appProtocol`

test/framework/deployments/observability/deployment.go, test/framework/deployments/observability/kubernetes.go
1. observability deployment had a dependency on Kuma with `cluster.GetKuma().GetName()`, but Kuma should not be needed to deploy it
2. Using it without jaeger was impossible. If you do `WithComponent(prometheus)` the code was still trying to port forward jaeger.
3. I also used a couple of test helpers to shorten the code.
=> test(e2e): improve observability deployment

pkg/plugins/policies/meshtimeout/api/v1alpha1/validator.go, pkg/plugins/policies/meshtimeout/api/v1alpha1/validator_test.go
=> feat(MeshTimeout): allow top level targetRef.kind MeshGateway

pkg/plugins/runtime/opentelemetry/plugin.go
=> fix(kuma-cp): don't return from opentelemetry Start

pkg/core/bootstrap/bootstrap.go, pkg/metrics/components/cp_info.go, pkg/metrics/metrics.go, pkg/plugins/bootstrap/k8s/plugin.go
Fix #2927
This is a bit tricky, because Kube Controller Manager registers all the metrics in `init()` methods.
Because of this we cannot easily replace their `kube_metrics.Registerer` with our instance. Instead, we can take their instance and use it to register our metrics and use their gatherer to our metrics server.
I wanted to prefix all Kube Controller Manager metrics, but it seems to be quite hard to do. I tried with `prometheus.WrapRegistererWithPrefix`, but all metrics are already registered after I try to swap it. We could try to have a custom Gatherer implementation and add prefix to kube metrics, but it would require to explicitly have a list of kube metrics, we would need to maintain and update it.
Kube Controller Manager also registers standard Go metrics that we register so …
=> feat(metrics): expose kube controller manager metrics

pkg/api-server/testdata/auth-admin-https-bad-creds.golden.json, pkg/api-server/testdata/auth-admin-non-localhost.golden.json, pkg/api-server/testdata/inspect_xds_remote_zoneingress.json, pkg/api-server/testdata/resource-delete_not-found.golden.json, pkg/api-server/testdata/resource-read-only_delete.golden.json, pkg/api-server/testdata/resource-read-only_put.golden.json, pkg/api-server/testdata/resource_incoherent-mesh.golden.json, pkg/api-server/testdata/resource_incoherent-names.golden.json, pkg/api-server/testdata/resource_incoherent-types.golden.json, pkg/api-server/testdata/resource_invalid-conf.golden.json, pkg/api-server/testdata/resource_mesh-not-found.golden.json, pkg/api-server/testdata/resource_name-mesh.golden.json, pkg/api-server/testdata/resource_name-too-long.golden.json, pkg/api-server/testdata/resource_not-found.golden.json, pkg/api-server/testdata/resource_page-offset-invalid.golden.json, pkg/api-server/testdata/resource_page-size-invalid.golden.json, pkg/api-server/testdata/resource_page-size-too-large.golden.json, pkg/core/rest/errors/error_handler.go, pkg/core/rest/errors/types/error.go, pkg/plugins/authn/api-server/tokens/ws/testdata/ws-0-validFor.golden.json, pkg/plugins/authn/api-server/tokens/ws/testdata/ws-missing-validFor.golden.json, pkg/plugins/authn/api-server/tokens/ws/testdata/ws-no-name.golden.json, pkg/plugins/authn/api-server/tokens/ws/testdata/ws-token-issuer-disabled.golden.json
=> feat(api): error status is an int

test/framework/deployments/postgres/kubernetes.go
=> test(e2e): pin postgres chart version

.github/workflows/helm-release.yaml
Due to a bug in `checkout` action mentioned here https://github.com/actions/checkout/issues/1359 we need to explicitly set `ref` to have the proper SHA put in helm charts on pull requests builds.
=> fix(helm): due to a bug in checkout action we need to use github.sha

pkg/xds/context/mesh_context_builder.go, test/e2e_env/kubernetes/externalservices/permissive_mtls.go, test/e2e_env/kubernetes/kubernetes_suite_test.go
While technically it's not an issue on master I want to have test/code parity between master an release-2.3 branch.
On the release branch we have `.Dataplanes.Total` which we don't fill anymore, therefore we had to switch to Offline + Online.
On the release branch Service Insight for some reason increment number of Total DP, but does not increment Offline nor Offline so we end up with `false` on 
`insight.IssuedBackends[backend.Name] == insight.Dataplanes.Total` condition.
Fix #7140
=> fix(kuma-cp): handle external services with permissive mtls

pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator.go, pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator_test.go
=> feat(MeshHealthCheck): allow top level targetRef kind MeshGateway

pkg/plugins/policies/meshretry/api/v1alpha1/validator.go, pkg/plugins/policies/meshretry/api/v1alpha1/validator_test.go
#6956 
https://github.com/kumahq/kuma-website/issues/1393
=> feat(MeshRetry): allow top level targetRef kind MeshGateway

go.mod, go.sum, pkg/util/cache/prometheus_status_counter.go, pkg/xds/auth/components/components.go, pkg/xds/auth/k8s/authenticator.go, pkg/xds/metrics/metrics.go, pkg/xds/runtime/context.go, pkg/xds/server/components.go
This PR adds missing observability to k8s auth cache.
Additionally we may want to switch to go burrow for other caches (to have bounded cache), however I don't want to do it in this PR.
Prometheus stats counter is in utils, because it will be reused in Kong Mesh.
=> feat(kuma-cp): add observability to k8s auth cache

pkg/kds/mux/server.go
Stream traces aren't especially useful here and they last quite a long time.
=> chore(kuma-cp): don't include otelgrpc Stream intercepter

.github/dependabot.yml
=> ci(dependabot): add group for k8s libs

test/framework/envoy_admin/tunnel/k8s.go, test/framework/envs/multizone/env.go, test/framework/k8s_cluster.go
Changes: 
* make the port-forward method public so it can be used from other projects without the need to modify k8s_cluster.go
* small refactoring to simplify things
=> ci(e2e): make port-forward methods public

pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go, pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go, test/e2e_env/multizone/meshtrafficpermission/meshtrafficpermission.go
=> fix(MeshTrafficPermission): use serviceName instead of resource name for egress MTP

pkg/xds/server/v3/components.go
For `OnStreamOpen`, they're run in this order and `OnStreamClosed`, in the reverse. We want to have metadata before syncing and want to delete metadata after syncing so this order makes sense.
=> fix(kuma-cp): put metadata xds callbacks before sync

test/framework/k8s_cluster.go, test/framework/k8s_controlplane.go, test/framework/kumactl.go
When using the e2e framework from other projects `kuma_version.Build.Version` could be set to `unknown`. So it's better not to add CLI version flags and rely on `kumactl` version.
=> ci(e2e): don't add version flags to kumactl when version is "unknown"

tools/releases/version.sh
=> chore(deps): bump envoy to 1.24.9

tools/releases/version.sh
=> chore(deps): bump envoy to 1.25.8

tools/releases/version.sh
=> chore(deps): bump envoy to 1.26.3

pkg/plugins/resources/postgres/pgx_store.go
This attribute is necessary for tracing integrations like Datadog, to have full insights into sql queries connected with traces.
ref. https://github.com/DataDog/dd-trace-go/blob/3d97fcec9f8b21fdd821af526d27d4335b26da66/contrib/database/sql/conn.go#L290
- It won't
- Manual tests on private/temporary datadog account
=> ci(tracing): add span.type attribute to pgx tracer

app/kuma-dp/pkg/dataplane/accesslogs/streamer_windows.go
- It won't (it actually fixes it)
- No tests
- There is no need as it was not released yet
=> chore(kuma-dp): fix missing type in accesslogs streamer on windows

app/kuma-dp/pkg/dataplane/metrics/server.go, app/kuma-dp/pkg/dataplane/metrics/server_test.go, app/kuma-dp/pkg/dataplane/metrics/testdata/multi-openmetrics-counter.out, app/kuma-dp/pkg/dataplane/metrics/testdata/openmetrics_0_0_1-counter.out, app/kuma-dp/pkg/dataplane/metrics/testdata/openmetrics_0_1_1.in, app/kuma-dp/pkg/dataplane/metrics/testdata/prom-text-counter.out, app/kuma-dp/pkg/dataplane/metrics/testdata/prom-text.in, test/e2e_env/universal/observability/applications_metrics.go
This reverts commit bba743f5ae5656bb5ea3dd45cf74fdb867f4109f.
=> feat(metrics): support OpenMetrics from applications

mk/kind.mk
=> ci(mk): update kind k8s version to v1.22

pkg/core/tokens/default_signing_key.go, pkg/defaults/envoy_admin_ca.go, pkg/defaults/mesh.go, pkg/defaults/mesh/mesh.go, pkg/log/logger.go, pkg/multitenant/multitenant.go
So the source of truth for tenant ID is just one key in the context.
=> refactor(log): get tenantId from ctx

pkg/core/bootstrap/bootstrap.go, pkg/core/managers/apis/mesh/mesh_manager.go, pkg/core/managers/apis/mesh/mesh_manager_test.go, pkg/core/tokens/default_signing_key.go, pkg/defaults/components.go, pkg/defaults/components_test.go, pkg/defaults/envoy_admin_ca.go, pkg/defaults/envoy_admin_ca_test.go, pkg/defaults/mesh.go, pkg/defaults/mesh/mesh.go, pkg/defaults/mesh/mesh_test.go, pkg/log/logger.go, pkg/plugins/authn/api-server/tokens/plugin.go, pkg/plugins/extensions/logger/context.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go, pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller_test.go, pkg/plugins/runtime/k8s/plugin.go, pkg/test/runtime/runtime.go
By enriching context with span processing function, we can modify default logging behaviour when tracing is enabled from logging `trace_id` and `span_id` fields to something else.
It allows any application which depends on Kuma, but wants to for example transform trace/span idsfrom otel to datadog format, to do that.
- It won't
- Tested manually
=> chore(logging/tracing): allow to modify trace/span id logging

app/kumactl/pkg/client/api_server_client.go
Defines the User-Agent value kumactl/1.0.0 (Linux; amd64; Kuma/a1f30b4) With 
* 1.0.0 : the version of Kuma,
* Kuma : the name of the Product
* a1f30b4 : the short git commit
=> feat(kumactl): define User-Agent

mk/distribution.mk
This resolves an issue with the release process that was causing uploads using the `kong/release-scirpt` container to fail:
```
determining if pulp upload is wanted... yes
usage: release-scripts [-h] {repository,repo,artifact,art,release,rel} ...
release-scripts: error: argument command: invalid choice: '/files/kuma-2.2.3-linux-amd64.tar.gz' (choose from 'repository', 'repo', 'artifact', 'art', 'release', 'rel')
make: *** [mk/distribution.mk:84: publish/pulp/kuma-2.2.3-linux-amd64] Error 2
Exited with code exit status 2
```
=> fix(dist): ensure rel flags are flags

docs/generated/kuma-cp.md, docs/generated/raw/kuma-cp.yaml, pkg/config/app/kuma-cp/config.go, pkg/config/app/kuma-cp/kuma-cp.defaults.yaml, pkg/config/loader_test.go, pkg/metrics/components/cp_info.go
Currently, we are reporting metrics for each resource name with the number of resources. When we introduced multitenancy we also increased the cardinality of the metrics. In the case of many tenants, metrics can be really expensive. Now we are able to disable it because i feel like there is no point to report aggregated metrics with the count of all the resources.
=> feat(kuma-cp): allow to disable resources count metrics

pkg/intercp/catalog/heartbeat_component.go
AFAICT the problem is that [we get a new connection from the pool, at which point it's marked as accessed](https://github.com/kumahq/kuma/blob/fdabfff101ee88134ab1b548e05ee1a8c6c17298/pkg/intercp/client/pool.go#L77) but then [we save it in our struct](https://github.com/kumahq/kuma/blob/fdabfff101ee88134ab1b548e05ee1a8c6c17298/pkg/intercp/catalog/heartbeat_component.go#L131) and [keep using it directly, never marking it as accessed again](https://github.com/kumahq/kuma/blob/fdabfff101ee88134ab1b548e05ee1a8c6c17298/pkg/intercp/catalog/heartbeat_component.go#L107). And [so eventually it's closed due to idleness.](https://github.com/kumahq/kuma/blob/fdabfff101ee88134ab1b548e05ee1a8c6c17298/pkg/intercp/client/pool.go#L105)
This PR makes it so that we always get the connection from the pool. …
=> fix(intercp): properly track idleness of pool connections

test/framework/interface.go
V2 is default, we should also switch to V2 by default in tests
=> test(e2e): switch to tproxy v2 by default

test/e2e_env/universal/meshretry/http.go
We fixed the assert previously, however, now the test is flaky We now use MustPassRepeatedly to make things reliable
=> ci(e2e): fix meshretry test

test/e2e_env/kubernetes/connectivity/exclude_outbound_port.go
=> ci(e2e): fix a missing assert on DeleteMesh

pkg/api-server/authn/localhost.go, pkg/api-server/dataplane_overview_endpoints.go, pkg/api-server/global_insights_endpoints.go, pkg/api-server/inspect_endpoints.go, pkg/api-server/inspect_envoy_admin_endpoints.go, pkg/api-server/resource_endpoints.go, pkg/api-server/service_insight_endpoints.go, pkg/api-server/zone_overview_endpoints.go, pkg/api-server/zoneegressoverview_endpoints.go, pkg/api-server/zoneingress_overview_endpoints.go, pkg/api-server/zones_ws.go, pkg/core/rest/errors/error_handler.go, pkg/mads/v1/service/http.go, pkg/plugins/authn/api-server/tokens/authenticator.go, pkg/plugins/authn/api-server/tokens/ws/server/webservice.go, pkg/tokens/builtin/server/webservice.go
=> feat(obs): add traceId in error messages

pkg/xds/server/callbacks/dataplane_status_tracker.go
We were logging a lot of messages with little use. Moved them to debug
Here's an example on a dev setup I got running:
```
➜  docs.konghq.com git:(updateSubmodule) kubectl logs -n kong-mesh-system kong-mesh-control-plane-6b9646457b-tv79l | grep 'config has changed' | wc -l
20
➜  docs.konghq.com git:(updateSubmodule) kubectl logs -n kong-mesh-system kong-mesh-control-plane-6b9646457b-tv79l | grep 'config accepted' | wc -l
63
➜  docs.konghq.com git:(updateSubmodule) kubectl logs -n kong-mesh-system kong-mesh-control-plane-6b9646457b-tv79l | grep 'config requested' | wc -l
25
➜  docs.konghq.com git:(updateSubmodule) kubectl logs -n kong-mesh-system kong-mesh-control-plane-6b9646457b-tv79l | grep 'config sent' | wc -l
54
```
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues …
=> chore(logs): reduce status tracker log noise

pkg/dns/vips_allocator.go
It looks like resources are not ordered; whenever we do a `List` call, we can get resources in a different order. I've added sorting of the resources to make it stable in case we have a duplicate of the resource and we should use the first in order not randomly.
I tried to use `store.ListOrdered` but it seems not implemented for `memory` and `k8s`? Should we implement it on the store level? WDYT?
=> fix(kuma-cp): order resources for building VIPs

tools/releases/version.sh
Fix [CVE-2023-35943](https://github.com/envoyproxy/envoy/security/advisories/GHSA-mc6h-6j9x-v3gq), [CVE-2023-35944](https://github.com/envoyproxy/envoy/security/advisories/GHSA-pvgm-7jpg-pw5g), [CVE-2023-35941](https://github.com/envoyproxy/envoy/security/advisories/GHSA-7mhv-gr67-hq55), [CVE-2023-35942](https://github.com/envoyproxy/envoy/security/advisories/GHSA-69vr-g55c-v2v4).
=> chore(deps): upgrade envoy to 1.24.10

tools/releases/version.sh
Fix [CVE-2023-35943](https://github.com/envoyproxy/envoy/security/advisories/GHSA-mc6h-6j9x-v3gq), [CVE-2023-35944](https://github.com/envoyproxy/envoy/security/advisories/GHSA-pvgm-7jpg-pw5g), [CVE-2023-35941](https://github.com/envoyproxy/envoy/security/advisories/GHSA-7mhv-gr67-hq55), [CVE-2023-35942](https://github.com/envoyproxy/envoy/security/advisories/GHSA-69vr-g55c-v2v4).
=> chore(deps): upgrade envoy to 1.26.4

tools/releases/version.sh
Fix [CVE-2023-35943](https://github.com/envoyproxy/envoy/security/advisories/GHSA-mc6h-6j9x-v3gq), [CVE-2023-35944](https://github.com/envoyproxy/envoy/security/advisories/GHSA-pvgm-7jpg-pw5g), [CVE-2023-35941](https://github.com/envoyproxy/envoy/security/advisories/GHSA-7mhv-gr67-hq55), [CVE-2023-35942](https://github.com/envoyproxy/envoy/security/advisories/GHSA-69vr-g55c-v2v4).
=> chore(deps): upgrade envoy to 1.25.9

test/framework/k8s_cluster.go
Should've deleted this right after https://github.com/kumahq/kuma/pull/4335. We don't need node selectors since our images support both platforms.
=> ci(e2e): remove `kubernetes.io/arch: arm64`

app/kuma-dp/pkg/dataplane/cgroups/cgroups.go, app/kuma-dp/pkg/dataplane/envoy/memory_limit_linux.go, go.mod, go.sum
Containerd shows up time and time again with a CVE that does not actually impact our codebase but looks not great in scan results. I copied the code from the source so we no longer rely on it.
=> fix(sec): get rid of dependency on containerd

pkg/kds/v2/reconcile/reconciler.go
This ends up leading to error messages for `OnStop() failed`.
=> chore(kds): remove superfluous error log

app/kuma-dp/pkg/dataplane/cgroups/cgroups.go
=> fix(containerd): only build cgroups on linux

tools/releases/version.sh
=> chore(deps): upgrade envoy to 1.27.0

app/kuma-dp/pkg/dataplane/cgroups/cgroups.go
I don't know why this doesn't fail the lint check..
=> build(formatting): fix indentation from #7408

.github/workflows/auto-backport.yaml
otherwise this will happen - https://github.com/kumahq/kuma/actions/runs/5761094834/job/15618313595?pr=7456#step:4:53 
=> ci(actions): autolabel needs fetch depth 0 to be able to diff all branches
