kumahq/kuma

- pkg/xds/context/aggregate_mesh_context.go
- pkg/xds/context/context.go
- pkg/xds/sync/components.go
- pkg/xds/sync/dataplane_proxy_builder.go
- pkg/xds/sync/dataplane_watchdog.go
- pkg/xds/sync/egress_proxy_builder.go
- pkg/xds/sync/ingress_proxy_builder.go
- pkg/xds/sync/proxy_builder_test.go
With the recent VirtualOutbound cross zone work I noticed that we can heavily use MeshContext from specific meshes. If we do, then it's very easy to avoid unnecessary zone proxies XDS generation by checking the aggregated mesh hash following the same pattern as we do for regular DP proxies.
This improvement reduces:
* Number of queries to DB, instead of doing separate DB queries to all DPPs or all MeshGateways we can just aggregate all from all mesh contexts
* Number of XDS reconciliations for zone proxies if there are no changes in the system
Note: I'm not sure if `MeshContexts` is a good name. It can be easily confused with `MeshContext` when reading the code. Should this be `AggregatedMeshContexts`? `AllMeshContexts`?
`meshContextFetcher` is introduced so we don't have dependency on …
> perf(xds): use aggregated mesh context for zone proxies

- pkg/plugins/common/postgres/connection.go
- pkg/plugins/common/postgres/pgx_listener.go
- pkg/plugins/resources/postgres/pgx_store.go
I noticed that we repeat the code of pool creation across the code as well as Kong Mesh extensions. We should make it a common public function so all settings are respected. Bonus point is that we get tracing with other DB pools
> chore(postgres): share db creation pool code

- mk/test.mk
> build(mk): remove non existent make target dep

- .github/dependabot.yml
Groups go.opentelemetry.io/contrib/ and go.opentelemetry.io/otel dependencies updates
> ci(deps): group updates of several dependencies

- go.mod
- go.sum
it was released on Friday so we no longer need to rely on master commit
> chore(deps): update testcontainers-go to 0.22.0

- mk/build.mk
> build(coredns): fix build after upstream update

- mk/build.mk
> build: fix GOENV usage

- tools/releases/version.sh
> build(version.sh): fix version suffix with changes stashed

- pkg/insights/resyncer.go
It produces a lot of logs when there are multiple tenants. There is no point in doing so after the context is done
> chore(insights): do not continue on deadline

- mk/build.mk
> chore(deps): update CoreDNS to v1.11.0

- pkg/insights/resyncer.go
The pattern across the codebase is to store time metrics in milliseconds.
> feat(insights): change metrics to milliseconds

- pkg/core/rest/errors/error_handler.go
- pkg/core/rest/errors/errors.go
> feat(rest): add service unavailable error

- pkg/api-server/api_server_suite_test.go
- pkg/api-server/customization/customization_suite_test.go
- pkg/api-server/server.go
- pkg/core/runtime/builder.go
- pkg/core/runtime/runtime.go
- pkg/test/kds/setup/server.go
> feat(api-server): allow WebService customization in plugins

- pkg/core/bootstrap/bootstrap.go
- pkg/core/runtime/builder.go
- pkg/core/runtime/runtime.go
- pkg/events/eventbus.go
- pkg/events/interfaces.go
- pkg/insights/components.go
- pkg/insights/resyncer.go
- pkg/insights/resyncer_test.go
- pkg/test/runtime/runtime.go
Add an event to do on-demand computation of insights.
> feat(insights): add event to trigger computation

- test/e2e_env/kubernetes/kubernetes_suite_test.go
- test/e2e_env/multizone/multizone_suite_test.go
- test/e2e_env/universal/universal_suite_test.go
- test/framework/ginkgo.go
This has been missing for a while...
> test(e2e_env): don't cleanup if suite is failing

- .github/workflows/golangci-lint.yml
If a linter provides an option to fix the file itself, it will fix the file and golangci-lint returns 0 (no error). It worked before with `make check` because we were checking at the end of all linters whether there are no changed files in git.
> ci(lint): fail instead of fixing linter errors

- tools/ci/needs_backporting.sh
> ci(.github): more strict bash in autobackporting workflow

- mk/k3d.mk
- mk/metallb-k3d-kuma-1.yaml
- mk/metallb-k3d-kuma-2.yaml
- mk/metallb-k3d-kuma.yaml
> ci(k3d): construct metallb IPAddressPool from docker network address space

- test/framework/k8s_cluster.go
When we delete the namespace we can delete the pods without a grace period because we don't care about those pods anymore. This way we can immediately free up resources (CPU/MEM request for new pods). Otherwise if the resources stay at is (for 30-40s) it can eventually add up and the new test may be stuck on creating new pods and fail
> test(e2e): delete pods faster on namespace delete

- mk/check.mk
- mk/e2e.new.mk
> build(mk): include GOENV where needed

- mk/test.mk
> ci(mk): remove nonexistent make dependency

- mk/build.mk
- mk/distribution.mk
This allows us to have multiple files in the envoy tar, so if we want to bundle it with something it will work.
> ci(envoy): extract everything from the archive not just envoy binary

- pkg/xds/sync/dataplane_watchdog.go
I think that they do use Mesh Hash now, cf. lines 178 and 226
> fix(dataplane_watchdog): fix outdated comment

- pkg/xds/topology/outbound.go
- pkg/xds/topology/outbound_test.go
- test/e2e/zoneegress/externalservices/zoneegress_externalservices_hybrid.go
There was a logic that if you enabled `Mesh#routing.zoneEgress=true` and you didn't have egress deployed we still would route the traffic directly to zone ingress of other zones, but only for internal services (it would fail for external services). This can be misleading for users that expect their traffic to always go through zone egress when this setting is enabled.
> feat(kuma-cp): force routing through zone egress

- pkg/kds/store/sync.go
- pkg/kds/v2/store/sync.go
> chore(logging): switch updating a resource log to debug

- app/kuma-dp/pkg/dataplane/metrics/server.go
We should not pass accept-enconding further to apps when we aggregate metrics.
My prometheus server sends `accept-enconding: gzip` with request for metrics.
Golang client handles gzip automatically, but if you set this manually (our case) then it's up to the user to handle this. That's why we were merging metrics with compressed data.
https://go.dev/src/net/http/transport.go#L187
The solution is to not pass it through. We should not pass accept-encoding because there is no guarantee that our HTTP client can handle whatever prometheus wishes.
Why our E2E test missed this?
In our E2E test that checks app aggregate we scrape metrics manually https://github.com/kumahq/kuma/blob/master/test/e2e_env/universal/observability/applications_metrics.go
We should deploy prom and check it via prom, not …
> fix(metrics): hijacker should not pass accept-encoding

- test/e2e_env/kubernetes/gateway/cross-mesh.go
- test/e2e_env/universal/gateway/utils.go
- test/e2e_env/universal/healthcheck/panic.go
- test/e2e_env/universal/meshhealthcheck/panic.go
- test/e2e_env/universal/meshretry/grpc.go
- test/e2e_env/universal/meshretry/http.go
- test/e2e_env/universal/retry/retry.go
- test/framework/envs/kubernetes/env.go
- test/framework/envs/multizone/env.go
- test/framework/envs/universal/env.go
- test/framework/gateway.go
- test/framework/k8s_cluster.go
- test/framework/universal_cluster.go
This PR gets rid of unsafe delete by default in E2E tests.
Unsafe delete lets you delete a mesh without extra validations like all DPPs are removed.
Because we wanted to get rid of mesh as soon as possible, we did not want to wait for all dpps to terminate. This worked although we saw quite a bit errors logs especially in multizone that mesh is no longer available because we were deleting mesh "too soon". Doing it the right way (delete dpps first) is closer to production env. We can now do this because `TriggerNamespaceDelete` deletes the pods immediately.
The only drawback is that we can no longer test misconfigured provided mesh mtls with gateway because CP prevents us to delete a secret that is used for a mesh.
The main advantage of this chance is that we reduce the number of error …
> test(e2e): do not use unsafe delete

- .golangci.yml
- pkg/api-server/auth_test.go
- test/e2e_env/kubernetes/gateway/resources.go
- test/e2e_env/universal/observability/metrics.go
> feat(e2e): fix metrics tls test

- app/kumactl/cmd/install/install_transparent_proxy.go
Users often forget doing this. Hopefully a little message may help them
> chore(transparent-proxy): remind to run kuma-dp after installing tp

- pkg/plugins/leader/plugin.go
- pkg/plugins/leader/postgres/leader_elector.go
They chose kind of a weird interface for the logging, no option to add keys, just a list of values. So I added the arg number as a key, as opposed to just concatenating everything.
> fix(kuma-cp): universal mode don't log on every lock acquire attempt

- .circleci/config.yml
- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/config.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/kds/v2/reconcile/interfaces.go
- pkg/kds/v2/reconcile/reconciler.go
- pkg/kds/v2/reconcile/snapshot_generator.go
- pkg/kds/v2/server/components.go
- pkg/kds/v2/server/event_based_watchdog.go
- pkg/test/kds/setup/server.go
A test of experimental event-based watchdog for KDS.
I tested it manually with E2E test and it looks ok. We want to deploy this on our dev environment to see the perf gain. This might be a default, but for now we want to put it behind a flag.
The idea is instead of querying DB resources every X interval we react on postgres events and only generate snapshot for changed resources. Every Y interval we do a full resync if for some reason we lose the event.
> feat(kds): experimental event based watchdog

- pkg/kds/v2/reconcile/interfaces.go
- pkg/kds/v2/reconcile/reconciler.go
- pkg/kds/v2/server/components.go
- pkg/kds/v2/server/event_based_watchdog.go
- pkg/kds/v2/server/event_based_watchdog_test.go
- pkg/kds/v2/server/metrics.go
This PR adds more granular metrics to kds reconciller and unit tests to the experimental watchdog.
We want to measure what triggered watchdog flush (event or resync) and what is the result (was something changed or did we waste CPU time). This way we can discover how useful is resync and whether we can change the resync of 60s to something like 5mins or 1h etc and save CPU resources. 
> feat(kds): add metrics to event based watchdog

- pkg/insights/resyncer.go
In many cases service insights are computed with mesh insights in one event.
I noticed that we fetch dp overviews in both `createOrUpdateServiceInsight` and `createOrUpdateMeshInsight`. This is probably the most expensive DB query in insights. This change fetches dp overviews once and pass it to both functions.
> perf(insights): fetch dp overviews once

- pkg/core/xds/metadata.go
- pkg/core/xds/metadata_test.go
- pkg/xds/auth/callbacks.go
- pkg/xds/server/callbacks/dataplane_callbacks.go
- pkg/xds/server/callbacks/dataplane_status_tracker.go
The problem was `else if metadata.Resource != nil {`. In case of indirect lifecycle (Kubernetes), we don't have resource in the metadata therefore `AccessLogSocketPath` was always empty which results in
```
2023-09-05T23:47:22.049Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"xxx","Name":"xxx"}, "error": "invalid resource \"kuma:metrics:hijacker\": invalid Cluster.LoadAssignment: embedded message failed validation | caused by: invalid ClusterLoadAssignment.Endpoints[0]: embedded message failed validation | caused by: invalid LocalityLbEndpoints.LbEndpoints[0]: embedded message failed validation | caused by: invalid LbEndpoint.Endpoint: embedded message failed validation | caused by: invalid Endpoint.Address: embedded message failed validation | caused …
```
> fix(xds): backwards compatibility on access logs paths

- go.mod
- go.sum
> chore(deps): upgrade github.com/gruntwork-io/terratest to v0.43.13

- test/e2e_env/multizone/localityawarelb/meshloadbalancingstrategy.go
- test/e2e_env/multizone/multizone_suite_test.go
Just noticed the test I wrote is not executed. I don't know what I was thinking about 🤦‍♂️ 
> fix(e2e): enable LocalityAware test

- .github/workflows/blackbox-tests.yaml
- .github/workflows/pr-comments.yaml
`~/go/pkg/mod` seems to be cached by the `actions/cache@v4`
https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
> ci(upgrade): do not cache go mod manually

- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/config.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/eventbus/config.go
- pkg/config/loader_test.go
- pkg/core/bootstrap/bootstrap.go
- pkg/events/eventbus.go
- pkg/events/eventbus_suite_test.go
- pkg/events/eventbus_test.go
- pkg/events/interfaces.go
- pkg/insights/resyncer.go
- pkg/insights/test/test_event_reader.go
- pkg/kds/v2/server/components.go
- pkg/kds/v2/server/event_based_watchdog.go
- pkg/kds/v2/server/event_based_watchdog_test.go
- pkg/plugins/resources/postgres/listener_test.go
- pkg/test/kds/setup/server.go
- pkg/test/runtime/runtime.go
This PR improves an event bus.
Until now, every event listener created a channel and whenever we send an event, we send it into a channel. This means that whenever there is a full channel we are stuck on `.Send`. The cause of this can be a single listener that is not reading fast enough.
I changed the event bus to drop the event in this case and emit a log. Additionally:
* I created a config for the channel buffer. If we see that listeners are not consuming events on time, we can always increase this buffer without releasing a new version of Kuma.
* I introduced predicates. For example, if there is a listener that only cares about a specific event we can define a predicate. This way we can avoid putting unnecessary events into a channel.
[1]: …
> feat(events): configurable buffers and predicates

- pkg/insights/resyncer.go
Depends on https://github.com/kumahq/kuma/pull/7735/files
> perf(insights): refresh only changed

- pkg/kds/v2/reconcile/reconciler.go
Result of snapshot generator was not set properly.
> fix(metrics): result of reconciliation

- pkg/metrics/store/store.go
- pkg/metrics/store/store_test.go
Add metric for store conflicts
> feat(store): conflict metrics

- pkg/insights/resyncer.go
- pkg/insights/resyncer_test.go
Add metric of reason and result of insight computation. This can help us track if we actually need full resync or not.
> feat(insights): metrics of reason and result

- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/config/plugins/resources/postgres/config.go
- pkg/plugins/resources/postgres/pgx_store.go
Enable support for reader replica. If you use for example Aurora RDS, you can loadbalance requests between writer and reader. With this PR you can set host of a reader and ratio of requests that should go to a reader.
> feat(postgres): support reader replica

- pkg/kds/global/components.go
- pkg/kds/mux/client.go
- pkg/kds/mux/server.go
- pkg/kds/mux/session.go
- pkg/kds/zone/components.go
We are using bi-directional GRPC for the communication between zone and global. KDS might fail when trying to connect with the global and because of this, the zone might not be in sync with Global resources. Because of that, we are using a resilient component which is responsible for starting the code again in case of errors. It works well when an error is returned. But the zone code wasn't returning an error and that caused the component to not start again.
I am not sure how to exactly test it yet.
> fix(kuma-cp): set error when KDS clients fails in goroutine

- pkg/insights/resyncer_test.go
It was visible here https://app.circleci.com/pipelines/github/kumahq/kuma/24830/workflows/1451fc5f-9455-4a8a-9fd4-b62213674c11/jobs/496399/tests
getters handle nulls
> test(unit): do not panic on missing metric

- pkg/plugins/resources/postgres/pgx_store.go
> fix(postgres): use customizer for ro pool

- pkg/insights/resyncer.go
- pkg/kds/v2/server/event_based_watchdog.go
Feedback from the team that trigger was not clear. `&` does not map great for Datadog
> chore(metrics): rename reasons

- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/config.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/insights/components.go
- pkg/insights/resyncer.go
- pkg/insights/resyncer_test.go
- pkg/metrics/store/counter_test.go
A couple of insights improvements
* Introduce multiple workers that consume events (still 1 by default)
* Parallelize `addMeshesToBatch` for multiple tenants
* Flush only required for `TriggerInsightsComputationEvent`
> feat(insights): multiple workers

- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/config.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/kds/v2/server/components.go
When zones are reconnecting to the global control plane they might reconnect at the same time. That could cause that ticker responsible for full resync might be processed at the same time. We have introduced an option to delay a full resync by random between 0-FullResyncInterval. First tick will be delayed but after it we are setting it to FullResyncInterval.
> feat(kuma-cp): allow to delay full resync when ticker

- go.mod
- go.sum
- test/e2e/gateway/gatewayapi/conformance_test.go
- test/framework/k8s.go
> chore(deps): bump sigs.k8s.io/gateway-api from v0.8.0 to v0.8.1

- pkg/plugins/runtime/k8s/controllers/gatewayapi/conversion.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
We weren't actually checking whether a ref is permitted when converting for GAMMA, which is correct, but we reused the condition list from the gateway case.
Closes #7764 
> fix(gatewayapi): don't set RefNotPermitted for GAMMA routes

- pkg/kds/v2/reconcile/reconciler.go
- pkg/util/xds/stats_callbacks.go
- pkg/util/xds/stats_callbacks_test.go
> fix(kds): delta delivery metric

- pkg/kds/global/components.go
- pkg/kds/global/components_test.go
- pkg/kds/v2/client/zone_sync_test.go
- pkg/kds/v2/store/sync.go
- pkg/kds/v2/store/sync_test.go
- pkg/kds/zone/components.go
- pkg/kds/zone/components_test.go
We have metrics of KDS traffic, KDS processing on the producer side (snapshot generation latency), but we don't have metric of processing events on the consumer side (resource syncer). This PR introduces this metric. I picked Historgram instead of Summary this time. With other histograms it seems to be updated more frequently, we may want to update our other summary metrics.
> feat(kds): resource sync metric

- pkg/core/ca/manager.go
- pkg/core/managers/apis/mesh/mesh_helpers.go
- pkg/core/managers/apis/mesh/mesh_manager.go
- pkg/core/tokens/meshed_signing_key_manager.go
- pkg/defaults/components.go
- pkg/defaults/mesh.go
- pkg/defaults/mesh/mesh.go
- pkg/defaults/mesh/mesh_test.go
- pkg/defaults/mesh/signing_key.go
- pkg/plugins/ca/builtin/manager.go
- pkg/plugins/ca/builtin/manager_test.go
- pkg/plugins/ca/provided/manager.go
- pkg/plugins/resources/postgres/store_template_test.go
- pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go
- pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller_test.go
- pkg/plugins/secrets/k8s/plugin.go
- pkg/plugins/secrets/k8s/store.go
- pkg/plugins/secrets/k8s/store_test.go
- pkg/test/store/owner_test_template.go
- pkg/xds/secrets/secrets_test.go
- test/e2e_env/kubernetes/gateway/gateway.go
- test/e2e_env/kubernetes/gateway/mtls.go
based on https://github.com/kumahq/kuma/pull/7736 
closes https://github.com/kumahq/kuma/issues/3276
you can check parent project PR to see how it works there
> feat(store): add owner reference to the secrets

- pkg/insights/resyncer.go
When calculating insight we are fetching `ExternalServices` twice. We can fetch them only once and pass to other method.
> perf(insight): fetch external services once

- pkg/api-server/dataplane_overview_endpoints.go
- pkg/api-server/dataplane_overview_endpoints_test.go
Fix https://github.com/kumahq/kuma/issues/7801
When we introduced the endpoint we were filtering items in this file therefore we had to set a total to all items we fetched. Some time ago we changed this to pass filter function to the store. This means that `overviews.Item` was after pagination and filtering was done.
> fix(api): dataplane overview pagination

- pkg/insights/resyncer.go
> fix(kuma-cp): take proper context for resync

- pkg/kds/v2/store/sync.go
Default histograms expect seconds. Here are buckets
```
kds_resources_sync_bucket{zone="Global",le="0.005"} 0
kds_resources_sync_bucket{zone="Global",le="0.01"} 0
kds_resources_sync_bucket{zone="Global",le="0.025"} 0
kds_resources_sync_bucket{zone="Global",le="0.05"} 0
kds_resources_sync_bucket{zone="Global",le="0.1"} 0
kds_resources_sync_bucket{zone="Global",le="0.25"} 0
kds_resources_sync_bucket{zone="Global",le="0.5"} 0
kds_resources_sync_bucket{zone="Global",le="1"} 0
kds_resources_sync_bucket{zone="Global",le="2.5"} 6
kds_resources_sync_bucket{zone="Global",le="5"} 6
kds_resources_sync_bucket{zone="Global",le="10"} 6
kds_resources_sync_bucket{zone="Global",le="+Inf"} 6
kds_resources_sync_sum{zone="Global"} 6.01
kds_resources_sync_count{zone="Global"} 6
```
[1]: …
> fix(metrics): resources synced

- pkg/core/rest/errors/error_handler.go
* Update HandleError to process pointer to rest_errors.Error as an argument. This allows us to use errors.As directly, which simplifies the code and allows project depending on Kuma to handle not hardcoded errors.
* Fix a bug in HandleError where it was incorrectly assigning err to itself in the case of an Unauthenticated error.
- Closes https://github.com/kumahq/kuma/issues/7817
- It won't
> fix(errors): improve HandleError to handle rest_errors.Error and fix Unauthenticated error handling

- api/mesh/v1alpha1/externalservice_helpers.go
- pkg/api-server/api_server_suite_test.go
- pkg/api-server/dataplane_overview_endpoints.go
- pkg/api-server/filters/filtering.go
- pkg/api-server/resource_endpoints.go
- pkg/api-server/resource_endpoints_test.go
- pkg/api-server/server.go
This also opens the path to adding more filters to the api depending on the resource descriptor
Fix #5908
> feat(api-server): add filtering on list external-services and dataplanes

- deployments/charts/kuma/templates/NOTES.txt
This way we can easily reuse this in entreprise distributions
> chore(helm): don't use Kuma in NOTES.txt

- .github/workflows/codeql.yaml
ATM [failures around the new version syntax in `go.mod`](https://github.com/kumahq/kuma/actions/runs/6302100387)
> ci(codeql): add explicit setup-go step

- .github/workflows/helm-release.yaml
This job doesn't _need_ it, only the first which already has it, but we should be using the right version. 
> ci(.github): add setup-go to helm release workflow

- pkg/kds/mux/server.go
- pkg/kds/mux/zone_sync.go
- pkg/kds/service/server.go
- pkg/kds/v2/server/error_recorder_stream.go
- pkg/kds/v2/server/kds.go
- pkg/kds/v2/server/streamwrapper.go
* Do not propagate errors to zone
* When `kdsSyncClient` errors out. There was a situation when KDS component could not be restarted, because `DeltaStreamHandler` swallows errors.
> feat(kds): better error handling

- pkg/insights/globalinsight/global_insight_service.go
- pkg/insights/globalinsight/global_insight_service_test.go
- pkg/insights/globalinsight/testdata/full_global_insight.golden.json
> feat(kuma-cp): fix global insight endpoint zone cp count

- .golangci.yml
- app/kuma-cp/cmd/run.go
- pkg/config/loader.go
- pkg/core/alias.go
- pkg/core/secrets/manager/validator.go
- pkg/insights/resyncer.go
- pkg/mads/v1/generator/assignments.go
- pkg/plugins/policies/core/matchers/dataplane.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_class_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
- pkg/xds/context/context.go
* Add linter
* Fix linter problems (mainly `%T`)
* Name all unnamed logs (it does not map well with a Datadog)
* Remove `stopped resyncEvents loop` logs because with 100 loops it's quite a spam and it can only log this when the whole component is down which we already log.
> chore(kuma-cp): improve logging

- .github/workflows/pr-comments.yaml
Use `clean/generated` instead of `clean` target (former had to wide scope) and run `generate` target afterwards.
- Closes: https://github.com/kumahq/kuma/issues/7873
- It won't
> ci(ghaction): fix pr-comments /format gh action

- app/kumactl/cmd/completion/testdata/fish.golden
- docs/madr/decisions/000-template.md
- mk/kind.mk
> fix: multiple typos

- pkg/core/resources/store/store.go
- pkg/plugins/resources/k8s/store.go
- test/e2e_env/kubernetes/inspect/inspect.go
Enterprise distributions can use this type of error to return not only format related errors.
- It won't
- Manually tested - it's a trivial change, so I don't think there is need to introduce new unit tests
> chore(kuma-cp): remove default prefix from PreconditionError.Reason

- pkg/kds/service/server.go
Why can't go just properly support constants?
> chore(kds): don't overwrite global log variable

- pkg/kds/global/components.go
- pkg/kds/service/server.go
Execute the same interceptors as with KDS to be able to plug in extra functionallity
> feat(kds): execute filters on envoy admin streams

- pkg/kds/v2/server/components.go
- pkg/kds/v2/server/event_based_watchdog.go
- pkg/kds/v2/server/metrics.go
Note: as a consequence, the canceled reconcile run is no longer "represented" in the metrics. It's not fully clear to me whether this would lead to inconsistencies.
> fix(kds): don't inc KdsGenerationErrors when context canceled

- go.mod
- go.sum
> chore(deps): bump k8s.io/apiextensions-apiserver from v0.28.1 to v0.28.2

- pkg/kds/service/server.go
Cancelled stream should not be an error
> chore(kds): handle cancelled and stopped envoy admin stream

- pkg/kds/global/components.go
- pkg/kds/global/components_test.go
- pkg/kds/mux/zone_sync.go
- pkg/kds/service/server.go
- pkg/kds/v2/client/zone_sync_test.go
- pkg/kds/v2/reconcile/interfaces.go
- pkg/kds/v2/reconcile/reconciler.go
- pkg/kds/v2/server/components.go
- pkg/kds/v2/server/event_based_watchdog.go
- pkg/kds/v2/server/event_based_watchdog_test.go
- pkg/kds/v2/store/sync.go
- pkg/kds/v2/store/sync_test.go
- pkg/kds/zone/components.go
- pkg/kds/zone/components_test.go
- pkg/test/kds/setup/server.go
Adding missing tenant ID logging.
I really dislike piping through this Extensions object :( I need to think if this can be refactored to something more sane.
xref #7907
> chore(kds): tenant logging

- pkg/core/xds/metadata.go
- pkg/xds/bootstrap/template_v3.go
- pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml
- pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml
- pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config-token-path.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.ipv6.golden.yaml
- pkg/xds/bootstrap/testdata/generator.metrics-config.kubernetes.golden.yaml
- pkg/xds/generator/admin_proxy_generator.go
- pkg/xds/generator/admin_proxy_generator_test.go
- pkg/xds/generator/testdata/admin/02.dataplane.input.yaml
- pkg/xds/generator/testdata/admin/02.envoy-config.golden.yaml
- pkg/xds/generator/testdata/admin/03.dataplane.input.yaml
- pkg/xds/generator/testdata/admin/03.envoy-config.golden.yaml
- pkg/xds/generator/testdata/admin/04.dataplane.input.yaml
- pkg/xds/generator/testdata/admin/04.envoy-config.golden.yaml
- pkg/xds/generator/testdata/admin/05.dataplane.input.yaml
- pkg/xds/generator/testdata/admin/05.envoy-config.golden.yaml
Today there is a possibility to change the Envoy Admin address to `::1` but `admin_proxy_generator.go` generates an admin cluster always with a `127.0.0.1` address.
This PR puts a specified admin address to proxy metadata and uses it when generating an admin cluster.
> fix(kuma-cp): specifying IPv6 Envoy Admin address breaks readiness/liveness probes

- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/core/resources/store/config.go
- pkg/config/loader_test.go
- pkg/core/resources/manager/manager.go
- pkg/kds/global/components.go
- pkg/kds/server/components.go
- pkg/kds/server/status_sink.go
- pkg/kds/service/server.go
- pkg/kds/v2/server/components.go
* Use upsert settings once again (it was used at some point and then dropped?). This way we can customize those values without releasing new version
* Add jitter for storing envoy streams
* Add jitter to upserts
* Change default values to 200ms, max 10 retries and 30% jitter.
Fix #https://github.com/kumahq/kuma/issues/7921
> feat(insights): jitter zone insights upsert

- pkg/xds/generator/admin_proxy_generator.go
- pkg/xds/generator/admin_proxy_generator_test.go
Introduced a flaky test in https://github.com/kumahq/kuma/pull/7909, this is a fix
> test(unit): fix flaky "should return error when admin address is not allowed" test

- pkg/xds/generator/admin_proxy_generator.go
- pkg/xds/generator/admin_proxy_generator_test.go
No reason to expose golang's utterly bizarre formatting choices to users.
> chore(kuma-cp): improve error message for invalid admin addresses

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.cni-legacy-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.values.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/cp-deployment.yaml
- deployments/charts/kuma/values.yaml
- docs/generated/raw/helm-values.yaml
Add `minReadySeconds` to the HELM chart for control plane.
This can help us rollout the new version longer over time instead of very quickly terminating all the control planes.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#deploymentspec-v1-apps
> feat(helm): minReadySeconds for control plane

- pkg/core/resources/manager/manager.go
- pkg/core/resources/store/options.go
- pkg/plugins/resources/postgres/pgx_store.go
So whenever we use read replica for postgres and execute Upsert, we reduce chance of read replica lag.
Fix https://github.com/kumahq/kuma/issues/7922
> feat(store): consistent gets for read replica

- .github/workflows/release.yaml
> ci(.github): checkout files before setup-go in release workflow

- pkg/core/resources/apis/mesh/traffic_route_validator.go
- pkg/core/resources/apis/mesh/traffic_route_validator_test.go
- pkg/xds/envoy/clusters/v3/lb_configurer.go
- pkg/xds/envoy/clusters/v3/lb_configurer_test.go
Api says that when `choiceCount` is not defined we are using a default value of 2 which is correct from the envoy perspective but not from kuma API. 
`GetLeastRequest()` returns an object that has `choiceCount` equal 0, so when a user creates a policy without `choiceCount` it doesn't fail on the API but will fail on xds configuration generation because envoy requires a minimum value of 2.  
I've changed a bit how validation works now:
* validate object if the value is equal 1, that won't cause xds configuration to fail and break the sidecar
* when the value is equal to 0 we assume that it's an empty object and we set it to default 2
> fix(kuma-cp): use default value when choiceCount is 0

- pkg/plugins/runtime/k8s/plugin_gateway.go
- test/framework/envs/multizone/env.go
Changes:
* always pass `waitForDataplaneReady: false` when generating builtin gateway pod
* bind envoy admin to `::1` and set `waitForDataplaneReady: true` in e2e-multizone
Note: even though `postStart` hook should be completely harmless for builtin gateway for some reason it doesn't work. Builtin gateway pod spends 3m in `ContainerCreating` phase, restarts, and then works as expected. @lukidzi do you know why this can happen? 
> fix(kuma-cp): don't add `postStart` hook to builtin gateway even if `waitForDataplaneReady: true`

- pkg/config/loader_test.go
- pkg/config/tracing/config.go
- pkg/plugins/runtime/opentelemetry/plugin.go
Closes https://github.com/kumahq/kuma/issues/7161
The upstream library checks for `OTLP_EXPORTER_OTEL_*` variables.
> feat(kuma-cp): make OpenTelemetry control plane tracing fully configurable

- pkg/gc/components.go
> fix(insights): have subscription gc also work for zoneEgress insights

- pkg/plugins/runtime/opentelemetry/plugin.go
The check only worked if both were set, which defeats the purpose.
> chore(kuma-cp): fix check if OpenTelemetry is enabled

- pkg/insights/components.go
- pkg/insights/resyncer.go
- pkg/insights/resyncer_test.go
- pkg/kds/server/components.go
- pkg/kds/server/status_sink.go
- pkg/kds/v2/server/components.go
- pkg/metrics/store/counter_test.go
Fix https://github.com/kumahq/kuma/issues/7943
> chore(logs): add missing tenant id

- pkg/kds/server/status_sink.go
- pkg/kds/service/server.go
* Storing empty admin operations stream is really not that useful, we won't be able to execute envoy admin operation anyways.
* Remove conflict retry from kds status sink at the cost of potentially longer time to see the zone online
> chore(kds): reduce zone insights conflicts

- pkg/core/resources/model/resource.go
> chore(kuma-cp): add "Or" TypeFilter for core_model

- pkg/defaults/mesh/mesh.go
When validating the default resources for the mesh when using an eventually consistent store there might be an issue that resources won't be available on the read replica at the time of validation. This ensures that resources are checked from a write replica.
> fix(kuma-cp): use GetConsistent store when validating default mesh resources

- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/config/multizone/kds.go
- pkg/config/multizone/multicluster.go
- pkg/kds/mux/server.go
> feat(kuma-cp): allow to disable KDS SOTW grpc api

- .circleci/config.yml
[failing job](https://app.circleci.com/pipelines/github/kumahq/kuma/25317/workflows/417cfb92-3a71-4885-b502-1209f89ec7a2/jobs/513061)
> ci(.circleci): fix darwin job after deprecation

- pkg/kds/v2/server/resource_retry_forcer.go
> chore(logging): bump nack level to info to surface potential problems

- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/config/multizone/kds.go
- pkg/kds/global/components.go
- pkg/kds/v2/client/kds_client.go
- pkg/kds/v2/client/zone_sync_test.go
- pkg/kds/zone/components.go
- pkg/kds/zone/components_test.go
- pkg/test/kds/setup/client.go
Response backoff is a way to rate limit clients from sending data too often.
Let's say we have a Zone CP that has many constant changes to Dataplane objects. With the default 1s `KUMA_MULTIZONE_ZONE_KDS_REFRESH_INTERVAL` we will aggregate changes every 1s and send this to global. However, Global CP may want to slow down Zone CP from changing resources too often.
The communication looks like this
Global CP sends DeltaDiscoveryRequest
Zone CP sends DeltaDiscoveryResponse with DP list
Global CP saves DPPs and sends ACK (DeltaDiscoveryRequest)
Zone CP sends DeltaDiscoveryResponse with DP list
Global CP saves DPPs and sends ACK...
If Global CP waits to send ACK after it saves DPPs, Zone CP won't send a new list. Instead, it will aggregate changes over time.
This is a setting for all resources, …
> feat(kds): response backoff

- .circleci/config.yml
> ci(circleci): install qemu on `build` to be able to build arm64 docker

- pkg/core/bootstrap/bootstrap.go
- pkg/core/plugins/interfaces.go
- pkg/core/resources/manager/manager.go
- pkg/core/resources/store/transactions.go
- pkg/core/runtime/builder.go
- pkg/core/runtime/runtime.go
- pkg/kds/global/components.go
- pkg/kds/global/components_test.go
- pkg/kds/server/components.go
- pkg/kds/server/status_sink.go
- pkg/kds/v2/client/zone_sync_test.go
- pkg/kds/v2/server/components.go
- pkg/kds/v2/store/sync.go
- pkg/kds/v2/store/sync_test.go
- pkg/kds/zone/components.go
- pkg/kds/zone/components_test.go
- pkg/plugins/resources/k8s/plugin.go
- pkg/plugins/resources/memory/plugin.go
- pkg/plugins/resources/postgres/pgx_store.go
- pkg/plugins/resources/postgres/plugin.go
- pkg/test/runtime/runtime.go
Introducing postgres transactions.
This PR does NOT introduce need for transactions in Kuma, this is just a perf optimization for stores that support transactions.
I introduced a new interface called Transactions, so the transaction can be used by either ResourceStore and ResourceManager. If I would add a new method in ResourceStore we would also add this to ResourceManager.
I decided to propagate transaction implicitly in context instead of explicitly in store opts like `CreateInTx(tx)`. This is more flexible with less changes to the code. We could also for example open a transaction when we create new Mesh without adding `CreateInTx` to every call.
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-u …
> perf(store): postgres transactions

- tools/releases/version.sh
> chore(deps): bump envoy from 1.24.10 to 1.24.11

- tools/releases/version.sh
> chore(deps): bump envoy from 1.25.9 to 1.25.10

- go.mod
- go.sum
> chore(deps): bump golang.org/x/net to v0.17.0, google.golang.org/grpc to v1.58.3

- tools/releases/version.sh
> chore(deps): bump envoy from 1.27.0 to 1.27.1

- pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/testdata/basic_listener_1.golden.yaml
- pkg/plugins/policies/meshfaultinjection/plugin/xds/configurer.go
Take into account tags negation when generating header matchers for MeshFaultInjection policy.
- Closes: https://github.com/kumahq/kuma/issues/7728
- It won't
- Unit tests updated
- It doesn't
> fix(MeshFaultInjection): include tags negation in header matching

- pkg/plugins/policies/core/matchers/dataplane.go
- pkg/plugins/policies/meshproxypatch/api/v1alpha1/validator.go
- pkg/plugins/policies/meshproxypatch/api/v1alpha1/validator_test.go
Allow MeshProxyPatch to target MeshGateway resources
- Closes https://github.com/kumahq/kuma/issues/7623
- It won't
- Unit tests updated
> feat(MeshProxyPatch): allow policy to target MeshGateway resources

- pkg/kds/global/components.go
- pkg/kds/mux/zone_sync.go
- pkg/kds/service/server.go
> fix(shutdown): try returning unavailable on app context finish

- pkg/kds/mux/zone_watch.go
- pkg/kds/mux/zone_watch_test.go
Changed some logic in the original PR https://github.com/kumahq/kuma/pull/7821/commits/0356948b8a2a4887fd4160338d9c133467378134 without updating the saved time.
> fix(kuma-cp): store correct last seen time in ZoneWatch

- pkg/kds/context/context.go
- pkg/kds/global/components.go
- pkg/kds/mux/server.go
Do we also need interceptors like https://github.com/kumahq/kuma/blob/c795edf1e6c503bfb9e414069932016eaa729f29/pkg/kds/global/components.go#L190-L194
> feat(kuma-cp): add unary interceptors to KDS server

- pkg/xds/cache/mesh/cache.go
`hashCache` has an expiration time of 1m, but the cleanup interval was 900ms
> fix(kuma-cp): cleanup interval should be calculated based on "expirationTime" for hashCache

- UPGRADE.md
- pkg/api-server/dataplane_overview_endpoints_test.go
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?gateway=builtin.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?gateway=delegated.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?gateway=true.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?name=gateway.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?name=tew.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?tag=service:backend&tag=version:v1.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?tag=service:backend&tag=version:v2.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?tag=service:backend.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?tag=service:ck.json
- pkg/api-server/testdata/_meshes_mesh1_dataplanes+insights?tag=tagcolumn:tag:v.json
- pkg/core/resources/apis/mesh/zz_generated.resources.go
- pkg/core/resources/apis/system/zz_generated.resources.go
- tools/resource-gen/main.go
This was causing panic if we ask for the overview before any insight was created.
We've also updated UPGRADE.md to notify of the deprecation
> fix(api-server): avoid panic when there no insight for entity

- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/egress-deployment.yaml
- deployments/charts/kuma/templates/ingress-deployment.yaml
- deployments/charts/kuma/values.yaml
- docs/generated/raw/helm-values.yaml
> chore(helm): allow to set log level for {in|e}gress

- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
> chore(tests): update golden file for kumactl install cp

- DEVELOPER.md
> docs(DEVELOPER.md): remove clang exception

- tools/ci/update-vulnerable-dependencies.sh
since the publishing of [our CVE advisory](https://github.com/kumahq/kuma/security/advisories/GHSA-9wmc-rg4h-28wv) in Kuma and it being picked up by osv scanner https://osv.dev/vulnerability/GHSA-9wmc-rg4h-28wv our security update action is failing in parent project (it's trying to update to 2.0.8 per our policy of upgrading deps to the lowest one that is patched).
This PR simply filters out kuma from that job.
> ci(security): filter out kuma from security update

- app/kuma-dp/pkg/dataplane/dnsserver/Corefile
- app/kuma-dp/pkg/dataplane/dnsserver/config_file.go
- app/kuma-dp/pkg/dataplane/dnsserver/dnsserver.go
- app/kuma-dp/pkg/dataplane/dnsserver/dnsserver_test.go
We can link to this file directly instead of having it copy pasted in the docs.
> refactor(kuma-dp): put Corefile into embedded FS

- pkg/xds/context/aggregate_mesh_context.go
- pkg/xds/context/mesh_context_builder.go
- pkg/xds/sync/dataplane_watchdog.go
- pkg/xds/sync/egress_proxy_builder.go
- Add ZoneEgresses to AggregatetMeshContexts when there is no mesh.
- Sync ZoneIngresses and ZoneEgresses only when the hash changes.
- Return an error with the correct resource type (ZoneEgress) when a ZoneEgress cannot be found.
- It won't
- Manually tested on k3d
- It does
> fix(kuma-cp): fix Zone{In|E}gress sync when no mesh

- pkg/core/permissions/matcher.go
- pkg/core/permissions/matcher_test.go
- pkg/plugins/runtime/gateway/generator.go
- pkg/plugins/runtime/gateway/plugin.go
- pkg/xds/context/mesh_context_builder.go
- pkg/xds/sync/dataplane_proxy_builder.go
- pkg/xds/sync/dataplane_watchdog.go
Improve XDS error handling. One user ended up with such log
```
2023-10-09T17:23:42.781Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"xxx","Name":"xxx"}, "error": "EOF"}
```
which is not enough context to figure out what is going on.
> chore(xds): improve error logging

- pkg/api-server/service_insight_endpoints.go
- pkg/api-server/service_insight_endpoints_test.go
> feat(kuma-cp): added query parameter to filter services by name

- .golangci.yml
- mk/build.mk
No longer needed for gateway-api, added in #7374 
> build(go): remove no longer needed `experimental` build tag

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
- deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
Some public cloud providers have a warning which confuses users In any case it's good practice: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#avoiding-operating-on-the-kube-system-namespace
> fix(helm): do not run webhooks on kube-system

- tools/releases/version.sh
> chore(deps): upgrade envoy to 1.24.12

- tools/releases/version.sh
> chore(deps): upgrade envoy to 1.25.11

- tools/releases/version.sh
> chore(deps): upgrade envoy to 1.26.6

- tools/releases/version.sh
> chore(deps): upgrade envoy to 1.27.2

- tools/releases/version.sh
> chore(deps): upgrade envoy to 1.28.0

- UPGRADE.md
- pkg/api-server/dataplane_overview_endpoints_test.go
- pkg/api-server/resource_endpoints.go
- pkg/api-server/testdata/meshes_mesh1_dataplanes_overview_name_tew.json
Update https://github.com/kumahq/kuma/pull/7999 to be conformant with other API choices made in #8148
> Changelog: feat(api-server): add /_overview for all types that have overviews
> fix(api-server): move -overview to _overview

- pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/testdata/apply.golden.yaml
- pkg/test/resources/builders/mesh_builder.go
- pkg/xds/generator/inbound_proxy_generator.go
- pkg/xds/generator/testdata/inbound-proxy/5-envoy-config.golden.yaml
- pkg/xds/generator/testdata/inbound-proxy/6-envoy-config.golden.yaml
- test/e2e_env/universal/meshtrafficpermission/meshtrafficpermission.go
Fix https://github.com/kumahq/kuma/issues/8152
I noticed that we put RBAC filter even for filterChains without mTLS on them.
This PR fixes this so we put RBAC filters only on listeners with Kuma's mTLS (by checking transport socket match).
This was also the case for TrafficPermission, not only for MeshTrafficPermission.
Why was it not caught by E2E test?
It was not a problem when you have "allow any to any" policy, because in this case even though we put RBAC filter it has principal "any" which matches any traffic in the end.
> fix(MeshTrafficPermission): support permissive mtls

- mk/generate.mk
This target should only be run on the Kuma project. If any other project depends on this target, it can overwrite the `EXTRA_GENERATE_DEPS_TARGETS` variable to prevent the target from running and generating the `imports.go` file.
xref. https://github.com/kumahq/kuma/pull/8193
-  https://github.com/kumahq/kuma/pull/8193
-  it won't
- manually tested
-  there is no need
-  there is no need
> ci(mk): make generate/envoy-imports target to only run on Kuma

- .github/workflows/update-insecure-dependencies.yaml
so its ready when starting work early
> chore(actions): run security update job at 3 am

- app/kuma-dp/cmd/context.go
- app/kuma-dp/cmd/run.go
> feat(kuma-dp): allow token generator to be a component

- pkg/metrics/components/cp_info.go
- pkg/version/version.go
This is useful for entreprise distributions
Fix #8143
> feat(kuma-cp): add basedOnKuma in cp_info metric

- pkg/plugins/runtime/gateway/filter_chain_generator.go
- pkg/plugins/runtime/gateway/gateway_route_generator_test.go
- pkg/plugins/runtime/gateway/testdata/http/cross-mesh-gateway.yaml
- pkg/plugins/runtime/gateway/testdata/https/cross-mesh-gateway.yaml
In the cross-mesh case, the SNI string will be a kuma SNI string for the gateway service (e.g. edge-gateway{mesh=default,port=tcp-8080}). Thus it is not possible to distinguish hosts at the listener level and no filter chain sni matchers are added. This can lead to a duplicate listener filter chain being added if there are multiple hostnames to route.
Thus we truncate the gatewayHosts array to size 1 before creating the listener blocks.
Fixes #8076 
Supersedes #8105 
* The approach in my PR solves the problem in a way that leaves the door open for host-based cross-mesh routing (i.e. specifying mesh hostnames in MeshGatewayRoute). I have that working and will submit a follow on PR for it
* The tests in this PR are modified from the ones in #8105, the authorship of the original tests …
> fix(MeshGateway): ensure that duplicate listeners are not added when crossMesh is enabled on a listener and Routes specify hostnames

- api/generic/insights.go
- api/mesh/v1alpha1/dataplane_insight_helpers.go
- api/mesh/v1alpha1/dataplane_insight_helpers_test.go
- api/mesh/v1alpha1/zone_ingress_insight_helpers.go
- api/mesh/v1alpha1/zone_ingress_insight_helpers_test.go
- api/mesh/v1alpha1/zoneegressinsight_helpers.go
- api/mesh/v1alpha1/zoneegressinsight_helpers_test.go
- api/system/v1alpha1/zone_insight_helpers.go
- api/system/v1alpha1/zone_insight_helpers_test.go
- pkg/gc/components.go
- pkg/gc/finalizer.go
- pkg/gc/finalizer_test.go
- pkg/xds/server/callbacks/dataplane_lifecycle.go
- pkg/xds/server/callbacks/dataplane_status_sink_test.go
> fix(kuma-cp): improve ZoneInsight subscription management

- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid.go
Test seems flaky and this should reduce it. Traffic might not be distributed equally and only with higher number of requests it can reduce the difference
> feat(kuma-cp): increase possible values in e2e test

- app/kumactl/cmd/install/install_transparent_proxy_test.go
- app/kumactl/cmd/install/testdata/install-transparent-proxy.dns.golden.txt
- app/kumactl/cmd/install/testdata/install-transparent-proxy.dns.no-conntrack.golden.txt
- it won't
- it contains only changes in tests
- no need
- no need
> test(kumactl) adjust matcher for install tproxy test

- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid.go
- test/framework/deployments/testserver/kubernetes.go
To be investigated in https://github.com/kumahq/kuma/issues/8245
> test(e2e): revert implementation of delete deployment for test-server

- app/kuma-dp/cmd/run.go
- app/kuma-dp/pkg/dataplane/envoy/envoy.go
- docs/generated/cmd/kuma-dp/kuma-dp_run.md
- pkg/config/app/kuma-dp/config.go
- pkg/plugins/runtime/k8s/containers/factory.go
- pkg/plugins/runtime/k8s/metadata/annotations.go
> feat(kuma-dp): support setting Envoy's --component-log-level

- .circleci/config.yml
> ci(.circleci): don't depend on e2e or legacy for distributions job

- pkg/version/version.go
otherwise on previews we will get (7 chars):
```
based_on_kuma:0.0.0-p
```
> chore(metrics): do not shorten commit in basedOnKuma cp_metric

- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid.go
> test(e2e): increase ranges of possible value

- app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go
- https://github.com/kumahq/kuma/issues/8256
- no need to update
- no need
> fix(kuma-dp): advise user to check pod events when data plane rejected by webhooks

- go.mod
- go.sum
More fixes for conformance tests
> chore(deps): update gateway-api

- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/cp-ingress.yaml
- deployments/charts/kuma/values.yaml
- docs/generated/raw/helm-values.yaml
> feat(helm): add configurable service port for cp ingress

- pkg/kds/service/server.go
This can happen when someone kills the stream at the right time. I don't think we need to log on error there, can just return the proper error code.
> chore(logs): do not log context canceled on rpc streams

- app/kuma-dp/cmd/run.go
- app/kuma-dp/pkg/dataplane/command/base_command.go
- app/kuma-dp/pkg/dataplane/command/build_command_darwin.go
- app/kuma-dp/pkg/dataplane/command/build_command_windows.go
- app/kuma-dp/pkg/dataplane/dnsserver/dnsserver.go
- app/kuma-dp/pkg/dataplane/envoy/envoy.go
- pkg/config/app/kuma-dp/config.go
- pkg/core/runtime/component/component.go
- pkg/kds/mux/client.go
- For kuma-dp we properly shutdown when context is closed
- In KDS the client cancelled being closed make all the components stop
> fix(core): better lifecycle when context is getting cancelled

- app/kuma-dp/pkg/dataplane/command/build_command_windows.go
> fix(kuma-dp): fix build

- pkg/plugins/runtime/k8s/controllers/pod_controller_test.go
- pkg/plugins/runtime/k8s/controllers/pod_converter.go
- pkg/plugins/runtime/k8s/controllers/pod_converter_test.go
- pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists.existing-dataplane.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists.golden.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists.pod.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists.services-for-pod.yaml
instead of https://github.com/kumahq/kuma/pull/8300
> fix(k8s): don't temporarily remove all AvailableServices on ZoneIngress Pod reconciliations

- pkg/xds/bootstrap/template_v3.go
- pkg/xds/bootstrap/testdata/bootstrap.gateway.golden.yaml
- pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml
- pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml
- pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml
- pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml
- pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config-minimal-request.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config-token-path.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.ipv6.golden.yaml
- pkg/xds/bootstrap/testdata/generator.gateway.golden.yaml
- pkg/xds/bootstrap/testdata/generator.metrics-config.kubernetes.golden.yaml
> fix(envoy): remove apple flag

- pkg/core/rest/errors/error_handler.go
- pkg/core/rest/errors/errors.go
> feat(kuma-cp): map BadRequest error to 400

- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_egress.go
> ci(e2e): improve stability of locality aware e2e test

- pkg/core/rest/errors/error_handler.go
Having logger with a name "error" is confusing and incorrect in my opinion. I believe "rest" is more appropriate and it allows to filter these logs with the logger name if necessary.
- it won't
- no tests
> chore(kuma-cp): change logger name in HandleError from error to rest

- app/cni/pkg/cni/annotations.go
- app/cni/pkg/cni/annotations_test.go
- app/cni/pkg/cni/injector_linux.go
- pkg/transparentproxy/kubernetes/kubernetes.go
- pkg/transparentproxy/transparentproxy_v2.go
- test/e2e/cni/e2e_suite_test.go
- test/e2e/cni/exclude_outbound_port.go
Kuma Init container supports the following pod annotations:
* `traffic.kuma.io/exclude-outbound-tcp-ports-for-uids`
* `traffic.kuma.io/exclude-outbound-udp-ports-for-uids`
but Kuma CNI doesn't. Current PR adds support for these annotations for Kuma CNI. 
[Ideally](https://github.com/kumahq/kuma/issues/8320), we'd like to converge Kuma CNI and Transparent Proxy code bases to share parsing and config structures.
> fix(kuma-cni): support port exclusion for UIDs

- .circleci/config.yml
- go.mod
to fix:
- https://osv.dev/vulnerability/GO-2023-2185
- https://osv.dev/vulnerability/GO-2023-2186
- broken security scanner
> chore(deps): update go to 1.21.4

- tools/ci/update-vulnerable-dependencies.sh
xrel: https://github.com/kumahq/kuma/pull/8341/files
This way when there is a vulnerability in go itself security update will update it.
after running this on current master I get:
```
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 43a41545c..4ddb8dd8f 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,7 +3,7 @@ parameters:
go_version:
type: string
-    default: "1.21.3"
+    default: "1.21.4"
first_k8s_version:
type: string
default: "v1.23.17-k3s1"
diff --git a/go.mod b/go.mod
index 00534603e..d72d540a4 100644
--- a/go.mod
+++ b/go.mod
@@ -1,6 +1,6 @@
module github.com/kumahq/kuma
-go 1.21.3
+go 1.21.4
require (
cirello.io/pglock v1.14.1
@@ -54,22 +54,22 @@ require (
github.com/vishvananda/netlink v1.2.1-beta.2
github.com/vishvananda/netns v0.0.4 …
```
> ci(actions): make security update work with go updates

- pkg/api-server/gui_handler_test.go
closes https://github.com/kumahq/kuma/issues/8329
> test(gui): fix gui test not working on branches that start with release-x.y*

- app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
- app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml
- pkg/api-server/testdata/inspect/empty_resources_dataplanes.golden.json
- pkg/api-server/testdata/inspect/match_mesh_dataplanes.golden.json
- pkg/api-server/testdata/inspect/match_meshservice_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshgateway_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshgatewayroute_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshhttproute_absent_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshhttproute_dataplanes.golden.json
- pkg/api-server/testdata/inspect/meshtimeouthttproute.golden.json
- pkg/api-server/testdata/inspect/namefilter_dataplanes.golden.json
- pkg/api-server/testdata/inspect/pagination_dataplanes.golden.json
- pkg/api-server/testdata/inspect/policy_not_found_dataplanes.golden.json
- pkg/api-server/testdata/inspect/proxytemplate_dataplanes.golden.json
- pkg/api-server/testdata/inspect/retry_dataplanes.golden.json
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/dataplanepolicies/06.golden.yaml
without this we get "bad address: github.com" errors
> fix(observability): add annotation to make observability while running CNI work

- docs/generated/kuma-cp.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/config.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/kds/context/context.go
- pkg/kds/context/context_test.go
- test/framework/config.go
- test/framework/envs/multizone/env.go
> feat(kuma-cp): move KDS hash suffix under a feature flag

- app/kumactl/cmd/install/install_transparent_proxy.go
- docs/generated/cmd/kumactl/kumactl_install_transparent-proxy.md
- pkg/transparentproxy/config/config.go
- pkg/transparentproxy/iptables/builder/builder.go
When running `kumactl install transparent-proxy`, the default behavior with the `--max-retries` flag is set to `0` should not be treated as if the flag wasn't provided. Instead, the value `0` should be accepted as a valid option and should be used to disable retries.
- it won't
- manually tested
> fix(tproxy): allow value 0 in --max-retries flag for tproxy install

- app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
- app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml
That way we can exclude traffic only for the initContainer.
> fix(observability): change Grafana container UID to be different from initContainer UID

- .github/workflows/helm-release.yaml
going by this comment: https://youtrack.jetbrains.com/issue/TW-83463/All-public-repos-are-shown-during-new-Project-Build-Configuration-Creation-even-if-they-were-excluded-in-the-Repository-access#focus=Comments-27-8077545.0-0
maybe it will help 🤷 
> ci(actions): fix helm release by not specifying repostiory scope

- .github/workflows/release.yaml
- .github/workflows/update-docs.yaml
This means that the person that releases doesn't have to do anything for the docs PR to make its way.
- The update-docs workflows now triggers on push to paths that are synced to docs
- The release workflow is fixed for when we trigger a release
> ci(docs): auto-trigger workflows on release and docs change

- .github/workflows/golangci-lint.yml
> ci(.github): backport golangci-lint

- .github/workflows/release.yaml
- .github/workflows/update-docs.yaml
* The master job updates for all branches
> ci(.github): fix release which was invalid and ignore branches on docs

- .github/workflows/build-test-distribute.yaml
- N/A
- Confirmed.
- No need.
- No need.
- labeled
This PR makes these jobs run in parallel to speed the overall run:
- build
- test
- check
A successful run can be found here: https://github.com/jijiechen/kuma/actions/runs/6878015850
This PR also includes some other related minor improvements.
> ci(actions): made build/test/check run in parallel in build-test-distribute workflow

- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
- pkg/test/resources/builders/dataplane_builder.go
- pkg/test/resources/builders/targetref_builder.go
- pkg/test/xds/builders/context_builder.go
- pkg/test/xds/builders/endpoint_builder.go
- pkg/test/xds/builders/endpointmap_builder.go
- pkg/test/xds/builders/proxy_builder.go
- pkg/test/xds/builders/routing_builder.go
- pkg/test/xds/samples/endpoint_samples.go
- pkg/test/xds/samples/meshcontext_samples.go
> test(policy): introduce new resources builders for tests

- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/header-modifiers.listeners.golden.yaml
- pkg/plugins/policies/meshhttproute/xds/filters/requestredirect.go
> fix(MeshHTTPRoute): use 302 as default status code on Universal to match Kubernetes

- pkg/xds/generator/egress/external_services_generator.go
- pkg/xds/generator/egress/testdata/01.externalservice-only.golden.yaml
- pkg/xds/generator/egress/testdata/03.mixed-services.golden.yaml
- pkg/xds/generator/egress/testdata/04.mixed-services-custom-trafficroute.golden.yaml
- pkg/xds/generator/egress/testdata/05.mixed-services-with-custom-trafficpermissions.golden.yaml
- pkg/xds/generator/egress/testdata/06.mixed-services-with-external-in-other-zone.golden.yaml
We do this for requests when not using ZoneEgress.
> fix(ZoneEgress): rewrite host header on ExternalService requests

- test/e2e_env/multizone/trafficroute/trafficroute.go
I've noticed a few flakes of the 80/20 test for mutlizone:
* https://app.circleci.com/pipelines/github/kumahq/kuma/26017/workflows/3f9768e0-16c2-445d-b7d7-5b823d59afbf/jobs/537004
* https://app.circleci.com/pipelines/github/kumahq/kuma/25961/workflows/4cc86364-a616-426c-befd-af0c8b2d650f/jobs/534954
This PR adds a similar test for local traffic, so we can observe if the problem relates exclusively to multizone traffic. 
> test(e2e): add 80/20 split for local only services

- pkg/kds/v2/server/components.go
Without this the `kds_delta_generation` metric is not reported correctly.
> fix(metrics): fix kds metrics for simple watchdog

- pkg/plugins/runtime/k8s/controllers/pod_controller.go
> chore(k8s): don't record Event on context.Canceled

- pkg/kds/server/status_sink.go
- pkg/multitenant/multitenant.go
> refactor(kuma-cp): use context.WithoutCancel where possible

- pkg/xds/topology/router.go
- pkg/xds/topology/router_helper_test.go
- pkg/xds/topology/router_test.go
I'm going to extend the ResourceMeta interface with the GetLabels method, so I looked through existing implementations to remove implementations we don't need.
> chore(kuma-cp): remove PseudoMeta, we already have test_model.ResourceMeta

- pkg/core/bootstrap/bootstrap.go
- pkg/metrics/metrics.go
- pkg/plugins/bootstrap/k8s/plugin.go
Otherwise we get different "zone" in metrics for global cp
vs 
> fix(metrics): unify zone name in metrics for k8s and universal

- pkg/core/runtime/builder.go
- pkg/core/runtime/runtime.go
- pkg/core/runtime/runtime_suite_test.go
- pkg/core/runtime/runtime_test.go
- pkg/test/api_server/api_server.go
- pkg/test/runtime/runtime.go
So far when used `WithAPIWebServiceCustomize` more than once, only the last function was being used and others silently ignored. Now we can customize WebService multiple times
- it won't
> chore(kuma-cp): allow to pass more apiWebServiceCustomize fns

- mk/check.mk
otherwise it fails for parent projects that have different paths for actions
> ci(lint): add prefix to actions paths

- docs/madr/decisions/032-add-inbound-in-runtime.md
A solution for https://github.com/kumahq/kuma/issues/5086
> docs(MADR): add inbound in runtime

- test/e2e/gateway/gatewayapi/conformance_test.go
> test(e2e): fix Gateway API Namespace label value

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
- deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
Everywhere else we support both `'true'` and `'enabled'` 
> fix(k8s): support injection with label kuma.io/sidecar-injection: 'true'

- .circleci/config.yml
- .github/workflows/build-test-distribute.yaml
In the latest GitHub Actions run, there  are two issues:
1. a successful trigger of E2E will also run `kuma-commit` workflow which is redundant since we already run  it on every `push` event
2. the PR checks are not providing secrets according to GitHub security policies. An example run could be found [here](https://github.com/kumahq/kuma/actions/runs/7022080252/job/19105818733).
This PR is to fix these issues.
- N/A
- Confirmed
- Added
- No need
- No need.
> ci(actions): do not run kuma-commit workflow when trigger E2E on CircleCI; use pull_request_target on PRs to master

- tools/releases/dockerfiles/envoy.Dockerfile
Dependabot will upgrade the image either way, we might as well see if the hash change moves us a minor version or not.
> chore(deps): more explicit image tag in envoy.Dockerfile

- .github/workflows/build-test-distribute.yaml
- .github/workflows/e2e.yaml
- N/A
- Confirmed
- Added
- No need
- No need to back-port.
This PR follows the previous one at [here](https://github.com/kumahq/kuma/pull/8457) and supports running E2E tests on GitHub Actions when `arch is amd64`, other arches will still run on CircleCI
> ci(actions): run amd64 E2E on GitHub actions and arm64 on CircleCI

- .github/workflows/build-test-distribute.yaml
Skips the e2e tests for now, and open up when they are stable.
- N/A
- Confirmed 
- N/A
- Added
- No need
- No need
> ci(actions): disable e2e tests because they are not stable for the moment

- pkg/plugins/policies/core/jsonpatch/jsonpatch_suite_test.go
- pkg/plugins/policies/core/jsonpatch/merge_test.go
Adds test that would be useful for my debugging. It was far from obvious that I have to use camelCase instead of snake_case, because Envoy returns snake_case from /config_dump. I'll also add this to docs.
> test(unit): add json patch merge test

- pkg/kds/service/server.go
This way we can use more of the existing gRPC status codes in authorizers and not have them logged as errors in the CP.
> feat(kds): log additional gRPC status codes at info level

- test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid.go
- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_egress.go
The CI is unstable enough to just retry these tests
ref #4700
> test(e2e): add retries to prevent some flakes

- pkg/gc/components.go
- pkg/gc/finalizer.go
- pkg/gc/finalizer_test.go
Coming from service review.
Do we want to make this configurable?
> chore(finalizer): add retry to finalizer

- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_egress.go
- test/e2e_env/multizone/localityawarelb/locality_multizone_hybrid.go
> test(e2e): disable flaky locality aware tests

- pkg/xds/generator/zoneproxy/destinations.go
> chore(kuma-cp): fix function usage after bad merge

- .github/commitlint.config.js
There's been a few `chore(tests)` which shouldn't exist as they are not user visible changes
> ci(commitlint): disallow `tests` as scope it's a type

- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
- pkg/plugins/runtime/gateway/route/table.go
- pkg/plugins/runtime/gateway/route_table_generator.go
- pkg/xds/envoy/routes/route_configurers.go
> feat(MeshHTTPRoute): support all matches with MeshGateway

- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
- app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
- deployments/charts/kuma/crds/kuma.io_meshaccesslogs.yaml
- docs/generated/openapi.yaml
- docs/generated/raw/crds/kuma.io_meshaccesslogs.yaml
- pkg/plugins/policies/meshaccesslog/api/v1alpha1/meshaccesslog.go
- pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml
- pkg/plugins/policies/meshaccesslog/k8s/crd/kuma.io_meshaccesslogs.yaml
Added kubebuilder annotations with defaults and examples to generate better openapi schema.
- Closes https://github.com/kumahq/kuma/issues/8223
- https://github.com/kumahq/kuma-website/issues/1538
- https://github.com/kumahq/kuma/issues/8348#issuecomment-1832369151
- It won't
- No changes which would require new tests
- It doesn't
> chore(MeshAccessLog): improve policy's openapi schema

- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
- app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
- deployments/charts/kuma/crds/kuma.io_meshtimeouts.yaml
- docs/generated/openapi.yaml
- docs/generated/raw/crds/kuma.io_meshtimeouts.yaml
- pkg/plugins/policies/meshtimeout/api/v1alpha1/meshtimeout.go
- pkg/plugins/policies/meshtimeout/api/v1alpha1/schema.yaml
- pkg/plugins/policies/meshtimeout/k8s/crd/kuma.io_meshtimeouts.yaml
Added kubebuilder annotations with defaults and examples to generate better openapi schema.
- Closes https://github.com/kumahq/kuma/issues/8260
- It won't
- No changes which would require new tests
- It doesn't
> chore(MeshTimeout): improve policy's openapi schema

- tools/policy-gen/bootstrap/root.go
> ci(policy-gen): change "inplace" to "in-place"

- pkg/api-server/authn/skip.go
- pkg/api-server/index_endpoints.go
- pkg/plugins/authn/api-server/tokens/authenticator.go
- test/e2e_env/universal/auth/user_auth.go
Fix #3576
It will also simplify logic in KM
> feat(api-server): skip auth on specific endpoints

- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
- app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
- deployments/charts/kuma/crds/kuma.io_meshtimeouts.yaml
- docs/generated/openapi.yaml
- docs/generated/raw/crds/kuma.io_meshtimeouts.yaml
- pkg/plugins/policies/meshtimeout/api/v1alpha1/meshtimeout.go
- pkg/plugins/policies/meshtimeout/api/v1alpha1/schema.yaml
- pkg/plugins/policies/meshtimeout/k8s/crd/kuma.io_meshtimeouts.yaml
This reverts commit b81edc42482c77b1c20791a3804ffc4011fe7689.
Validation in current form doesn't allow to set the default values using `kubebuilder` annotations.
> Revert "chore(MeshTimeout): improve policy's openapi schema (#8532)"

- app/kuma-dp/pkg/dataplane/metrics/server.go
- go.mod
- go.sum
- pkg/api-server/server.go
- pkg/diagnostics/server.go
- pkg/dp-server/server/server.go
- pkg/mads/server/server.go
Logs like this
```
2023/12/05 10:49:11 http: TLS handshake error from 10.42.0.1:42848: EOF
2023-12-05T10:49:11.119Z	INFO	controllers.Pod	Dataplane updated	{"pod": {"name":"demo-app-gateway-747594bcb5-sv6db","namespace":"kuma-demo"}}
2023/12/05 10:49:11 http: TLS handshake error from 10.42.0.1:42896: EOF
```
are very annoying because we don't know which sever it is and those logs are not in common format. I found a way to enrich those logs so it looks like this
```
2023-12-05T12:09:21.885Z	INFO	dp-server	http: TLS handshake error from 10.42.0.8:38384: EOF
```
> chore(logging): add more context on errors from http servers

- pkg/plugins/policies/meshhttproute/api/v1alpha1/validation.go
- pkg/plugins/policies/meshhttproute/api/v1alpha1/validation_test.go
Added validation for PreciseHostname used in RequestRedirect and URLRewrite filters
- Closes https://github.com/kumahq/kuma/issues/8286
- It won't
- Unit tests added and run locally
> chore(MeshHTTPRoute): add precise hostname validation

- .circleci/config.yml
- .github/workflows/e2e.yaml
CircleCI failed to load downloaded artifacts if there are new commits pushed in the branch during an ongoing run.
This PR is to pin the SHA that CircleCI workflows run on.
It should fix failures like this: https://app.circleci.com/pipelines/gh/kumahq/kuma/26972/workflows/be3668af-9369-4cf2-81d4-39e61694606a/jobs/566681
- N/A
- Confirmed 
- N/A
- Added
- No need
- No need
> ci(actions): pin git SHA to the same value as GH Actions when running e2e tests on CircleCI

- pkg/core/xds/matched_policies.go
- pkg/plugins/policies/core/matchers/dataplane.go
- pkg/plugins/policies/core/matchers/dataplane_test.go
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/01.policies.yaml
- pkg/plugins/policies/core/rules/rules.go
At the moment we're actually using `ToRules` in policies which doesn't take into account the MeshGateway listener tags. We need a new entry indexed by listener, like `FromRules`, but for `to` policies.
> feat(policy): support MeshGateway listener matching

- pkg/test/store/postgres/test_container.go
- test/framework/k8s_cluster.go
- test/framework/setup.go
Try to fix flaky tests related to postgre db:
* Connect to the newly created database instance before test cases run
Trying to fix this flaky:
https://github.com/kumahq/kuma/actions/runs/7119978753/job/19386239557#step:6:3840
Print more useful information when timeout waiting for k8s Pod to be available:
* print Pod phase and conditions
* print Deployment and ReplicaSet conditions
Trying to help on this flaky:
https://github.com/kumahq/kuma/actions/runs/7116642948/job/19375940607#step:10:25037
- N/A
- Confirmed
- N/A
- Checked
- No need
- No backport.
> test(framework): try to fix flaky tests related to postgre db and k8s resource installation

- pkg/plugins/policies/meshproxypatch/api/v1alpha1/validator.go
- pkg/plugins/policies/meshproxypatch/api/v1alpha1/validator_test.go
Previously, the MeshProxyPatch policy only validated the first element in the provided modification object. This meant that if a modification object contained multiple types of modifications (e.g., cluster, listener and networkFilter), only the first type of modification would be applied, and the others would be silently ignored. To address this, I updated the validator to fail when multiple modification types to be specified within a single modification object.
- Closes https://github.com/kumahq/kuma/issues/8287
- It won't
- Unit tests were updated
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a- …
> chore(MeshProxyPatch): handle multiple modification types in a single object

- pkg/test/xds/builders/matchedpolicies_builder.go
Needed to test policies after #8551
> test(policy): add gateway policy builder

- test/e2e_env/kubernetes/kubernetes_suite_test.go
Seems flaky :( Skipping it for now
> test(e2e): skip change service

- docs/madr/decisions/019-fault-injection-policy.md
What do we think about this? This is basically to keep only `to` rules for `MeshGateway`.
> docs(MADR): add `to` to `MeshFaultInjection` for top level `MeshGateway`

- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
> feat(MeshAccessLog): select gateway listeners

- test/e2e_env/kubernetes/meshtimeout/meshtimeout.go
> test(e2e): try to reduce meshtimeout k8s flakiness

- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
> feat(MeshHealthCheck): select MeshGateway listeners

- pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go
> feat(MeshCircuitBreaker): select MeshGateway listeners

- docs/madr/decisions/035-mesh-metric-policy.md
After extending Prometheus integration ([PR](https://github.com/prometheus/prometheus/pull/13278)), and some discussion with @slonka we think that changing backend `name` to `promtheus.clientId` makes more sense
> fix(madr): change `MeshMetric` MADR to use prometheus client id instead of backend name for MADS

- mk/distribution.mk
This was causing issues in CI like GH actions which don't have tty
addresses the failure: https://github.com/kumahq/kuma/actions/runs/7185343654/job/19571263923#step:11:17
> ci(publish): don't use -i in docker

- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/split-traffic.endpoints.golden.yaml
* Fix service/endpoint inconsistency
* These confs need to have a `MeshService` subset since `kind: Mesh` isn't allowed with `MeshTCPRoute.spec.to[].targetRef`
* This means I'm kind of guessing at the intention of the tests
* Outbounds were missing from the `Dataplanes`
> test(MeshTCPRoute): improve and fix test cases

- pkg/core/runtime/component/resilient.go
- pkg/util/watchdog/watchdog.go
Right now, runtime errors, like out of bounds accesses, aren't logged with a stack trace.
> chore(kuma-cp): include stack traces on runtime errors

- .circleci/config.yml
- go.mod
> chore(deps): update go to 1.21.5

- pkg/xds/generator/ingress_generator_test.go
- pkg/xds/generator/testdata/ingress/virtual-outbound.envoy.golden.yaml
Otherwise there are no traffic routes present for this test which isn't a realistic scenario.
> test(xds): add default allow all to ingress test resources

- .github/workflows/build-test-distribute.yaml
- .gitignore
Because it makes sense and it's easier on self-hosted runners
> ci(github): use a ci_tools dir inside the checkout

- docs/madr/decisions/036-route-transition.md
[Rendered](https://github.com/michaelbeaumont/kuma/blob/docs/madr-route-transition/docs/madr/decisions/036-route-transition.md)
For the record.
> docs(MADR): document transition from TrafficRoute to Mesh*Route

- pkg/api-server/resource_endpoints.go
- pkg/core/resources/registry/registry.go
- pkg/gc/finalizer.go
- pkg/kds/reconcile/snapshot_generator.go
- pkg/kds/v2/reconcile/snapshot_generator.go
add MustNewList and MustNewObject to TypeRegistry interface, panic on error and replace calls where the errors are ignored
'Create Must* functions for registry.Global #2572'
https://github.com/kumahq/kuma/issues/2572
> refactor(pkg/core): create MustNewList and MustNewObject for registry

- .github/workflows/e2e.yaml
- mk/k3d.mk
- mk/kind.mk
This is useful for child repos as we use the environment from KUMA
> ci(e2e): use KUMA_DIR instead of TOP in e2e setup

- pkg/core/resources/apis/mesh/external_service_validator.go
- pkg/core/resources/apis/mesh/external_service_validator_test.go
We cannot use same service tag as hostname.
When we do this, we create Envoy Cluster of name "hostname.org" then when Envoy does DNS resolution instead of returning VIPs it returns actual IPs. It seems that it's a (not documented?) behavior of DNSFilter that it first lookup for host = cluster name and only then it goes through the static list of IPs https://github.com/envoyproxy/envoy/blob/2c7edc491b6e5b0e4a9fa76b5f3aa647f41eb1af/source/extensions/filters/udp/dns_filter/dns_filter.cc#L325C1-L326C1
fix #8075
Technically it's a breaking change, but since the behavior was broken I don't think anyone uses it
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to …
> feat(ExternalService): validate same value for service and address

- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/01.golden.yaml
- pkg/plugins/policies/core/rules/rules.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtrace/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtrace/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtrace/plugin/v1alpha1/testdata/simple-gateway.listeners.golden.yaml
> feat(MeshTrace): select MeshGateway listeners

- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go
> chore(routes): fix plugin after merge

- .github/workflows/build-test-distribute.yaml
> ci(github): correct syntax of secrets in distribution

- .github/workflows/helm-release.yaml
- .github/workflows/pr-comments.yaml
> ci(github): set CI_TOOLS_DIR so that cache always works

- .github/workflows/blackbox-tests.yaml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/e2e.yaml
- .github/workflows/helm-release.yaml
- .github/workflows/pr-comments.yaml
> ci(github): add arch in cache keys

- .github/workflows/update-docs.yaml
[Related PR](https://github.com/kumahq/kuma-website/pull/1554)
Update github action to copy the auto-generated docs to `app/assets/<versions>/raw/`
These are static files and shoudn't be processed by Jekyll, moving them to app/assets prevents that from happening.
> ci(docs): change auto-generated docs path in kuma-website

- .github/workflows/update-insecure-dependencies.yaml
seems to have worked https://github.com/kumahq/kuma/actions/runs/7259538562/job/19776891548
based on https://github.com/actions/runner-images/discussions/7188#discussioncomment-6750749
> chore(deps): fix update insecure dependencies by setting bigger swap

- go.mod
- go.sum
This way Dependabot shouldn't [try to upgrade it to `v0.0.2`](https://github.com/kumahq/kuma/pull/8656)
> chore(deps): tweak github.com/bakito/go-log-logr-adapter version string

- .github/workflows/build-test-distribute.yaml
This only applies to PRs so that each individual commits still get their own CI
> ci(github): use concurrency to avoid multiple CI in PRs

- .github/dependabot.yml
- pkg/plugins/leader/postgres/leader_elector_test.go
- pkg/plugins/leader/postgres/postgres_suite_test.go
- pkg/plugins/resources/postgres/listener_test.go
- pkg/plugins/resources/postgres/migrate.go
- pkg/plugins/resources/postgres/migrate_test.go
- pkg/plugins/resources/postgres/plugin.go
- pkg/plugins/resources/postgres/store_suite_test.go
- pkg/plugins/resources/postgres/store_template_test.go
- pkg/test/store/postgres/test_container.go
> test(postgres): simplify tests to hope to get stability

- .github/workflows/build-test-distribute.yaml
> ci(github): improve test matrix when not doing full matrix

- .github/workflows/build-test-distribute.yaml
This might make names better on auto-generated stuff
> ci(github): don't set the names in the matrix e2e jobs

- test/framework/k8s.go
- N/A
- Confirmed
- Added
- No need
- No need
> test(framework): get logs from pods when it's not available to help diagnose CI issues

- .github/workflows/build-test-distribute.yaml
- .github/workflows/e2e.yaml
https://github.com/kumahq/kuma/pull/8661 and https://github.com/kumahq/kuma/pull/8660
> chore(deps): bump actions/download-artifact and actions/upload-artifact from 3 to 4

- pkg/kds/server/status_tracker.go
- pkg/kds/v2/server/status_tracker.go
- pkg/xds/server/callbacks/dataplane_status_tracker.go
There were rare cases where state is not in the streams map. We simply avoid a nil pointer by returning early in this case. There shouldn't be any problems with this as the entry is not in the map anyway
However, maybe there's a race where streamClosed is called before streamOpen
> fix(kds): avoid rare cases where onStreamClosed is called with no state

- UPGRADE.md
- pkg/api-server/inspect_endpoints_test.go
- pkg/api-server/testdata/inspect/dataplanes/_rules/meshhttproute.golden.json
- pkg/api-server/testdata/inspect_dataplane_rules_subset.golden.json
- pkg/plugins/policies/core/matchers/dataplane.go
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/dataplanepolicies/02.golden.yaml
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/fromrules/multiple-policies-lexicog-order.golden.yaml
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/fromrules/multiple-policies-lexicog-order.policies.yaml
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/01.golden.yaml
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/torules/02.golden.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/merge_test.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtrafficpermission/graph/reachable_services_graph_test.go
As a potential reference, gateway api specifies the lexicographically first policy wins.
> fix(policies): first lexicographically wins, kind MeshGateway with tags over kind MeshGateway

- .github/workflows/update-docs.yaml
> ci(github): don't have update docs trigger on non release branches

- test/framework/k8s_cluster.go
We were waiting for everything at once. This might be the reason for things to be unstable.
> test(e2e): wait for CP to be started before other components

- .circleci/config.yml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/e2e.yaml
> ci(circle): debug arm builds and not have it fail CI

- pkg/kds/global/components.go
- pkg/kds/server/status_tracker.go
- pkg/kds/v2/server/status_tracker.go
Since we now do status tracking on the zone we need to support not having metadata as these are only sent to global.
> fix(kds): make status tracker work when there's no metadata

- app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
- app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
- app/kumactl/data/install/k8s/metrics/grafana/kuma-cp.json
- app/kumactl/data/install/k8s/metrics/grafana/kuma-dataplane.json
- app/kumactl/data/install/k8s/metrics/grafana/kuma-gateway.json
- app/kumactl/data/install/k8s/metrics/grafana/kuma-mesh.json
- app/kumactl/data/install/k8s/metrics/grafana/kuma-service-to-service.json
- app/kumactl/data/install/k8s/metrics/grafana/kuma-service.json
https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/
> feat(grafana): change fixed interval to rate interval variable

- pkg/util/os/limits_test.go
This test is annoying on darwin as it fails, skip it
> test(util): skip darwin test that was failing

- .circleci/config.yml
- .github/workflows/e2e.yaml
To fix CI errors here:
https://github.com/kumahq/kuma/actions/runs/7273842586/job/19819186863#step:16:73
The artifact downloading failures started to occur after this PR: https://github.com/kumahq/kuma/pull/8701
There are some behavior changes between these two versions of the artifact plugin, according to GH documents:
https://github.com/actions/toolkit/tree/main/packages/artifact#improvements
These changes broke our download artifact implementation for CircleCI: artifacts uploaded by version 4 are not available to the "internal API" we are using (which worked for version 3).
Fortunately, according to GH docs, artifacts uploaded by version 4 are now available to their public rest APIs. So we are switching to use their public API. This will also be a more reliable way to achieve our …
> ci(github): use GitHub public artifact API when downloading artifacts from CircleCI

- pkg/core/resources/model/resource.go
- pkg/plugins/policies/core/rules/merge.go
- pkg/plugins/policies/core/rules/merge_test.go
- pkg/plugins/policies/meshhttproute/api/v1alpha1/helpers.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/merge_test.go
See the tests at https://github.com/michaelbeaumont/kuma/blob/fix/route-merging-order/pkg/plugins/policies/meshhttproute/plugin/v1alpha1/merge_test.go
> fix(MeshHTTPRoute): make ordering more consistent

- .github/workflows/e2e.yaml
In a previous PR, we prevented arm e2e test failures from failing the GitHub Actions runs, because we didn't fix the CIecleCI run at that time.
https://github.com/kumahq/kuma/pull/8719
And now the arm E2E tests are run stably, so we are openning the ability to fail CI on test failures.
https://app.circleci.com/pipelines/gh/kumahq/kuma
- N/A
- Confirmed
- Tested
- Added
- No need
- No need
> ci(github): allow arm/circleci failures to fail GH Actions CI

- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator.go
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator_test.go
> fix(MeshCircuitBreaker): allow MeshGateway through validation

- pkg/core/resources/apis/mesh/validators.go
- pkg/core/resources/apis/mesh/validators_test.go
- pkg/plugins/policies/meshaccesslog/api/v1alpha1/validator.go
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator.go
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/validator.go
- pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator.go
- pkg/plugins/policies/meshhttproute/api/v1alpha1/validation.go
- pkg/plugins/policies/meshproxypatch/api/v1alpha1/validator.go
- pkg/plugins/policies/meshtimeout/api/v1alpha1/validator.go
This doesn't change any behavior just allows validating the presence of tags.
> refactor(policy): control whether MeshGateway tags are allowed

- .circleci/config.yml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/e2e.yaml
The download-artifact action plugin was updated to v4 recently and we are seeing request timeouts after that updating.
This is a known issue at GitHub Actions server side and it's tracked at https://github.com/actions/download-artifact/issues/249
I'm adding some retries to work around this issue for the moment. This work around does not break the main run process, we can see successful artifact downloading from the following run:
https://github.com/jijiechen/kuma/actions/runs/7394542119/job/20117851713
(The run failed eventually because of flaky e2e tests, but we can stil know the PR here will not break the CI process)
- https://github.com/kumahq/kuma/actions/runs/7291088227/job/19869652348#step:9:21
- Confirmed
- …
> ci(.github): add retry to download artifacts to work around the RequestTimeout issue of downloading artifacts

- pkg/api-server/server.go
- pkg/plugins/secrets/k8s/mapper.go
- pkg/plugins/secrets/k8s/secret.go
- test/e2e_env/kubernetes/api/api.go
- test/e2e_env/universal/api/api.go
Fix requesting Secrets in Kube format using Kuma API
xref #8212
> fix(api): secret in k8s format

- pkg/plugins/policies/meshretry/api/v1alpha1/validator.go
- pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go
> feat(MeshRetry): select MeshGateway listeners

- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
We need to propagate tags to backendsRefs so that later in the case of VirtualOutbounds we can match them and create the correct configuration
> feat(policy): add tags to backends for support VirtualOutbounds

- test/e2e/bootstrap/corefile_template.go
- test/e2e/bootstrap/e2e_suite_test.go
- test/e2e_env/kubernetes/kubernetes_suite_test.go
To fix comments from this previous PR https://github.com/kumahq/kuma/pull/8634
- N/A
- Confirmed
- N/A
- No need
- No
- No
> test(bootstrap): move corefile template e2e test to test/e2e from test/e2e_env/kubernetes

- pkg/plugins/policies/core/matchers/egress.go
- pkg/plugins/policies/core/matchers/egress_test.go
- pkg/plugins/policies/core/matchers/testdata/egressmatchedpolicies/fromtorules/01.es.yaml
- pkg/plugins/policies/core/matchers/testdata/egressmatchedpolicies/fromtorules/01.golden.yaml
- pkg/plugins/policies/core/matchers/testdata/egressmatchedpolicies/fromtorules/01.policies.yaml
When policy has `from` and `to` it cannot configure egress. `MeshFaultInjection` is a policy that has both and should configure so instead of checking if policy has both, in case it has both we are taking `from` https://github.com/kumahq/kuma/pull/8739/files#diff-26e4e045ed595ee5e2ddec0d50aa1d944fddf095cf98773505a6f713d892d469L42
> feat(policy): allow policies with from and to configuring egress

- app/kumactl/cmd/export/export.go
- app/kumactl/pkg/client/client_suite_test.go
- app/kumactl/pkg/client/kube_resources_client.go
- app/kumactl/pkg/client/kube_resources_client_test.go
- app/kumactl/pkg/cmd/root_context.go
Kumactl export in Kubernetes format.
It converts resources one by one. Obviously, this is not optimal, but my reasoning is
* We would need to introduce new list APIs with two alternative schemas based on query param which is not a great design. We cannot reuse `rest.ResourceList` for this, because it requires `ResourceSpec`
* It does not matter if kumactl export will run in 1s or 5s, because it's run once when you do a federation.
* It probably won't be used for backup either, because if you operate on Kubernetes you do a backup on your Kube API Server / etcd level.
We can optimize this if needed.
I plan to write E2E tests when we have applying resources on Zone CP. This way we can test full flow of Zone federation.
[1]: …
> feat(kumactl): export in kube format

- test/e2e_env/multizone/sync/sync.go
> chore(e2e): disable flaky e2e test

- pkg/plugins/runtime/k8s/webhooks/dataplane_validator.go
- pkg/plugins/runtime/k8s/webhooks/externalservice_validator.go
- pkg/plugins/runtime/k8s/webhooks/mesh_validator.go
- pkg/plugins/runtime/k8s/webhooks/ratelimit_validator.go
- pkg/plugins/runtime/k8s/webhooks/validation.go
Atm there are errors like:
```
spec.spec.to[0].rules[0].default.backendRefs[0].kind: value is not supported
```
on Kubernetes. This checks if we need to add the extra `spec.`. Tested universal/k8s and targetRef/non-targetRef matrix.
> chore(policy): fix `spec.spec` in validation errors

- pkg/plugins/policies/core/matchers/egress.go
> feat(kuma-cp): added comment and more explicit structure

- test/e2e/externalservices/localityawarelb_multizone/locality_multizone_hybrid.go
- test/e2e/helm/kuma_helm_deploy_global_zone.go
I executed full matrix and _legacy e2e_ passed on branch, but failed on master...
> test(e2e): fix cluster name in the resource

- pkg/core/resources/apis/mesh/validators.go
- pkg/core/resources/apis/mesh/validators_test.go
Since these refer to K8s objects
> fix(policy): allow period in targetRef names

- test/e2e_env/multizone/sync/sync.go
fixes https://github.com/kumahq/kuma/issues/8756
- https://github.com/kumahq/kuma/issues/8756
- Confirmed
- Added
- No
- No
> test(e2e): fix test failure for syncing when on legacyKDS mode

- pkg/mads/v1/generator/meshmetrics.go
- pkg/mads/v1/reconcile/snapshot_generator.go
- pkg/mads/v1/service/components.go
- pkg/mads/v1/service/service.go
- test/e2e_env/kubernetes/kubernetes_suite_test.go
- test/e2e_env/kubernetes/meshmetric/meshmetric.go
- test/framework/envs/kubernetes/env.go
- test/framework/envs/multizone/env.go
- test/framework/interface.go
- test/framework/k8s_cluster.go
- test/framework/k8s_controlplane.go
- test/framework/universal_controlplane.go
> feat(policy): add `MeshMetric` policy e2e tests

- .github/workflows/e2e.yaml
When run a full-matrix CI for PRs, the git SHA passed to Circle was incorrect, so it was not possible to load correct images from the `build-output` generated on GH Actions.
An example failure can be found here (its a check of [PR 8738](https://github.com/kumahq/kuma/pull/8738)):
https://app.circleci.com/pipelines/gh/kumahq/kuma/29133/workflows/98afa0e8-1455-4fb3-bcb0-6e6649e99087/jobs/576232/parallel-runs/0/steps/0-110
To correct this, the only way is to use the same PR merge ref on CircleCI runs. We can not use a git SHA for PR builds, because:
1. The `github.event.pull_request.head.sha` is different from `github.sha`, which is identical to the SHA that had been checked out to on GH Actions. [See an example run](https://github.com/jijiechen/kuma/actions/runs/7456258131/job/20286615405?pr …
> ci(github): use merge commit sha for pull requests to trigger CircleCI builds

- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
- app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
- deployments/charts/kuma/crds/kuma.io_meshhttproutes.yaml
- docs/generated/openapi.yaml
- docs/generated/raw/crds/kuma.io_meshhttproutes.yaml
- pkg/plugins/policies/meshhttproute/api/v1alpha1/meshhttproute.go
- pkg/plugins/policies/meshhttproute/api/v1alpha1/schema.yaml
- pkg/plugins/policies/meshhttproute/api/v1alpha1/validation.go
- pkg/plugins/policies/meshhttproute/api/v1alpha1/validation_test.go
- pkg/plugins/policies/meshhttproute/k8s/crd/kuma.io_meshhttproutes.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
> feat(MeshHTTPRoute): add hostToBackendHostname rewrite with MeshGateway

- .github/dependabot.yml
- .github/workflows/auto-backport.yaml
- .github/workflows/blackbox-tests.yaml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/check.yaml
- .github/workflows/codeql.yaml
- .github/workflows/e2e.yaml
- .github/workflows/golangci-lint.yml
- .github/workflows/pr-comments.yaml
- .github/workflows/pr-merged.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecard.yml
- .github/workflows/update-docs.yaml
- .github/workflows/update-insecure-dependencies.yaml
- tools/postgres/Dockerfile
> ci: setup OSSF Scorecard and pin actions and Docker versions

- test/e2e_env/multizone/resilience/resilience_multizone_universal_postgres.go
- test/framework/testing.go
Looks like in some cases the containers are not fully removed before we create the new ones. We make sure to use different container names to avoid these kind of flakes
> test(e2e): avoid flake on postgres tests

- .github/workflows/e2e.yaml
The fix on yesterday didn't work, the correct field for reference PRs should be PR number instead of PR id.
```
Calling CircleCI api with parameters:
URL: https://circleci.com/api/v2/project/gh/kumahq/kuma/pipeline
BODY: {parameters:{gh_action_build_artifact_name:build-output,gh_action_run_id:7469668214,e2e_param_target:universal,e2e_param_k8sVersion:kind,e2e_param_arch:arm64,e2e_param_parallelism:1,e2e_param_cniNetworkPlugin:flannel,e2e_param_legacyKDS:false},branch:pull/1649958655/merge}
jq: error (at <stdin>:0): Invalid numeric literal at line 1, column 6 (while parsing 'Error requesting POST https://circleci.com/api/v2/project/gh/kumahq/kuma/pipeline (status 400) {"message":"Branch not found"}{"message":"Branch not found"}')
Error: Process completed with exit code 5.
``` …
> ci(github): fix branch name for reference PR branches to trigger CircleCI builds

- pkg/core/tokens/default_signing_key.go
- pkg/defaults/envoy_admin_ca.go
- pkg/defaults/mesh.go
- pkg/intercp/tls/defaults.go
I don't see a good reason to log "trying..." when we log on both success and failure.
> chore(kuma-cp): improve log messages about default creation

- test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
> test(e2e): check DPP name without zone prefix

- pkg/plugins/policies/core/xds/meshroute/listeners.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_filterchain.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/kafka.clusters.golden.yaml
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/kafka.endpoints.golden.yaml
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/kafka.listeners.golden.yaml
> feat(meshtcproute): add kafka protocol support

- README.md
Updates OSSF Badges.
The actual used links are not up to date.
The Scorecard is now viewable on a nice interface.
> docs(readme): update OSSF Badges

- .circleci/config.yml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/e2e.yaml
- Storing build artifacts was slow and unstable, we now rebuild each time.
- We also reduce the number of arm test cases (there's no real reason to rerun tests on arm so many times).
Example full run: https://github.com/kumahq/kuma/actions/runs/7478606778/job/20353924056
> ci(github): don't rely on artifacts, instead rebuild each time

- .github/workflows/e2e.yaml
- test/e2e/helm/kuma_helm_deploy_global_zone.go
- Helm fix was only partial in #8799
- #8676 didn't do what it was expected to
> test(e2e): fix ipv6 and helm failure

- pkg/intercp/catalog/heartbeat_component.go
- pkg/intercp/components.go
- pkg/intercp/server/server.go
This way we have the same values on all the log messages so we can debug error messages a little easier.
> chore(kuma-cp): improve intercp log messages

- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
> fix(MeshHealthCheck): handle gateway listener protocol correctly

- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/gateway-listener-specific.clusters.golden.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/gateway-listener-specific.endpoints.golden.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/gateway-listener-specific.listeners.golden.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/gateway-listener-specific.routes.golden.yaml
Per listener attachment was being ignored
> fix(MeshHTTPRoute): apply gateway rules properly to listeners

- pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin.go
> fix(MeshFaultInjection): handle listener protocol correctly

- app/kuma-dp/pkg/dataplane/meshmetrics/component.go
- test/e2e_env/kubernetes/meshmetric/meshmetric.go
> fix(policy): fix meshmetric e2e flake

- test/e2e_env/kubernetes/observability/tracing.go
- test/framework/k8s.go
- test/framework/k8s_cluster.go
- test/framework/setup.go
Display a nice and complete failure like: https://gist.github.com/lahabana/5f25fe340b532523b578503bb13267af
> test(e2e): add nice output with info when pod or deployment fail

- mk/e2e.new.mk
- test/e2e/bootstrap/e2e_suite_test.go
left over from https://github.com/kumahq/kuma/pull/8736
> test(e2e): avoid starting 2 k8s clusters in test/e2e-kubernetes

- test/e2e_env/kubernetes/kic/kong_ingress.go
- test/framework/deployments/kic/deployment.go
- test/framework/deployments/kic/kubernetes.go
This functionallity will be heavy reused when introducing e2e test cases for testing new policies with delegated gateway.
- related to: https://github.com/kumahq/kuma/issues/8746
- It won't
- Tested with existing e2e tests as well as locally on newly created tests which will be added in the following pull requests
> test(framework): extract getting IP for KIC service to deployment

- .github/workflows/build-test-distribute.yaml
- mk/test.mk
This uses `go test` instead of `ginkgo cli` This seems to run tests twice as quick.
> test(unit): don't generate test reports for quicker tests

- app/kumactl/cmd/apply/apply_test.go
- pkg/api-server/testdata/resource_400onInvalidJson.golden.json
- pkg/api-server/testdata/resource_400onInvalidMetaSchema.golden.json
- pkg/api-server/testdata/resource_400onInvalidSpecSchema.golden.json
- pkg/core/resources/apis/mesh/virtual_outbound_helpers.go
- pkg/core/resources/apis/mesh/virtual_outbound_helpers_test.go
- pkg/core/resources/apis/mesh/virtual_outbound_validator.go
- pkg/core/resources/apis/mesh/virtual_outbound_validator_test.go
- pkg/core/resources/model/rest/unmarshaller.go
- pkg/plugins/policies/core/matchers/dataplane.go
- pkg/transparentproxy/iptables/builder/builder.go
- test/framework/k8s.go
We were using `'%s'` is a few places, this can be a problem and a potential security issue.
Use `%q` which does the right escaping of `"`.
Fix #8830
> chore(security): fix quoting in some format

- .github/workflows/auto-merge.yaml
APP_ID was wrong it's a secrets not a var
> ci(github): fix bad reference in auto-merge

- .github/workflows/lifecycle.yml
> ci(github): add github app to lifecycle job

- pkg/kds/v2/client/zone_sync_test.go
- pkg/kds/v2/store/sync.go
- pkg/kds/zone/components.go
- pkg/kds/zone/components_test.go
Old zones don't have a `kuma.io/zone` label on ZoneIngress when upgrading to the new `master` we don't want Zone CP to sync ZoneIngresses without a `kuma.io/zone` label to Global pretending they're originating here. That's why upgrading from 2.5 to 2.6 (and 2.7) requires casting resources to `*core_mesh.ZoneIngressResource` and checking its `spec.zone` field.
> fix(kuma-cp): upgrade from Zone CP without labels to new one

- pkg/defaults/zone.go
We were failing to delete a zone which was causing KDS to be able to work
> fix(kds): fix deletion of previous zones in components

- test/e2e_env/kubernetes/meshtimeout/meshtimeout.go
Unfortunately we don't seem to find the root cause of this flake
> test(e2e): add FlakeAttempt to meshtimeout k8s test

- pkg/plugins/policies/core/matchers/dataplane.go
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/torules/04.dataplane.yaml
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/torules/04.golden.yaml
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/torules/04.policies.yaml
- pkg/plugins/policies/donothingpolicy/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshaccesslog/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshhealthcheck/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshhttproute/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshmetric/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshproxypatch/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshratelimit/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshretry/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshtcproute/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshtimeout/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshtrace/api/v1alpha1/zz_generated.resource.go
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/zz_generated.resource.go
- test/e2e_env/multizone/meshtimeout/meshtimeout.go
- tools/policy-gen/generator/cmd/core_resource.go
> feat(kuma-cp): enable zone-originated policies

- tools/dev/install-dev-tools.sh
These logs will be shown when debug logging is enabled during the github action run and might be helpful in debugging issues related to generating deps.lock file.
- It won't
- No tests
> ci(install-dev-tools.sh): add debug logs

- tools/dev/install-dev-tools.sh
Added more debug logs
- It won't
- No tests
> ci(install-dev-tools.sh): add more debug logs

- .gitignore
- mk/dependencies/go-deps.versions
The `mk/dependencies/go-deps.versions` file is used to calculate the `mk/dependencies/deps.lock` hash. However, when calling `make dev/tools` from another project, the hash can vary depending on whether `make dev/tools` has been previously called in the kuma directory. This is because if it was, two `go-deps.versions` files are being used in hash.
To ensure consistent `mk/dependencies/deps.lock` hashes across projects, we have included the `mk/dependencies/go-deps.versions` file in the repository. This will allow `make dev/tools` to produce the same hash regardless of whether it is called from within the kuma directory or from another project.
- It won't
- No tests
> …
> ci(go-deps): include `mk/dependencies/go-deps.versions` file

- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/basic.gateway.clusters.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/basic.gateway.endpoints.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/basic.gateway.listeners.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/basic.gateway.routes.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/locality_aware.gateway.clusters.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/locality_aware.gateway.endpoints.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/locality_aware.gateway.listeners.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/locality_aware.gateway.routes.golden.yaml
We were somewhat unnecessarily only taking the first resource of the given type.
> test(MeshLoadBalancingStrategy): improve gateway case golden files

- pkg/plugins/policies/meshtrace/api/v1alpha1/validator.go
- pkg/plugins/policies/meshtrace/api/v1alpha1/validator_test.go
> feat(MeshTrace): support kind MeshGateway

- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator.go
- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator_test.go
> feat(MeshLoadBalancingStrategy): support kind MeshGateway

- pkg/kds/global/components.go
- pkg/kds/v2/store/sync.go
Despite having a code on the Global:
```go
for _, r := range upstream.AddedResources.GetItems() {
r.SetMeta(util.CloneResourceMeta(r.GetMeta(),
util.WithLabel(mesh_proto.ZoneTag, upstream.ControlPlaneId),
util.WithLabel(mesh_proto.ResourceOriginLabel, mesh_proto.ResourceOriginZone),
))
}
```
We still can't prefilter in Sync using only `kuma.io/zone` label. The very first Sync is going to fail with `Resource already exists` and required labels are never set on Global.
That's why for zones that don't support hashSuffixes we have to prefilter using prefixes.  
> fix(kuma-cp): global upgrade

- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
- app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
- deployments/charts/kuma/crds/kuma.io_meshmetrics.yaml
- docs/generated/openapi.yaml
- docs/generated/raw/crds/kuma.io_meshmetrics.yaml
- pkg/plugins/policies/meshmetric/api/v1alpha1/meshmetric.go
- pkg/plugins/policies/meshmetric/api/v1alpha1/schema.yaml
- pkg/plugins/policies/meshmetric/api/v1alpha1/zz_generated.deepcopy.go
- pkg/plugins/policies/meshmetric/k8s/crd/kuma.io_meshmetrics.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/default.clusters.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/default.listeners.golden.yaml
rename used only to include unused and revert the logic
> feat(meshmetrics): rename used only to include unused 

- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/01.golden.yaml
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/01.policies.yaml
- pkg/plugins/policies/core/rules/rules.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/testdata/basic-gateway.gateway.listener.golden.yaml
This was introduced when implementing #8549
> fix(meshaccesslog): add back `from` support for gateways

- pkg/kds/global/components.go
- pkg/kds/mux/server.go
- pkg/kds/mux/session.go
- pkg/kds/util/client_id.go
> chore(kuma-cp): improve docs around KDS client-id/peerID

- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/no-cross-zone.gateway.clusters.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/no-cross-zone.gateway.endpoints.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/no-cross-zone.gateway.listeners.golden.yaml
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/no-cross-zone.gateway.routes.golden.yaml
> test(MeshLoadBalancingStrategy): add disable cross-zone MeshGateway case

- test/e2e_env/multizone/sync/sync.go
We need to check both sides in the same eventually block
Fix #8900
> test(e2e): remove flake on multizone sync test

- pkg/kds/util/client_id.go
> fix(kuma-cp): make metadata retrieve method public

- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin.go
- pkg/plugins/runtime/gateway/plugin.go
The issue here is that we were only looking at what the gateway plugin itself generated, not what MeshHTTPRoute generates. This makes it so that MeshHTTPRoute writes to the context like the gateway plugin does.
> fix(gateway): make MeshHTTPRoute-based routing available to plugins

- pkg/kds/mux/server.go
We were intentionally using the deprecated version but [the issue](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4576) seems to have been fixed by https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4577 which was released in `v0.46.1` which we're using
> chore(kds): stop using deprecated otelgrpc.UnaryServerInterceptor

- pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
> fix(meshtimeout): nil pointer with MeshGateway

- UPGRADE.md
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
- app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
- deployments/charts/kuma/crds/kuma.io_meshfaultinjections.yaml
- docs/generated/openapi.yaml
- docs/generated/raw/crds/kuma.io_meshfaultinjections.yaml
- pkg/core/validators/common_validators.go
- pkg/core/validators/messages.go
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/meshfaultinjection.go
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/schema.yaml
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/validator.go
- pkg/plugins/policies/meshfaultinjection/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshfaultinjection/k8s/crd/kuma.io_meshfaultinjections.yaml
- pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator.go
- pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/locality_aware.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/testdata/locality_aware_basic.endpoints.golden.yaml
- pkg/test/resources/validation.go
- pkg/xds/envoy/listeners/v3/util.go
- pkg/xds/envoy/listeners/v3/util_test.go
- MeshFaultInjection were not using SI notation for bandwidth (using m for Mega)
- Make error messages more coherent (use always "must" never "has to")
- When intOrString is a not a number don't validate ranges too
- MeshLocalityAwareLoadBalancing failoverthreshold was just ignoring string values
> fix(policy): improve validator messages, allow string failoverthreshold

- pkg/kds/status/status_sink.go
It fixes potential nil pointer excetion in `kuma_log.AddFieldsFromCtx` in `*zoneInsightSink.Start` method
- Related: https://github.com/kumahq/kuma/pull/7951
- It won't
- No tests
- It probably does
> fix(kuma-cp): assign `extensions` in `ZoneInsightSink` constructor

- .github/workflows/backport.yaml
> ci(github-actions/backport): add missing PR: write permissions

- pkg/metrics/store/store.go
- pkg/metrics/store/store_test.go
Resource Already Exist is considered conflict therefore we should add this to the existing metric.
> feat(metrics): add create conflicts to the metric

- .github/workflows/backport.yaml
> ci(github-actions/backport): move permissions section to job

- .github/workflows/backport.yaml
> ci(github-actions/backport): move contents: read permission to job

- pkg/kds/v2/client/zone_sync_test.go
- pkg/kds/v2/store/sync.go
> fix(kuma-cp): failure during the migration from non-federated to federated zone

- .circleci/config.yml
- go.mod
> chore(deps): update go from 1.21.5 to 1.21.6

- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go
> fix(gateway): make MeshTCPRoute-based routing available to plugins

- pkg/plugins/runtime/gateway/route/configurers.go
- pkg/plugins/runtime/gateway/route_table_generator.go
- pkg/plugins/runtime/gateway/testdata/http/external-service-without-default-traffic-permission.yaml
- pkg/plugins/runtime/gateway/testdata/https/external-service-without-default-traffic-permission.yaml
> fix(gateway): check if external service from context when no trafficpermission

- tools/releases/dockerfiles/kuma-init.Dockerfile
This way we have a little more insight into what's changing. See for example https://github.com/kumahq/kuma/pull/8965
> chore(deps): tag ubuntu image more explicitly

- pkg/kds/store/sync.go
- pkg/kds/v2/store/sync.go
Resource meta doesn't have creationTime after KDS sync so we can't call `r.GetMeta().GetCreationTime()`.
> fix(kuma-cp): set creationTime on KDS sync

- pkg/envoy/admin/kds_client.go
- pkg/envoy/admin/kds_client_test.go
- pkg/kds/service/server.go
This shouldn't change anything, it's just for internal documentation.
> chore(kuma-cp): introduce helper type for semantics

- .github/workflows/backport.yaml
It seems we have to have `contents: read` in both, top level and job to make it work
Remediates: https://github.com/kumahq/kuma/security/code-scanning/38
- https://github.com/kumahq/kuma/security/code-scanning/38
- It won't
- No tests
> ci(github-actions/backport): add back "permissions" top section

- mk/kind.mk
Fix `kind create cluster --config` argument value to refer to existing cluster.yaml file. Without this, `make kind/start` fails with `No kind clusters found. make: *** [mk/kind.mk:32: kind/start] Error 1` but actually, the issues is `ERROR: failed to create cluster: error reading file: open ./test/kind/cluster-kuma.yaml: no such file or directory` which isn’t shown due to a `--quiet` argument on the `kind create cluster` command.
See also https://github.com/kumahq/kuma/pull/8676.
> chore(mk): fix make kind/start

- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
> refactor(MeshAccessLog): use gateway plugin listener info

- mk/kind.mk
This reverts commit 184a7366ffb0f86389bbeceb24573eea6f2778d9. This broke CI on branches. We'll solve whatever #8676 broke separately.
> Revert "chore(mk): fix make kind/start (#8977)"

- mk/kind.mk
This reverts commit 184a7366ffb0f86389bbeceb24573eea6f2778d9 which broke CI on branches. We'll solve whatever #8676 broke separately.
> Revert "chore(mk): fix make kind/start (#8977)" (#9020)

- pkg/plugins/secrets/k8s/store.go
- pkg/plugins/secrets/k8s/store_test.go
While debugging I've noticed that secrets are returned in a random order. That caused meshContext to be updated all the time and caused higher CPU usage. I've added sorting for secrets on K8s so now Context should be stable 
> fix(kuma-cp): return sorted list of k8s secrets

- pkg/defaults/mesh/meshcircuitbreaker.go
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator.go
- pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshcircuitbreaker/plugin/xds/configurer.go
Revert validation but check for nil so we can set defaults 
> fix(meshcircuitbreaker): revert validator and check if config is empty

- pkg/core/bootstrap/bootstrap.go
- pkg/plugins/secrets/k8s/store.go
- pkg/plugins/secrets/k8s/store_test.go
SecretStore wasn't using a pagination store so there was a risk that resources might not be sorted. Changed SecretStore to use pagination store.
> fix(kuma-cp): use pagination store for secret store

- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/gateway-listener-different-hostnames-specific.clusters.golden.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/gateway-listener-different-hostnames-specific.endpoints.golden.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/gateway-listener-different-hostnames-specific.listeners.golden.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/gateway-listener-different-hostnames-specific.routes.golden.yaml
- pkg/plugins/runtime/gateway/filter_chain_generator.go
- pkg/plugins/runtime/gateway/generator.go
We shouldn't use the _route_ hostnames in the SNI level match. The SNI should match according to the listener hostnames and _then_ it should fail to match at the HTTP level.
See the diff between [the first and third commit.](https://github.com/kumahq/kuma/pull/9038/commits/1dc7df2cc766702c9649762fbeac96149c3d7f1a)
> fix(MeshHTTPRoute): generate better resources when using HTTPS

- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/basic-meshhttproute.gateway_cluster.golden.yaml
> test(MeshHealthCheck): add test with MeshGateway+MeshHTTPRoute

- pkg/api-server/inspect_endpoints.go
- pkg/plugins/policies/core/xds/meshroute/gateway.go
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/basic-meshhttproute.gateway_cluster.golden.yaml
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/basic.gateway_cluster.golden.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go
- pkg/plugins/runtime/gateway/generator.go
- pkg/plugins/runtime/gateway/plugin.go
> fix(routes): share logic between new route resources

- pkg/intercp/catalog/catalog.go
- pkg/intercp/catalog/catalog_test.go
- pkg/intercp/catalog/config_catalog.go
- pkg/intercp/catalog/heartbeat_component.go
- pkg/intercp/catalog/writer.go
- pkg/intercp/catalog/writer_test.go
This PR fixes ERROR logs and behavior of inter-cp on redeploy of CP.
Leader will replace itself in the catalog. Followers will log info instead of errors, so it looks more like this
```
2024-01-26T16:47:25.010Z	INFO	intercp.catalog.heartbeat	could not send a heartbeat to a leader. It's likely due to leader change	{"instanceId": "kuma-control-plane-68454686fc-2lwbg-0c21", "ready": true, "leaderAddress": "10.42.0.7", "cause": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.42.0.7:5683: connect: connection refused\""}
2024-01-26T16:47:30.013Z	INFO	intercp.catalog.heartbeat	leader is not yet present in the cluster. No heartbeat to send	{"instanceId": "kuma-control-plane-68454686fc-2lwbg-0c21", "ready": true}
2024-01-26T16:47:35.011Z …
```
> feat(intercp): drop leader on cp shutdown

- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/gateway.clusters.golden.yaml
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/gateway.endpoints.golden.yaml
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/gateway.listeners.golden.yaml
- pkg/plugins/runtime/gateway/filter_chain_generator.go
Depends on https://github.com/kumahq/kuma/pull/9043
> fix(MeshTCPRoute): handle per TLS listener routes

- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/config/plugins/runtime/universal/config.go
- pkg/config/plugins/runtime/universal/config_test.go
- pkg/config/plugins/runtime/universal/testdata/default-config.golden.yaml
- pkg/config/plugins/runtime/universal/testdata/invalid-config.input.yaml
- pkg/config/plugins/runtime/universal/testdata/valid-config.input.yaml
- pkg/plugins/runtime/universal/plugin.go
It allows to customize at which rate all VIPs should be re-computed for all meshes. The default is unchanged, 500ms
> feat(universal): add VIP_REFRESH_INTERVAL

- pkg/dns/metrics/metrics.go
- pkg/dns/vips_allocator.go
- pkg/dns/vips_allocator_test.go
- pkg/plugins/runtime/k8s/plugin.go
- pkg/plugins/runtime/universal/plugin.go
> feat(vip): record generation metrics

- SECURITY-INSIGHTS.yml
Following what @lahabana started on sbom and clomonitor
Clomonitor requires a SECURITY-INSIGHTS.yml
This is a first draft based https://github.com/ossf/security-insights-spec/blob/v1.0.0/specification.md and what I could find on the repository. 
I could not find a security mail adress. Is there any ?
> ci(ossf): create SECURITY-INSIGHTS.yml

- SECURITY-INSIGHTS.yml
> ci(SECURITY-INSIGHTS): correct typo

- pkg/plugins/policies/meshmetric/api/v1alpha1/validator.go
> fix: allow targeting meshgateway in meshmetric 

- test/e2e_env/kubernetes/gateway/delegated.go
- test/e2e_env/kubernetes/gateway/delegated_meshproxypatch.go
Add test for `MeshProxyPatch` targeting delegated gateway
- Relates to https://github.com/kumahq/kuma/issues/8746
-  It won't
- This PR introduces e2e test
- 🤔 
> test(e2e/MeshProxyPatch): add test for delegated gateway

- test/e2e_env/multizone/meshtimeout/meshtimeout.go
> chore(e2e): fix flake

- test/e2e_env/multizone/meshtimeout/meshtimeout.go
> chore(e2e): meshtimeout flake

- pkg/plugins/policies/core/xds/meshroute/gateway.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway.go
- pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
- pkg/plugins/runtime/gateway/filter_chain_generator.go
- pkg/plugins/runtime/gateway/generator.go
Not needed for release but good to have IMO in the branch
> refactor(gateway): avoid manual creation of envoy resource names

- .github/workflows/build-test-distribute.yaml
> ci(distribute/helm-charts): add missing GH_USER/GH_EMAIL env vars

- test/e2e_env/universal/auth/dp_auth.go
Retry without TrafficRoute does not trigger xds change. We need MeshRetry
> test(e2e): fix dp auth flake

- pkg/xds/generator/outbound_proxy_generator.go
- pkg/xds/generator/outbound_proxy_generator_test.go
> fix(kuma-cp): don't run outbound proxy generator when there is no TrafficRoute

- CONTRIBUTING.md
Adding digital contributor badge information
> docs(contributing): update CONTRIBUTING.md

- test/framework/deployments/kic/kubernetes.go
KIC is fetched from the internet. Increase the timeout to prevent long downloads of images
> test(e2e): increase KIC fetch timeout

- pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/testdata/apply.golden.yaml
- pkg/xds/generator/egress/testdata/05.mixed-services-with-custom-trafficpermissions.golden.yaml
- pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml
- pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
- test/e2e_env/kubernetes/externalservices/externalservices.go
- test/e2e_env/multizone/meshtrafficpermission/meshtrafficpermission.go
- test/e2e_env/multizone/trafficpermission/trafficpermission.go
- test/e2e_env/universal/gateway/gateway.go
- test/e2e_env/universal/meshtrafficpermission/meshtrafficpermission.go
- test/e2e_env/universal/mtls/mtls.go
- test/e2e_env/universal/trafficpermission/traffic_permission.go
This PR changes the default behavior on no TrafficPermission and no MeshTrafficPermission for HTTP apps. It fixes a flake that we have on CI.
mtls.go "should enforce traffic permissions" (the one that already has FlakeAttempts) test is flaking in a weird way. When we apply mTLS the traffic is blocked. When we add TrafficPermission/MeshTrafficPermission it starts working, then it fails for a couple of requests and then it's running fine after this. I'd rather debug this in separate PR.
> feat(MeshTrafficPermission): apply default deny

- .github/workflows/build-test-distribute.yaml
because parent project is timing out
> ci(distribute): prolong timeout on distribute

- tools/releases/version.sh
> chore(deps): upgrade envoy to v1.29.0

- pkg/plugins/runtime/k8s/controllers/pod_controller.go
- pkg/xds/sync/dataplane_watchdog.go
I noticed that we produce quite a lot of error logs on a simple namespace termination.
We should just ignore reconciliation if namespace is terminating. Kuberenetes errors out on modyfing objects when namespace is being terminated.
```
2024-02-02T14:31:55.590Z	ERROR	kube-manager	Reconciler error	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"demo-app-gateway-75fcbdc9f5-hdmsw","namespace":"kuma-demo"}, "namespace": "kuma-demo", "name": "demo-app-gateway-75fcbdc9f5-hdmsw", "reconcileID": "edb796aa-15b7-424f-944d-63614cb8480a", "error": "dataplanes.kuma.io \"demo-app-gateway-75fcbdc9f5-hdmsw\" is forbidden: unable to create new content in namespace kuma-demo because it is being terminated"}
```
Additionally, on delete namespace, Kubernetes deletes all …
> chore(kubernetes): better logs of namespace termination

- pkg/core/rest/errors/error_handler.go
- pkg/envoy/admin/kds_client.go
- pkg/intercp/envoyadmin/forwarding_kds_client.go
- pkg/intercp/envoyadmin/server.go
Global control-plane forwards admin requests to an instance of global cp which has a connection. In case other instance returns errors, these errors are not mapped correctly by the handler and might return not expected API code.
> fix(kuma-cp): return wrapped forward KDS client errors

- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/runtime/k8s/util/util.go
- test/e2e_env/kubernetes/gateway/delegated.go
- test/e2e_env/kubernetes/gateway/delegated/common.go
- test/e2e_env/kubernetes/gateway/delegated/meshcircuitbreaker.go
- test/e2e_env/kubernetes/gateway/delegated/meshproxypatch.go
- test/e2e_env/kubernetes/gateway/gateway.go
- test/e2e_env/kubernetes/gateway/utils.go
- MeshTCPRoute when applied to a MeshGateway would panic thus making it unusable. This fixes this and backfills e2e tests
- Refactor tests to make them easier to maintain
Fix #9154
> fix(MeshGateway): fix MeshTCPRoute on MeshGateway

- test/framework/k8s_controlplane.go
- test/framework/universal_cluster.go
Before we were doing `kumactl get dataplanes`.
but since #9175 this returns 404 when the default mesh doesn't exist. We have e2e tests where we skip the creation of the default mesh. We now use just `get meshes` so that this always works
> test(e2e): use `kumactl get meshes` to check on kuma health

- tools/releases/version.sh
> chore(deps): upgrade envoy to v1.29.1

- tools/releases/version.sh
> chore(deps): upgrade envoy to v1.28.1

- deployments/charts/kuma/templates/egress-pdb.yaml
- deployments/charts/kuma/templates/ingress-pdb.yaml
This PR fixes the PDB generated by Helm chart for Ingress and Egress.
Currently, the selector is always using "kuma" app label whereas it should use either "kuma" or "kong-mesh" depending on the kuma.name variable.
> fix(helm): use kuma name in ingress and egress pdb selectors

- tools/releases/version.sh
> chore(deps): upgrade envoy to v1.27.3

- tools/releases/version.sh
> chore(deps): upgrade envoy to v1.26.7

- pkg/config/multizone/multicluster.go
- pkg/core/managers/apis/mesh/mesh_manager_test.go
- pkg/core/managers/apis/mesh/mesh_validator.go
- pkg/plugins/resources/k8s/store.go
- pkg/plugins/resources/k8s/store_test.go
- test/e2e_env/multizone/sync/sync.go
Fix #9168
Introduce limit for mesh name to 63. This is a limit of a label in Kubernetes. Since attach policy to a mesh via label, there is no way to attach a policy if a mesh name is longer than 63 chars. Store `display-name` as annotation on Kubernetes to escape the limit of 63 chars.
Other labels already have a validation of 63 chars.
> fix(kuma-cp): prevent violating kubernetes label limit

- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
We were accidentally setting a status for Kuma.
> fix(gatewayapi): don't add HTTPRoute status if Kuma isn't the controller

- pkg/xds/server/v3/reconcile.go
We cannot log proxy object because it contains secrets. We also should not log and return error. It's either return error or log and return nil
> chore(logging): do not log proxy object

- pkg/plugins/policies/meshtcproute/api/v1alpha1/validator.go
- pkg/plugins/policies/meshtcproute/api/v1alpha1/validator_test.go
> fix(MeshTCPRoute): allow MeshGateway listener tags

- pkg/xds/context/mesh_context_builder.go
We cannot wrap the error because of how `core_store.IsResourceNotFound` works. Ideally, we should create a type for not found error, but that sounds like a big separate PR.
https://github.com/kumahq/kuma/blob/master/pkg/xds/context/aggregate_mesh_context.go#L31 
```
2024-02-13T08:55:34.339Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"","Name":"egress"}, "error": "could not aggregate mesh contexts: could not fetch mesh connectivity: Resource not found: type=\"Mesh\" name=\"connectivity\" mesh=\"\"", "errorVerbose": "Resource not found: type=\"Mesh\" name=\"connectivity\" mesh=\"\"\ncould not fetch mesh connectivity\ngithub.com/kumahq/kuma/pkg/xds/context.(*meshContextBuilder).BuildBaseMeshContextIfChanged\n\tgithub.com/kumahq/kuma/pkg/xds/context/mesh_ …
```
> chore(logging): ignore missing mesh in aggregate context

- pkg/plugins/resources/k8s/store.go
`mesh_controller` adds `k8s.kuma.io/mesh-defaults-generated` annotations to the default resources. Lately, we've changed a bit of labels/annotations logic and we were setting an empty annotation map instead of coping the existing one. Added a change that copies existing annotations.
> fix(kuma-cp): copy annotations when adding/update k8s object

- .github/workflows/auto-merge.yaml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/helm-release.yaml
- .github/workflows/pr-comments.yaml
- .github/workflows/release.yaml
- .github/workflows/update-docs.yaml
- .github/workflows/update-insecure-dependencies.yaml
Also fix helm-release for this code-scanning issues:
- https://github.com/kumahq/kuma/security/code-scanning/66
- https://github.com/kumahq/kuma/security/code-scanning/65
- https://github.com/kumahq/kuma/security/code-scanning/68
- https://github.com/kumahq/kuma/security/code-scanning/67
- https://github.com/kumahq/kuma/security/code-scanning/62
> ci(github): move to actions/create-github-app-token

- pkg/api-server/api_server_suite_test.go
- pkg/api-server/circuit_breaker_endpoints_test.go
- pkg/api-server/fault_injection_endpoints_test.go
- pkg/api-server/global_secret_endpoints_test.go
- pkg/api-server/health_check_endpoints_test.go
- pkg/api-server/resource_endpoints.go
- pkg/api-server/resource_endpoints_test.go
- pkg/api-server/secret_endpoints_test.go
- pkg/api-server/testdata/resource_400onNoOriginLabel.golden.json
- pkg/api-server/traffic_route_endpoints_test.go
- pkg/api-server/traffic_trace_endpoints_test.go
- pkg/core/resources/model/resource.go
- pkg/kds/context/context.go
- pkg/plugins/runtime/k8s/plugin.go
- pkg/plugins/runtime/k8s/webhooks/defaulter.go
- pkg/plugins/runtime/k8s/webhooks/defaulter_test.go
- pkg/plugins/runtime/k8s/webhooks/resourceadmissionchecker.go
- pkg/plugins/runtime/k8s/webhooks/validation.go
- pkg/plugins/runtime/k8s/webhooks/validation_test.go
- test/e2e/helm/kuma_helm_upgrade_multizone.go
The PR makes KDS sync rely on `kuma.io/origin: zone` label. But we still want `KUMA_MULTIZONE_ZONE_DISABLE_ORIGIN_LABEL_VALIDATION: true` to disable origin label validation. That's why the PR introduces a webhook that automatically adds `kuma.io/origin: zone` after the validation.
> fix(kuma-cp): kds sync on upgrade doubles the number of policies

- .github/workflows/release.yaml
In entreprise we need to switch this config around so expose it here to easily disable it
> ci(versions.yml): add new arg disabled by default

- .github/workflows/pr-comments.yaml
> ci(.github): properly set token in checkout action in PR comment workflow

- pkg/plugins/policies/core/matchers/dataplane.go
- pkg/plugins/policies/core/matchers/egress.go
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/fromrules/03.dataplane.yaml
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/fromrules/03.golden.yaml
- pkg/plugins/policies/core/matchers/testdata/matchedpolicies/fromrules/03.policies.yaml
- pkg/plugins/policies/core/rules/rules.go
- pkg/plugins/policies/core/rules/rules_test.go
- pkg/plugins/policies/core/rules/testdata/rules/from/mesh-gateway.golden.yaml
- pkg/plugins/policies/core/rules/testdata/rules/from/mesh-gateway.input.yaml
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/validator.go
- pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/validator_test.go
- test/e2e_env/kubernetes/gateway/mtls.go
When using `MeshGateway` as the `from.kind`, we didn't map it for subsets. Additionally, `MeshGateway` kind uses the name of a gateway, so to make it work with `MeshTrafficPermission` we need to map matched dataplanes to services. I didn't add support for `MeshGateway` for `to` because I think there is no reason to target `MeshGateway`s from the mesh. Also, the single-match policy (`MeshTrace`) has no support for it either.
The matching of the `MeshGateway` to services:
1. Find `MeshGateway` resource with the name provided in `from.name`
2. Get all selectors and for each create a new `targetRef` with tags from selector
3. Each `targetRef` map to subset
1st commit shows the failing unit test with `from.kind: MeshGateway`
2nd commit shows the change required to make it work and the changed …
> feat(meshtrafficpermission): support from MeshGateway

- .github/workflows/release.yaml
Otherwise multiple "release" simultaneous triggers will make the `create-pull-request` fail. See: https://github.com/kumahq/kuma/actions/workflows/release.yaml
> ci(release): add concurrency group

- .circleci/config.yml
- .github/workflows/build-test-distribute.yaml
- .github/workflows/e2e.yaml
- test/e2e_env/multizone/meshtimeout/meshtimeout.go
- test/e2e_env/multizone/sync/sync.go
- test/framework/config.go
The new implementation will be on by default so remove the logic where `KumaLegacyKDS == true`.
> test(e2e): remove legacy KDS job

- mk/k3d.mk
> ci(k3d): increase timeout for metallb deployment

- .github/workflows/build-test-distribute.yaml
- .github/workflows/check.yaml
We encountered multiple times that 10 minutes was not enough (i.e. [1](https://github.com/kumahq/kuma/actions/runs/8001175106/job/21851878049), [2](https://github.com/kumahq/kuma/actions/runs/7970557081/job/21758384360), [3](https://github.com/kumahq/kuma/actions/runs/7970158016/job/21757220657)). I also fixed `synchronized` to `synchronize which is correct pull_request event type for "Lint PRs" workflow.
- It won't
- No tests
> ci(gh-action/check): increase check job timeout to 15 minutes

- pkg/plugins/policies/meshtimeout/plugin/testdata/outbound_listener_with_different_timeouts_per_route.yaml
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
While implementing MeshRetry I've noticed that MeshTimeout policy is not applied on MeshHTTPRoute. After debugging I found out that the issue was the wrong value of the name of routes in test.
> test(meshtimeout): fix test route matching

- .github/workflows/e2e.yaml
- mk/test.mk
> ci(e2e): upload junit results to gh artifacts

- mk/kind.mk
> chore(kind): change deploy/kuma to wait for mesh to be present

- .github/workflows/e2e.yaml
- mk/test.mk
This reverts commit d94a6865d24480960663ee67a52fdd8914543943.
There is need to figure out better names, which will appear in following up PRs, and to fix CI on KM I'm temporarily reverting this change.
> Revert "ci(e2e): upload junit results to gh artifacts (#9354)"

- test/e2e_env/kubernetes/gateway/delegated/meshproxypatch.go
- test/e2e_env/multizone/meshhttproute/test.go
- test/e2e_env/multizone/resilience/resilience_multizone_universal_postgres.go
- test/e2e_env/universal/reachableservices/reachableservices.go
Following our earlier decision, I'm disabling flaking tests. When amount of disabled tests because of flakes exceed 10, we should stop other work and focus on fixing flakes.
- https://github.com/kumahq/kuma/issues/9348
- https://github.com/kumahq/kuma/issues/9346
- https://github.com/kumahq/kuma/issues/9345
- https://github.com/kumahq/kuma/issues/9349
- It won't
- 🤔 
> ci(e2e): disable flaking tests

- app/kuma-dp/pkg/dataplane/meshmetrics/component.go
- app/kuma-dp/pkg/dataplane/metrics/server.go
- app/kuma-dp/pkg/dataplane/metrics/server_test.go
- pkg/plugins/policies/meshmetric/api/v1alpha1/validator_test.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/basic.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/default.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_prometheus.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/provided_tls.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/xds/dpp_config_configurer.go
- test/e2e_env/kubernetes/meshmetric/meshmetric.go
closes https://github.com/kumahq/kuma/issues/8926
> feat(meshmetric): usedonly filters

- pkg/api-server/testdata/resources/inspect/meshgateways/_rules/meshhttproute.golden.json
- pkg/plugins/policies/core/rules/rules.go
- pkg/plugins/policies/core/rules/testdata/rules/to/to-with-mesh-http-route.golden.yaml
- pkg/plugins/policies/core/rules/testdata/rules/to/to-with-mesh-http-route.input.yaml
When policy targets `MeshHTTPRoute` with `to.kind: Mesh` we are creating an artificial object that has a tag with a hashed value of a matcher from `MeshHTTPRoute`. By default, we are creating it as a `MeshServiceSubset` which by default has `kuma.io/service` with an empty value. That works well for policies that have `to.kind: MeshService/MeshServiceSubset` but not for `Mesh/MeshSubset`. Later we cannot match the subset because `kuma.io/service: ""` is set. This change checks the kind and sets the correct value.
The best to review by commits 
1st shows the issue
2nd implementation
3rd shows the file
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-i …
> fix(policy): don't set empty kuma.io service when using MeshHTTPRoute

- .github/workflows/build-test-distribute.yaml
> ci(github): correct build-test-distribute deps

- test/e2e_env/kubernetes/gateway/delegated.go
- test/e2e_env/kubernetes/gateway/delegated/meshhealthcheck.go
> test(e2e): add e2e test for MeshHealthCheck with delegated gateway

- .github/workflows/_e2e.yaml
> ci(github): use CIRCLECI_TOKEN instead of circleCIToken

- .github/workflows/_publish.yaml
The input was present but it wasn't set as an env var
> ci(github): restore push and full matrix in publish

- test/server/cmd/echo.go
There is currently no easy way to test MeshRetry policy with delegated gateway as current MeshRetry e2e tests are implemented on universal suites, but our framework only allows to deploy delegated gateway on kubernetes clusters.
This functionality allows test server to fail with 503 for the initial `n` request after which everything goes to normal.
- It won't
> test(framework/test-server): add option to succeed only after n requests

- .github/workflows/check.yaml
Pin `@commitlint/cli` and `@commitlint/config-conventional` versions for `Lint PRs` workflow
- It won't
- No tests
> ci(gh-actions): pin versions in commitlint deps for "Lint PRs" workflow

- docs/madr/decisions/036-internal-listeners.md
> docs(MADR): internal listener naming

- pkg/envoy/admin/kds_client.go
> feat(kds): add span for admin requests to zone CPs

- .github/workflows/_build.yaml
- .github/workflows/_publish.yaml
- .github/workflows/build-test-distribute.yaml
- .syft.yaml
> ci(github): add SBOM from project

- pkg/api-server/index_endpoints.go
> chore(api-server): remove duplicate error checking logic

- test/e2e_env/kubernetes/gateway/delegated.go
- test/e2e_env/kubernetes/gateway/delegated/meshretry.go
> test(e2e): add e2e test for MeshRetry with delegated gateway

- test/e2e_env/kubernetes/gateway/delegated.go
- test/e2e_env/kubernetes/gateway/delegated/meshhttproute.go
> test(e2e): add e2e test for MeshHTTPRoute with delegated gateway

- app/kuma-dp/pkg/dataplane/meshmetrics/component.go
- pkg/core/xds/sockets.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/basic.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/default.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_otel.clusters.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_otel.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_prometheus.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/openTelemetry.clusters.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/openTelemetry.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.clusters.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/provided_tls.listeners.golden.yaml
- pkg/plugins/policies/meshmetric/plugin/xds/dpp_config_configurer.go
- pkg/plugins/policies/meshmetric/plugin/xds/open_telemetry_configurer.go
- pkg/xds/envoy/names/resource_names.go
- test/e2e_env/kubernetes/meshmetric/meshmetric.go
- test/framework/deployments/otelcollector/deployment.go
- test/framework/deployments/otelcollector/deployment_kubernetes.go
> feat(policy): add possibility to configure multiple opentelemetry backends

- .github/workflows/build-test-distribute.yaml
This should speed up `make dev/tools` as the go cache will be present.
This is because otherwise make dev/tools pulls modules already present in the cache pulled by golangci-lint.
> ci(github): run golangci-lint before make dev/tools

- test/e2e_env/kubernetes/gateway/delegated.go
- test/e2e_env/kubernetes/gateway/delegated/common.go
- test/e2e_env/kubernetes/gateway/delegated/meshtrace.go
> test(e2e): add e2e test for MeshTrace with delegated gateway

- app/kuma-dp/pkg/dataplane/metrics/consts.go
- app/kuma-dp/pkg/dataplane/metrics/server.go
- app/kuma-dp/pkg/dataplane/metrics/server_test.go
- go.mod
- go.sum
- test/e2e_env/universal/observability/applications_metrics.go
This is needed because parent project requires `prometheus/common@v0.48.0` for another dependency
> chore(deps): bump prometheus/common to v0.48.0

- mk/test-container-structure.mk
Before it was running for supported arches so clearly it wasn't working
> ci(mk): test-containers should run on enabled archs

- test/e2e_env/kubernetes/gateway/delegated.go
- test/e2e_env/kubernetes/gateway/delegated/meshloadbalancingstrategy.go
> test(e2e): add e2e test for MeshLoadBalancingStrategy with delegated gateway

- test/framework/deployments/kic/kubernetes.go
- test/framework/k8s_cluster.go
When removing kic deployment we are removing a configured ingress namespace. There might be situation when this namespace might be already deleted during different test suite stage, so if doesn't exist, we don't have to fail during the deletion.
Updated kic deployment delete function to call `TraiggerDeleteNamespace` (which potentially might be more performant) instead of `DeleteNamespace`.
- It won't
> test(e2e/framework): don't fail when deleting non-existing k8s namespace

- .github/workflows/release.yaml
> ci(github): use a specific version of ci-tools

- .github/workflows/build-test-distribute.yaml
This is is required so that calls the make commands in the check job reflects FULL_MATRIX.
This was causing problems as make images/info/release/json wasn't setting everything
> ci(github): set env in check for FULL_MATRIX

- .github/workflows/check.yaml
> ci(actions): disable backport step temporarly

- test/e2e_env/kubernetes/gateway/delegated/meshmetric.go
This test is flaking, and there is slight chance it might be related with metrics not being refreshed in the expected time frame.
- There are no relevant issues
- It won't
> test(e2e/gateway/delegated): add refreshInterval to MeshMetric policy

- test/container-structure/kuma-init.yaml
When using nftables based iptables it fails on arm64 because of https://github.com/multiarch/qemu-user-static/issues/191
> test(container-structure): skip iptable test on kuma-init

- .github/workflows/_build_publish.yaml
We need https://github.com/Kong/public-shared-actions/pull/95 to make this work on self-hosted runners
> ci(github): use newer Kong/public-shared-actions

- .github/workflows/_build_publish.yaml
The condition was switched around
> ci(github): fix helm publish

- .github/workflows/_build_publish.yaml
- .github/workflows/_test.yaml
- .github/workflows/build-test-distribute.yaml
More work integrating https://github.com/kumahq/kuma/pull/9169
Now we should be signing usign cosign.
> ci(github): enable image signing

- .github/workflows/update-insecure-dependencies.yaml
Looks like 10 minutes is not enough https://github.com/kumahq/kuma/actions/runs/8166392754.
> chore(workflow): increase timeout for update-insecure-dependencies

- pkg/kds/context/context.go
On the parent project we can decide what to do with the metadata.
> feat(kds): add kds client version to outgoing context

- test/e2e_env/kubernetes/gateway/resources.go
- test/e2e_env/kubernetes/meshmetric/meshmetric.go
> test(e2e): improve a gateway test and skip a flaky meshmetric

- test/e2e_env/kubernetes/gateway/delegated.go
- test/e2e_env/kubernetes/gateway/delegated/meshtcproute.go
> test(e2e): add e2e test for MeshTCPRoute with delegated gateway

- test/e2e_env/kubernetes/meshmetric/meshmetric.go
> fix(e2e): skip meshmetric otel tests until we find why there are flaky

- tools/ci/update-vulnerable-dependencies.sh
> chore(workflow): add bash function to compare semvers

- pkg/plugins/runtime/k8s/controllers/pod_controller.go
- pkg/plugins/runtime/k8s/controllers/pod_controller_test.go
- pkg/plugins/runtime/k8s/plugin.go
> chore(k8s): cleanup unused struct field

- UPGRADE.md
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/dp-server/config.go
- pkg/config/loader_test.go
- pkg/core/bootstrap/autoconfig.go
- pkg/test/runtime/runtime.go
> chore(cleanup): remove deprecated dpServer.auth

- pkg/xds/generator/outbound_proxy_generator.go
- pkg/xds/generator/outbound_proxy_generator_test.go
- pkg/xds/generator/testdata/outbound-proxy/08.envoy.golden.yaml
- pkg/xds/generator/testdata/outbound-proxy/11.envoy.golden.yaml
Fix #9006 (at least for headless services).
I've rewritten the `buildAdditionalAddresses` function. It now just groups outbound by tags and puts addresses in proper order. It's O(n) as well. I also don't get why `08` test case was not squashed to additional addresses before.
> fix(xds): duplicated listeners

- .github/workflows/build-test-distribute.yaml
> ci(.github): add checks permissions for golangci-lint-action

- pkg/xds/topology/outbound.go
> refactor(xds): use maps.Clone

- mk/dependencies/clang-format.sh
- mk/dependencies/container-structure-test.sh
- mk/dependencies/deps.lock
- mk/dependencies/etcd.sh
- mk/dependencies/go-deps.sh
- mk/dependencies/golangci-lint.sh
- mk/dependencies/hadolint.sh
- mk/dependencies/helm.sh
- mk/dependencies/k3d.sh
- mk/dependencies/kind.sh
- mk/dependencies/kubebuilder.sh
- mk/dependencies/kubernetes.sh
- mk/dependencies/protoc.sh
- mk/dependencies/shellcheck.sh
- tools/ci/has_label.sh
- tools/ci/needs_backporting.sh
- tools/dev/install-dev-tools.sh
- tools/policy-gen/crd-extract-openapi.sh
- tools/policy-gen/generate-policy-config.sh
- tools/policy-gen/generate-policy-defaults.sh
- tools/policy-gen/generate-policy-helm.sh
- tools/policy-gen/generate-policy-import.sh
- tools/postgres/certs/generate.sh
- tools/postgres/wait-for-postgres.sh
We should use the user's preferred version of `bash` found by looking in `$PATH`.
> build(shell): use env in shebang

- .github/workflows/_build_publish.yaml
- .github/workflows/_provenance.yaml
- .github/workflows/_test.yaml
- .github/workflows/build-test-distribute.yaml
> ci(github): add provenance for binary artifacts

- test/e2e_env/kubernetes/gateway/delegated.go
By far the flakiest test atm afaict. If we decide to merge this I will open an issue.
- [xx] This will not break child repos: it doesn't hardcode values (.e.g "kumahq" as a image registry) and it will work on Windows, system specific functions like `syscall.Mkfifo` have equivalent implementation on the other OS --
> test(e2e): disable delegated gateway + MeshTCPRoute test

- pkg/xds/generator/outbound_proxy_generator.go
There was an error:
```
fatal error: concurrent map writes
goroutine 11569 [running]:
github.com/kumahq/kuma/pkg/xds/generator.buildOutboundsWithMultipleIPs(0xc00325f878, {0xc002dbca10, 0x2, 0x10?}, {0xc001d88230, 0x2, 0x307ee20?})
github.com/kumahq/kuma/pkg/xds/generator/outbound_proxy_generator.go:475 +0x253
```
> fix(kuma-cp): clone outbound tags

- .github/workflows/build-test-distribute.yaml
- meta_repo.yml
This aims to reduce queueing by running less things on PRs
You can always use `ci/run-build` to still run these jobs
> ci(github): don't build on PRs

- pkg/core/resources/apis/donothingresource/api/v1alpha1/zz_generated.resource.go
- pkg/core/resources/apis/meshservice/api/v1alpha1/zz_generated.resource.go
- tools/policy-gen/generator/cmd/core_resource.go
Without `IsPluginOriginated` the deserialization expects a `ProtoMessage`:
```
$ kumactl apply -f meshservice.yaml
panic: interface conversion: *v1alpha1.MeshService is not protoreflect.ProtoMessage: missing method ProtoReflect
goroutine 1 [running]:
github.com/kumahq/kuma/pkg/core/resources/model/rest/unversioned.(*Resource).UnmarshalJSON(0xc000086180, {0xc000925400, 0x3f, 0x200})
github.com/kumahq/kuma/pkg/core/resources/model/rest/unversioned/resource.go:72 +0xc9
encoding/json.(*decodeState).object(0xc000379068, {0x266e2c0?, 0xc0002ffa90?, 0xc000999408?})
encoding/json/decode.go:604 +0x6cc
encoding/json.(*decodeState).value(0xc000379068, {0x266e2c0?, 0xc0002ffa90?, 0xc000999458?})
encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).unmarshal(0xc000379068, {0x266e2c0?, …
```
> fix(kumactl): npe when creating new core resources

- pkg/mads/v1/reconcile/interfaces.go
- pkg/mads/v1/reconcile/reconciler.go
- pkg/mads/v1/reconcile/snapshot_generator.go
- pkg/mads/v1/reconcile/snapshot_generator_test.go
- pkg/mads/v1/service/components.go
- pkg/mads/v1/service_test.go
> fix(kuma-cp): fix long polling issues in mads

- test/e2e_env/kubernetes/gateway/delegated.go
[Flaking](https://github.com/kumahq/kuma/actions/runs/8271315103/job/22631253652#step:13:17066)
> test(e2e): disable delegated gateway + MeshCircuitBreaker test

- tools/releases/version.sh
> chore(deps): bump envoy version to v1.29.2

- .github/workflows/_e2e.yaml
- app/kuma-dp/cmd/run.go
- app/kuma-dp/pkg/dataplane/meshmetrics/component.go
> fix(kuma-dp): pass proper context in meshmetric component

- pkg/api-server/testdata/resources/inspect/meshgateways/_rules/meshgateway2.golden.json
- pkg/api-server/testdata/resources/inspect/meshgateways/_rules/meshgateway2.input.yaml
…eways
This test case is meant to be updated once selection in the matchers works correctly
ref #9589
> test(_rules): add test case with httproutes with listeners on meshgateways

- pkg/plugins/policies/core/rules/rules.go
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
Because we have `GatewayListenerTagsAllowed: true` in validation, we must take the policies from `ByListenerAndHostname`, listener-specific rules from one policy can be clobbered by another in `ByListener`, if the listeners share a port.
> fix(MeshHealthCheck): isolate MeshGateway config based on hostname

- app/kuma-dp/pkg/dataplane/meshmetrics/component.go
> fix(kuma-dp): fix starting infinite otel exporters in kuma dp

- app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
- deployments/charts/kuma/README.md
- deployments/charts/kuma/templates/_helpers.tpl
- deployments/charts/kuma/values.yaml
- docs/generated/raw/helm-values.yaml
> feat(k8s): add `experimental.sidecarContainers` to Helm chart

- pkg/mads/v1/generator/meshmetrics.go
- pkg/mads/v1/reconcile/snapshot_generator.go
- pkg/mads/v1/reconcile/snapshot_generator_test.go
- pkg/mads/v1/service/components.go
> fix(kuma-cp): fix for mads adding dataplanes with empty client id to snapshots for specific client id

- pkg/plugins/policies/meshmetric/api/v1alpha1/validator.go
- pkg/plugins/policies/meshmetric/api/v1alpha1/validator_test.go
> fix(policy): fix otel endpoint validation for meshmetric

- .github/workflows/_test.yaml
This should avoid master starving all runners.
> ci(github): limit max number of jobs on e2e test

- pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
According to https://github.com/kubernetes-sigs/gateway-api/pull/1880
> When empty, the redirect port MUST be derived using the following rules: //
> * If redirect scheme is not-empty, the redirect port MUST be the well-known
>   port associated with the redirect scheme. Specifically "http" to port 80
>   and "https" to port 443. If the redirect scheme does not have a
>   well-known port, the listener port of the Gateway SHOULD be used.
> * If redirect scheme is empty, the redirect port MUST be the Gateway
>   Listener port.
- It won't
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-req …
> fix(GatewayAPI): make MeshHTTPRoute conversion port redirect gapi conformant

- mk/test.mk
> ci(ginkgo): use newer ginkgo with better output

- pkg/plugins/policies/meshhttproute/api/v1alpha1/validation.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
MeshHTTPRoutes with MeshGateway as parentRefs can have rules without backendRefs, as long as the RequestRedirect filter is present. This is because the rule with the RequestRedirect filter acts like a shortcut, redirecting traffic without needing a backend service.
- It won't
> fix(MeshGateway/MeshHTTPRoute): allow no backendRefs when RequestRedirect filter present

- pkg/plugins/common/postgres/connection.go
> fix(pgx): use default MaxConnLifetimeJitter value for jitter

- test/e2e_env/kubernetes/gateway/delegated/meshmetric.go
- test/e2e_env/kubernetes/meshmetric/meshmetric.go
We merged couple of fixes to OTEL in MeshMetric: 
- https://github.com/kumahq/kuma/pull/9606
- https://github.com/kumahq/kuma/pull/9623
- https://github.com/kumahq/kuma/pull/9632
- https://github.com/kumahq/kuma/pull/9636
This should make otel tests more stable
> chore(e2e): re enable meshmetric with otel backend e2e tests

- app/kuma-cp/cmd/run.go
- go.mod
- go.sum
- pkg/api-server/auth_test.go
- pkg/api-server/server.go
- pkg/core/runtime/component/component.go
- pkg/diagnostics/components.go
- pkg/diagnostics/server.go
- pkg/dp-server/server/server.go
- pkg/intercp/server/server.go
- pkg/mads/server/server.go
- pkg/mads/server/server_test.go
- pkg/plugins/bootstrap/k8s/plugin.go
- pkg/test/kds/setup/server.go
- pkg/util/http/server/server.go
- Abstract some common http startup code.
- Add a ReadyComponent interface and implement it for api-server,dp-server,intercp and mads
- Use this readyComponent to return CP readiness in `/ready` probe
This should avoid sending requests to a server that's going down or sending requests too early when the server starts.
part of #1001
> chore(kuma-cp): have readiness probe be dependent of server health

- test/e2e_env/kubernetes/meshmetric/meshmetric.go
> chore(e2e): disable otel test

- pkg/plugins/policies/meshhttproute/xds/configurer.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
Matches based on a URL path prefix split by `/`. Matching is case-sensitive and done on a path element by element basis. A path element refers to the list of labels in the path split by the `/` separator. When specified, a trailing `/` is ignored.
For example, the paths `/abc`, `/abc/`, and `/abc/def` would all match the prefix `/abc`, but the path `/abcd` would not.
ref. https://github.com/kubernetes-sigs/gateway-api/blob/50091d071226d4ab2dbdb115ae65e27cf3fd5b85/apis/v1/httproute_types.go#L357-L367
Necessary as MehHTTPRoute validator won't allow value with trailing `/`
- It won't
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking …
> fix(GAPI/MeshHTTPRoute): trim "/" path match suffix when converting HTTPRoute

- app/kumactl/cmd/install/testdata/install-control-plane.zone-universal-on-k8s.golden.yaml
- deployments/charts/kuma/templates/_helpers.tpl
- pkg/plugins/runtime/k8s/controllers/testdata/04.dataplane.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/05.dataplane.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/24.dataplane.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/25.dataplane.yaml
- pkg/xds/generator/testdata/transparent-proxy/05.envoy.golden.yaml
In helm, when `Values.postgres.tls.mode is verifyNone or disable`, key `KUMA_STORE_POSTGRES_TLS_MODE` is not getting added, causing kuma-cp to take the default which is "disable".
Few testcases might fail, as with this change when `Values.postgres.tls.mode=disable`, `KUMA_STORE_POSTGRES_TLS_MODE=disable` will be added , where as earlier the env variable was omitted.
> fix(helm): missing postgres tls mode when it is set to verifyNone

- .github/workflows/_e2e.yaml
see disk space after e2e tests to see
> ci(github): don't free disk space in e2e tests

- .github/workflows/_e2e.yaml
Unfortunately we still need a lot of disk space
> ci(github): add back all the disk pruning

- .github/workflows/_build_publish.yaml
- .github/workflows/_provenance.yaml
- .github/workflows/build-test-distribute.yaml
> ci(github): add provenance for images

- tools/releases/dockerfiles/kuma-init.Dockerfile
> build(kuma-init): don't run try to run iptables when building kuma-init

- test/framework/k8s_cluster.go
Time and time again I'm seeing `no endpoints available for service \"kuma-control-plane\""` ([example](https://github.com/kumahq/kuma/actions/runs/8435507434/job/23102735001?pr=9624#step:13:1067)):
```
2024-03-26T13:06:54.0183958Z  2024-03-26T13:06:53Z logger.go:66: 2024-03-26T13:03:32.587Z	INFO	kds-delta-zone	error during callback received, sending NACK	{"kds-version": "v2", "err": "failed to create k8s resource: Internal error occurred: failed calling webhook \"mesh.defaulter.kuma-admission.kuma.io\": failed to call webhook: Post \"https://kuma-control-plane.kuma-system.svc:443/default-kuma-io-v1alpha1-mesh?timeout=10s\": no endpoints available for service \"kuma-control-plane\""...
```
this is repeated X times and eventually, after just a couple of seconds (5 in this case)
``` …
```
> ci(stability): wait for kuma service to be available

- mk/build.mk
- mk/check.mk
- mk/docker.mk
- tools/releases/dockerfiles/kuma-init.Dockerfile
- tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
> chore(kuma-init): revert iptables wrapper changes

- app/kuma-dp/pkg/dataplane/metrics/profiles.go
> chore(meshmetric): adjust logs

- app/kuma-dp/pkg/dataplane/envoy/envoy.go
- app/kuma-dp/pkg/dataplane/envoy/envoy_test.go
There's no reason to not immediately start GOAWAYing _all_ connections.
> feat(kuma-dp): use Envoy `--drain-strategy immediate`

- .github/workflows/_build_publish.yaml
image scanning is sometimes a little slower
> ci(github): increase image build timeout a limit

- mk/build.mk
- mk/check.mk
- mk/docker.mk
- tools/releases/dockerfiles/kuma-init.Dockerfile
- tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
This reverts commit 5711de29f750b0d2a234d61fe6f9ad4251e93aac.
> Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9728)"

- mk/build.mk
- mk/check.mk
- mk/docker.mk
- tools/releases/dockerfiles/kuma-init.Dockerfile
- tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
This reverts commit 59b9e60c49c3f91a214b35949e2be63fa62aff9a.
> Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9726)"

- mk/build.mk
- mk/check.mk
- mk/docker.mk
- tools/releases/dockerfiles/kuma-init.Dockerfile
- tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
This reverts commit 4da26461e66360e52e272a993b30e99fe6a1ca8e.
> Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9725)"

- mk/build.mk
- mk/check.mk
- mk/docker.mk
- tools/releases/dockerfiles/kuma-init.Dockerfile
- tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
This reverts commit 78a0ce054916418bb6a907a51169a8ea2503739b.
> Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9727)"

- mk/build.mk
- mk/check.mk
- mk/docker.mk
- tools/releases/dockerfiles/kuma-init.Dockerfile
- tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
This reverts commit 325df19f8bbaa633639404c1c01264646708618c.
> Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9724)"

- app/kuma-dp/pkg/dataplane/metrics/profiles.go
- app/kuma-dp/pkg/dataplane/metrics/testdata/profiles/dashboards.in
- app/kuma-dp/pkg/dataplane/metrics/testdata/profiles/exclude.yaml
- pkg/xds/bootstrap/template_v3.go
- pkg/xds/envoy/names/resource_names.go
- test/e2e_env/kubernetes/gateway/delegated/meshmetric.go
- test/e2e_env/kubernetes/meshmetric/meshmetric.go
> feat(meshmetric): filter out internal clusters

- .github/workflows/build-test-distribute.yaml
What was happening:
1. New push on PRs cancelled previous runs
2. Commits on branches would run in parallel
What happens now:
1. Unchanged from before
2. Commits on branches run CI one after the other
This should help streamline CI runs favouring the oldest merge first
> ci(github): tweak parallelism in build-test-distribute

- pkg/kds/global/components.go
- pkg/kds/zone/components.go
We are changing this because with context cancelled we will log it as error, that is irrelevant since we are logging it on info level later on
> fix(kds): skip error on context cancelled

- pkg/kds/global/components.go
> fix(kds): skip error log on context cancelled

- pkg/kds/server/components.go
- pkg/kds/status/status_tracker.go
- pkg/kds/v2/server/components.go
- pkg/plugins/runtime/gateway/gateway_route_generator_test.go
- pkg/plugins/runtime/gateway/listener_generator_test.go
- pkg/util/xds/stats_callbacks.go
- pkg/util/xds/stats_callbacks_test.go
- pkg/xds/server/components.go
- pkg/xds/server/v3/reconcile_test.go
This PR adds stats of number of clients per version. For now it only works with Delta KDS, but I added this to generic stats callbacks so in the future we can add this to other DSes if we want to.
I considered just adding a dimension to `_streams_active` metric, but streams active counts all DS streams, whereas this metric only counts streams with at least one DiscoveryRequest, because version is carried in metadata of request. This should be equal, but technically _can_ be different.
> feat(kds): stats of kds client versions

- .github/workflows/_provenance.yaml
Because of https://github.com/slsa-framework/slsa-github-generator/issues/3498 we can't use hash in the action so we use version instead
> ci(github): fix provenance to use version for action

- .github/workflows/_provenance.yaml
We were using a secret instead of a variable
> ci(github): correct DOCKER_USERNAME in provenance

- app/kuma-dp/cmd/run.go
- app/kuma-dp/pkg/dataplane/meshmetrics/component.go
- app/kuma-dp/pkg/dataplane/metrics/merge.go
closes: https://github.com/kumahq/kuma/issues/9738
Looks like it works as intended:
Querying via prometheus exposed via MeshMetric:
Querying directly:
It needs traffic split to get the hash into the clusters:
```
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
name: http-route-1
namespace: kuma-system
labels:
kuma.io/mesh: default
spec:
targetRef:
kind: MeshService
name: frontend_kuma-demo_svc_8080
to:
- targetRef:
kind: MeshService
name: backend_kuma-demo_svc_3001
rules:
- matches:
- path:
type: PathPrefix
value: /api
default:
backendRefs:
- kind: MeshServiceSubset
name: backend_kuma-demo_svc_3001
tags:
version: "1.0"
weight: 90
- kind: MeshServiceSubset
name: backend_kuma-demo_svc_3001
tags:
version: "2.0"
weight: 10
```
and I used this MeshMetric:
```
apiVersion: …
```
> feat(meshmetric): disable rollup of clusters

- mk/check.mk
- tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
When this target is being called from the projects which depends on Kuma, path to `tools/ci/update-vulnerable-dependencies/main.go` is different, so script needs to take into account this root path.
- It actually fixes child repos
- Manually tested locally
> ci(update-vulnerable-dependencies): pass KUMA_DIR to the script

- .github/workflows/build-test-distribute.yaml
There is no access to secrets on a PRs from forks, so to have a quick feedback, whole workflow will immediately fail when CI will detect `ci/force-publish` label on such PRs.
- It won't
- https://github.com/kumahq/kuma/actions/runs/8537662169/job/23388720406?pr=9801
> ci(check): fail CI wih `ci/force-publish` label on PRs from forks

- .github/workflows/build-test-distribute.yaml
When workflow was started as a result of `push` event, check was failing
- It won't
> ci(build-test-distribute): fix check of 'ci/force-push' label in PRs

- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/config/plugins/runtime/k8s/config.go
- pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml
- pkg/plugins/runtime/k8s/plugin.go
- pkg/plugins/runtime/k8s/webhooks/owner_reference_mutator.go
- pkg/plugins/runtime/k8s/webhooks/owner_reference_mutator_test.go
- pkg/plugins/runtime/k8s/webhooks/webhook_suite_test.go
Introduce a new config flag to not add ownerReference to resources.
This is useful when using argoCD which will refuse deleting resources if they have an ownerReference
Fix #9541
> feat(kubernetes): add possibility to not add owner reference

- .github/workflows/_build_publish.yaml
- .github/workflows/_provenance.yaml
- .github/workflows/build-test-distribute.yaml
> ci(github): add registry to provenance

- tools/releases/version.sh
> chore(deps): update Envoy to v1.26.8

- tools/releases/version.sh
> chore(deps): update Envoy to v1.28.2

- tools/releases/version.sh
> chore(deps): update Envoy to v1.27.4

- tools/releases/version.sh
> chore(deps): upgrade Envoy from 1.29.2 to 1.29.3

- docs/madr/decisions/041-resource-api-warnings.md
> docs(MADR): `warnings` field in the Resource API responses

- .gitignore
> chore(.gitignore): ignore justfile

- pkg/plugins/runtime/k8s/plugin.go
- pkg/plugins/runtime/k8s/webhooks/owner_reference_mutator.go
- pkg/plugins/runtime/k8s/webhooks/owner_reference_mutator_test.go
- pkg/plugins/runtime/k8s/webhooks/secret_validator.go
- pkg/plugins/runtime/k8s/webhooks/secret_validator_test.go
I investigated KDS NACKs in E2E tests and all of them are caused by mesh owner reference.
What is interesting is that we don't set Mesh owner reference on Universal (because we go directly thorough store, not resource manager), that's why the only NACKs we saw were from Kube zones.
Setting mesh owner reference caused the following problems:
* Policy is synced before mesh - fails because mesh is not present so we cannot set an owner
* Resource not found on delete - fails because resource was first deleted by owner mechanism
Additionally, I disabled secret delete validation on synced resources. This also caused a race when you delete Secret before Mesh. It was also only applied on Kube because of same reasons (store vs manager).
After this change, I see 0 NACKs on KDS in the multizone …
> feat(kuma-cp): do not set mesh owner reference on synced resources

- UPGRADE.md
and move previous section to the correct place
> docs(upgrade): document cluster merging

- pkg/kds/v2/server/components.go
- pkg/kds/v2/server/resource_retry_forcer.go
> fix(kuma-cp): log hashed `Node` instead of `Node.Id`

- pkg/dns/vips_allocator.go
- pkg/dns/vips_allocator_test.go
- test/e2e_env/kubernetes/inspect/inspect.go
Instead of https://github.com/kumahq/kuma/pull/9896
Do not include serviceless pods into vips list. Those are not adressable anyways, so we can save unnecessary XDS changes.
> perf(k8s): ignore serviceless pods from vips list

- pkg/core/alias.go
- pkg/core/signals.go
- pkg/core/signals_windows.go
> chore(kuma-cp): define fake USR2 signal for windows

- api/openapi/specs/api.yaml
- api/openapi/types/zz_generated.api.go
- docs/generated/openapi.yaml
- docs/madr/decisions/040-transition-to-new-policies.md
- pkg/api-server/resource_endpoints.go
- pkg/api-server/testdata/resources/inspect/dataplanes/_rules/proxyconfig_shadow-true_diff.golden.json
Previously the following invariant took place in the `_config` endpoint:
```
${response.diff} apply to ${response.xds} results in ${current_proxy_config}
```
this PR changes the invariant to:
```
${response.diff} apply to ${current_proxy_config} results in ${response.xds}
```
that way users see a list of changes that are going to be applied to current configs if they switch "shadow" mode to normal one.
> fix(kuma-cp): change the "direction" of the diff in inspect shadow responses

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
- deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
In multi-zone environments when Gateway was being converted to MeshGateway, it was missing `kuma.io/origin: zone` label, which was causing it not bying synced to global. Adding MeshGateways to defaulter mutating webhook seems to be safe way to solve this issue.
- Closes: https://github.com/kumahq/kuma/issues/9916
- It won't
- Manually tested on local k3d cluster
> fix(GAPI): add missing origin label for MeshGateway converted from Gateway

- app/kumactl/cmd/install/testdata/install-demo.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-demo.overrides.golden.yaml
- app/kumactl/data/install/k8s/demo/gateway.yaml
It's deprecated to use kuma.io/service tag in MeshGatewayInstance
> chore(demo): remove tags from meshgatewayinstance

- .github/workflows/update-insecure-dependencies.yaml
osv is timing out in parent project - it passes locally but takes a bit more time. Let's try to update this and see if this helps 
> ci(github): update osv scanner

- deployments/charts/kuma/templates/cni-rbac.yaml
fixes https://github.com/kumahq/kuma/issues/9655
- https://github.com/kumahq/kuma/issues/9655
- Confirmed
- Tested manually
- Added
- No need
- No need
> fix(kuma-cni): fix the subject namespace reference in Helm Chart

- test/e2e/helm/kuma_helm_upgrade_multizone.go
We changed `version.yaml`. No we upgrade from version that has default mesh timeout for dpps and gateway. Then if we added a synced one, it's 3, not 1. 
> test(e2e): fix number of policies on upgrade

- pkg/core/plugins/interfaces.go
- pkg/plugins/policies/core/matchers/egress.go
- pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin.go
- pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go
I don't know yet if we need to introduce a JSONPatch for ZoneEgress (scale-wise it's not great as it requires all resources in all meshes), but we hundred percent shouldn't take into account shadow policies when building ZoneEgress config.
> fix(kuma-cp): ignore shadow policies on ZoneEgress

- test/e2e_env/multizone/resilience/resilience_multizone_universal_postgres.go
We adjusted this in `test/e2e/resilience` for the new exponential backoff, but not in `test/e2e_env/multizone/resilience`. I noticed that it flaked.
> test(e2e): adjust backoff for resilience tests

- test/e2e_env/kubernetes/gateway/delegated/meshcircuitbreaker.go
- test/e2e_env/kubernetes/gateway/delegated/meshloadbalancingstrategy.go
- test/e2e_env/kubernetes/gateway/delegated/meshmetric.go
- test/e2e_env/kubernetes/gateway/delegated/meshproxypatch.go
- test/e2e_env/kubernetes/gateway/delegated/meshretry.go
- test/e2e_env/kubernetes/gateway/delegated/meshtimeout.go
- test/e2e_env/kubernetes/gateway/delegated/meshtrace.go
Some policies have the same name but are in different meshes. That might cause one policy to override another because all are applied in the same namespace. This might cause tests to be flaky. Added suffix to resource names for delegated tests.
> chore(e2e): added suffix to e2e test resource delegated

- .github/workflows/update-insecure-dependencies.yaml
- tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
Need to pass additional arg in parent project.
> ci(update): make it possible to pass additional options to osv-scanner

- .golangci.yml
- app/kumactl/pkg/output/table/printer.go
- go.mod
- pkg/core/runtime/runtime.go
Replace errors.Join instead of github.com/hashicorp/go-multierror . It avoid using hashicorp dependencies. 
> chore(deps): use `errors.Join` instead of `github.com/hashicorp/go-multierror`

- pkg/core/rest/errors/error_handler.go
> feat(api-server): add errors to trace spans

- .github/workflows/_build_publish.yaml
It's bringing complexity and not improving things much
> ci(github): don't do targetSpecific go mod caching

- test/e2e_env/kubernetes/gateway/delegated.go
- test/e2e_env/kubernetes/gateway/delegated/meshproxypatch.go
- test/e2e_env/kubernetes/gateway/delegated/meshtcproute.go
@lukidzi found why we had so many flakes in e2e tests
https://github.com/kumahq/kuma/pull/9937
With this change, we can reenable MeshProxyPatch (it was a name conflict). Fix #9378 Fix #9348.
As well as circuit breaker (there was no issue for it).
Added ci/run-full-matrix to run this a bunch of times before we merge.
> test(e2e): enable skipped delegated gateway tests

- pkg/plugins/runtime/k8s/controllers/gatewayapi/common/common.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
Specifying `kuma.io/service` tag for `MeshGatewayInstance` is deprecated, so we shouldn't be use it when converting Gateway API resources to our internal ones.
Specifying `kuma.io/mesh` as an annotation is also deprecated, so I changed it to label in conversion to `MeshGatewayInstance`
- It won't
- Manually tested on local k3d cluster
> chore(GAPI): move from deprecated behavior

- test/framework/k8s_cluster.go
> test(framework): add back wait for kuma service

- test/e2e_env/kubernetes/gateway/gatewayapi.go
GAPI test sometimes flakes with "could not get a LoadBalancer IP of the Gateway".
We don't have enough information to debug what's going on. Let's start with pods, services, gateways.
> test(e2e): add debug info to gateway api test

- pkg/intercp/catalog/catalog.go
- pkg/intercp/envoyadmin/forwarding_kds_client.go
Adds the not found instance ID to the error.
> refactor(kds): reduce duplication in forwarding client, improve error

- deployments/charts/kuma/templates/gateway-class.yaml
> fix(helm): include GatewayClass only if installing a zone CP in Kubernetes mode

- .circleci/config.yml
- .github/workflows/_e2e.yaml
- test/e2e_env/kubernetes/connectivity/headless_services.go
- test/e2e_env/kubernetes/gateway/gatewayapi.go
- test/e2e_env/multizone/connectivity/connectivity.go
- test/e2e_env/universal/grpc/grpc.go
- test/framework/config.go
- test/framework/debug.go
- test/framework/ginkgo.go
A new strategy to help us debug flakes.
One of the problem with flakes is that we don't have enough information. In case of failure, we should preserve as much as we can. I introduced a new block that we could add to every test
```
AfterEachFailure(func() {
DebugKube(kubernetes.Cluster, meshName, namespace)
})
```
Then we can gradually add more stuff to the implementation.
I only added one invocation of it as an example. If we accept this PR, I'll add it to all tests.
We need this in each test because we need to execute it before the test cleans up namespace and mesh.
We already have CP logs after the whole suite fails, no need to print this again.
[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull- …
> test(e2e): add debug information on failure

- tools/releases/version.sh
> chore(deps): upgrade Envoy to version 1.28.3

- tools/releases/version.sh
> chore(deps): upgrade Envoy to version 1.29.4

- tools/releases/version.sh
> chore(deps): upgrade Envoy version to 1.29.4

- pkg/util/xds/stats_callbacks.go
> feat(metrics): add error type to nack metric

- pkg/transparentproxy/iptables/builder/builder.go
- pkg/transparentproxy/iptables/builder/builder_restore.go
Because of the construction of the log line, where everything was located at the same line, we were not able to figure out at the beginnig of the log if it'll be successfull or not, so everything was logged in stderr. It's wrong when you have a monitoring set to watch stderr. I changed it so now the same information is placed in multiple lines and only failure is send to stderr.
Examples:
```
* nat
-N KUMA_MESH_INBOUND
-N KUMA_MESH_OUTBOUND
-N KUMA_MESH_INBOUND_REDIRECT
-N KUMA_MESH_OUTBOUND_REDIRECT
-A PREROUTING -p tcp -j KUMA_MESH_INBOUND
-A OUTPUT -p tcp -j KUMA_MESH_OUTBOUND
-A KUMA_MESH_INBOUND -p tcp -j KUMA_MESH_INBOUND_REDIRECT
-A KUMA_MESH_OUTBOUND -s 127.0.0.6/32 -o lo -j RETURN
-A KUMA_MESH_OUTBOUND -p tcp -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 5678 -j …
```
> fix(transparent-proxy): stop logging all to stderr when installing tproxy

- test/framework/debug.go
all is not really all. This PR adds more stuff (kuma and gapi resources)
> test(e2e): add gapi resources to kube debug

- pkg/kds/mux/zone_sync.go
These shouldn't behave differently here.
> fix(kds): make error handling similar between GlobalToZoneSync and ZoneToGlobalSync

- .github/workflows/release.yaml
- mk/docs.mk
This is needed for LTS versions
> ci(github): bump ci-tools to v0.11.0

- docs/madr/decisions/041-meshservice-kubernetes-ux.md
> docs(MADR): add Kubernetes UX for `MeshService`

- test/e2e_env/multizone/connectivity/cni_v2_ipv6_gateway.go
- test/e2e_env/multizone/externalservices/externalservices_multizone_universal.go
- test/e2e_env/multizone/gateway/cross-mesh.go
- test/e2e_env/multizone/gateway/gateway.go
- test/e2e_env/multizone/healthcheck/healthcheck.go
- test/e2e_env/multizone/inbound_communication/inbound_passthrough.go
- test/e2e_env/multizone/inbound_communication/inbound_passthrough_disabled.go
- test/e2e_env/multizone/inspect/inspect.go
- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid.go
- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_egress.go
- test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_gateway.go
- test/e2e_env/multizone/localityawarelb/locality_multizone_hybrid.go
- test/e2e_env/multizone/localityawarelb/meshloadbalancingstrategy.go
- test/e2e_env/multizone/meshhttproute/test.go
- test/e2e_env/multizone/meshtcproute/test.go
- test/e2e_env/multizone/meshtimeout/meshtimeout.go
- test/e2e_env/multizone/meshtrafficpermission/meshtrafficpermission.go
- test/e2e_env/multizone/ownership/ownership.go
- test/e2e_env/multizone/resilience/resilience_multizone_universal.go
- test/e2e_env/multizone/resilience/resilience_multizone_universal_postgres.go
- test/e2e_env/multizone/sync/sync.go
- test/e2e_env/multizone/sync/sync_legacy.go
- test/e2e_env/multizone/trafficpermission/trafficpermission.go
- test/e2e_env/multizone/trafficroute/trafficroute.go
- test/e2e_env/multizone/virtualoutbound/virtualoutbound.go
- test/e2e_env/multizone/zonedisable/zone_disable.go
- test/e2e_env/multizone/zoneegress/internal_services.go
> test(e2e): add debug to all multizone tests

- pkg/plugins/runtime/k8s/controllers/gateway_converter.go
- pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
Fix https://github.com/kumahq/kuma/issues/10072
As @Icarus9913 noticed in his PR https://github.com/kumahq/kuma/pull/10073 we end up with `kuma.io/tags: "null"` which we then unmarshal to map and try to set value to nil map.
Why do we end up with `kuma.io/tags: "null"`?
It's because for gateway instance we now have "implicit" `kuma.io/service` tag. It should not be set by user. To handle this, we created a method called `resolveGatewayInstanceServiceTag` in `GatewayInstanceReconciler` which resolves this implicit tag. This however was only called in selector func of `SelectGateway`. If there was at least one gateway, we would resolve this, if not then we wouldn't. If gateway was missing, we would then go to `createOrUpdateDeployment` and write tags to an annotation. This is how ended up …
> fix(gateway): handle implicit kuma.io/service in pod annotation

- pkg/plugins/runtime/k8s/plugin_gateway.go
Existing check of presence for only `Gateway` resource is insufficient in situation when some (not all) of the Gateway API CRDs are missing (i.e. package with CRDs was installed before `ReferenceGrant` was added), which causes CP to start throwing lot of errors:
```
controller-runtime.source.EventHandler	if kind is a CRD, it should be installed before calling Start	{"kind": "ReferenceGrant.gateway.networking.k8s.io", "error": "no matches for kind \"ReferenceGrant\" in version \"gateway.networking.k8s.io/v1beta1\""}
```
This is the simplest solution as we could also verify if `ReferenceGrant` is present, and if not to disable cross-mesh references, but it would be unnecesarily complex, especially in situation when Gateway API is GA and contains `ReferenceGrant` in `v1`.
Closes: …
> fix(gatewayapi): validate presence of all required Gateway API resources

- pkg/plugins/runtime/k8s/controllers/pod_status_controller.go
Fix jobs termination in case of CP missing update event (like CP restart etc.)
I tested it by applying this
```
apiVersion: batch/v1
kind: Job
metadata:
name: pi-2
namespace: kuma-demo
spec:
template:
spec:
containers:
- name: ubuntu
image: ubuntu:latest
command: [ "/bin/bash", "-c", "--" ]
args: [ "sleep 60" ]
restartPolicy: Never
backoffLimit: 4
```
then scaling CP down
```
kubectl scale deployments -n kuma-system kuma-control-plane --replicas=0
```
then up
```
kubectl scale deployments -n kuma-system kuma-control-plane --replicas=1
```
without this fix, the job stays running.
I'd love write E2E test for it, but it requires CP restart so it would land in non-env tests and it would be a time-consuming test.
[1]: …
> fix(jobs): jobs termination after CP restart

- deployments/charts/kuma/templates/pre-delete-webhooks.yaml
There's a possible case where we uninstall while we don't have webhooks installed. Added `--ignore-not-found` for the job not to fail in this case
Fix #10097
> fix(helm): don't fail when webhook doesn't exist

- tools/releases/version.sh
I'm getting `make dev/tools` installed in `release-2.7` on `master`. I don't see why this logic should require vX.Y.0 in particular.
> build(version): fix detection if latest patch isn't 0

- .github/workflows/merge-release-to-master.yaml
Enable workflow when we push a commit to any release branch. At this point we don't know which release branch is latest, but that's fine. Workflow will do nothing on push to older release branches.
> chore(gha): enable trigger for merge release to master

- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
- deployments/charts/kuma/crds/kuma.io_meshratelimits.yaml
- docs/generated/openapi.yaml
- docs/generated/raw/crds/kuma.io_meshratelimits.yaml
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/plugins/policies/meshratelimit/api/v1alpha1/meshratelimit.go
- pkg/plugins/policies/meshratelimit/api/v1alpha1/schema.yaml
- pkg/plugins/policies/meshratelimit/k8s/crd/kuma.io_meshratelimits.yaml
> chore(docs): fix typos

- test/framework/debug.go
We want to export any state available and not fail in the middle of an export
> test(e2e): never fail when running debug commands

- pkg/api-server/api_server_suite_test.go
- pkg/api-server/customization/customization_suite_test.go
- pkg/api-server/server.go
- pkg/core/rest/errors/error_handler.go
- pkg/test/api_server/api_server.go
- pkg/test/runtime/runtime.go
Currently, processing trace/span IDs before logging them (e.g., converting them to Datadog format) requires calling [`NewSpanLogValuesProcessorContext`](https://github.com/kumahq/kuma/blob/dd95f22e4e568ebeb899c187b107020a28703db5/pkg/plugins/extensions/logger/context.go#L19-L24) with the `runtime.Extensions()` context. However, this context isn't always available, particularly when [handling errors in REST endpoint handlers through `AddFieldsFromCtx`](https://github.com/kumahq/kuma/blob/dd95f22e4e568ebeb899c187b107020a28703db5/pkg/log/logger.go#L120). This inconsistency leads to the processing function being ignored.
- Pass `runtime.Extensions()` Context to [`HandleError`](https://github.com/kumahq/kuma/blob/8d2eaed06c21ad74b6806ce1db837f6610dcaaee/pkg/core/rest/errors/error_handler.go#L27 …
> fix(api-server): fix trace/span ID processing in logs

- pkg/plugins/runtime/gateway/filter_chain_generator.go
I think this was just overlooked. `LoadSecret` handles this so there's no reason not to support it, also tested manually just in case.
> fix(gateway): support `inlineString` in TLS certificates

- pkg/xds/sync/dataplane_watchdog.go
> fix(kuma-cp): cleanup generated egress certs

- .github/workflows/release.yaml
- mk/docs.mk
Use latest version of ci-tools which does the right thing
> ci(github): fix release binary check

- pkg/core/resources/apis/mesh/proxy_type.go
- pkg/test/xds/secrets.go
- pkg/xds/secrets/secrets.go
- pkg/xds/secrets/secrets_test.go
- pkg/xds/server/callbacks/dataplane_status_sink.go
- pkg/xds/sync/dataplane_watchdog.go
> fix(kuma-cp): index generated certs by proxy type, cleanup generated egress certs (backport of #10161, #10162)

- app/kumactl/cmd/export/export.go
- app/kumactl/pkg/resources/dataplane_overview_client.go
- app/kumactl/pkg/resources/dataplane_overview_client_test.go
- app/kumactl/pkg/resources/zone_overview_client.go
- app/kumactl/pkg/resources/zoneegressoverview_client.go
- app/kumactl/pkg/resources/zoneingress_overview_client.go
Stop using the older endpoints as there are better more coherent ones.
> chore(kumactl): use _overview endpoint for all entities

- pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
This is important if an HTTPRoute references a Service that didn't initially exist but then is created, we need to reconvert to MeshHTTPRoute and update status.
The PR adds an index on HTTPRoutes to the Services they care about to make it cheaper to queue reconciliation for HTTPRoutes when a Service changes.
> fix(gatewayapi): reconcile HTTPRoutes when relevant Services change

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
> chore(gatewayapi): actually log error listing Gateways

- app/cni/pkg/cni/injector_linux.go
- app/kumactl/cmd/install/install_transparent_proxy.go
- pkg/transparentproxy/config/config.go
- pkg/transparentproxy/iptables/builder/builder.go
I recommend doing review on commit per commit bases
We had `defaultConfig` and `DefaultConfig`, where latter was just calling former function.
This commit removes the unnecessary and hard-to-maintain `MergeConfigWithDefaults` function. Instead, we now use `DefaultConfig` directly and explicitly set modified values in commands like `kumactl install transparent-proxy` and CNI.
I've also streamlined the `transparentProxyArgs` structure by removing parameters that can be directly configured via the `Config` structure. This paves the way for potentially removing this intermediate structure altogether in the future, although that would involve more complex changes in flag parsing.
I think it's the logical place for this value as it's basically part of the configuration.
We don't have to cast …
> refactor(transparent-proxy): simplify more tproxy configuration

- .circleci/config.yml
- go.mod
> chore(deps): manually bump go to 1.21.10

- app/cni/pkg/cni/injector_linux.go
`Config` has both - inbound and outbound traffic redirection enabled by default (change introduced in https://github.com/kumahq/kuma/pull/10206), which is wrong in case of gateway so `GatewayIPV6CNIV2` tests were failing (ref. https://github.com/kumahq/kuma/actions/runs/9030440854/job/24815380164)
- It won't
> chore(cni): don't redirect inbound for gateway in CNI

- mk/run.mk
- test/dockerfiles/docker-compose.yaml
> ci(mk): fix postgres target

- mk/run.mk
`CP_STORE` was unconditionally overwritten to `memory` anyway so this didn't work.
> ci(mk): use `POSTGRES_STORE_TYPE` directly for `run/kuma-cp`

- pkg/kds/global/components.go
- pkg/kds/v2/store/sync.go
Now if there are `<zone-name>`-prefixes added to hashed versions (which can be reproduced as described below), they are removed initially and later resynced if the zone sends them again.
1. zone CP upgrade 2.6.2
2. global CP upgrade 2.6.2
3. see dangling resources
4. dangling resources still there
5. global CP upgrade this fix
6. resources gone
1. west CP upgrade 2.6.2
2. global CP upgrade 2.6.2
3. dangling resources from west in global and east
4. east CP upgrade 2.6.2
5. global CP upgrade this fix
6. resources gone from global and zones
1. west CP upgrade 2.6.2
2. east CP upgrade 2.6.2
3. global CP upgrade 2.6.2
4. dangling resources from both west and east in global and east/west
5. global CP upgrade this fix
6. resources gone from global and zones
- new ZoneIngresses come up fine …
> fix(kuma-cp): filter out old dangling zone resources in global

- .circleci/config.yml
```
The following packages have unmet dependencies:
git : Depends: git-man (< 1:2.43.2-.) but 1:2.45.1-0ppa1~ubuntu22.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.
Exited with code exit status 100
```
> ci(.circleci): update ubuntu image

- .circleci/config.yml
This isn't necessary.
This reverts commit 5a3501d16314352f7acfc0d8d60e37446615bd9f.
> ci(circleci): revert "ci(.circleci): update ubuntu image (#10252)"

- pkg/kds/global/components.go
- pkg/kds/v2/store/sync.go
> fix(kuma-cp): filter out old dangling zone resources in global (backport of #10245)

- .github/workflows/release.yaml
> chore(deps): upgrade ci-tools to v0.13.0

- .github/workflows/release.yaml
> chore(deps): upgrade ci-tools to v.0.13.1

- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/plugins/runtime/k8s/config.go
- pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml
xref https://github.com/kumahq/kuma-website/pull/1688/files#r1538921663
> feat(k8s): add kubernetes.io/hostname to default node labels to copy

- pkg/plugins/runtime/k8s/controllers/meshservice_controller.go
- pkg/plugins/runtime/k8s/controllers/meshservice_controller_test.go
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/01.meshservice.yaml
- pkg/plugins/runtime/k8s/metadata/annotations.go
- pkg/plugins/runtime/k8s/plugin.go
Also sets `k8s.kuma.io/service-name`
> feat(MeshService): add events when generating from Kubernetes Service

- docs/madr/decisions/050-mesh-passthrough.md
- docs/madr/decisions/051-mesh-passthrough.md
> docs(MADR): meshpassthrough design

- pkg/clusterid/reader.go
- pkg/core/runtime/builder.go
- pkg/core/runtime/reports/reports.go
- pkg/core/runtime/runtime.go
- pkg/kds/v2/client/zone_sync_test.go
- pkg/kds/zone/components_test.go
- pkg/test/kds/setup/client.go
- pkg/test/kds/setup/server.go
- pkg/test/runtime/runtime.go
- pkg/xds/server/callbacks/dataplane_status_tracker_test.go
- Remove `TestRuntime` as it was just unecessary complexity
- Add clusterCreationTime to easily figure when a cluster was first created (roughly)
- Add a zoneHashName to be able to easily uniquely identity the number of zones in a cluster
This should provide better metadata for understand usage
> feat(report): add more info in the report

- pkg/kds/context/context.go
- pkg/kds/global/components.go
This behaviour is not valid in Mink where we create zones before connecting them
xref https://github.com/Kong/kong-mesh/issues/5523
> feat(kds): add a flag to avoid creating a zone on connection on kds

- pkg/util/xds/stats_callbacks.go
- pkg/util/xds/stats_callbacks_test.go
We were updating metric in `OnStreamRequest` method, problem is that in case of Global this is run after sending discovery request to zone not after receiving one from zone. We need to update this metric in `OnStreamResponse` where we have original request from zone with metadata
> fix(kds): fix updating metric of kds client version

- pkg/plugins/runtime/k8s/controllers/meshservice_controller_test.go
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/02.meshservice.yaml
> test(MeshService): fix testdata references

- pkg/util/xds/stats_callbacks.go
- pkg/util/xds/stats_callbacks_test.go
this metric label can collide with automatically added label `version` which results with invalid version label looking like: `$cp-version,$client-version` for example when using datadog
> fix(kds): change version label for kds_clint_versions metric

- mk/check.mk
> feat(mk): add possibility to configure extra args for shellcheck

- pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
For example, in GAMMA, the parentRef can also be a Service.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> fix(GatewayAPI): only enqueue Gateway reconciliations from routes if parent is a Gateway

- pkg/plugins/runtime/k8s/controllers/meshservice_controller_test.go
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/01.meshservice.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/02.meshservice.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/03.meshservice.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/04.meshservice.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/05.meshservice.yaml
Allows checking the state of all MeshServices
> test(MeshService): improve golden files in controller

- app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml
- app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
- deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
- pkg/plugins/runtime/k8s/webhooks/gateway_instance_validator.go
Refer to #3799, we missed the change of the ValidatingWebhookConfiguration. Furthermore, with #9504 we deprecated kuma.io/service tag for the MeshGatewayInstance and we need to remove the tag validations.
close #10329 
> fix(gateway): run validating webhook on MeshGatewayInstance

- mk/check.mk
This stops searching if the directory has `.git` in it and otherwise returns only files.
> ci(check): improve find call for shellcheck

- app/kuma-cp/cmd/run.go
- docs/generated/raw/kuma-cp.yaml
- pkg/config/app/kuma-cp/config.go
- pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
- pkg/config/loader_test.go
- pkg/core/resources/apis/meshservice/vip/allocator.go
- pkg/core/resources/apis/meshservice/vip/allocator_test.go
- pkg/core/resources/apis/meshservice/vip/suite_test.go
- pkg/ipam/components.go
- pkg/test/resources/builders/meshservice_builder.go
- pkg/test/resources/samples/meshservice_samples.go
IPAM part of the implementation decided in [MADR 046](https://github.com/kumahq/kuma/blob/master/docs/madr/decisions/046-meshservice-hostname-vips.md).
Still unit tests. Will create e2e tests once we have hostname generator to actually check that we can communicate over DNS -> VIP.
> feat(meshservice): ipam

- .golangci.yml
- api/common/v1alpha1/ref.go
- app/kumactl/cmd/install/install_observability.go
I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.
see issues https://github.com/alingse/go-linter-runner/issues/1
and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9242968813/job/25426482280 
```
====================================================================================================
append to slice `orderedTags` with non-zero initialized length at https://github.com/kumahq/kuma/blob/master/api/common/v1alpha1/ref.go#L104:17
append to slice `combinedResources` with non-zero initialized length at https://github.com/kumahq/kuma/blob/master/app/kumactl/cmd/install/install_observability.go#L43:24
append to slice `combinedResources` with non-zero initialized length at …
```
> ci(lint): don't accidentally append to non-zero length slices

- app/kuma-dp/cmd/run.go
- app/kuma-dp/pkg/dataplane/certificate/cert.go
- app/kuma-dp/pkg/dataplane/envoy/envoy.go
- app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-0.golden.json
- app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-1.golden.json
- app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-2.golden.json
- app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-3.golden.json
- pkg/config/app/kuma-dp/config.go
- pkg/core/xds/metadata.go
- pkg/core/xds/metadata_test.go
- pkg/xds/bootstrap/generator.go
- pkg/xds/bootstrap/generator_test.go
- pkg/xds/bootstrap/parameters.go
- pkg/xds/bootstrap/template_v3.go
- pkg/xds/bootstrap/testdata/bootstrap.gateway.golden.yaml
- pkg/xds/bootstrap/testdata/bootstrap.k8s.golden.yaml
- pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml
- pkg/xds/bootstrap/testdata/bootstrap.universal.golden.yaml
- pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request.golden.yaml
- pkg/xds/bootstrap/testdata/generator.custom-config.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config-minimal-request.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config-token-path.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.golden.yaml
- pkg/xds/bootstrap/testdata/generator.default-config.kubernetes.golden.yaml
- pkg/xds/bootstrap/testdata/generator.gateway.golden.yaml
- pkg/xds/bootstrap/testdata/generator.metrics-config.kubernetes.golden.yaml
- pkg/xds/bootstrap/testdata/generator.system-cert-config.kubernetes.golden.yaml
- pkg/xds/bootstrap/types/bootstrap_request.go
xrel: https://github.com/kumahq/kuma/issues/10238
I added an option to propagate information about the default OS CA certificate in a bootstrap request from kuma-dp.
* a user can provide a path to the certificate when it's not a default one for the OS
* if the cert path is not provided we are scanning default paths based on the https://golang.org/src/crypto/x509/root_linux.go
* propagate the information in metadata
> feat(kuma-dp): add function to find default CA

- pkg/core/rest/errors/error_handler.go
We can't rely on the filter added in #10100 because we don't have the tenant at that point.
> fix(api-server): check for tenant just before logging

- pkg/kds/v2/server/resource_retry_forcer.go
- pkg/log/logger.go
> chore(kds): add tenantID to 'received NACK' log message

- pkg/xds/context/mesh_context_builder.go
- pkg/xds/topology/dns.go
This just takes the first VIP.
> feat(MeshService): use hostnames for DNS

- pkg/plugins/runtime/k8s/webhooks/injector/injector.go
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.34.golden.yaml
- pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.34.golden.yaml
fixes https://github.com/kumahq/kuma/issues/10366
- https://github.com/kumahq/kuma/issues/10366
- Confirmed
- No need
- No
- No
> feat(kuma-cni): add readOnlyRootFilesystem into securityContext of the container kuma-validation

- pkg/core/resources/apis/hostnamegenerator/hostname/generator.go
> fix(HostnameGenerator): don't exit component on error

- tools/releases/version.sh
> chore(deps): bump envoy version from 1.27.5 to 1.27.6

- tools/releases/version.sh
> chore(deps): bump envoy version from 1.29.4 to 1.29.5

- pkg/plugins/policies/core/xds/meshroute/clusters.go
- pkg/plugins/policies/core/xds/meshroute/listeners.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.clusters.golden.yaml
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.endpoints.golden.yaml
- pkg/test/xds/builders/context_builder.go
- pkg/xds/context/context.go
- pkg/xds/context/mesh_context_builder.go
- pkg/xds/envoy/clusters/configurers.go
- pkg/xds/envoy/clusters/v3/client_side_mtls_configurer.go
- pkg/xds/envoy/tls/v3/tls.go
- pkg/xds/envoy/tls/v3/tls_test.go
- pkg/xds/envoy/types.go
- pkg/xds/topology/outbound.go
- test/e2e_env/universal/meshservice/meshservice.go
Add support for mTLS by verifying that the destination's cert comes from one of the identities (`kuma.io/service` values) matched by this `MeshService`'s selector.
> feat(MeshService): support mTLS

- tools/releases/version.sh
> chore(deps): bump envoy version from 1.28.3 to 1.28.4

- .github/dependabot.yml
v0.12.0 introduced deadlock so just to be sure it won't be upgraded by mistake when new patch will be released
- it won't
- no tests
> chore(deps): ignore go-control-plane updates by dependabot

- pkg/plugins/resources/k8s/store.go
- pkg/plugins/runtime/k8s/webhooks/defaulter.go
- pkg/plugins/runtime/k8s/webhooks/defaulter_test.go
https://github.com/kumahq/kuma/pull/10361 introduced a bug that resulted in setting `kuma.io/display-name` as a label instead of an annotation. We can't set `kuma.io/display-name` as label, because it can be longer than 63 char.
> fix(kuma-cp): mistakenly setting 'kuma.io/display-name' as label

- app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go
It wasn't set during implementation 
> fix(kuma-dp): set systemCaPath when requesting config from kuma-cp

- pkg/plugins/policies/core/xds/meshroute/clusters.go
- pkg/plugins/policies/core/xds/meshroute/listeners.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.clusters.golden.yaml
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
- pkg/xds/envoy/clusters/configurers.go
- pkg/xds/envoy/clusters/v3/client_side_mtls_configurer.go
- pkg/xds/envoy/tls/sni.go
- pkg/xds/envoy/tls/sni_test.go
- pkg/xds/envoy/types.go
- pkg/xds/generator/egress/external_services_generator.go
- pkg/xds/generator/egress/internal_services_generator.go
- pkg/xds/generator/ingress_generator.go
- pkg/xds/generator/ingress_generator_test.go
- pkg/xds/generator/testdata/ingress/mesh-service.envoy.golden.yaml
- pkg/xds/generator/zoneproxy/destinations.go
- pkg/xds/generator/zoneproxy/generator.go
- pkg/xds/ingress/outbound.go
- pkg/xds/ingress/outbound_test.go
- pkg/xds/sync/ingress_proxy_builder.go
- pkg/xds/topology/outbound.go
Cross zone connectivity using synced MeshServices.
Required things to have E2E tests:
* Syncing identities
Things to improve:
* Splits
* Routing through egress
> feat(meshservice): cross-zone connectivity

- app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
- app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
- app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
- deployments/charts/kuma/crds/kuma.io_meshexternalservices.yaml
- docs/generated/raw/crds/kuma.io_meshexternalservices.yaml
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/meshexternalservice.go
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.input.yaml
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.output.yaml
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-without-extension-valid.input.yaml
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go
- pkg/core/resources/apis/meshexternalservice/api/v1alpha1/zz_generated.deepcopy.go
- pkg/core/resources/apis/meshexternalservice/k8s/crd/kuma.io_meshexternalservices.yaml
> feat(meshexternalservice): add servername

- pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
- pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go
- pkg/test/xds/builders/context_builder.go
- pkg/test/xds/samples/meshcontext_samples.go
* renamed `WithMesh` to `WithMeshBuilder` because we ar providing Builder
> test(refactor): change the name from WithMesh to WithMeshBuilder

- pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/plugin_test.go
> fix(meshpassthrough): fix build

- pkg/kds/context/context.go
While this is a "bug" it was not a problem for the current code, because we never update synced resource.
I only discovered this after I added a component that takes synced resource from cached resource manager and tries to update it. The meta was wrong, because it was replaced on the cached resource. 
xref https://github.com/kumahq/kuma/issues/9031
No need to backport.
> fix(kds): clone resource on update meta

- test/e2e/helm/e2e_suite_test.go
We won't be able to fix this test until we release a new patch releases for https://github.com/kumahq/kuma/issues/10463
> test(e2e): disable "Upgrade Multizone with Helm"

- pkg/xds/context/mesh_context_builder.go
Refer to #10421, we made a mistake in the past to use a no pointer variable which leads to a panic
close #10421
> fix(ZoneIngress): fix no pointer panic for advertised address resolving

- pkg/plugins/runtime/k8s/controllers/meshservice_controller.go
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/01.meshservice.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/02.meshservice.yaml
- pkg/plugins/runtime/k8s/controllers/testdata/meshservice/headless.meshservice.yaml
- pkg/plugins/runtime/k8s/metadata/annotations.go
> feat(MeshService): set kuma.io/managed-by for converted MeshServices
